### ISSUE TITLE
beef is not hooking

### ISSUE THREAD

**Issue by tiagosecurity** [beefproject/beef#1002]
When the browser tries to execute the hook.js the following exception is triggered: 

Uncaught SysntaxError: Unexpected token )

Such behavior occurred during the execution of hook.js script in the line 2079, so isn't possible too hook.

**Comment by joseph-kovacs** [comment]
Having the same issue, BeEF will not hook browsers when they visit my hook and worse it seems to crash/freeze (ctrl + c for instance will not let me stop) BeEF with all of this: 

[ 9:40:17][*] BeEF server started (press control+c to stop)
ArgumentError - invalid byte sequence in US-ASCII:
        /usr/local/rvm/gems/ruby-2.2.1/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `scan'
        /usr/local/rvm/gems/ruby-2.2.1/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `convert_input'
        /usr/local/rvm/gems/ruby-2.2.1/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
        /usr/local/rvm/gems/ruby-2.2.1/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
        /root/beef/core/main/handlers/modules/beefjs.rb:117:in `new'
        /root/beef/core/main/handlers/modules/beefjs.rb:117:in `build_beefjs!'
        /root/beef/core/main/handlers/hookedbrowsers.rb:50:in `block in <class:HookedBrowsers>'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1415:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1415:in `block in compile!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `[]'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `block (3 levels) in route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:960:in `route_eval'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `block (2 levels) in route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:981:in `block in process_route'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:979:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:979:in `process_route'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:943:in `block in route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:942:in `each'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:942:in `route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1053:in `block in dispatch!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1050:in `dispatch!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:878:in `block in call!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:878:in `call!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:864:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:172:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1947:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:86:in `block in pre_process'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:84:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:84:in `pre_process'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:53:in `process'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:39:in `receive_data'
        /usr/local/rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
        /usr/local/rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/backends/base.rb:73:in `start'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/server.rb:162:in `start'
        /root/beef/core/main/server.rb:127:in `start'
        beef:148:in `<main>'
ArgumentError - invalid byte sequence in US-ASCII:
        /usr/local/rvm/gems/ruby-2.2.1/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `scan'
        /usr/local/rvm/gems/ruby-2.2.1/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `convert_input'
        /usr/local/rvm/gems/ruby-2.2.1/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
        /usr/local/rvm/gems/ruby-2.2.1/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
        /root/beef/core/main/handlers/modules/beefjs.rb:117:in `new'
        /root/beef/core/main/handlers/modules/beefjs.rb:117:in `build_beefjs!'
        /root/beef/core/main/handlers/hookedbrowsers.rb:50:in `block in <class:HookedBrowsers>'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1415:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1415:in `block in compile!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `[]'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `block (3 levels) in route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:960:in `route_eval'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `block (2 levels) in route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:981:in `block in process_route'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:979:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:979:in `process_route'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:943:in `block in route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:942:in `each'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:942:in `route!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1053:in `block in dispatch!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1050:in `dispatch!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:878:in `block in call!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `block in invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1035:in `invoke'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:878:in `call!'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:864:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:172:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/sinatra-1.4.2/lib/sinatra/base.rb:1947:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
        /usr/local/rvm/gems/ruby-2.2.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:86:in `block in pre_process'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:84:in `catch'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:84:in `pre_process'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:53:in `process'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/connection.rb:39:in `receive_data'
        /usr/local/rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
        /usr/local/rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/backends/base.rb:73:in `start'
        /usr/local/rvm/gems/ruby-2.2.1/gems/thin-1.6.2/lib/thin/server.rb:162:in `start'
        /root/beef/core/main/server.rb:127:in `start'
        beef:148:in `<main>'


Anyone have any clues why BeEF freaks out when someone browsers off to the hook? It shouldn't be resource overload either. When it did this is was using no more than 18% of my memory.
