### ISSUE TITLE
Feature request: Link to host in /ui/panel

### ISSUE THREAD

**Issue by zeroSteiner** [beefproject/beef#1003]
It would be really useful for third party tools that use the BeEF API to be able to link to a specific host in the /ui/panel given a zombie's session id.

Something like: `http://localhost:3000/ui/panel?zombie_session=SESSIONID` which would open the UI and highlight the specified host and show it's information as if it had been clicked.  It would also be fantastic if the user is not logged in yet that they could still be redirected to the specific host post-auth.

**Comment by bcoles** [comment]
@zeroSteiner Three years on, this has finally be implemented.

A browser may be referenced like so:

* `http://beef.local:3000/ui/panel#id=<session>`

Unfortunately, the currently implementation does not allow the `#id=` to survive authentication. As such, the user must authenticate before using one of these links.

Also note that the `/ui/` portion of the URL is user-configurable. A "hardened" BeEF install should make use of a different path for the Admin UI (specified in the `beef.extension.admin_ui.base_path` configuration property in the Admin UI extension's [config.yaml](https://github.com/beefproject/beef/blob/master/extensions/admin_ui/config.yaml) configuration file).
