### ISSUE TITLE
Update DNS Unit/Integration Tests

### ISSUE THREAD

**Issue by soh-cah-toa** [beefproject/beef#1010]
The unit and integration tests for the DNS extension are currently disabled since they are still using the old DNS API. They need to be updated to make use of the new API.

I plan to return to this issue in the future. At the moment, there are bigger fish to fry - namely DNS tunneling - and have to put this on the back burner for the time being. If anyone feels they can handle this in the meantime, they are certainly free to do so.

**Comment by bcoles** [comment]
Blocked on #1253
