### ISSUE TITLE
Don't hardcode specific versions in Gemfile

### ISSUE THREAD

**Issue by rhertzog** [beefproject/beef#1025]
Hello, I'm trying to improve the beef-xss package for Kali and in the process I want to use system-wide ruby gems provided by proper debian packages. I packaged most of the required gems but when I do that I package the latest version of each gem (or keep the version already available in Kali, which on the contrary might be older than the one that you are requiring).

Please fix the Gemfile to avoid exact version requirements (like you do on eventmachine, sinatra, rack and now rubydns) and favor relationships that matches the reality of beef-xss requirements (i.e. >= a specific minimal version that is required). FWIW Kali still has evenmachine 0.12, rack 1.4.1, sinatra 1.3.2. Do you know if beef works with them?

Furthermore you have some "~>" relationship that imposes to use an older version. em-websocket for instance is locked to 0.3.X while we now have 0.5.1 in Kali. Would beef work with 0.5.1 ?

In general, it's best to assume that the code will continue to work with new versions of the gems unless you have prior experience with a specific gem breaking backwards compatibility all the time (or if the upstream author announced a clear versioning scheme reflecting the compatibility breaks).

**Comment by xntrik** [comment]
I also believe we should start shifting the Gemfile.lock into the distribution. I'm aware we ran into some issues with this in the past, but, my understanding of Bundler is that you're meant to commit the lock file too, as this is used to keep all the devs/environments using the *same* set of Gems. This is discussed in the top FAQ here http://bundler.io/v1.9/faq.html ..

**Comment by ioquatix** [comment]
RubyDNS 1.x is stable.

**Comment by frenchi** [comment]
+1 to commiting Gemfile.lock. That's what it's there for.

On Monday, 30 November 2015, Samuel Williams <notifications@github.com>
wrote:

> RubyDNS 1.x is stable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beefproject/beef/issues/1025#issuecomment-160589239>.
>


-- 
Sent from Gmail Mobile

**Comment by bcoles** [comment]
Gemfile.lock is now included with BeEF.

Several gems still make use of hardcoded versions:

* gem 'em-websocket', '~> 0.3.6' # WebSocket support
* #gem 'twitter', '>= 5.0.0' # Twitter Notifications extension
* gem 'rubyzip', '>= 1.0.0'
* gem 'rubydns', '0.7.0'     # DNS extension
* gem 'therubyracer', '~> 0.11.0beta1' # Windows support
* gem 'therubyracer', '0.11.3'   # Mac support
* gem 'rest-client', '~> 1.8.0'  # tests

**Comment by bcoles** [comment]
Closing this issue.

All gem version requirements now make use of `>=` with the following exceptions:

```ruby
# Required for Linux
if RUBY_PLATFORM.downcase.include?('linux')
  gem 'therubyracer', '~> 0.12.2', '<= 0.12.2'
end
```

```ruby
# DNS extension - limited to 0.x
# backwards-compatibility breaking changes in 1.x and again in 2.x
group :ext_dns do
  gem 'rubydns', '~> 0.7.3'
end
```

```ruby
# Rack 2.x is not supported yet. To be updated to 2.x, as per #1424
gem 'rack', '~> 1.6.5'
```
