### ISSUE TITLE
API Fire Error: invalid byte sequence in AdminUI

### ISSUE THREAD

**Issue by zeknox** [beefproject/beef#1026]
Running the latest version of beef. Installed all the dependencies using `bundle install`.  When starting up beef I get the following error in the console. 

<pre>
[19:49:00][!] API Fire Error: invalid byte sequence in US-ASCII in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>16}.mount_handler()
</pre>

When I navigate to the login portal at /ui/panel I get prompted with the beef logo but not the login prompt for username and password

**Comment by Sayny385** [comment]
same error please help when i type export LC_ALL=en_US.UTF-8 to fix error it gives another error bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

**Comment by bcoles** [comment]
@Sayny385 BeEF requires a UTF8 locale to print UTF8 characters.

If your system does not have a UTF-8 local you will be unable to print UTF-8 characters.

The error you're receiving - `cannot change locale (en_US.UTF-8)` - is an error from your system. Perhaps this will help:

https://askubuntu.com/questions/454260/how-to-solve-locale-problem
