### ISSUE TITLE
Beef Bundle Install Error

### ISSUE THREAD

**Issue by Beefuser12** [beefproject/beef#1031]
So when in the beef directory running bundle install I get this error...

c:\BeEF>bundle install
DL is deprecated, please use Fiddle
Fetching gem metadata from http://rubygems.org/.........
Fetching additional metadata from http://rubygems.org/..
Resolving dependencies...
Using addressable 2.3.6
Using ansi 1.4.3
Using daemons 1.1.9
Using data_objects 0.10.14
Using dm-core 1.2.1
Using dm-do-adapter 1.2.0
Using dm-migrations 1.2.0

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension
.

    C:/Ruby200-x64/bin/ruby.exe extconf.rb
checking for sqlite3.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby200-x64/bin/ruby
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/

Gem files will remain installed in C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/do_sq
lite3-0.10.14 for inspection.
Results logged to C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/do_sqlite3-0.10.14/ext
/do_sqlite3/gem_make.out
An error occurred while installing do_sqlite3 (0.10.14), and Bundler cannot
continue.
Make sure that `gem install do_sqlite3 -v '0.10.14'` succeeds before bundling.

Help?

**Comment by coldalfred** [comment]
http://stackoverflow.com/questions/421225/why-cant-i-install-the-sqlite-gem

There is the solution :)

**Comment by wadealcorn** [comment]
Thanks @coldalfred

**Comment by zirou30** [comment]
Thanks @coldalfred
