### ISSUE TITLE
BeEF control panel not showing in Kali

### ISSUE THREAD

**Issue by DrDinosaur** [beefproject/beef#1049]
I have the latest Kali version and packages. BeEF shows:
"Not Found

The requested URL was not found on this server.

Apache/2.2.3 (CentOS)"

at 127.0.0.1:3000/ui/panel

127.0.0.1:3000 shows the Apache 2 Test Page for CentOS. 

root@Kali:~# service beef-xss start
process already running.

I've waited a while and still nothing.

**Comment by theverygoodwebsite** [comment]
how do do you download beef in ubutu

**Comment by theverygoodwebsite** [comment]
or can you say how to download it in google cloud console

**Comment by theverygoodwebsite** [comment]
I have done this many times but still it is showing as the first picture and if you notice that there are another two URLs I also clicked that but still, it is showing like this
![Screenshot (52)](https://user-images.githubusercontent.com/99941387/154633702-2d2026c2-4957-4ef3-8122-492be6591385.png)
![Screenshot (52)](https://user-images.githubusercontent.com/99941387/154634059-d3774357-4f28-4f48-9fa8-653a6f144ad6.png)

**Comment by theverygoodwebsite** [comment]
how to check it

**Comment by theverygoodwebsite** [comment]
Hello anybody are you there can you please say me how to see this

**Comment by theverygoodwebsite** [comment]
Please

**Comment by theverygoodwebsite** [comment]
I really want to use BeEF

**Comment by theverygoodwebsite** [comment]
And also i want to educate my family and friends that these hacks happen all the time so that why I want to use beef

**Comment by NeoTheGuy187** [comment]
> And also i want to educate my family and friends that these hacks happen all the time so that why I want to use beef

You have to make sure your distribution is fully up to date sudo update, sudo upgrade, apt dist-upgrade, and once all is done you then need to kill beef if it’s running “service beef-xss stop. 

Then you want to ./install again once you cd beef, then make sure you don’t init by ./beef make sure you init with “service beef-xss start” then you can check the connection with netstat you should see it.

Then just type on the machine that is the server “127.0.0.1:3000/ui/panel” which points to the machine or type the private ip of the machine/server” 

If this doesn’t work then you need to ensure that everything is up to date and also as a rule of thumb if your program isn’t working you might need to do a simple restart.

Next you need to look up how to port scan a device on your network and see if that device has port 80 open and inject beEF with bettercap using a man in the middle attack, have fun.
