### ISSUE TITLE
Event logger - Browser issues and possible improvements

### ISSUE THREAD

**Issue by ohpe** [beefproject/beef#1055]
Hey guys, 
here there are some wrong behaviors for the event logger:
- _Chrome and friends_ : keys with the CTRL are not logged
- _Internet Explorer_ : using the CTRL it shows the message `User Copied/Pasted Text` but the content is empty
- _Opera_ : using the CTRL it has some encoding issues and thus no character is visible

Furthermore, I think that the event logger also needs to handle editing keys such as CR/Enter, backspace, delete and most of all TAB.

**Comment by ohpe** [comment]
Hi Wade, thank you for the proposal.
I'm not a ruby ninja but I can give it a try. Hope to push something useful as soon as I can.

**Comment by wadealcorn** [comment]
Thanks @ohpe. Did you have a chance to look into this?

**Comment by ohpe** [comment]
Yes @wadealcorn I started last week, I'm working on the extension of the logger.

**Comment by wadealcorn** [comment]
Great! Thanks!
