### ISSUE TITLE
Is there a mistake into the BeEF "INSTALL.txt" attached file ?

### ISSUE THREAD

**Issue by ghost** [beefproject/beef#1057]
Hello Sirs at Beefproject, 

I was following Your instructions from the "INSTALL.txt" attached file; I'm a MAC user, so I am following point N°4 (Prerequisites) and I need to install RVM and Ruby on my OSX,

but when launching the terminal command according to the first line suggested there, I get this result:

```
                                                   -bash: $: command not found
```

am I missing something ? Where's the glitch ?

Thank You, B.R.

**Comment by mansurabbas** [comment]
pls i install beef-xss normal procedure and it installed.But when i try to run it by "beef" it shows the following error :

Could not find nokogiri-1.8.1 in any of the sources
Run bundle install to install missing gems.

I saw answer to the solution in this wonderful and helping forum ( gem install nokogiri-1.8.1 --use-system-libraries and bundler -v and bundle install). It install nokogiri-1.8.1 and clone Gemfile in my /$HOME but still when i try to run by "beef" it still shows :

Could not find nokogiri-1.8.1 in any of the sources
Run bundle install to install missing gems

                        Pls help me, thank in advance.
