### ISSUE TITLE
Ability to export logs

### ISSUE THREAD

**Issue by xntrik** [beefproject/beef#1061]
Hey guys,

Saw someone asking for this on Twitter. Probably not too difficult. Probably just a new flag/parameter in the console extension.

"beefproject Once I hook a browser is there a way to export the logs and output of all commands for whole session?"

"beefproject If I can export is there a way to export the output for a specific browser if I have multiple browsers hooked?"

Both of these from Gh0stF0rce

**Comment by bcoles** [comment]
See the [RESTful API](https://github.com/beefproject/beef/wiki/BeEF-RESTful-API) and [RESTful API examples](https://github.com/beefproject/beef/tree/master/tools/rest_api_examples), specifically [export-logs](https://github.com/beefproject/beef/blob/master/tools/rest_api_examples/export-logs).
