### ISSUE TITLE
Add functionality to detect if the browser has changed IP addresses. 

### ISSUE THREAD

**Issue by wadealcorn** [beefproject/beef#1084]
When the IP address of the browser changes it should trigger the ARE. 

For example, a new IP address might suggest a new subnet so the port scan module could be triggered.

**Comment by xntrik** [comment]
There is logic that handles this event in the server.
https://github.com/beefproject/beef/blob/master/core/main/handlers/hookedbrowsers.rb#L62

**Comment by bcoles** [comment]
Are there any other event types which would warrant (re-)execution of one or more ARE rules?

The ARE currently presumes that all rules will be run only upon hook. I'm wondering whether it is worth re-architecting the ARE to support multiple event types, or whether `onhook` and `onipaddresschange` are likely the only valid events.
