### ISSUE TITLE
Distributed Cross-Site Request Timing

### ISSUE THREAD

**Issue by wadealcorn** [beefproject/beef#1085]
Add a distributed module to the framework that can be configured to perform distributed cross-site request timing attacks.

More information can be found here:
https://www.blackhat.com/presentations/bh-usa-07/Meer_and_Slaviero/Whitepaper/bh-usa-07-meer_and_slaviero-WP.pdf

**Comment by DeezyE** [comment]
Is this still relevant?

**Comment by bcoles** [comment]
Will not implement. Closing.
