### ISSUE TITLE
Interactive Shell Console no longer appears to start the back-end BeEF web server

### ISSUE THREAD

**Issue by xntrik** [beefproject/beef#1090]
I think I'm the only person in the universe starting beef with the -i flag, so I'll try and figure out what's going on.

**Comment by xntrik** [comment]
Appears to be related to the shift from ruby 1.9.3 -> 2.1.5 ..

**Comment by wadealcorn** [comment]
Any progress @xntrik? Should we close this?

**Comment by bcoles** [comment]
Confirmed broken with Ruby 2.1.5

**Comment by antisnatchor** [comment]
@xntrik did you had a chance to look into this?
Are you keen to write a BeEF blog post or at least a wiki page about how to use the console?

**Comment by auraltension** [comment]
+1 on this.

**Comment by auraltension** [comment]
I've tested this on ruby-1.9.3-p551 (works), 2.1.5 & 2.2.1 (don't work).

I am terrible with ruby so am without a clue of how to diagnose this further, but running through a debugger I can see errors that seem to be related to librex?  These trigger when trying to open a connection to the webserver host:port.

```
/home/user/.gem/gems/librex-0.0.999/lib/rex/job_container.rb:39: `superclass mismatch for class Tempfile' (TypeError)
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/debug.rb:829:in `excn_handle'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/debug.rb:883:in `trace_func'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/debug.rb:1085:in `block in <class:DEBUGGER__>'
        from /home/user/.gem/gems/librex-0.0.999/lib/rex/job_container.rb:39:in `ensure in block in start'
        from /home/user/.gem/gems/librex-0.0.999/lib/rex/job_container.rb:40:in `block in start'
        from /home/user/.gem/gems/librex-0.0.999/lib/rex/thread_factory.rb:29:in `call'
        from /home/user/.gem/gems/librex-0.0.999/lib/rex/thread_factory.rb:29:in `block in spawn'
/home/user/.gem/gems/librex-0.0.999/lib/rex/job_container.rb:39:          clean_proc.call(ctx)
```

**Comment by xntrik** [comment]
Hey guys, thought I'd give you an update on my understanding of this problem .. 

The old 'Rex' library from MSF has changed somewhere along the line. The way the console extension used to work was that rex was used for most of the console interface, now, in the rex library there was a 'jobs' framework as well. What used to happen was that the console extension would start the beef server in a new 'job' (or thread), and then the console would run in the front. This allowed both components to work separately (somewhat).

Since ruby 2 - it appears that whatever underlying thread mechanisms were used in rex changed, and subsequently, MSF's use of Rex changed - PLUS - the way in which they publish Rex changed. You'll notice we don't specify *ANY* rex requirements in the Gemfile. Even if you were to add the appropriate gem, there's still something not quite right.

I need to do some further investigation, but, I've just been crazy busy with random shit. :( But - I so want to get on top of this... so yeah, keep this open - I'll try and find some time to nut down and get into it.

**Comment by caoimhinp** [comment]
ping...

Anymore info on this? This is useful for those of us that need to use this from an instance out in the wide world where we'd rather not have an admin interface hosted and we'd rather use ssh for all management.

**Comment by xntrik** [comment]
Hey All,

Unfortunately I believe somewhere during the Ruby 1.9.2/3 -> 2 something in
the associated MSF Rex library changed with regards to 'jobs'. In the older
version, when you started with the console it would use Rex' library to
kick off the beef server as a separate job. That stopped working properly.

In the interim, you could perhaps limit the admin web UI to localhost, and
simply SSH with tunnelling to the server? This would allow you to hit
http://localhost:blah to see the admin UI ?

Cheers,

Christian

**Comment by bcoles** [comment]
@xntrik ping

**Comment by wadealcorn** [comment]
3+ years old - closing
