### ISSUE TITLE
forgot username and password for beef

### ISSUE THREAD

**Issue by panda314** [beefproject/beef#1091]
i forgot the user name and password for my beef account, please advise on how to proceed

**Comment by xntrik** [comment]
Hi @panda314 - the username/password are set in the config.yaml file. Check for the line with 'credentials:' on it.

**Comment by danygsam** [comment]
run `sudo nano /usr/share/beef-xss/config.yaml` and change user and psswd

**Comment by Capsyss** [comment]
> run `sudo nano /usr/share/beef-xss/config.yaml` and change user and psswd

where do i put this

**Comment by Pokment** [comment]
Hi, I can't open the file directory because of some issues. I also cant change my password, maybe can i get some help because i don't know what to do next. Thank u

**Comment by bcoles** [comment]
> Hi, I can't open the file directory because of some issues.

Then resolve those issues.

> I also cant change my password, maybe can i get some help because i don't know what to do next. Thank u

It is probably a permission issue. Try editing the file with root privileges.

**Comment by jokerking1202** [comment]
how to create beef xss username and password

**Comment by Khan83133** [comment]
I am new go login page

Username beef
Password beef

But can't login show invalid user and password

**Comment by stephenakq** [comment]
@Khan83133 Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc*

**Comment by ogrill** [comment]
> > run `sudo nano /usr/share/beef-xss/config.yaml` and change user and psswd
> 
> where do i put this

put it in the terminal

**Comment by ogrill** [comment]
then enter and it will display the username and password mixed in all the other info

**Comment by Ashwin68** [comment]
First you have to download the leafpad on the Kali machine after you go to the config.yaml folder then you can see the beef login credentials!

**Comment by giggles4e** [comment]
I have the credentials but it's not accepting the credentials when I go in there to enter it so I'm thinking of just removing the whole application or the whole beef and reinstalling it but I have to remove their credentials from Foxfire. What do you think?

**Comment by mdshakibkhan0x1** [comment]
I use this command 
> sudo nano /usr/share/beef-xss/config.yaml 
Which works very well and thanks for sharing
