### ISSUE TITLE
HSTS Super Cookies

### ISSUE THREAD

**Issue by soh-cah-toa** [beefproject/beef#1092]
HTTP Strict Transport Security can be abused to track users across normal -> incognito sessions.

http://www.radicalresearch.co.uk/Lab/HstsSuperCookies

I'll look into the technical details of this a little more and see how it can be used in conjuction with the Evercookies we're currently using.

**Comment by wadealcorn** [comment]
Should we drop this due to bandwidth?

**Comment by bcoles** [comment]
@wadealcorn yes.

Insufficient developer bandwidth. WontFix. Closing this issue.
