### ISSUE TITLE
Beef not detecting browser type 

### ISSUE THREAD

**Issue by adi-rfeist** [beefproject/beef#1100]
I have tried both BeEF 0.4.5.0-alpha and BeEF 0.4.4.9-alpha on 2 different Kali installs and am getting the Browser Version as UNKNOWN . Tried with various browsers. 

Console shows:

[23:38:40][!] [Browser Details] Invalid browser name UNKNOWN returned from the hook browser's initial connection.
[23:38:46][*] New Hooked Browser [id:1, ip:<client NAT ip>, type:UNKNOWN-UNKNOWN, os:Windows 7], hooked domain [<webserver ip>:3000]

Have now located core/main/client/browser.js and can see there is no detection code for recent browser versions. Is anyone working on this ?

**Comment by antisnatchor** [comment]
make sure you run the latest BeEF version

$git pull https://github.com/beefproject/beef.git beef_latest
$bundle install
$ruby beef -x -v

**Comment by byt3bl33d3r** [comment]
@antisnatchor this is happening to me too only for Chrome though, using the latest beef from github

**Comment by bcoles** [comment]
Chrome 41 was released earlier in March. Support for Chrome 41 was added in 791c9d14616b3e353775f67b36fb0913b1857380.

@adi-rfeist @byt3bl33d3r This should be fixed.

**Comment by byt3bl33d3r** [comment]
@bcoles awesome! thanks
