### ISSUE TITLE
Issue with Ubuntu VPS

### ISSUE THREAD

**Issue by bitchnigga** [beefproject/beef#1101]
I got beef installed completely and got it running perfectly, but at one point my VPS completely shut down. When I booted it back up and tried starting beef the only thing the console outputted was "Killed". When I installed it in a different directory it started working again, but the process repeated and I keep getting "Killed".Also, is there a way to make beef a system service on a non-kali environment?

**Comment by antisnatchor** [comment]
This is not a BeEF issue at all, but an issue with your VPS.

For info about writing init scripts for ubuntu see here:
https://help.ubuntu.com/community/UbuntuBootupHowto
