### ISSUE TITLE
API Fire Error: authentication failed in {:owner=>BeEF::Extension::Metasploit::API::MetasploitHooks, :id=>12}.post_soft_load()

### ISSUE THREAD

**Issue by ccavxx** [beefproject/beef#1106]
API Fire Error: authentication failed in {:owner=>BeEF::Extension::Metasploit::API::MetasploitHooks, :id=>12}.post_soft_load()

**Comment by antisnatchor** [comment]
Which version or BeEF and of Metasploit are you using?
Opening issues like this is completely useless...

**Comment by bcoles** [comment]
Closing this issue due to insufficient information.

BeEF authentication to Metasploit RPC is working with Ruby 2.1.6p336 on Kali with and without SSL.

![msf1](https://cloud.githubusercontent.com/assets/434827/8393639/0d3e2188-1d5c-11e5-902a-613d1cbfe26e.png)

![msf2](https://cloud.githubusercontent.com/assets/434827/8393641/3cefa992-1d5c-11e5-9e8b-019e48140ce1.png)

**Comment by tennc** [comment]
@bcoles  can you show me your config.yml ???  beef  and metasploit

**Comment by Iromhide** [comment]
I have the same problem. I updated beef and metasploit and the config.yaml file is correct.

**Comment by bcoles** [comment]
@Iromhide Chances are your `config.yaml` is not correct.

https://github.com/beefproject/beef/wiki/Configuration#metasploit

There should be more output which indicates the cause of the issue. Can you provide the console output?

**Comment by Iromhide** [comment]
My config.yaml file of Metasploit (beef-xss/extansions/metasploit) is the following. I saw that the password should be changed every time with the given password.

<img width="1000" alt="screen shot 2017-12-13 at 09 14 15" src="https://user-images.githubusercontent.com/34367760/33926289-2681d1b8-dfe6-11e7-9eb7-e157cdf1f1e4.png">

**Comment by bcoles** [comment]
@Iromhide it looks like your version of BeEF is old. Also, the SSL configuration is wrong.

`ssl_version: 'TLS1'`

**Comment by Iromhide** [comment]
I updated beef with a script I found. Changed the config.yaml files but continue to have the problem.

**Comment by David5201** [comment]
i also got the problem . but after changed the password of msf  the problem is fixed!

**Comment by q2dg** [comment]
I can confirm it: just changing the default password it works  :-S

**Comment by jaja83ful** [comment]
Might be as simple as not running as root
running as just user gets me this result
#cd /usr/share/beef-xss/
#./beef

![screenshot from 2018-08-23 12-52-07](https://user-images.githubusercontent.com/42642500/44523904-86856700-a6d3-11e8-9ab6-ae7810d5f50a.png)

running as sudo gets me this result
#cd /usr/share/beef-xss/
#.sudo /beef

![screenshot from 2018-08-23 12-52-21](https://user-images.githubusercontent.com/42642500/44524000-dfed9600-a6d3-11e8-8044-71522582a944.png)
