### ISSUE TITLE
execjs requires Ruby version >= 2.0.0

### ISSUE THREAD

**Issue by pyllyukko** [beefproject/beef#1107]
At least the most recent versions of execjs (in this case 2.5.1) seem to require Ruby version 2.0.

BeEF documentation and the installation script use Ruby 1.9.[23] and as the version of the required execjs is not specified, RVM tries to fetch the latest and it fails:

```
$ gem install execjs
ERROR:  Error installing execjs:
	    execjs requires Ruby version >= 2.0.0.
```

**Comment by antisnatchor** [comment]
Good point, we should update docs and script.
I've been always using RVM regardless to be honest, use that and you will be fine.

**Comment by bw-z** [comment]
@pyllyukko Thanks for raising this - we'll update the documentation and install script. 

In the meantime you can update to Ruby 2 using:
```
rvm install 2.1.5
rvm use 2.1.5
```

Please let us know if you run into any issues running BeEF with this Ruby version

**Comment by bcoles** [comment]
Thanks @pyllyukko 

Documentation and install scripts have been updated for Ruby 2.1.5.

Closing this issue.
