### ISSUE TITLE
API use - add the module id into the log message to make it more usable

### ISSUE THREAD

**Issue by adi-rfeist** [beefproject/beef#1108]
Current log ...

[id] => 2470
[date] => 2015-04-14T18:02:50-05:00
[event] => Hooked browser [id:11, ip:10.1.1.101] has executed instructions from command module [id:89, name:'Man-In-The-Browser']

Can we change this to include the module id also. The id: 89 [above example] is the command response id. Example of what it could look like:

[id] => 2470
[date] => 2015-04-14T18:02:50-05:00
[event] => Hooked browser [id:11, ip:10.1.1.101] has executed instructions from command module [module_id:4, name:'Man-In-The-Browser', response_id:89]

then you can pull the logs for a specific hooked browser and via api query the response for the specific modules that have been run i.e. 

curl -v http://10.1.1.10:3000/api/modules/3NmNj1iUP3oUiFSBKlfU1jy1ZLPFtzi1Se5ASIB0s5iFkEd4v10Wre6wLfcbz5DljQW70UnYTwv40hh0/4/89?token=5617e4c2e6eed61a3398c9f7dd3b0f24e38d8797

**Comment by antisnatchor** [comment]
Good point, I will add it in the coming weeks as soon as I have time.
Thanks

**Comment by adi-rfeist** [comment]
For ref, my use case is to create a security awareness tool ('web page') showing what has occurred in a hooked browser session and allowing the user to also trigger 1 or 2 commands and see results.

**Comment by adi-rfeist** [comment]
edited the following

core/main/models/command.rb

line 59 - BeEF::Core::Logger.instance.register('Command', "Hooked browser [id:#{hooked_browser.id}, ip:#{hooked_browser.ip}] has executed instructions from command module [mod:#{command.comm$

line 64 - print_info "Hooked browser [id:#{hooked_browser.id}, ip:#{hooked_browser.ip}] has executed instructions from command module [mod:#{command.command_module_id}, id:#{command_id}, n$

core/main/handlers/modules/command.rb

line 68 - print_info "Hooked browser [id:#{hooked_browser.id}, ip:#{hooked_browser.ip}] has been sent instructions from command module [mod:#{command.command_module_id}, id:#{command$

**Comment by bcoles** [comment]
@antisnatchor I'll take care of this shortly, unless you've already started?

**Comment by bcoles** [comment]
Thanks @adi-rfeist

This has been added in efb99f9e98684ab775068ddc130ef6967daaedd2.
