### ISSUE TITLE
0.4.6.0-alpha: Links to Images Like Fake Flash Update do not work anymore

### ISSUE THREAD

**Issue by ghelm** [beefproject/beef#1109]
Hi there,

just grabbed a fresh clone of 4.6.0-alpha and noticed, that the Fake Flash Update (and I think a couple of other extensions too) do not work anymore, as they are unable to request files like "http://172.16.60.42:3000/adobe/flash_update.png". If I run this in a Browser I just get a

"Not Found
The requested URL was not found on this server.
Apache/2.2.3 (CentOS)"

Bug is not present in "beef-0.4.5.1". Maybe a recent commit broke the webserver part?

Regards..

**Comment by bmantra** [comment]
Problem lies with the new Rack Gem version "1.6.1".  I downgraded from "1.6.1" back to old version "1.5.3" and the images did re-appear.  So I think there is some compatibility issues between rack 1.5.x and rack 1.6.x.
As a workaround you can hardcode the version in Gemfile: 
gem "rack" 
    => 
gem "rack", "1.5.3"

**Comment by bmantra** [comment]
Fixed by commit ea9549adbe015bebd7a041bc9458b165c4da2ce4 from @antisnatchor.
