### ISSUE TITLE
0.4.5.1-alpha: Man-In-the-Browser is causing wrong encoding

### ISSUE THREAD

**Issue by ghelm** [beefproject/beef#1110]
Hi,

using the persistency module "Man-In-the-Browser" on a German site like http://www.otto-office.com/de/ is destroying the encoding of german umlauts (ä ö ü ß) as you can see on the attached screenshot.

Best Regards

**Comment by ghelm** [comment]
![otto-office-encoding](https://cloud.githubusercontent.com/assets/1833568/7274005/6cecff2e-e8f9-11e4-94c4-2040d3a1b5e7.png)

**Comment by antisnatchor** [comment]
Closing for lack of bandwidth sorry
