### ISSUE TITLE
Use history.js for Man-in-the-Browser stuff

### ISSUE THREAD

**Issue by antisnatchor** [beefproject/beef#1111]
https://github.com/browserstate/history.js/

Change the code mitb.js and the related command module to use this wrapper which is browser-agnostic.

**Comment by antisnatchor** [comment]
Hey @radoen do you have any bandwidth to look into this?

**Comment by bcoles** [comment]
Hi @radoen 

Have you had any luck with this?

**Comment by bcoles** [comment]
Presumably this was closed as WontFix.
