### ISSUE TITLE
Twitter Alert not working

### ISSUE THREAD

**Issue by pand0rausa** [beefproject/beef#1112]
The alerting feature seems to not be working. Lots of dependency issues that don't resolve and it also looks like Twitter has updated their API since the alerting was last modified.

**Comment by redknight99** [comment]
Heya @pand0rausa, 

I saw the problem you're referring today and came up with a fix that I tested on a Windows box and Ubuntu machine. 

1. I installed the latest Twitter gem  by running the command "gem install twitter" as per the comment in the config.yaml file. 

2. I then put "require twitter" in the beef gem file.

3. Finally I ran "bundle install" 

On the Windows box I had to configure the SSL certs but I'm not 100% that was part of the fix. 

Hope that helps. Let me know if you're still having an issue.

**Comment by pand0rausa** [comment]
Thanks!
I did follow the comments in the config file, I'll try it as you have it
written and get back to you.
