### ISSUE TITLE
Login form not showing. (Arch Linux install)

### ISSUE THREAD

**Issue by Darkpaw95** [beefproject/beef#1115]
I've recently installed beef from the git repo/AUR, The login form is not showing up to accept user credentials. I've provided a few screenshots below. I've tried a few things to get it to work properly but I can't figure this out.

http://i.imgur.com/EOHMjhr.png -> Web UI
http://i.imgur.com/fIKMYZZ.png -> Web UI source
http://i.imgur.com/UZCCH0f.png -> Beef console

**Comment by sudoaza** [comment]
Im getting the same problem on Arch cloning it and runnning bundle install. 
Im getting internal server error on all the resources 

* /ui/media/javascript/ext-base.js
* /ui/media/javascript/ext-all.js
* /ui/media/javascript-min/web_ui_auth.js
* /ui/media/css/ext-all.css
* /ui/media/images/beef.png

**Comment by antisnatchor** [comment]
This is likely a problem with that OS, not BeEF's ;-)
