### ISSUE TITLE
createIframeXsrfForm() fails when form input is named 'submit'

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1117]
The function `beef.dom.createIframeXsrfForm` fails when form input is named 'submit', for example:

`{'type':'hidden', 'name':'submit', 'value':'Run' }`

If a form input field is named `submit` in a call to `createIframeXsrfForm` the input field overrides `form.submit()` preventing submission of the form:

`formXsrf.submit is not a function`

Note: 'Submit' with a capital 'S' works fine.

See:
* https://stackoverflow.com/questions/3571328/form-submit-button-will-not-submit-when-name-of-button-is-submit
* https://stackoverflow.com/questions/8729319/how-send-a-form-with-javascript-when-input-name-is-submit

**Comment by antisnatchor** [comment]
You keen to have a look into this mate?

**Comment by bcoles** [comment]
One partial solution - although not particularly intuitive - would be to replace all user-supplied parameters called 'submit' with 'Submit' in `beef.dom.createIframeXsrfForm` and throw a warning with `beef.debug`. However, errors arising from this change could be problematic to track down if client-side debugging is disabled.

I'll implement this if you like; for lack of a better solution. I have no interest in investigating further.

**Comment by antisnatchor** [comment]
Yeah implement it mate, thanks!
