### ISSUE TITLE
I keep Getting this error while using beef strike plugin for cobalt strike 

### ISSUE THREAD

**Issue by amitkurud** [beefproject/beef#1119]
ERROR: net.sf.json.JSONException: JSONObject["value"] not found.
 
also cobalt strike  becomes too slow to work with I mean when clean on beef menu tab its almost takes 5 minutes to open beef menu

**Comment by antisnatchor** [comment]
This is certainly not a problem of BeEF. I would ping https://twitter.com/thebenygreen who I know he's using a lot CobaltStrike + BeEF with great success.
