### ISSUE TITLE
Beef installation on Windows

### ISSUE THREAD

**Issue by shantanudesai** [beefproject/beef#1120]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20150527-6804-4hrd3x.rb extconf.rb
checking for sqlite3.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Have been trying to troubleshoot this for close to 8 hours now.
That's the thing with ruby on windows.. you keep on trying and trying and trying.
Just wanted to point out that 'simple' steps mentioned here - https://github.com/beefproject/beef/wiki/Installation
need to be updated for windows. The last step of 'bundle install' does not work due to the above mentioned error.

I will keep on digging - provide the solution and close this IFF i am able to.
Any help is appreciated.

**Comment by bcoles** [comment]
Hi @shantanudesai

Support for BeEF on Windows is minimal. Like you said, Ruby on Windows is tedious.

See issue #1031 which should resolve your issues.

Failing that, this [guide](https://github.com/beefproject/beef/issues/932#issuecomment-69188364) gives instructions for configuring BeEF for Heroku on Win XP SP3 which might help. It gives instructions for using PostgreSQL rather then SQLite.

As an alternative, check out the BeEF live CD or a unix based operating system.

**Comment by shantanudesai** [comment]
Shifted to iOS after spending a couple of nights on this.
Consider adding a big "Nor recommended on Windows" header to Beef. 
Closing the issue.
Over and out.
