### ISSUE TITLE
web_cloner.rb uses beef.http.host & port vs beef.http.public & public_port

### ISSUE THREAD

**Issue by bitcracker** [beefproject/beef#1121]
**web_cloner.rb** **initialize** sets **@beef_hook** to always use **beef.http.host** and **beef.http.port**. However, when using Google Compute Engine to run BeEF, **beef.http.host** & **beef.http.port** must be set to the private 10.x.x.x internal IP & port while **beef.http.public** & **beef.http.public_port** are set to the public external IP & port. As currently coded, the cloned html returned to the victim will have a reference to that private 10.x.x.x IP and thus the client cannot fetch hook.js and never gets hooked.

It appears that **initialize** should do something like the following (remember I know even less about ruby than BeEF) :

```ruby
  beef_host = @config.get("beef.http.public") != nil ? @config.get("beef.http.public") : @config.get('beef.http.host')
  beef_port = @config.get("beef.http.public_port") != nil ? @config.get("beef.http.public_port") : @config.get('beef.http.port')
  @beef_hook = "#{beef_proto}://#{beef_host}:#{beef_port}#{@config.get('beef.http.hook_file')}"
```

**Comment by bcoles** [comment]
Thanks @bitcracker
