### ISSUE TITLE
Rake quick test errors - invalid byte sequence in UTF-8 

### ISSUE THREAD

**Issue by xntrik** [beefproject/beef#1126]
Running 'rake' (or 'rake quick' or 'rake unit') in Ruby 2 (I'm currently on 2.2.1) results in UTF-8 errors when we try and pass \xFF .. according to https://en.wikipedia.org/wiki/UTF-8#Codepage_layout this is invalid UTF-8 character. There's a good summary of the issue https://robots.thoughtbot.com/fight-back-utf-8-invalid-byte-sequences

This also means there's a chance that if BeEF filters/accepts those invalid UTF-8 characters then it may throw exceptions.

Relates to Issue #1083

**Comment by xntrik** [comment]
The above commit is a 'partial' fix. I've also removed a few of the test cases (and commented as such). I'm going to leave it as is until someone @bcoles perhaps? can have a double check of what I've done.

**Comment by bcoles** [comment]
This gets the test cases passing which is nice.

I believe the correct approach is to detect and set the encoding of all input, at input.

The filters should also encode input and return false if encoding fails  (`rescue Encoding::UndefinedConversionError`).
