### ISSUE TITLE
WebRTC RTCPeerConnection - command execution only sends 'raw' js

### ISSUE THREAD

**Issue by xntrik** [beefproject/beef#1136]
Ideally you should be able to send _any_ beef command module through the data channel to the peer browser.

**Comment by antisnatchor** [comment]
Is this done mate ;-0 ?

**Comment by xntrik** [comment]
Yep. Haha, but it needs a tidy. But I'm stupid time poor til post Vegas.

I also added most of it into the admin ui too, plus rest api etc.

**Comment by antisnatchor** [comment]
ping pong @xntrik

**Comment by bcoles** [comment]
@xntrik ping

**Comment by DeezyE** [comment]
Closing - stale. Reopen if necessary
