### ISSUE TITLE
Persormance issues when 400 browsers offline

### ISSUE THREAD

**Issue by badbob** [beefproject/beef#1138]
After few days hooking on audited website I have about 400 hosts in DB. And webinterface now completelly down. Any request from UI generates a high load on server and dropped by timeout. So, only CLI interface still working. 

Possible it would be better to implement some king of lazy loading of ofline browsers. The offline browser sub-tree should be collapsed by default.

**Comment by xntrik** [comment]
Hi Vladimir,

Is this using MySQL/Postgres?

-x

**Comment by badbob** [comment]
Yes, I use a MySQL. Ruby process generate huge CPU load. As I can see, the most common information about zoombies Beef stores not like relation DB way, but it just stores a JSON in text fields. I suppose, that it can be the reason, because Beef need to parse every loaded object every time.

**Comment by badbob** [comment]
Any news/ideas? 
I tried to run ruby-prof, but can't find any sensitive information.

**Comment by antisnatchor** [comment]
Can you give us more details?

Ruby version, OS details (ssd/ram), htop info under high load, MySQL configuration, etc..
Also, which things you're doing in BeEF (autorun/obfuscation/etc)

This will help
Thanks

**Comment by antisnatchor** [comment]
Also, memory consumption of the ruby and mysql process would be nice ;-)
I would also increase file descriptor limits, and potentially run from a ramdisk (both BeEF and MySQL DB).

It might as well be an issue with the fact we are getting all the hooked browsers at once, maybe I could add paging in the UI.

Btw have a look at the ARE stuff ;-)

**Comment by badbob** [comment]
Ruby version is 2.1.6:

```
~/beef$ ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
```

OS Debian on VPS 3G RAM. 

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
```

![image](https://cloud.githubusercontent.com/assets/1911432/9079314/a43f0224-3b6a-11e5-9416-5f935638d00f.png)

I just open an UI and browse the main page after login. No obfuscation enabled. No autorun. Just browsing the main page. 

![image](https://cloud.githubusercontent.com/assets/1911432/9079336/e48f315a-3b6a-11e5-9e5c-1839ff5441e5.png)

I think, this issue is about 

1) getting all browsers at once.
2) storing information as json in DB and parsing it when read

What did you mean "ARE stuff"?

**Comment by antisnatchor** [comment]
Yeah, storing JSON stringfied structures in the db, then parsing it again is not ideal. It's a long time change I had in mind. I was also thinking to have some most used data structures in memory rather than on db.

Are you also maybe using a very short XHR polling? Like less than 1 sec? Is WebSocket enabled?

I will have a look into this hopefully soon. In the meantime you can use as a workaround multiple BeEF servers, and control them both via restful api.

Thanks for these inputs ;-)

**Comment by bcoles** [comment]
A few changes have been made in an attempt to decrease the network and processing overhead of polling the zombie list.

Ideally the Admin UI should allow filtering, to optionally retrieve only online hooked browsers, and ignore offline browsers. However, this has not yet been implemented.

The zombie details are still all retrieved in a single request. Some of the processing has been offloaded to the browser to cut down on the size of the JSON response. Currently, each zombie results in approximately 500 bytes of JSON data in the poll response. Having 400 offline browsers would result in approximately 200KB of JSON data returned per poll.

If you're still having issues, a few workarounds exist.

It is now possible to delete zombies. Zombies can be removed manually via a right-click context menu, or all at once using the [remove-offline-browsers](https://github.com/beefproject/beef/blob/master/tools/rest_api_examples/remove-offline-browsers) example script which uses the REST API. Note that deleting a zombie also deletes all the associate logs, command module results, etc, which may be undesirable.

Also, a `beef.extension.admin_ui.panel_update_interval` option has been introduced in #1690.

Cranking this option up (from the default of `10` seconds) may alleviate the bottleneck induced be frequently polling and parsing the browser details.

**Comment by DeezyE** [comment]
This is reasonably addressed, closing.
