### ISSUE TITLE
Tidy up webrtc.js - rely on BeEF's global debugging capability

### ISSUE THREAD

**Issue by xntrik** [beefproject/beef#1142]
There's a bunch of weird logic in the current webrtc.js file to determine whether or not things should be debugged. Once all the console.log commands are shifted to beef.debug commands, a bunch of these checks can be removed. (Yay!)

**Comment by antisnatchor** [comment]
Is this done mate?

**Comment by xntrik** [comment]
Yep :) just needs a tidy and push

**Comment by bcoles** [comment]
@xntrik ping

**Comment by antisnatchor** [comment]
ping pong @xntrik

**Comment by bcoles** [comment]
@xntrik ping

**Comment by bcoles** [comment]
@xntrik ping

**Comment by bcoles** [comment]
I'm just going to assume this is done. There's no references to `console.log` in `core/main/client/webrtc.js`.
