### ISSUE TITLE
Make it such that the -x cli argument also clears out the minified js files for the admin ui such that they're rebuilt

### ISSUE THREAD

**Issue by xntrik** [beefproject/beef#1143]

**Comment by antisnatchor** [comment]
Is this done mate ;-0 ?

**Comment by antisnatchor** [comment]
ping

**Comment by antisnatchor** [comment]
ping pong @xntrik

**Comment by bcoles** [comment]
@xntrik ping

**Comment by bcoles** [comment]
The admin UI JavaScript files `web_ui_all.js` and `web_ui_auth.js` in `extensions/admin_ui/media/javascript-min/` are rebuilt regardless of whether the `-x` parameter was provided. This is the intended behavior. This issue is closed.
