### ISSUE TITLE
Scroll to bottom of Command Results after rendering

### ISSUE THREAD

**Issue by nstarke** [beefproject/beef#1144]
Right now, every time the ajax response comes back from the server for the command results, the entire results table is re-rendered.  If the user has scrolled down to see the newest results, once the results are re-rendered, the scroll jumps to the first result.  This makes viewing results for modules that report back in streams (iframe_keylogger, etc) difficult.  Is there any way we can either 1) keep track of the user's current scroll position and reset to that after rebinding or 2) automatically scroll to the newest results coming in? I'd be happy to do the work if someone can point me in the correct direction.

**Comment by antisnatchor** [comment]
You should add something like an auto-scroll down action somewhere here:
/Users/antisnatchor/WORKS/BeEF/ARE-work/beef/extensions/admin_ui/media/javascript/ui/panel/tabs/ZombieTabCommands.js

command_module_grid is where you want to have a look ;-)

**Comment by nstarke** [comment]
Thinking about this a little more, I think for now a "pause" button might be the best way to go.  If we force scroll the results on each data rebind, we're going to have the same problem in reverse (not being able to see the first results).  What are your thoughts on that idea?

**Comment by antisnatchor** [comment]
Quite easy: calculate the height of the div where the results are displayed. As you know how big is one line of results in that div, as its height is always fixed, you want to auto-scroll down only if (result_height * result entries) > div_height ;-)

**Comment by bcoles** [comment]
Will that work? The command results div is not always the same height. Command results are of variable length.  This is especially true for modules which return images as base64 data, such as Spyder Eye and the webcam modules, which is then rendered within the UI.

Alternatively, consider first extracting the data using the REST API or querying the database.

**Comment by antisnatchor** [comment]
Yes, I would go easily RESTful API for now, even from JavaScript with a single get ;-)

**Comment by nstarke** [comment]
Have we come to any sort of consensus on the proper course of action for this problem?  Again, I'm happy to write the code for this as long as there is an agreement on what to do :-)

**Comment by bcoles** [comment]
I'd also like to see this fixed but it's not high priority for me.

I think the expected behavior, when new command results are received, would be as follows:
* If the results window is scrolled to the bottom it should scroll to the new result (ie, to the bottom).
* If the results window is scrolled to the top it should stay at the top.
* If the results window is scrolled to neither the top nor bottom it should stay scrolled at the same position.

This gets a bit tricky when the existing result data in the results window is insufficient to overflow the height of the results window, then a new command result is received which causes an overflow. In this situation, when command results are received, the scroll bar should scroll to the newest result (ie, to the bottom).

Does this make sense?

**Comment by antisnatchor** [comment]
Yes it does, @nstarke do you have bandwidth to look into this?

**Comment by nstarke** [comment]
Yes, I will take a look at it starting tonight.  It may take me a few days.

**Comment by nstarke** [comment]
this is taking me longer than expected.  I'll continue working on this as I have time over the next couple of weeks unless someone else wants to pick it up.  Thanks.

**Comment by antisnatchor** [comment]
cool, let us know how it goes, thanks ;-)

**Comment by antisnatchor** [comment]
any updates on this @nstarke ?

**Comment by nstarke** [comment]
Sorry for the delay in responding, I don't have the bandwidth to work on this at the moment.  if anything changes with that I'll be sure to comment on this thread.

**Comment by bcoles** [comment]
WontFix. Closing this issue.
