### ISSUE TITLE
Hook.js not working

### ISSUE THREAD

**Issue by NickWinston123** [beefproject/beef#1149]
Beef seems to run well but while trying on both my Kali Linux as well as my Mac OS X when trying to visit "http://127.0.0.1:3000/hook.js" from any other computer it seems to do nothing but show the text in the file and not do anything to http://127.0.0.1:3000/ui/panel which works well but it won't hook.js won't connect to it due to it not being runnable.
![screenshot 2015-07-29 15 01 49](https://cloud.githubusercontent.com/assets/11579042/8967061/c25e2a90-3602-11e5-9da8-e0a82223277b.png)

**Comment by xntrik** [comment]
You need to get the JS to run in the context of a page/origin. Try visiting
/demos/basic.html as this includes the hook properly.

**Comment by NickWinston123** [comment]
@xntrik Oh, thanks worked perfectly!

**Comment by badbob** [comment]
Zombie goes offline, because user close the tab.

**Comment by antisnatchor** [comment]
guys, read the Browser Hacker's Handbook. This is all expected behaviour.

**Comment by NickWinston123** [comment]
@badbob @antisnatchor By instantly I mean without closing the tab, I would just open a new tab and search or I would search with the existing tab that I had hooked.

**Comment by xntrik** [comment]
@NickWinston123 as soon as the domain/origin of the page changes, the DOM is cleared. The hook is only stored within the current DOM. The running javascript can't execute if it's environment disappears.

**Comment by minijus704** [comment]
hi,
i have problem with beef.
I have install beef on kubuntu on vps.
I have hooked our browser, but when click execute I don't get dialog box on browser.( I testing "social engineering">pretty cheft)
What's wrong? Don't working on kubuntu in vps?
Please help me

**Comment by lukes-sequeira** [comment]
Hi, I have the same problem. But I didn't fully understand the solution. I am quite new with this but I am trying to learn. Do you mind going step by step through the solution? Thank you!!
