### ISSUE TITLE
Invalid JSON object returned when adding ARE rule via API

### ISSUE THREAD

**Issue by byt3bl33d3r** [beefproject/beef#1151]
Nothing major! just for consistency 

Adding an ARE rule:
```python
In [4]: beef.are_rules.add('/home/byt3bl33d3r/Devel/MITMf-0.9.8/config/beef_arerules/c_osx_test-return-mods.json')
Out[4]: u'["success", true]["rule_id", 5]'
```
the returned object can't be serialized properly using the python ```requests``` or ```json``` libraries  (don't know for ruby) :
```python
TypeError: <Response [200]> is not JSON serializable
```

**Comment by antisnatchor** [comment]
I will fix this today, was planned ;-) thanks mate!

**Comment by antisnatchor** [comment]
Grazie once again ;-) if you find anything else, please open more issues :-) Thanks mate
