### ISSUE TITLE
Old version in repo

### ISSUE THREAD

**Issue by AnguisCaptor** [beefproject/beef#1152]
When doing apt-get update/upgrade, I still get version 0.4.4.9-alpha
Could you update it to last version

**Comment by bandwagonz** [comment]
Correct me if I'm wrong but Im pretty sure the maintainers of the OS you're using will have to update their repo, the creators of beef don't really have control over that. 

If you're using Kali, you'll need to submit your request to them.

**Comment by AnguisCaptor** [comment]
Oh ok, will do :)
