### ISSUE TITLE
ARE, feature request

### ISSUE THREAD

**Issue by benyG** [beefproject/beef#1153]
Actually we can trigger a rule and that will have impact on every targets that will match it. But what happens if we want to target just one zombie. An API request like this one can be usefull. 
curl http://beefserver:3000/api/autorun/rule/trigger/1/ZOMBIE_ID/token=xyz.

**Comment by antisnatchor** [comment]
I will implement this soon ;-)

**Comment by bcoles** [comment]
Happy birthday #1153

@antisnatchor ping

**Comment by jcrew99** [comment]
This actually has been done, closing because of @https://github.com/beefproject/beef/issues/1751
