### ISSUE TITLE
API Fire Error: "\xC2" from ASCII-8BIT to UTF-8 in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>23}.mount_handler()

### ISSUE THREAD

**Issue by majl** [beefproject/beef#1155]
I installed latest version of beef on my MAC(OS X yosemite10.10.4) and  I'm still getting this error:

API Fire Error: "\xC2" from ASCII-8BIT to UTF-8 in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>23}.mount_handler()

I used :
ruby 2.1.5p273
bundle install is done!

**Comment by antisnatchor** [comment]
I have the same version of ruby on OSX and I never seen than error.
