### ISSUE TITLE
Installation on Arch

### ISSUE THREAD

**Issue by 0x2F** [beefproject/beef#1158]
CAUTION: This installation script will install a number of BeEF dependencies including the Ruby-RVM environemnt and it's dependencies.

In rare cases, this may lead to unexpected behaviour or package conflicts on some systems.

Are you sure you wish to continue (Y/n)? Y

Detecting OS..

=======================================
          Install Failed
Unable to locate installer for your OS:
Linux

=======================================

[02:09 PM] - { ~/tmp/beef }
[n1c @ yard]->uname -a
Linux yard 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux
[02:09 PM] - { ~/tmp/beef }

**Comment by antisnatchor** [comment]
just install RVM and git clone the BeEF repo, then 'bundle install'
