### ISSUE TITLE
Browser not showing the Login Form (kali 2, up to date)

### ISSUE THREAD

**Issue by ThetaSigma3** [beefproject/beef#1159]
I start up beef (tried with both service start and using the icon) and when It opens the panel, I only see the logo but no Login/ Pass fields. I also get a few errors (some differ) including this one in the pic below. I ran a apt get update, upgrade and to make sure apt get install beef xss, but it's totally up to date. I use Kali 2 Live boot USB drive. I need some aid here. Thank you.
http://prntscr.com/895peb

**Comment by antisnatchor** [comment]
contact Kali support please, it's not a BeEF bug.
