### ISSUE TITLE
Feature Request - API call to manually set OS and Browser version of hooked browsers

### ISSUE THREAD

**Issue by byt3bl33d3r** [beefproject/beef#1164]
Hi all!
I'm currently working on a plugin for MITMf to help BeEF with fingerprinting zombies when using the ARE.

Would be really great to have an API call to manually set the OS and Browser of zombies so that if we perform fingerprinting using some other means, all we have to do to trigger the correct ARE rule is set the values in BeEF. 

Let me know if I didn't explain this very well :P 

Cheers!

**Comment by byt3bl33d3r** [comment]
Obviously, this is for when BeEF fails too fingerprint the hooked browsers

**Comment by antisnatchor** [comment]
Makes sense ;-) I will implement this soon ;-) stay tuned

**Comment by anonymous4ever1** [comment]
Is it implemented yet? I mean, is there any ARE rule for using with MITMf?
