### ISSUE TITLE
Can't load /hook.js

### ISSUE THREAD

**Issue by Sheerforce** [beefproject/beef#1173]
I'm running Kali linux sana on a [chroot](https://github.com/dnschneid/crouton/wiki/Kali) on my dell chromebook 11 and I installed beef via apt-get install kali-linux-web.

I can log in to the admin panel with no issues, but I get an empty response when trying to load hook.js. 

![screenshot - 091815 - 16 32 29](https://cloud.githubusercontent.com/assets/12566062/9970428/1cdb17e2-5e23-11e5-919d-b98debd6460f.png)

**Comment by dem-waffles** [comment]
Could this be related to #1174 by any chance?

**Comment by antisnatchor** [comment]
Not sure what is the issue with your setup, but I never experienced this on Kali 2. BeEF works pretty well.
