### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by dem-waffles** [beefproject/beef#1174]
When hosting from Mac OSX Yosemite, accessing with Chrome on Windows 7 from a different host gives the error net::ERR_CONTENT_LENGTH_MISMATCH and hook.js appears to be truncated. Scrolling to the bottom and refreshing loads more of the file, but hook.js fails to hook browsers.

This does not happen when accessing locally, only when remote hosts try to access.

It might be a Mac thing, but it does work on virtualized Ubuntu (virtualized from Windows).

**Comment by iw0rzm** [comment]
I'm having same problem. Beef is running on kali 2.0. With other linux machine or even mac osx it injection works via lan or wireless, with windows (xp, 7, 10) I get the same error. Hook.js is not entirely loaded. Any news about this bug??

**Comment by dem-waffles** [comment]
Unfortunately, I don't have the time time to fix this bug, so someone else will have to look into it.

**Comment by dem-waffles** [comment]
Unfortunately, I don't have the time time to fix this bug, so someone else will have to look into it.

**Comment by dem-waffles** [comment]
Unfortunately, I don't have the time time to fix this bug, so someone else will have to look into it.

**Comment by dem-waffles** [comment]
Unfortunately, I don't have the time time to fix this bug, so someone else will have to look into it.

**Comment by dem-waffles** [comment]
Unfortunately, I don't have the time time to fix this bug, so someone else will have to look into it.

**Comment by dem-waffles** [comment]
Unfortunately, I don't have the time time to fix this bug, so someone else will have to look into it.

**Comment by dem-waffles** [comment]
Unfortunately, I don't have the time time to fix this bug, so someone else will have to look into it.

**Comment by antisnatchor** [comment]
I can't really reproduce the bug.

I can easily hook IE11 on Win 8.1 running on vmware fusion on latest OSX.

**Comment by antisnatchor** [comment]
Also, I can assure you these should be local problems on your side, because when I use BeEF in production for phishing/client-side engagements I hook basically every kind of browsers (running BeEF on linux) and I never had issues.

**Comment by iw0rzm** [comment]
Got it, problem was not Beef but the antivirus (in my case Symantec SEP), which probably intercepts the hook.js. Without this antivirus, it works. Tested also with MS Defender without problems

**Comment by bcoles** [comment]
The evasion extension may help with bypassing antivirus. It's disabled by default, however you can enable it by setting `beef.extension.evasion.enable` to `true` in `config.yaml`
