### ISSUE TITLE
beef_strike Geolocate issue

### ISSUE THREAD

**Issue by SyxPl0it3r** [beefproject/beef#1182]
It returns always a capture of google maps of the whole planet :D lol 
i mean just like if you go to google maps and minimize to maximum then it's the same thing with beef_strike .. i tried with a public ip address that i can locate easily using no matter which ip location service on the web.
here is an exemple attached as .png
![-3888](https://cloud.githubusercontent.com/assets/15268710/10701681/343894b0-79c5-11e5-841f-051592f80e5f.png)

**Comment by antisnatchor** [comment]
beef_strike is not something we (BeEF developers) coded.

You should ping @thebenygreen on twitter. He's the dev.
