### ISSUE TITLE
After install of Phishing-Frenzy!

### ISSUE THREAD

**Issue by jteslaxxx** [beefproject/beef#1184]
Hello installed PF and now i,m getting this:
root@kali:~# cd /usr/share/beef-xss
root@kali:/usr/share/beef-xss# ./beef
/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rubydns (LoadError)
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/beef-xss/core/loader.rb:16:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./beef:32:in `<main>'
root@kali:/usr/share/beef-xss# 

When i run from Application=>System Services=>beef start ,
application run, but its not connecting to metasploit!

Thanks!

**Comment by antisnatchor** [comment]
You don't have the rubydns gem installed. You should do a 'bundle install' form the BeEF directory.
