### ISSUE TITLE
!] API Fire Error: TypeError: undefined is not an object (evaluating 'node._eval') in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>23}.mount_handler()

### ISSUE THREAD

**Issue by korang** [beefproject/beef#1186]
Not seeing Login interface when browsing to localhost:3000/ui/panel.  Saw this error:  File not found: /javascript-min/web_ui_auth.js.  Using EL Captitan.  Lastest BEEF from GIT.  I did RUN BUNDLE INSTALL.  Seeing this when I run a verbose for beef:

!] API Fire Error: TypeError: undefined is not an object (evaluating 'node._eval') in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>23}.mount_handler()

**Comment by ZhenjieRuan** [comment]
I have the same issue

**Comment by gitbenzo** [comment]
ehy guys.. its easy just install node and npm and work fine!
here---> https://nodejs.org/dist/v5.1.0/node-v5.1.0.pkg

**Comment by ZhenjieRuan** [comment]
Oops...Thanks ;)

**Comment by danielyzc** [comment]
Yo lo solucione copiando la carpeta "extensions\admin_ui"  que genere en Linux, en la instalacion de windows:
![captura de pantalla de 2016-10-02 11 53 14](https://cloud.githubusercontent.com/assets/3044181/19022152/ce03db96-8896-11e6-97c7-9c1663157c0a.png)
