### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Locknlol** [beefproject/beef#1189]
Could an audio file be played via the contol panel webgui when a new connection is found? This way those whom alt-tab won't miss a connection.

**Comment by antisnatchor** [comment]
Yep it's quite easy to implement.
Would you have time to look into this?

Or, anyone else?

**Comment by bcoles** [comment]
This has been added in 16da11e7df47fde7ca8a17197e9a437522e258d1

You can now play a sound in the web admin interface for each new hooked browser by specifying `play_sound_on_new_zombie: true` in [extensions/admin_ui/config.yaml](https://github.com/beefproject/beef/blob/master/extensions/admin_ui/config.yaml)

Closing this issue.

This functionality is disabled by default for a few reasons:

* If you have 100 hooked browsers then reload the admin web UI, the sound will play 100 times.
* The MP3 sound file is hosted in the `extensions/demos` directory. Instead, it should be hosted and mounted by the Admin UI extension.
* The UI should really have an option to mute the sounds which could become an annoyance.
