### ISSUE TITLE
Problem access admin page

### ISSUE THREAD

**Issue by kaaell** [beefproject/beef#1198]
Hi guys,
if I start beef I see this error:
---
[!] API Fire Error: invalid byte sequence in US-ASCII in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>14}.mount_handler()
---
When I try to logon in the admin page I don't see the form. Could you suggest me anything? I use ruby 2.1.5 and the last stable beef release.
Regards, k.

**Comment by TheGroundZero** [comment]
Did you browse to the corect URL?

http://127.0.0.1:3000/ui/panel

**Comment by kaaell** [comment]
Yes but without success.
k.

**Comment by hackthem** [comment]
Hi guys,

I have the same issue.

Regards,

Abdellah AZOUGARH

**Comment by hackthem** [comment]
I think this file is missed : 
"File not found: /javascript-min/web_ui_auth.js"

Regards,

**Comment by raphui** [comment]
Try: export LANG= "en_US.UTF-8″
export LC_ALL= "en_US.UTF-8″

**Comment by motiko** [comment]
@raphui Thanks, solved the issue for me

**Comment by kaaell** [comment]
Hi, my problem was related to a docker container (I had tried export LANG but without result). Now I've resolved in this way:
1-install "locales" package
2-(Dockerfile) RUN locale-gen UTF-8 en_US && localedef -c -f UTF-8 -i en_US en_US.UTF-8
3-(Dockerfile) ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en" LC_ALL="en_US.UTF-8"
Regards,k.

**Comment by hackthem** [comment]
Tanks, it solved the issue for me too.

**Comment by X0o0Z** [comment]
@raphui Tks, solved the issue for me.
