### ISSUE TITLE
WebSocket error

### ISSUE THREAD

**Issue by dontzonnail** [beefproject/beef#1200]
![websocket](https://cloud.githubusercontent.com/assets/16919577/12615181/d9d330a4-c49f-11e5-9367-fa7106cee360.png)

I'm getting this error while using beef with Evasion and WebSockets enabled.
The browser is hooked and modules are executed, it's just that I'm seeing this error and the user input is not shown in the beef panel 

Help needed please !!

**Comment by bcoles** [comment]
Thanks @dontzonnail 

I've reproduced this error with evasion enabled and disabled.

The issue appears to be related to the `save_result` call, here: https://github.com/beefproject/beef/blob/master/core/main/network_stack/websocket/websocket.rb#L249

I'm looking into it. I suspect this is related to changes introduced with the autorun rules engine.

**Comment by bcoles** [comment]
This should now be fixed.
