### ISSUE TITLE
Windows installing error

### ISSUE THREAD

**Issue by Kosti1** [beefproject/beef#1201]
Bundle tries to install therubyracer 0.11.4 instead of using version 0.11.0beta1

Using windows 10

**Comment by bcoles** [comment]
Hi @Kosti1 

That's unusual. The Gemfile should check the OS... 

I don't have a Win10 box handy. What's the result of `RUBY_PLATFORM.downcase` in IRB?

**Comment by Kosti1** [comment]
i368-mingw32

**Comment by Kosti1** [comment]
Works now.
I downloaded source and used it :+1:
