### ISSUE TITLE
Windows error...

### ISSUE THREAD

**Issue by Kosti1** [beefproject/beef#1202]
C:\Users\"This Was Removed"\Desktop\Ruby\beef-master>bundler install
Using addressable 2.4.0
Using ansi 1.5.0
Using chunky_png 1.3.5
Using daemons 1.2.3
Using fastercsv 1.5.5
Using json 1.8.3
Using json_pure 1.8.3
Using multi_json 1.11.2
Using eventmachine 1.0.9.1
Using erubis 2.7.0
Using execjs 2.6.0
Using geoip 1.6.1
Using librex 0.0.999
Using mime-types 2.99
Using mojo_magick 0.5.6
Using msgpack 0.5.12
Using parseconfig 1.0.8
Using rack 1.6.4
Using rainbow 2.1.0
Using ref 2.0.0
Using rubyzip 1.1.7
Using tilt 2.0.2
Using tins 1.8.2
Using win32console 1.3.2
Using bundler 1.11.2
Using data_objects 0.10.17
Using dm-core 1.2.1
Using rqrcode 0.9.0
Using em-websocket 0.3.8
Using uglifier 2.7.2
Using msfrpc-client 1.0.3
Using rack-protection 1.5.3
Using thin 1.6.4
Using rexec 1.6.3
Using therubyracer 0.11.0beta1
Using term-ansicolor 1.3.2
Using do_sqlite3 0.10.17
Using dm-do-adapter 1.2.0
Using dm-migrations 1.2.0
Using dm-serializer 1.2.2
Using qr4r 0.4.0
Using sinatra 1.4.7
Using rubydns 0.7.0
Using dm-sqlite-adapter 1.2.0
Bundle complete! 25 Gemfile dependencies, 44 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

C:\Users\"This Was Removed"\Desktop\Ruby\beef-master>ruby beef
C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/lib/Win32/Console.rb:12:in `require': cannot load such file -- 2.2/Console_ext (LoadError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/lib/Win32/Console.rb:12:in `rescue in <top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/lib/Win32/Console.rb:8:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/lib/Win32/Console/ANSI.rb:13:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/lib/Win32/Console/ANSI.rb:13:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/lib/win32console.rb:1:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/lib/win32console.rb:1:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from C:/Users/"This Was Removed"/Desktop/Ruby/beef-master/core/loader.rb:10:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from beef:24:in `<main>'

**Comment by bcoles** [comment]
Thanks @Kosti1

I believe the `win32console` gem does not work with Ruby 2.x.

The good news is that it doesn't work because it's no longer required.

Can you remove `win32console` from `Gemfile`, re-run `bundle install` (which should update `Gemfile.lock`) and try again?

Please let me know if this works and I'll remove the requirement.

**Comment by bcoles** [comment]
The `win32console` gem has been removed from the Gemfile. Closing this issue.

**Comment by bogere** [comment]
Hullo. i think this issue should be reopened abit.
suppose  running  bundle install  does not remove the win32console gem requirement.
when i run the gem list command. it does not show the win32console yet when you open the ruby library folder, it is present
