### ISSUE TITLE
How can I call all active hooked browsers from the parameter "hb_ids" ??

### ISSUE THREAD

**Issue by kaos69** [beefproject/beef#1205]
In the documentation the parameter "hb_ids" is used like this "hb_ids":[1,2,3,4,5,6}

How can I call all online browsers from this parameter, without specifying the browsers ids ?

Thanks

**Comment by bcoles** [comment]
@kaos69 

I assume this is for the `/api/modules/multi` RESTful API endpoint.

I believe it's currently not possible to specify all hooked browsers. I'll verify, and if not, look at implementing it.

**Comment by bcoles** [comment]
@kaos69 This has been added in f4ff606cbf61a4f17d54f18009741b02edf926f7

You should now be able to specify a command module to run on all hooked browsers using `"hb_ids":["ALL"]`

**Comment by kaos69** [comment]
Thanks for the fix, 

Now we can call ALL browsers, but it would be better if we could specify only the Online browsers, it would be very good if you could implement this also.

Thank you

**Comment by bcoles** [comment]
@kaos69 That makes sense. This has been added in 9e0ccf71bb509932ba66e574003b09b9ef6a7517

You should now be able to specify a command module to run on all online hooked browsers using "hb_ids":["ALL_ONLINE"]

I'm not sure if this is the most intuitive approach. It may change in the future.
