### ISSUE TITLE
Autorun = > Redirect Browser

### ISSUE THREAD

**Issue by Comancheroo** [beefproject/beef#1206]
Hi,
I setting config.yaml (beef/modules/browser/hooked_domain/site_redirect).
But new hooked browser not auto redirect. What should I do? Thanks.

beef:
    module:
        site_redirect:
            enable: true
            **autorun: true**
            category: ["Browser", "Hooked Domain"]
            name: "Redirect Browser"
            description: "This module will redirect the selected hooked browser to the address specified in the 'Redirect URL' input."
            authors: ["wade", "vo"]
            target:
                user_notify: ["ALL"]

**Comment by bcoles** [comment]
Hi @Comancheroo 

I believe the `autorun` notation is no longer supported since the addition of the new autorun rule engine.

You can achieve the desired result like so:

```
$ cat arerules/enabled/redirect.json
{
  "name": "Redirect Browser",
  "author": "bcoles",
  "browser": "ALL",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [{
    "name": "site_redirect",
    "condition": null,
    "options": {
      "redirect_url": "http://<YOUR SITE HERE>/"
    }
  }],
  "execution_order": [0],
  "execution_delay": [0],
  "chain_mode": "sequential"
}
```
