### ISSUE TITLE
Admin UI is not showing login page

### ISSUE THREAD

**Issue by rhertzog** [beefproject/beef#1207]
On Kali 2016.1, with latest beef and using ruby 2.2, the login page of the admin UI does not work. The reason is that /ui/media/javascript-min/web_ui_auth.js is not created. The permissions on the directory are correct but when I run beef in debug mode, the only error I see is this one:
```
[ 9:25:01][!] API Fire Error: invalid byte sequence in US-ASCII in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>24}.mount_handler()
```

A google search showed the same error in #1068 where it was said that beef was not supporting ruby 2.x yet. But that was in 2014. We're now in 2016 and you should really support the latest ruby version.

I can provide any additional information on request

**Comment by bcoles** [comment]
Hi @rhertzog 

It's highly likely this is related to your system locale/language settings, see #1198

I imagine if you do `echo $LANG` it will say `fr_FR.iso-8859-15` or `LANG=fr_FR.utf8`

Can you try `export LANG=en_US.utf8` and see if that fixes your issue?

If it does I'll create a new issue for processing. Issues related to 'admin page won't load because of web_ui_auth.js' get posted frequently. It's clear we need some better error handling and reporting in this part of the code base.

As an aside, BeEF now supports Ruby 2.x and longer supports Ruby < 2.0. The preferred version of Ruby is 2.1.5. I believe all BeEF devs are currently using Ruby 2.1.5+. Personally, I do the majority of my testing and development on Kali with Ruby 2.2.4.

**Comment by bcoles** [comment]
BeEF now checks the system language settings and throws a warning if it's not UTF-8 compatible.

Added in 989d6de65ae1fd102954b0de639cae4934fee944

This is as close to a patch as I can come up with. I'm open to suggestions.

**Comment by rhertzog** [comment]
In my case, I was running with a plain system without any locale (so LANG=C not UTF-8 enabled). You should probably set LANG yourself to some UTF-8 value if it's not set... you can use "locale -a" to know which locale are available.

On many systems (at least all Debian based distros), there's also a C.UTF-8 locale that you can rely on to be always available.

```
$ locale -a| grep -i utf
C.UTF-8
fr_FR.utf8
```

**Comment by rhertzog** [comment]
BTW, you should update the README to mention the correct ruby version that you support. It still documents 1.9.x...

**Comment by bcoles** [comment]
Thanks. The README now says 2.0 or higher.

I would rather not forcibly change the user's language settings. Is this best practice? Is there a way to set `$LANG` for only the currently running Ruby process?

**Comment by rhertzog** [comment]
Well, I said LANG=C to show the default value but actually LANG was unset... so it's not about forcibly changing the user's setting but about setting a reasonable default value when it's not set.

And changing the environment variable only affects the current ruby process (and its children) so it has no impacts on other processes of the user. I'm not a ruby programmer but I guess that assigning ENV['LANG'] should do the right thing...

**Comment by bcoles** [comment]
Sadly, setting `ENV['LANG']` does not work, nor does forking out with backticks `export LANG=en_us.utf8`, as neither can control the parent process. [1]

Unless I misunderstand the problem, I suspect launching BeEF from a shell script with the appropriate `$LANG` set beforehand would work, however this would break backwards compatibility for those launching BeEF using the Ruby interpreter, like `ruby beef`, which seems to be common practice.

Potentially; having BeEF fork out to a shell script, which in turn sets the `$LANG` then launches BeEF, would work, although decrease cross-platform support. This also seems like overkill. If the user's environment supports UTF8 the user should consider setting the `$LANG` appropriately or pay the penalty.

Thanks for the suggestions. If setting the appropriate `$LANG` worked for you then I'll close this issue and open it up for discussion on the BeEF mailing list.

[1] http://blog.honeybadger.io/ruby-guide-environment-variables/

**Comment by phocean** [comment]
Hello,

I am running into the same issue, but setting $LANG does not work.
I am probably not understanding how to fix it.

ruby 2.3.1p112 and BeEF 0.4.7.0-alpha.

**Comment by bcoles** [comment]
Hi @phocean 

Try setting these:

```bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by phocean** [comment]
Thank you, but unfortunately, same problem and error message.
Note that I am running it from an interactive docker container, but I can't imagine it would make a difference.

**Comment by bcoles** [comment]
Is JavaScript enabled in your browser? Do you receive any errors in console?

Do you have NodeJS installed?

**Comment by phocean** [comment]
I get a 404 in the Javascript console for the file: `/ui/media/javascript-min/web_ui_auth.js`.
This file does not seem to exist in the repo.
Otherwise, I tested on Firefox and Chrome, and none has restrictions regarding Javascript.

**Comment by phocean** [comment]
Problem solved, it was docker specific.
You need to install the `locale` package and then in your Dockerfile:

```
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
```

Source:
http://stackoverflow.com/questions/28405902/how-to-set-the-locale-inside-a-docker-container
http://jaredmarkell.com/docker-and-locales/

Thank you for your help ;-)
