### ISSUE TITLE
rescue in parse': uninitialized constant BeEF::Core::Console::CommandLine::OptionParser (NameError)

### ISSUE THREAD

**Issue by DTherHtun** [beefproject/beef#1212]
./beef 
/var/lib/openshift/56bc5c6e2d52718e01000058/app-root/runtime/repo/core/main/console/commandline.rb:67:in `rescue in parse': uninitialized constant BeEF::Core::Console::CommandLine::OptionParser (NameError)
	from /var/lib/openshift/56bc5c6e2d52718e01000058/app-root/runtime/repo/core/main/console/commandline.rb:33:in `parse'
	from ./beef:37:in `<main>'

**Comment by bcoles** [comment]
Hi @DTherHtun

This issue is related to #1090

Unfortunately BeEF no longer supports Ruby < 2.0, and the console extension requires Ruby 2.0+.

**Comment by bcoles** [comment]
Thanks @DTherHtun

Which version of Ruby are you using?

Are you passing any command-line arguments to BeEF?

**Comment by DTherHtun** [comment]
I use ruby 2.0 at https://openshift.redhat.com 
pls help me 
i can't install beef on openshift

**Comment by antisnatchor** [comment]
This should be fixed now with this commit https://github.com/beefproject/beef/commit/f1eb8c87237c4c4443f61608d05df50ccdfa8819
