### ISSUE TITLE
[websockets] Command modules post_execute does not execute

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1214]
The `post_execute` function within each command module is meant to execute upon receipt of command results. This works when XHR is used as the communication channel, however the function is never executed when WebSockets are used.

**Comment by antisnatchor** [comment]
Yep it's expected, I think I left a comment somewhere even ;-) lazy italian

**Comment by antisnatchor** [comment]
I'm having a look at it this week ; -)

**Comment by antisnatchor** [comment]
This one should also be done and dusted now. I've tested it with a bunch of modules like Get Internal IP and the post_execute body of the module executes correctly ;-) @bcoles give it a try and let me know

**Comment by bcoles** [comment]
Fixed. Closed. Thanks @antisnatchor !
