### ISSUE TITLE
dropped form submit notifications

### ISSUE THREAD

**Issue by ilatypov** [beefproject/beef#1215]
I saw form submits missing their notifications.  Adding web console debugging showed that the event handler did get called but the notification did not get sent.

I guessed that this happened when the form submit resulted in the browser reloading the entire document, thus cancelling the currently running Javascript thread that waited for more events to send in a batch.  Adding calls to "this.queue()" and "beef.net.flush()" in the bottom of the submit handler appeared to have helped. (I guess this work-around may stop working if the Javascript engines start implementing network requests in a continuation-friendly manner).

**Comment by bcoles** [comment]
Thanks @ilatypov

Are you keen to do a pull request for this?

**Comment by antisnatchor** [comment]
Merged thanks@
