### ISSUE TITLE
uninitialized constant BeEF

### ISSUE THREAD

**Issue by mluis** [beefproject/beef#1216]
beef/core/main/console/commandline.rb:67:in `rescue in parse': uninitialized constant BeEF::Core::Console::CommandLine::OptionParser (NameError)

**Comment by bcoles** [comment]
Thanks @mluis 

Which version of Ruby are you using?

Are you passing any command-line arguments to BeEF?

**Comment by mluis** [comment]
np @bcoles 

I'm using ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

commit d0ca66cbf53c11056cd375820e14cb8b4f3cb920

No.

**Comment by Und3rf10w** [comment]
I have encountered the same issue using a clean installation of the latest version:

```
$ ./beef -x
/opt/beef/core/main/console/commandline.rb:67:in `rescue in parse': uninitialized constant BeEF::Core::Console::CommandLine::OptionParser (NameError)
        from /opt/beef/core/main/console/commandline.rb:33:in `parse'
        from ./beef:39:in `<main>'

```

It appears to be cause by an error in ```core/main/console/commandline.rb``` where on line 67, it attempts to call 'OptionParser':

```ruby
begin
            optparse = OptionParser.new do |opts|
              opts.on('-x', '--reset', 'Reset the database') do
                @options[:resetdb] = true
```

I added ```require 'optparse'``` to ```core/loader.rb``` and this resolved the issue:

```ruby
# @note Include here all the gems we are using
require 'rubygems'
require 'bundler/setup'
Bundler.require(:default)
require 'optparse' #here's the fix
```

**Comment by necony286** [comment]
@Und3rf10w   dude thanks u fixed it for me. much THANKS!
i had the same error as shown 
~/beef# ./beef
/root/beef/core/main/console/commandline.rb:67:in `rescue in parse': uninitialized constant BeEF::Core::Console::CommandLine::OptionParser (NameError)
	from /root/beef/core/main/console/commandline.rb:33:in `parse'
	from ./beef:39:in `<main>'
added the line of code u provided us and it works ;)
