### ISSUE TITLE
multiple hooks attaching to a page

### ISSUE THREAD

**Issue by ilatypov** [beefproject/beef#1217]
Inspecting a hooked page showed a few (not more than 10) head script tags added by the hook script.

I failed to find where the beef initialization adds itself as a head script tag.  I wish this mechanism checked for existing head script tags and removed older tags.

**Comment by ilatypov** [comment]
As a side, I worried that older scripts could register themselves as listeners in logger.js, so I cleared event listeners with the useful jQuery calls in logger.start and logger.stop,

```javascript
+        $j(document).off('keypress');
+        $j(document).off('click');
+        $j(window).off('focus');
+        $j(window).off('blur');
+        $j('form').off('submit');
+        $j(document.body).off('copy');
+        $j(document.body).off('cut');
+        $j(document.body).off('paste');
```
and made the existing listeners register with jQuery's internal list (because the javascript native listener add calls seem to require keeping the the listeners as references for subsequent removal),
```javascript
-               document.body.oncopy = function() {
+               $j(document.body).on('copy', function() {
                        setTimeout("beef.logger.copy();", 10);
-               };
-               document.body.oncut = function() {
+               });
+               $j(document.body).on('cut', function() {
                        setTimeout("beef.logger.cut();", 10);
-               };
-               document.body.onpaste = function() {
+               });
+               $j(document.body).on('paste', function() {
                        beef.logger.paste();
-               }
+               });
```

**Comment by bcoles** [comment]
@ilatypov I have no idea why BeEF would add itself to the head script tag.

Were all of the scripts you're seeing for the hook.js or something else?

Are you using BeEF in conjunction with a mitm tool? Appending the hook to the head or body tags is a common technique for mitm applications to append the script to an intercepted page.

Does this happen after you've run some modules?

Are you using any extensions which aren't enabled by default?

**Comment by bcoles** [comment]
@ilatypov your changes to the existing event listeners to use jQuery are good.

The event logger is old code and needs some love. Are you keen to test and do a pull request for this?

The `.off()` changes will break any existing event listeners within the hooked page, which may be undesirable. If the hooked page stops functioning the user may not enter as much input or simply leave the page.

**Comment by ilatypov** [comment]
I figured the head script tag appeared with the social_engineering extension that is enabled by default.

**Comment by bcoles** [comment]
Nope. Not unless you're using the Web Cloner or Mass Mailer.

**Comment by ilatypov** [comment]
Thanks.  On a closer look I see it's jQuery that adds the script tags to execute cross-domain queries that expect the "script" response.

Sorry I do not know much about BeEF.  Its beef.net.request sets the expected response type for GET queries to "script", which causes the above jQuery's cross-domain workaround.  Would POST queries suffice for logging cross-domain?  The responses to cross-domain POST requests would not be available to the browser.

**Comment by antisnatchor** [comment]
I've merged the pull request related to this, thanks @ilatypov
