### ISSUE TITLE
WebSocket error

### ISSUE THREAD

**Issue by antisnitch** [beefproject/beef#1223]
[10:53:43][!] WebSocket - something wrong in msg handling - skipped: undefined method `<<' for nil:NilClass

I'm using both preferred websockets and xhr, evasion is enabled. But I'm getting this error ??

**Comment by antisnatchor** [comment]
hard to understand what's the problem from what you wrote above...

can you run BeEF in verbose mode (-v) and copy the full exception stack trace? also, what browser are you hooking on which OS, and which modules are you sending?
