### ISSUE TITLE
Framework slower than usual

### ISSUE THREAD

**Issue by Bry-fi** [beefproject/beef#1225]
Ever since I updated to the version 0.4.7.0a, Beef has slowed down drastically. Sometimes even to the point of the framework crashing. Which happens multiple times per minute. Also, I would enter the right username and password and it would throw (Invalid username or password) even though I entered it correctly. Could it just be my computer or is it something else and if it is anyway I can prevent this from occurring to the newer versions?

**Comment by bcoles** [comment]
Regarding the user/pass authentication failure, you'll need to reload the login page (and maybe clear cookies) if you restart the framework.

**Comment by antisnatchor** [comment]
Certainly your environment. BeEF scales well up to 400 hooked browsers and more on a small Amazon EC2 instances with 1 core/2GB ram.
