### ISSUE TITLE
Hook Me -error

### ISSUE THREAD

**Issue by mcnightstricker** [beefproject/beef#1226]
hi. i have installed kali linux-rolling 2016.1 on my hard disk , full tools installed , when i open 
beef xss frame work , and try to hook it to the firefox browser i get this error : 

 1457280735505	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]

please help , 

thank you

**Comment by bcoles** [comment]
I assume this is in reference to the `Hook Me` bookmarklet.

It looks like you're trying to hook a resource which makes use of the `https` URI scheme, however your BeEF server is not using HTTPS.

You won't be able to hook HTTPS websites unless the BeEF hook is hosted using HTTPS (unless the browser allows loading mixed-content, which is non-default in modern browsers).

**Comment by ziflar** [comment]
try to disable the DNS extension in /etc/beef-xss/config.yaml by setting 
beef.extension.dns.enabled: false
