### ISSUE TITLE
Autorun = > Redirect Browser (iFrame)

### ISSUE THREAD

**Issue by Comancheroo** [beefproject/beef#1227]
Hi,
I setting config.yaml - autorun: true (beef/modules/browser/hooked_domain/site_redirect_iframe).
But new hooked browser not auto redirect(iframe). What should I do?

I have tried but this not work. (redirect browser working https://github.com/beefproject/beef/issues/1206#issuecomment-179667238 but iframe not working.

/root/beef/arerules/enabled
{
  "name": "Redirect Browser",
  "browser": "ALL",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [{
    "name": "site_redirect_iframe",
    "condition": null,
    "options": {
    "iframe_title": "Search"
      "iframe_src": "http://www.site.com"
      "iframe_timeout": "10"
    }
  }],
  "execution_order": [0],
  "execution_delay": [0],
  "chain_mode": "sequential"
}

[ARE] Ruleset (Redirect Browser): ERROR. The specified option (iframe_src) for module (site_redirect_iframe) does not exist.

Thanks.

**Comment by bcoles** [comment]
You're missing a mandatory option `iframe_favicon`

The ARE rule should look something like this:

```
{
  "name": "site_redirect_iframe",
  "author": "author",
  "browser": "ALL",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [{
    "name": "site_redirect_iframe",
    "condition": null,
    "options": {
      "iframe_title": "Search",
      "iframe_favicon": "http://<YOUR FAVICON URL>",
      "iframe_src": "http://www.site.com",
      "iframe_timeout": "10"
    }
  }],
  "execution_order": [0],
  "execution_delay": [0],
  "chain_mode": "sequential"
}
```

**Comment by antisnatchor** [comment]
Verified that this works (as @bcoles rightly pointed out). Sooner or later there will be some logic to detect if an ARE ruleset has missing module options, but for now just make sure that each mandatory input (module option) defined in module.rb is in the ARE module options.

For instance, the Prompt module required the question option, as per module.rb here:
'name' =>'question'

**Comment by Comancheroo** [comment]
Thanks. Working.
