### ISSUE TITLE
Bug: Module lcamtuf_download - param do_once not evaluated correctly

### ISSUE THREAD

**Issue by gaf5098** [beefproject/beef#1228]
When choosing _true_ for _Run Once_ in the BeEF web gui for Lcamtuf Download module, the param is not evaluated correctly.

in modules/social_engineering/lcamtuf_download/command.js line 11 should be changed from

`var once = '<%= @do_once %>';`
to
`var once = <%= @do_once %>;`

to make the module work as expected.

**Comment by antisnatchor** [comment]
Heap space memory issue. looks like you are running it on a very low memory system? 
Not sure about the error message though. Certainly not a BeEF issue.
