### ISSUE TITLE
cant run beef, bundle install error

### ISSUE THREAD

**Issue by necony286** [beefproject/beef#1229]
running on kali rolling 2016.1 
i had beef working 5 days ago...
when i try to run it today i get the error to run bundle install and this happend: 

git pull https://github.com/beefproject/beef.git
From https://github.com/beefproject/beef
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
root@neco286:~/Tools/beef# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing addressable 2.4.0
Using ansi 1.5.0
Installing chunky_png 1.3.5
Installing daemons 1.2.3
Using json 1.8.3

Gem::RemoteFetcher::UnknownHostError: no such name (https://rubygems.org/gems/json_pure-1.8.3.gem)
Using multi_json 1.11.2
Installing eventmachine 1.0.9.1 with native extensions
Using erubis 2.7.0
Using execjs 2.6.0
Installing fastercsv 1.5.5
Installing geoip 1.6.1
Installing librex 0.0.999
Installing libv8 3.11.8.17

Gem::RemoteFetcher::UnknownHostError: no such name (https://rubygems.org/gems/mime-types-2.99.gem)
Using mojo_magick 0.5.6
Installing msgpack 0.5.12 with native extensions
Installing parseconfig 1.0.8
Using rack 1.6.4
Installing rainbow 2.1.0
Using ref 2.0.0
Using rubyzip 1.1.7
Installing tilt 2.0.2
Installing tins 1.8.2
Using bundler 1.11.2
Installing data_objects 0.10.17
Using dm-core 1.2.1
Installing rqrcode 0.10.1
An error occurred while installing json_pure (1.8.3), and Bundler cannot
continue.
Make sure that `gem install json_pure -v '1.8.3'` succeeds before bundling.
root@neco286:~/Tools/beef# gem bunlder install
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command bunlder
root@neco286:~/Tools/beef# gem install bundler
Successfully installed bundler-1.11.2
Parsing documentation for bundler-1.11.2
Done installing documentation for bundler after 4 seconds
1 gem installed
root@neco286:~/Tools/beef# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using addressable 2.4.0
Using ansi 1.5.0
Using chunky_png 1.3.5
Using daemons 1.2.3
Using json 1.8.3
Installing json_pure 1.8.3
Using multi_json 1.11.2
Using eventmachine 1.0.9.1
Using erubis 2.7.0
Using execjs 2.6.0
Using fastercsv 1.5.5
Using geoip 1.6.1
Using librex 0.0.999
Using libv8 3.11.8.17
Installing mime-types 2.99
Using mojo_magick 0.5.6
Using msgpack 0.5.12
Using parseconfig 1.0.8
Using rack 1.6.4
Using rainbow 2.1.0
Using ref 2.0.0
Using rubyzip 1.1.7
Using tilt 2.0.2
Using tins 1.8.2
Using bundler 1.11.2
Using data_objects 0.10.17
Using dm-core 1.2.1
Using rqrcode 0.10.1
Installing em-websocket 0.3.8
Using uglifier 2.7.2
Installing msfrpc-client 1.0.3
Using rack-protection 1.5.3
Installing thin 1.6.4 with native extensions
Using rexec 1.6.3
Installing therubyracer 0.11.3 with native extensions

Gem::RemoteFetcher::UnknownHostError: no such name (https://rubygems.org/gems/term-ansicolor-1.3.2.gem)
Installing do_sqlite3 0.10.17 with native extensions
Using dm-do-adapter 1.2.0
Using dm-migrations 1.2.0
Using dm-serializer 1.2.2
Using qr4r 0.4.0
Using sinatra 1.4.7
Using rubydns 0.7.0
An error occurred while installing term-ansicolor (1.3.2), and Bundler cannot
continue.
Make sure that `gem install term-ansicolor -v '1.3.2'` succeeds before bundling.
root@neco286:~/Tools/beef# gem install term-ansicolor -v '1.3.2'
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    no such name (https://api.rubygems.org/quick/Marshal.4.8/term-ansicolor-1.3.2.gemspec.rz)

**Comment by bcoles** [comment]
Looks like a network/DNS issue with your environment. Closing this issue.

**Comment by xudongwei01** [comment]
1) maybe the network
2) or delete the ../bundle/jruby/1.x/cache/term-ansicolor-1.3.2.gem
