### ISSUE TITLE
GET GPSLOCATION

### ISSUE THREAD

**Issue by yk2016** [beefproject/beef#1233]
I have try this module which is in  host menu many times,but always failed.
Firefox Windows,and it can successfully run java applet.
 Do anyone know why it cound't work?
thanks!

**Comment by antisnatchor** [comment]
It depends on which version of Java (JRE) you're running it.

It's from a while that only applets signed with a valid certificate can be run. This is probably your problem. If you sign the applet that BeEF serves with a valid code signing certificate, it will work.

You can also try for educational purposes on old versions of JRE (like 1.6).
