### ISSUE TITLE
cant update beef

### ISSUE THREAD

**Issue by necony286** [beefproject/beef#1235]
:~/tools/beef# git pull https://github.com/beefproject/beef.git
From https://github.com/beefproject/beef
 * branch            HEAD       -> FETCH_HEAD
Updating 4409599..98873e4
error: Your local changes to the following files would be overwritten by merge:
	Gemfile.lock
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by bcoles** [comment]
The `Gemfile.lock` file was recently updated to ensure the dependencies are up to date.

To fix, run `git checkout Gemfile.lock`, then update BeEF and run `bundle install` to install the updated packages.

**Comment by necony286** [comment]
yep that fixed it. thanks
