### ISSUE TITLE
The hook.js not working on IE9 or low

### ISSUE THREAD

**Issue by zhankehua** [beefproject/beef#1238]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?
Ruby version is 2.1.5p273
On what browser?
IE9,IE8,IE6
On what operating system?
Windows 7,windows 2003

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?
no

#### Summary

Please provide a summary of the issue.
I start beef , and send the hook page to customer . the customer's web browser is IE9,when the customer open the link that i send . The Browser pop up a error dialog note "Missing Identifiers in line 8634"

#### Expected Behaviour

What was the expected result?
BeEF can hook customer's Browser .

#### Actual Behaviour

What was the actual result?
BeEF can't hook customer's Browser.

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
That's unusual.

I've verified the hook works with the default BeEF settings for:
* IE8 on Windows XP SP 3
* IE8 on Windows 7

Unfortunately due to the dynamic nature of the hook it's unclear what happens at line 8634. Can you reproduce the bug and provide any additional info?

**Comment by zhankehua** [comment]
Thank's your replay!
    I find ,The error was caused by the rubby version . if the rubby version is 2.1.5 or low , the hook.js can work .
otherwise , the hook.js would  not work on the IE8 Or IE 9.
    this is my step:
1 I down load kali linux 2.0(vm image)
2 i run this command: apt-get install ruby-full
3 i run : ruby -v , to know the version of the ruby . i get 2.15 
4 i run beef ,and test ,It working  very good.





zhankehua@163.com
 
From: Brendan Coles
Date: 2016-04-01 20:50
To: beefproject/beef
CC: zhankehua
Subject: Re: [beefproject/beef] The hook.js not working on IE9 or low (#1238)
That's unusual.
I've verified the hook works with the default BeEF settings for:
IE8 on Windows XP SP 3
IE8 on Windows 7
Unfortunately due to the dynamic nature of the hook it's unclear what happens at line 8634. Can you reproduce the bug and provide any additional info?

**Comment by zhankehua** [comment]
I am sorry,could you tell me ,how to reduce the version of the ruby (kali linux)?
thank you!



zhankehua@163.com
 
From: Brendan Coles
Date: 2016-04-01 20:50
To: beefproject/beef
CC: zhankehua
Subject: Re: [beefproject/beef] The hook.js not working on IE9 or low (#1238)
That's unusual.
I've verified the hook works with the default BeEF settings for:
IE8 on Windows XP SP 3
IE8 on Windows 7
Unfortunately due to the dynamic nature of the hook it's unclear what happens at line 8634. Can you reproduce the bug and provide any additional info?

**Comment by bcoles** [comment]
Since Kali changed to Kali-rolling I'm not sure the best way to downgrade Ruby.

You can use rvm or rbenv to manage multiple versions of Ruby on the same system:
* https://github.com/rbenv/rbenv
* https://rvm.io/

**Comment by mcnightstricker** [comment]
thank you

**Comment by mcnightstricker** [comment]
i will get more into it ,
