### ISSUE TITLE
[ARE] Ruleset (raw_javascript): ERROR. execution_order and execution_delay values must be consistent with modules numbers

### ISSUE THREAD

**Issue by leetu** [beefproject/beef#1244]
Hello im getting a weird issue i never seen before, nor cant find in documentation.

[ARE] Ruleset (raw_javascript): ERROR. execution_order and execution_delay values must be consistent with modules numbers, never had the issue before only on the newer version. Can anyone confirm this issue or help thanks in advance.

This is my custom script:
{
  "name": "raw_javascript",
  "author": "alien",
  "browser": "ALL",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [
    {
      "name": "raw_javascript",
      "condition": null,
      "options": {
        "cmd": "var xhr = new XMLHttpRequest();\nxhr.open(\'POST\', ****CUT****;\nreturn \'It worked!\';"
     }
    }
  ],
  "execution_order": [0,1],
  "execution_delay": [0,2000],
  "chain_mode": "sequential"
}

**Comment by leetu** [comment]
I just figured it out, the newest version requires the following:
Think it will be helpful for others, im closing it now.

"execution_order": [0],
"execution_delay": [0],
"chain_mode": "sequential"
}

**Comment by bcoles** [comment]
Yup, that's correct. Duplicate of issue #1231

Your ARE rule executes only one module, thus `execution_order` and `execution_delay` take only one argument.
