### ISSUE TITLE
Autonrun module problem.

### ISSUE THREAD

**Issue by xcolacho** [beefproject/beef#1251]
Hi, first of all my english isn't good enough, so sorry about that. I'm trying to enable autorun on hta_powershell module, but when I add `Autrorun: true` in the module config beef crash at boot. I was reading about Autorun Rule Engine (ARE) but it's too dificult to understand for me. I only want to autorun this module with the default settings. Thanks.

**Comment by bcoles** [comment]
@xcolacho using `autorun: true` does not work any more.

You need to write ARE rules.

Check out the [ARE page on the wiki](https://github.com/beefproject/beef/wiki/Autorun-Rule-Engine) and the [existing ARE rules](https://github.com/beefproject/beef/tree/master/arerules).

**Comment by bcoles** [comment]
@xcolacho Here's an example rule which makes use of the HTA Powershell module:

https://github.com/beefproject/beef/blob/master/arerules/ie_win_htapowershell.json

**Comment by bcoles** [comment]
@xcolacho did you get it working? What error does BeEF give?
