### ISSUE TITLE
Android: Cannot detect a Google Chrome browser

### ISSUE THREAD

**Issue by utkabobr** [beefproject/beef#1261]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

#### Environment

What version/revision of BeEF are you using?
0.4.6.1-alpha
On what version of Ruby?
2.2.3p173 (2015-08-18) [x86_64-linux-gnu]
On what browser?
Google Chrome
On what operating system?
Android

#### Configuration

Are you using a non-default configuration?
No
Have you enabled or disabled any BeEF extensions?
No

#### Summary

Please provide a summary of the issue.
No detection for that browser

#### Expected Behaviour

What was the expected result?
That browser will be detected

#### Actual Behaviour

What was the actual result?
No detection

#### Steps to Reproduce

Please provide steps to reproduce this issue.
Connect Android Google Chrome Browser

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.
Printing "Browser Version: UNKNOWN" in Details

**Comment by bcoles** [comment]
Hi @utkabobr

The version of BeEF you are using is quite old. Version 0.4.6.1-alpha was released almost a year ago, on Jul 13, 2015. The version of Chrome you're using likely did not exist at this time.

I've verified that Google Chrome on Android is correctly hooked and identified using the latest version of BeEF.

Try updating BeEF. The latest version is beef-0.4.7.0, or you can update from GitHub: `git clone https://github.com/beefproject/beef.git`

**Comment by utkabobr** [comment]
Thanks, i'm used a kali linux pre-installed version, i will update it
