### ISSUE TITLE
Kali Rolling : Hook.js problem 

### ISSUE THREAD

**Issue by gray1747** [beefproject/beef#1262]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

#### Environment

What version/revision of BeEF are you using?
I'm using version 0.4.7.0-alpha
On what version of Ruby?
The version of Ruby is 2.3.1p112 ( 2016-04-26)
On what browser?
On Firefox browser.
On what operating system?
I'm using Kali Rolling version 4.4.0. (x64)

#### Configuration
Are you using a non-default configuration?
Yes.
Have you enabled or disabled any BeEF extensions?
I have enabled the consle :    shell : enable : true
and change db_file:"beef.db" to db_file:"db/beef.db".
#### Summary
I've tried to use the hook url to hook a browser in my LAN network, but it's seem didn't work for me,
nothing hapened. But when i tried a demo for beef, it's worked. I don't know if the demo is different from the hook.js or not. I've tried to fix this problem it's still did not work. Sorry for my bad English.

#### Additional Information
When i open the hook url it's just appear this page : 
<img src="http://i.imgur.com/EKnPmS4.png" />

**Comment by bcoles** [comment]
The console extension is no longer supported. Disable it and you should be fine.

Also, the hook.js is JavaScript. It won't render in a browser. Try `http://BeEF.local:3000/demos/basic.html`
