### ISSUE TITLE
beef console errors with simple hook

### ISSUE THREAD

**Issue by bkr32** [beefproject/beef#1263]
#### Environment

kali linux 2.0 latest version of beef
firefox browser

#### Summary

after launching the basic beef hook provided in the getting started page i repeatedly get the following error

http://127.0.0.1:3000/hook.js?BEEFHOOK=MoZHvnBlz62yNI5GxtK6VwW2vEmzVS9E1OSdhaK2SGrx2gsJ4nytH2a4J7r2qQhcLiIwaEJs3Ap9WSeK&_=1462867160625 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

is this a normal error ?

**Comment by bcoles** [comment]
Do you have the DNS extension or console extension enabled? If so, try disabling them.

**Comment by bkr32** [comment]
DNS extension was disabled, after re-installing beef the issue is gone and everything works fine now 
thanks
