### ISSUE TITLE
Suggested wiki documentation update for 'extension/metasploit/config.yaml' showing ssl_version: 'TSV1'

### ISSUE THREAD

**Issue by prairie-guy** [beefproject/beef#1268]
I really got bitten badly with trying to get extension/metasploit to work. Finally found the change to metasploit/config.yaml from ssl_version: 'TSv1' -> ssl_version: 'TSV1'. I spent hours on this issue. My fault for not searching here first. For others, it would be great to update the wiki documentation:
`https://github.com/beefproject/beef/wiki/Configuration`

Sorry if this is the wrong place to post this or if I should make the change on the wiki instead. I'm a long time user of git-hub, but never been a contributor . . .

**Comment by bcoles** [comment]
Thanks @prairie-guy 

The [configuration](https://github.com/beefproject/beef/wiki/Configuration) page has been updated.

The underlying issue was discussed in #1171 and addressed in b0bf1c0c215bae0a1065267b085a35d0d1af9039.
