### ISSUE TITLE
Geolocation not Working on any Chrome Browser (Android,Windows,Linux, iOS)

### ISSUE THREAD

**Issue by ghost** [beefproject/beef#1269]
#### Environment

What version/revision of BeEF are you using?

0.4.7.0-alpha

On what version of Ruby?

ruby-2.3.0

On what browser?

Chrome Browser  50.0.2661.89

On what operating system?

Android,Windows,Linux, iOS
#### Configuration

Are you using a non-default configuration?
No

Have you enabled or disabled any BeEF extensions?
No
#### Summary

Please provide a summary of the issue.
Geolocation is not working. On any Chrome Browser .
#### Expected Behaviour

What was the expected result?

pop-up " Do you want to share your location"
#### Actual Behaviour

What was the actual result?
Nothing happend.

**Comment by antisnatchor** [comment]
Geolocation with the HTML5 api requires user intervention, so it's not that useful.
Was nice back then in 2011, but nowadays it more practical to enable geolocation in the config.yaml and use IP-based (not so accurate but makes sense).

**Comment by bcoles** [comment]
Hi @ghost

The geolocation client-side library was not included in the hook core for some reason. This has been added in 1a68c165bba810e556e827b6050b29660ce37fba. If you do a `git pull` the [Get Geolocation](https://github.com/beefproject/beef/tree/master/modules/host/physical_location) module should work for you now.
