### ISSUE TITLE
Denying load of chrome-extension://xxx/manifest.json. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

### ISSUE THREAD

**Issue by fooying** [beefproject/beef#1271]
Denying load of chrome-extension://xxx/manifest.json. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

---

modules/browser/detect_extensions

 Chrome Vesion:50.0.2661.102 (64-bit)

**Comment by antisnatchor** [comment]
Is this just a console.log error, or is the module not working?

**Comment by bcoles** [comment]
This module only works on Chrome version 1 to 18 and some versions of Firefox.
