### ISSUE TITLE
[ARE] Ruleset (FF35-36): ERROR. Illegal browser_version definition

### ISSUE THREAD

**Issue by leetu** [beefproject/beef#1272]
Im having an issue regarding specific browser versions within the ARE-Ruleset.

[ARE] Ruleset (FF35-36): ERROR. Illegal browser_version definition
Wrote a custom module which i would like to run between 2 versions or more versions.
From e.g Firefox Version 35-36, but in the documentation i can only see that its possible to run like:
33 => last version / 35 > last version, my goal here is to run it between version numbers which im struggling with.

Older or newer versions would result in a crash e.g

My syntax which cause an error look like this, my goal is to run javascript if between 2 version:
Not older / newer version, then it should be another custom ARE Rule for example regarding other versions.
{
  "name": "FF41-44",
  "author": "leetu",
  "browser": "FF",
  "browser_version": "´41<= 44",
  "os": "WIN",
  "os_version": "ALL",
  "modules": [

**Comment by bcoles** [comment]
@leetu Unfortunately currently you cannot specify an ARE rule to run between two browser versions. This may be added in the future.

**Comment by leetu** [comment]
@bcoles Thanks for letting community know, think people have been struggling with.
I think it would be really great to implement this feature in the nearby future.

All the time i knew the BeEF Project, 3 years or more i thougth it always have had that function.

But this will certainly boost the beef community, i think alot would be happy to see this feature get implemented soon.

Also i think i know how to make the Debugging Button to work again with javascript: URI
But via private messaging we can talk.

**Comment by bcoles** [comment]
@leetu you can specify in the module `config.yaml` file which browsers are supported by the module, however the module will run regardless.

In the short term, you could specify in your module `command.js` to `return` prematurely if the browser is not the required version. For example:

```javascript
if ( beef.browser.isFF41() || beef.browser.isFF42 || beef.browser.isFF43() || beef.browser.isFF44() ) {
do Stuff();
} else return;
```

**Comment by leetu** [comment]
Thanks for the short-term solution, i will look into that!

I hope to see this will get implemented as a feature so it would be possible run payloads between version numbers. Like shown below:
 "´41<= 44",  "´41< 44",  "´41=> 44", if you know what i mean :) This will contribute a lot to the framework!

**Comment by DeezyE** [comment]
Close Stale
