### ISSUE TITLE
ARE module + Metasploit

### ISSUE THREAD

**Issue by qubis-zz** [beefproject/beef#1274]
I can't run autorun engine with metasploit modules. As I understood I can add metasploit modules, crawler finds it, but then I got a problem because of "options". I was trying to add some options that I found in wireshark, but it doesn't working. 

So how can I use ARE + metasploit without making own modules from metasploit to ARE, just using stock metasploit module with stock ARE module?

**Comment by antisnatchor** [comment]
As @bcoles flagged, I will look into it. Likely mid-September.

**Comment by jcrew99** [comment]
@qubis Did this go anywhere?

**Comment by DeezyE** [comment]
Closing stale
