### ISSUE TITLE
Beef don't working on kubuntu

### ISSUE THREAD

**Issue by minijus704** [beefproject/beef#1276]
i have problem with beef.
I have install beef on kubuntu on vps.
I have hooked our browser, but when click execute I don't get dialog box on browser.( I testing "social engineering">pretty cheft)
What's wrong? Don't working on kubuntu in vps?
Please help me

**Comment by bcoles** [comment]
It's unlikely that what ever issue you're experiencing is related to kubuntu.

Do you receive any JavaScript errors? Do other modules work?

**Comment by minijus704** [comment]
I don,t getting errors. And other modules don,t working

2016 m. birželio 30 d., ketvirtadienis, Brendan Coles <
notifications@github.com> rašė:

> It's unlikely that what ever issue you're experiencing is related to
> kubuntu.
>
> Do you receive any JavaScript errors? Do other modules work?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/beefproject/beef/issues/1276#issuecomment-229670119>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATRurtlXmArEyGRsxGBWLAYnCJ37z84Yks5qQ86bgaJpZM4JBir6>
> .
>


-- 
Pagarbiai,
Minijus Žalnierukynas

**Comment by minijus704** [comment]
Where problem?

2016 m. birželio 30 d., ketvirtadienis, Minijus Žalnierukynas <
minijus704@gmail.com> rašė:

> I don,t getting errors. And other modules don,t working
>
> 2016 m. birželio 30 d., ketvirtadienis, Brendan Coles <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> rašė:
>
>> It's unlikely that what ever issue you're experiencing is related to
>> kubuntu.
>>
>> Do you receive any JavaScript errors? Do other modules work?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/beefproject/beef/issues/1276#issuecomment-229670119>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ATRurtlXmArEyGRsxGBWLAYnCJ37z84Yks5qQ86bgaJpZM4JBir6>
>> .
>>
>
>
> --
> Pagarbiai,
> Minijus Žalnierukynas
>


-- 
Pagarbiai,
Minijus Žalnierukynas

**Comment by minijus704** [comment]
Hi,
I don't getting errors on JavaScrips. Other modules, don't working.
I attaching logs info.
Please help

On Sun, Jul 3, 2016 at 7:50 PM, Minijus Žalnierukynas <minijus704@gmail.com>
wrote:

> Where problem?
>
>
> 2016 m. birželio 30 d., ketvirtadienis, Minijus Žalnierukynas <
> minijus704@gmail.com> rašė:
>
>> I don,t getting errors. And other modules don,t working
>>
>> 2016 m. birželio 30 d., ketvirtadienis, Brendan Coles <
>> notifications@github.com> rašė:
>>
>>> It's unlikely that what ever issue you're experiencing is related to
>>> kubuntu.
>>>
>>> Do you receive any JavaScript errors? Do other modules work?
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/beefproject/beef/issues/1276#issuecomment-229670119>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe/ATRurtlXmArEyGRsxGBWLAYnCJ37z84Yks5qQ86bgaJpZM4JBir6>
>>> .
>>>
>>
>>
>> --
>> Pagarbiai,
>> Minijus Žalnierukynas
>>
>
>
> --
> Pagarbiai,
> Minijus Žalnierukynas
>



-- 
Pagarbiai,
Minijus Žalnierukynas

**Comment by minijus704** [comment]
I using windows7 and chrome on hooked computer.
Beef can attcak windows7?

On Mon, Jul 4, 2016 at 12:03 PM, Minijus Žalnierukynas <minijus704@gmail.com
> wrote:

> Hi,
> I don't getting errors on JavaScrips. Other modules, don't working.
> I attaching logs info.
> Please help
>
> On Sun, Jul 3, 2016 at 7:50 PM, Minijus Žalnierukynas <
> minijus704@gmail.com> wrote:
>
>> Where problem?
>>
>>
>> 2016 m. birželio 30 d., ketvirtadienis, Minijus Žalnierukynas <
>> minijus704@gmail.com> rašė:
>>
>>> I don,t getting errors. And other modules don,t working
>>>
>>> 2016 m. birželio 30 d., ketvirtadienis, Brendan Coles <
>>> notifications@github.com> rašė:
>>>
>>>> It's unlikely that what ever issue you're experiencing is related to
>>>> kubuntu.
>>>>
>>>> Do you receive any JavaScript errors? Do other modules work?
>>>>
>>>> —
>>>> You are receiving this because you authored the thread.
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/beefproject/beef/issues/1276#issuecomment-229670119>,
>>>> or mute the thread
>>>> <https://github.com/notifications/unsubscribe/ATRurtlXmArEyGRsxGBWLAYnCJ37z84Yks5qQ86bgaJpZM4JBir6>
>>>> .
>>>>
>>>
>>>
>>> --
>>> Pagarbiai,
>>> Minijus Žalnierukynas
>>>
>>
>>
>> --
>> Pagarbiai,
>> Minijus Žalnierukynas
>>
>
>
>
> --
> Pagarbiai,
> Minijus Žalnierukynas
>



-- 
Pagarbiai,
Minijus Žalnierukynas

**Comment by bcoles** [comment]
@minijus704 Yes, BeEF can hook browsers running on Windows 7. Is any anti-virus software installed?

BeEF runs on Ubuntu, Fedora, Kali, Debian. It should work on kubuntu.

**Comment by minijus704** [comment]
Antivirus I was disabled.
Maybe VPS blocking beef?

2016 m. liepos 4 d., pirmadienis, Brendan Coles <notifications@github.com>
rašė:

> @minijus704 <https://github.com/minijus704> Yes, BeEF can hook browsers
> running on Windows 7. Is any anti-virus software installed?
>
> BeEF runs on Ubuntu, Fedora, Kali, Debian. It should work on kubuntu.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/beefproject/beef/issues/1276#issuecomment-230257279>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATRursC8pRm7s-R0XJ7FKqaCVj5m0CeSks5qSN4ugaJpZM4JBir6>
> .
>


-- 
Pagarbiai,
Minijus Žalnierukynas

**Comment by bcoles** [comment]
It's unlikely the VPS is blocking BeEF if the hook is working.

**Comment by bcoles** [comment]
Are you using the latest version of BeEF?

Have you allowed port 3000 through your firewall?
