### ISSUE TITLE
Can't load server

### ISSUE THREAD

**Issue by minijus704** [beefproject/beef#1278]
Hi,
i have install kali linux2 on my pc.
get all updates of all needs to beef.
run beef xss and it is working fine, but it is problem when I want hook browser.
When click http://192.168.0.102:3000/demos/basic.html from my computer all it is good working, but when enter this url http://192.168.0.102:3000/demos/basic.html from other computer website don't loading. I try access beef panel from other computer, i can't, connecting, but don't loading.
where problem?

**Comment by bcoles** [comment]
Are you using the latest version of BeEF?

Have you allowed port 3000 through your firewall?
