### ISSUE TITLE
Commenting modules in BEEF

### ISSUE THREAD

**Issue by JohnTet** [beefproject/beef#1285]
There are lot of modules enabled in beef that are of no use to me at the moment (though very helpful overall), I want to customize beed and comment out these modules,

One option is to update config.yaml of each module and set the enabled variable to false, but that invovles going in each module, is there any other to disable all modules of 'browser Module Tree ?

**Comment by bcoles** [comment]
Hi @JohnTet 

No such functionality exists. There was an issue (#545) posted on the bug tracker (five years ago) to add this functionality, which I closed (four years ago) for no good reason.

The quickest and easiest way to achieve this would be to move all the unwanted module directories out of the `modules` directory, or `sed` recursively replace `enabled: true` in `modules/**/config.yaml`.

I can understand wanting to disable modules for performance or security reasons. If you simply want to hide them from the UI, this could likely be achieved with a simple JavaScript hack, but I suspect that's not what you're after.

If you're keen to implement functionality for mass-disabling a module tree, I suggest adding a `config.yaml` file to each parent directory in the `modules` directory with a single `enabled: true/false` property. I say this without having looked at the module parsing code - it might be a horrible idea.

**Comment by antisnatchor** [comment]
As @bcoles said, sed is the key here ;-)
