### ISSUE TITLE
error beef on windows 7  

### ISSUE THREAD

**Issue by heero20** [beefproject/beef#1287]
hi, when install beef on windows 7 86 have this error:
ruby beef
C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/lib/Win32/Cons
ole.rb:12:in `require': cannot load such file -- 2.2/Console_ext (LoadError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/l
ib/Win32/Console.rb:12:in `rescue in <top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/l
ib/Win32/Console.rb:8:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/l
ib/Win32/Console/ANSI.rb:13:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/l
ib/Win32/Console/ANSI.rb:13:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/l
ib/win32console.rb:1:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32console-1.3.2-x86-mingw32/l
ib/win32console.rb:1:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runti
me.rb:86:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runti
me.rb:86:in `block (2 levels) in require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runti
me.rb:81:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runti
me.rb:81:in `block in require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runti
me.rb:70:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runti
me.rb:70:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler.rb:10
2:in `require'
        from C:/beef/core/loader.rb:19:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from beef:42:in `<main>'

please help me

**Comment by bcoles** [comment]
Hi @heero20

Unfortunately BeEF is no longer supported on Windows.
