### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by bkr32** [beefproject/beef#1288]
#### Environment

What version/revision of BeEF are you using?
0.4.6.1-alpha
On what version of Ruby?
ruby 2.3.1p112
On what browser?
firefox
On what operating system?
Kali 2 rolling

#### Configuration

Are you using a non-default configuration?
Yes
Have you enabled or disabled any BeEF extensions?
No

#### Summary

Please provide a summary of the issue.
beef panel does not show up, gives  a "internal server error"

#### Expected Behaviour

What was the expected result?
should display beef login and UI panel

#### Actual Behaviour

What was the actual result?
beef panel does not show up, gives  a "internal server error"

#### Steps to Reproduce

Please provide steps to reproduce this issue.
apt-get remove beef-xss
apt-get install beef-xss
beef-xss OR ./beef

#### Additional Information
Error code 500

**Comment by bcoles** [comment]
@bkr32 Are you getting an `ArgumentError - invalid byte sequence in US-ASCII` error in console?

**Comment by bkr32** [comment]
i get no error in console other than the usual output of UI IP and External IP

**Comment by bkr32** [comment]
(process:47894): GLib-CRITICAL **: g_path_get_basename: assertion 'file_name != NULL' failed
ATTENTION: default value of option force_s3tc_enable overridden by environment.

this is the error i get after some time
