### ISSUE TITLE
BEEF

### ISSUE THREAD

**Issue by DLysys** [beefproject/beef#1289]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?

On what browser?

On what operating system?

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by CrazyPython** [comment]
@DLysys did you just post the issue template?

**Comment by bcoles** [comment]
@CrazyPython that happens a bit. I assume bots. Closing this issue.
