### ISSUE TITLE
/root/beef/core/main/server.rb:127:in `start'

### ISSUE THREAD

**Issue by ArtemBernatskyy** [beefproject/beef#1290]
Beef isn't working. Tested on Debian and Ubuntu (DigitalOcean, x64 both).

Instalation: by your tutorial.

Beef is starting ok, but when i visit my public `IP:3000/ui/authentication` it doesn't load `/ui/media/javascript-min/web_ui_auth.js` (404 error) and displaying static page only.  
Then when i am trying to hook browser via default page `/demos/butcher/index.html` i see a bunch of errors in terminal

    2016-08-10 19:31:21 - ArgumentError - invalid byte sequence in US-ASCII:
    /usr/local/rvm/gems/ruby-2.1.5/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `scan'
    /usr/local/rvm/gems/ruby-2.1.5/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `convert_input'
    /usr/local/rvm/gems/ruby-2.1.5/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
    /usr/local/rvm/gems/ruby-2.1.5/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
    /root/beef/core/main/handlers/modules/beefjs.rb:118:in `new'
    /root/beef/core/main/handlers/modules/beefjs.rb:118:in `build_beefjs!'
    /root/beef/core/main/handlers/hookedbrowsers.rb:50:in `block in <class:HookedBrowsers>'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
    /usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    /usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
    /usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
    /usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
    /usr/local/rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
    /usr/local/rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
    /usr/local/rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
    /usr/local/rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
    /usr/local/rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
    /usr/local/rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
    /usr/local/rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
    /usr/local/rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
    /usr/local/rvm/gems/ruby-2.1.5/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
    /root/beef/core/main/server.rb:127:in `start'
    beef:165:in `<main>'

**Comment by bcoles** [comment]
Hi @ArtemBernatskyy - try this:

```bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by ArtemBernatskyy** [comment]
Thank you, works like a charm. Maybe you will add this to documentation, because this problem is pretty annoying and present in all DIgitalOcean's machines.

**Comment by faccboy** [comment]
Had the same issue, worked for me

**Comment by NolanBrute** [comment]
Hey, Thank you very much Stranger

**Comment by punitp1990** [comment]
Hello,

I did enter those export commands still I continue to get the "ArgumentError - invalid byte sequence in US-ASCII:"
Since I was getting "Warning: System language $LANG 'C' does not appear to be UTF-8 compatible" error, it was solved after the export commands though.
Please help
