### ISSUE TITLE
Beef athenticatio  error

### ISSUE THREAD

**Issue by mojtabamarashee** [beefproject/beef#1293]
When i run beef in the authentication page there is only beef logo and no form

**Comment by mojtabamarashee** [comment]
In the index.html file there is not tag of javascript for authentication.js

**Comment by bcoles** [comment]
Hi @mojtabamarashee

Make sure you've set your locale, as per: https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-

Are you getting any errors in console?

Are you using the latest version of BeEF? Try cloning from GitHub.

**Comment by bcoles** [comment]
Hi @mojtabamarashee

Did you get this working?
