### ISSUE TITLE
BUNDLE INSTALL ERROR

### ISSUE THREAD

**Issue by pritamdstan** [beefproject/beef#1297]
PLEASE HELP. I CANT INSTALL BUNDLE. GIVES ME ERRORS. I AM IN WINDOWS 10 64 BIT in latest ruby and python 27.

C:\beef>bundle  install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using addressable 2.4.0
Using ansi 1.5.0
Using chunky_png 1.3.5
Using daemons 1.2.3
Using fastercsv 1.5.5
Using json 1.8.3
Using json_pure 1.8.3
Using multi_json 1.11.3
Using eventmachine 1.0.9.1
Using http_parser.rb 0.6.0
Using erubis 2.7.0
Using espeak-ruby 1.0.3
Using execjs 2.6.0
Using geoip 1.6.1
Using librex 0.0.999
Using libv8 3.11.8.17
Using mime-types-data 3.2016.0221
Using mojo_magick 0.5.6
Using msgpack 0.5.12
Using parseconfig 1.0.8
Using rack 1.6.4
Using rainbow 2.1.0
Using ref 2.0.0
Using rubyzip 1.2.0
Using tilt 2.0.2
Using tins 1.10.1
Using bundler 1.12.5
Using data_objects 0.10.17
Using dm-core 1.2.1
Using rqrcode 0.10.1
Using em-websocket 0.5.1
Using uglifier 3.0.0
Using mime-types 3.0
Using msfrpc-client 1.0.3
Using rack-protection 1.5.3
Using thin 1.6.4
Using rexec 1.6.3
Installing therubyracer 0.11.4 (was 0.11.0beta1) with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/therubyracer-0.11.4/ext/v8
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20160904-3572-q29s45.rb extconf.rb
checking for main() in -lpthread... yes
checking for v8.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby23-x64/bin/$(RUBY_BASE_NAME)
        --with-pthreadlib
        --without-pthreadlib
        --enable-debug
        --disable-debug
        --with-v8-dir
        --without-v8-dir
        --with-v8-include
        --without-v8-include=${v8-dir}/include
        --with-v8-lib
        --without-v8-lib=${v8-dir}/lib
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.11.8.17/ext/libv8/location.rb:50:in `configure': You have chosen to use the version of V8 found on your system (Libv8::Location::System::NotFoundError)
and *not* the one that is bundle with the libv8 rubygem. However,
it could not be located. please make sure you have a version of
v8 that is compatible with 3.11.8.17 installed. You may
need to special --with-v8-dir options if it is in a non-standard
location

thanks,
The Mgmt

        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libv8-3.11.8.17/lib/libv8.rb:7:in `configure_makefile'
        from extconf.rb:32:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/therubyracer-0.11.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/therubyracer-0.11.4 for inspection.
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/therubyracer-0.11.4/gem_make.out
Using term-ansicolor 1.3.2
Installing do_sqlite3 0.10.17 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/do_sqlite3-0.10.17/ext/do_sqlite3
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20160904-3572-9h83ah.rb extconf.rb
checking for sqlite3.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby23-x64/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/do_sqlite3-0.10.17/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/do_sqlite3-0.10.17 for inspection.
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/do_sqlite3-0.10.17/gem_make.out
Using dm-do-adapter 1.2.0
Using dm-migrations 1.2.0
Using dm-serializer 1.2.2
Using qr4r 0.4.1
Using sinatra 1.4.7
Using rubydns 0.7.3
An error occurred while installing therubyracer (0.11.4), and Bundler cannot
continue.
Make sure that `gem install therubyracer -v '0.11.4'` succeeds before bundling.

C:\beef>bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using addressable 2.4.0
Using ansi 1.5.0
Using chunky_png 1.3.5
Using daemons 1.2.3
Using fastercsv 1.5.5
Using json 1.8.3
Using json_pure 1.8.3
Using multi_json 1.11.3
Using eventmachine 1.0.9.1
Using http_parser.rb 0.6.0
Using erubis 2.7.0
Using espeak-ruby 1.0.3
Using execjs 2.6.0
Using geoip 1.6.1
Using librex 0.0.999
Using libv8 3.11.8.17
Using mime-types-data 3.2016.0221
Using mojo_magick 0.5.6
Using msgpack 0.5.12
Using parseconfig 1.0.8
Using rack 1.6.4
Using rainbow 2.1.0
Using ref 2.0.0
Using rubyzip 1.2.0
Using tilt 2.0.2
Using tins 1.10.1
Using bundler 1.12.5
Using data_objects 0.10.17
Using dm-core 1.2.1
Using rqrcode 0.10.1
Using em-websocket 0.5.1
Using uglifier 3.0.0
Using mime-types 3.0
Using msfrpc-client 1.0.3
Using rack-protection 1.5.3
Using thin 1.6.4
Using rexec 1.6.3
Installing therubyracer 0.11.0beta1 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/therubyracer-0.11.0beta1/ext/v8
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20160904-5452-1k3vo88.rb extconf.rb
checking for main() in -lpthread... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby23-x64/bin/$(RUBY_BASE_NAME)
        --with-pthreadlib
        --without-pthreadlib
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/therubyracer-0.11.0beta1/ext/v8/build.rb:49:in `build_with_rubygem_libv8': undefined local variable or method `libv8_include_flags' for main:Object (NameError)
        from extconf.rb:18:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/therubyracer-0.11.0beta1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/therubyracer-0.11.0beta1 for inspection.
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/therubyracer-0.11.0beta1/gem_make.out
Using term-ansicolor 1.3.2
Installing do_sqlite3 0.10.17 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/do_sqlite3-0.10.17/ext/do_sqlite3
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20160904-5452-1i48ub9.rb extconf.rb
checking for sqlite3.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby23-x64/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/do_sqlite3-0.10.17/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/do_sqlite3-0.10.17 for inspection.
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/do_sqlite3-0.10.17/gem_make.out
Using dm-do-adapter 1.2.0
Using dm-migrations 1.2.0
Using dm-serializer 1.2.2
Using qr4r 0.4.1
Using sinatra 1.4.7
Using rubydns 0.7.3
An error occurred while installing therubyracer (0.11.0beta1), and Bundler
cannot continue.
Make sure that `gem install therubyracer -v '0.11.0beta1'` succeeds before
bundling.

**Comment by bcoles** [comment]
Hi @pritamdstan 

Unfortunately Windows is no longer supported by BeEF.
