### ISSUE TITLE
Problem logging into webside-Kali Linux 4.6.0

### ISSUE THREAD

**Issue by Betawolf1213** [beefproject/beef#1306]
Environment

What version/revision of BeEF are you using?
Latest- Ran apt-get update/upgrade and Dist upgrade
On what version of Ruby?
Latest- Ran apt-get update/upgrade and Dist upgrade
On what browser?
Firefox ESR and Ice Weasel 
On what operating system?
Kali Linux 4.6.0

Configuration
Nothing out of the ordinary  

Have you enabled or disabled any BeEF extensions?
No
Summary

When using a standard user on my Kali Linux box I'm having an issue where I can't log into the web browser with the default username and password. On my root account it works perfectly fine. when making the standard user I made sure to give it access to what it needed why isn't it working?

Expected Behaviour

Allow me to login like it does with my root account. 

Actual Behaviour

Not being able to login 

Steps to Reproduce

None needed it won't allow me to login unless I'm on my root account.

**Comment by bcoles** [comment]
@Betawolf1213 If I understand correctly, when you run BeEF as `root` you can log in ok, but when you run BeEF as another user you cannot login.

It may be that your environment variables are incorrect for your user account. Try this before you run BeEF:

```bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

You should also consider updating to the latest version of BeEF with `./update-beef`, or from GitHub:

```sh
git clone https://github.com/beefproject/beef
cd beef
bundle install
```

**Comment by Betawolf1213** [comment]
An error occurred while installing do_sqlite3 (0.10.17), and Bundler cannot
continue.
Make sure that `gem install do_sqlite3 -v '0.10.17'` succeeds before bundling. 


^^^ Gaining this error when trying to install from github and use the bundle install then tried installing just that gem and got an error as well. 

Building native extensions.  This could take a while...
ERROR:  Error installing do_sqlite3:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/do_sqlite3-0.10.17/ext/do_sqlite3
/usr/bin/ruby2.3 -r ./siteconf20161004-4539-2e4z61.rb extconf.rb
checking for sqlite3.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.


Thanks for the help so far.

**Comment by Betawolf1213** [comment]
Fixed that issue above to come across another one. 



/usr/lib/ruby/vendor_ruby/data_objects/connection.rb:79:in `initialize': unable to open database file (DataObjects::ConnectionError)
	from /usr/lib/ruby/vendor_ruby/data_objects/connection.rb:79:in `new'
	from /usr/lib/ruby/vendor_ruby/data_objects/pooling.rb:181:in `block in new'
	from /usr/lib/ruby/vendor_ruby/data_objects/pooling.rb:176:in `synchronize'
	from /usr/lib/ruby/vendor_ruby/data_objects/pooling.rb:176:in `new'
	from /usr/lib/ruby/vendor_ruby/data_objects/pooling.rb:121:in `new'
	from /usr/lib/ruby/vendor_ruby/data_objects/connection.rb:68:in `new'
	from /usr/lib/ruby/vendor_ruby/dm-do-adapter/adapter.rb:251:in `open_connection'
	from /usr/lib/ruby/vendor_ruby/dm-do-adapter/adapter.rb:276:in `with_connection'
	from /usr/lib/ruby/vendor_ruby/dm-do-adapter/adapter.rb:33:in `select'
	from /usr/lib/ruby/vendor_ruby/dm-migrations/adapters/dm-sqlite-adapter.rb:43:in `table_info'
	from /usr/lib/ruby/vendor_ruby/dm-migrations/adapters/dm-sqlite-adapter.rb:18:in `storage_exists?'
	from /usr/lib/ruby/vendor_ruby/dm-migrations/adapters/dm-do-adapter.rb:90:in `create_model_storage'
	from /usr/lib/ruby/vendor_ruby/dm-migrations/adapters/dm-do-adapter.rb:57:in `upgrade_model_storage'
	from /usr/lib/ruby/vendor_ruby/dm-migrations/auto_migration.rb:73:in `upgrade_model_storage'
	from /usr/lib/ruby/vendor_ruby/dm-migrations/auto_migration.rb:145:in `auto_upgrade!'
	from /usr/lib/ruby/vendor_ruby/dm-migrations/auto_migration.rb:47:in `block in repository_execute'
	from /usr/lib/ruby/vendor_ruby/dm-core/support/descendant_set.rb:64:in `block in each'
	from /usr/lib/ruby/vendor_ruby/dm-core/support/subject_set.rb:211:in `block in each'
	from /usr/lib/ruby/vendor_ruby/dm-core/support/ordered_set.rb:320:in `block in each'
	from /usr/lib/ruby/vendor_ruby/dm-core/support/ordered_set.rb:320:in `each'
	from /usr/lib/ruby/vendor_ruby/dm-core/support/ordered_set.rb:320:in `each'
	from /usr/lib/ruby/vendor_ruby/dm-core/support/subject_set.rb:211:in `each'
	from /usr/lib/ruby/vendor_ruby/dm-core/support/descendant_set.rb:63:in `each'
	from /usr/lib/ruby/vendor_ruby/dm-migrations/auto_migration.rb:46:in `repository_execute'
	from /usr/lib/ruby/vendor_ruby/dm-migrations/auto_migration.rb:27:in `auto_upgrade!'
	from ./beef:102:in `<main>' 


^^ When going to run beef it gives me this. This is the first time I've ever had something in beef really stump me to the point of having to come here. It normally works and even when it doesn't its an easy fix. what on earth is going on?

**Comment by Betawolf1213** [comment]
Solved thank you!

**Comment by ekkimosi** [comment]
How to solve?

**Comment by bcoles** [comment]
@ekkimosi what error are you getting? If the above steps don't work for you, make sure your BeEF is up to date, and create a new issue if the problem persists.

**Comment by ekkimosi** [comment]
Thank you for your very fast response. 
Was a mistake of mine... trying to relaunch BeEF server with web intarface open. Solved closing browser and restarting beef. 
By the way....nice work!
