### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by sasatefa2009** [beefproject/beef#1313]
What version/revision of BeEF are you using?
0.4.6.1-alpha

On what version of Ruby?
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

On what browser?
firefox 45.4.0

On what operating system?
kali 2016.2

#### Configuration

Are you using a non-default configuration?
no
Have you enabled or disabled any BeEF extensions?
no

#### Summary
BeEF was working very good and suddenly after restarting kali and running beef
and trying to log into beef config page http://192.168.1.7:3000/ui/panel
it says " Internal server error "

**Comment by bcoles** [comment]
BeEF version 0.4.6.1-alpha is over a year old. Try cloning the latest version from GitHub.

```sh
git clone https://github.com/beefproject/beef
cd beef
bundle install
```

**Comment by sasatefa2009** [comment]
thanks for the fast response 
i've given that error

Installing rubydns 0.7.3
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/var/lib/gems/2.3.0/gems/do_sqlite3-0.10.17/ext/do_sqlite3
/usr/bin/ruby2.3 -r ./siteconf20161020-2433-a34g1u.rb extconf.rb
checking for sqlite3.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-sqlite3-dir
	--without-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/do_sqlite3-0.10.17/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/do_sqlite3-0.10.17
for inspection.
Results logged to
/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/do_sqlite3-0.10.17/gem_make.out

An error occurred while installing do_sqlite3 (0.10.17), and Bundler
cannot continue.
Make sure that `gem install do_sqlite3 -v '0.10.17'` succeeds before
bundling.
root@kali:~/beef#

**Comment by sasatefa2009** [comment]
using  "apt-get install libsqlite3-dev"  fixed the problem

if you want you can add anything or close the issue
