### ISSUE TITLE
BeEF version on Kali up to date?

### ISSUE THREAD

**Issue by griddd** [beefproject/beef#1314]
In looking at the Kali repos, the version of BeEF there is up to date [http://git.kali.org/gitweb/?p=packages/beef-xss.git;a=summary](url)  However, when I start BeEF, it lists the version as 0.4.6.1-alpha.  

I frequently run apt-get update && apt-get dist-upgrade on Kali to keep it current.  My /etc/apt/sources.list is set correctly to the Kali repos.  

Is this just a simple bug whereby the version number hasn't been incremented?  Or am I running an outdated copy of BeEF because the Kali repos are incorrect?

Thanks for your help!

**Comment by antisnatchor** [comment]
this is a Kali issue.

The best way to run BeEF is to install RVM, then gem install bundler, and then bundle install.

**Comment by griddd** [comment]
Thanks for the tip, Antisnatchor.
