### ISSUE TITLE
Beef over WAN?

### ISSUE THREAD

**Issue by BrickleRex** [beefproject/beef#1317]
Hello sir. I have tried many guides for using beef xss over wan with a neighbour of mine who gave me permission to pentest. But i cannot seem to get it working. After i edit the config.yaml files, i still cannot access the web ui using my external ip. Note that i do not directly use my external ip but a ddns provided by No-IP. Also, apache doesnt recognise my external ip when he tries it. Please help.

**Comment by bcoles** [comment]
Hi @BrickleRex 

This is more than likely an issue with your port forwarding configuration.

All the config.yaml file does is tell BeEF what the WAN IP is so it knows the hook URL. This is required for hooking. The admin web interface should be accessible without making any changes to the config.yaml at all. If it's not accessible then your port forwarding is misconfigured.

Perhaps your ISP blocks port 3000? You could try another port.

**Comment by BrickleRex** [comment]
Can u give me a complete step by step guide on how to make this work from the beginning. Including how to make an apache server accessible through WAN.

**Comment by bcoles** [comment]
Read the documentation for your router to configure port forwarding. Test and troubleshoot the port forwarding.

Configure BeEF as per the FAQ:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

As you're rusing DDNS you'll also need to take note of:

https://github.com/beefproject/beef/wiki/FAQ#can-i-use-a-domain-name-instead-of-ip-address-for-the-beef-hook
