### ISSUE TITLE
permitted_ui_subnet multiple networks 

### ISSUE THREAD

**Issue by NikolayDachev** [beefproject/beef#1319]
I'm not sure but I think will be good idea to be able to have options for multiple network permission to ui 

for example something like:
permitted_ui_subnet = ['192.168.1.0/24', '192.168.23.0/24']  etc..

The reason to ask about that is because in my case I have second network accessible via VPN. 
The idea is to have beef ui accessible via my phone via this second vpn network but also will be useful and for 'permitted_hooking_subnet '

If this is possible let me know and close this issue 

```
# @note check source ip address of browser
      permitted_hooking_subnet = config.get('beef.restrictions.permitted_hooking_subnet')
      target_network = IPAddr.new(permitted_hooking_subnet)
      if not target_network.include?(request.ip)
        BeEF::Core::Logger.instance.register('Target Range', "Attempted hook from out of target range browser (#{request.ip}) rejected.")
        error 500
end

 #
  # Check the UI browser source IP is within the permitted subnet
  #
  def permited_source?(ip)
    # get permitted subnet 
    config = BeEF::Core::Configuration.instance
    permitted_ui_subnet = config.get('beef.restrictions.permitted_ui_subnet')
    target_network = IPAddr.new(permitted_ui_subnet)
    
    # test if ip within subnet
    return target_network.include?(ip)
  end
```

**Comment by bcoles** [comment]
@NikolayDachev This is a good idea. I can't promise when it will be implemented.

You're welcome to do a PR.

In the interim you could hard-code the subnet.

**Comment by NikolayDachev** [comment]
Thank you!

**Comment by bcoles** [comment]
In the short term, the easiest way to solve this issue is to run BeEF behind a reverse proxy.

However, there's also a bug related to the `permitted_ui_subnet` and `permitted_hookig_subnet` config directives, as IPv6 is not supported. #519

Augmenting these directives to accept multiple values will resolve these issues.

**Comment by bcoles** [comment]
This should now be fixed.

`permitted_ui_subnet` and `permitted_hooking_subnet` are expected to be arrays in `config.yaml`, allowing multiple subnets to be specified.
