### ISSUE TITLE
Kali linux beef dont work Java payload

### ISSUE THREAD

**Issue by karencho777** [beefproject/beef#1320]
Hello i am using Kali Linux 2016.2 ,latest version of Beef framework.... not working Java Payload module  and dont work Fake Notification bar too can you tell me why?

**Comment by karencho777** [comment]
i have test it on Firefox last version and Google Chrome

**Comment by bcoles** [comment]
What error are you getting?

**Comment by karencho777** [comment]
in console there is no error i guess.... there i need to look to see errors? i just add java payload but on victims browser nothing appears ... same with fake stuff

**Comment by bcoles** [comment]
The Fake Notification modules work fine. Can't reproduce.

For the Java Payload, on latest Kali you should get a prompt to run Java.

![java-payload](https://cloud.githubusercontent.com/assets/434827/25298021/02e86920-2735-11e7-88a5-5dadbcc52751.png)

**Comment by mohamedaminebelghith** [comment]
Hi , I don't know why Java Payload doesn't work for me . Are you sure that The module Java Payload can force browsers such (chrome/firefox...) to answer the request .? 
I saw some forums that says : Recently , browsers blocks Beef Attack ? Is it true ?
