### ISSUE TITLE
Browser Hooking - Javascript Disabled

### ISSUE THREAD

**Issue by TomAshley303** [beefproject/beef#1321]
I was thinking about what could be done if a browser were to visit a beef page with Javascript disabled. Of course Javascript isn't the only attack surface. For instance, if you want to keep a constant connection to the user without Javascript, simply embed a very low bitrate media file. Of course it wouldn't actually be a media file, just a script sending the header of one and that way you'll have a connection to the browser for as long as you can keep one of these fake streams going to the browser.

And that's a start.

**Comment by bcoles** [comment]
Thanks @TomAshley303 - This is an interesting idea.

Unfortunately we don't have the development bandwidth for reworking such an integral part of the command and control handling. There's also the issue of what useful browser behaviors could be induced over such a channel - beyond simply maintaining a connection - to make such fundamental changes viable.

It could make an interesting research topic. We accept pull requests ;)
