### ISSUE TITLE
beefjs not processing all required js files.

### ISSUE THREAD

**Issue by neeksor** [beefproject/beef#1323]
Using latest version from git. Seems that net/requester.js doesn't get processed by the BeEFJS function that I assume renames beef in the JS files to some random string.

VM1993:18 Uncaught ReferenceError: beef is not defined(…)(anonymous function) @ VM1993:18socket.onmessage @ hook.js:formatted:9126
VM1995:18 Uncaught ReferenceError: beef is not defined(…)(anonymous function) @ VM1995:18socket.onmessage @ hook.js:formatted:9126

line 26 core/main/handlers/modules/beefjs.rb:
```
# @note BeEF libraries: need Eruby evaluation and obfuscation
beef_js_sub_files = %w(beef.js browser.js browser/cookie.js browser/popup.js session.js os.js hardware.js dom.js logger.js net.js updater.js encode/base64.js encode/json.js net/local.js init.js mitb.js net/dns.js net/connection.js net/cors.js are.js)
```

I'm not sure how many other libraries are not being processed as I have not tested further.

**Comment by bcoles** [comment]
Thanks @neeksor 

I've investigated this issue and identified a few libraries were missing from `beef_js_sub_files`, as per the diff below. However, quick testing revealed that this does not resolve the issue with the requester when evasion is enabled. Further investigation required.

```diff
diff --git a/core/main/handlers/modules/beefjs.rb b/core/main/handlers/modules/beefjs.rb
index a33f861..02c55f5 100644
--- a/core/main/handlers/modules/beefjs.rb
+++ b/core/main/handlers/modules/beefjs.rb
@@ -24,7 +24,7 @@ module BeEF
             ext_js_sub_files = %w(lib/jquery-1.10.2.min.js lib/jquery-migrate-1.2.1.min.js lib/evercookie.js lib/json2.js lib/mdetect.js lib/jquery.blockUI.js)
 
             # @note BeEF libraries: need Eruby evaluation and obfuscation
-            beef_js_sub_files = %w(beef.js browser.js browser/cookie.js browser/popup.js session.js os.js hardware.js dom.js logger.js net.js updater.js encode/base64.js encode/json.js net/local.js init.js mitb.js net/dns.js net/connection.js net/cors.js are.js)
+            beef_js_sub_files = %w(beef.js browser.js browser/cookie.js browser/popup.js geolocation.js session.js os.js hardware.js dom.js logger.js net.js updater.js encode/base64.js encode/json.js net/local.js init.js mitb.js net/dns.js net/connection.js net/cors.js net/requester.js net/xssrays.js net/portscanner.js are.js)
             # @note Load websocket library only if WS server is enabled in config.yaml
             if config.get("beef.http.websocket.enable") == true
               beef_js_sub_files << "websocket.js"
```

**Comment by bcoles** [comment]
Commit 1a68c165bba810e556e827b6050b29660ce37fba should have added all the missing libraries.

Closing this issue, and opened #1386 for the defect in Requester when evasion extension is enabled.
