### ISSUE TITLE
beef framework can not find the target of XP

### ISSUE THREAD

**Issue by KesonLai** [beefproject/beef#1326]
My version:
BeEF 0.4.6.1-alpha
kali 2016.2
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
Question:
My computer can find target of target with xssf,but I can't find find the target of XP!
I can open the website http://localhost:3000/demos/butcher/index.html in my XP.
Help!!

**Comment by bcoles** [comment]
BeEF version 0.4.6.1-alpha is over a year old. Try cloning the latest version from GitHub.

``` sh
git clone https://github.com/beefproject/beef
cd beef
bundle install
```
