### ISSUE TITLE
No users are online or offline in the hook browser

### ISSUE THREAD

**Issue by ArusAT** [beefproject/beef#1332]
Hi! i need help. I do not see the victims in online browser or in offline browser, please!!!

When I enter the Hook I get the following error:

2016-12-27 01:49:51 - ArgumentError - invalid byte sequence in US-ASCII:
        /usr/lib/ruby/vendor_ruby/erubis/enhancer.rb:647:in `scan'
        /usr/lib/ruby/vendor_ruby/erubis/enhancer.rb:647:in `convert_input'
        /usr/lib/ruby/vendor_ruby/erubis/converter.rb:36:in `convert'
        /usr/lib/ruby/vendor_ruby/erubis/engine.rb:30:in `initialize'
        /usr/share/beef-xss/core/main/handlers/modules/beefjs.rb:117:in `new'
        /usr/share/beef-xss/core/main/handlers/modules/beefjs.rb:117:in `build_beefjs!'
        /usr/share/beef-xss/core/main/handlers/hookedbrowsers.rb:50:in `block in <class:HookedBrowsers>'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1611:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1611:in `block in compile!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:975:in `block (3 levels) in route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:994:in `route_eval'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:975:in `block (2 levels) in route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1015:in `block in process_route'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1013:in `catch'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1013:in `process_route'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:973:in `block in route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:972:in `each'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:972:in `route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1085:in `block in dispatch!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `block in invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `catch'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1082:in `dispatch!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:907:in `block in call!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `block in invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `catch'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:907:in `call!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:895:in `call'
        /usr/lib/ruby/vendor_ruby/rack/nulllogger.rb:9:in `call'
        /usr/lib/ruby/vendor_ruby/rack/head.rb:13:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:182:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:2013:in `call'
        /usr/lib/ruby/vendor_ruby/rack/urlmap.rb:66:in `block in call'
        /usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
        /usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:86:in `block in pre_process'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `catch'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `pre_process'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
        /usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run_machine'
        /usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run'
        /usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
        /usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
        /usr/share/beef-xss/core/main/server.rb:127:in `start'
        ./beef:154:in `<main>'

**Comment by bcoles** [comment]
Set the appropriate locale:

```bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

As per: https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-

**Comment by ArusAT** [comment]
I write that direct code in console? Or do I have to modify a file?

**Comment by bcoles** [comment]
In the terminal before you launch BeEF.

**Comment by abhishek-pandit1** [comment]
thank you so much man its working ...
