### ISSUE TITLE
'std::runtime_error'   what():  Encryption not available on this event-machine Aborted

### ISSUE THREAD

**Issue by dimpol** [beefproject/beef#1335]
I have seen similar issues but i am not able to resolve the following error when enabling HTTPS in config.yaml.  apt-get install libssl-dev didn't help.

terminate called after throwing an instance of 'std::runtime_error'
  what():  Encryption not available on this event-machine
Aborted

OS: Kali Linux (rolling 2016.2)
beef:0.4.7.0-alpha
ruby:ruby 2.3.0p0

Maybe there are some steps i should do for enabling HTTPS that i missed?

**Comment by bcoles** [comment]
Hi @dimpol 

It might be that you've compiled Ruby and/or eventmachine without OpenSSL.

Try `apt-get install openssl-dev` and then `gem install eventmachine` again.

**Comment by dimpol** [comment]
It looks that i was using 2 different versions of eventmachine concurrently (apparently the system was using the one which was not compiled with SSL) gem uninstall eventmachine and bundle install on beef folder solved the issue. Thank you bcoles !
