### ISSUE TITLE
Windows computer is not showing up on the online browsers!

### ISSUE THREAD

**Issue by floppykirby** [beefproject/beef#1339]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?

5.0

On what version of Ruby?

1.0

On what browser?
Firefox
On what operating system?
 
Kali Linux

#### Configuration

Are you using a non-default configuration?

No

Have you enabled or disabled any BeEF extensions?

NO

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

The expected result was that the computer would show up on online browser

#### Actual Behaviour

What was the actual result?

It did not show up on any!

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
Hi @floppykirby 

Version 0.4.5.0 of BeEF is ancient; as is Ruby 1.0.

Try using the latest version of BeEF with Ruby 2.1+
