### ISSUE TITLE
Error! Could not retrieve the response.

### ISSUE THREAD

**Issue by x99frankov** [beefproject/beef#1340]
Hello!
Sorry, I bad speak English, and I'm bad at programming
I try to use beef.
I install beef, it works. I try to use the tunneling and Forge Request.
When I'm testing on demos/basic.html everything works fine.
But when I do it on other sites I'm having problems.
For example, I hooked browser on the host nosocivhl.justclick.ru:80. Then in the admin panel navigate to the tab Rider -> Forge Request. Write the query "GET / HTTP/1.0 Host: nosocivhl.justclick.ru:80".
This request is sent to the hooked browser, where it runs and returns back. 
<img width="783" alt="1" src="https://cloud.githubusercontent.com/assets/25106512/21938979/bc8fb180-d9ce-11e6-9aa0-b0e9b5de569e.png">
But when I try to see the result it says error "Error! Could not retrieve the response." and nothing shows.
When I use proxy, it begins to load the page, the browser loads the page title and nothing else loads.

Tell me, please, what could be the problem.

**Comment by x99frankov** [comment]
Here is the error which shows the terminal:

324124522 HTTP/1.1" 200 - 0.0219
E, [2017-01-13T18:18:09.516899 #6269] ERROR -- : Unexpected error while processing request: "\xD0" from ASCII-8BIT to UTF-8
        /root/beef/extensions/requester/controllers/requester.rb:180:in `encode'
        /root/beef/extensions/requester/controllers/requester.rb:180:in `to_json'
        /root/beef/extensions/requester/controllers/requester.rb:180:in `get_zombie_response'
        /root/beef/extensions/admin_ui/classes/httpcontroller.rb:65:in `call'
        /root/beef/extensions/admin_ui/classes/httpcontroller.rb:65:in `run'
        /root/beef/extensions/admin_ui/handlers/ui.rb:31:in `call'
        /usr/local/rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'
        /usr/local/rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'
        /usr/local/rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'
        /usr/local/rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
        /usr/local/rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
        /usr/local/rvm/gems/ruby-2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
        /usr/local/rvm/gems/ruby-2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
        /usr/local/rvm/gems/ruby-2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
        /usr/local/rvm/gems/ruby-2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
        /usr/local/rvm/gems/ruby-2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
        /usr/local/rvm/gems/ruby-2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
        /usr/local/rvm/gems/ruby-2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
        /usr/local/rvm/gems/ruby-2.3.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
        /usr/local/rvm/gems/ruby-2.3.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
        /root/beef/core/main/server.rb:125:in `start'
        beef:165:in `<main>'

**Comment by bcoles** [comment]
Hi @x99frankov

Does this help?

```bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by bcoles** [comment]
Hi @x99frankov - any luck with this?

**Comment by bcoles** [comment]
Thanks for reporting this @x99frankov 

It looks like this is one of our many UTF-8 related bugs. I'll implement a patch for this soon.

**Comment by bcoles** [comment]
Hi @x99frankov

This should now be fixed.
