### ISSUE TITLE
Cant install under ruby-2.4

### ISSUE THREAD

**Issue by wifislax-ng** [beefproject/beef#1341]
When try to install gems under ruby-2.4 some gems fails.

First is json 1.8.3 , need at least 1.8.5  (1.8.6 is available)
Second is msgpack-0.5.12 (not build)

Envoriment is slackware64-current with ruby-2.4.0

gem install bundler
clone beef git
cd beef
bundle install

And error building gems... (some old versions not build under ruby-2.4.0)

Thanks for your work!

Waiting fixes.

**Comment by bcoles** [comment]
Thanks @wifislax-ng 

I've gone through the dependencies. It's just the `msfrpc-client` gem holding up support for Ruby 2.4.0.

The gem hasn't been updated in over two years. I've prodded the MSF guys on IRC and [created an issue](https://github.com/rapid7/msfrpc-client/issues/1).

In the interim, if for some reason you're desperate to get BeEF running under Ruby 2.4.0, you can change JSON 1.8.3 to 1.8.6; comment out the requirement for `msfrpc-client`; `bundle install`; and ensure the metasploit extension for BeEF is disabled in the config.

**Comment by busterb** [comment]
I started updating msfrpc-client, sorry for the holdup. We've had our own snow-plowing trying to get all of our upstream gems ready for Ruby 2.4 as well.

**Comment by bcoles** [comment]
Hi @wifislax-ng 

I've updated the dependencies and have BeEF running with Ruby 2.4.0 on Debian. Please update BeEF and let us know if you have any issues.

**Comment by bcoles** [comment]
Thanks @busterb 

Preliminary tests indicate msfrpc-client 1.1.0 is working as intended. I ran into a few issues, but I think they're BeEF related. I'll let you know if there's any issues when I have a chance to investigate further.
