### ISSUE TITLE
Reloadable ARE rules for (MiTB Persistence)?

### ISSUE THREAD

**Issue by leetu** [beefproject/beef#1344]
Hello, and thank you all for the amazing project and hard work!

Is there a feature or is it possible to reload a custom ARE rule for real persistence 'e.g MiTB'?

I connect as 'client' for the first time and my 'BeEF ARE Rule' gets triggered and in my case i get 'MiTB' poisoned and the ARE rule worked. But 2nd time for example, 'the client' revisits url again (2nd time) '10minutes / few hours later' the BeEF Hook gets loaded again but this time (MiTB ARE Rule does not get autoloaded) and the persistence fails. 

I need to flush databases everytime to get the, 'ARE rules' running again.

If this is not possible im sure this would be a great feature for the project, few improvement on ARE.
For example an option/trigger to reload the same ARE rule, if 'the client' have been offline for more than (3minutes) it should be able to re-run previous ARE rule again. E.g: ('MiTB') for good autorun persistence.

Keep up the good work!

**Comment by xntrik** [comment]
Hey @leetu under the wiki page https://github.com/beefproject/beef/wiki/Autorun-Rule-Engine you can see there are API calls to 'trigger' modules.

For example, to list all available ARE rules:
`curl http://beefhost:3000/api/autorun/rule/list/1?token=xyz`

To trigger an arbitrary rule:
`curl http://beefhost:3000/api/autorun/rule/trigger/1?token=xyz`

You can also upload new rules with a POST request:
`curl -H "Content-Type: application/json; charset=UTF-8" --data "@ie_win_htapowershell.json" -X POST http://beefhost:3000/api/autorun/rule/add?token=xyz`

In each instance, the xyz token is the authentication token, displayed on load (you can also query it via the API too)

**Comment by leetu** [comment]
Hello @xntrik , and thanks for the help!

I know rules for triggering, but what im trying to explain, is a option that completely flushes the old rules.

Your fix, require the 'client' to already be hooked before the trigger will actually trigger/load.

Which mean, that if client connect second time, you rule doesnt get triggered. Your rule only gets loaded/triggered if the client is already hooked into BeEF, it wont trigger clients reconnecting to BeEF and get hooked.

In reflected XSS cases you only have few seconds before client is away from page, unlike stored xss where you sometimes have minutes to reload up a module. My current solution will have to restart beef every second time i want to reload / obtain (MiTB Persistence).

If we could only flush the rules there would be no problem!
Here is my quick and noisy syntax, for flushing an arbitary rule, as (MiTB)(not recommended)

while true;do curl http://beefhost/api/autorun/rule/trigger/1?token=xyz;sleep 3;done
