### ISSUE TITLE
ARE trouble with Get_cookie

### ISSUE THREAD

**Issue by benichmt1** [beefproject/beef#1351]
Hi, 
I have the latest version of beef running on Ubuntu 16.
I am trying to work with the ARE rules but I'm running into some difficulty. I'm able to use the samples correctly by moving them to the enabled folder, but I'd like to be able to auto-send domain cookies when a browser is hooked. Here's what I have in my get_cookie.json:

```
{"name": "Get Cookie",
  "author": "author",
  "browser": "ALL",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [
    {"name": "get_cookie",
      "condition": null,
      "options": {
      }
    }
  ],
  "execution_order": [0],
  "execution_delay": [0],
  "chain_mode": "sequential"
}
```
For some reason, I get the following output when it runs:
`status: UNKNOWN) from command module [cid:2, mod: 221, name:'Get Cookie`

At this point, I'm not sure if it has actually executed and I am not seeing where the output of the command is, or if my syntax has an error.

Thanks.

**Comment by bcoles** [comment]
Hi @benichmt1 

It looks like your ARE rule is working as intended.

The output you're getting means that the module has returned a result. (The result may or may not be empty, depending on whether the cookie(s) make use of `HttpOnly`).

The Get Cookies module has only one return point, so the fact you're getting that output means it's working.

The ARE was implemented within the last twelve months and not all modules have been updated to return a status, hence the `status: UNKNOWN`. BeEF has almost 300 modules so updating them all is somewhat time consuming.

**Comment by benichmt1** [comment]
Thanks for the quick response. Looks like I can in fact view it in the Commands tab.

I'll have to look into getting this module to return a status since it's in my most used.

**Comment by bcoles** [comment]
It should be easy to implement. Here's the appropriate return values:

* beef.are.status_error()
* beef.are.status_success()
* beef.are.status_unknown()

**Comment by benichmt1** [comment]
Cool, thanks. I did some testing and this seemed to work although I had issues getting debugging output to display.

**Comment by bcoles** [comment]
Set `client_debug: true` to enable client-side debugging.
