### ISSUE TITLE
Does beef can be injected by X-Forwarded-For?

### ISSUE THREAD

**Issue by whirlwind110** [beefproject/beef#1354]
x-forwarded-for:8.8.8.8‘

```
E, [2017-02-04T14:24:30.715815 #11752] ERROR -- : Unexpected error while processing request: invalid address
	/usr/lib/ruby/2.3.0/ipaddr.rb:560:in `in6_addr'
	/usr/lib/ruby/2.3.0/ipaddr.rb:497:in `initialize'
	/usr/lib/ruby/2.3.0/ipaddr.rb:515:in `new'
	/usr/lib/ruby/2.3.0/ipaddr.rb:515:in `coerce_other'
	/usr/lib/ruby/2.3.0/ipaddr.rb:171:in `include?'
	/home/****/****/beef/extensions/admin_ui/controllers/authentication/authentication.rb:114:in `permited_source?'
	/home/****/****/beef/extensions/admin_ui/controllers/authentication/authentication.rb:49:in `login'
	/home/****/****/beef/extensions/admin_ui/classes/httpcontroller.rb:65:in `call'
	/home/****/****/beef/extensions/admin_ui/classes/httpcontroller.rb:65:in `run'
	/home/****/****/beef/extensions/admin_ui/handlers/ui.rb:31:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
	/var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
	/var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
	/var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
	/home/****/****/beef/core/main/server.rb:125:in `start'
	./beef:165:in `<main>'

```

**Comment by bcoles** [comment]
Thanks @whirlwind110 

Looks like it's possible to bypass the `permitted_ui_subnet: 127.0.0.1/32` IP address access controls by providing `X-Forwarded-For: 127.0.0.1/32`.

```
curl 'http://beef.local:3000/ui/authentication/login' --data 'username-cfrm=beef&password-cfrm=beef' -H 'X-Forwarded-For: 127.0.0.1/32'
```

**Comment by bcoles** [comment]
I've added a check to prevent bypassing `/32` IP address access controls by spoofing the `/32` address in the `X-Forwarded-For` header, such as `127.0.0.1/32`, in 06263790c80a990fd975a09b2eb8c62812f2b639.

This prevents bypassing `/32` access controls, but won't help if the access controls are more permissive, such as `/24` or `/16`. In these instances the IP address access controls can still be bypassed by supplying a valid IP address within the permitted range in the `X-Forwarded-For` header.

For example, `permitted_ui_subnet: "10.1.1.1/24"` could by bypassed by providing `X-Forwarded-For: 10.1.1.666`

Ideally BeEF should be running behind a reverse proxy which would prevent this issue.

Unfortunately we need to continue to support `X-Forwarded-For` for the same reason.

The best defense is to change the default username and password to something more secure using the `beef.credentials.user` and `beef.credentials.passwd` options respectively.

Closing this issue.

**Comment by bcoles** [comment]
A configuration option should be implemented, so users can specify whether BeEF is running behind a reverse proxy.

A `beef.http.use_x_forward_for` option exists and is used in `core/main/handlers/hookedbrowsers.rb` - but for unrelated reasons, and it's never initialized.
