### ISSUE TITLE
 My script to Install Beef-xss in kali-linux from github and resolving all Problem's with kali beef

### ISSUE THREAD

**Issue by ziflar** [beefproject/beef#1356]
To resolve all problem's with beef-xss in kali linux : 
i've edited a script to install it from github : 

## step's to Install it 

```
git clone https://github.com/ziflar/beef-xss_fix
cd beef-xss_fix/ && chmod +x beef-resolve.sh && ./beef-resolve.sh
```
let's the script delete beef insalled in kali and it's clone the new one from github 

## Tuto

[Tuto from here](https://www.youtube.com/watch?v=Z7G2k4ZXoHA&feature=youtu.be)

**Comment by kalifan** [comment]
what do you mean when you say resolve all problems? what are these problems or what do you fix about fix thank you..

**Comment by ziflar** [comment]
@kalifan 
My script was edited 6 months before to fix beef problem's on kali rolling as hocked browser and login panel:

On kali linux beef and metasploit are late for their upgrade not as on github.

The update on kali may take months to go from one version to another

Then my script can simply install beef from github and proceed to its update any time we want and keep on use it as beef kali

**Comment by kalifan** [comment]
@ziflar thanks my friend.

**Comment by InnerSoul** [comment]
@ziflar @beefproject still it is not loading with metasploit modules :( i kept metasploit extension to true and changed the host and callback host to my ip, and loaded msgrpc plugin in metasploit, but still beef is not loading with metasploit modules. can you say the steps for making it work?

**Comment by kalifan** [comment]
@InnerSoul Hi maybe here is the solution for your problem:
https://github.com/beefproject/beef/issues/1322

**Comment by KewL-1** [comment]
Awesome script bro keep up the good work and thanks!

**Comment by ziflar** [comment]
@KewL-1 thank you

**Comment by maxrep66** [comment]
hi everybody i have a problem with that script now the config.yaml have chage 
now i dont have dns_host"ip" 

i have db_host but no dns_host 
i have integrate metasploit with beef but i cant work in wan i dont now how to configure this new config.yaml without dns_host i run my noip1 my apache1 and my postgresql but i cant work and hook out of lan pls if sombody knows help me i have been working in it 2 weeks and i cant thx to everybody here

**Comment by bcoles** [comment]
@maxrep66 

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
https://github.com/beefproject/beef/wiki/FAQ#can-i-use-a-domain-name-instead-of-ip-address-for-the-beef-hook

**Comment by 8181war** [comment]
git clone https://github.com/ziflar/beef-xss_fix
cd beef-xss_fix/ && chmod +x beef-resolve.sh && ./beef-resolve.sh

**Comment by x0rw** [comment]
if you faced any problem just add **sudo** 
```
git clone https://github.com/ziflar/beef-xss_fix
cd beef-xss_fix/ && sudo chmod +x beef-resolve.sh && sudo ./beef-resolve.sh
```

**Comment by ChopperCharles** [comment]
Any chance on a fix for getting Beef to download and work properly in the 2020 version of kali linux, virtualbox VM edition? It's completely borked.

**Comment by TOXIC00JATT** [comment]
bro its having authenticator what to do with it and i dont know how to deal with it so provide me the soluiton please............
