### ISSUE TITLE
beEF installation wiki change

### ISSUE THREAD

**Issue by legit** [beefproject/beef#1358]
The first part, Install dependencies, says: `source ~/.rvm/scripts/rvm`.
This did not work for me (Debian). RVM told me this:
 * To start using RVM you need to run `source /etc/profile.d/rvm.sh`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

That worked, so maybe you could change it. 👍

**Comment by bcoles** [comment]
Thanks @legit

Updated
