### ISSUE TITLE
Cannot remote access beEF

### ISSUE THREAD

**Issue by legit** [beefproject/beef#1359]
#### Environment

Latest version of beEF
Ruby 2.3.0

Debian 7 (Wheezy)

#### Configuration
I'm using the default configuration
I did not enable/disable any beEF extension.

#### Summary

I cannot access the beEF webserver from another system/network.

#### Expected Behaviour

I should be able to connect to beEF but this is not working.

#### Actual Behaviour

```
> nc beefIP 3000-v
[beefIP] 3000 (?): TIMEDOUT (10060:10060)
```

Tried enabling debugging, have tried everything in this issue as well: 
https://github.com/beefproject/beef/issues/1237

**Comment by bcoles** [comment]
Sounds like a network issue.

Have you tried disabling the DNS extension?

If you have multiple versions of Ruby installed, have you tried using an older version of Ruby?

**Comment by legit** [comment]
I have tried using other versions and disabling the DNS extension did not fix it. :[

**Comment by bcoles** [comment]
@legit it sounds like a network issue.

Can you confirm you've opened port 3000 in the host firewall? Verify with `nc -lvp 3000` and see if you can connect from a remote host.

Can you confirm you can connect to the web interface on the local network interface http://127.0.0.1:3000 ?

In addition to enabling debugging with `beef.debug: true`, try also enabling HTTP debugging with `beef.http.debug: true`.

**Comment by legit** [comment]
Thank you so much. I opened port 3000 before but then I restarted the server without doing iptables-save. Works great now!
