### ISSUE TITLE
Cross Domain error

### ISSUE THREAD

**Issue by legit** [beefproject/beef#1371]
Hi,
Whatever the URL is I want to visit using the beEF proxy (using public IP to connect to proxy, beefproject is hosted on VPS and I use it on my own computer), I always get this response: 
ERROR: Cross Domain Request. The request was sent however it is impossible to view the response.
Is this normal? If it isn't, how do I fix this?

**Comment by bcoles** [comment]
This is normal if you're trying to access a page on a different origin.

**Comment by bcoles** [comment]
For example, if the browser is hooked on `http://example.local:1337/path` then you will only be able to view the response of HTTP requests `example.local:1337`.

Try checking the network tab of the browser developer tools on the hooked browser to verify whether the request was sent.
