### ISSUE TITLE
beef cannot detect any details abount hooked browser

### ISSUE THREAD

**Issue by BenSimp** [beefproject/beef#1372]
#### Environment

What version/revision of BeEF are you using?
version: '0.4.7.0-alpha'
On what version of Ruby?
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
On what browser?
All
On what operating system?
Windows, Linux

#### Configuration

    # BeEF Configuration file
      beef:
      version: '0.4.7.0-alpha'
      # More verbose messages (server-side)
      debug: false
      # More verbose messages (client-side)
      client_debug: false
      # Used for generating secure tokens
      crypto_default_value_length: 80

    # Interface / IP restrictions
    restrictions:
        # subnet of IP addresses that can hook to the framework
        permitted_hooking_subnet: "0.0.0.0/0"
        # subnet of IP addresses that can connect to the admin UI
        #permitted_ui_subnet: "127.0.0.1/32"
        permitted_ui_subnet: "0.0.0.0/0"

    # HTTP server
    http:
        debug: true #Thin::Logging.debug, very verbose. Prints also full exception stack trace.
        host: "0.0.0.0"
        port: "5555"

        # Decrease this setting to 1,000 (ms) if you want more responsiveness
        #  when sending modules and retrieving results.
        # NOTE: A poll timeout of less than 5,000 (ms) might impact performance
        #  when hooking lots of browsers (50+).
        # Enabling WebSockets is generally better (beef.websocket.enable)
        xhr_poll_timeout: 1000

        # Reverse Proxy / NAT
        # If BeEF is running behind a reverse proxy or NAT
        #  set the public hostname and port here
        #public: ""      # public hostname/IP address
        #public_port: "" # experimental

        # DNS
        dns_host: "8.8.8.8"
        dns_port: 53

        # Web Admin user interface URI
        web_ui_basepath: "/xxxxxui"

        # Hook
        hook_file: "/fhgfhgfdh.js"
        hook_session_name: "fdsafdsa"
        session_cookie_name: "hgffhfdh"

        # Allow one or multiple origins to access the RESTful API using CORS
        # For multiple origins use: "http://browserhacker.com, http://domain2.com"
        restful_api:
            allow_cors: false
            cors_allowed_domains: "http://browserhacker.com"

        # Prefer WebSockets over XHR-polling when possible.
        websocket:
            enable: true
            port: 61985 # WS: good success rate through proxies
            # Use encrypted 'WebSocketSecure'
            # NOTE: works only on HTTPS domains and with HTTPS support enabled in BeEF
            secure: true
            secure_port: 61986 # WSSecure
            ws_poll_timeout: 1000 # poll BeEF every second

        # Imitate a specified web server (default root page, 404 default error page, 'Server' HTTP response header)
        web_server_imitation:
            enable: true
            type: "apache" # Supported: apache, iis, nginx
            hook_404: false # inject BeEF hook in HTTP 404 responses
            hook_root: false # inject BeEF hook in the server home page
        # Experimental HTTPS support for the hook / admin / all other Thin managed web services
        https:
            enable: false
            # In production environments, be sure to use a valid certificate signed for the value
            # used in beef.http.dns_host (the domain name of the server where you run BeEF)
            key: "beef_key.pem"
            cert: "beef_cert.pem"

    database:
        # For information on using other databases please read the
        # README.databases file

        # supported DBs: sqlite, mysql, postgres
        # NOTE: you must change the Gemfile adding a gem require line like:
        #   gem "dm-postgres-adapter"
        # or
        #   gem "dm-mysql-adapter"
        # if you want to switch drivers from sqlite to postgres (or mysql).
        # Finally, run a 'bundle install' command and start BeEF.
        driver: "sqlite"

        # db_file is only used for sqlite
        db_file: "db/beef.db"

        # db connection information is only used for mysql/postgres
        db_host: "localhost"
        db_port: 3306
        db_name: "beef"
        db_user: "beef"
        db_passwd: "beef"
        db_encoding: "UTF-8"

    # Credentials to authenticate in BeEF.
    # Used by both the RESTful API and the Admin_UI extension
    credentials:
        user:   "beef"
        passwd: "beef"

    # Autorun Rule Engine
    autorun:
        # this is used when rule chain_mode type is nested-forward, needed as command results are checked via setInterval
        # to ensure that we can wait for async command results. The timeout is needed to prevent infinite loops or eventually
        # continue execution regardless of results.
        # If you're chaining multiple async modules, and you expect them to complete in more than 5 seconds, increase the timeout.
        result_poll_interval: 300
        result_poll_timeout: 5000

        # If the modules doesn't return status/results and timeout exceeded, continue anyway with the chain.
        # This is useful to call modules (nested-forward chain mode) that are not returning their status/results.
        continue_after_timeout: true

    # Enables DNS lookups on zombie IP addresses
    dns_hostname_lookup: true

    # IP Geolocation
    # NOTE: requires MaxMind database:
    #   curl -O http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
    #   gunzip GeoLiteCity.dat.gz && mkdir /opt/GeoIP && mv GeoLiteCity.dat /opt/GeoIP
    geoip:
        enable: true
        database: '/opt/GeoIP/GeoLiteCity.dat'

    # Integration with PhishingFrenzy
    # If enabled BeEF will try to get the UID parameter value from the hooked URI, as this is used by PhishingFrenzy
    # to uniquely identify the victims. In this way you can easily associate phishing emails with hooked browser.
    integration:
        phishing_frenzy:
            enable: false

    # You may override default extension configuration parameters here
    extension:
        requester:
            enable: true
        proxy:
            enable: true
            key: "beef_key.pem"
            cert: "beef_cert.pem"
        metasploit:
            enable: false
        social_engineering:
            enable: true
        evasion:
            enable: false
        console:
             shell:
                enable: false
        ipec:
            enable: true
        # this is still experimental..
        # Disable it in kali because it doesn't work with the current
        # version of ruby-rubydns (older version is required by beef-xss)
        dns:
            enable: false
        # this is still experimental..
        dns_rebinding:
            enable: false

#### Summary

I'm able to hook browsers, they appear in beef UI. But beef cannot gather any information about hooked browser, only IP.

#### Expected Behaviour

Beef should gather information about hooked browser, as stated in wiki: browser, OS, plugins, etc.

#### Actual Behaviour

 beef cannot gather any information about hooked browser, only IP.

#### Steps to Reproduce

Usual beef setup.

**Comment by BenSimp** [comment]
What is more, I open beef.db in sqlite manager and see all the details. But I'm UI does not use this info. 
This is example info from db.
{"VERSION":"HTTP/1.1","ACCEPT":"application/javascript, */*;q=0.8","REFERER":"http://testsite.local/index.php","ACCEPT_LANGUAGE":"de-DE","USER_AGENT":"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko","ACCEPT_ENCODING":"gzip, deflate","HOST":"192.168.1.1:5555","CONNECTION":"Keep-Alive"}

{"VERSION":"HTTP/1.1","HOST":"192.168.1.1:5555","CONNECTION":"keep-alive","USER_AGENT":"Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991","ACCEPT":"*/*","REFERER":"http://testsite.local/index.php","ACCEPT_ENCODING":"gzip,deflate","ACCEPT_LANGUAGE":"ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4"}

**Comment by BenSimp** [comment]
Also, simple ARE rules, like this, does not work. 
{
  "name": "Invisible Frame",
  "author": "BenSimpson",
  "browser": "ALL",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [{
    "name": "invisible_iframe",
    "condition": null,
    "options": {
       "target": "http://192.168.1.2:8080/check"
    }
  }],
  "execution_order": [0],
  "execution_delay": [0],
  "chain_mode": "sequential"
}
I think, this is because Beef can't determine correct os and browser versions.
Will be gratefull for any advice or help.

**Comment by BenSimp** [comment]
I'm still alone, but some progress, if someone will need this.
Simply reinstalling BeEF I was able to detect correct browser, I think browser.js and os.js (/core/main/client) were updated, where signatures are located. 
But with OS and other info situation is still bad. Also, ARE rules aren't fired, but parsed correctly. I can't get to work even stock are rule "get cookie". So, help will be still appreciated.

**Comment by bcoles** [comment]
Hi @BenSimp

I can't reproduce this error.

Do you have NodeJS installed?

**Comment by BenSimp** [comment]
Yes. 
root@kali# nodejs -v
v4.7.2
root@kali# uname -a
Linux  4.9.0-kali1-amd64 #1 SMP Debian 4.9.6-3kali2 (2017-01-30) x86_64 GNU/Linux
Beef is up-to-date.

**Comment by bcoles** [comment]
Hi @BenSimp

There was a syntax error in the Get Cookie module. This was my bad.

Given that the browser detection is working for you now that you've updated, if you update again to update the Get Cookie module, this issue should now be resolved.

**Comment by BenSimp** [comment]
Thanks. I'll check. Can you say, is my script "Invisible frame" is correct?
{
"name": "Invisible Frame",
"author": "BenSimpson",
"browser": "ALL",
"browser_version": "ALL",
"os": "ALL",
"os_version": "ALL",
"modules": [{
"name": "invisible_iframe",
"condition": null,
"options": {
"target": "http://192.168.1.2:8080/check"
}
}],
"execution_order": [0],
"execution_delay": [0],
"chain_mode": "sequential"
}
And what about OS, and other staff? I can research myself, but where to start?

**Comment by bcoles** [comment]
Hi @BenSimp

Yes, your ARE rule is correct.

To learn more about the ARE, check out the [wiki page](https://github.com/beefproject/beef/wiki/Autorun-Rule-Engine).

The [existing ARE rules](https://github.com/beefproject/beef/tree/master/arerules) may also help to learn by example.

**Comment by bcoles** [comment]
Hi @BenSimp - any luck with this? Can I close this issue?

**Comment by netcretin** [comment]
Hi there,

coming back to this older issue, which I am encountering just now in a similar fashion.

I have run a couple of tests over WAN with my own devices using ngrok + beef-over-wan, I can hook the browser of the target machines just fine, some commands work, but the basic things I am looking for atm i.e. information about the browser, system etc. are null (not displaying).

Has the issue developed in the meantime?

Cheers.
