### ISSUE TITLE
The Gemfile specifies an absolutely ancient version of therubyracer

### ISSUE THREAD

**Issue by ignisf** [beefproject/beef#1374]
Hello,

The versions of `therubyracer` that have been hardcoded in the Gemfile are from 2013. This for example causes installation of the project to fail on arm-based hardware (https://github.com/cowboyd/libv8/issues/234#issuecomment-286672230). Please consider either removing the version constraint of `therubyracer` or if you insist on keeping Windows compatibility, consider using a different JS runtime (see [node for example](https://github.com/rails/execjs#execjs)).

**Comment by bcoles** [comment]
Hey @antisnatchor can you take a look at this?

therubyracer version 0.11.3 is waaay behind the version i've been using (2.5.1).

Relevant lines from `Gemfile`:

```
# Windows support
if RUBY_PLATFORM.downcase.include?('mswin') || RUBY_PLATFORM.downcase.include?('mingw')
  # make sure you install this gem following https://github.com/eakmotion/therubyracer_for_windows
  gem 'therubyracer', '~> 0.11.0beta1'
elsif !RUBY_PLATFORM.downcase.include?('darwin')
  gem 'therubyracer', '0.11.3'
end
```

I think this entire code block is redundant and can be removed. I've removed it in 089bacd0a2f268b1689421fd5eccfee479656f54.

I noticed that in your BeEF_NG branch you've also removed this section of code. Is it safe to do this in the master branch?

If therubyracer is required, can we look at replacing therubyracer with Node now that we require Node for the autorun rules engine anyway?

**Comment by tykkz** [comment]
Hello, 

I have followed the [Installation](https://github.com/beefproject/beef/wiki/Installation) page from the Wiki and hit by this problem.. Using Debian "jessie" release.

Thankfully, I have installed Node.js and everything worked. Maybe you could write this detail in the Installation page.

Cheers.

**Comment by bcoles** [comment]
Thanks @tykkz

NodeJS has been added as a dependency to the  [Installation](https://github.com/beefproject/beef/wiki/Installation) page.

**Comment by bcoles** [comment]
It appears that we need `therubyracer` on some Linux distros for running the test cases.

Closing this issue until someone yells at me.

**Comment by bcoles** [comment]
Hi @ ignisf 

Unfortunately therubyracer 0.12.3 causes issues. I've force downgraded therubyracer to 0.12.2 which was released in 2015. therubyracer is required only for Linux systems.

`gem 'therubyracer', '~> 0.12.2', '<= 0.12.2'`

Unfortunately we have insufficient developer bandwidth to look at swapping out therubyracer for nodejs.

Does therubyracer 0.12.2 work on ARM for you?
