### ISSUE TITLE
An error occurred while installing rainbow (2.2.1), and Bundler cannot continue. Make sure that `gem install rainbow -v '2.2.1'` succeeds before bundling.

### ISSUE THREAD

**Issue by blackh0st** [beefproject/beef#1387]
root@blackghost:/usr/share/beef-xss# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this
machine.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 2.0.5
Using ansi 1.5.0
Using chunky_png 1.3.8
Using daemons 1.2.4
Using json 1.8.6
Using json_pure 1.8.6
Using multi_json 1.12.1
Using eventmachine 1.0.9.1
Using http_parser.rb 0.6.0
Using erubis 2.7.0
Using espeak-ruby 1.0.4
Using execjs 2.7.0
Using fastercsv 1.5.5
Using filesize 0.1.1
Using geoip 1.6.3
Using rkelly-remix 0.0.7
Using metasm 1.0.3
Using mime-types-data 3.2016.0521
Using mini_portile2 2.1.0
Using mojo_magick 0.5.6
Using msgpack 1.1.0
Using rb-readline-r7 0.5.2.0
Using robots 0.10.1
Using parseconfig 1.0.8
Using rack 1.6.5
Installing rainbow 2.2.1 with native extensions
Using rubyzip 1.2.1
Using tilt 2.0.7
Using tins 1.13.2
Using bundler 1.14.6
Using addressable 2.5.1
Using rqrcode 0.10.1
Using em-websocket 0.5.1
Using uglifier 3.2.0
Using jsobfu 0.4.2
Using mime-types 3.1
Using nokogiri 1.7.1
Using rack-protection 1.5.3
Using thin 1.7.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.1/ext
/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.1/ext
/usr/bin/ruby2.3 -rubygems /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1
RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1
/usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/rainbow-2.2.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1/gem_make.out

An error occurred while installing rainbow (2.2.1), and Bundler cannot continue.
Make sure that `gem install rainbow -v '2.2.1'` succeeds before bundling.

**Comment by bretth18** [comment]
How did you solve this? I can't seem to figure it out

**Comment by bcoles** [comment]
Hi @bretth18 

Does this resolve your issue?

```bash
gem update --system
gem install rainbow -v '2.2.1'
```

**Comment by bretth18** [comment]
No, I had tried that several times. Turned out the issue was the lack of a node/javascript environment installed on my VPS.

Appreciate the reply

**Comment by bcoles** [comment]
Try `gem install rake` then `bundle install`

`rake` is a dependency of `rainbow` because reasons.
