### ISSUE TITLE
ipec shell isn't working on master

### ISSUE THREAD

**Issue by lucasduffey** [beefproject/beef#1394]
beef's ipsec shell isn't working on the latest git master branch but it is working in the latest tagged release (beef-0.4.7.0).

When you type "help" for instance it just goes to the next line and doesn't clear the "help"

**Comment by bcoles** [comment]
Thanks @lucasduffey 

The IPEC shell was broken a few days ago when I updated jQuery to 1.12.4.

The wterm JavaScript library has not been updated in 8 years. In the long term we'll need to look at replacing it.

**Comment by bcoles** [comment]
I've submitted [an issue](https://github.com/gvenkat/wterm/issues/2) but I don't expect it will be resolved as the project looks dead.

**Comment by bcoles** [comment]
[JQuery Terminal Emulator Plugin](https://terminal.jcubic.pl/) is a possible alternative.

**Comment by bcoles** [comment]
IPEC extension has been removed in #2792.
