### ISSUE TITLE
Warning : System language $LANG does not appear to be UTF-8 compatible. (WINDOWS 7)

### ISSUE THREAD

**Issue by samuelhutauruk2** [beefproject/beef#1399]
Beef i have installed on my Windows 7 computer and i found : API Fire Error, what should i do ? Please help me !
![abc](https://cloud.githubusercontent.com/assets/28714809/26075528/d5aae1a0-39df-11e7-8c1c-46ba62e7e69d.jpg)
![abc2](https://cloud.githubusercontent.com/assets/28714809/26075540/ddb83f32-39df-11e7-8606-90cae8157891.jpg)
![abc3](https://cloud.githubusercontent.com/assets/28714809/26075548/e44912f4-39df-11e7-875e-c91ba77a26e8.jpg)

**Comment by bcoles** [comment]
We've long since stopped supporting Windows.

You could try using cygwin and setting the LANG environment variable. Note that Cygwin on Windows is also unsupported.

```bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by bcoles** [comment]
Also, make sure you have nodejs installed
