### ISSUE TITLE
Beef on 16.04 RBENV

### ISSUE THREAD

**Issue by alphaaurigae** [beefproject/beef#1402]
10:49 $ beef
/home/$USER/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- core/loader (LoadError)
	from /home/$USER/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bin/beef:25:in `<main>'

#### Environment

What version/revision of BeEF are you using?
GIT Master 04.06.2017
On what version of Ruby?
using RBENV, tried 2.2.7, 2.3.0, 2.3.3, 2.4.0, 2.4.1
On what browser?
Didnt get there
On what operating system?
xubuntu 16.04 - 4.8.0-53-generic

#### Configuration

Are you using a non-default configuration?
apart from RBENV, no
Have you enabled or disabled any BeEF extensions?
Didnt get there.

#### Summary

Same err with every rbenv ruby i tried.
10:49 $ beef
/home/$USER/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- core/loader (LoadError)
	from /home/$USER/.rbenv/versions/2.2.7/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/bin/beef:25:in `<main>'

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

On blanc xubuntu 16.04
https://hastebin.com/eledoqulef.bash

####
https://hastebin.com/emadabefon.bash

#### Additional Information
- none
Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
Hi @alphaaurigae

Unfortunately it looks like your hastebin links have expired.

BeEF should work with both rbenv and rvm.

It looks like you're running `beef` from `$PATH` and it's trying to load `core/loader` from the working directory. This is bad.

Does BeEF run if you `cd` to the BeEF directory and execute `./beef` ?

**Comment by alphaaurigae** [comment]
hi, thx for reply, issue is solved by now - i forgot to update here and my repo ..

https://pastebin.com/JEmQfrL7

https://github.com/alphaaurigae/ITSEC-Install-Scripts/commit/ffac4772cf98284572f4c848c9e57cc3c2565976

**Comment by bcoles** [comment]
Thanks @alphaaurigae

**Comment by alphaaurigae** [comment]
wrote a comment, in case you missed it :)
