### ISSUE TITLE
what version of beef,armitage and metasploit are required to run beef strike.cna?

### ISSUE THREAD

**Issue by BlaacckK** [beefproject/beef#1404]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?

On what browser?

On what operating system?

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
Hi @BlaacckK this is something you would need to as the author of `beef_strike.cna`

`beef_strike.cna` was written 5+ years ago. From a quick look at the code, it uses the BeEF plugin for metasploit which is no longer maintained or supported.

To answer your question, you'll probably want to use a version of BeEF and Metasploit from early 2013, or earlier.

**Comment by BlaacckK** [comment]
Thanks
