### ISSUE TITLE
NameError - uninitialized constant BeEF::Core::Command::Text_to_voice

### ISSUE THREAD

**Issue by instruder** [beefproject/beef#1413]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

2017-07-14 11:44:55 - NameError - uninitialized constant BeEF::Core::Command::Text_to_voice:
	/root/beef/core/main/handlers/modules/command.rb:33:in `const_get'
	/root/beef/core/main/handlers/modules/command.rb:33:in `add_command_instructions'
	/root/beef/core/main/handlers/hookedbrowsers.rb:80:in `block (2 levels) in <class:HookedBrowsers>'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/dm-core-1.2.1/lib/dm-core/collection.rb:508:in `block in each'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `block in each'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/dm-core-1.2.1/lib/dm-core/collection.rb:505:in `each'
	/root/beef/core/main/handlers/hookedbrowsers.rb:80:in `block in <class:HookedBrowsers>'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/thin-1.7.1/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/thin-1.7.1/lib/thin/connection.rb:84:in `catch'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/thin-1.7.1/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/thin-1.7.1/lib/thin/connection.rb:53:in `process'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/thin-1.7.1/lib/thin/connection.rb:39:in `receive_data'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/thin-1.7.1/lib/thin/backends/base.rb:73:in `start'
	/usr/local/rvm/gems/ruby-2.3.0@beef/gems/thin-1.7.1/lib/thin/server.rb:162:in `start'
	/root/beef/core/main/server.rb:125:in `start'
	./beef:178:in `<main>'

#### Environment

What version/revision of BeEF are you using?
0.4.7

On what version of Ruby?

On what browser?

On what operating system?

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

I just execute the command text to voice module,after that,the beef console is error ;

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
Hi @instruder 

I can't reproduce this error. Are you using the latest version of BeEF from Github? Have you run `bundle install` to install the espeak-ruby gem?

**Comment by instruder** [comment]
Yes , i download from the github a weeks ago, and install it with the beef wiki.

**Comment by bcoles** [comment]
The error you're receiving indicates that the Text to Voice module could not be hard loaded.

Did you receive that error when you selected the module in the web interface, or when you attempted to execute the module?

If you received the error when you clicked the module, then chances are that the espeak-ruby gem could not be initialised for some reason.

**Comment by instruder** [comment]
[11:50:29][!] [Text to Voice] Lame is not in $PATH (apt-get install lame)

It give me this tips...

**Comment by instruder** [comment]
After I do it with this tips,its ok now,thankyou

**Comment by bcoles** [comment]
Cool :)

**Comment by sphereict** [comment]
Hey guys 

Please can someone help not sure what is causing the error..
Yes just upgraded my Kali distribution last night so I am on the latest version.

[12:19:43][*] Using dropper: '/usr/share/beef-xss/modules/social_engineering/firefox_extension_dropper/dropper/AdobeF236789.exe'
2018-07-20 12:19:43 - Errno::ENOENT - No such file or directory @ rb_sysopen - /usr/share/beef-xss/modules/social_engineering/firefox_extension_dropper/extension/build/install.rdf:
	/usr/share/beef-xss/modules/social_engineering/firefox_extension_dropper/module.rb:57:in `initialize'
	/usr/share/beef-xss/modules/social_engineering/firefox_extension_dropper/module.rb:57:in `open'
	/usr/share/beef-xss/modules/social_engineering/firefox_extension_dropper/module.rb:57:in `pre_send'
	/usr/share/beef-xss/core/main/handlers/modules/command.rb:39:in `add_command_instructions'
	/usr/share/beef-xss/core/main/handlers/hookedbrowsers.rb:80:in `block (2 levels) in <class:HookedBrowsers>'
	/usr/lib/ruby/vendor_ruby/dm-core/collection.rb:508:in `block in each'
	/usr/lib/ruby/vendor_ruby/dm-core/support/lazy_array.rb:411:in `block in each'
	/usr/lib/ruby/vendor_ruby/dm-core/support/lazy_array.rb:411:in `each'
	/usr/lib/ruby/vendor_ruby/dm-core/support/lazy_array.rb:411:in `each'
	/usr/lib/ruby/vendor_ruby/dm-core/collection.rb:505:in `each'
	/usr/share/beef-xss/core/main/handlers/hookedbrowsers.rb:80:in `block in <class:HookedBrowsers>'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1611:in `call'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1611:in `block in compile!'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:994:in `route_eval'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1015:in `block in process_route'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1013:in `catch'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1013:in `process_route'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:973:in `block in route!'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:972:in `each'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:972:in `route!'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `block in invoke'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `catch'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `invoke'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1082:in `dispatch!'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:907:in `block in call!'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `block in invoke'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `catch'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:1067:in `invoke'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:907:in `call!'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:895:in `call'
	/usr/lib/ruby/vendor_ruby/rack/nulllogger.rb:9:in `call'
	/usr/lib/ruby/vendor_ruby/rack/head.rb:13:in `call'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:182:in `call'
	/usr/lib/ruby/vendor_ruby/sinatra/base.rb:2013:in `call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:66:in `block in call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:86:in `block in pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `catch'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
	/usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run_machine'
	/usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run'
	/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
	/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
	/usr/share/beef-xss/core/main/server.rb:127:in `start'
	./beef:154:in `<main>'
Any help will be appreciated thanks
