### ISSUE TITLE
Problem installing beef

### ISSUE THREAD

**Issue by sasatefa2009** [beefproject/beef#1416]
On what version of Ruby?
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

On what operating system?
kali 2016.2

### Summary
I've done the following 

git clone git://github.com/beefproject/beef.git
cd beef
bundle install

but i got an error as follow

#### Actual Behaviour

**/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/gems/bundler-1.13.6/exe/bundle (LoadError)
	from /usr/local/bin/bundle:23:in `<main>'**

**Comment by sasatefa2009** [comment]
i found the problem,
it was an older version of bundler i was using.

"  **## gem install bundler**  " fixed the problem

to be closed by admin if no comments to add.

**Comment by sasatefa2009** [comment]
i faced another problem while installing

Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 12.0.0
Using public_suffix 2.0.5
Using ansi 1.5.0
Using bundler 1.15.3
Using chunky_png 1.3.8
Using daemons 1.2.4
Using fastercsv 1.5.5
Using json 1.8.6
Using json_pure 1.8.6
Using multi_json 1.12.1
Using eventmachine 1.0.9.1
Using http_parser.rb 0.6.0
Using erubis 2.7.0
Using espeak-ruby 1.0.4
Using execjs 2.7.0
Using filesize 0.1.1
Using geoip 1.6.3
Using rkelly-remix 0.0.7
Using libv8 3.16.14.19 (x86_64-linux)
Using metasm 1.0.3
Using mime-types-data 3.2016.0521
Using mini_portile2 2.1.0
Using mojo_magick 0.5.6
Using msgpack 1.1.0
Using rb-readline 0.5.4
Using robots 0.10.1
Using parseconfig 1.0.8
Using rack 1.6.8
Using ref 2.0.0
Using rubyzip 1.2.1
Using tilt 2.0.7
Using tins 1.15.0
Fetching rainbow 2.2.2
Installing rainbow 2.2.2 with native extensions
Using addressable 2.5.1
Using rqrcode 0.10.1
Using em-websocket 0.5.1
Using uglifier 3.2.0
Using jsobfu 0.4.2
Using mime-types 3.1
Fetching nokogiri 1.7.2
Installing nokogiri 1.7.2 with native extensions
Using rack-protection 1.5.3
Using thin 1.7.1
Using therubyracer 0.12.2
Using term-ansicolor 1.6.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 -rubygems
/usr/share/rubygems-integration/all/gems/rake-12.0.0/exe/rake
RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2
RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2
/usr/bin/ruby2.3: No such file or directory --
/usr/share/rubygems-integration/all/gems/rake-12.0.0/exe/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/rainbow-2.2.2 for
inspection.
Results logged to
/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2/gem_make.out

An error occurred while installing rainbow (2.2.2), and Bundler cannot
continue.
Make sure that `gem install rainbow -v '2.2.2'` succeeds before bundling.

In Gemfile:
  rubydns was resolved to 0.7.3, which depends on
    rexec was resolved to 1.6.3, which depends on
      rainbow

**Comment by sasatefa2009** [comment]
and if i tried to run beef using /beef
i get this error

Your bundle is locked to nokogiri (1.7.2), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of nokogiri (1.7.2) has removed it. You'll need to update your bundle to a different version of nokogiri (1.7.2) that hasn't been removed in order to install.

**Comment by bcoles** [comment]
Try `gem install rake` then `bundle install`

`rake` is a dependency of `rainbow` because reasons.

**Comment by sasatefa2009** [comment]
**Well, that really works. but another error comes**

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.7.2/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20170725-5111-trm30k.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.7.2 for
inspection.
Results logged to
/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.7.2/gem_make.out

An error occurred while installing nokogiri (1.7.2), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.7.2'` succeeds before bundling.

In Gemfile:
  msfrpc-client was resolved to 1.1.0, which depends on
    rex was resolved to 2.0.11, which depends on
      nokogiri

**Comment by sasatefa2009** [comment]
I found the problem, it was that "zlib is missing" as it says in the eighth line.
using this line helped fix the problem

**sudo apt-get install libpng-dev
sudo apt-get install --reinstall zlibc zlib1g zlib1g-dev**

**Comment by gkaan07** [comment]
whats the passwort on bundle install ?

**Comment by bcoles** [comment]
> 
> 
> whats the passwort on bundle install ?

`bundle install` is probably asking for your sudo password.

**Comment by RDewetTDS** [comment]
An error occurred while installing tilt (2.0.10), and Bundler cannot
continue.

In Gemfile:
  sinatra was resolved to 2.2.0, which depends on
    tilt




I still get the error what should I do?
