### ISSUE TITLE
Google search module doesn't work

### ISSUE THREAD

**Issue by darker0n** [beefproject/beef#1417]
Result of module execution:
`query=beef&results={"responseData":null,"responseDetails":"The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)","responseStatus":403}`

**Comment by bcoles** [comment]
Yup, unfortunately Google have deprecated the API. This module was removed from BeEF ages ago. Your version of BeEF is out of date.
