### ISSUE TITLE
beef ssl Port conflict

### ISSUE THREAD

**Issue by Gzsa** [beefproject/beef#1419]
at
server {
        listen       442;
        root /opt/beef;
        server_name xx.xx.com;
        ssl on;

    http:
        debug: flase #Thin::Logging.debug, very verbose. Prints also full exception stack trace.
        host: "0.0.0.0"
        port: "442"
![gzsa2](https://user-images.githubusercontent.com/30402637/28512917-74b6b2ec-7086-11e7-8e1d-667800d27ef0.png)

if
    http:
        debug: flase #Thin::Logging.debug, very verbose. Prints also full exception stack trace.
        host: "0.0.0.0"
        port: "443"
interview  https://xxx.xxx.com:443/ui/panl
There will be a certificate error

at
server {
        listen       443;
        root /opt/beef;
        server_name beef.gzsa.me;
        ssl on;

    http:
        debug: flase #Thin::Logging.debug, very verbose. Prints also full exception stack trace.
        host: "0.0.0.0"
        port: "442"

interview  https://xxx.xxx.com:442/ui/panl
There will be a certificate error

How to solve the problem of beef and Nginx ssl port duplication.

**Comment by Gzsa** [comment]
My English is not very good.............................................

**Comment by bcoles** [comment]
Are you using nginx as a reverse proxy?

Try stripping SSL between nginx and BeEF?

**Comment by bcoles** [comment]
I'm not sure what you're trying to achieve. Maybe this will help.

* https://github.com/beefproject/beef/wiki/FAQ#can-i-use-a-domain-name-instead-of-ip-address-for-the-beef-hook

**Comment by Gzsa** [comment]
@bcoles  I would like to normally access the hook.js under https    
https://www.xxx.com/hook.js
my ssl port is 443    beef port is 444  
https://www.xxx.com:444/hook.js   There will be a certificate error

**Comment by Gzsa** [comment]
@bcoles   https://beef.gzsa.me:444/hook.js There will be a certificate error   
This is my configuration file :https://beef.gzsa.me/config.yaml
How should i modify it? 。。

**Comment by bcoles** [comment]
BeEF listens on only one port.

Set BeEF to listen on port `443` in `config.yaml`

```yaml
beef:
    # ...
    http:
      # ...
      port: "443"
```

And enable HTTPS with `enable: true` in `config.yaml`

```yaml
beef:
    # ...
    http:
      # ...
      https:
        # ...
        enable: true
```

**Comment by Gzsa** [comment]
@bcoles 
[19:15:15][!] Another process is already listening on port 443, or you're trying to bind BeEF to an invalid IP.
[19:15:15][!] Is BeEF already running? Exiting...

 https:
            enable: true
            # In production environments, be sure to use a valid certificate signed for the value
            # used in beef.http.public (the domain name of the server where you run BeEF)
            key: "beef_key.pem" ←
            cert: "beef_cert.pem" ←
This certificate 。 use beef_key.pem and beef_cert.pem  or my own certificate?

and also here ↓
  # You may override default extension configuration parameters here
    extension:
        requester:
            enable: true
        proxy:
            enable: true
            key: "beef_key.pem"  ←
            cert: "beef_cert.pem" ←
        metasploit:
            enable: true

**Comment by Gzsa** [comment]
![Uploading 11.jpg…]()

**Comment by bcoles** [comment]
Another process is already listening on port 443.

Try `lsof -i :443` or `netstat -anp | grep 443`

**Comment by Gzsa** [comment]
@bcoles 
[root@izj6c4fvpqsvwfqd8vcdrzz beef]# netstat -anp | grep 443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      2513/nginx: master      
tcp        0      0 172.31.109.253:443      11x.9x.5x.20x:47528     ESTABLISHED 2517/nginx: worker  
If it turns off it my nginx will not run....

**Comment by bcoles** [comment]
Each port can have only one service listening.

You can move nginx to a different port, or move BeEF to a different port.

I assume what you're trying to do is set up BeEF behind nginx.

One option would be to set nginx to list on the public interface, and set BeEF to listen on the local interface.

This is not a BeEF issue. Please refer to nginx documentation.

**Comment by Gzsa** [comment]
好的  我觉得我懂了  谢谢！

**Comment by bcoles** [comment]
No worries. 祝你好运

https://www.techandme.se/set-up-nginx-reverse-proxy/

**Comment by Gzsa** [comment]
O(∩_∩)O~ Thanks you again ! Has been successfully resolved！
`    # HTTP server
    http:
        debug: flase #Thin::Logging.debug, very verbose. Prints also full exception stack trace.
        host: "0.0.0.0"
        port: "3000"

        # Decrease this setting to 1,000 (ms) if you want more responsiveness
        #  when sending modules and retrieving results.
        # NOTE: A poll timeout of less than 5,000 (ms) might impact performance
        #  when hooking lots of browsers (50+).
        # Enabling WebSockets is generally better (beef.websocket.enable)
        xhr_poll_timeout: 1000

        # Host Name / Domain Name
        # If you want BeEF to be accessible via hostname or domain name (ie, DynDNS),
        #   set the public hostname below:
        #public: "47.52.xx.xx"      # public hostname/IP address

        # Reverse Proxy / NAT
        # If you want BeEF to be accessible behind a reverse proxy or NAT,
        #   set both the publicly accessible hostname/IP address and port below:
        #public: "47.52.xx.xx"      # public hostname/IP address
        #public_port: "443" # public port (experimental)` ←//The problem is here

just now  https://beef.xxxx.com:3000/hook.js    The certificate is no longer in error

**Comment by Gzsa** [comment]
This question has bothered me for more than a week   O(∩_∩)O~~

**Comment by bcoles** [comment]
:)
