### ISSUE TITLE
[RFE] DNS rebinding is requires iptables but nftables should be supported as well

### ISSUE THREAD

**Issue by fabianfrz** [beefproject/beef#1430]
nftables is the successor of iptables and the script should use it if installed or it should go to the configuration file. Note that in nftables there are not predefined chains like in iptables.

https://github.com/beefproject/beef/blob/32d2226991ac30f0e1a75d4ce5e26716c2e5d6c5/extensions/dns_rebinding/dns_rebinding.rb#L48

**Comment by bcoles** [comment]
Thanks @fabianfrz 

Unfortunately this issue will not be resolved due to lack of developer bandwidth. We welcome PRs.
