### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by usama7628674** [beefproject/beef#1432]
Please anyone bump the version of beef because a lot of commits had done from 30th december 2015 and we are not getting those  commits except using git clone method

**Comment by bcoles** [comment]
Hi @usama7628674 

Unfortunately there's a number of issues to be resolved before the next release:

https://github.com/beefproject/beef/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.4.7.1-alpha

We're also short on developer bandwidth, but welcome pull requests :)

**Comment by bcoles** [comment]
The final remaining issue from the 0.4.7.1 milestone has been resolved.

@wadealcorn BeEF master branch should be ready for pre-release testing and subsequent release.

**Comment by bcoles** [comment]
Tracked in #1530

Closing this issue.
