### ISSUE TITLE
BeEF creds not working.

### ISSUE THREAD

**Issue by PwNS0uc3** [beefproject/beef#1439]
I am having problems with BeEF on Kali Linux on vbox.
I am very new to BeEF and have got it to work before but suddenly the credentials do not work. I have tried to change the password through config.yaml but it still does not work. I really need help and would much appreciate any support.

Thank you

**Comment by bcoles** [comment]
Hi @PwNS0uc3 

If you make changes to the `config.yaml` file you'll need to restart BeEF.

Also, if you restart BeEF, you may need to reload/refresh the admin UI.

If that doesn't work... Are you receiving any errors in terminal or in the browser console?
