### ISSUE TITLE
a ton of problems after using ./beef

### ISSUE THREAD

**Issue by Blank0P** [beefproject/beef#1441]
/usr/lib/ruby/2.3.0/psych.rb:474:in `initialize': No such file or directory @ rb_sysopen - /usr/lib/ruby/data/geoip/country_code.yml (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /usr/lib/ruby/vendor_ruby/geoip.rb:68:in `<class:GeoIP>'
	from /usr/lib/ruby/vendor_ruby/geoip.rb:58:in `<top (required)>'
	from /usr/share/beef-xss/core/loader.rb:21:in `require'
	from /usr/share/beef-xss/core/loader.rb:21:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./beef:25:in `<main>'

how do i fix this

**Comment by bcoles** [comment]
I assume you're using Kali.

`ln -s /var/lib/gems/2.3.0/gems/geoip-1.6.3/data /usr/lib/ruby/data`

**Comment by Blank0P** [comment]
thanks
