### ISSUE TITLE
 country_code.yml

### ISSUE THREAD

**Issue by Dmitry1788** [beefproject/beef#1456]
Good day! Tell me how to fix this error?Thank you for your consideration of my question

> /usr/lib/ruby/2.3.0/psych.rb:379:in `parse': (/usr/lib/ruby/data/geoip/country_code3.yml): mapping values are not allowed in this context at line 327 column 24 (Psych::SyntaxError)
	from /usr/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /usr/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /usr/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /usr/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /usr/lib/ruby/vendor_ruby/geoip.rb:72:in `<class:GeoIP>'
	from /usr/lib/ruby/vendor_ruby/geoip.rb:58:in `<top (required)>'
	from /media/root/01D2C73C91198660/softKali/beef/core/loader.rb:21:in `require'
	from /media/root/01D2C73C91198660/softKali/beef/core/loader.rb:21:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./beef:25:in `<main>

![screenshot at 2017-10-14 18-25-31](https://user-images.githubusercontent.com/32652244/31582908-0327a312-b199-11e7-9693-934f08b2508f.png)

`

**Comment by bcoles** [comment]
Hi @Dmitry1788 

This looks like an issue with the GeoIP gem.

Can you paste the contents of the `/usr/lib/ruby/data/geoip/country_code3.yml` ?

**Comment by Dmitry1788** [comment]
Hi @bcoles 
Yes I can replace the contents of the documents. I tried to manually replace the document, unfortunately the error remains

**Comment by bcoles** [comment]
This is likely an error with the GeoIP gem and/or Parrot, not BeEF.

As a workaround, you can remove the GeoIP dependency:

```diff
diff --git a/Gemfile b/Gemfile
index 459fa19..1403654 100644
--- a/Gemfile
+++ b/Gemfile
@@ -43,9 +43,9 @@ group :mysql do
 end
 
 # Geolocation support
-group :geoip do
-  gem 'geoip'
-end
+#group :geoip do
+#  gem 'geoip'
+#end
 
 gem 'parseconfig'
 gem 'erubis'
```

```diff
diff --git a/core/loader.rb b/core/loader.rb
index 0683c48..47ead8c 100644
--- a/core/loader.rb
+++ b/core/loader.rb
@@ -18,7 +18,7 @@ require 'rubydns'
 require 'mime/types'
 require 'optparse'
 require 'resolv'
-require 'geoip'
+#require 'geoip'
 
 # @note Include the filters
 require 'core/filters'
```

```sh
bundle install
```

**Comment by Dmitry1788** [comment]
@bcoles Hi!
I replaced the text in the file with the one you provided, unfortunately the error did not disappear

**Comment by bcoles** [comment]
@Dmitry1788  Looks like your issue is due to geoip.

Does the comment at the end of [this thread](https://github.com/tsu-iscd/beef-drive/issues/1) help?

Something like this:

```bash
ln -s /var/lib/gems/2.3.0/gems/geoip-1.6.3/data /usr/lib/ruby/data
```
