### ISSUE TITLE
Tunneling proxy doesn't render

### ISSUE THREAD

**Issue by billgateways** [beefproject/beef#1460]
#### Environment

What version/revision of BeEF are you using?
0.4.7.0-alpha

On what version of Ruby?
2.3.3p222
On what browser?
Firefox ESR 45.8.0
Chrome 61.0.3163.100 (hooked browser)
On what operating system?
Kali linux
Windows 10 (hooked)

#### Configuration

Are you using a non-default configuration?
i changed the extensions/proxy/config.yaml to point to a different port

Have you enabled or disabled any BeEF extensions?
no

#### Summary

When i use the proxy i can see the response to a forged request, but browsing on kali using the proxy gives me a blank page
and i get this error on the terminal:
[!] This http request has been saved before

#### Expected Behaviour

I should be able to browse as the hooked browser

#### Actual Behaviour

I see a blank page, loading.
I think it worked fine on the demo page (secret_page.html)

**Comment by billgateways** [comment]
When using the proxy on the custom port, i see the request made and the responses in the beef control panel. Everything fine, except it doesn't render the webpage (blank page/ doesn't change page)

**Comment by billgateways** [comment]
On a different webapp i get this error, might be related?
![proxyencodingerror](https://user-images.githubusercontent.com/32869533/31675739-8dfa01c4-b333-11e7-937a-99c5ab606427.png)

**Comment by bcoles** [comment]
The encoding error is likely related.

Can you try using the proxy with cURL rather than a browser and see what output you get, if any ?

`curl -isk --http://127.0.0.1:6789 <YOUR URL>`
