### ISSUE TITLE
Proxy to internal

### ISSUE THREAD

**Issue by yashmelev** [beefproject/beef#1462]
There is a web site, that has allow-access-from domains "*" in crossdomain.xml.

If some user loggs into that web site by his credentials and opens my hook.js in another tab, can I proxy and see any information on that site?

**Comment by bcoles** [comment]
Unfortunately, the BeEF proxy / requester does not support fetching resources cross-origin with Flash.

With some reworking, you could modify the [Cross-Origin Scanner (Flash)](https://github.com/beefproject/beef/blob/master/modules/network/cross_origin_scanner_flash/) module to fetch arbitrary cross-origin resources for you.

This module scans an IP range for web servers looking for permissive Flash cross-origin policies in Chrome and Firefox browsers.
