### ISSUE TITLE
beef symbolic link 

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [beefproject/beef#1466]
Hello, 
i cloned beef project and i did `bundle install` , tested `./beef`  and it **worked fine** 
so i would liked to add a symbolic link for beef so i used the command `ln -s /folder/beef/beef /usr/local/bin/beef` to be able to launch it from everywhere 

but when i tested the **symbolic link** it **doesn't work** , i got this error: 
```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- core/loader (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bin/beef:25:in `<main>'
```

optional info: 
/usr/local/bin/beef:25  so line 25 of the script is:  
`require 'core/loader'`
```

/beef/core$ ls
api  api.rb  ...  loader.rb  main  module.rb  modules.rb  ruby 
```
Os used: Elementary Os based on Ubuntu 16.04 xenial 
Ruby version:  ruby 2.3.1p112 (2016-04-26)

**Any idea how to resolve this?**

**Comment by bcoles** [comment]
The good news is that this has been fixed in 946f593b5e5553791b2756c159f7870b26949d84

The bad news is that you still won't be able to run BeEF using a symlink due to the use of `Bundler.require(:default)`.

**Comment by gilbertons** [comment]
Symbolic link doesn't work, I solved my problem creating a bash script to enter in the path of Beef and starting him. Something like this:

#!/bin/bash
cd /opt/beef
exec ruby beef

Then I changed the file to an executable with chmod a+x "NameOfScript" and moved it to path /usr/bin/

This was works fine!

**Comment by 4nnph** [comment]
i install beef as normal then i edited beef file:
$root_dir = File.join(File.expand_path(__dir__), '.')

and it works fine.

**Comment by 4nnph** [comment]
__dir__*

**Comment by jcrew99** [comment]
I dont believe this should still be open? @mIcHyAmRaNe is there anything else to do further? Re-open this issue if so please
