### ISSUE TITLE
How do I delete all my zombies?

### ISSUE THREAD

**Issue by trollmad3** [beefproject/beef#1484]
![image](https://user-images.githubusercontent.com/7843719/34645428-d0f23900-f312-11e7-9e39-eab4017a8340.png)
Is there a way to delete all zombies without going one by one? This list is very large and the only way (that I know) is to right click and click delete. Is there any other way?

**Comment by bcoles** [comment]
The easiest way is to reset the database with the `-x` flag: `./beef -x` Note that this will delete everything from the database; in particular all zombies and all command responses.

Alternatively, zombies can be removed programmatically via the API.

**Comment by trollmad3** [comment]
@bcoles 

Thank you for telling me. This worked.


**Closed**

**Comment by bcoles** [comment]
I've added a REST API example script to remove all offline browsers.

```
# cd tools/rest_api_examples
# ./remove-offline-browsers --user beef --pass secret
[*] Authenticating to: http://127.0.0.1:3000
[+] Retrieved RESTful API token: b6000c4054516a653a1cdf31881eeca5b6b4825b
[+] Retrieved BeEF version: 0.4.7.0-alpha
[+] Retrieved offline browser list [1 offline]
[*] Removing hooked browser [id: 5]
[+] Removed browser [session: rvBlzx5CdGmWWVVZw1lYbyXHMec2hvyq4VMONw4b5OhJX2hkP41Ses5p6ExiAk2u0cKHrVtdaB5foCRs]
```

Use  `./remove-offline-browsers --help` for help.

**Comment by azamet90** [comment]
on me it is preinstalled and this beef -x command is not working im running it so: sudo beef-xss -x

**Comment by GingerCam** [comment]
Same
