### ISSUE TITLE
[Feature Request] Persistent Install 

### ISSUE THREAD

**Issue by zero77** [beefproject/beef#1486]
Can you please add support for persistent install, as an example by opening a hidden or very very small pop under window and testing different pop under alongside the current method, in case it gets blocked by the browser.
 
So there will still be a connection to the web browser even if the tab or main browser has closed.
![hidden_mining](https://user-images.githubusercontent.com/16563034/35188387-57aad0a0-fe2c-11e7-866d-77567d62e0ae.gif)
https://blog.malwarebytes.com/cybercrime/2017/11/persistent-drive-by-cryptomining-coming-to-a-browser-near-you/

Although, there may be a better way of doing this, as it will not stay connection if the dvice is restarted.
Thanks

**Comment by bcoles** [comment]
There are numerous [persistence modules](https://github.com/beefproject/beef/tree/master/modules/persistence), such as the [Popunder Window](https://github.com/beefproject/beef/tree/master/modules/persistence/popunder_window) module which does as you suggest.

These will not survive closing and reopening the browser. Nor will they survive restarting the device.

How do you propose to maintain a browser session when the browser is closed or device is restarted?

The best way to maintain permanent persistence would be to compromise and backdoor the underlying operating system. There are a few [social engineering modules](https://github.com/beefproject/beef/tree/master/modules/social_engineering) to gain code execution.

**Comment by zero77** [comment]
I was thinking of something like this https://thehackernews.com/2017/11/cryptocurrency-mining-javascript.html

But also with different pop up methods used in case the web browser or addon blocks it.

**Comment by bcoles** [comment]
If you have a technique for byassing popup blockers - we accept PRs.

The [Create Pop Under (IE) module](https://github.com/beefproject/beef/tree/master/modules/persistence/popunder_window_ie) will bypass the popup blocker in Internet Explorer.

**Comment by zero77** [comment]
I don’t currently, I will have to stick with that module for now.

**Comment by DeezyE** [comment]
Closed Stale
