### ISSUE TITLE
impossible to logged in beef

### ISSUE THREAD

**Issue by lacroutelacroute** [beefproject/beef#1499]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

I use git version of beef on kali linux rolling up to date
use this command for start
sudo ./beef -x -c config.yaml

start ok but impossible to loggin

#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?
ruby 2.3.6p384 (2017-12-14) [x86_64-linux-gnu]
On what browser?
firefox on kali rolling up to date
On what operating system?

#### Configuration

Are you using a non-default configuration?
no
Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
The `config.yaml` file probably makes use of the default password `beef`.

BeEF no longer allows a default password. Change the password, or check the console output for a new temporary password.

**Comment by lacroutelacroute** [comment]
I changed the pass and user and finally I manage to log
beef not allow the default password beef
