### ISSUE TITLE
Beef doesn't run in  Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by hunterxie123** [beefproject/beef#1500]
Environment

What version/revision of BeEF are you using?
0.4.7.0-alpha
On what version of Ruby?
ruby 2.3.1p112 
On what browser?
firefox
On what operating system?
Ubuntu 16.04 LTS

Error  :
root@hunterxie:/home/11/beef# ./beef 
/home/11/beef/core/ruby/patches/dm-do-adapter/adapter.rb:40:in `require': cannot load such file -- dm-do-adapter (LoadError)
	from /home/11/beef/core/ruby/patches/dm-do-adapter/adapter.rb:40:in `<top (required)>'
	from /home/11/beef/core/ruby.rb:18:in `require'
	from /home/11/beef/core/ruby.rb:18:in `<top (required)>'
	from /home/11/beef/core/loader.rb:25:in `require'
	from /home/11/beef/core/loader.rb:25:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./beef:44:in `<main>'

Summary :

Beef is executed with root privileges.
Steps to Reproduce :

Start the Beef from the Command line

**Comment by bcoles** [comment]
Have you tried running the install script? BeEF requires a bunch of OS dependencies.

It looks like you're missing SQLite.

Try:

```sh
sudo apt-get install zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev
```

You may or may not also need `libsqlite3-ruby`
