### ISSUE TITLE
Error while Running Beef

### ISSUE THREAD

**Issue by m-imran79** [beefproject/beef#1506]
In using :
Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.10-1kali2 (2017-11-08) x86_64 GNU/Linux

Once I click on BeEF icon from Favroit icons. I get the new terminal window open, and initially, it seems ok and I get 5 line response. 

[*] Please wait as BeEF services are started.
[*] You might need to refresh your browser once it opens.
[*] UI URL: http://127.0.0.1:3000/ui/panel
[*] Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

But then I get this result:

root@kali:~# 1518351639540	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
1518351639621	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1518351639705	addons.update-checker	WARN	Update manifest for webcompat@mozilla.org did not contain an updates property
1518351639771	addons.update-checker	WARN	Update manifest for aushelper@mozilla.org did not contain an updates property
1518351639856	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property

**Comment by bcoles** [comment]
Those are Firefox messages printed to console.
