### ISSUE TITLE
How to use it over WAN using tunnels?

### ISSUE THREAD

**Issue by th3j0ker** [beefproject/beef#1507]
Hello!

I have tried everything whatsoever but I am not able to perform tests across WAN or anywhere outside my local network, I also tried to do it using port forwarding through my wireless router but the port won't forward (as my ISP was filtering those ports so there is no way for me to do it that way), also I tried to do it using VPN so but I am not able to comprehend the fundamental logic behind this method. so I tried to make it simple, I simply tunneled my localhost using localtunnel (similar to ngrok) and now I had access to my localhost from anywhere in the world. now the question is that it doesn't work, I used my subdomain "something.localtunnel.me" instead of my local IP address, and nothing! I can access the infected page with apache2 server but browsers won't hook! , I am frustrated and directionless, Can anyone please guide me through and help me with something that I should do, or something that I am doing wrong?

thanks, and have a nice day :)

**Comment by th3j0ker** [comment]
alright, I found the solution...

basically, the VPN that I was using was blocking all other ports except 80 (HTTP) and 443 (https).. maybe that VPN was designed to filter all other vulnerable ports for standard users. so I tried it with a different VPN that doesn't filter ports and Voilá! I've achieved the kind of liberty I wished for.

so,

ISP doesn't matter
port forwarding doesn't matter
dynamic DNS may or may not matter
nothing would matter unless your VPN doesn't filter out ports

thanks!

**Comment by bcoles** [comment]
@th3j0ker  That's about right. You literally need to do nothing to get BeEF to work over a WAN interface. If you can't access the admin panel, then your network config is broken. The one caveat is that you'll want to set `public` and `public_port` for convenience in `config.yaml` as per the [FAQ](https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat).

A lot of people seem to struggle with this. Congratulations on figuring it out :)

**Comment by azamet90** [comment]
> @th3j0ker That's about right. You literally need to do nothing to get BeEF to work over a WAN interface. If you can't access the admin panel, then your network config is broken. The one caveat is that you'll want to set `public` and `public_port` for convenience in `config.yaml` as per the [FAQ](https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat).
> 
> A lot of people seem to struggle with this. Congratulations on figuring it out :)

this FAQ about ngrok is just garbage if u do a statistic about how many people have success with that FAQ over wan with ngrok u will be shocked :D

**Comment by efeobhokhan123** [comment]
Hello!

I have successfully installed beef operating system inside my Ubuntu, but my two links aren't working outside my Ubuntu operating system. Though I have tried changing my ip but still not working please help me.

**Comment by bcoles** [comment]
> Hello!
> 
> I have successfully installed beef operating system inside my Ubuntu, but my two links aren't working outside my Ubuntu operating system. Though I have tried changing my ip but still not working please help me.

* https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

**Comment by bcoles** [comment]
> I have used ngrok the problem is that the port forwarding of ngrok is only single server ngrok port forwards. Ngrok doesn't bring out multiple servers outside like having both the localhost and the target host, only local host ngrok brings

BeEF listens on port `3000` by default.

What do you mean by "the port forwarding of ngrok is only single server ngrok port forwards" ?

**Comment by efeobhokhan123** [comment]
Okay please teach me how to connect my beef to ngrok step by step guide please I don't need link description thanks for your understanding

**Comment by bcoles** [comment]
> Okay please teach me how to connect my beef to ngrok step by step guide please I don't need link description thanks for your understanding

https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

**Comment by efeobhokhan123** [comment]
How can I get a paid account
