### ISSUE TITLE
I can't  execute ./beef

### ISSUE THREAD

**Issue by MSPrime** [beefproject/beef#1510]
I just installed ruby with all other updates for beEF access. After tiring execution of codes, I installed beEF but when I try to open beEF by ./beef command, it displays "bash: ./beef: Is a directory" and no other information is provided. Please provide me with a solution for this problem as I am still new to the terminal stuff.
![screenshot from 2018-02-18 00 00 09](https://user-images.githubusercontent.com/36572808/36344330-e2b1f8c2-143e-11e8-8429-4236446ef931.png)

**Comment by bcoles** [comment]
Here's a few hints:

* `/home/user/beef` is a directory.
* You cannot execute a directory.
* You can use the `cd` command to change working directory

**Comment by MSPrime** [comment]
I tried to change the directory "beef " name to "beefy" and then executed the command but now it displays there is no such directory. Please Help.

![screenshot from 2018-02-19 13-05-33](https://user-images.githubusercontent.com/36572808/36366768-9a24492e-1575-11e8-9564-602c83ca58d8.png)

**Comment by bcoles** [comment]
Here's a few hints:

* You cannot execute something which does not exist.
* In this context, `No such file or directory` means that the specified command does not represent a file or directory in the current working directory.
