### ISSUE TITLE
beef not working on parrot os

### ISSUE THREAD

**Issue by echosj** [beefproject/beef#1514]
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: noroot option is not available
Parent pid 1996, child pid 1997
The new log directory is /proc/1997/root/var/log
Blacklist violations are logged to syslog
Child process initialized in 366.11 ms
No protocol specified
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0

Parent is shutting down, bye...

**Comment by bcoles** [comment]
This issue isn't related to BeEF.

The error is due to Firefox failing to start.

Try:

```sh
export DISPLAY=:1
```

**Comment by ansarkamina** [comment]
└──╼ $./beef
Traceback (most recent call last):
	10: from ./beef:44:in `<main>'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /home/ayan/Desktop/beef/core/loader.rb:10:in `<top (required)>'
	 6: from /usr/lib/ruby/vendor_ruby/bundler.rb:108:in `require'
	 5: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `require'
	 4: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `each'
	 3: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `block in require'
	 2: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `each'
	 1: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
Gem Load Error is: wrong argument type Class (expected Module)
Backtrace for gem load error is:
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `include'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:22:in `class_eval'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:22:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:21:in `each'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:21:in `<top (required)>'
/var/lib/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `require'
/var/lib/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `<top (required)>'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `require'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `available?'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `each'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `find'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `best_available'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:57:in `autodetect'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/var/lib/gems/2.5.0/gems/uglifier-4.1.8/lib/uglifier.rb:5:in `require'
/var/lib/gems/2.5.0/gems/uglifier-4.1.8/lib/uglifier.rb:5:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:82:in `require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:82:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `block in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `require'
/usr/lib/ruby/vendor_ruby/bundler.rb:108:in `require'
/home/ayan/Desktop/beef/core/loader.rb:10:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
./beef:44:in `<main>'
Bundler Error Backtrace:
