### ISSUE TITLE
How is BeEF able to send and force a client to run JavaScript if the page is already loaded?

### ISSUE THREAD

**Issue by keeganjk** [beefproject/beef#1516]
How is BeEF able to send and force a client to run JavaScript if the page is already loaded?

**Comment by bcoles** [comment]
wut

**Comment by keeganjk** [comment]
How does this work?

**Comment by bcoles** [comment]
JavaScript.

**Comment by keeganjk** [comment]
@bcoles How does the JS that is run update after each input? The file is only read once... Right?

**Comment by bcoles** [comment]
You can learn more about the BeEF architecture here: https://github.com/beefproject/beef/wiki/Architecture

The default command and control channel is via JavaScript [`XMLHttpRequest`](https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest). Alternatively, [WebSockets](https://en.wikipedia.org/wiki/WebSocket) can be used for command and control on modern browsers.

**Comment by keeganjk** [comment]
Thx
