### ISSUE TITLE
Add support for FISH Shell

### ISSUE THREAD

**Issue by keeganjk** [beefproject/beef#1517]
`bash -s stable < <(curl -s https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer) source ~/.bash_profile` doesn't work in the FISH Shell. http://fishshell.com Could you add a working installation guide for BASh and FISH to the wiki?

**Comment by bcoles** [comment]
lol no.

Installing RVM / rbenv is outside the scope of BeEF. Users should manage their own Ruby environment.

Updating the installation instructions in the wiki is tracked in #1477.

I've also removed the RVM installation from the `install` script.

Closing this issue.
