### ISSUE TITLE
Upload file commad is green but results is null

### ISSUE THREAD

**Issue by hackerbbk** [beefproject/beef#1520]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?
lasted
On what browser?
google chrome in android. Firefox in kali linux
On what operating system?
android and kali linux

#### Configuration

Are you using a non-default configuration?
no
Have you enabled or disabled any BeEF extensions?
no

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
The traffic light system of green, orange and red indicates that the command module works on the zombie browser and underlying operating system in use by the zombie browser. The module may have other requirements, such as the presence of third-party browser addons such as Flash, may require execution within a privileged zone, such as `chrome://`, or may require the presence of third-party libraries such as the [PhoneGap API](https://phonegap.com/).

Are you referring to the `phonegap_file_upload` module? That module only works if the [PhoneGap API](https://phonegap.com/) is available.

**Comment by bcoles** [comment]
> how to use in javascript sory for my bad english

The PhoneGap API is used for mobile applications. It is not available on websites.

**Comment by bcoles** [comment]
You can check whether the PhoneGap library is available using the [phonegap_detect](https://github.com/beefproject/beef/tree/master/modules/phonegap/phonegap_detect) module.

**Comment by bcoles** [comment]
> i understand need download zombie application  ? or hackable from browser ? for phonegap api

To use the PhoneGap API you must hook a mobile application.

**Comment by bcoles** [comment]
@hackerbbk
