### ISSUE TITLE
do_sqlite3 error during `bundle install`

### ISSUE THREAD

**Issue by keeganjk** [beefproject/beef#1523]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using? Latest

On what version of Ruby? Latest

On what browser? N/A

On what operating system? macOS High Sierra

#### Configuration

Are you using a non-default configuration? No

Have you enabled or disabled any BeEF extensions? No

#### Summary

Please provide a summary of the issue.
After running `bundle install`, this error appears:
```
Errno::EACCES: Permission denied @ rb_sysopen - /Users/[censored]/git/beef/vendor/bundle/ruby/2.3.0/gems/do_sqlite3-0.10.17/ChangeLog.markdown
An error occurred while installing do_sqlite3 (0.10.17), and Bundler cannot continue.
Make sure that `gem install do_sqlite3 -v '0.10.17'` succeeds before bundling.
```
When I run `sudo gem install do_sqlite3 -v '0.10.17'`, this error appears:
```
Building native extensions. This could take a while...
ERROR:  Error installing do_sqlite3:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/do_sqlite3-0.10.17/ext/do_sqlite3
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180316-11650-n6h3ve.rb extconf.rb
checking for sqlite3.h... yes
checking for sqlite3_open() in -lsqlite3... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib
        --with-sqlite3lib
        --without-sqlite3lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/do_sqlite3-0.10.17/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/do_sqlite3-0.10.17 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/do_sqlite3-0.10.17/gem_make.out
```

#### Expected Behaviour 

What was the expected result?
Successful installation

#### Actual Behaviour

What was the actual result?
Failed `bundle install`, failed `sudo gem install do_sqlite3 -v '0.10.17'`

#### Steps to Reproduce

Please provide steps to reproduce this issue.
Run `bundle install`

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
Have you installed SQLite3? Try running the installer script. `./install`

**Comment by keeganjk** [comment]
`./install` just gives me install instructions. Also, running `sqlite3` successfully brings up a `sqlite3` command line.

**Comment by bcoles** [comment]
The install script was updated recently. Make sure your BeEF is up to date.

However, no doubt you would have noticed the instruction for installing SQLite3 in the installation instructions.

**Comment by keeganjk** [comment]
I still get:
```
An error occurred while installing do_sqlite3 (0.10.17), and Bundler cannot continue.
Make sure that `gem install do_sqlite3 -v '0.10.17'` succeeds before bundling.

In Gemfile:
  dm-sqlite-adapter was resolved to 1.2.0, which depends on
    do_sqlite3
```
after running the new installer.

--------------------------------------
BTW, the new installer looks awesome!

**Comment by bcoles** [comment]
:(

Oh, right, you're using Mac OS. The installer won't work for Mac.

On Linux you need to `sudo apt-get install libsqlite3-0 libsqlite3-dev sqlite3`. For Mac, the packages should be named similarly.

Are you using system Ruby, or a Ruby environment manager such as rbenv/rvm?

If you're using system Ruby, you may also need `ruby-dev` or `ruby-devel` - not sure what it's called on Mac.

Do you have `xcode` installed?

**Comment by keeganjk** [comment]
I believe I'm on stock Ruby. I recently installed `rbenv`. It appears I don't have full `xcode`, but a few parts and commands of it.

**Comment by bcoles** [comment]
It looks like you're missing SQLite3. The sqlite gem won't install without the appropriate operating system libraries.

**Comment by keeganjk** [comment]
Still not working. `sqlite3` *does **exist** on the system... Do I *need* `xcode`?

**Comment by bcoles** [comment]
You'll probably need xcode.

In addition to sqlite3, you also need the libraries. On linux, the packages are `libsqlite3-0` and `libsqlite3-dev`. Googling seems to suggest `brew install sqlite3` is sufficient.

**Comment by keeganjk** [comment]
Installed Xcode, still doesn't work...

**Comment by bcoles** [comment]
The install script has recently been updated to support Mac OSX. You could try `./install`

**Comment by keeganjk** [comment]
Thanks! I'll try it in a minute!

**Comment by keeganjk** [comment]
I just went through the new installer and had some issues with things I already had installed such as `nodejs` and `python3`. Manually fixed these and went through the installer again to encounter the same error:
```
An error occurred while installing do_sqlite3 (0.10.17), and Bundler cannot continue.
Make sure that `gem install do_sqlite3 -v '0.10.17'` succeeds before bundling.

In Gemfile:
  dm-sqlite-adapter was resolved to 1.2.0, which depends on
    do_sqlite3
```

**Comment by bcoles** [comment]
Welp. You're on your own. Good luck.

If you want to buy me a Mac, or mail me your Mac, I'll have a crack at fixing it.

**Comment by Pupilo** [comment]
I solved the issue as it follows:
apt-get install ruby-dev
bundle install

**Comment by keeganjk** [comment]
@Pupilo I was in macOS

**Comment by Pupilo** [comment]
Sorry the error was similar on Linux.
On Mac try to use the homebrew to setup:
brew install ruby
bundle install
https://www.ruby-lang.org/en/documentation/installation/

Obs: 
After installing ruby open a new terminal and try again the installation of the beef. 
I've had trouble installing a lib and not having the environment variables in the updated sh.

**Comment by darksh3llgr** [comment]
> I solved the issue as it follows:
> apt-get install ruby-dev
> bundle install

That solve the problem. Thx!

**Comment by GetRektBoy724** [comment]
Thx @Pupilo ....i solve this problem with that way

**Comment by bcoles** [comment]
This has probably been fixed now with the addition of `ruby-dev` to the `install` script.

Closing this issue.

**Comment by liyiqiao02** [comment]
visit https://www.rubydoc.info/gems/do_sqlite3/0.10.17 to install do_sqlite3
