### ISSUE TITLE
[Question] Login and Zombies Connecting To Different Ports

### ISSUE THREAD

**Issue by zero77** [beefproject/beef#1524]
I am trying to get the have the beef login page on a different port to the one the zombies use, how can I do this.

For example, the zombies will connect to IP:80/hook.js and the login IP:8080/ui/authentication.
Thanks

**Comment by bcoles** [comment]
The admin UI binds to the same port.

You can use the `permitted_ui_subnet` directive to restrict access to the administrator UI based on IP address, as per the [Configuration](https://github.com/beefproject/beef/wiki/Configuration) page on the wiki.

You could restrict the admin UI to `127.0.0.1`, then access it via an SSH tunnel. It would still be on the same port though.

**Comment by zero77** [comment]
So, without white listing IPs there’s no way to do this.

**Comment by bcoles** [comment]
There are ways to do this, but require network onfiguration outside of BeEF.

**Comment by bcoles** [comment]
Tracked in #1389

Closing this issue.
