### ISSUE TITLE
API Fire Error: authentication failed in {owner=>BeEF::Extension::Metasploit::API::MetasploitHooks, :id=>22}.post_soft_load()

### ISSUE THREAD

**Issue by jake-thewoz** [beefproject/beef#1526]
I've checked every post I can find on this, including the FAQ and the documentation. I learned about the weird SSL things, but that hasn't fixed the problem. See below in my steps that I have the correct info in the config and database files as far as the ssl is concerned.

#### Environment

What version/revision of BeEF are you using?
0.4.7.0

On what version of Ruby?
2.3.6p384

On what browser?
huh? the UI runs on Firefox, but that's fine.

On what operating system?
Kali Linux, fully up to date, running on VirtualBox

#### Configuration

Are you using a non-default configuration?
no

Have you enabled or disabled any BeEF extensions?
only tried to enable Metasploit

#### Summary

Please provide a summary of the issue.
I've been following a guide to enable Metasploit in Beef. This error appears while running ./beef in the /beef-xss/ folder. 

#### Expected Behaviour

What was the expected result?
Loading the Metasploit modules into my Beef.

#### Actual Behaviour

What was the actual result?
[see title]

#### Steps to Reproduce

Please provide steps to reproduce this issue:

Run apt-get update and apt-get upgrade.
Go to /beef-xss/ and in config.yaml, change metasploit=true, ssl=true, ssl_version='TLS1'
Go to /beef-xss/extensions/metasploit/ and in config.yaml, change host=[my ip] and callback_host=[my ip] - I'm using my internal IP for both of these, 10.0.2.4
Go to /usr/share/metasploit-framework/config/ and in database.yml, verify that 'database' and 'username' = msf
Restart kali
In msf> load msgrpc ServerHost=[my ip] Pass=abc123 SSL=y
Go to /usr/share/beef-xss/ type ./beef and hit enter.
Watch your soul slowly die as the API Fire Error winks at you yet again, caring not that you have ssl=true, and ssl_version='TLS1' instead of TLSv1.

#### Additional Information

I figure there's some error happening in the /extensions/metasploit/api.rb file, but I'm just not competent enough to hardcode a fix. Any help would be really appreciated. Beef is rull fun!

**Comment by bcoles** [comment]
Welp. At a guess this is an issue with the BeEF package on Kali.

If you're in a hurry, I'd recommend cloning BeEF from GitHub.

Make sure your BeEF and Metasploit are up to date.

**Comment by bcoles** [comment]
There's a tonne of problems that could be causing your issue. Thanks for taking the time to read existing issues.

BeEF was once misconfigred by default to use `TLSv1` not `TLS1`. It seems you're aware of this issue.

There was a bug where metasploit would not reinitialize the msfrpc daemon properly in the event that you misconfigured it (perhaps without SSL?) then launched it again. The old settings would still be in effect. This was fixed about a year ago.

The msfrpc client gem BeEF uses to connect to Metasploit did not give very verbose error messages. This has since been fixed. The fact that the minimal output you've provided does not give any specific error message implies that the version of the msfrpc gem you're using is old. Which means your BeEF is old.

**Comment by jake-thewoz** [comment]
Thanks for the quick response!

I'm still a bit of a noob with kali and linux- do you recommend that I remove BeEF altogether (like apt-get remove, or rm -a the folder...?), then clone the git? Or should I just clone the git for BeEF and run it from its new directory?

I know this isn't really what you're here for, but if I could just have a little guidance with it, I'm sure I can google the rest. Thanks again!

**Comment by bcoles** [comment]
If you want to run BeEF as a service (`beef-xss`) you'll probably need to replace the BeEF install in the `beef-xss` folder with the clone from GitHub. Be aware that the install may get nuked by Kali later on when you update system packages.

The easiest approach is probably:

```sh
cd /home/jake/
git clone https://github.com/beefproject/beef
cd beef
bundle install
```

You should then be free to configure BeEF to use Metasploit as you were doing before.

**Comment by jake-thewoz** [comment]
Thanks! I'll go ahead and close this issue and provide an update when I'm able to work on this again.

**Comment by bcoles** [comment]
Cool. Chances are you may run into some issues with `bundle install`. The good news is these are easily fixed.
