### ISSUE TITLE
Get all cookies module is red and not working on google chrome 

### ISSUE THREAD

**Issue by hackerbbk** [beefproject/beef#1529]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?
lastest
On what version of Ruby?

On what browser?
google chrome
On what operating system?
android 

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

Get all cookies module is red and not working on google chrome

**Comment by bcoles** [comment]
Are you referring to this module? https://github.com/beefproject/beef/tree/master/modules/chrome_extensions/get_all_cookies

This module only works for hooks within Chrome extensions.
