### ISSUE TITLE
Error while loading eventmachine 

### ISSUE THREAD

**Issue by lkdevil** [beefproject/beef#1532]
After executing `beef` I am getting
```/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin.rb:7:in `require': cannot load such file -- eventmachine (LoadError)```
But when I installing event machine with bundler I am not getting this error but when I installing this locally, error is coming

**Comment by bcoles** [comment]
Sounds like your Ruby environment is messed up

**Comment by lkdevil** [comment]
I tried same with my other phone but same results

**Comment by slavadba** [comment]
Hi,
probably I have the same issue during install latest version using git clone :

Using bundler 1.15.1
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/eventmachine-1.0.9.1/ext
/usr/bin/ruby2.5 -r ./siteconf20180501-6484-bupa86.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/eventmachine-1.0.9.1 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/eventmachine-1.0.9.1/gem_make.out

An error occurred while installing eventmachine (1.0.9.1), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.0.9.1'` succeeds before bundling.

In Gemfile:
  thin was resolved to 1.7.2, which depends on
    eventmachine
root@kali:~/beef# 

Or its different situations and I need create another topic?

**Comment by bcoles** [comment]
@slavadba `mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h` means you probably need `ruby-dev` or `ruby-devel` depending on your OS.

You can run the handy `./install` script to install all OS dependencies.

However, BeEF hasn't been tested thoroughly on Ruby 2.5.x and you'll likely run into issues. Ruby 2.4.1 is the latest support version.

**Comment by slavadba** [comment]
"You can run the handy ./install script to install all OS dependencies." - yes, I used ./install, but the installation ended with errors that I showed above. My OS  -  Kali 2018.

**Comment by bcoles** [comment]
Welp. For Kali, you'll need `ruby-dev` or maybe it's called `ruby2.5-dev`

**Comment by slavadba** [comment]
Thank you,its help, and I install BeEF without errors - but then  started , I got another errors  - see my comment in https://github.com/beefproject/beef/issues/1547

**Comment by Auxilus** [comment]
https://github.com/eventmachine/eventmachine/issues/198

**Comment by Auxilus** [comment]
changing `eventmachine` version to `1.2.7` in Gemfile.lock worked for me

**Comment by bcoles** [comment]
Thanks @Auxilus

BeEF is not locked to a particular version of eventmachine.

The `Gemfile.lock` file should be wiped when BeEF is updated (`./update-beef`) or installed (`./install`), allowing for newer versions to be installed.

Closing this issue.
