### ISSUE TITLE
config

### ISSUE THREAD

**Issue by newdie484** [beefproject/beef#1536]
msf_path: [
{os: 'osx', path: '/opt/local/msf/'},
{os: 'livecd', path: '/opt/metasploit-framework/'},
{os: 'bt5r3', path: '/opt/metasploit/msf3/'},
{os: 'bt5', path: '/opt/framework3/msf3/'},
{os: 'backbox', path: '/opt/backbox/msf/'},
{os: 'kali', path: '/usr/share/metasploit-framework/'},
{os: 'pentoo', path: '/usr/lib/metasploit'},
{os: 'custom', path: ''}
]
my metasploit is /home/redeye/metasploit-framework
how to config that??

**Comment by bcoles** [comment]
@newdie484 

```yaml
msf_path: [
  {os: 'custom', path: '/home/redeye/metasploit-framework/'}
]
```

Be aware that this functionality may or may not be broken.

**Comment by newdie484** [comment]
http://s8.picofile.com/file/8323088142/Selection_017.png
why cant login???
my beef is work by cant login
