### ISSUE TITLE
Hooking problem

### ISSUE THREAD

**Issue by tupley** [beefproject/beef#1538]
I installed beef on my vps with system Ubuntu 16. I installed all from tutorial . After ./beef i logged to panel and clicked on Hook Me! https://imgur.com/a/EWfuD i got this error. While checking links from /demos/basic.html i see only output Internal server error.

//edit text form error: https://hastebin.com/ojolekavoy.cs

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-
