### ISSUE TITLE
I can't connect to the metasploit。。。。。。

### ISSUE THREAD

**Issue by mnnnnnnn** [beefproject/beef#1541]
I installed the beef in my mac ，but it can't connect to the metasploit the error message is shown ：

API Fire Error: execution expired in {:owner=>BeEF::Extension::Metasploit::API::MetasploitHooks, :id=>10}.post_soft_load() 

I don't know how to solve  it。。。
and When I use the default account it's shown :ERROR: invalid username or password

**Comment by bcoles** [comment]
> API Fire Error: execution expired in {:owner=>BeEF::Extension::Metasploit::API::MetasploitHooks, :id=>10}.post_soft_load()

There is a problem with your configuration.

> and When I use the default account it's shown :ERROR: invalid username or password

Check the console output for the new password.
