### ISSUE TITLE
getaddrinfo: Name or service not known (SocketError)

### ISSUE THREAD

**Issue by mjackstone6** [beefproject/beef#1552]
What version/revision of BeEF are you using?
Latest version.

On what version of Ruby?
2.5.1

On what browser?
Firefox

On what operating system?
Kali 2018.1

#### Summary

I am currently on a fresh installation of Kali. 
I am trying to run the framework using ./beef from within /usr/share/beef-xss and it generates the following error:

```
#<Thread:0x00005636a805d518@/usr/lib/ruby/vendor_ruby/rex/thread_factory.rb:29 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	2: from /usr/lib/ruby/vendor_ruby/rex/thread_factory.rb:29:in `block in spawn'
	1: from /usr/lib/ruby/vendor_ruby/rex/job_container.rb:40:in `block in start'
/usr/lib/ruby/vendor_ruby/rex/job_container.rb:39:in `ensure in block in start': undefined method `call' for nil:NilClass (NoMethodError)
BeEF > #<Thread:0x00005636a88d9e08@/usr/share/beef-xss/extensions/dns_rebinding/api.rb:21 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	3: from /usr/share/beef-xss/extensions/dns_rebinding/api.rb:21:in `block in pre_http_start'
	2: from /usr/share/beef-xss/extensions/dns_rebinding/dns_rebinding.rb:210:in `run_server'
	1: from /usr/share/beef-xss/extensions/dns_rebinding/dns_rebinding.rb:210:in `new'
/usr/share/beef-xss/extensions/dns_rebinding/dns_rebinding.rb:210:in `initialize': getaddrinfo: Name or service not known (SocketError)
#<Thread:0x00005636a88d9f98@/usr/share/beef-xss/extensions/dns_rebinding/api.rb:20 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	3: from /usr/share/beef-xss/extensions/dns_rebinding/api.rb:20:in `block in pre_http_start'
	2: from /usr/share/beef-xss/extensions/dns_rebinding/dns_rebinding.rb:14:in `run_server'
	1: from /usr/share/beef-xss/extensions/dns_rebinding/dns_rebinding.rb:14:in `new'
/usr/share/beef-xss/extensions/dns_rebinding/dns_rebinding.rb:14:in `initialize': getaddrinfo: Name or service not known (SocketError)
```

**Comment by mjackstone6** [comment]
Sorry, I'm new to this project.
Where exactly is this inside config.yaml?

For reference I'm using the config file from https://github.com/beefproject/beef/blob/master/config.yaml and the only thing that might relate to it is possibly the network extension but I still get the same error with that disabled.

**Comment by bcoles** [comment]
Your error is triggered in this file `/usr/share/beef-xss/extensions/dns_rebinding/dns_rebinding.rb`

BeEF should not load this file unless the DNS Rebinding extension is enabled.

Ensure the `extensions/dns_rebinding/config.yaml` config file has `enabled: false`.

**Comment by bcoles** [comment]
A little background on how BeEF configuration works.

Each extension has it's own `config.yaml` file in its directory. For example, the Admin UI extension has `extensions/admin_ui/config.yaml`. This file contains various configuration settings related to the extension.

Each of these configuration settings can be overwritten by the master `config.yaml` file in the BeEF root directory.

I had a look at the default configuration on Kali 2018. It appears that the `extensions/dns_rebinding/config.yaml` sets the extension to be enabled; however the master `config.yaml` file overrides this with the following:

```yaml
    extension:
        admin_ui:
            enable: true
        # ... snip ...
        dns_rebinding:
            enable: false
```

This is the expected default, as the extension is experimental.

I cannot reproduce your issue in the default configuration; however I can reproduce your issue by setting `enable: true` in the master `/usr/share/beef-xss/config.yaml`.

I assume this will resolve your issue. Closing this issue. Please re-open if this does resolve your issue.
