### ISSUE TITLE
How to Disable SSL Warning

### ISSUE THREAD

**Issue by H4xl0r** [beefproject/beef#1559]
#### Environment

What version/revision of BeEF are you using?
 0.4.7.0-alpha
On what version of Ruby?
2.5 (yes i know ) but its just a trust ssl problem
On what operating system?
KalI linux 2018

#### Summary

Hey There i am using beef_connect to connect beef and msf together, but  with  a self signed cert/pem All is working well when i disable the ssl option in beef.
But i would like to use SSL  with self signed option.

It thows this Error on connect :+1:  

How do i disable the warning ? 
msf > beef_connect https://127.0.0.1:3000 beef Hackme01!
[-] Error while running command beef_connect: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)

#### Expected Behaviour
Connection Armitage / msf to beef ....

#### Actual Behaviour
msf > load beef
[*] BeEF Bridge for Metasploit 0.1
[+] Type beef_help for a command listing
[*] Successfully loaded plugin: beef
msf > beef_connect https://127.0.0.1:3000 beef Hackme01!

[-] Error while running command beef_connect: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)

Call stack:
/usr/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
/usr/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/lib/ruby/2.5.0/net/http.rb:981:in `connect'
/usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
/usr/lib/ruby/2.5.0/net/http.rb:609:in `start'
/usr/lib/ruby/2.5.0/net/http.rb:532:in `post_form'
/usr/share/metasploit-framework/lib/beef/remote/session.rb:20:in `authenticate'
/usr/share/metasploit-framework/plugins/beef.rb:84:in `cmd_beef_connect'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:548:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:510:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:208:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:49:in `<main>'
msf > 

#### Steps to Reproduce
set up beef with self signed ssl ...
load msfconsole with connect beef 
msf > load beef
[*] BeEF Bridge for Metasploit 0.1
[+] Type beef_help for a command listing
[*] Successfully loaded plugin: beef
msf > beef_connect https://127.0.0.1:3000 beef Hackme01!

[-] Error while running command beef_connect: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)

#### Additional Information

Hope i cold get some help to fix this ? is it a beef problem ? or the Ruby ? or just the cert ? (how do i import them to avoid this warning )? thanks for beef its very nice

**Comment by bcoles** [comment]
The BeEF plugin for Metasploit has not been updating in a long time. I'm not sure that it even still

**Comment by H4xl0r** [comment]
It works with no ssl 
but i am not so familiar with ruby 
and would like to know how to change it to accept ssl and ssl self signed certs ?
maybe u have a an idea , ur more skilled rubbier then i am :-)

https://github.com/xntrik/beefmetasploitplugin
those are the files from it it think the problem resides under /lib/beef/remote/session

would be nice to get help , sure its another repo ....

**Comment by H4xl0r** [comment]
could you get me to there at least :-)? would be nice 
if its to much work , then ok , but i would like to give it a try ... 
all functions of the plugin are working for me without ssl 
so maybe it could fix it ....
just a try ... or i will have to use all without ssl (what sucks)

**Comment by H4xl0r** [comment]
will give it a try thanks mate :-)

**Comment by bcoles** [comment]
It worked for me, but you're also going to run into other issues.

At the very least, you'll also need to replace every instance of `Rex::Ui::Text::Table` with `Rex::Text::Table` in `plugins/beef.rb`

https://github.com/xntrik/beefmetasploitplugin/pull/6

**Comment by H4xl0r** [comment]
looks nice man
