### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by kirubaaa** [beefproject/beef#1562]
When i run beef and after i open UI pannel in browser its shows 'Internal sever error" 
OS Kali linux

**Comment by bcoles** [comment]
More info required. Make sure you update BeEF.

**Comment by alimp5** [comment]
Hi @bcoles 

I got same error in firefox browser:
```Internal server error```

### Beef-xss Version
0.4.7.0-0kali7

### root@kali: beef-xss -v
```
[i] Something is already using port: 3000/tcp
COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ruby    5665 beef-xss   17u  IPv4  75627      0t0  TCP *:3000 (LISTEN)

UID        PID  PPID  C STIME TTY      STAT   TIME CMD
beef-xss  5665     1  0 11:16 ?        Sl     0:03 ruby /usr/share/beef-xss/beef

[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

● beef-xss.service - LSB: BeEF
   Loaded: loaded (/etc/init.d/beef-xss; generated)
   Active: active (running) since Wed 2018-05-30 11:16:33 +0430; 12min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5659 ExecStart=/etc/init.d/beef-xss start (code=exited, status=0/SUCCESS)
    Tasks: 5 (limit: 4915)
   Memory: 164.3M
   CGroup: /system.slice/beef-xss.service
           └─5665 ruby /usr/share/beef-xss/beef

May 30 11:16:33 kali systemd[1]: Starting LSB: BeEF...
May 30 11:16:33 kali systemd[1]: Started LSB: BeEF.

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1...
```
http://127.0.0.1:3000/ui/panel:
`Internal server error`

**Comment by bcoles** [comment]
BeEF is not tested on Ruby 2.5.1

**Comment by bcoles** [comment]
BeEF has been mostly tested on 2.4.1.

Some testing has been performed on 2.5.x. It works, mostly, but hasn't been tested thoroughly.

There may or may not be some issues with db locking.

**Comment by saikishorekate** [comment]
Actually, I am using ruby 2.5.1 but I am getting an error!
Kali Linux 2018.3(Rolling Version)

Please Review this 
![screenshot from 2018-09-21 13-07-30](https://user-images.githubusercontent.com/10182914/45866769-711d5e80-bd9f-11e8-8dc0-b7c0cbbc59f6.png)
![screenshot from 2018-09-21 13-07-57](https://user-images.githubusercontent.com/10182914/45866771-711d5e80-bd9f-11e8-99ce-bb2d58ead94e.png)

**Comment by bcoles** [comment]
The BeEF package in Kali is supported by the Kali team.

Alternatively, you could try downloading BeEF from Github.

**Comment by sabri-zaki** [comment]
I download beef from Github and I get the same error 'internal server error what is the solution on Kali Linux
