### ISSUE TITLE
Official Dockerfile

### ISSUE THREAD

**Issue by brianclemens** [beefproject/beef#1564]
Any chance we can get an official docker image (and link it to this repository as an automated build)?  I've been trying to get it working on an Alpine base.  Unfortunately it's a bit painful because of the rubyracer libv8 dependency.  Anyhow, here's what I put together so far:

```
FROM joenyland/ruby-alpine-v8:2.3

RUN apk add --update --no-cache --virtual build-dependencies \
    build-base \
    git \
    sqlite-dev \
    && apk add --no-cache --virtual runtime-dependencies \
    sqlite-libs \
    && git clone -n https://github.com/beefproject/beef \
    && cd beef \
    && git checkout ${BEEF_COMMIT} \
    && bundle install \
    && apk del --purge build-dependencies

EXPOSE 3000

ENTRYPOINT ["/beef/beef"]
```
I did not file a pull request because it crashes with an error concerning xmlrpc.

**Comment by bcoles** [comment]
Hi @brianclemens 

You're more than welcome to host your own unofficial Docker image.

Here's a couple of previous attempts:

* https://github.com/beefproject/beef/pull/1397
* https://github.com/beefproject/beef/issues/1207#issuecomment-281903053

Unfortunately there's no-one to maintain an official image.
