### ISSUE TITLE
Issue with Ui in Parrot os

### ISSUE THREAD

**Issue by claytonx** [beefproject/beef#1567]
Clean install of Parrot OS on VMplayer Beef-xss starts then stops and gives error 

[*] Please wait as BeEF services are started.
[*] You might need to refresh your browser once it opens.
[*] UI URL: http://127.0.0.1:3000/ui/panel
[*] Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>
root@parrot:~# [19861:19861:0520/160933.216547:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

I've reinstalled BeEF 
installed BeEF via git hub and BeEF website

running BeEF version 0.4.6.1-alpha 
debuging is true

Seems to be a problem with running browser as root but If I start the browser then paste the UI link 
I get "Problem Loading page"

**Comment by bcoles** [comment]
0.4.6.1-alpha is ancient.

Your issue is likely related to Ruby gems, which should be fixed in the latest version of BeEF in the git repository.
