### ISSUE TITLE
Not open /hook.js, and basic demo

### ISSUE THREAD

**Issue by miklman** [beefproject/beef#1568]
Hello, i have last version BeeF
And last version Ruby
AdminPanel, Autorization work nice.

If i go to 3000/hook.js then i receive "Internal Server Error"
And this lines in log: 
`**ArgumentError - invalid byte sequence in US-ASCII:**
 /var/lib/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `scan'
 /var/lib/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `convert_input'
 /var/lib/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
 /var/lib/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
 /root/beef/beef/core/main/handlers/modules/beefjs.rb:118:in `new'
 /root/beef/beef/core/main/handlers/modules/beefjs.rb:118:in `build_beefjs!'
 /root/beef/beef/core/main/handlers/hookedbrowsers.rb:50:in `block in <class:HookedBrowsers>'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:1175:in `call'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:1175:in `block in compile!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:739:in `instance_eval'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:739:in `route_eval'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:723:in `block (2 levels) in route!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:773:in `block in process_route'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:770:in `catch'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:770:in `process_route'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:722:in `block in route!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:721:in `each'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:721:in `route!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:857:in `dispatch!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:659:in `block in call!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:823:in `block in invoke'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:823:in `catch'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:823:in `invoke'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:659:in `call!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:644:in `call'
 /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
 /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/urlmap.rb:66:in `block in call'
 /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `each'
 /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `call'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
 /var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
 /var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
 /root/beef/beef/core/main/server.rb:135:in `start'
 ./beef:220:in `<main>'`

**Comment by bcoles** [comment]
Try:

```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by miklman** [comment]
I try, it's don't help me

**Comment by bcoles** [comment]
Are you sure you're using the latest version of BeEF?

**Comment by miklman** [comment]
If 'git clone ' this repository don't give me latest version then maybe no

**Comment by miklman** [comment]
I using is vps,beef good start and none send errors

I watch in backtrace after open hook.js -> Post requests to authorization. js, after none. 
i can open adminpanel

**Comment by bcoles** [comment]
What happens if you request the hook with cURL?

`curl http://beef.local:3000/hook.js`

**Comment by bcoles** [comment]
It's likely that your system locale is messed up.

**Comment by miklman** [comment]
Sorry, but can be you say you message in more simple speech, my skills it's not translate you message, and translate service too

**Comment by miklman** [comment]
How you can advice me?

**Comment by bcoles** [comment]
Your issue is due to the system [locale](https://wiki.archlinux.org/index.php/locale).

Usually this is fixed with:

```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by bcoles** [comment]
Did you manage to fix it?

**Comment by ZZR1** [comment]
Did you manage to fix it?
