### ISSUE TITLE
Direct inject code

### ISSUE THREAD

**Issue by s0i37** [beefproject/beef#1575]
Hello.
How can I inject hook-code via direct js-code? I have a CSP who prevent <script> tag.
May I poison app-cache some js-library and put hook-code there?

**Comment by bcoles** [comment]
Yes, you can append or prepend the BeEF hook code to existing JavaScript code.

**Comment by s0i37** [comment]
You mean implementation of hook.js? Its a little bit huge file (9k lines). 
By the way, I injected this code earlier, but I had no opened session... But I'll try again.
