### ISSUE TITLE
BeF 

### ISSUE THREAD

**Issue by Sayny385** [beefproject/beef#1576]
Please help !!
API Fire Error: invalid byte sequence in US-ASCII in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>11}.mount_handler()
 I have tried 
export LC_ALL=en_US.UTF-8
But it gives error:-
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Then I had edited /etc/default/locale   from   LANG=C   to   
LANGUAGE=en_US.UTF-8
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
and tried to configure it--
But again error
sudo dpkg-reconfigure locales
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US.UTF-8",
	LC_ALL = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
Generating locales (this might take a while)...
Generation complete.

Please help !!!! Tried hard but unable to resolve Please Help Thanks for Advance!!!

**Comment by bcoles** [comment]
BeEF requires a UTF8 locale to print UTF8 characters.

If your system does not have a UTF-8 local you will be unable to print UTF-8 characters.

The error you're receiving - `cannot change locale (en_US.UTF-8)` - is an error from your system.

You need to configure your system to use a UTF-8 compatible locale. 

You can list your locales with `locale --all-locales`
