### ISSUE TITLE
Port 3000 to 80

### ISSUE THREAD

**Issue by secnum** [beefproject/beef#1581]
#### Environment

What version/revision of BeEF are you using?
0.4.7.0-alpha

On what version of Ruby?
ruby 2.5.1p57 (2018-03-29 revision 63029)

On what browser?
firefox esr 52.8.1 (64-bit)

On what operating system?
4.16.0-kali2-amd64

#### Configuration

Are you using a non-default configuration?
Just changed one line of config.yaml
```
# HTTP server
    http:
        debug: false #Thin::Logging.debug, very verbose. Prints also full exception stack trace.
        host: "0.0.0.0"
        port: "3000" => to "80"
```

Have you enabled or disabled any BeEF extensions?
No

#### Summary

Please provide a summary of the issue.
Unable to connect http://127.0.0.1/ui/panel
Same thing with port 443.
Works with 8080, 3000 (as an example)

#### Expected Behaviour

What was the expected result?
To reach http://127.0.0.1/ui/authentication

#### Additional Information
No other process listens on port 80.

**Comment by bcoles** [comment]
Are you certain there are no processes listening on port 80?

Did you modify the correct `config.yaml` file? (ie, did it actually start on port 3000?)

Were any errors printed to the console?

**Comment by alexssi** [comment]
I ran `netsat -antp | grep 80` and `netsat -antp | grep 443` nothing was displayed.
I modified and restarted beef-xss service.
No errors appeared on the console.

**Comment by bcoles** [comment]
BeEF runs as the `beef-xss` user on Kali. It probably does not have permissions to bind to privileged ports < 1024.

**Comment by Cyber-stranger** [comment]
how to run beef with my public IP.. with port forwarding? and my isp blocked port "3000"  plz tell me.

**Comment by bcoles** [comment]
> 
> 
> how to run beef with my public IP.. with port forwarding? and my isp blocked port "3000" plz tell me.

If your ISP has blocked port 3000 then you could try another port. There's more than 65 thousand to choose from.

**Comment by Cyber-stranger** [comment]
Well if I use my public IP in Beef then Beef shows me an error. How can I
use public and private IP yogurt together in beef? If the process would
tell a little. Then I will be very grateful to you.

**Comment by bcoles** [comment]
> 
> Well if I use my public IP in Beef then Beef shows me an error. How can I use public and private IP yogurt together in beef? If the process would tell a little. Then I will be very grateful to you.

The documentation is a great place to start:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

This question has been asked many times. You may find the answer you're looking for in some of the existing issues:

https://github.com/beefproject/beef/issues?q=is%3Aissue+ngrok

This issue is closed. If you believe you have found a bug please post a new issue describing what you tried to do, how you did it, what you expected to happen and what happened instead.
