### ISSUE TITLE
GTK Errors Stopping BeEF From Starting?

### ISSUE THREAD

**Issue by Astrades** [beefproject/beef#1583]
I'm using the latest version of BeEF running with ruby 2.5.1p57. Firefox is my goto and this is all on Kali rolling. Everything is the same as vanilla install.

Every time I try to run the framework, I get a ridiculous amount of gtk errors, to be specific I get css errors. For example,
(firefox-esr:2676): Gtk-WARNING **: 18:29:49.162: Theme parsing error: gtk-widgets.css:186:14: not a number

I wouldn't expect a css or a gtk error to stop the service from even starting, but it looks like that's all that's happening. Not too sure how to fix this.
 
I haven't used or updated this OS in a few months but today I picked it up and did the usual apt-get update, apt-get upgrade and then I tried to run it. Sadly, nothing,

I've tried to reinstall some of the css packages that are causing the errors but they don't seem to be helping at all.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.162: Theme parsing error: gtk-widgets.css:186:14: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.163: Theme parsing error: gtk-widgets.css:186:14: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.174: Theme parsing error: gtk-widgets.css:2749:24: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.174: Theme parsing error: gtk-widgets.css:2749:24: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.176: Theme parsing error: gtk-widgets.css:2940:14: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.176: Theme parsing error: gtk-widgets.css:2940:14: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.176: Theme parsing error: gtk-widgets.css:2946:17: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.182: Theme parsing error: gtk-widgets.css:4083:14: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.182: Theme parsing error: gtk-widgets.css:4083:14: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.182: Theme parsing error: gtk-widgets.css:4088:17: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.185: Theme parsing error: gtk-widgets.css:4729:14: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.185: Theme parsing error: gtk-widgets.css:4729:14: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.190: Theme parsing error: xfce.css:47:16: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.190: Theme parsing error: xfce.css:47:16: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.190: Theme parsing error: lightdm-gtk-greeter.css:16:14: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.191: Theme parsing error: lightdm-gtk-greeter.css:16:14: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.191: Theme parsing error: lightdm-gtk-greeter.css:26:14: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.191: Theme parsing error: lightdm-gtk-greeter.css:26:14: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.191: Theme parsing error: lightdm-gtk-greeter.css:40:16: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.192: Theme parsing error: lightdm-gtk-greeter.css:40:16: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.192: Theme parsing error: lightdm-gtk-greeter.css:96:14: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.192: Theme parsing error: lightdm-gtk-greeter.css:100:16: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.192: Theme parsing error: lightdm-gtk-greeter.css:100:16: Expected a string.

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.193: Theme parsing error: lightdm-gtk-greeter.css:279:14: not a number

(firefox-esr:2676): Gtk-WARNING **: 18:29:49.193: Theme parsing error: lightdm-gtk-greeter.css:279:14: Expected a string.

**Comment by bcoles** [comment]
BeEF hasn't been tested thoroughly on Ruby 2.5.1; however, its seems far more likely that the GTK issues are related to your web browser, rather than BeEF.

Are you sure the service doesn't start?

**Comment by Astrades** [comment]
It doesn't start at all. I looked in my processes and tried to test my
connection on ports 3000 and 80, neither accepting connections. And isn't
the requirement for ruby just 2.3 and up?

**Comment by bcoles** [comment]
Yes, the requirement for BeEF is Ruby 2.3.0 and up.

However, BeEF has not been tested very thoroughly on Ruby 2.5.1.

You could try cloning BeEF from Github.

**Comment by bcoles** [comment]
I can't reproduce this error at all on Kali 2018.

BeEF is a console application and does not use GTK. Those errors you're receiving are from Firefox, which does use GTK. I can reproduce Firefox spitting out some errors to console, but that's not related to BeEF. The service starts fine.

**Comment by Astrades** [comment]
I did a clean reinstall and I was able to get it working. I'm not sure what the issue was, now but I will definitely do some more research and try tot recreate the problem.
