### ISSUE TITLE
Using fake lastpass causes

### ISSUE THREAD

**Issue by Tomoli75** [beefproject/beef#1587]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using? 4.7.0

On what version of Ruby? 2.3.1

On what browser? Chrome Latest

On what operating system? Mac OS High Sierra

#### Configuration

Are you using a non-default configuration? Only changed the login info and domain to be my domain
 
Have you enabled or disabled any BeEF extensions? No

#### Summary

Please provide a summary of the issue.
The fake lastpass feature isn't working (neither is hooking)

#### Expected Behaviour

What was the expected result?
A fake lastpass login info feature to popup (or to hook)

#### Actual Behaviour

What was the actual result?
Absolutely nothing.

#### Steps to Reproduce

Please provide steps to reproduce this issue.
May be a problem with my setup, but just install BeEF, change login info, set domain to toms-things.ml and use http://toms-things.ml:8080/demos/butcher/index.html. (or use <script>)

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.
NameError - uninitialized constant BeEF::Core::Command::Fake_lastpass:
 /root/beef-master/core/main/handlers/modules/command.rb:33:in `add_command_instructions'
 /root/beef-master/core/main/handlers/hookedbrowsers.rb:80:in `block (2 levels) in <class:HookedBrowsers>'
 /var/lib/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb:508:in `block in each'
 /var/lib/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `block in each'
 /var/lib/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
 /var/lib/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
 /var/lib/gems/2.3.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb:505:in `each'
 /root/beef-master/core/main/handlers/hookedbrowsers.rb:80:in `block in <class:HookedBrowsers>'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:1175:in `call'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:1175:in `block in compile!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:739:in `instance_eval'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:739:in `route_eval'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:723:in `block (2 levels) in route!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:773:in `block in process_route'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:770:in `catch'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:770:in `process_route'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:722:in `block in route!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:721:in `each'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:721:in `route!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:857:in `dispatch!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:659:in `block in call!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:823:in `block in invoke'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:823:in `catch'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:823:in `invoke'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:659:in `call!'
 /var/lib/gems/2.3.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:644:in `call'
 /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
 /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/urlmap.rb:66:in `block in call'
 /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `each'
 /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `call'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
 /var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
 /var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
 /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
 /root/beef-master/core/main/server.rb:161:in `start'

**Comment by bcoles** [comment]
Fixed in 5b771274fbd3340b5fb0186cb9f6d9d0271e4a78.
