### ISSUE TITLE
Update BeEF to support Rack 2.x

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1592]

**Comment by passbe** [comment]
Fixed by @bcoles in 0a415b22520057eef565e22620a8ce13dd07e440

**Comment by bcoles** [comment]
It's not entirely supported.

For example, the Ruby environment on Kali is kind of messed up, resulting in #1593

**Comment by bcoles** [comment]
#1628

**Comment by bcoles** [comment]
@UnCorpuscler 

#1593 is a placeholder for people to find the patch.

`Can't log in` is a woefully inadequate issue description.

If you have an issue, then post an issue, with debug logs.

**Comment by UnCorpuscler** [comment]
Same debug error as #1603 aftwr patch.

**Comment by bcoles** [comment]
@UnCorpuscler That's not a debug message.

Please set `debug: true` and `beef.http.debug: true` in `config.yaml` and post the log.

**Comment by AlexandrZT** [comment]
After patch 1593 got following error 

```
127.0.0.1 - - [25/Oct/2018:13:28:21 -0400] "GET /adminui/authentication HTTP/1.1" 200 1053 0.0041
E, [2018-10-25T13:28:21.927541 #20217] ERROR -- : Unexpected error while processing request: undefined method \`unescape_path\' for Rack::Utils:Module
Did you mean?  escape_path
	/usr/lib/ruby/vendor_ruby/rack/file.rb:41:in `_call'
	/usr/lib/ruby/vendor_ruby/rack/file.rb:31:in `call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:66:in `block in call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
	/usr/lib/ruby/vendor_ruby/rack/commonlogger.rb:33:in `call'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:86:in `block in pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `catch'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/var/lib/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
	/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
	/usr/share/beef-xss/core/main/server.rb:161:in `start'
	./beef:231:in `<main>'
```
OS - kali rolling
Ruby - ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by xfox64x** [comment]
Added a "fix", for those running Kali to #1628

**Comment by bcoles** [comment]
Try this:

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install ruby-rack ruby-rack-protection ruby-sinatra
```

As per: https://github.com/beefproject/beef/issues/1628#issuecomment-464289170

**Comment by bcoles** [comment]
It seems most of the issues related to Rack 2.x should now be resolved.

As of now, cloning BeEF `master` branch and running `./install` works on latest fully up-to-date Kali, Parrot and Linux Mint 19.

Closing this issue.
