### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1593]
**Edit:** The original issue should now be fixed.

If you're encountering `Error handling HTTP request` errors, make sure you `./update-beef`, and try this:

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install ruby-rack ruby-rack-protection ruby-sinatra
```

As per: https://github.com/beefproject/beef/issues/1628#issuecomment-464289170

---

This issue is a placeholder. If you've encountered an issue that could not be resolved by the above, please ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/archive/master.zip).

If you're still encountering issues, please search the [existing issues](https://github.com/beefproject/beef/issues) and [FAQ](https://github.com/beefproject/beef/wiki/FAQ).

If you do not find a solution, please create a [new issue](https://github.com/beefproject/beef/issues/new), ensuring that you complete the issue template, and try to provide debug output where possible. Debugging can be enabled with `debug: true` set in `config.yaml`.

---

This is likely due to Rack 2.x. #1592

To fix, apply the following diff to `Gemfile`, remove `Gemfile.lock`, and run `bundle install`.

```diff
diff --git a/Gemfile b/Gemfile
index 029b0d52..a5d1a2e9 100644
--- a/Gemfile
+++ b/Gemfile
@@ -8,8 +8,8 @@
 
 gem 'eventmachine'
 gem 'thin'
-gem 'sinatra', '~> 2.0'
-gem 'rack', '~> 2.0'
+gem 'sinatra', '~> 1.2'
+gem 'rack', '~> 1.6.8'
 gem 'rack-protection', '~> 2.0'
 gem 'em-websocket' # WebSocket support
 gem 'uglifier'
```

**Comment by TheTh1nker** [comment]
What do you mean by apply the following diff to gemfile. I recently just joined github sorry if this is a noob question.

**Comment by TheTh1nker** [comment]
Nvm just figured it out.

**Comment by RaczoOBY** [comment]
i didn't got this part 
"diff --git a/Gemfile b/Gemfile
index 029b0d52..a5d1a2e9 100644
--- a/Gemfile
+++ b/Gemfile
@@ -8,8 +8,8 @@
 "
could u please help me?
i just did this steps:

*rm Gemfile.lock
*nano Gemfile:
gem 'eventmachine'
gem 'thin'
#gem 'sinatra', '~> 2.0'
#gem 'rack', '~> 2.0'
gem 'sinatra', '~> 1.2'
gem 'rack', '~> 1.6.8'
gem 'rack-protection', '~> 2.0'
gem 'em-websocket'
gem 'uglifier'
gem 'mime-types'
gem 'execjs'
gem 'ansi'
gem 'term-ansicolor', :require => 'term/ansicolor'
gem 'dm-core'

* bundle install
*./beef
and i still having problems with the logging

**Comment by Th3R4nd0m** [comment]
@TheTh1nker , how did you do it?

**Comment by jasonthename** [comment]
@bcoles Please explain how I'd do that?

**Comment by bcoles** [comment]
@jasonthename Edit the `Gemfile` file as shown in the diff.

Remove these lines:

```
gem 'sinatra', '~> 2.0'
gem 'rack', '~> 2.0'
```

Add these lines:

```
gem 'sinatra', '~> 1.2'
gem 'rack', '~> 1.6.8'
```

**Comment by ColeShelly** [comment]
Still doesn’t work.. for me

**Comment by jasonthename** [comment]
I got it to work, I changed the settings the dev told me to on the gemfile then beef requested that I update rack and I did then restart the machine and it worked

**Comment by ColeShelly** [comment]
That's really weird, I just did everything you said and it's still not working... ill keep trying.

**Comment by UnCorpuscler** [comment]
Same issue here, tried the method, beef-xss seems to not be working as well.

**Comment by ColeShelly** [comment]
What do you mean by diff --git a/Gemfile b/Gemfile
index 029b0d52..a5d1a2e9 100644
--- a/Gemfile
+++ b/Gemfile
@@ -8,8 +8,8 @@

???

**Comment by jasonthename** [comment]
@ColeShelly 

Remove these lines:
gem 'sinatra', '~> 2.0'
gem 'rack', '~> 2.0'

Add these lines:
gem 'sinatra', '~> 1.2'
gem 'rack', '~> 1.6.8'

**Comment by ColeShelly** [comment]
Still having trouble logging, Sorry I just really want to get this fixed.

**Comment by bcoles** [comment]
@ColeShelly need a little more information. If you have an issue, post an issue. Preferably with some debug output.

**Comment by bcoles** [comment]
This issue is a placeholder so people can find the patch. Locking.

**Comment by bcoles** [comment]
The tags on this issue don't make sense. This is not an issue, and can be closed.

This issue was created as a placeholder titled `Can't log in` so that user's could find it. This was necessary due to an influx of issues caused by package conflicts. There is no specific issue here, and the package situation is now well over a year old.

If there are issues logging in, then a new issue should be created with specific details and logs.

If there are issues related to a specific version of Rack or Sinatra, a new issue should be created.

**Comment by wadealcorn** [comment]
Thanks
