### ISSUE TITLE
Merge BeEF NG

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1594]
Review and merge [BeEF NG](https://github.com/beefproject/beef/tree/beef_NG) for web server agnosticism.

**Comment by bcoles** [comment]
@passbe This was never merged. The PR wasn't created by antisnatch0r, it was created by a rogue PR bot.

Unfortunately the BeEF NG branch also got messed up at one point in time, presumably due to a typo. There's a `BeEF_NG` branch and a `BeEF_N` branch. This needs to be investigated.

**Comment by bcoles** [comment]
In retrospect, it might not have been a bot. #1431

The PR wanted to merge only the `BeEF_N` branch into master, ignoring the much large `BeEF_NG` branch, and provided no commentary or context.

I have no idea who the author is, and neither the author nor antisnatch0r have followed up.

A lot of changes have been made to BeEF since these branches.

**Comment by passbe** [comment]
I'd suggest we close this issue and move forward then.

**Comment by bcoles** [comment]
The PR should be reviewed.

A huge amount of support issues have been generated due to Rack and dependencies. The dependencies have also caused issues with packages on various Linux distributions.
