### ISSUE TITLE
Getting BeEF listening on https://mydomain.io:3000

### ISSUE THREAD

**Issue by tootytagames** [beefproject/beef#1598]
Hello, I have been using BeEF OK for a few days on my Debian 9.1 box in google's cloud.  I've set up an ingress rule to my BeEF instance on port 3000.

I can get to the external IP just fine, http://a.b.c.d:3000/ui/panel, but if I use my domain name, secure or not, it doesn't seem to let me in.  I was expecting it to redirect me to the authorization part then to the admin console.  It just hangs.

I have my domain behind CloudFlare, which I suspect might be the issue... but I don't really know where to start debugging this.

Ideally I'd like to have public: mydomain.io, in config.yaml, and enable secure mode;  I have the CloudFlare cert and key in the beef directory as beef-key.pem and beef-cert.pem,  I have enabled and disabled SSL in CloudFlare, set it to flexible mode, and still no luck getting through to my BeEF admin panel by going to mydomain.io:3000/ui/panel.

Does anyone know of what might be causing this issue, and why I can only access it through its external IP and not the domain name?

**Comment by tootytagames** [comment]
Managed to think of where the traffic would normally go (ports 80, 443), and looked up where CF proxies traffic for http and https.  Selected ports 8080 and 8443 for http and https respectively, enabled incoming traffic on those ports to my Debian instance in Google cloud, all working now.

**Comment by siva-hub-hub** [comment]
I want to use beef + cloudflared domain what are the config I want to change
