### ISSUE TITLE
ERROR:  type modifier is not allowed for type "bytea"

### ISSUE THREAD

**Issue by Felarof23** [beefproject/beef#1605]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?
 0.4.7.0-alpha

On what version of Ruby?
ruby 2.5.1p57

On what browser?
Chrome

On what operating system?
Linux kali 4.1.19-v7 #1 SMP Tue Mar 15 15:10:00 CDT 2016 armv7l GNU/Linux

#### Configuration

Are you using a non-default configuration?
yes, driver :postgres

Have you enabled or disabled any BeEF extensions?
yes, metasploit

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?
run BeEF normally

#### Actual Behaviour

What was the actual result?
Error when it try to create postgresql database

#### Steps to Reproduce

Please provide steps to reproduce this issue.

change driver to postgres in config.yaml
change port to 5432 in config.yaml
enable dm-postgres-adapter
successfully bundle install
run ./beef

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

Postgresql Version:
psql (10.4 (Debian 10.4-2), server 9.6.5)

![image](https://user-images.githubusercontent.com/5028343/43926334-8cd70a58-9bef-11e8-9407-f7825e534332.png)

![image](https://user-images.githubusercontent.com/5028343/43926376-b130e572-9bef-11e8-90ed-9d25874f0753.png)

**Comment by bcoles** [comment]
I also ran into this a while ago. https://github.com/beefproject/beef/issues/932#issuecomment-69188364

Changing the column type to `Text` in the `extensions/requester/models/http.rb` model resolved the issue (at least for plain text).

I'm not sure how well that will work with binary data, but it probably can't make things any worse, as there's other bugs lurking in the requester/proxy code when dealing with binary data, such as #1460.

**Comment by bcoles** [comment]
BeEF now uses ActiveRecord instead of DataMapper, which may (or may not) have resolved this issue.

More importantly, BeEF no longer supports PostgreSQL.

Closing.
