### ISSUE TITLE
ERROR: invalid username or password

### ISSUE THREAD

**Issue by ynizon** [beefproject/beef#1607]
Hello,
I use Kali 2018-02.
I update my system.
I take the latest github of Beef, then when i try to login, i have this error:
ERROR: invalid username or password
With the debug, i see this error:
Undefined method extract_multipart for Rack::Multipart::Module
All my Gem files are updated (the rack is v2.0.5)

Any idea to fix this ?
Thanks

**Comment by bcoles** [comment]
#1593

**Comment by bjackfsk** [comment]
use Kali 2018-02.
I update my system.
I take the latest github of Beef, then when i try to login, i have this error:
ERROR: invalid username or password
With the debug, i see this error:\


can me reasonpose quickly

**Comment by bcoles** [comment]
> 
> 
> use Kali 2018-02.
> I update my system.
> I take the latest github of Beef, then when i try to login, i have this error:
> ERROR: invalid username or password
> With the debug, i see this error:\
> 
> can me reasonpose quickly

You can find the username and password in `/etc/beef-xss/config.yaml`.

**Comment by TH3V1P3R** [comment]
Hello , i've seen the Config.yaml file and i found that the
-username : beef
-passwoed : 'your linux system login password!'
im using kali 2021.

**Comment by KareemAk** [comment]
> 
it worked! thanks a lot pal!
