### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Corleanus** [beefproject/beef#1610]
Why? Why? Why does it always has to be some ninjucu with this program! I know it is not actively maintained but please sync it with atleast kali linux so that making everything works does not lasts longer than actually using the program!

**Comment by passbe** [comment]
@Corleanus could you please provide some more details here. Kali's ruby system is not great and it is difficult to maintain beef across so many different systems. This may be related to #1593.

**Comment by bcoles** [comment]
> atleast kali linux

There's more to the world than Kali.

I broke Kali support so as to support other distributions. It's something I had been putting off for a while, but had to be done eventually.

I'm confident the Kali package managers will fix it eventually, if they haven't already.
