### ISSUE TITLE
wont hook when using ngrok or serveo.net

### ISSUE THREAD

**Issue by laughingman2k17** [beefproject/beef#1611]
hi im using beef with ngrok and serveo when i try them they dont hook i added the hooking script to my webpage but still dont hook but hooks when using lan ip

**Comment by bcoles** [comment]
A few other users have used ngrok and managed to get it working. You might find some useful information in one of the issues:

* https://github.com/beefproject/beef/issues?utf8=%E2%9C%93&q=is%3Aissue+ngrok+

**Comment by bcoles** [comment]
#1619
