### ISSUE TITLE
Detect LastPass Not Working

### ISSUE THREAD

**Issue by beachjosh77** [beefproject/beef#1612]
#### Environment

What version/revision of BeEF are you using?
0.4.7.0-0kali7
On what version of Ruby?
1.2.5.1
On what browser?
Firefox ESR
On what operating system?
Kali

####Configuration

Are you using a non-default configuration?
No
Have you enabled or disabled any BeEF extensions?
No

####Summary

Please provide a summary of the issue.
I tried using the "Detect LastPass" command on a Windows 10 host machine to detect the LastPass extension on the Vivaldi browser but it gave me the result that LastPass was not installed

####Expected Behavior

What was the expected result?
The command would detect the LastPass extension

####Actual Behavior

What was the actual result?
The command did not detect the LastPass extension yielding a false negative 

####Steps to Reproduce

Please provide steps to reproduce this issue.
1. Run beef on Kali
2. Connect to a Windows 10 zombie
3. Install Vivaldi browser and the LastPass extension on the zombie (not sure if it's exclusive to the browser)
4. Execute the "Detect LastPass" command

**Comment by DeezyE** [comment]
I will look at this

**Comment by DeezyE** [comment]
Looks like I should be able to use `lpform` as one method
```
<div id="__lpform_user" style="max-height: 16px; vertical-align: top; position: absolute; top: 114px; left: 1083px; z-index: 8;"><img id="__lpform_user_icon" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAARNJREFUOBGlU72ORWAQPYREq9CtRryBQqJSaGziATyB1/AaV3c7ryAegUZHfxM1hUTiZ82EXbvVcicx35yZOWe+nxDiOP4E8FjX9WNb/22CILy25kjc3GUyTdkHPsSrk4l8GHFpB2/ZbQFVVXnwbQHXdX8EJEkCJRzHwXa7XLAsC57nQVEUxoZhwPd9aJrG+HASBbZtswDFXdeh73sEQUAQsiwjz3OEYcixrutIkoRr5PgI0zR9Jyj+i7fbxjzP3HOuUYJ3UBQFlmXBOI5omoYb0zQFXVRZlkx+Pp8wTRNVVXH9cCxAZBI5W13XZ4i2bfn7ldzA7VfIsoy1bgsMw/CewHEUcf+rDnxpJS4dIbojsnOiL0hfafwTOClcAAAAAElFTkSuQmCC" style="opacity: 0.6; vertical-align: top;" width="16" height="16"></div>
```

**Comment by bcoles** [comment]
Is this done?
