### ISSUE TITLE
Can BEEF-xss get any unique identifier of a smart phone or computer?

### ISSUE THREAD

**Issue by linuxsa00** [beefproject/beef#1613]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?
latest version 

On what version of Ruby?

On what browser?

On what operating system?

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information
Hi, I notice BEEF-xss is able to tell a computer / smart phone's brand and version.  How does it obtain it?   Is BEEF-xss able to obtain unique identifier of a smart phone / computer such as IMEI, android ID, MacAddress, MEID, ESN or IMSI?

**Comment by bcoles** [comment]
BeEF uses various JavaScript functions to retrieve information about the browser and underlying host system.

The source is available here:

* https://github.com/beefproject/beef/tree/master/core/main/client

In particular:

* https://github.com/beefproject/beef/blob/master/core/main/client/browser.js

**Comment by linuxsa00** [comment]
Thanks for your explanation.  Does it mean that I can actually add new functions to my BEEF-XSS by putting more .js into the folder?   Is there any additional steps needed?

**Comment by bcoles** [comment]
It's probably best to implement your functionality as a command module. These modules live in the [modules directory](https://github.com/beefproject/beef/tree/master/modules) and are loaded into the framework automatically when BeEF starts.

If you want to modify the core libraries, you can modify the existing JS files in the [core/main/client](https://github.com/beefproject/beef/tree/master/core/main/client) directory.

If you want to add new libraries, you can add JS files to this directory, however you'll also need to add the file path to the `beef_js_sub_files` variable in the [beefjs.rb](https://github.com/beefproject/beef/tree/master/core/main/handlers/modules/beefjs.rb) loader. The new files will be compiled into the hook JavaScript file when BeEF is started.

**Comment by linuxsa00** [comment]
Thanks, I will try.  So I do not need to compile the BEEF-XSS, and it will just auto compile when I restart BEEF-XSS?

And can I possibly backup the Zombies I previously recorded using BEEF-XSS?  Will they disappear after add new modules or download latest BEEF-XSS?

**Comment by bcoles** [comment]
I assume you're refering to the hook file, in which case, no, you do not need to compile anything. The [beefjs.rb](https://github.com/beefproject/beef/tree/master/core/main/handlers/modules/beefjs.rb) loader specifies which files are to be combined into the JavaScript hook. The JavaScript hook is dynamically generated using the files specified in the [beefjs.rb](https://github.com/beefproject/beef/tree/master/core/main/handlers/modules/beefjs.rb) loader when the framework starts.

The zombies will not disappear from BeEF unless you start BeEF with the `-x` flag. BeEF makes use of a database. All zombie details are stored in the database. The default database is a SQLite3 database called `beef.db` stored in the BeEF root directory. The `-x` flag tells BeEF to clear the database.

```
# ./beef -h
Usage: beef [options]
    -x, --reset                      Reset the database
    -v, --verbose                    Display debug information
    -a, --ascii_art                  Prints BeEF ascii art
    -c, --config FILE                Load a different configuration file: if it's called custom-config.yaml, git automatically ignores it.
    -p, --port PORT                  Change the default BeEF listening port
    -w, --wsport WS_PORT             Change the default BeEF WebSocket listening port
```
