### ISSUE TITLE
Cannot log in with default credentials

### ISSUE THREAD

**Issue by KNobles** [beefproject/beef#1626]
Hello just cloned beef on Parrot Security (the default beef-xss doesn't work), installed it with bundle etc. and I followed the others issues with the missing password but still can't find a solution. If I change rack's version my login page just have the beEF logo with no text field. I am using the latest ruby version and cloned beef (again) today to see if it was the version but still have the issue

**Comment by KNobles** [comment]
Well i don't know why but I get this after applying the #1593 patch 
![image](https://user-images.githubusercontent.com/14289711/46288803-4ee9c480-c587-11e8-8778-cb63fce08049.png)

On the latest Parrot.

**Comment by bcoles** [comment]
I'm doing a full dist upgrade on Parrot now to test. But chances are high that patch will work. Did you remember to remove the `Gemfile.lock` before running `bundle install`?

**Comment by KNobles** [comment]
Yup I even reinstalled a fresh Parrot and cloned beef then after the error I went in the `Gemfile`, changed rack and sinatra version, then removed the `Gemfile.lock `and then did `bundle install` thus getting me to the screen shown.

**Comment by bcoles** [comment]
Welp. Updates are gonna take a while.

Do you have nodejs installed? You could try running the installer `./install` in case there's missing dependencies.

**Comment by KNobles** [comment]
Yes i'm using nodejs v8.11.2 and after running the install I get this 
![image](https://user-images.githubusercontent.com/14289711/46290330-d802fa80-c58b-11e8-9a90-3dd4e99a9bc2.png)

**Comment by bcoles** [comment]
No errors in BeEF terminal or web browser console? Tried clearing cache?

**Comment by KNobles** [comment]
Indeed i have errors in browser console : 
`Loading failed for the <script> with source “http://localhost:3000/ui/media/javascript/ext-base.js”.`
`Loading failed for the <script> with source “http://localhost:3000/ui/media/javascript/ext-all.js”.`
`Loading failed for the <script> with source “http://localhost:3000/ui/media/javascript-min/web_ui_auth.js”.`
![image](https://user-images.githubusercontent.com/14289711/46290796-18af4380-c58d-11e8-9635-e56939baf35f.png)

**Comment by bcoles** [comment]
If you request those URLs in a browser (or with CURL), do they load?

**Comment by KNobles** [comment]
Doing so i'm getting Internal Server error
![image](https://user-images.githubusercontent.com/14289711/46291955-126e9680-c590-11e8-9835-d24248363b7d.png)

**Comment by bcoles** [comment]
Welp. If you enable `debug: true` and `beef.http.debug: true` in `config.yaml` you might get some better output as to the cause of the error.

**Comment by bcoles** [comment]
This issue is reminiscent of an issue with kali/parrot a while ago that should have been resolved.

I can't reproduce this issue on Parrot. Still waiting for upgrade to finish.

**Comment by KNobles** [comment]
Well I'll dig in it more later I have something to do. If i can't find the problem i'll reinstall my Parrot and directly clone beef and do the #1592 fix on it to see if there was something i did before that went wrong.

**Comment by bcoles** [comment]
I was able to reproduce this issue on fully updated Parrot, with and without the patch to Gemfile.

**Comment by bcoles** [comment]
Tracking in #1628

**Comment by KNobles** [comment]
Thanks ! I'll wait until there's a fix.

**Comment by bcoles** [comment]
Hi @Knobles

Try this:

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install ruby-rack ruby-rack-protection ruby-sinatra
```

As per: https://github.com/beefproject/beef/issues/1628#issuecomment-464289170

**Comment by bcoles** [comment]
Closing this issue, but please let us know if it doesn't work for you.

**Comment by 42force** [comment]
> Closing this issue, but please let us know if it doesn't work for you.

still doesn't work for latest Kali as root user.
