### ISSUE TITLE
undefined method merge

### ISSUE THREAD

**Issue by alexStrickner00** [beefproject/beef#1629]
Beef Version: 4.7.0
Ruby Version: 2.5.1, 2.3.0, 2.4.1
Firefox
Debian 9
default configuration

I'm running beef on my vServer. When I try to hook a browser i get this error message:

`E, [2018-10-02T07:00:21.810397 #12536] ERROR -- : Unexpected error while processing request: undefined method `merge' for "":String
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1112:in `handle_exception!'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1100:in `block in dispatch!'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1100:in `rescue in dispatch!'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1107:in `dispatch!'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/urlmap.rb:68:in `block in call'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `each'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `call'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/home/alex/beef/vendor/bundle/ruby/2.3.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/home/alex/beef/core/main/server.rb:161:in `start'
	./beef:231:in `<main>'
`

**Comment by chichicuervo** [comment]
happening to me too.... what do?

**Comment by bcoles** [comment]
Probably related to #1592

**Comment by chichicuervo** [comment]
well.....

`E, [2018-11-26T05:40:41.061990 #7982] ERROR -- : Unexpected error while processing request: undefined method `merge' for "":String
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1112:in `handle_exception!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1100:in `block in dispatch!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1100:in `rescue in dispatch!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1092:in `dispatch!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
        /var/lib/gems/2.5.0/gems/rack-2.0.6/lib/rack/null_logger.rb:9:in `call'
        /var/lib/gems/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
        /var/lib/gems/2.5.0/gems/rack-2.0.6/lib/rack/urlmap.rb:68:in `block in call'
        /var/lib/gems/2.5.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `each'
        /var/lib/gems/2.5.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `call'
        /var/lib/gems/2.5.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
        /var/lib/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
        /var/lib/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
        /usr/local/beef/core/main/server.rb:161:in `start'
        ./beef:231:in `<main>'
`

**Comment by bcoles** [comment]
Any luck with this @alexStrickner00

Perhaps try this:

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install ruby-rack ruby-rack-protection ruby-sinatra
```

As per: https://github.com/beefproject/beef/issues/1628#issuecomment-464289170
