### ISSUE TITLE
SSL/TLS issue

### ISSUE THREAD

**Issue by noraj** [beefproject/beef#1636]
#### Environment

What version/revision of BeEF are you using? `0.4.7.0-alpha`

On what version of Ruby? `ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]`

On what browser?

Using Firefox 62.0.3 and Opera 56.0.3051.36

```
curl --version 
curl 7.61.1 (x86_64-pc-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

On what operating system? Manjaro up to date.

#### Configuration

Are you using a non-default configuration? Default.

Have you enabled or disabled any BeEF extensions? No.

#### Summary

If trying to load the UI or the hook through HTTPS, I get a certificate issue: `SSL_ERROR_RX_RECORD_TOO_LONG` (in Firefox).

![](https://i.imgur.com/jUpAQP6.png)

Or a less verbose message on Opera:

![](https://i.imgur.com/eBbhUQB.png)

No problem with HTTP.

#### Expected Behaviour

Loading the page seamlessly.

#### Actual Behaviour

Can't load the page.

#### Steps to Reproduce

Please provide steps to reproduce this issue.

```
$ curl -vvv https://x.x.x.x:3000/hook.js
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to x.x.x.x (x.x.x.x) port 3000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

#### Additional Information

Maybe the embedded Apache server serving offering too old SSL version?

**Comment by bcoles** [comment]
This might be a dumb question, but... have you configured BeEF to use HTTPS? BeEF does not use HTTPS by default. You'll need to enable HTTPS in the `config.yaml` config file.

Also, BeEF uses a Ruby server (Rack) - it doesn't use an embedded Apache server.

**Comment by noraj** [comment]
The question is not stupid, I'm maybe dumber than the question.

Yeah I miised the `enable: false` on `https` section, laso I don't know why I said apache. Shame on me.
