### ISSUE TITLE
Internal Server Error (Ruby 2.3)

### ISSUE THREAD

**Issue by cybergulag** [beefproject/beef#1648]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using? 0.4.7.0-alpha

On what version of Ruby? 2.3

On what browser? Firefox

On what operating system? Debian 9

#### Configuration

Are you using a non-default configuration? no

Have you enabled or disabled any BeEF extensions? no

#### Summary

Please provide a summary of the issue.

I have successfully installed Beef on my Debian 9 system without any errors.
I am able to login to UI panel, however I am unable to:
1) hook any browser
2) navigate to demo page, I receive "Internal Server Error"
3) interact with The Butcher page (the page is loading, but the buttons are inactive

#### Expected Behaviour

What was the expected result?

The expected result was to be able to hook browsers

#### Actual Behaviour

What was the actual result?

I am unable to hook browsers / open demo pages
#### Steps to Reproduce

Please provide steps to reproduce this issue.
Install beef, change login credentials, navigate to UI, click "Demo" -> Receive an error "Internal Server Error"

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

Debug log when I click on "Demo" page:
E, [2018-11-28T17:32:08.189273 #2234] ERROR -- : Unexpected error while processing request: invalid byte sequence in US-ASCII
	/var/lib/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `scan'
	/var/lib/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `convert_input'
	/var/lib/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
	/var/lib/gems/2.3.0/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
	/root/beef/extensions/demos/handler.rb:26:in `new'
	/root/beef/extensions/demos/handler.rb:26:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/urlmap.rb:68:in `block in call'
	/var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `each'
	/var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/root/beef/core/main/server.rb:161:in `start'
	./beef:231:in `<main>'

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-

**Comment by cybergulag** [comment]
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-

I can't understand where I should add these lines as config.yaml does not have anything similar to those lines

**Comment by cybergulag** [comment]
Can anybody explain how to fix this error as the explanation provided here [https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-](url) is extremely vague

**Comment by bcoles** [comment]
@cybergulag 

```
$ export LANG=en_US.UTF-8
$ export LANGUAGE=en_US.UTF-8
$ export LC_ALL=en_US.UTF-8
$ ./beef -x
```

**Comment by cybergulag** [comment]
Resolved after I installed 
> apt-get install -y locales
