### ISSUE TITLE
BeEF-XSS Ruby Error

### ISSUE THREAD

**Issue by Dusk2DawnYT** [beefproject/beef#1649]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?
0.4.7.0-alpha
On what version of Ruby?
Ruby 2.5
On what browser?
Firefox
On what operating system?
Kali Linux

#### Configuration

Are you using a non-default configuration?
Yes
Have you enabled or disabled any BeEF extensions?
No

#### Summary

Please provide a summary of the issue.

root@Kali-Linux: /usr/share/beef-xss# ./beef
Traceback (most recent call last):
	19: from ./beef:32:in `<main>'
	18: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	17: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	16: from /usr/share/beef-xss/core/loader.rb:21:in `<top (required)>'
	15: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	14: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	13: from /usr/lib/ruby/vendor_ruby/em-websocket.rb:14:in `<top (required)>'
	12: from /usr/lib/ruby/vendor_ruby/em-websocket.rb:14:in `each'
	11: from /usr/lib/ruby/vendor_ruby/em-websocket.rb:15:in `block in <top (required)>'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /usr/lib/ruby/vendor_ruby/em-websocket/handshake.rb:1:in `<top (required)>'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /usr/lib/ruby/vendor_ruby/http/parser.rb:1:in `<top (required)>'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /usr/lib/ruby/vendor_ruby/http_parser.rb:1:in `<top (required)>'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ruby_http_parser (LoadErro)
root@Kali-Linux:/usr/share/beef-xss#

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by Dusk2DawnYT** [comment]
Sorry there was an error with the details above. I accidently put the BeEF version in the Ruby version. I am using BeEF version 0.4.7.0-alpha and ruby 2.5

**Comment by bcoles** [comment]
Closing as duplicate of #1654
