### ISSUE TITLE
Feature Request: Fake Mac OS X Icon

### ISSUE THREAD

**Issue by JonathanWilbur** [beefproject/beef#1656]
BEEF should include an attack module that can make a fake Mac OS icon (such as the Safari compass icon) bounce up from the bottom of the screen as though there were a notification. It should first check that the User Agent indicates that it is a Mac OS X device, and then, ensure (or at least, intelligently guess) if the browser window is full-screen or at least touching the bottom of the screen (where the dock usually is).

**Comment by DeezyE** [comment]
Closed Stale
