### ISSUE TITLE
How to update beef?

### ISSUE THREAD

**Issue by pepal00** [beefproject/beef#1661]
#### Environment

Beef version: '0.4.7.0-alpha'
OS: 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux 
    (removed Kali beef and installed from repository)

#### Configuration

I've edited the `config.yaml` file to change authentication and access controls parameters to fit my needs.

#### Summary

Because of the above, when trying to `git pull` or `./update-beef` I get the following ```error: Your local changes to the following files would be overwritten by merge:
	config.yaml
Please commit your changes or stash them before you merge```

This is most likely my lack of knowledge on Git operations, but how do I keep my changes on the config.yaml file AND update beef?

**Comment by bcoles** [comment]
Unfortunately I don't have an easy solution for you, beyond creating a backup of the existing config, or making a backup of only the changes (`git diff config.yaml > myoldconfigchanges`). Then reset the `config.yaml` with `git checkout config.yaml`, updating, and manually re-applying the changes after updating.

**Comment by pepal00** [comment]
Thank you! that did the trick

**Comment by bcoles** [comment]
No worries.

I made a few updates to BeEF the past couple days. They should be available when you update.

Chances are high that I've broken something. If there's any new issues, I can probably get it fixed pretty quick.

Closing this issue.

**Comment by RoryPratt** [comment]
ty
