### ISSUE TITLE
Problem while starting beef

### ISSUE THREAD

**Issue by GetRektBoy724** [beefproject/beef#1665]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).
Problem:
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- public_suffix (LoadError)            from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/vendor_ruby/addressable/uri.rb:21:in `<top (required)>'                                                     from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                   from /usr/lib/ruby/vendor_ruby/dm-core.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/beef-xss/core/loader.rb:27:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from beef:32:in `<main>'
#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?

On what browser?

On what operating system?

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by bcoles** [comment]
Is the `public_suffix` gem installed?

```sh
gem list | grep public_suffix
```

Have you run `bundle install`? `public_suffix` is required by `addressable`, which is required by `dm-core`. It should have been installed automatically with `bundle install`.

**Comment by GetRektBoy724** [comment]
Ok....i will try it

**Comment by bcoles** [comment]
Any luck with this?
