### ISSUE TITLE
migrate away from dm-serializer

### ISSUE THREAD

**Issue by blshkv** [beefproject/beef#1676]
dm-serializer is dead. The latest commit was back in 2012 and the official repository has been archived by the owner.

The latest release 1.2.2 requires very old dependencies such as json 1.6,  that causes additional problem on maintainers  of linux distributions, etc.

Would be good if you could find a better supported alternative

**Comment by bcoles** [comment]
Hey @blshkv

This was on my list of things to fix this weekend. It should be fixed now.

I may have introduced some other issues in the process, but they shouldn't be too hard to fix, and shouldn't have any effect on your package build process.
