### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1680]
Termux is not an officially supported platform for BeEF.

I have no idea if BeEF works on Termux. Apparently it does.

If you have issues, @Auxilus is a nice guy and may or may not be able to help.

**Comment by Auxilus** [comment]
I have a working workflow for using beef in termux,
1. clone the repo
2. update `rubydns` version to `2.0.2`(latest) in Gemfile
3. Install nodejs
4. ./beef

**Comment by bcoles** [comment]
@Auxilus awesome. You're probably better off disabling the DNS extension in `config.yaml` though. The DNS extension was never updated to make use of the new RubyDNS library 2.x which uses a new async library. Even if you update the gem dependency, the extension won't work.

**Comment by Auxilus** [comment]
meh... It's working, that's what matters for running app for the first time.
rubydns was apparently requesting ancient version of eventmachine which isn't supported for termux 🙆

**Comment by Auxilus** [comment]
![screenshot_20190217-122942](https://user-images.githubusercontent.com/23075789/52909523-c490cb80-32af-11e9-839d-914e0f800569.png)

**Comment by AhMaD-LaRy** [comment]
beef
Traceback (most recent call last):
        5: from beef:44:in `<main>'
        4: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        2: from /data/data/com.termux/files/usr/share/beef-xss/core/loader.rb:9:in `<top (required)>'
        1: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)
$

plz how i can fix !!?

**Comment by bcoles** [comment]
@AhMaD-LaRy Have you run `bundle install` ?

Termux is not an officially supported platform for BeEF.

**Comment by AhMaD-LaRy** [comment]
yes

**Comment by sabri-zaki** [comment]
Auxilus how did you install beef

**Comment by Auxilus** [comment]
@sabri-zaki 
https://github.com/beefproject/beef/issues/1680#issuecomment-464422903

**Comment by sabri-zaki** [comment]
not working as you see in the image
![Screenshot_20190504-182505](https://user-images.githubusercontent.com/37634605/57182704-063a1700-6e9a-11e9-838a-5d8478940fc8.png)

**Comment by Mik39907** [comment]
Can you reopen the case and help us out?

**Comment by bcoles** [comment]
@Mik39907  your best bet is to bug @Auxilus

**Comment by Auxilus** [comment]
@sabri-zaki try https://github.com/beefproject/beef/issues/1680#issuecomment-464422903

**Comment by stalkerned** [comment]
![Screenshot_20191002-203308](https://user-images.githubusercontent.com/47676780/66063176-e8113980-e553-11e9-987e-577ae50d7412.png)
I launched the beef. Why don't I have a color log in the console? can i fix it?

**Comment by stalkerned** [comment]
> @ sabri-zaki try [# 1680 (комментарий)](https://github.com/beefproject/beef/issues/1680#issuecomment-464422903)
> 
> Я только что проверил, все еще работает.

you will not advise how to make a color broad gull?

**Comment by rooted-cyber** [comment]
![Screenshot_2020-01-03-20-26-46](https://user-images.githubusercontent.com/50019150/71730148-6dfc9380-2e67-11ea-9486-2fba2dc75fbb.png)
not work

**Comment by rooted-cyber** [comment]
> I have a working steps for using beef in termux,
> 
> 1. clone the repo
> 2. update `rubydns` version to `2.0.2`(latest) in Gemfile
> 3. Install nodejs
> 4. ./beef

yhi to kiye lekin fir v error

**Comment by Tajmirul** [comment]
@Auxilus 
How to update rubydns version to 2.0.2(latest) in Gemfile

**Comment by rooted-cyber** [comment]
> @Auxilus
> How to update rubydns version to 2.0.2(latest) in Gemfile
> Please help me...

kali, ubuntu .. ye sb install lro isme beef install ho jayega ya ek bar metasploit install kr k beef install kro

**Comment by rooted-cyber** [comment]
> > @Auxilus
> > How to update rubydns version to 2.0.2(latest) in Gemfile
> > Please help me...
> 
> kali, ubuntu .. ye sb install lro isme beef install ho jayega ya ek bar metasploit install kr k beef install kro

ubuntu me beef install kiye or install ho gya tha 40-50 min lga tha

**Comment by Tajmirul** [comment]
can't I download it in **termux**...??

**Comment by rooted-cyber** [comment]
> can't I download it in **termux**...??

https://github.com/rooted-cyber/Termux-os2
ynha se ubuntu kr lo or beef usme install kro

**Comment by Tajmirul** [comment]
![Screenshot_20200710-192923](https://user-images.githubusercontent.com/62275307/87160213-71744a00-c2e4-11ea-8c3e-7afa7046ad17.png)
How to solve this error...??
@Auxilus

**Comment by Auxilus** [comment]
@Tajmirul do you have `ruby-dev` and/or other dependencies installed installed? the error message should say which lib is missing

**Comment by Jay1352** [comment]
Sir am having a issue with installing beef please help  @Auxilus ![Screenshot_2022-02-21-21-45-06-001_com.termux.jpg](https://user-images.githubusercontent.com/95006763/154992683-10b1c09b-244c-4613-bdd9-87fe3a96dd39.jpg)
