### ISSUE TITLE
Fix Origin/Domain terminology

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1688]
BeEF was initially written in 2006, when SOP bypasses were plentiful, when browser plugins (Flash, Silverlight, ActiveX) played by their own rules, and prior to the advent of CORS. To this day, cookies do not strictly obey SOP, although the `samesite` flag is a step in this direction.

The term `cross-domain` was used frequently throughout the codebase, as the difference wasn't important at the time.

---

Update all references to `cross-domain` with `cross-origin`.

Update UI components and associated backend models to represent origins rather than domains, where appropriate. ie, `hooked_origin` (or simply `origin`), rather than `hooked_domain`. Ensure that this is done sensibly, so as to not cause confusion. For example, care should be taken to differentiate between cross-origin requests and cross-origin CORS requests.

**Comment by zinduolis** [comment]
Looking into this.

**Comment by zinduolis** [comment]
Finding and replacing:

- `cross-domain` with `cross-origin`
- `cross_domain` with `cross_origin`

**Comment by zinduolis** [comment]
Hey @bcoles , @stephenakq , please take a look at the above message and let me know if I missed anything. Thanks
