### ISSUE TITLE
Add pagination and sort capabilities to REST API

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1695]
Add pagination and sort capabilities to REST API.

The parameters should match those issued by the AdminUI.

This lack of pagination is an issue in anything but the most contrived of scenarios. Pagination is required to prevent hammering the network when multiple browsers are hooked. The current solution of increasing the UI polling duration is objectively terrible.

**Comment by sudeme** [comment]
mk1044707@gmail.com
