### ISSUE TITLE
beefproject on Ubuntu can't run beef -error

### ISSUE THREAD

**Issue by adelinemartin** [beefproject/beef#1701]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.1).

#### Environment

What version/revision of BeEF are you using? latest version 

On what version of Ruby?

On what browser? Firefox

On what operating system? Ubuntu 

#### Configuration

Are you using a non-default configuration? No

Have you enabled or disabled any BeEF extensions? No

#### Summary

Please provide a summary of the issue.
 I cannot run the beEF project on Ubuntu. the usual ./beef command is not responding and an error message is popping instead:

Traceback (most recent call last):
          1: from ./beef:44:in '<main>'
./beef:47:in 'rescue in <main>: undefined method ' print_error' for main:Object (NoMethodError) 

#### Expected Behaviour

What was the expected result?
once ./beef command is entered it should run the interface and show a link to the hookpage

#### Actual Behaviour

What was the actual result?
error message

#### Steps to Reproduce

Please provide steps to reproduce this issue.
The first thing: install Ruby on my Ubuntu 18.04.2 image:

sudo apt install ruby ruby-dev

The next installed git:

sudo apt install git

clone the git project:

git clone https://github.com/beefproject/beef

.Next, move into the beef directory:

cd beef

On Ubuntu run:

sudo ./install

Once the installation was successfully completed, I ran:

./beef

I was quickly greeted with the following error. To fix this, I tried to tell BeEF that it needs this gem, so I modified the Gemfile file following these steps:

rm Gemfile.lock.  Click Y to remove it.

sudo nano Gemfile

In the file, add the following line:

gem ‘xmlrpc’

Save the file and re-run the installation:

sudo ./install

At this point, the installation should be successful. Try running the following command:

./beef

But another error message popped and I am now stocked:

Traceback (most recent call last):
          1: from ./beef:44:in '<main>'
./beef:47:in 'rescue in <main>: undefined method ' print_error' for main:Object (NoMethodError) 
![error message from git](https://user-images.githubusercontent.com/48265716/53849903-49e0e380-4005-11e9-8594-b5d757373595.PNG)
![error message from git](https://user-images.githubusercontent.com/48265716/53849949-6e3cc000-4005-11e9-9f09-cde5cc82fa68.PNG)

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by bcoles** [comment]
Thanks. I probably introduced this issue in #1699

Can you let me know if this works? Edit `./beef`, and switch these segments:

```ruby
#
# @note Create ~/.beef/                                                                                         
#
begin
  FileUtils.mkdir_p($home_dir) unless File.directory?($home_dir)
rescue => e
  print_error "Could not create '#{$home_dir}': #{e.message}"
  exit 1
end

#
# @note Require core loader's
#
require 'core/loader'
```

So that the `require` comes first, like this:

```ruby
#
# @note Require core loader's
#
require 'core/loader'

#
# @note Create ~/.beef/                                                                                         
#
begin
  FileUtils.mkdir_p($home_dir) unless File.directory?($home_dir)
rescue => e
  print_error "Could not create '#{$home_dir}': #{e.message}"
  exit 1
end
```

**Comment by bcoles** [comment]
(Alternatively, I'll commit a fix to `master` in a few hours)

**Comment by adelinemartin** [comment]
Thank you @bcoles your help was a success, I now have beef running on my Ubuntu.
Have a great day

**Comment by bcoles** [comment]
Fixed in 46d82dc8b8d0a990161512bfc3afdfdc77b46095

**Comment by Molowogan** [comment]
i still cant run beef by editing ./beef

**Comment by Molowogan** [comment]
ALL OF THIS IS NOT IN My edit ./beef
#
# @note Require core loader's
#
require 'core/loader'

#
# @note Create ~/.beef/                                                                                         
#
begin
  FileUtils.mkdir_p($home_dir) unless File.directory?($home_dir)
rescue => e
  print_error "Could not create '#{$home_dir}': #{e.message}"
  exit 1
end

**Comment by bcoles** [comment]
@Molowogan grab the latest versin of BeEF from GitHub.
