### ISSUE TITLE
how can i get android wifi passwords using beef without installing apks ?

### ISSUE THREAD

**Issue by minanagehsalalma** [beefproject/beef#1707]

**Comment by bcoles** [comment]
Wireless passwords are stored in `/data/misc/wifi/wpa_supplicant.conf`.

You'll need code execution within the context of something which can access this file.

**Comment by minanagehsalalma** [comment]
@bcoles  there is two problems the first is this path needs root 
the second one is  i can't find any code execution for this ...

**Comment by bcoles** [comment]
Good luck with your research.

**Comment by minanagehsalalma** [comment]
@bcoles  ok thanks
