### ISSUE TITLE
Beef not working on mobile devices (Android Phones)

### ISSUE THREAD

**Issue by zilect** [beefproject/beef#1709]
#### Environment

What version/revision of BeEF are you using?
0.4.7.0 alpha
On what version of Ruby?
unsure
On what browser?
firefox
On what operating system?
kali

#### Configuration

Are you using a non-default configuration?
just set beef to use my IP and embedded the provided hook to a webpage (which works fine on other pcs)
Have you enabled or disabled any BeEF extensions?
Nope

#### Summary

Please provide a summary of the issue.
I cannot see any Mobile devices SPECIFICALLY Android devices (tried using different browsers within them)
They load the site fine but never register in the beef console as an online browser

#### Expected Behaviour

What was the expected result?
To see the mobile device/browser hooked in the beef console

#### Actual Behaviour

What was the actual result?
nothing displayed, almost as if the hook doesnt execute on mobile

#### Steps to Reproduce

Please provide steps to reproduce this issue.
Sorry not sure what else I could provide here (Also good to note Im fairly new to Beef)

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

ANY information is GREATLY appreciated. I assure you I have no crazy configs setup, as I barely know how to use beef at this point

**Comment by bcoles** [comment]
Hard to know what the issue is here. Also, version `0.4.7.0` is old.

**Comment by zilect** [comment]
Good point, I'll start by updating the client. Sorry my post is shit. Thanks for looking though

On Mar 21, 2019 8:53 PM, bcoles <notifications@github.com> wrote:

Hard to know what the issue is here. Also, version 0.4.7.0 is old.

**Comment by bcoles** [comment]
No worries. I haven't tested on an Android in a while. There could be a bug in the JS, but it's more likely to be something else.

Are you hooking on a HTTPS page?

Try enabling `debug: true` and `client_debug: true` in the `config.yaml`. The former will write logs to `~/.beef/beef.log` and the latter will display some debug info in the browser console.

**Comment by ChillVibesMushroom** [comment]
What was the fix for this do we have to run it via https this is the only thing I’m missing tbh
