### ISSUE TITLE
while running ./beef 

### ISSUE THREAD

**Issue by souviksenapati** [beefproject/beef#1710]
Traceback (most recent call last):
	3: from ./beef:60:in `<main>'
	2: from ./beef:60:in `new'
	1: from /etc/BeEF/core/main/configuration.rb:26:in `initialize'
/etc/BeEF/core/main/configuration.rb:33:in `rescue in initialize': undefined local variable or method `file' for #<BeEF::Core::Configuration:0x0000560e85b8f788> (NameError)

**Comment by bcoles** [comment]
This should be fixed in 355cb385933d1631d46df3828471726cef662d3a.

However, the error occurred inside the error handling. It looks like there was an issue loading the configuration file.
