### ISSUE TITLE
Beef not showing hooked browser but logging them

### ISSUE THREAD

**Issue by Jacquemin1927** [beefproject/beef#1712]
Hello,

I have tried several computers on my network and various browsers, all resulting the same : 

They are listed under the Zombies and Log tabs but not in the hooked browsers one, nor online nor offline.. 

![Capture d’écran de 2019-04-02 14-38-31](https://user-images.githubusercontent.com/20812144/55402990-0cfd0380-5555-11e9-9305-94b8c528413a.png)

**Comment by Jacquemin1927** [comment]
At first I used the default hook pages, then, I created under my /var/www/html folder an index, calling the scripts. The calling works, the script is accessible when showing source page and everything is logged.

**Comment by bcoles** [comment]
Are there any error in the browser console?

You'll have to wait a few seconds (~7 seconds) for the browser tree on the left to update.

**Comment by Jacquemin1927** [comment]
Hello, 
Thanks for your answer. No errors in the "victims" browsers. Under network tab, I can see that the file is called in loops and reached. 
On the server console, there are errors : 
![Capture d’écran de 2019-04-04 08-39-15](https://user-images.githubusercontent.com/20812144/55534948-fb7f3d00-56b5-11e9-8813-5ab4a860665c.png)

**Comment by klezVirus** [comment]
Same problem here, I temporary fixed it by adding the following simple check to web_ui_all.js:
if(!e.country_code){ e.country_code="NOT_FOUND"; }
Hope that helps someone incurring in the same problem, at least till a better solution is found.

**Comment by L7n111** [comment]
where i can find web_ui_all.js

> Hi there, I know it's closed, but I had the same problem and I temporary fixed it by adding the following simple check to web_ui_all.js:
> if(!e.country_code){ e.country_code="NOT_FOUND"; }
> Hope that helps someone incurring in the same problem, at least till a better solution is found.

**Comment by sankalpsingha** [comment]
@klezVirus where did you edit this code exactly? In the minified file? I cant find the location for this for the unminified version. I am getting the same issue. I dont know why this issue has been marked as closed.

**Comment by klezVirus** [comment]
> @klezVirus where did you edit this code exactly? In the minified file? I cant find the location for this for the unminified version. I am getting the same issue. I dont know why this issue has been marked as closed.

Hi mate, well, even my post is from one year ago, more than something has changed in the meantime. However, if the error you're getting is the same, the problem is likely due to be the same, e.country_code is not null checked. The issue is easily solved with the workaround, even if that would be only temporary. The file `web_ui_all.js` is a minified file created when the admin panel is accessed, so anything put there, is temporary. Give me a sec, I'll write a pull request so you can see where the real file should be modified.
