### ISSUE TITLE
admin_ui as extension, question about it

### ISSUE THREAD

**Issue by OscarAkaElvis** [beefproject/beef#1713]
Hi, I'm one of the developers of [airgeddon](https://github.com/v1s1t0r1sh3r3/airgeddon) script which has an already integrated BeEF+Bettercap Evil Twin attack. This was working flawlessly since more than 2 years.

I must admit that I didn't used BeEF from some time ago... but today I did a test and it seems BeEF is not working on the integrated attack. No errors on launching BeEF, but the ui panel is not shown. After some digging I found the problem so my question is not about how to fix it. I saw BeEF was updated on my Linux (tested with same result on Kali and Parrot OS). My BeEF version now is `0.4.7.1-alpha`.

This is because airgeddon generates a custom BeEF config file and it seems that this config file must be modified for new versions. For years this was working but now seems that new version requires new stuff. I added this manually to config file under extensions section, it started to work:

```
admin_ui:
            enable: true
            base_path: "/ui"
```

That was not needed in old version... so, three questions in order to get this full integrated:

 - From which version is this needed? I need to know in order to detect the version to add it to the config file only if needed.
 - Can I add this always for any version? or this could impact to old versions generating errors on launching BeEF? In this way I could avoid the version detection and the customization of the config file based on version
 - If finally the version detection is needed because that admin_ui new statement can't be added always... how is the best choice to detect version in your opinion? Just a grep on config.yaml file?

If you are curious (not needed to answer the questions), you can see here the BeEF config file generated by airgeddon. Is as small as possible removing all the unneeded stuff. It is generated dynamically on each attack and then is removed, ips could change:

```
beef:
    version: 'airgeddon integrated'
    debug: false
    client_debug: false
    crypto_default_value_length: 80
    restrictions:
        permitted_hooking_subnet: "192.168.1.0/24"
        permitted_ui_subnet: "127.0.0.1/32"
    http:
        debug: false
        host: "0.0.0.0"
        port: "3000"
        dns_host: "localhost"
        dns_port: 53
        web_ui_basepath: "/ui"
        hook_file: "/hook.js"
        hook_session_name: "BEEFHOOK"
        session_cookie_name: "BEEFSESSION"
        web_server_imitation:
            enable: true
            type: "apache"
            hook_404: false
            hook_root: false
    database:
        driver: "sqlite"
        db_file: "db/beef.db"
    credentials:
        user: "beef"
        passwd: "airgeddon"
    autorun:
        enable: true
        result_poll_interval: 300
        result_poll_timeout: 5000
        continue_after_timeout: true
    dns_hostname_lookup: false
    integration:
        phishing_frenzy:
            enable: false
    extension:
        requester:
            enable: true
        proxy:
            enable: true
            key: "beef_key.pem"
            cert: "beef_cert.pem"
        metasploit:
            enable: false
        social_engineering:
            enable: true
        evasion:
            enable: false
        console:
            shell:
                enable: false
        ipec:
            enable: true
        dns:
            enable: false
        dns_rebinding:
            enable: false
```

Thanks in advance.

**Comment by bcoles** [comment]
Hey. There's a few things going on here.

> 
> 
> Hi, I'm one of the developers of [airgeddon](https://github.com/v1s1t0r1sh3r3/airgeddon) script which has an already integrated BeEF+Bettercap Evil Twin attack. This was working flawlessly since more than 2 years.

BeEF was updated somewhat regularly, but no releases were released for several years. It's unclear exactly which version you would be using. Complicating matters, distributions package their own version of BeEF.

> 
> I must admit that I didn't used BeEF from some time ago... but today I did a test and it seems BeEF is not working on the integrated attack. No errors on launching BeEF, but the ui panel is not shown. After some digging I found the problem so my question is not about how to fix it. I saw BeEF was updated on my Linux (tested with same result on Kali and Parrot OS). My BeEF version now is `0.4.7.1-alpha`.

Glad you got it working. `0.4.7.1-alpha` may or may not be the latest released version, as all changes to the git repository were performed with this version `0.4.7.1-alpha` still in place. This has since been changed so that bleeding edge versions from the git repo now have a `-pre` suffix, ie `0.4.7.2-alpha-pre`, indicating pre-release status.

> 
> This is because airgeddon generates a custom BeEF config file and it seems that this config file must be modified for new versions.

Fortunately, changes to the config file are rare. Usually, the config file format does not change much between versions, so as to prevent these kinds of issues. The conig file loading could certainly be improved.

> For years this was working but now seems that new version requires new stuff. I added this manually to config file under extensions section, it started to work:
> 
> ```
> admin_ui:
>             enable: true
>             base_path: "/ui"
> ```

There's a couple things going on here. The main `config.yaml` file overwrites the configuration settings in extensions. The `base_path` was "needed" for a long time; however, previously this setting was found in the `extensions/admin_ui/config.yaml` file. It has been moved to the primary configuration file for visibility, as this is an option users will likely want to change to "harden" the system.

In theory, this setting isn't "needed" in the main `config.yaml` file, as BeEF should fall back to using the value in the `extensions/admin_ui/config.yaml` file if it isn't specified.

> 
> That was not needed in old version... so, three questions in order to get this full integrated:
> 
>     * From which version is this needed? I need to know in order to detect the version to add it to the config file only if needed.

The change to `base_path` was implemented in https://github.com/beefproject/beef/commit/9c9119f9cd557c0282753abb39e9bf2282fc9f4f#diff-d21df8ba99b3f4b5728add00978da16a in February 2019.

> 
>     * Can I add this always for any version? or this could impact to old versions generating errors on launching BeEF? In this way I could avoid the version detection and the customization of the config file based on version

It should be safe to add for any version, as the main `config.yaml` overrides extension configuration. It is worth noting that the config setting will have no effect on versions prior to February 2019.

> 
>     * If finally the version detection is needed because that admin_ui new statement can't be added always... how is the best choice to detect version in your opinion? Just a grep on config.yaml file?

The version can be found in the `VERSION` file, and also in the `beef.version` in `config.yaml`. Unfortunately, version matching is somewhat complicated, as per the above.

> 
> 
> If you are curious (not needed to answer the questions), you can see here the BeEF config file generated by airgeddon. Is as small as possible removing all the unneeded stuff. It is generated dynamically on each attack and then is removed, ips could change:
> 
> ```
> beef:
>     version: 'airgeddon integrated'
>     debug: false
>     client_debug: false
>     crypto_default_value_length: 80
>     restrictions:
>         permitted_hooking_subnet: "192.168.1.0/24"
>         permitted_ui_subnet: "127.0.0.1/32"
>     http:
>         debug: false
>         host: "0.0.0.0"
>         port: "3000"
>         dns_host: "localhost"
>         dns_port: 53
>         web_ui_basepath: "/ui"
>         hook_file: "/hook.js"
>         hook_session_name: "BEEFHOOK"
>         session_cookie_name: "BEEFSESSION"
>         web_server_imitation:
>             enable: true
>             type: "apache"
>             hook_404: false
>             hook_root: false
>     database:
>         driver: "sqlite"
>         db_file: "db/beef.db"
>     credentials:
>         user: "beef"
>         passwd: "airgeddon"
>     autorun:
>         enable: true
>         result_poll_interval: 300
>         result_poll_timeout: 5000
>         continue_after_timeout: true
>     dns_hostname_lookup: false
>     integration:
>         phishing_frenzy:
>             enable: false
>     extension:
>         requester:
>             enable: true
>         proxy:
>             enable: true
>             key: "beef_key.pem"
>             cert: "beef_cert.pem"
>         metasploit:
>             enable: false
>         social_engineering:
>             enable: true
>         evasion:
>             enable: false
>         console:
>             shell:
>                 enable: false
>         ipec:
>             enable: true
>         dns:
>             enable: false
>         dns_rebinding:
>             enable: false
> ```
> 
> Thanks in advance.


Fortunately there shouldn't be many changes to the `config.yaml` file. Unfortunately, there's a bug related to `permitted_hooking_subnet` and `permitted_ui_subnet`, which requires a change to the `config.yaml` file, and has been implemented in `0.4.7.2-alpha-pre`.

**Comment by OscarAkaElvis** [comment]
Thanks for the info and the quick response... it seems using a custom config file the admin_ui is needed or it doesn't work. At least on the version I'm testing it. But it is not a problem... and even better if that is something that can be added always to the extensions part of the config file even for older versions... in that case I don't need to check BeEF's version, I'll add it always and it will work for everybody.

The `0.4.7.1-alpha` version I'm using is the last on Kali/Parrot repositories... i try to reproduce the exactly the same that the airgeddon users will face. Hard to know which exact version could be that. As you said, OS repo maintaniers sometimes get latest (of that moment) from your github... to avoid that is complicated. I think that is not happening in airgeddon because our git workflow never interact to master except for a Pull Request passing finished version to master, which means that getting code from master will be the same version always for everybody and once master is updated with a new pull request means another new version. And each new version has a git tag and the referring release from github is pointing to it. Maybe this is easier for us because our project is smaller... but a good git workflow could save a project! 😸 

Closing this... If I have some more doubt I will not hesitate to contact you by this thread if you agree. Thanks again.

**Comment by bcoles** [comment]
> Closing this... If I have some more doubt I will not hesitate to contact you by this thread if you agree. Thanks again.

Any time. I can't guarantee a quick response.

I'll probably drop version `0.4.7.2-alpha` soon, then disappear for a while.

Airgeddon is cool. I haven't used it in a while.

**Comment by bcoles** [comment]
You're probably going to want to take a look at this: https://github.com/beefproject/beef/issues/1319#issuecomment-469063731 - related to `permitted_ui_subnet` and `permitted_hooking_subnet`.

I *think* leaving these values as a string, rather than an array, won't cause any crashes. However, your users will run into the same issues related to IPv6 that required this change to BeEF.

This change will be introduced officially in BeEF `0.4.7.2-alpha`.

**Comment by OscarAkaElvis** [comment]
> Airgeddon is cool. I haven't used it in a while.

Thanks!!! yeah, we try to maintain it but is hard sometimes... a wrapper using so many 3rd party tools is a headache... 3rd tools are changing and we need to support all the changes... is complicated.

Regarding the bracket changes for the permitted_* statements... it seems finally I'll need the version detection in order to set them for that `0.4.7.2-alpha` version. There is no VERSION file for Kali/Parrot package. grep from config.yaml seems the best choice for me. Thanks.

**Comment by OscarAkaElvis** [comment]
Hi @bcoles I pushed a couple of fixes on airgeddon for the needed BeEF config file changes. First this commit which solves the ui access: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/d1819c90c53fb5b00e9a2e01c90178f852e9812d

I tested it on some different versions and it worked.

Then I added a function to get BeEF version from config file: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/2ea540c97e7eb1802fcb9d180ba6ae4983dcd535

And finally I pushed the needed changes (adding brackets) for config file for version 0.4.7.2: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/687c90fb769df646422672e595074c6c43251dc1

I wasn't be able to test this last commit. Can you verify if this looks good to you? because I didn't added the ipv6 stuff... just the brackets. I know, I need to find time to get lastest version from master branch and test this myself, but the author's approval could be nice! 😄 Thanks.

**Comment by OscarAkaElvis** [comment]
Tested on 0.4.7.2 , adding brackets the access to the ui panel is working, no need for ipv6 stuff. But I'm not able to make the js injection with bettercap... no machines are hooked... something with this new version is happening... maybe something more about the config file? I didn't modified anything regarding bettercap (1.6.2 used). On the below image I marked in red what is shown on BeEF's console.

![beef_error](https://user-images.githubusercontent.com/5803348/55652698-97ab6000-57ec-11e9-9c7b-32d6bc12281e.png)

Just changing BeEF version to 0.4.7.1 it works without any modification... any help @bcoles ? Thanks.

**Comment by bcoles** [comment]
The error about browser plugins can be safely ignored. It's irrelevant.

Are you hooking a HTTPS domain, while running BeEF without HTTPS. That won't work.

> Just changing BeEF version to 0.4.7.1 it works without any modification

Are you referring to the 0.4.7.1 release? That was years ago.

**Comment by bcoles** [comment]
> 
> 
> Hi @bcoles I pushed a couple of fixes on airgeddon for the needed BeEF config file changes. First this commit which solves the ui access: [v1s1t0r1sh3r3/airgeddon@d1819c9](https://github.com/v1s1t0r1sh3r3/airgeddon/commit/d1819c90c53fb5b00e9a2e01c90178f852e9812d)
> 
> I tested it on some different versions and it worked.
> 
> Then I added a function to get BeEF version from config file: [v1s1t0r1sh3r3/airgeddon@2ea540c](https://github.com/v1s1t0r1sh3r3/airgeddon/commit/2ea540c97e7eb1802fcb9d180ba6ae4983dcd535)
> 
> And finally I pushed the needed changes (adding brackets) for config file for version 0.4.7.2: [v1s1t0r1sh3r3/airgeddon@687c90f](https://github.com/v1s1t0r1sh3r3/airgeddon/commit/687c90fb769df646422672e595074c6c43251dc1)
> 
> I wasn't be able to test this last commit. Can you verify if this looks good to you? because I didn't added the ipv6 stuff... just the brackets. I know, I need to find time to get lastest version from master branch and test this myself, but the author's approval could be nice! smile Thanks.

Looks reasonable, but you'll need to adjust the `permitted_hooking_subnet` too. It needs to be an array, and it needs to support IPv6.

**Comment by OscarAkaElvis** [comment]
Yeah you were right. After adding the brackets as you said, now everything is working flawlessly. Now airgeddon supportsr 0.4.7.0, 0.4.7.1 and 0.4.7.2 BeEF versions. This is the commit:

https://github.com/v1s1t0r1sh3r3/airgeddon/commit/7707a0b3688dcf255af7a9c6e241f146f9113f7f

By the way... was wondering about to add ipv6 support. I'm not experienced about it. Depending of some circumstances some ip ranges are changing and on my config there are only 4 different possibilities. I need to translate them to ipv6:

0.0.0.0/0
For this is clear to me:
::/0

127.0.0.1/32
This is also clear:
::1/128

192.168.1.0/24
Not sure how to translate this

172.16.250.0/24
Same boat here

Any help? Maybe it doesn't worth the time to add ipv6 support... not sure.

**Comment by bcoles** [comment]
> 
> 192.168.1.0/24
> Not sure how to translate this
> 
> 172.16.250.0/24
> Same boat here

Where did those IP addresses come from? They're IPv4 and cannot be converted to IPv6.

**Comment by OscarAkaElvis** [comment]
That ips are to restrict the permitted_hooking_subnet and it depends of the existing ranges on the interface cards of the attacker (the person who launches airgeddon).

To create an Evil Twin, airgeddon needs to create a fake network with a network range. it creates it as 192.168.1.0/24 by default, but maybe the attacker could already have one interface on that network range. If it is the case, airgeddon changes it to 172.16.250.0/24 to avoid routing problems. That's all.

Maybe a "poor" workaround could be to set it always to 0.0.0.0/0 and ::/0 for ipv6... but is not too much elegant I think.

**Comment by OscarAkaElvis** [comment]
Hi @bcoles , not sure if it could be better idea to open a new github issue or if you prefer any other kind of communication (Discord, IRC or whatever).

I noticed that latest version of BeEF (tested on fully updated Kali and Parrot Security), the file called beef.db is missing. That is causing a problem on the airgeddon integration which is creating its own custom config file. The BeEF version shown in config.yaml is `0.4.7.1-alpha`.

The error shown is this:

![image](https://user-images.githubusercontent.com/5803348/84894849-cc2dd380-b0a1-11ea-9078-be492a78fcea.png)

In my code I used to have this to construct the path to the db file:

```
if [ -d "${beef_path}db" ]; then
	beef_db_path="db/${beef_db}"
else
	beef_db_path="${beef_db}"
fi
```

Some BeEF versions (or maybe some implementations of BeEF on some O.S.) used to have the beef.db file on the root BeEF path or in the db dir. That was enough until now... it seems on this new version there is no beef.db file. I noticed there is a db file called `beef-xss-backup-old-0.4.7.db` on db dir. I tried instead of using `beef.db` as static name as always to try to get the name dynamically... to use any .db file there... but is not working. I mean, even if I put that `beef-xss-backup-old-0.4.7.db` in a fixed way just to test, I'm getting the same error.

Any recommendation about what to do? where is the sqlite file? or can I now to avoid its use? or what happened?

Thanks in advance.

**Comment by OscarAkaElvis** [comment]
I'll add as data, an example of config file generated by airgeddon. Maybe it could help to debug the problem, but I really think is related to the absence of beef.db file:

```
beef:
    version: 'airgeddon integrated'
    debug: false
    client_debug: false
    crypto_default_value_length: 80
    restrictions:
        permitted_hooking_subnet: "192.169.1.0/24"
        permitted_ui_subnet: "127.0.0.1/32"
    http:
        debug: false
        host: "0.0.0.0"
        port: "3000"
        dns_host: "localhost"
        dns_port: 53
        web_ui_basepath: "/ui"
        hook_file: "/hook.js"
        hook_session_name: "BEEFHOOK"
        session_cookie_name: "BEEFSESSION"
        web_server_imitation:
            enable: true
            type: "apache"
            hook_404: false
            hook_root: false
    database:
        driver: "sqlite"
        db_file: "db/beef.db"
    credentials:
        user: "beef"
        passwd: "airgeddon"
    autorun:
        enable: true
        result_poll_interval: 300
        result_poll_timeout: 5000
        continue_after_timeout: true
    dns_hostname_lookup: false
    integration:
        phishing_frenzy:
            enable: false
    extension:
        requester:
            enable: true
        proxy:
            enable: true
            key: "beef_key.pem"
            cert: "beef_cert.pem"
        metasploit:
            enable: false
        social_engineering:
            enable: true
        evasion:
            enable: false
        console:
            shell:
                enable: false
        ipec:
            enable: true
        dns:
            enable: false
        dns_rebinding:
            enable: false
        admin_ui:
            enable: true
            base_path: "/ui"
```

**Comment by bcoles** [comment]
Hi @OscarAkaElvis

The structure of the `config.yaml` looks wrong. It should looks something like this:

```yaml
      database:
          file: "beef.db"
```

However, here's some additional context and ramblings:

I haven't been actively involved with BeEF for a while. The BeEF team doesn't have control over the Kali/Parrot packages - version `0.4.7.1-alpha` is old. Due to the way BeEF is packaged, it's possible that the `config.yaml` file (and the `version` property) weren't updated correctly, either during packaging, or during updatin; ie, "do you want to override existing config file? y/n"

There were some changes to the database a while ago, which were merged into master and released with `0.5.0.0`. These changes were much needed, as the database libraries were ancient, and have now been replaced with activerecord. I wasn't involved in this project. @jcrew99 might be able to help you out here.

> Any recommendation about what to do? where is the sqlite file? or can I now to avoid its use? or what happened?

The stack trace you provided shows the activerecord gem is in use, which doesn't sound right for `0.4.7.1-alpha`.

The short answer is that I'm not entirely sure; however, so long as the `config.yaml` file is in the correct format, you should be able to regenerate the database. You could try `./beef -x` (resets the database and deletes all contents) which should regenerate the database. One of the `rake` tasks might also be able to seed the database.

@jcrew99 can probably offer some guidance here.

To complicate matters, Kali appear to have recently removed Ruby 2.5. While BeEF has been tested on 2.7, I'm not sure what issues this might cause.

**Comment by OscarAkaElvis** [comment]
wow... I put `file` instead of `db_file` and now it is finding the database. Great! thanks. So now I need to know from which version you did the change in order to do the change only for newer versions to maintain retrocmpatibility. I already have a BeEF version detection function to be able to do this kind of changes.

So the first problem is solved. Now a new one appeared. It did some kind of migration the first time (I guess is normal due major changes on db structure). Ok, now BeEF is loading, but I can't login on the web... weird because airgeddon is setting "beef" as user and "airgeddon" as password... and on the config is what is shown... but anyway, can't login using that credentials. I also tried beef/beef. Same result. This is the error shown when I try to login:

![image](https://user-images.githubusercontent.com/5803348/84933551-5abc4800-b0d6-11ea-866c-dcecee76e6c8.png)

Weird because the file has the permitted_ui_subnet: "127.0.0.1/32" so everything looks good... what can be happening now?

**Comment by bcoles** [comment]
> Weird because the file has the permitted_ui_subnet: "127.0.0.1/32" so everything looks good... what can be happening now?

The format of `permitted_ui_subnet` (and `permitted_hooking_subnet`) was changed to an `Array` a while back.

Take a look at the most recent `config.yaml` for formatting:

* https://github.com/beefproject/beef/blob/master/config.yaml

>  So now I need to know from which version you did the change in order to do the change only for newer versions to maintain retrocmpatibility.

It would be best to take a look through the history:

* https://github.com/beefproject/beef/commits/master/config.yaml

Unfortunately, it is not straight forward, as it looks like changes may have been reverted at some point:

* https://github.com/beefproject/beef/commit/06d1ba7754e9f1d525d7de34cfb5c8e4fee5f2d9#diff-259fe82e12a866f01123927480c7851b

Or, alternatively, check the releases:

https://github.com/beefproject/beef/releases

**Comment by OscarAkaElvis** [comment]
Weird... On this same thread, you already told me about the need of the brackets from specific version. And I already implemented it on my code time ago. airgeddon is performing a BeEF version check and adding the new brackets structure if that version or higher is detected:

This is from my code:

![image](https://user-images.githubusercontent.com/5803348/84955529-b945ee00-b0f7-11ea-8e87-30162fa34d9c.png)

The value of `beef_needed_brackets_version` var is `0.4.7.2`. It is a constant defined at the beginning of the program. It is what I understood from what we talked before... and it worked time ago for 0.4.7.0, 0.4.7.1 and 0.4.7.2 were tested when I did that changes.

Analyzing what can be wrong at my development, the answer is "nothing". The version check is ok. It is just that the version shown on this Kali and Parrot BeEF releases is `0.4.7.1-alpha` so they are not higher than the needed version (0.4.7.2) to set the brackets. That is the reason of the error.

I can change that var to set its value to `0.4.7.1` instead of `0.4.7.2`. I hope to not broke anything else on other Linux with old versions... I'm testing it. I changed it manually for the tests and now it works fine. Tested on Kali, Parrot and on an older distro with 0.4.7.0 version. It seems ok in all of them now.

Thanks as always for your support. In this way is easier to keep the compatibility for a better integration.

P.S. I've found a "dirty" way to fix the db not found problem. It seems that on config file we can set both options at the same time (new and old, so "file" and "db_file") and it works. No errors or warnings. Tested on new versions and on old versions. So no version check needed here. Great!

**Comment by bcoles** [comment]
> It is just that the version shown on this Kali and Parrot BeEF releases is `0.4.7.1-alpha`

The version in the config file is wrong for some reason. My guess is that the config file failed to update during a package update, but maybe they're packaging a config file with the wrong version string. :shrug:

**Comment by OscarAkaElvis** [comment]
Yeah, it is supposed that the version is 0.5.0.0, look:

![image](https://user-images.githubusercontent.com/5803348/84986798-714ab980-b13f-11ea-9bf5-218463eeed0e.png)

If I remove it, and then I reinstall it, the version number is ok and everything works fine again... so my guess is that nothing needs to be done regarding version number in airgeddon. I'll undo the commit and I'll commit only the db_file/file fix. Thanks.
