### ISSUE TITLE
Beef Strike can't load in Armitage

### ISSUE THREAD

**Issue by mistermookiefun** [beefproject/beef#1714]
#### Environment

What version/revision of BeEF are you using? I'm using beef_strike in latest cortana-scripts

On what version of Ruby? 2.7.6.2

On what browser? Armitage, Firefox for BeEF

On what operating system? Kali Linux 2019.1

#### Configuration

Are you using a non-default configuration? Yes

Have you enabled or disabled any BeEF extensions? Enabled Armitage extension

#### Summary

When I try to load the script in /root/beef_strike/beef_strike.cna I get this ( pastebin ) : https://pastebin.com/Z51AwHHX

#### Expected Behaviour

Beef_strike to load

#### Actual Behaviour

It doesn't load and I don't understand why

#### Steps to Reproduce

Armitage -> Scripts -> Load -> beef_strike.cna

#### Additional Information

Just tell me what you need, I'll give it to you

**Comment by bcoles** [comment]
I'm not sure what the issue is. `BeefLib.jar` is not part of BeEF, nor is `beef_strike.cna`

You'll need to speak with the Cobalt Strike team.
