### ISSUE TITLE
Beef hook url not working

### ISSUE THREAD

**Issue by xjulixnz21** [beefproject/beef#1719]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.1).

#### Environment

What version/revision of BeEF are you using? 4.7

On what version of Ruby? 2.5.3

On what browser? Firefox

On what operating system? Kali Linux 64 bit

#### Configuration

Are you using a non-default configuration? i'm using default except i enabled debug, but thats all i've done

Have you enabled or disabled any BeEF extensions? i have 12 enabled.

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result? for the hook url to hook to people 

#### Actual Behaviour

What was the actual result? the hook url not hooking

#### Steps to Reproduce

Please provide steps to reproduce this issue.
./beef

#### Additional Information

I'm a bit new to this beef thing so theres most likely something i'm doing wrong also i'm on a vm using vmware workstation 15

![image](https://user-images.githubusercontent.com/50092222/56875673-f5a41f80-6a07-11e9-84c2-d08a6410093a.png)

**Comment by bcoles** [comment]
What happens instead? Does the demo page work on localhost?

**Comment by xjulixnz21** [comment]
> What happens instead? Does the demo page work on localhost?

the demo and the one with my ip works on my vm but not when im outside of the virtual machine or on my phone

**Comment by bcoles** [comment]
> the demo and the one with my ip works on my vm but not when im outside of the virtual machine or on my phone

It's most likely a network routing issue.

**Comment by bcoles** [comment]
If the virtual machine is NATed, then it won't be accessible to the LAN. You'll need to bridge the VM.

**Comment by xjulixnz21** [comment]
> > the demo and the one with my ip works on my vm but not when im outside of the virtual machine 

i bridged it earlier but there was another box under it do i need to check that?
![image](https://user-images.githubusercontent.com/50092222/56875987-cbebf800-6a09-11e9-86bd-784b664e39cc.png)

**Comment by bcoles** [comment]
You'll also need to make sure that the interface updated with an IP address for your LAN. This should have happened automatically via DHCP.

Check the IP in console output. The URL your redacted. Is the IP address correct for your LAN?

Make sure the firewall isn't blocking requests. Check if port `3000` is accessible from other hosts on the LAN.

**Comment by xjulixnz21** [comment]
> Make sure the firewall isn't blocking requests. Check if port `3000` is accessible from other hosts on the LAN.

how do i check this?

**Comment by bcoles** [comment]
> how do i check this?

`curl -isk http://youripaddress:3000/hook.js`

Or open the URL in a web browser.

**Comment by xjulixnz21** [comment]
It was working but now it’s not

**Comment by xjulixnz21** [comment]
my av blocks some stuff idk if this could be the problem tho 
![image](https://user-images.githubusercontent.com/50092222/56926380-53cc1380-6a97-11e9-8ba7-044725058b48.png)

**Comment by bcoles** [comment]
It is unlikely this is an issue with BeEF. You need to configure your network.

Make sure the port is accessible from other hosts on the LAN. That means ensuring that it's on the same subnet and not blocked by the firewall.

**Comment by xjulixnz21** [comment]
could my anti virus be the issue?

**Comment by bcoles** [comment]
Maybe, if your anti-virus software also contains a firewall component. It's been a while since I've seen any AV block BeEF.

The issue is more likely related to your network configuration. Review your network configuration.

Ensure port 3000 on the host running BeEF is accessible from the host you're trying to hook.

**Comment by xjulixnz21** [comment]
My av has a network firewall

**Comment by bcoles** [comment]
Review your network configuration.

Ensure port 3000 on the host running BeEF is accessible from the host you're trying to hook.

**Comment by xjulixnz21** [comment]
yep it was my antivirus, not my network config

**Comment by bcoles** [comment]
> 
> 
> yep it was my antivirus, not my network config

Do you mean your firewall?

**Comment by xjulixnz21** [comment]
yeah I got it to work on my network but i cant get it to work on other networks

**Comment by bcoles** [comment]
> 
> 
> yeah I got it to work on my network but i cant get it to work on other networks

Are they routable? If it's outside your LAN, you'll need to port forward from the border router, or using a tunneling program such as ngrok.

**Comment by xjulixnz21** [comment]
what port do i need to foward to

**Comment by bcoles** [comment]
> 
> 
> what port do i need to foward to

The port which BeEF is listening on. Presumably, that would be port 3000. If you're using web sockets for command and control, you'll need to permit those ports too.

**Comment by xjulixnz21** [comment]
alright thanks

**Comment by xjulixnz21** [comment]
it still only works on my lan. I did the port forwarding thing but it didnt help

**Comment by bcoles** [comment]
You may wish to learn more about port forwarding. Once you have successfully established a network route from outside the LAN to port 3000, review the [FAQ](https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat) to configure BeEF.

**Comment by xjulixnz21** [comment]
i followed the faq and i did what it said and it still only works on my lan

**Comment by bcoles** [comment]
Review your network configuration.

Is port 3000 accessible from outside your LAN? If it is no accessible, your port forwarding is not working.

**Comment by xjulixnz21** [comment]
i downloaded ngrok typed in ngrok http 3000 it gave my my id, i put it in the config and try it on my phone, it doesn't work

**Comment by bcoles** [comment]
Can you access the admin web UI on port 3000?

Are you using IPv6?

Do you get any output in console?

**Comment by xjulixnz21** [comment]
> Can you access the admin web UI on port 3000?
> yes, on my lan
> Are you using IPv6?
> no
> Do you get any output in console?
> idk what you mean if you mean errors then no

**Comment by bcoles** [comment]
There's a bug with IPv6 that was patched a few weeks ago. I'm not sure if it's patched in the BeEF package for Kali.

You can enable debugging by setting `debug: true` in the `config.yaml` file.

Apart from that I can't help you. You cannot route traffic to a port if is not routed.

Try to access the web admin UI from outside your LAN. If you can't access it, then there's something wrong without network configuration.

**Comment by xjulixnz21** [comment]
what do you mean my port is routed
also whats the admin ui

**Comment by bcoles** [comment]
> what do you mean my port is routed

You'll need to port forward or use a tunnel.

> also whats the admin ui

By default: `/ui/panel`

**Comment by xjulixnz21** [comment]
i typed in ngrok http 3000 it gave me my id, i put it in config and it still doesn't work

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by xjulixnz21** [comment]
what port do i use underneath the spot i put my id

**Comment by bcoles** [comment]
> 
> 
> what port do i use underneath the spot i put my id

If you used `ngrok http` you should use:

```yaml
public_port: "80"
```

**Comment by xjulixnz21** [comment]
yeah not working

**Comment by xjulixnz21** [comment]
do i tunnel on the http.public_port?

so it would be ngrok http 80 or not

**Comment by bcoles** [comment]
If you run `ngrok http 3000` then `http.public_port` should be `80`.

You should then be able to access the admin ui with `http://<your ngrok id>.ngrok.io/ui/panel`

**Comment by xjulixnz21** [comment]
the admin ui link works on my lan and on other networks its just the beef url that doesnt work

**Comment by xjulixnz21** [comment]
so do i use the beef hook or the ngrok hook

**Comment by bcoles** [comment]
> 
> 
> the admin ui link works on my lan and on other networks its just the beef url that doesnt work

> 
> 
> so do i use the beef hook or the ngrok hook

If `http://<your ngrok id>.ngrok.io/ui/panel` works to access the admin panel, then use `http://<your ngrok id>.ngrok.io/demos/basic.html` to test the hook.

**Comment by aayushh5419** [comment]
hey ! i have the same issue as @xjulixnz21 i.e my beef panel works totally fine but my beef hook url does not pls help

**Comment by yellowbedsheets** [comment]
same problem with me

**Comment by JustRitesh** [comment]
@bcoles can I get your email ID?
