### ISSUE TITLE
Error in Beef_Strike: Cannot add BeefLib.jar into System

### ISSUE THREAD

**Issue by Developer103** [beefproject/beef#1720]
Error:

Could not load /root/cortana-scripts/beef_strike/beef_strike.cna:

Error: Error, could not add /root/beef_strike/BeefLib.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 13
       import com.eyesopencrew.* from: /root/beef_strike/BeefLib.jar
Error: Error, could not add /root/beef_strike/lib/commons-lang-2.5.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 14
       import org.apache.commons.* from: /root/beef_strike/lib/commons-lang-2.5.jar
Error: Error, could not add /root/beef_strike/lib/commons-logging-1.1.3.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 15
       import org.apache.commons.* from: /root/beef_strike/lib/commons-logging-1.1.3.jar
Error: Error, could not add /root/beef_strike/lib/commons-beanutils-1.8.3.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 16
       import org.apache.commons.* from: /root/beef_strike/lib/commons-beanutils-1.8.3.jar
Error: Error, could not add /root/beef_strike/lib/commons-collections-3.2.1.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 17
       import org.apache.commons.* from: /root/beef_strike/lib/commons-collections-3.2.1.jar
Error: Error, could not add /root/beef_strike/lib/itextpdf-5.5.1.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 18
       import com.itextpdf.text.* from: /root/beef_strike/lib/itextpdf-5.5.1.jar
Error: Error, could not add /root/beef_strike/lib/httpcore-4.3.3.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 19
       import org.apache.http.* from: /root/beef_strike/lib/httpcore-4.3.3.jar
Error: Error, could not add /root/beef_strike/lib/httpclient-4.3.6.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 20
       import org.apache.http.* from: /root/beef_strike/lib/httpclient-4.3.6.jar
Error: Error, could not add /root/beef_strike/lib/json-lib.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 21
       import net.sf.json.* from: /root/beef_strike/lib/json-lib.jar
Error: Error, could not add /root/beef_strike/lib/ezmorph-1.0.6.jar to system classloader - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at line 22
       import net.sf.ezmorph.* from: /root/beef_strike/lib/ezmorph-1.0.6.jar

I do not know what to do, please help me.

**Comment by bcoles** [comment]
I'm not sure what the issue is. `BeefLib.jar` is not part of BeEF, nor is `beef_strike.cna`

You'll need to speak with the Cobalt Strike team.
