### ISSUE TITLE
./install: line 208: bundle: command not found

### ISSUE THREAD

**Issue by DrPhilosophus** [beefproject/beef#1729]
#### Environment

What version/revision of BeEF are you using? Beef 0.4.7.3

On what version of Ruby? ruby 2.6.3-1

On what operating system? Arch linux

#### Summary

Installing beef is exiting with error bundle command not found

#### Expected Behaviour
Installtion of beef should be completed without errors

#### Actual Behaviour
./install: line 208: bundle: command not found

#### Steps to Reproduce
git clone https://github.com/beefproject/beef.git
cd beef
./beef
Install all the packages
./install: line 208: bundle: command not found

#### Additional Information
Also tring to update beef with ./update-beef gives similar error

./update-beef: line 19: bundle: command not found

**Comment by bcoles** [comment]
`gem install bundler`

**Comment by JessW98** [comment]
Hi @DrPhilosophus , did the above suggestion by Bcoles work for you? If you're still having issues please let me know before next week, otherwise I will be closing the ticket. Thank you!
