### ISSUE TITLE
Beef Authentication failure

### ISSUE THREAD

**Issue by demonlive** [beefproject/beef#1730]
What version/revision of BeEF are you using?
.0.4.7.1-Alpha
On what browser?
firefox
On what operating system?
Kali

#### Configuration

Are you using a non-default configuration?
yes
Have you enabled or disabled any BeEF extensions?

no
#### Summary

Please provide a summary of the issue.

I have updated like other posts have recomended as well as followed the lines of code they had used but when i try to log into beef it says authentication error invalid username or password
#### Expected Behaviour

What was the expected result?
to log in 

#### Actual Behaviour

What was the actual result?

did not log in 
#### Steps to Reproduce

Please provide steps to reproduce this issue.

in terminal i cd /usr/share/bee*
then ./beef 
i then take the UI url and open it and try to log in and every time i am denied 
#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by bcoles** [comment]
BeEF version 0.4.7.1-alpha is old. Make sure you're using the latest version (0.4.7.3-alpha).

Make sure you also change the default credentials in `/etc/beef-xss/config.yaml`.

```
root@kali:/usr/share/beef-xss# ./beef -x
[17:21:49][!] ERROR: Don't use default username and password!
[17:21:49]    |_  Change the beef.credentials.passwd in /etc/beef-xss/config.yaml
```
