### ISSUE TITLE
Cant login Beef Authentication failure

### ISSUE THREAD

**Issue by alienwaresoldier** [beefproject/beef#1732]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.2).Yes

#### Environment

What version/revision of BeEF are you using?
.0.4.7.1-Alpha

On what browser?
Firefox
On what operating system?
Parros os

#### Configuration

Are you using a non-default configuration?
yes
Have you enabled or disabled any BeEF extensions?
no

#### Summary

Please provide a summary of the issue.
Cant login after parrot os update.

#### Expected Behaviour

What was the expected result?
Login

#### Actual Behaviour
Cant login

What was the actual result?

Cant login
#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information
SAME PROBLEM LIKE SOME OTHERS CANT LOGIN 

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by bcoles** [comment]
Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `beef.debug: true` and `beef.http.debug` in the `config.yaml` configuration file. The debug log can be found in the `~/.beef/` directory.

**Comment by alienwaresoldier** [comment]
> 
> 
> Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `beef.debug: true` and `beef.http.debug` in the `config.yaml` configuration file. The debug log can be found in the `~/.beef/` directory.

I have reinstalled my Parrot OS, so its working again.
