### ISSUE TITLE
[Question]BeEF loses connection to online browser.

### ISSUE THREAD

**Issue by samd10** [beefproject/beef#1733]
I am new to BeEF.I was testing its different commands.But i found that when i use the redirect command then BeEF redirect the hooked webpage to the specified website.But as soon as BeEF does that it loses connection with the hooked browser.Is it a bug?or BeEF could only provide us connection as long as the hooked webpage remain online.Thanks in advance!

**Comment by bcoles** [comment]
The BeEF hook is client-side JavaScript. If none of the open browser tabs contain the BeEF hook, then the BeEF hook code will not execute, and there will be no connection to the BeEF server.

There are some [persistence modules](https://github.com/beefproject/beef/tree/master/modules/persistence) for persistence. Your mileage may vary.

**Comment by samd10** [comment]
So that's it.But I was watching a udemy course on hacking in which BeEF did'nt lose connection even after the redirect command.Why?
I just wanna ask one more question that "If I execute any command from BeEF like a direct html.Will it execute on the hooked browser on any webpage the target person is using or only on the hooked webpage?"

**Comment by bcoles** [comment]
> So that's it.But I was watching a udemy course on hacking in which BeEF did'nt lose connection even after the redirect command.Why?

Perhaps they redirected to a page which contained a BeEF hook.

Perhaps they had another tab open which contained a BeEF hook.

> I just wanna ask one more question that "If I execute any command from BeEF like a direct html.Will it execute on the hooked browser on any webpage the target person is using or only on the hooked webpage?"

Web browsers have a concept of "origin". Code can be executed only on the same origin due to the [Same-Origin Policy (SOP)](https://en.wikipedia.org/wiki/Same-origin_policy). There are multiple methods to bypass SOP, the most common being [Cross-Site Scripting](https://en.wikipedia.org/wiki/Cross-site_scripting) and [Cross-Origin Resource Sharing (CORS)](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
).

**Comment by samd10** [comment]
One last question.Is there a practical way to make beef hooked to the target browser even if the target user closes the hooked webpage.
[Thanks for your time]

**Comment by bcoles** [comment]
> Is there a practical way to make beef hooked to the target browser even if the target user closes the hooked webpage.

There are some [persistence modules](https://github.com/beefproject/beef/tree/master/modules/persistence) for persistence.

In particular, the [Man-In-The-Browser](https://github.com/beefproject/beef/tree/master/modules/persistence/man_in_the_browser), [Invisible HTMLFile (ActiveX)](https://github.com/beefproject/beef/tree/master/modules/persistence/invisible_htmlfile_activex), and [Create Foreground iFrame](https://github.com/beefproject/beef/tree/master/modules/persistence/iframe_above) modules use various techniques to maintain a hook, even if the browser tab navigates to a different origin.

However, none of these methods will survive closing the tab, and your mileage may vary.
