### ISSUE TITLE
beEF not working. Hook also not working.

### ISSUE THREAD

**Issue by thecowmilk** [beefproject/beef#1737]
Hello @bcoles I have an issue with beEF. When I installed kali on my VMware Machine and run BeEF for the first time it worked perfectly. I could hook any website I wanted. After a while (I guess 1 month) I launched beEF and on the terminal and it showed me this:
[-] You are using the Default credentials
[-] (Password must be different from "beef")

I went to config file and changed the username and password and when I opened beEF the hook was not working. On the control panel was nothing to show. I made a couple of reloads but it did not worked.

In my terminal showed me this:
beef-xss.service - beef-xss
   Loaded: loaded (/lib/systemd/system/beef-xss.service; disabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-06-02 12:50:12 CDT; 5s ago
 Main PID: 2876 (ruby)
    Tasks: 4 (limit: 5749)
   Memory: 124.8M
   CGroup: /system.slice/beef-xss.service
           └─2876 ruby /usr/share/beef-xss/beef

It was the first time beEF loaded in this way on my terminal because it usually loads only with the "Web UI", "Hook script" and "Hook example". A week ago, in my terminal was a line: "Something is already running on port '3000' ", so I listed the processes in the port 3000 and there was 2 beEF processes running, one was "ESTABLISHED" and the other was "LISTENING" I killed the listening process and I kept the ESTABLISHED one and still not any progress on it.

Another I do have even this issue. I have started apache2 server and this happens when I type my IP address.
![61977807_448658145699621_2428916147484098560_n](https://user-images.githubusercontent.com/43875051/58797845-a2a12780-85c6-11e9-9959-172892837749.png)

Many Thanks In Advance

**Comment by bcoles** [comment]
>  I opened beEF the hook was not working. On the control panel was nothing to show.

What does this mean?

> It was the first time beEF loaded in this way on my terminal because it usually loads only with the "Web UI", "Hook script" and "Hook example". A week ago, in my terminal was a line: "Something is already running on port '3000' ", so I listed the processes in the port 3000 and there was 2 beEF processes running, one was "ESTABLISHED" and the other was "LISTENING" I killed the listening process and I kept the ESTABLISHED one and still not any progress on it.

Kill everything on port 3000 and restart the `beef-xss` service.

> I have started apache2 server and this happens when I type my IP address.

The default web root for apache on Kali is `/var/www/html/`

**Comment by thecowmilk** [comment]
As for the first question:
- After beef required a new username and password, I went to config.yaml file and changed them. I opened beef again, I putted my IP address on another browser, I went to beef control panel and under the folder "Online browsers", it was not showing my hooked browser. I thought browser were updated (I tested this on Mozilla, Google and Internet Explorer) so I downloaded an outdated Mozilla version, I putted my IP address on it and the hook was not working.

**Comment by thecowmilk** [comment]
As for the second question:
- I killed every process on port 3000, restarted the beef-xss service and 3 processes are still there.... That is my output:

ruby      2589 beef-xss    9u  IPv4  59642      0t0  TCP localhost:3000->localhost:60010 (ESTABLISHED)
ruby      2589 beef-xss   16u  IPv4  52994      0t0  TCP *:3000 (LISTEN)
firefox-e 2611     root   86u  IPv4  60450      0t0  TCP localhost:60010->localhost:3000 (ESTABLISHED

**Comment by thecowmilk** [comment]
As for the third question:
- I know, there is where my html file is located, but why it shows me that?

**Comment by bcoles** [comment]
> 
> 
> As for the third question:
> 
>     * I know, there is where my html file is located, but why it shows me that?

You can learn more about Directory Indexing here:

* https://www.cyberciti.biz/faq/enabling-apache-file-directory-indexing/
* https://cwiki.apache.org/confluence/display/HTTPD/DirectoryListings

**Comment by bcoles** [comment]
> 
> 
> As for the first question:
> 
>     * After beef required a new username and password, I went to config.yaml file and changed them. I opened beef again, I putted my IP address on another browser, I went to beef control panel and under the folder "Online browsers", it was not showing my hooked browser. I thought browser were updated (I tested this on Mozilla, Google and Internet Explorer) so I downloaded an outdated Mozilla version, I putted my IP address on it and the hook was not working.

Try using the demo page to hook a browser.

**Comment by thecowmilk** [comment]
> > As for the first question:
> > ```
> > * After beef required a new username and password, I went to config.yaml file and changed them. I opened beef again, I putted my IP address on another browser, I went to beef control panel and under the folder "Online browsers", it was not showing my hooked browser. I thought browser were updated (I tested this on Mozilla, Google and Internet Explorer) so I downloaded an outdated Mozilla version, I putted my IP address on it and the hook was not working.
> > ```
> 
> Try using the demo page to hook a browser.

Well honestly I don't know how to do that....

**Comment by bcoles** [comment]
The links to the demo page are on the `Getting Started` tab when you log in to the BeEF web interface.
