### ISSUE TITLE
I'm sure this is more something I'm doing wrong

### ISSUE THREAD

**Issue by sin3141** [beefproject/beef#1748]
I was actually able to start the framework this time, but it still gave me these errors. I also can't for whatever reason get my hook.js to work not when I click it nor consenting test subjects

[ 1:13:55][*] Bind socket [imapeudora1] listening on [0.0.0.0:2000].
[ 1:13:55][!] Event Logger extension is not compatible with WebSockets command and control channel
[ 1:13:57][*] Connecting to Metasploit on 127.0.0.1:55552
[ 1:13:57][!] [Metasploit] RPC call to 'auth.login' failed: Failed to open TCP connection to 127.0.0.1:55552 (Connection refused - connect(2) for "127.0.0.1" port 55552)
[ 1:13:57][!] API Fire Error: no implicit conversion of Array into String in {:owner=>BeEF::Extension::Metasploit::API::MetasploitHooks, :id=>11}.post_soft_load()
[ 1:13:57][*] BeEF is loading. Wait a few seconds...
[ 1:14:11][!] Warning: Default SSL cert/key in use.

**Comment by bcoles** [comment]
> I was actually able to start the framework this time, but it still gave me these errors. I also can't for whatever reason get my hook.js to work not when I click it nor consenting test subjects

In this instance, the Metasploit extension failed to cause to the Metasploit RPC server. Try disabling the Metasploit extension.

It also looks like you're using HTTPS, with the default certificate, which is going to cause issues if the target browsers do no trust your SSL certificate.

By the looks of things, you've turned on all the options. I strongly suggest starting with the default configuration, and ensuring that works, before randomly flipping switches.

**Comment by sin3141** [comment]
I enabled everything that sounded like it could be useful to me. If I uninstall and then reinstall, starting with the default configuraton, do I still have to changethe config.yaml files in the extension module to match? They usually all say false while in the main config.yaml everything except metasploit will be enabled. Also will that help my issue with using the hook?

**Comment by bcoles** [comment]
There's no need to uninstall, simply set the configuration options in the [config.yaml](https://github.com/beefproject/beef/blob/master/config.yaml) file back to the default. Specifically, disable the `evasion` and `metasploit` extensions. Also, disable any autorun rules you may have enabled. You should probably also disable HTTPS until you have a known-good working configuration.

There are some bugs with the `evasion` module, and it looks like there's also some bugs with the Metasploit integration in the `metasploit` integration. There were some changes to the msfrpc gem a while ago, which the `metasploit` extension uses, so the extension may need to be updated.

**Comment by sin3141** [comment]
I'll give it a try. Thank you! I'll be back with the results. This has been one of my favorite tools to play around with since I discovered it a couple of months ago, but I still got a lot of learning it to do.
