### ISSUE TITLE
why not 4 Windows 

### ISSUE THREAD

**Issue by n82freak** [beefproject/beef#1758]
Hey Dudes... 
I understand that the most special tools working good with Linux but i think that all this tools can work in Windows too... 
In Windows can do a lot of things with dos-console, powershell, vbscript, Java, Python, etc. etc.and i believe that we can do the same allmighty things through the combination of those called scripting languages... and Athen the last it should be possible to realize a lot of linuxpreferred tools with .net code... 
So i ask if you can realize windowsbased version of beef !.

Thx a lot 4 read my question...

**Comment by bcoles** [comment]
You can probably get BeEF running on Windows. However, [Windows is not a supported platform](https://github.com/beefproject/beef/wiki/Installation):

> In theory, BeEF should work on any operating system which can run Ruby 2.3+ and nodejs. However, only MacOS and Linux are officially supported.

The maintenance overhead for Windows is too high, and the potential user base is too small.

If you're interesting in trying to get BeEF running on Windows, this [guide](https://github.com/beefproject/beef/issues/932#issuecomment-69188364) gives instructions for configuring BeEF for Heroku on Win XP SP3, which might help. It gives instructions for using PostgreSQL rather then SQLite. It is also out of date, and I wouldn't recommend it.
