### ISSUE TITLE
A small problem

### ISSUE THREAD

**Issue by loool0987** [beefproject/beef#1759]
I can't open this website:

![Capture](https://user-images.githubusercontent.com/54402802/63513686-8dfe6c80-c4ef-11e9-804f-a9c11631b444.JPG)

**Comment by bcoles** [comment]
The Live CD has not been updated for about 7-8 years and is not currently maintained or supported.

**Comment by ru-faraon** [comment]
http://downloads.beefproject.com/BeEFLive1.4.iso
