### ISSUE TITLE
js hook not working

### ISSUE THREAD

**Issue by sercanyilmaz84** [beefproject/beef#1760]
I couldnt run beef which default in kali linux. ı downloaded again. now ı am trying js inject with man in the middle, bettercap and other tools. But its not working. Even ı have tried on my browser but didnt work.

**Comment by bcoles** [comment]
Have you tried hooking using the default demo page?

Do you receive any errors in console?

**Comment by sercanyilmaz84** [comment]
> Have you tried hooking using the default demo page?
> 
> Do you receive any errors in console?

Yes ı have tried. But i didnt recieve any error. Because of that ı cant find where is the problem. For example mitmf or bettercap working very well. But when i try to inject beef js hook, nothing. No error, no any behavior.

**Comment by bcoles** [comment]
Are you using a non-default configuration for BeEF?

Try running BeEF without all the other tools, and see if the hook page works by using the demo page.

**Comment by sercanyilmaz84** [comment]
I tried without all other tools :( still same

**Comment by bcoles** [comment]
Are you using the latest version of BeEF?

Enable `debug: true` and `beef.http.debug: true` in the `config.yaml` configuration file. Is there any output in console? Are there are any errors in `~/.beef/beef.log` ?

**Comment by sercanyilmaz84** [comment]
Yes, now ı have changed these things in  config.yaml file. Beef started without any error. And ı am trying js hook in demo page and also with mitmf js inject. Still same. I am using latest version of Beef

**Comment by bcoles** [comment]
Try running BeEF without all the other tools, and see if the hook page works by using the demo page.

Are there any errors in the browser console? Are errors in your terminal? Are there errors in the log file?

**Comment by sercanyilmaz84** [comment]
I tried without other tools and with other tools. Results didnt change. There is no any error in terminal or log file.

**Comment by JessW98** [comment]
Hi @sercanyilmaz84 , are you still having troubles with this?

**Comment by jcrew99** [comment]
@sercanyilmaz84  Are you still having this issue? Do you mind filling out the issue template found: https://github.com/beefproject/beef/blob/master/.github/ISSUE_TEMPLATE.md
Would you also be able to provide screenshots of the terminal and log file with no errors, and of the UI that has the hook not working on the demo page?
I will close this issue after a while if no response

**Comment by jcrew99** [comment]
I am closing due to No response
