### ISSUE TITLE
Flagged By Google Safe Browsing for malware

### ISSUE THREAD

**Issue by edwardgalligan** [beefproject/beef#1775]
This Github repo has been flagged by Google for containing malware, preventing browsers (with this protection enabled) from visiting it https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fgithub.com%2Fbeefproject%2Fbeef

<img width="1177" alt="Screenshot 2019-09-26 at 11 45 16" src="https://user-images.githubusercontent.com/170268/65682614-cba06900-e04a-11e9-9283-332a5023df30.png">

**Comment by jcrew99** [comment]
We have tried contacting Google, but they need us to prove that we own it(which we can't since we don't own Github) and github have said they are unable to influence google from their end.

**Comment by ekampp** [comment]
This is the digital version of swatting.

**Comment by jcrew99** [comment]
This has been removed so i am closing this ticket
