### ISSUE TITLE
bundle install failed on curb install

### ISSUE THREAD

**Issue by RJColeman** [beefproject/beef#1778]
Trying to install https://github.com/beefproject/beef/releases/tag/beef-0.4.7.2
Using ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
On Fedora 30 (kernel 5.2.15-200.fc30.x86_64)

Couldn't install.  Got this error from commandline after running bundler install:

    An error occurred while installing curb (0.9.10), and Bundler cannot continue.
    Make sure that `gem install curb -v '0.9.10' --source 'https://rubygems.org/'` succeeds before bundling.

Two issues with installing:

1. compiler couldn't find libcurl.so. Error reported in /usr/lib64/gems/ruby/curb-0.9.10/mkmf.log:

    `/bin/ld: cannot find -lcurl`

    SOLUTION: 

    Find libcurl.so.* (I used locate libcurl)
    Create symlink from path to found libcurl.so.* from /path/to/libcurl.so like so: 

    `sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl.so`
    `sudo ldconfig`

2. compiler couldn't fine curl/curl.h which is included in one of the c files necessary to compile curb for beef

    Gemfile says:

        # curb gem requires curl libraries
        # sudo apt-get install libcurl4-openssl-dev

    which is outdated.  
    
    SOLUTION:

        `sudo yum install libcurl-devel.x86_64`

**Comment by stratigos** [comment]
@RJColeman ty for the solution to symlink `libcurl.so` :+1: 

The solution for missing `curl.h` is for a RedHat package system. For anyone using Ubuntu, the following worked for me:

> sudo apt-get install libcurl4-gnutls-dev

...there is also the `libcurl4-openssl-dev` variant as well, as Ubuntu has a few different packages for different curl strategies.

**Comment by jcrew99** [comment]
@RJColeman  This seems resolved for now, do you think there is value trying to add this to the setup, depending on the distro? 
Otherwise it may be able to close this ticket as it seems env dependant.

**Comment by RJColeman** [comment]
I did a fresh install of fedora 31 and then beef and had a ton of failed dependencies I had to resolve, but this issue was handled, yup.

**Comment by harshyadavjiii** [comment]
What to say about this man installing beef on red hat based systems is real pain firstly bundle was throwing errors for nio4r 2.5.4 and say what people using Ubuntu get quick solution for this by installing libgmp-dev package but it was not installing on fedora again throwing bunch of errors dnf and yum package managers were not able to even find it and manual installation was also flop then I reinstalled ruby with rvm and removed the previous one and again this shit I hope your solution will work Thanks dude

**Comment by bcoles** [comment]
> 
> 
> What to say about this man installing beef on red hat based systems is real pain firstly bundle was throwing errors for nio4r 2.5.4 and say what people using Ubuntu get quick solution for this by installing libgmp-dev package but it was not installing on fedora again throwing bunch of errors dnf and yum package managers were not able to even find it and manual installation was also flop then I reinstalled ruby with rvm and removed the previous one and again this shit I hope your solution will work Thanks dude

Debian/Ubuntu based systems use a different naming convention for packages to the Fedora/CentOS/RHEL family.

`libgmp-dev` is probably something like `libgmp-devel` on RHEL.

If you paste the output of the `bundle install` command then maybe we can offer further assistance.
