### ISSUE TITLE
@Auxilus i am getting error while installing therubyracer (0.12.3) in termux

### ISSUE THREAD

**Issue by jsn-OO7** [beefproject/beef#1780]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.2).

#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?

On what browser?

On what operating system?

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by Moron-bit** [comment]
here is what i did .

1st. i would recommend to install unstable-repo + metasploit-framework + node js + python/python2.

2nd. cloning beef.

3rd. edit the config.yaml to install the correct versions like @Auxilus suggested + delete the "rubyracer" line from config.yaml

4th. run "bundle install" if it asks for additional gems, just install them by specifying the gem version required, something like this: "gem install sinatra -v 2.0".

5th. run "./beef" if you get a "traceback error" try this: 
https://github.com/rapid7/metasploit-framework/issues/11492#issuecomment-468285757

this is working for me on galaxy s7, credit to @Auxilus, and i guess for other users on git :]

sorry if i didnt write a respose correctly, its my first one :]

i hope this will help you :]

**Comment by Moron-bit** [comment]
change:

gem 'rubydns', '~> 0.7.3'

to:

gem 'rubydns', '~> 2.0.2'

and only if its needed 

change:

gem 'eventmachine'

to:

gem 'eventmachine', '~> 1.2.7'

thats it :]

**Comment by Moron-bit** [comment]
@jsn-OO7 i think, its kinda rude not to say thx after someone have helped you

i think, not sure, other people wont be so glad to help you if you keep behaving like that

good day.

 cheers :]

**Comment by Auxilus** [comment]
@Moron-bit, dude joined github 18 days ago, don't take it personally 😅

**Comment by jsn-OO7** [comment]
O thx very much.Can u just give ur WhatsApp or something like that

**Comment by Moron-bit** [comment]
not using whatsapp you can contact me on my gmail account:

moronsxclubsv1.0@gmail.com.

it might take me some time to answer though :/

**Comment by jcrew99** [comment]
therubyracer is no longer a gem required by beef, it has been removed so it should no longer be an issue @jsn-OO7  let us know if there are any further issues.

**Comment by Auxilus** [comment]
I feel really bad, I didn't literally nothing more than clone the repo and editing gemfile, I'm not even familiar with the beef code 😅
