### ISSUE TITLE
core/main/client/net.js should use public_host / public_port

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1785]
The `host` and `port` properties in `core/main/client/net.js` should make use of the appropriate `public_host` and `public_port` properties, if available. A `public_proto` option should probably also be added to the config file, then added here too.

```javascript
    host: "<%= @beef_host %>",
    port: "<%= @beef_port %>",
    hook: "<%= @beef_hook %>",
    httpproto: "<%= @beef_proto %>",
    handler: '/dh',
    chop: 500,
    pad: 30, //this is the amount of padding for extra params such as pc, pid and sid
    sid_count: 0,
    cmd_queue: [],
```

**Comment by bcoles** [comment]
This is kind of important, as this bug prevents BeEF from hooking when the BeEF hook URL is different form the BeEF host URL (ie, behind a reverse proxy, or when used via services such as ngrok, or when using port forwarding from a border gateway).

The entire `public_` prefix implementation for differentiating between public network and internal network configuration also needs to be addressed. Ideally, the public variant should automatically take on the values used for the internal BeEF host IP address, port, and URL scheme by default, unless the user has specifically configured a public variant.

Then, every attempt to retrieve the hook URL within the code base can safely use the public variant, without having to copypasta the same `if public_host then do this else just use the host` code that appears everywhere.

The network host:port to which BeEF binds, and the network host:port to which zombies connect, should be fully decoupled.

This still won't allow for specifying multiple public host:port combinations, which is a foreseeable use case, but that's a whole other kettle of fish.

The whole differentiation between public and private was slapped on without much thought and was never implemented properly. It's got the project this far, which is good, but it hasn't aged well. A disproportionately huge number of bugs filed to the issue tracker are due to issues with trying to access BeEF on a host within an internal network from outside the network. In a lot of cases, this is due to users misunderstanding the basic fundamentals of reality, but there are legitimate bugs here too.

**Comment by jcrew99** [comment]
@bcoles  This is interesting, especially how it will reduce the length of code used to describe the calls for the hook. Apologies if its a question that should seem obvious but would you be able to describe the steps that will need to be taken in more detail? I would like to start working on this if possible since its very important but its currently out of my depth with my current understanding.

**Comment by wheatley** [comment]
@bcoles what's the status of this issue, was thinking about diving in.

**Comment by bcoles** [comment]
> 
> 
> @bcoles what's the status of this issue, was thinking about diving in.

status: it's complicated

There's a band-aid patch here #2060 which partially fixes part of the problem, incorrectly.

**Comment by wheatley** [comment]
@bcoles it seems complicated, have been look into to a bit today.
have you seen a hooked browser with reverse proxy specifically with ngrok?

**Comment by bcoles** [comment]
> have you seen a hooked browser with tunnelling specifically with ngrok?

I don't know what that means. I've successfully hooked a browser using ngrok (http not https).

**Comment by wheatley** [comment]
okay that's good, just need that confirmation as the hooks aren't working for me over http

**Comment by bcoles** [comment]
> @bcoles Is it worth trying to merge #2060, or leave it as is and try to solve the issue properly correctly first?

Sure! If you're committed to continuing work on this issue.

If someone wants to take ownership of this issue, reviewing whether #2060 makes sense is as good a place to start as any.

**Comment by jcrew99** [comment]
I'm currently looking at #2093 but can grab it after, that is, unless @wheatley  wants to take ownership of it :p

**Comment by wheatley** [comment]
I'm happy taking this on, it's causing a lot of issues so resolving it would be a good win for the project

**Comment by wheatley** [comment]
okay weird thing today.
loaded up a new vm (bridged) and pulled the latest code base
setup https enabled, internal set to localhost, set public pto the ngrok host and public port to 443
started ngrok to point to https://localhost:3000 
was able to hook browsers

I haven't been able to test everything but thought I'd give you both an update

**Comment by wheatley** [comment]
This should now be resolved.
