### ISSUE TITLE
how to set up public ip here?

### ISSUE THREAD

**Issue by azamet90** [beefproject/beef#1788]
this is my config.yaml but not looks like same like those people here have?

`---
beef:
  version: 0.4.7.3-alpha
  debug: false
  client_debug: false
  crypto_default_value_length: 80
  credentials:
    user: beef
    passwd: Deneme123..1..1
  restrictions:
    permitted_hooking_subnet:
    - 0.0.0.0/0
    - "::/0"
    permitted_ui_subnet:
    - 0.0.0.0/0
    - "::/0"
    api_attempt_delay: '0.05'
  http:
    debug: false
    host: 0.0.0.0
    port: '3000'
    xhr_poll_timeout: 1000
    hook_file: "/hook.js"
    hook_session_name: BEEFHOOK
    restful_api:
      allow_cors: false
      cors_allowed_domains: http://browserhacker.com
    websocket:
      enable: false
      port: 61985
      secure: true
      secure_port: 61986
      ws_poll_timeout: 1000
      ws_connect_timeout: 500
    web_server_imitation:
      enable: true
      type: apache
      hook_404: false
      hook_root: false
    https:
      enable: false
      key: beef_key.pem
      cert: beef_cert.pem
  database:
    driver: sqlite
    db_file: db/beef.db
    db_host: localhost
    db_port: 3306
    db_name: beef
    db_user: beef
    db_passwd: beef
    db_encoding: UTF-8
  autorun:
    result_poll_interval: 300
    result_poll_timeout: 5000
    continue_after_timeout: true
  dns_hostname_lookup: false
  geoip:
    enable: true
    database: "/var/lib/GeoIP/GeoLite2-City.mmdb"
  integration:
    phishing_frenzy:
      enable: false
  extension:
    admin_ui:
      enable: true
      base_path: "/ui"
    demos:
      enable: true
    events:
      enable: true
    evasion:
      enable: false
    requester:
      enable: true
    proxy:
      enable: true
    network:
      enable: true
    metasploit:
      enable: false
    social_engineering:
      enable: true
    xssrays:
      enable: true`

**Comment by bcoles** [comment]
Set `beef.http.public` and `beef.http.public_port`

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

**Comment by azamet90** [comment]
> Set `beef.http.public` and `beef.http.public_port`
> 
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

![image](https://user-images.githubusercontent.com/44042178/69427015-87d79080-0d69-11ea-85a6-ca4ec334a870.png)
there is nothing to found with beef.http.public on config.yaml ?

**Comment by bcoles** [comment]
> there is nothing to found with beef.http.public on config.yaml ?

Strange that it's missing - it's included by default. Also, your version of BeEF is out of date. You should update.

**Comment by azamet90** [comment]
> > there is nothing to found with beef.http.public on config.yaml ?
> 
> Strange that it's missing - it's included by default. Also, your version of BeEF is out of date. You should update.

![image](https://user-images.githubusercontent.com/44042178/69429423-7775e480-0d6e-11ea-9738-84f157ddbd11.png)
at the right top of this window it shows the version and on your releases page is the same version which is the latest or not? it was preinstalled on kali and i did apt-get upgrade too :/

**Comment by bcoles** [comment]
Oh yeah, my bad. [BeEF 0.4.7.3 is the latest release](https://github.com/beefproject/beef/releases).

**Comment by azamet90** [comment]
> Oh yeah, my bad. [BeEF 0.4.7.3 is the latest release](https://github.com/beefproject/beef/releases).

yeah but how to do it now :D

**Comment by bcoles** [comment]
> yeah but how to do it now :D

Set `beef.http.public` and `beef.http.public_port`

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

**Comment by azamet90** [comment]
> > yeah but how to do it now :D
> 
> Set `beef.http.public` and `beef.http.public_port`
> 
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

![image](https://user-images.githubusercontent.com/44042178/69430871-7e522680-0d71-11ea-8c97-d230a783b707.png)
this we talk before i think huh? :D

**Comment by bcoles** [comment]
> this we talk before i think huh? :D

You can use you favorite input device, in combination with your favorite text editor, to insert text into the configuration file. You may also wish to refer to the [default configuration file](https://github.com/beefproject/beef/blob/master/config.yaml) as an example.

**Comment by azamet90** [comment]
> > this we talk before i think huh? :D
> 
> You can use you favorite input device, in combination with your favorite text editor, to insert text into the configuration file. You may also wish to refer to the [default configuration file](https://github.com/beefproject/beef/blob/master/config.yaml) as an example.

thank you for answers the last thing is you have to know i think this:
![image](https://user-images.githubusercontent.com/44042178/69431632-156bae00-0d73-11ea-897c-211d3d08cacc.png)
this happens only if i visit your source code

**Comment by bcoles** [comment]
Yeah, there was a failed attempt to fix that. :shrug:

**Comment by azamet90** [comment]
> Yeah, there was a failed attempt to fix that. :shrug:

really last question i need to ask you: the target also must stay only on that ip domain everytime? cannot go to google.com for example? will the attack drop on changing the url?

**Comment by bcoles** [comment]
> 
> 
> > Yeah, there was a failed attempt to fix that. :shrug:
> 
> really last question i need to ask you: the target also must stay only on that ip domain everytime? cannot go to google.com for example? will the attack drop on changing the url?

The BeEF hook is written in JavaScript and executes within the browser, in the context of the hooked origin, within a `window`. There are many reasons the hook could stop executing. The most likely, is that the `window` has navigated to a different `location`.

You may wish to look at some of the [persistence modules](https://github.com/beefproject/beef/tree/master/modules/persistence).

**Comment by azamet90** [comment]
> > > Yeah, there was a failed attempt to fix that. :shrug:
> > 
> > 
> > really last question i need to ask you: the target also must stay only on that ip domain everytime? cannot go to google.com for example? will the attack drop on changing the url?
> 
> The BeEF hook is written in JavaScript and executes within the browser, in the context of the hooked origin, within a `window`. There are many reasons the hook could stop executing. The most likely, is that the `window` has navigated to a different `location`.
> 
> You may wish to look at some of the [persistence modules](https://github.com/beefproject/beef/tree/master/modules/persistence).

sorry for my bad english i think you did not understand my question look at this gif image to understand what i mean with my question:
x-special/nautilus-clipboard
copy
![Peek 2019-11-23 00-26](https://user-images.githubusercontent.com/44042178/69443407-45be4700-0d89-11ea-8df8-679d1bc9528e.gif)

**Comment by bcoles** [comment]
> the target also must stay only on that ip

The short answer is yes.

However, you may wish to look at some of the [persistence modules](https://github.com/beefproject/beef/tree/master/modules/persistence).

**Comment by Moron-bit** [comment]
there is a bug that i remember in kali linux 2019.3 if thats what your were using

i remember that, that specific beef version had conflicts with the config.yaml. 

after you ran beef once the config.yaml would totally changed, and a lot of options were missing,

after git cloning the repo everything worked fine, this was true for kali linux 2019.3,

even did a "apt purge --auto-remove beef-xss" and reinstallation with apt gave the same thing.

if you want my advice always clone this repo.

**Comment by jcrew99** [comment]
@azamet90 Has your question\'s been answered fully? do you understand what @bcoles is saying above in regards to the Persistence modules and what their use is?

**Comment by jcrew99** [comment]
@azamet90 I am going to close this due to inactivity, if youre still having this issue and need more help please re-open it.

**Comment by Tevgeralahmad** [comment]
I have the same problem

**Comment by bcoles** [comment]
> I have the same problem

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
