### ISSUE TITLE
Replacing Therubyracer

### ISSUE THREAD

**Issue by jcrew99** [beefproject/beef#1789]
This is an issue to try and replace therubyracer with another gem. 
Therubyracer seems to have been causing problems for a while and if there is an alternative that would work and remove the issues therubyracer sometimes causes for people that would be helpful.
I am currently trying discourse/mini_racer for example, which seems to be more up to date.
I have been using mini_racer in place of therubyracer and havent seen any issues, but will note them down when seen.
If anyone has any ideas or methods that is more stable please put them down so we can discuss

**Comment by bcoles** [comment]
`therubyracer` was dropped in #1591 in favor of relying on NodeJS, but was latter re-added without explanation.

**Comment by jcrew99** [comment]
So it was removed on 2018-07-19 by Petko Bordjukov and added on 2019-09-26 by @passbe when the Rspec tests were merged. Ben is it fine for me to remove therubyracer again or is there a specific reason to have the gem? If so would using mini_racer be viable instead?

**Comment by jcrew99** [comment]
#1793

**Comment by jcrew99** [comment]
Ben confirmed that there is no conflicts so i removed it and am closing this issue.
