### ISSUE TITLE
hook injection is not effective on edge and chrome

### ISSUE THREAD

**Issue by Prometheus0088** [beefproject/beef#1795]
beef version 0.4.7.3-alpha in Kali 
The host machine is Kali and the target is windows10 running in virtual box.
I've have customized the config.yaml according the guide in the github page and it works just fine as long as I hook the firefox on the target machine but it seems that the hook is ineffective on microsoft edge and chrome browsers.

**Comment by jcrew99** [comment]
@Prometheus0088  Was this resolved for you? i have been using beef with edge and chrome and haven't had any issues with it so far.
