### ISSUE TITLE
pretty theft log in button not working

### ISSUE THREAD

**Issue by isuruwijesinghe** [beefproject/beef#1800]
Im using BeEF 0.4.7.3-alpha version . hook is working fine but when I use pretty theft and execute dialog box shows up but cannot click login button after entering the data.

**Comment by jackdwalker** [comment]
@isuruwijesinghe did you ever manage to get this issue resolved? If not could you please try pulling the current latest version and try again. If you're still encountering issues please try and give us as much information as possible including error logs, OS/browser information, etc, preferably using the standard issue template.

If we don't hear back within the next week we'll be closing the issue off.
