### ISSUE TITLE
BeEF Wiki - Advanced Module Creation

### ISSUE THREAD

**Issue by grantrburgess** [beefproject/beef#1811]
Could this page be removed? It seems like it might be redundant with the Module creation page under Advanced Utilization? https://github.com/beefproject/beef/wiki/Module-creation

**Comment by bcoles** [comment]
It is somewhat redundant. The intention of the [Advanced Module Creation](https://github.com/beefproject/beef/wiki/Advanced-Module-Creation) page may have been to document more advanced functionality.

For example, some of the `modules/browser/detect_*` modules populate `BrowserDetails` using `BeEF::Core::Models::BrowserDetails.set`.

Similarly, some of the `modules/network/*` network related modules populate `NetworkService` using `BeEF::Core::Models::NetworkService.add`.

There's the option to perform more complex post-processing, however this functionality is rarely used.

**Comment by jcrew99** [comment]
I am going to close this ticket as the other module creation page has been modified to try and describe how to actually create a module in a lot more depth, ideally like a walk through
