### ISSUE TITLE
Proxy is broken

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1851]
Proxy is broken

![image](https://user-images.githubusercontent.com/434827/72316547-a2374600-36ea-11ea-9cea-74ccf0b0807b.png)

`Request sent to hooked browser undefined`

The client never sends the request, and the Proxy `History` tab is not populated.

**Comment by h4sh5** [comment]
I tried on OSX and it works on Chrome, but not Firefox or safari. It's really weird. Does Chrome work for you?

**Comment by jcrew99** [comment]
@bcoles I am having the history show up, are you still having this error?
![image](https://user-images.githubusercontent.com/37361441/72692707-253c1e80-3b79-11ea-9997-61454adde450.png)

**Comment by bcoles** [comment]
I'm not having this issue any more.

However, `Request sent to hooked browser undefined` still appears in the UI. The admin UI JavaScript needs an update somewhere.
