### ISSUE TITLE
Network Map/Hosts/Services is broken

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1852]
Network Map/Hosts/Services is broken.

![image](https://user-images.githubusercontent.com/434827/72316641-fcd0a200-36ea-11ea-9d09-9a306c6698e2.png)

No details are populated.

**Comment by h4sh5** [comment]
Is there some error message / log that you can attach? It will helps us see what's wrong

**Comment by bcoles** [comment]
> 
> 
> Is there some error message / log that you can attach? It will helps us see what's wrong

No logs.

Steps to reproduce:

1. start BeEF
1. hook a browser
1. select the hooked browser
1. navigate to the Network tab
1. observe the Map, Hosts, and Services tabs are empty

**Comment by h4sh5** [comment]
It could be a browser/even linux security feature. Can you open the developer js console and take a screenshot of possible debug messages / errors?

Also, try hooking other browsers to see if the same result is produced.

**Comment by bcoles** [comment]
> It could be a browser/even linux security feature.

This is not due to a security feature. The `Get Internal IP (WebRTC)` module works correctly.

> Can you open the developer js console and take a screenshot of possible debug messages / errors?

There are no JavaScript error messages in the Admin UI. HTTP requests to the API are successful, however no hosts or services are returned.

The `NetworkHosts` table is initialised with a default entry of `127.0.0.1` for each hooked browser. As such, the Map should never be empty. Likewise, the Hosts tab should never be empty. For whatever reason, this is no longer being populated.

> Also, try hooking other browsers to see if the same result is produced.

The same result is produced on Linux and Windows using Firefox and Chrome. The bug exists server side. The bug was introduced following changes introduced some time in the past few months.

**Comment by jcrew99** [comment]
@bcoles  Can you try and see if its fixed for you now?

**Comment by bcoles** [comment]
Fixed thanks

**Comment by Craeckie** [comment]
I have the same problem

**Comment by jackdwalker** [comment]
Am I reading this wrong? Was the issue fixed with #1857, and then closed. Then https://github.com/beefproject/beef/commit/7d9a235bbf792172dddbdb87bb5dff73e7b2629c was reverted and the issue re-appeared again?

Why was the solution reverted?

@jcrew99 @h4sh5

**Comment by jackdwalker** [comment]
As soon as I add the changes back on my local it works fine. I'll wait for some context indicating why this solution is not suitable otherwise I'm going to re-push **h4sh5's** changes.

**Comment by jackdwalker** [comment]
It's been two weeks without discussion or comment on the PR. I'm going to merge it across and close this off.
