### ISSUE TITLE
undefined method after upgrading Ubuntu

### ISSUE THREAD

**Issue by pomil** [beefproject/beef#1864]
Installed Versions:
============
BeEF: 0.5.0.0-alpha-pre
Ruby: 2.5.3p105 (2018-10-18 revision 65156)
Browser: Mozilla Firefox 72.0.1
OS: Ubuntu (x64) 19.10

#### Configuration

Are you using a non-default configuration? --> NO

Have you enabled or disabled any BeEF extensions? --> NO

#### Summary

Ubuntu, Ruby, BeEF updated to the latest updates. 

#### Expected Behaviour

No error message. "./beef" should start BeEF.

#### Actual Behaviour

When running ./beef I get following Error message: 

Traceback (most recent call last):
        4: from ./beef:142:in `<main>'
        3: from /home/osboxes/PenTestingTools/beef/core/extensions.rb:25:in `load'
        2: from /home/osboxes/PenTestingTools/beef/core/extensions.rb:12:in `get_enabled'
        1: from /home/osboxes/PenTestingTools/beef/core/extensions.rb:12:in `select'
/home/osboxes/PenTestingTools/beef/core/extensions.rb:12:in `block in get_enabled': undefined method `[]' for nil:NilClass (NoMethodError)

#### Steps to Reproduce

1. Update Ubuntu 19.10 to latest updates.
2. Update Ruby, SQLite, Node.js
3. Update BeEF

**Comment by jcrew99** [comment]
@pomil I will try and look at this later tonight but may you please try starting beef with the x tag?
i.e. /home/osboxes/PenTestingTools/beef/ ./beef -x and see what that does for you. 
Can you also provide the terminal output of what beef does when it starts?

**Comment by jcrew99** [comment]
I think this is the Nil class error as shown in @1856

**Comment by bcoles** [comment]
> 
> 
> I think this is the Nil class error as shown in #1856

Unlikely. #1856 is related to processing network traffic.

This issue appears to be related to loading extensions.  I added some debug output in #1873 which might help.

I wasn't able to reproduce this on a mostly-up-to-date Ubuntu 19.04 using the latest version of BeEF from `master` and default settings.

**Comment by jcrew99** [comment]
@bcoles  That's fair enough. 
@pomil  Can you please try the debug output that Bcoles has added above?

**Comment by jackdwalker** [comment]
@pomil I'm going to close this off as we haven't heard from you since you created the issue. Please feel free to let us know if you've had further issues and/or addressed the feedback above and we can look at re-opening it.

**Comment by catchmeifyoucaan** [comment]
im having this very error

**Comment by bcoles** [comment]
> im having this very error

This issue is over 2 years old. It is unlikely that you are encountering this error.

Also this issue is closed. Please create a new issue and be sure to complete the issue template.
