### ISSUE TITLE
BeEF Jquery decoupling

### ISSUE THREAD

**Issue by jcrew99** [beefproject/beef#1871]
In BeEF the Jquery version needs to be able to support an updated version of Jquery.
Ideally it should be able to handle Jquery core 2.x and Jquery core 3.x as well.
Versions of Jquery which are deprecated we need to be able to handle.

This may involve changing how beef works to determine what version is being supplied and change depending on the version.
 
@bcoles  May you know what may go into doing this? 
I understand its a large task and that significant portions of the codebase may need to change but i was hoping you may be able to provide a lot more information.

**Comment by bcoles** [comment]
The lame option is to simply upgrade jQuery and stop supporting older browsers.

The correct solution is to use a staged hook, which should have been done a long time ago, but it is a huge piece of work. #1573

**Comment by jcrew99** [comment]
@bcoles That would be a much more useful and interesting way to do it. I will comment further on the Staged Hook Issue.
