### ISSUE TITLE
Running in chroot ignoring start

### ISSUE THREAD

**Issue by Thiviyan** [beefproject/beef#1876]
beef-xx not starting in Nethunter

when launching beef with beef-xss it fails to start  and the error is 
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

Running in chroot, ignoring request: start
Running in chroot, ignoring request: status

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1... 

able to start beef manually by giving this commands
cd /usr/share/beef-xss 
./beef
------

**Comment by jcrew99** [comment]
@Thiviyan Can you please provide some more information about the environment, what the expected outcome and the actual outcome is? I am not familiar with net hunter but it seems like you tried to start beef in the incorrect directory?

**Comment by bcoles** [comment]
This is probably related to the use of `Bundler.require(:default)` - see also: https://github.com/beefproject/beef/issues/1466#issuecomment-350190077

**Comment by Thiviyan** [comment]
> This is probably related to the use of `Bundler.require(:default)` - see also: [#1466 (comment)](https://github.com/beefproject/beef/issues/1466#issuecomment-350190077)

Yes this one worked for me now i am able to run beef by just typing beef

**Comment by Thiviyan** [comment]
> @Thiviyan Can you please provide some more information about the environment, what the expected outcome and the actual outcome is? I am not familiar with net hunter but it seems like you tried to start beef in the incorrect directory?

It's solved with a dirty fix.

**Comment by Morrigan-Ship** [comment]
same error via systemctl start services
