### ISSUE TITLE
Add excluded_hooking_subnet config option

### ISSUE THREAD

**Issue by icamys** [beefproject/beef#1878]
It would be convenient to list excluded hooking subnets the same way we do with permitted ones.

**Comment by jackdwalker** [comment]
@icamys could you please review bcoles comments on your PR? :)

It's a nice feature! We will be closing this off though if we don't hear back from you in the next 7 days. Feel free to re-open this ticket and your PR if you don't see this until after it's closed.

**Comment by jackdwalker** [comment]
Decided to go ahead and address the changes myself - I like the feature :) See #1973.
