### ISSUE TITLE
Beef not working on Kali Linux 2020 VirtualBox VM. 

### ISSUE THREAD

**Issue by ChopperCharles** [beefproject/beef#1884]
#### Environment

What version/revision of BeEF are you using? 0.5.0.0

On what version of Ruby? No idea. Whatever comes installed with Kali 2020.1

On what browser? Chrome, FireFox, and Safari.

On what operating system? Kali Linux

#### Configuration

Are you using a non-default configuration?  No

Have you enabled or disabled any BeEF extensions? No

#### Summary

First of all, Beef-xss doesn't install on the fresh Kali Linux virtual machine. I get a "Unable to locate package" error. I have to edit the /etc/apt/sources.list file and add more sources before "apt-get install beef-xss" would work.

After that, it installed correctly, and I am able to start the service and load the configuration panel, both from inside the Kali linux machine and from a browser on my host.  I can also hook a browser. But that's it. I can't do anything else. None of the commands work. When I execute them, they don't do anything on the hooked browsers, and when I click on the "Module Results History", the results are blank. There is never any data. I've enabled debugging via the config.yaml file, and yet there is no additional data in the logging tab.

What's more, any hooked browser almost immediately switches from online to offline. 

#### Expected Behaviour

I expect the hooked browsers to stay in the online section when they're still online, and the commands to work. I also expect a seamless installation -- or better yet, it should come installed on Kali linux. 

#### Actual Behaviour

Unstable "Online Browser". Sometimes a particular browser will bounce back and forth between online and offline. Usually however a hooked browser immediately becomes offline, for no discernible reason. 

None of the commands work. Every now and then, if I time it just right, I can get one of the debug commands to work with the browser that bounces between online and offline. (the one that returns an image)

#### Steps to Reproduce

Please provide steps to reproduce this issue. Install Virtualbox on a Mac. Download the kali linux 2020.1 VM and mount it into VirtualBox. Set the adapter type to Bridged. Try and sudo run apt-get install beef-xss. It won't install. Edit the /etc/apt/sources.list file Add the following lines:

deb http://http.kali.org/kali sana main non-free contrib
deb http://security.kali.org/kali-security sana/updates main contrib non-free
deb http://old.kali.org/kali moto main non-free contrib

Then run sudo apt-get update
Then sudo apt-get install beef-xss should work. 

After it installs, start it. Copy the hook link into the bookmarks tab of browser of your choice on the host. Open facebook, then click the bookmark. Browser is hooked. 

Open control panel on kali box, and attempt to run any commands, such as play a sound. The hooked browser will immediately show as offline, no sound will play, and there will be no result in the module results history. The command results will always be blank. 

#### Additional Information

Anywhere in the config.yaml file where "debug" was printed, I changed it from false to true. This didn't appear to do anything, the log doesn't indicate why transactions failed.

**Comment by jcrew99** [comment]
Hi @ChopperCharles,
For the first section for the Summary question, BeEF has been removed from the default metapackage to the larger one. (https://www.kali.org/news/major-metapackage-makeover/)
Its disappointing but beef didn't have any control over it.

Thats definitely odd behavior, can you please do the following and post the results? 
  * (debian/Kali) $ruby -v
  * (output of beef) $./beef or the beef xss command 
  * confirm that you are using the localhost ui  or the other one.

I am also not sure what Kali currently has for beef, Can you also clone the repo and try manually and see if you get the same output?

**Comment by ChopperCharles** [comment]
I downloaded an old copy of Kali 2019.1 and am using that instead.

**Comment by jcrew99** [comment]
@ChopperCharles  Okay, i haven't had this issue occur with me with testing and haven't been able to replicate it. I will test the latest kali version and see if i find the same issues as above. If so we can potentially try and reach out to ask them to update if possible. 
Please let me know if that happens again or with another version but i will close this ticket for now.
Feel free to reopen if the issue occurs again.

**Comment by mahimakaushik-oss** [comment]
once my kali installed and was working in my virtual box but after some time it stop working. so i tried to re install that but installation error is coming (kali version 2020.2) . i tried many times but same issue . plz suggest something if someone know about it.......

**Comment by bcoles** [comment]
> 
> 
> once my kali installed and was working in my virtual box but after some time it stop working. so i tried to re install that but installation error is coming (kali version 2020.2) . i tried many times but same issue . plz suggest something if someone know about it.......

This issue is closed. Please create a new issue and fill out the issue template.

**Comment by becj356** [comment]
My hook link is not working..is there something needed too be done.?

**Comment by becj356** [comment]
I install and took every precaution..download beef xss,set up password and sent the link but it’s not hooking my target browser

**Comment by bcoles** [comment]
> I install and took every precaution..download beef xss,set up password and sent the link but it’s not hooking my target browser

There is not enough information. You will need to perform troubleshooting.

This issue is closed.
