### ISSUE TITLE
UI lock on selecting a module

### ISSUE THREAD

**Issue by aussieklutz** [beefproject/beef#1889]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).

#### Environment

What version/revision of BeEF are you using?
0.5.0.0-alpha-pre
On what version of Ruby?
2.5.3 (configured by RVM)
On what browser?
Chrome 80
On what operating system?
Windows 10
Server on Debian 10

#### Configuration

Are you using a non-default configuration?
No
Have you enabled or disabled any BeEF extensions?
No, default extensions

#### Summary

Please provide a summary of the issue.
On selecting a module in the ui, browser locks at please wait module config is loading. Observed on multiple modules, example below from Detect Microsoft Office module

#### Expected Behaviour

What was the expected result?
Module config options will load.

#### Actual Behaviour

What was the actual result?
UI locks at the module config is loading modal. The debug shows the following

Uncaught SyntaxError: Unexpected number
    at doDecode (ext-all.js:2681)
    at Object.decode (ext-all.js:2779)
    at success (web_ui_all.js:1)
    at Ext.data.Connection.handleResponse (ext-all.js:2595)
    at f (ext-base.js:7)
    at m (ext-base.js:7)
    at ext-base.js:7

#### Steps to Reproduce

Please provide steps to reproduce this issue.

Authenticate into ui, select a target hooked browser, select the commands tab, select the Detect Microsoft Office payload

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by jcrew99** [comment]
@aussieklutz  Have you tried refreshing your UI browser? Sometimes that might fix it but ill look at the module and take steps to replicate it.

**Comment by jackdwalker** [comment]
I have not been able to replicate the issue. @jcrew99 could you please have a go and if you're unable to replicate it, feel free to close the issue off.

**Comment by jcrew99** [comment]
I haven't been able to replicate it either, as described above nor been able to configure it in any other way to achieve the bug. I believe it may be related to a configuration not specified. I will close for now.

**Comment by lucachala** [comment]
Same Issue here
