### ISSUE TITLE
[ARE] Failed to load ruleset from /root/beef/./arerules/enabled/lan_port_scan.json

### ISSUE THREAD

**Issue by websecer** [beefproject/beef#1892]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
root@vultr:~/beef# ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by jcrew99** [comment]
@websecer  Thanks, a ARE rule was moved to enabled by default in the repo. #1895  will remove it.

**Comment by websecer** [comment]
tks
