### ISSUE TITLE
Unable to see Online Browsers in Panel

### ISSUE THREAD

**Issue by jgm96** [beefproject/beef#1906]
#### Environment

What version/revision of BeEF are you using? 
BeEF 0.5.0.0-alpha-pre 

On what version of Ruby?
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]

On what browser?
68.2.0esr (64-bit)

On what operating system?
Kali Linux 2019.4

#### Configuration

Are you using a non-default configuration?
No

Have you enabled or disabled any BeEF extensions?
No

#### Summary
I am not being able to see any hooked browser in online or offline browsers panel. When I hook a browser, `beefnew` is shown in console, but I can't see any in hooked browsers. The only error I get when starting BeEF is:
` [ARE] Failed to load ruleset from /root/Documents/web/beef/./arerules/enabled/lan_port_scan.json`
I don't think it has nothing to do with the problem though.
If I run BeEF in debug mode, I see this message when I click on the hook link:
`beefnew10.1.0.1 - - [09/Apr/2020:09:54:17 +0100] "GET /hook.js HTTP/1.1" 200 - 0.0024`
If I access to UI in debug mode, the program breaks.

` [2020-04-09T09:56:35.197098 #5735] ERROR -- : Unexpected error while processing request: undefined method `each' for nil:NilClass

        /var/lib/gems/2.5.0/gems/rack-2.2.2/lib/rack/utils.rb:425:in `initialize'
        /var/lib/gems/2.5.0/gems/rack-2.2.2/lib/rack/utils.rb:418:in `new'
        /var/lib/gems/2.5.0/gems/rack-2.2.2/lib/rack/utils.rb:418:in `[]'
        /var/lib/gems/2.5.0/gems/rack-2.2.2/lib/rack/common_logger.rb:39:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:231:in `call'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:86:in `block in pre_process'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `catch'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `pre_process'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
        /var/lib/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /var/lib/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
        /usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
        /root/Documents/web/beef/core/main/server.rb:165:in `start'
        ./beef:232:in `<main>' `

#### Expected Behaviour

Hooked browsers are shown in the UI panel.

#### Actual Behaviour

No hooked browsers are shown in the UI panel.

#### Steps to Reproduce

Try to hook a browser, even clicking on "Hook me" button, it won't show anything in the panel.

**Comment by jcrew99** [comment]
hi @jgm96, That ARE problem should be fixed now. Are you definitely pulled from the lasted master? Does refreshing the page help and can you start beef with the -x flag.
" $ ./beef -x " 
Please let me know if youre still having the issue.

**Comment by jgm96** [comment]
The problem is fixed now. Fully tested. Thank you for your help.

**Comment by norayr93** [comment]
@jgm96 I am having the same issue. Could you please tell me, how you fixed that ?

Also, in the terminal, it warns me 
**/usr/bin/python: No module named virtualenvwrapper
virtualenvwrapper.sh: There was a problem running the initialization hooks.

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python and that PATH is
set properly.**

Even though, I set the path correctly, the error doesn't go

**Comment by bcoles** [comment]
> I am having the same issue. Could you please tell me, how you fixed that ?

If you have an issue please create a new issue and ensure you complete the issue template.

By "the same issue" do you mean the `Unexpected error while processing request: undefined method` error? Or not being able to see hooked browsers? Not being able to see hooked browsers could be caused by a number of things.
