### ISSUE TITLE
Why there is a key whose name is "unique"?

### ISSUE THREAD

**Issue by l0kihardt** [beefproject/beef#1909]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).

#### Environment

What version/revision of BeEF are you using?
BeEF 0.5.0.0-alpha-pre
On what version of Ruby?
ruby 2.5.7
On what browser?
Firefox
On what operating system?
Manjaro

#### Configuration

Are you using a non-default configuration?
nope
Have you enabled or disabled any BeEF extensions?
nope

#### Summary

Please provide a summary of the issue.

After injecting hook.js, you will find that every Object Array have an extra object.
Why there is a key whose name is "unique".
```
let a = [{}, {}, {}];
for(i in a){
    console.log(i);
}

0 
1
2
unique
```

#### Expected Behaviour

What was the expected result?
```
let a = [{}, {}, {}];
for(i in a){
    console.log(i);
}

0 
1
2
```

#### Actual Behaviour

What was the actual result?
```
0 
1
2
unique
```

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by l0kihardt** [comment]
Not being a JavaScript developer, I debugged painfully and finally found why this happens.
In the `core/main/client/browser.js` file, it redefined the `Array.prototype.unique` to its own function.
This results in an conflict to the for loop.

**CODE**
```JavaScript
    /**
     * Returns the list of plugins installed in the browser.
     */
    getPlugins: function () {

        var results;
        Array.prototype.unique = function () {
            var o = {}, i, l = this.length, r = [];
            for (i = 0; i < l; i += 1) o[this[i]] = this[i];
            for (i in o) r.push(o[i]);
            return r;
        };

        // Things lacking navigator.plugins
        if (!navigator.plugins) 
```

I don't know how to fix it, tried some methods, but didnt work.

**Comment by jcrew99** [comment]
That is an odd issue, I am unsure as to why its doing that.

**Comment by bcoles** [comment]
> 
> 
> That is an odd issue, I am unsure as to why its doing that.

The library should not need to modify the `Array` object with `Array.prototype.unique`. There's probably a cleaner `jQuery` way to do this. This code was written in a time when IE8 was still popular.

**Comment by jackdwalker** [comment]
I think I've dev'd out a solution for this. Seems to be working fine. As suggested by @bcoles I did a bit of digging and found a cleaner jQuery alternative to address the problem that the `Array.prototype.unique` function was solving. 

```javascript
function unique(array) {
    return $.grep(array, function(el, index) {
        return index === $.inArray(el, array);
    });
}
```

The code snippet shared above by @l0kihardt should now result in the expected behaviour:

```javascript
let a = [{}, {}, {}];

for(i in a){
    console.log(i);
}

// OUTPUT
0 
1
2
```

Tests are passing and I haven't noticed any other issues/bugs caused by this change.
