### ISSUE TITLE
How to install beef on Windows? I have some errors

### ISSUE THREAD

**Issue by vanproskur** [beefproject/beef#1910]
I found it: https://www.hackingarticles.in/how-to-install-beef-in-windows-pc/
But i have some errors. For example i downloaded the beef from github and ran "ruby install".
Windows said , that no Ruby script found in input. Can you help me?

**Comment by bcoles** [comment]
I recommend you do not run BeEF on Windows.

**Comment by vanproskur** [comment]
i have not good computer , i can't install linux on for example on VmWare.

**Comment by bcoles** [comment]
> 
> 
> i have not good computer , i can't install linux on for example on VmWare.

I understand.

You are going to have a hard time getting BeEF working on Windows.

If you really want to run BeEF on Windows, you could try with cygwin or WSL. You can find more info here: #1803

**Comment by vanproskur** [comment]
thank you very much

**Comment by jcrew99** [comment]
I am going to close this comment as beef in windows is not officially supported and has been covered before and there are related issues if you have trouble with it.
I definitely suggest the issue bcoles linked above as it has a lot of information
