### ISSUE TITLE
code=exited, status=1/FAILURE 

### ISSUE THREAD

**Issue by xkenraali** [beefproject/beef#1921]
I need help to figure out what's wrong because my beef is not able to startup it says: 

● beef-xss.service - beef-xss
     Loaded: loaded (/lib/systemd/system/beef-xss.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2020-05-09 16:35:03 EEST; 4s ago
    Process: 5566 ExecStart=/usr/share/beef-xss/beef (code=exited, status=1/FAILURE)
   Main PID: 5566 (code=exited, status=1/FAILURE)

And here's infomation about my system:
os=parrot os
vpn= yes
proxy= no
Hellllpppp!!!!!!!!!!

**Comment by DeezyE** [comment]
Is this a new install of Beef?
Which beef version?

**Comment by jcrew99** [comment]
@DeezyE  This would be the pre-packaged version of beef by kali.
@xkenraali Can you please describe the kali version and other ENV ?

**Comment by jackdwalker** [comment]
@jcrew99 note @xkenraali has mentioned that they are using Parrot OS rather than Kali.

**Comment by jcrew99** [comment]
@jackdwalker  That's a good point, i think i got my issues messed up.
I will test for the parrot OS as well.

**Comment by xkenraali** [comment]
my linux version is:
Linux parrot 5.5.0-1parrot1-amd64 #1 SMP Parrot 5.5.17-1parrot1 (2020-04-25) x86_64 GNU/Linux
and beef version:
beef-xss is already the newest version (0.5.0.0+git20191218-0kali2)

**Comment by xkenraali** [comment]
Need anything else?

**Comment by bcoles** [comment]
> 
> 
> Need anything else?

Are there any logs in `dmesg`, `journalctl`, or `~/.beef` which might give an indication of the reason for startup failure?

**Comment by xkenraali** [comment]
idk where i would find those logs i tried /usr/share/beef-xss but no luck

**Comment by xkenraali** [comment]
Process: 2498 ExecStart=/usr/share/beef-xss/beef (code=exited, status=1/FAILURE)
i found that /usr/share/beef-xss/beef does no exist ??!!

**Comment by bcoles** [comment]
> idk where i would find those logs i tried /usr/share/beef-xss but no luck

`journalctl` and `dmesg` are utilities. You should find them in your `$PATH`.

`~/.beef` is a file path. `~` represents the user's home directory. The `beef-xss` service may (or may not) run as `root`, in which case the logs would located in `/root/.beef`. Presuming that BeEF is configured with logging on ParrotOS, you'll find the logs at `/root/.beef/beef.log`. However:

> Process: 2498 ExecStart=/usr/share/beef-xss/beef (code=exited, status=1/FAILURE)
> i found that /usr/share/beef-xss/beef does no exist ??!! would that be the reason?

That's not a good sign. Yes, that's probably the reason. I have no idea why or how that happened. Perhaps there's an issue with the `beef-xss` package on ParrotOS.

Perhaps you could find the directory containing the `beef` executable and run it from there.

Alternatively, you could try cloning BeEF from GitHub.

**Comment by xkenraali** [comment]
Ok ill try delete beef and download it from github and not with pip install beef-xss because it seems that the whole parrot's pip and apt is broken.

**Comment by bcoles** [comment]
> 
> 
> Ok ill try delete beef and download it from github and not with pip install beef-xss because it seems that the whole parrot's pip and apt is broken.

BeEF is written in Ruby. `pip` is used to managing Python packages.

**Comment by xkenraali** [comment]
ya but when i got problems by installed by pip after that i tried apt but still not work...

**Comment by xkenraali** [comment]
Omg i got it working!!! i did these commands:
git clone https://github.com/beefproject/beef/
cd beef
./install
./update-geoipdb
nano config.yaml
and changed username and password
./beef
and it worked thank so much for your help i wouldnt have motivation to do this my self :) !
