### ISSUE TITLE
0.6.0.0 alpha Milestone

### ISSUE THREAD

**Issue by jcrew99** [beefproject/beef#1926]
This Issue is to try and track steps towards the 0.6.0.0 milestone for beef.

Preferably this milestone should be aimed at Defect, Maintainability and Documentation tickets. I believe the goal of this is to try and make BeEF as easy to pick up for new users and Dev's as we can. To this goal the issues in the milestone should be reflect that and to making BeEF as stable as we can. 
This means we should focus on things which are not working as they should.

**Comment by jcrew99** [comment]
@bcoles May i ask for your thoughts on this? Also on the Milestone itself and the appropriate issues?

**Comment by jcrew99** [comment]
@DeezyE  please see this ticket and the 0.6.0.o milestone :)

**Comment by bcoles** [comment]
> 
> 
> @bcoles May i ask for your thoughts on this? Also on the Milestone itself and the appropriate issues?

This makes sense.

Traditionally we have used point releases, ie `0.5.1.0`, `0.5.2.0`, etc. With minor version reserved for urgent bug fixes. ie, `0.5.0.1`

The move from `DataMapper` to `ActiveRecord` was a large change which warranted bumping `0.4.x` to `0.5.x`.

Not that it makes much difference.
