### ISSUE TITLE
Not able to load hook.js file 

### ISSUE THREAD

**Issue by amitkhanna1884** [beefproject/beef#1928]
I am able to download hook.js by using direct url over WAN for example http://b865xx0.ngrok.io/hook.js but same file unable to load <script src="http://b865xx0.ngrok.io/hook.js"></script> in html page. 
when i load my html page, I see multiple requests go to http://b865xx0.ngrok.io:3000/dh?bh and my ngrok tunnel port is listening on port 80 due to that all requests failed.
I have also tried by changing the default port from 3000 to 80 in beef yml file but faced same problem.

I am not sure where i am making the mistake  and how to proceed further. Please suggest.

**Comment by bcoles** [comment]
In your `config.yaml` files, what have you set `public_host` and `public_port` to?

**Comment by amitkhanna1884** [comment]
do i need add these parameters because i don't see that in default config.yaml files

**Comment by bcoles** [comment]
Perhaps this will help:

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by amitkhanna1884** [comment]
I have updated the beef version and after modifying the config.yaml file, issue sorted. 
Thank you Bcoles for you help..

**Comment by jcrew99** [comment]
Sounds good, nice work bcoles. I am going to close this issue :)

**Comment by azamet90** [comment]
> Sounds good, nice work bcoles. I am going to close this issue :)

have success?? can u help me to do it? this information in that link is not enough for me to understand: https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
but if for u it was enough to solve the problem can u pls explain us? thx
