### ISSUE TITLE
I cant get information on the command on beef that I try to run

### ISSUE THREAD

**Issue by hooterhorn** [beefproject/beef#1930]
when I try to run a command on beef on a browser I hooked, I cannot get information on that command.
Does anyone know how to solve this?

**Comment by bcoles** [comment]
What command are you trying to run? How are you trying to run it? What do you mean by "cannot get information" ?

**Comment by hooterhorn** [comment]
Basically any command that is green.
What I mean by cannot get information,
is when you click on a command like the alert command, it does not give me a option to choose what the alert will be.
Also, if I click on a command, nothing shows up in the output, and nothing happens on the target machine.

**Comment by bcoles** [comment]
What errors do you get in console? What logs do you get?

`tail ~/.beef/beef.log`

If BeEF is running as a service, use: `journalctl -u beef-xss`

**Comment by hooterhorn** [comment]
Sometimes i get a error, sometimes I dont.  Also, I cant get a hooked browser, that I know is online, to be online on the beef control panel.
Do you know how to fix this?
Also, do you know how I can make the info (setting the message in the alert, etc.) show up?

**Comment by bcoles** [comment]
> Also, do you know how I can make the info (setting the message in the alert, etc.) show up?

No, I can't read your filesystem or your mind.

What errors do you get in console? What logs do you get?

**Comment by hooterhorn** [comment]
None, unless I try to run a command that is not known to work on the browser. Also, I downloaded BEEF with apt-get install beef-xss , I also tried git cloning, but I was not able to bundle install all of the other files, does that matter?

**Comment by jcrew99** [comment]
@hooterhorn  
Okay so its the pre-packaged kali version that you are using.
Can you please screenshot the terminal console that you are running when you run beef -xss? 
Also please do the same for the UI and show what you are getting and just explain what you are expecting.
Does the test browser hook correctly? Explain how the hooked browser is set up.
Please do as bcoles has suggested and use: journalctl -u beef-xss and show the output.

If you can fill out as much information that's on this and post that as well please do: 
https://github.com/beefproject/beef/blob/master/.github/ISSUE_TEMPLATE.md

Can you expand more on the git clone? 
what did you do after doing the $ git clone ?
did you ./install in the beef folder?
Have you looked at the installation wiki?
https://github.com/beefproject/beef/wiki/Installation

Please describe and post accompanying screenshots.

**Comment by jcrew99** [comment]
closing as unresponsive
