### ISSUE TITLE
GeoIP fails to install

### ISSUE THREAD

**Issue by Roxiun** [beefproject/beef#1935]
#### Environment
**BeEF Version**: Latest - 0.5.0.0
**OS**: macOS

#### Configuration
Default configuration except changes to credentials with all extensions are enabled.

#### Summary
When running `sudo -H ./update-geoipdb` it outputs `

#### Expected Behaviour
**Expected Result**: MaxMind GeoLite database installed to `/opt/GeoIP`

#### Actual Behaviour
**Actual Result**: 
1. First running `./update-geoipdb` fails due to insufficent permissions
2. Running `sudo -H ./update-geoipdb` fails due to curl error: `curl: (6) Could not resolve host: geolite.maxmind.com`

#### Steps to Reproduce
* Clone latest rpo
* `./install`
* `sudo -H ./update-geoipdb`

#### Additional Info
Tried going to the link in the script (https://web.archive.org/web/20191227182209/https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz) but ended up with network error

**Comment by bcoles** [comment]
Yeah looks like `web.archive.org` might behaving issues at the moment.

**Comment by Roxiun** [comment]
@bcoles is there any other place to download GeoLite2?

**Comment by bcoles** [comment]
> 
> 
> @bcoles is there any other place to download GeoLite2?

Maybe. Web Archive is back up. You can download it from there.

**Comment by Roxiun** [comment]
Yes. Archive is back up. Thanks!
