### ISSUE TITLE
Unmet dependencies:  `libc6-dev : Breaks: libgcc-9-dev` during install

### ISSUE THREAD

**Issue by DeezyE** [beefproject/beef#1937]
#### Environment

What version/revision of BeEF are you using?
0.5.0.0
On what version of Ruby?
2.7
On what browser?
n/a
On what operating system?
Kali 2020.1

#### Configuration

Are you using a non-default configuration?
no
Have you enabled or disabled any BeEF extensions?
no

#### Summary

Please provide a summary of the issue.
During install I get an error:
```bash
The following packages have unmet dependencies:
 build-essential : Depends: gcc (>= 4:9.2) but it is not going to be installed
                   Depends: g++ (>= 4:9.2) but it is not going to be installed
 libc6-dev : Breaks: libgcc-9-dev (< 9.3.0-5~) but 9.2.1-22 is to be installed
E: Unable to correct problems, you have held broken packages.
```
looking around it seems not an issue unique to beef:
https://superuser.com/questions/1555536/cannot-solve-the-the-following-packages-have-unmet-dependencies-issue

running the suggested:
```bash
apt-get install gcc-9-base libgcc-9-dev libc6-dev
```
resolves the issue so it would make sense to add this to the install script.
Unsure whether this will impact older versions of kali if it's included by default...

#### Expected Behaviour

What was the expected result?
install script runs correctly

#### Actual Behaviour

What was the actual result?
```bash
The following packages have unmet dependencies:
 build-essential : Depends: gcc (>= 4:9.2) but it is not going to be installed
                   Depends: g++ (>= 4:9.2) but it is not going to be installed
 libc6-dev : Breaks: libgcc-9-dev (< 9.3.0-5~) but 9.2.1-22 is to be installed
E: Unable to correct problems, you have held broken packages.
```

#### Steps to Reproduce

Please provide steps to reproduce this issue.
New install of Kali 2020.1
uninstall ruby
run install script

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by jackdwalker** [comment]
These dependencies will need to be added to the Dockerfile as well as the install script. Should be a straight-forward fix. Will try to get this done today.

**Comment by jackdwalker** [comment]
@DeezyE - these dependencies are already in the install script. I see you added them in #1940, so I'll close this off.
