### ISSUE TITLE
During the process of using beef, I couldn't display the acquired browser normally, and a series of errors appeared after a while.

### ISSUE THREAD

**Issue by Whiteer-pro** [beefproject/beef#1939]
Below is the error log：

`[20:28:22][!] [Browser Details] Invalid browser version returned from the hook browser's initial connection.
[20:28:22][!] [Browser Details] Invalid cookies returned from the hook browser's initial connection.
[20:28:24][!] [Browser Details] Invalid valid for 'browser.window.hostport' returned from the hook browser's 

initial connection.
#<Thread:0x000055f4da565de0@/root/.ho/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:47 run> 

terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        50: from /root/.ho/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:48:in `block (2 levels) 

in <class:DynamicReconstruction>'
        49: from /root/.ho/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `check_packets'
        48: from /root/.ho/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `each'
        47: from /root/.ho/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:80:in `block in 

check_packets'
        46: from /root/.ho/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `execute'
        45: from /root/.ho/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `new'
        44: from /root/.ho/beef/core/main/handlers/browserdetails.rb:19:in `initialize'
        43: from /root/.ho/beef/core/main/handlers/browserdetails.rb:425:in `setup'
        42: from /root/.ho/beef/core/main/handlers/browserdetails.rb:425:in `each'
        41: from /root/.ho/beef/core/main/handlers/browserdetails.rb:428:in `block in setup'
        40: from /root/.ho/beef/core/main/models/browserdetails.rb:40:in `set'
        39: from /var/lib/gems/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/suppressor.rb:48:in `save!'
        38: from /var/lib/gems/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/transactions.rb:318:in `save!'
        37: from /var/lib/gems/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/transactions.rb:366:in 

`with_transaction_returning_status'
        36: from /var/lib/gems/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/transactions.rb:212:in 

`transaction'
        35: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
        34: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
        33: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
        32: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
        31: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
        30: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
        29: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
        28: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:293:in `block in within_new_transaction'
        27: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:255:in `commit_transaction'
        26: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
        25: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
        24: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
        23: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
        22: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
        21: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:264:in `block in commit_transaction'
        20: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `commit'
        19: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:77:in `commit_db_transaction'
        18: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
        17: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
        16: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
        15: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
        14: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
        13: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
        12: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
        11: from /var/lib/gems/2.5.0/gems/activesupport-

6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
        10: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
         9: from /var/lib/gems/2.5.0/gems/activerecord-

6.0.3.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:77:in `block in 

commit_db_transaction'
         8: from /var/lib/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:650:in `commit'
         7: from /var/lib/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:193:in `execute'
         6: from /var/lib/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:151:in `prepare'
         5: from /var/lib/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:202:in `block in execute'
         4: from /var/lib/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:202:in `to_a'
         3: from /var/lib/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/resultset.rb:133:in `each'
         2: from /var/lib/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/resultset.rb:105:in `next'
         1: from /var/lib/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/resultset.rb:170:in `next_hash'
/var/lib/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/resultset.rb:170:in `step': SQLite3::BusyException: database 

is locked (ActiveRecord::StatementInvalid)`

**Comment by Whiteer-pro** [comment]
When I first started using it, it was perfect. Could it be because I used https?

**Comment by Whiteer-pro** [comment]
ruby 2.5.5p157
gem 2.7.6.2
SQLite version 3.27.2
node v14.3.0

**Comment by Whiteer-pro** [comment]
[
![722cba65-6104-459b-a408-d5bc82725456](https://user-images.githubusercontent.com/66051257/83934692-6316a800-a7e5-11ea-874f-da31133a3289.png)
](url)

**Comment by Whiteer-pro** [comment]
There were a lot of browsers, and they all disappeared after a while, not because of offline

**Comment by Whiteer-pro** [comment]
Most likely it is a database problem, but I don’t know how to solve it

**Comment by bcoles** [comment]
> There were a lot of browsers, and they all disappeared after a while, not because of offline

Did you run `beef` with the `-x` flag? That will clear the database.

> database is locked

Database is locked *usually* happens when multiple database record writes are attempted at the same time. This is possible with a large number of hooked browsers. SQLite does not support concurrency. Ideally, a different DBMS such as PostgreSQL or MySQL is used in place of SQLite.

> Most likely it is a database problem, but I don’t know how to solve it

It's possible that there's something else going on.

**Comment by Whiteer-pro** [comment]
> > There were a lot of browsers, and they all disappeared after a while, not because of offline
> 
> Did you run `beef` with the `-x` flag? That will clear the database.
> 
> > database is locked
> 
> Database is locked _usually_ happens when multiple database record writes are attempted at the same time. This is possible with a large number of hooked browsers. SQLite does not support concurrency. Ideally, a different DBMS such as PostgreSQL or MySQL is used in place of SQLite.
> 
> > Most likely it is a database problem, but I don’t know how to solve it
> 
> It's possible that there's something else going on.

I did not execute the `-x` parameter, but directly `ruby beef`. Anyway, after using it, an exception will appear, and the browser will disappear. It is probably the reason for the database lock. How can I replace SQLite with SQL? Is there a tutorial to share it?

**Comment by jcrew99** [comment]
@Whiteer-pro Do you still get the same issue when you run beef with `./beef` ? 

We don't have a wiki write-up but i am sure we can do that at some point.
You should be able to follow this: https://help.cloud66.com/rails/how-to-guides/databases/replace-sqlite.html
I'm unsure if there will be anything else to do though

**Comment by bcoles** [comment]
BeEF used to support alternative databases, such as PostgreSQL and MySQL before the recent migration to Active Record.

I don't recommend downgrading BeEF, but the old code may be useful to review when re-adding support for alternative DBMS.

**Comment by jackdwalker** [comment]
@jcrew99 I think that providing PostgreSQL and MySQL support for BeEF would be a good addition to the next set (not the current set) of milestones along with #1785.

**Comment by wheatley** [comment]
#2143

**Comment by wheatley** [comment]
Closing this ticket and raised two seperate issues relating to adding support for PostgreSQL and MySQL #2143 & #2144
