### ISSUE TITLE
ERROR: While executing gem ... (Gem::RemoteFetcher::UnknownHostError)

### ISSUE THREAD

**Issue by sanjeevsihag** [beefproject/beef#1941]
#### Environment

What version/revision of BeEF are you using? 0.5.0.0

On what version of Ruby? 2.7.0

On what browser?

On what operating system? kali linux 2020.1

#### Configuration

Are you using a non-default configuration? no

Have you enabled or disabled any BeEF extensions?
no

#### Summary

I was installing beef all. was done but when it comes to ruby its says this
 [INFO]  Detecting Ruby environment...
[INFO]  Ruby version 2.7.0 is installed
[INFO]  Updating rubygems...
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    timed out (https://rubygems.org/specs.4.8.gz)

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 2.7.0 is installed
[INFO]  Updating rubygems...
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    timed out (https://rubygems.org/specs.4.8.gz)

**Comment by bcoles** [comment]
Looks like a temporary name resolution error. Try again?

If it fails again, ensure that `rubygems.org` resolves correctly.

**Comment by sanjeevsihag** [comment]
> Looks like a temporary name resolution error. Try again?
> 
> If it fails again, ensure that `rubygems.org` resolves correctly.

i tried it many time but not succeded.

**Comment by bcoles** [comment]
> 
> 
> > Looks like a temporary name resolution error. Try again?
> > If it fails again, ensure that `rubygems.org` resolves correctly.
> 
> i tried it many time but not succeded.

[Gem::RemoteFetcher::UnknownHostError](https://docs.ruby-lang.org/en/2.7.0/Gem/RemoteFetcher/UnknownHostError.html) is a `FetchError` that indicates that the reason for not being able to fetch data was that the host could not be contacted.

This isn't an issue with BeEF or the BeEF installer.

Your network routes or DNS resolution are not working.

Ensure `rubygems.org` resolves correctly. You can use `nslookup rubygems.org` to test domain resolution.

Ensure `https://rubygems.org` is accessible. You can use `curl https://rubygems.org` to test.

**Comment by sanjeevsihag** [comment]
> > > Looks like a temporary name resolution error. Try again?
> > > If it fails again, ensure that `rubygems.org` resolves correctly.
> > 
> > 
> > i tried it many time but not succeded.
> 
> [Gem::RemoteFetcher::UnknownHostError](https://docs.ruby-lang.org/en/2.7.0/Gem/RemoteFetcher/UnknownHostError.html) is a `FetchError` that indicates that the reason for not being able to fetch data was that the host could not be contacted.
> 
> This isn't an issue with BeEF or the BeEF installer.
> 
> Your network routes or DNS resolution are not working.
> 
> Ensure `rubygems.org` resolves correctly. You can use `nslookup rubygems.org` to test domain resolution.
> 
> Ensure `https://rubygems.org` is accessible. You can use `curl https://rubygems.org` to test.

not fixed.. please provide a installation rather

**Comment by bcoles** [comment]
> 
> 
> > > > Looks like a temporary name resolution error. Try again?
> > > > If it fails again, ensure that `rubygems.org` resolves correctly.
> > > 
> > > 
> > > i tried it many time but not succeded.
> > 
> > 
> > [Gem::RemoteFetcher::UnknownHostError](https://docs.ruby-lang.org/en/2.7.0/Gem/RemoteFetcher/UnknownHostError.html) is a `FetchError` that indicates that the reason for not being able to fetch data was that the host could not be contacted.
> > This isn't an issue with BeEF or the BeEF installer.
> > Your network routes or DNS resolution are not working.
> > Ensure `rubygems.org` resolves correctly. You can use `nslookup rubygems.org` to test domain resolution.
> > Ensure `https://rubygems.org` is accessible. You can use `curl https://rubygems.org` to test.
> 
> not fixed.. please provide a installation rather

No. Fix your DNS.

**Comment by sanjeevsihag** [comment]
> > > > > Looks like a temporary name resolution error. Try again?
> > > > > If it fails again, ensure that `rubygems.org` resolves correctly.
> > > > 
> > > > 
> > > > i tried it many time but not succeded.
> > > 
> > > 
> > > [Gem::RemoteFetcher::UnknownHostError](https://docs.ruby-lang.org/en/2.7.0/Gem/RemoteFetcher/UnknownHostError.html) is a `FetchError` that indicates that the reason for not being able to fetch data was that the host could not be contacted.
> > > This isn't an issue with BeEF or the BeEF installer.
> > > Your network routes or DNS resolution are not working.
> > > Ensure `rubygems.org` resolves correctly. You can use `nslookup rubygems.org` to test domain resolution.
> > > Ensure `https://rubygems.org` is accessible. You can use `curl https://rubygems.org` to test.
> > 
> > 
> > not fixed.. please provide a installation rather
> 
> No. Fix your DNS.

dns is working

**Comment by bcoles** [comment]
> dns is working

What output do you get when you run `bundle install` ?

**Comment by bcoles** [comment]
Maybe your system proxy is misconfigured?

`https://rubygems.org/specs.4.8.gz` is definitely accessible and works fine for me.

**Comment by sanjeevsihag** [comment]
is there a way i can manually put it it.? 

> Maybe your system proxy is misconfigured?
> 
> `https://rubygems.org/specs.4.8.gz` is definitely accessible and works fine for me.

**Comment by bcoles** [comment]
Wherever you're executing `./install`, run `bundle install` instead.

Or alternatively, you could also try to modify the `install` script to skip this step:

```diff
diff --git a/install b/install
index cb0c09c9..ed6b74fe 100755
--- a/install
+++ b/install
@@ -174,7 +174,6 @@ check_rubygems () {
   if command_exists gem${RUBYSUFFIX}
   then
     info 'Updating rubygems...'
-    gem${RUBYSUFFIX} update --system
   fi
 }
 
```

**Comment by jcrew99** [comment]
@sanjeevsihag bcoles is correct, that is an error with resolving rubygems. What is your output of `bundle install`?
