### ISSUE TITLE
Installation beef appears Depends: libsqlite3-0 (= 3.31.1-5) but 3.32.2-2 is to be installed

### ISSUE THREAD

**Issue by BeckGeGe** [beefproject/beef#1948]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).

#### Environment

What version/revision of BeEF are you using?

0.5.0.0-alpha-pre

On what version of Ruby?

Ruby-2.7.0

On what browser?

Google Chrome

On what operating system?

Parrot os

#### Configuration

Are you using a non-default configuration?

NO

Have you enabled or disabled any BeEF extensions?

NO

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

Hope the installation is normal

#### Actual Behaviour

What was the actual result?

Installation error

#### Steps to Reproduce

Please provide steps to reproduce this issue.

`rvm install ruby-2.7.0`

`cd ./beef`

`./install`

The result is wrong
 

#### Additional Information

The error message is as follows：

`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:`

`The following packages have unmet dependencies:
 libsqlite3-dev : Depends: libsqlite3-0 (= 3.31.1-5) but 3.32.2-2 is to be installed
 sqlite3 : Depends: libsqlite3-0 (= 3.31.1-5) but 3.32.2-2 is to be installed
E: Unable to correct problems, you have held broken packages`

I changed a lot of sources and still can't solve the problem

**Comment by jackdwalker** [comment]
Hi @BeckGeGe - I'm working on reproducing your error. I'll get back to you soon. Let us know if you found a work-around/solution to your problem.

**Comment by BeckGeGe** [comment]
> Hi @BeckGeGe - I'm working on reproducing your error. I'll get back to you soon. Let us know if you found a work-around/solution to your problem.


Thank you very much, I did not find a solution

**Comment by jackdwalker** [comment]
Hi @BeckGeGe - confirming that I've been able to reproduce your error. Working on a fix now :)

**Comment by jackdwalker** [comment]
Hi @BeckGeGe - it looks like an upstream package issue with ParrotOS:
https://community.parrotsec.org/t/sqlite3-will-not-install-broken-dependencies/13760

It is possible to get the package from another repository such as Ubuntu's core repository (https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/libsqlite3-0_3.31.1-4_amd64.deb.html), but this is not recommended.

Please see this page for more information about why taking packages from different distributions is not the best idea:
https://unix.stackexchange.com/questions/251239/add-ubuntu-repository-to-debian

Those resources should help you out if you are looking to get this working ASAP, but otherwise I think you're going to have to wait for ParrotOS to sort this out on their end. My only other recommendation would be to potentially swap to another distribution similar to ParrotOS in the mean-time, such as Kali Linux.

**Comment by BeckGeGe** [comment]
> Hi @BeckGeGe - it looks like an upstream package issue with ParrotOS:
> https://community.parrotsec.org/t/sqlite3-will-not-install-broken-dependencies/13760
> 
> It also looks like they've had similar issues in the past due to running from the testing release of Debian:
> https://community.parrotsec.org/t/firefox-is-not-reinstalling/8982/12
> 
> It is possible to get the package from another repository such as Ubuntu's core repository (https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/libsqlite3-0_3.31.1-4_amd64.deb.html), but this is **not** recommended.
> 
> Please see this page for more information about why taking packages from different distributions is not the best idea:
> https://unix.stackexchange.com/questions/251239/add-ubuntu-repository-to-debian
> 
> Those resources should help you out if you are looking to get this working ASAP, but otherwise I think you're going to have to wait for ParrotOS to sort this out on their end.
> 
> The pre-packaged version of BeEF, `beef-xss`, comes with ParrotOS by default. It is currently working, so utilising that may be a solution to your problem. See `/usr/share/beef-xss` on your machine.
> 
> My only other recommendation would be to potentially swap to another distribution similar to ParrotOS in the mean-time, such as Kali Linux.

Thank you very much, I only have this problem when using ParrotOS, and this problem does not occur when I use Ubuntu, thank you jackdwalker

**Comment by jackdwalker** [comment]
No problems @BeckGeGe :) I'll close this off for now. If you have any issues further down the road please create a new issue!
