### ISSUE TITLE
Installation issue with docker build

### ISSUE THREAD

**Issue by balin77** [beefproject/beef#1951]
While installing, it gets stuck at building the docker image: docker build -t beef

When it gets to Installing eventmachin 1.2.7 the process suddenly stops. I could not get it working until now.

**Comment by jackdwalker** [comment]
Hi @balin77, could you please provide the console output for your error?

**Comment by jackdwalker** [comment]
Closing due to lack of response and inability to reproduce. If you continue to have similar issues @balin77 please re-open this with steps to reproduce (including information requested in our issue template) or feel free to raise a new issue.
