### ISSUE TITLE
Hello, BeFF settings

### ISSUE THREAD

**Issue by martinssssssss** [beefproject/beef#1954]
Hello, do you know how I can change these URLs permanently for each new visitor
![beefs](https://user-images.githubusercontent.com/66221656/86359951-b262c380-bc3f-11ea-9b75-8fe4b63dbd87.png)

**Comment by bcoles** [comment]
The source code for the modules is in the [modules](https://github.com/beefproject/beef/tree/master/modules) directory.

You can change the custom payload URL in [module.rb](https://github.com/beefproject/beef/blob/master/modules/social_engineering/fake_flash_update/module.rb).

You can also change the image path in module.rb; however, a better approach is to set the appropriate `public_host` and `public_port` in the beef `config.yaml` file.

**Comment by martinssssssss** [comment]
> The source code for the modules is in the [modules](https://github.com/beefproject/beef/tree/master/modules) directory.
> 
> You can change the custom payload URL in [module.rb](https://github.com/beefproject/beef/blob/master/modules/social_engineering/fake_flash_update/module.rb).
> 
> You can also change the image path in `module.rb`; however, a better approach is to set the appropriate `beef.http.public` and `beef.http.public_port` in the beef `config.yaml` file.

Thank you now is better

**Comment by martinssssssss** [comment]
btw, did you see my last issue "beef and facebook"?

**Comment by bcoles** [comment]
> 
> 
> btw, did you see my last issue "beef and facebook"?

Yes I'll reply there.
