### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by risottonero2** [beefproject/beef#1955]
I'm using the latest version of Beef.
My OS is Parrot Security OS.

It's the first time that I use your tool, and unfortunately I have encountered a problem: "Internal server error".
This happens as soon as I click on the Basic Demo Page.
I know well that the error is not given by some action of mine, I just wanted to know if you have predictions on when you will be able to get your server back online in a functional way.
Forgive the trouble, thanks for the assistance, and have a nice day!

**Comment by bcoles** [comment]
I presume you're using the BeEF package on parrot OS (rather than cloning from the git repo).

What errors do you get in terminal? What logs do you get?

`tail ~/.beef/beef.log`

`journalctl -u beef-xss`

Also, try running BeEF with `debug: true` set in the `config.yaml` configuration file. This will generate debug info useful to identify the issue.

**Comment by risottonero2** [comment]
> Presumo che tu stia usando il pacchetto BeEF su parrot OS (piuttosto che clonare dal repository git).
> 
> Quali errori vengono visualizzati nel terminale? Quali registri ricevi?
> 
> `tail ~/.beef/beef.log`
> 
> `journalctl -u beef-xss`
> 
> Inoltre, prova a eseguire BeEF con `debug: true`set nel `config.yaml`file di configurazione. Ciò genererà informazioni di debug utili per identificare il problema.

That's right, I use the pre-installed version of the tool, but if it seems better, I can still proceed with the git clone link. Tell me what would be better.
Anyway: no, to be honest I am not given anything strange, this server problem is not accompanied by anything else.
Also, forgive me for my eventual inexperience, but it's the very first time I use Beef.

**Comment by jackdwalker** [comment]
Using either the pre-installed `beef-xss` version of the tool or the Github release is fine. 


@risottonero2 - could you please follow the steps detailed by bcoles above and let us know what output you get in your console? That will help us identify the issue that is causing your error.

**Comment by jackdwalker** [comment]
The Github source is not currently compatible with ParrotOS due to a package issue on their end. See #1948 

Please continue to use the `beef-xss` package while on ParrotOS.

**Comment by jackdwalker** [comment]
Closing due to lack of response. If you continue to have similar issues @risottonero2 please re-open this or feel free to raise a new issue.
