### ISSUE TITLE
Filed to Execute Default Browser

### ISSUE THREAD

**Issue by khalidalwalid** [beefproject/beef#1959]
Do you guys know what the solution of this problem is?
![Screenshot 2020-07-06 02:31:43](https://user-images.githubusercontent.com/33023197/86563515-82af0680-bf32-11ea-92a5-153659c05da3.png)
I think everythings gonna work properly..
![beefp](https://user-images.githubusercontent.com/33023197/86563861-2b5d6600-bf33-11ea-82c5-dbe88f308474.png)

**Comment by bcoles** [comment]
> Do you guys know what the solution of this problem is?

The `beef-xss` service on various OS (Kali/Parrot/BackBox/etc) will automatically launch the browser after starting the service.

This is an issue with `beef-xss` as packaged on various distros and relates to the distro configuration.

Presuming that the BeEF server starts correctly, you can simply open a web browser and navigate to the web UI manually (using the `opening web UI` link printed to console). If the BeEF server isn't starting, then there's something else going on.

If I were to hazard a guess, without bothering to look at the service configuration, maybe it has issues with `xdg-open` failing to detect/launch the appropriate browser.

**Comment by khalidalwalid** [comment]
![thx](https://user-images.githubusercontent.com/33023197/86565578-146c4300-bf36-11ea-8c9d-c7e53373bb31.png)
okey, thx very much bro! helpful!

**Comment by jackdwalker** [comment]
@khalidalwalid - closing this off now as it seems your issue is solved.

**Comment by khalidalwalid** [comment]
> > Do you guys know what the solution of this problem is?
> 
> The `beef-xss` service on various OS (Kali/Parrot/BackBox/etc) will automatically launch the browser after starting the service.
> 
> This is an issue with `beef-xss` as packaged on various distros and relates to the distro configuration.
> 
> Presuming that the BeEF server starts correctly, you can simply open a web browser and navigate to the web UI manually (using the `opening web UI` link printed to console). If the BeEF server isn't starting, then there's something else going on.
> 
> If I were to hazard a guess, without bothering to look at the service configuration, maybe it has issues with `xdg-open` failing to detect/launch the appropriate browser.

where is the source code location to launch default browser in beef, then? Maybe I can fix it by myself. 
sorry if it's a dumb question..

**Comment by bcoles** [comment]
> 
> 
> > > Do you guys know what the solution of this problem is?
> > 
> > 
> > The `beef-xss` service on various OS (Kali/Parrot/BackBox/etc) will automatically launch the browser after starting the service.
> > This is an issue with `beef-xss` as packaged on various distros and relates to the distro configuration.
> > Presuming that the BeEF server starts correctly, you can simply open a web browser and navigate to the web UI manually (using the `opening web UI` link printed to console). If the BeEF server isn't starting, then there's something else going on.
> > If I were to hazard a guess, without bothering to look at the service configuration, maybe it has issues with `xdg-open` failing to detect/launch the appropriate browser.
> 
> where is the source code location to launch default browser in beef, then? Maybe I can fix it by myself.
> sorry if it's a dumb question..

BeEF does not start a web browser. The `beef-xss` service on various OS (Kali/Parrot/BackBox/etc) will automatically launch the browser after starting the service. I suggest reviewing the `beef-xss` Systemd service.
