### ISSUE TITLE
Cannot hook any browsers except firefox

### ISSUE THREAD

**Issue by pinkbat1** [beefproject/beef#1964]
## Summary
Cannot hook any browsers except firefox. 

What version/revision of BeEF are you using?
0.5.0.0-alpha-pre

On what version of Ruby?
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]

On what browser?
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

On what operating system?
Kali Linux kali 5.5.0-kali1-amd64 #1 SMP Debian 5.5.13-2kali1 (2020-04-03) x86_64 GNU/Linux

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:** No. 

**Q:** Have you enabled or disabled any BeEF extensions?
**A:** No. 

## Expected vs. Actual Behaviour
Javascript error:

Uncaught TypeError: Cannot read property 'grep' of undefined
    at unique (hook.js:9135)
    at Object.getPlugins (hook.js:9157)
    at Object.getDetails (hook.js:9420)
    at Object.browser_details (hook.js:12196)
    at beef_init (hook.js:12786)
    at window.onload (hook.js:12738)

**Comment by bcoles** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/434827/87016276-d6ab3b00-c211-11ea-8ba4-b1ee99271ff3.png)

**Comment by jackdwalker** [comment]
Might be best to just rollback the Array.prototype.unique vaporisation and work on a new solution from there. I'll sort it now.

**Comment by jackdwalker** [comment]
PR up. I'll merge it across once the tests pass. Will work on a new solution the next time I get a chance.

**Comment by jackdwalker** [comment]
Hi @pinkbat1 - this issue should have been solved with #1996. Could you pull from master and confirm you no longer have this issue?

**Comment by pinkbat1** [comment]
Hi, yes that fixed it.
