### ISSUE TITLE
Beef on Raspberry - Raspbian

### ISSUE THREAD

**Issue by f1se4** [beefproject/beef#1976]
Perhaps it's silly thing but it could help someone with the same issue.

# Error with package installation gcc9 using Rpi 3b+ and raspbian
You get an error executing install script from beef, about gcc9 packages that are not found.

# Solution
You need at first to follow this steps but be careful, installing gcc9 not 10
https://solarianprogrammer.com/2017/12/08/raspberry-pi-raspbian-install-gcc-compile-cpp-17-programs/

Then, you will need to edit 'install' file and find where is using apt-get to install gcc9 and clear dev and lib packages.

That's all, beef will be on your RPi without problems 👍

Thank you! 

 
Sergi García

**Comment by bcoles** [comment]
Nice

**Comment by jcrew99** [comment]
@f1se4  Did this install as Kali in the installer file?

so did you remove gcc-9-base libgcc-9-dev from the install file line and followed https://solarianprogrammer.com/2017/12/08/raspberry-pi-raspbian-install-gcc-compile-cpp-17-programs/
(withh gcc 9 ) and it worked fine?

as taken from this repo git clone https://bitbucket.org/sol_prog/raspberry-pi-gcc-binary.git ?

**Comment by f1se4** [comment]
@jcrew99 Yes.

Context: Rapsberry Pi 3b+ with raspbian. Well in Kali (in the last version) you only need to apt-get install bla bla XDDD

Here, I have no tested with gcc 10 compiler because when looking to install file from beef I see that apt-get install in this file was using version 9 could it be possible that compilation/installation works with 10, but i always prefer to use original installer versions.

And yes, i git clone gcc binary, then follow steps (with gcc9) linked standard files and when checked that i have gcc9 working on rpbi then execute beef installation.

Thank you!!!

**Comment by wheatley** [comment]
@f1se4 thanks for the information, I've add this to our FAQ section for reference if someone has another issue similar to the issue you faced.

https://github.com/beefproject/beef/wiki/FAQ#installation-of-beef-on-raspbian
