### ISSUE TITLE
beef tunneling isn't working 

### ISSUE THREAD

**Issue by casp3r0x0** [beefproject/beef#1988]
my kalilinux  machine  ip is :  192.168.100.30 
I have  been  hocked the 192.168.100.8 browser  
now  I can use the  victim browser as  proxy right ?  
I press the  use as  proxy  button 
and  go to  my browser  and set the proxy settings with  127.0.0.1:6789
When I want to navigate the router  page settings  of the hocked victim I type  
192.168.100.1 to access the  admin panel of  the router  
but beef dosn't even tunneling the traffic  and  the site which is  (192.198.100.1) it's loading  for ever with no response 
what I should do  ?

**Comment by bcoles** [comment]
You're attempting to access a page cross-origin. This is blocked by the Same Origin Policy (SOP).

if you take a look at the browser development console in the hooked browser you may see a CORS error in the console, or you may see a request in the network tab.

The response from the proxy will say something to the effect of "cross-origin request. the request has been sent but it is impossible to view the response"

**Comment by Casp3r0x1** [comment]
is  there  a way  that  I can  navigate a web site through a hocked browser ?

**Comment by bcoles** [comment]
> 
> 
> is there a way that I can navigate a web site through a hocked browser ?

You can send requests but can't see the response.

The Proxy/Requester may or may not support CORS - I don't remember - this would allow bidirectional communications if the destination origin permitted requests from the source origin (hooked origin).

**Comment by wheatley** [comment]
Making stale due to inactivity.

**Comment by wheatley** [comment]
Closed due to inactivity.
@casp3r0x0 please reopen if your are still requiring help.
