### ISSUE TITLE
Location of templates

### ISSUE THREAD

**Issue by paulo92921** [beefproject/beef#1990]
Where is located the template folder for the **Facebook** and **Gmail** page? i want to change the layout of these pages.

**Comment by bcoles** [comment]
The Facebook template is part of the Pretty Theft module. The code is here:

https://github.com/beefproject/beef/blob/master/modules/social_engineering/pretty_theft/command.js

The Gmail template is part of the Gmail Phishing module. The code is here:

https://github.com/beefproject/beef/blob/master/modules/social_engineering/gmail_phishing/command.js

**Comment by jcrew99** [comment]
@paulo92921 does that answer your question?
