### ISSUE TITLE
ARE Rules executing, but not getting much info returned

### ISSUE THREAD

**Issue by grunkle97** [beefproject/beef#1995]
## Summary

**Q:** Please provide a brief summary of the issue that you experienced.
**A:** I have these autorun rules in the enabled folder, all of them are default rules: confirm_close_tab.json, get_cookie.json, lan_cors_scan.json, lan_cors_scan_common.json, lan_fingerprint.json, lan_fingerprint_common.json, lan_flash_scan.json, lan_http_scan.json, lan_http_scan_common.json, lan_ping_sweep.json, lan_port_scan.json, and man_in_the_browser.json

When I start beef, all the autorun rules properly load and parse. I'm running beef using ngrok and BeeFOverWan, I can successfully hook my target, a Windows 7 laptop, using the hook link, and all the autorun rules execute properly once the target browser is hooked. However, the only information that is returned is the ipv6 and the geolocation, no cookies or anything else for that matter is returned, and none of the persistence rules seem to work either. I've tried testing it with four different browsers on the target machine, and every time the browser hooks and the ARE rules properly execute, but I get the same result with all of them. I've tried extensively to figure out what the problem could be. Please let me know if you need any info.

## Environment

1. **BeEF Version:** '0.5.0.0-alpha-pre'

2. **Ruby Version:** ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [i386-linux-gnu]

3. **Browser Details (e.g. Chrome v81.0):** Firefox 68.2.0esr (32-bit) 

4. **Operating System (e.g. OSX Catalina):** 
My laptop is running OSX Catalina 10.15.4, Kali is running on Virtual Box, top of VB window says "Kali Rolling (2019.4) x86"
lsb_release -a on the kali machine returned this:
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2020.3
Codename:	kali-rolling

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:** Other than changing the default password, not that I can remember

**Q:** Have you enabled or disabled any BeEF extensions?
**A:** Yes, Metasploit

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
Autorun rules should return information for enabled rules, and persistence modules should work.

**Actual Behaviour:**
Only the ipv6 and geolocation are being returned, and none of the persistence modules are working.

**Comment by wheatley** [comment]
Please reopen if this issue is still currently happening
