### ISSUE TITLE
How to write my own ARE rules?

### ISSUE THREAD

**Issue by grunkle97** [beefproject/beef#1998]
I've scoured the docs for a tutorial on writing my own ARE rules, but all I could find was tutorials for writing your own modules, extensions, etc. Maybe I just missed it? Is there a tutorial, or some basic guidance on how to write your own ARE rule?

**Comment by bcoles** [comment]
The wiki and existing ARE rules are a good place to start:

* https://github.com/beefproject/beef/wiki/Autorun-Rule-Engine
* https://github.com/beefproject/beef/tree/master/arerules

**Comment by jcrew99** [comment]
@grunkle97 Any luck with going through the documentation? let us know if you have questions.

**Comment by jcrew99** [comment]
closing due to lack of response
