### ISSUE TITLE
Re-execute command

### ISSUE THREAD

**Issue by thepipe99** [beefproject/beef#2007]
Hello everyone. Whenever i try to run any command/attack on a hooked target, all i get is "re execute command" in the ui pannel for eevery command, the target is a mac os working with google chrome. Im working in kali linux 2020.3 and i have beef 0.0.5.0.

anyone?

**Comment by bcoles** [comment]
Setting `debug: true` in `config.yaml` will reveal more useful output.

"Re-execute command" appears at the bottom of the tab. The output from the command should appear between the module list tree and the module options. It is unlikely that all modules will fail. Unless something has gone horribly wrong you should get output for most modules.

**Comment by thepipe99** [comment]
> Setting `debug: true` in `config.yaml` will reveal more useful output.
> 
> "Re-execute command" appears at the bottom of the tab. The output from the command should appear between the module list tree and the module options. It is unlikely that all modules will fail. Unless something has gone horribly wrong you should get output for most modules.

thanks! the debug thing helpeed. sorry for the trouble.
