### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by HyperFlame1324** [beefproject/beef#2012]
I forgot my password to Beef and I don't know how to reset it.

**Comment by slimwang** [comment]
check the `config.yaml` file in your beef directory.

**Comment by jcrew99** [comment]
@HyperFlame1324  It will be in the root beef directory in the ``config.yaml``.
Read the credentials section here: https://github.com/beefproject/beef/wiki/Configuration

**Comment by jcrew99** [comment]
I am going to close this issue as completed
