### ISSUE TITLE
nodejs : Depends: python-minimal but it is not installable

### ISSUE THREAD

**Issue by InfoSecMalang** [beefproject/beef#2016]
Trying to install beef-xss from kali repositries apt install beef-xss but getting this error:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Depends: python-minimal but it is not installable
E: Unable to correct problems, you have held broken packages.`

Already have python2-minimal and python3-minimal installed.

This happen after updating kali to the latest release with python3 as default python.

Any suggestions.

**Comment by bcoles** [comment]
A Kali package issue. BeEF depends on `nodejs` for the Autorun Rule Engine (maybe also the minifying and evasion). Presumably the Kali package maintainers have selected `nodejs` as a dependency for BeEF, which makes sense.

For some reason, `nodejs` relies upon `python-minimal`.

As per the error message, `python-minimal` is not installable. You have broken packages.

You could try installing `nodejs` first. If you can't `apt-get install nodejs` then this is an issue with Kali's `nodejs` package.

Some googling suggests that `python2` is required.

For what its worth, nodejs installed fine on my system. Not that that's what you want to hear. But that makes sense - I have Python2 (and Python3) installed.

**Comment by InfoSecMalang** [comment]
Thanks for the response, 

This is very strange. I also have python2 and python3 installed (python3 as default python) along with python2-minimal and python3-minimal but there is no installation candidate for python-minimal.

Also, when i tried to install install `apt install nodejs` i got exact same error of unmet dependencies.

![image](https://user-images.githubusercontent.com/6963584/99913974-a0ee8680-2cc8-11eb-841f-62115578e9ac.png)

Thanks for looking into it though, i will try installing node with out apt install nodejs.

**Comment by InfoSecMalang** [comment]
FIXED!!

Thanks @bcoles! your reply greatly helped.

So, the problem was i had "nodesource.list" sitting in my /etc/apt/sources.d/ with apt sources for ubuntu jessie, i probably put it there year ago while i was fixing something.

Remove nodesource.list from /etc/apt/sources.d/ and then `apt update`  `apt install nodejs` `apt install beef-xs` worked like a charm.

Thanks again!

**Comment by brutalgg** [comment]
That nodesources.list file is created when you are using one of the bash scripts available for nodejs install. I had the same jessie repos added after running the install just today using the node_14.x script. The default nodejs in kali is currently 12 which may not work for all use cases. Currently trying to determine if python-minimal was removed from kali repos or maybe additional an additional repo needs to be added to support the nodejs official installation path.

Just thought I'd share.

**Comment by stracker-phil** [comment]
Thanks for sharing the solution! On my system, the relevant commands were:

```lang-shell
sudo rm /etc/apt/sources.list.d/nodesource.*
sudo apt update
sudo apt install nodejs
```

**Comment by DeezyE** [comment]
Thanks for sharing your solution @stracker-phil 
Are you interested in working on the development of beef? beef@bindshell.net if you'd like an invite to the dev discord.
Cheers

**Comment by hiteshi-infotech-new** [comment]
> FIXED!!
> 
> Thanks @bcoles! your reply greatly helped.
> 
> So, the problem was i had "nodesource.list" sitting in my /etc/apt/sources.d/ with apt sources for ubuntu jessie, i probably put it there year ago while i was fixing something.
> 
> Remove nodesource.list from /etc/apt/sources.d/ and then `apt update` `apt install nodejs` `apt install beef-xs` worked like a charm.
> 
> Thanks again!

Its worked for me.Thanks

**Comment by SyedSaifAliAlvi** [comment]
> Thanks for sharing the solution! On my system, the relevant commands were:
> 
> ```
> sudo rm /etc/apt/sources.list.d/nodesource.*
> sudo apt update
> sudo apt install nodejs
> ```

It worked,
Thanks a lot !
