### ISSUE TITLE
How can i solve this proplem to run beef 

### ISSUE THREAD

**Issue by Mina93-min** [beefproject/beef#2031]
> Executing ??sudo beef-xss??
[sudo] password for kali: 
[i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1...

**Comment by bcoles** [comment]
Kali uses sytemd by default. Your systemd is broken.

**Comment by Mina93-min** [comment]
How can i solve it

**Comment by bcoles** [comment]
Fix your systemd so you can run services such as the `beef-xss` service.

Or clone BeEF from the GitHub repository and run it with `./beef`.

**Comment by abel432** [comment]
sudo apt-get install tor-geoipdb

**Comment by abel432** [comment]
sudo apt-get install tor-geoipdb

**Comment by popoe** [comment]
Hello, I have the same issue. I tried to git clone BeEF, however it wouldn't download me some of the files. Whenever I start BeEF this pops up: 
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1...
I have no idea how to fix my systemd, so please help.

**Comment by bcoles** [comment]
BeEF doesn't use systemd.

The `beef-xss` package and associated service on some distributions (Kali, Parrot, etc) use systemd. If you've broken your systemd installation then that isn't something we can help you with.

Alternatively, you can clone and use BeEF from the GitHub repository.

**Comment by hjs595975** [comment]
i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

● beef-xss.service - beef-xss
     Loaded: loaded (/lib/systemd/system/beef-xss.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2021-09-09 16:58:04 KST; 4s ago
    Process: 18916 ExecStart=/usr/share/beef-xss/beef (code=exited, status=1/FAILURE)
   Main PID: 18916 (code=exited, status=1/FAILURE)
        CPU: 986ms

 9월 09 16:58:04 kali beef[18916]: [16:58:04]    |   Site: https://beefproject.com
 9월 09 16:58:04 kali beef[18916]: [16:58:04]    |   Blog: http://blog.beefproject.com
 9월 09 16:58:04 kali beef[18916]: [16:58:04]    |_  Wiki: https://github.com/beefproject/beef/wiki
 9월 09 16:58:04 kali beef[18916]: [16:58:04][*] Project Creator: Wade Alcorn (@WadeAlcorn)
 9월 09 16:58:04 kali beef[18916]: [16:58:04][*] Connecting to Metasploit on 192.168.35.216:55552
 9월 09 16:58:04 kali beef[18916]: [16:58:04][!] [Metasploit] RPC call to 'auth.login' failed: Failed to open TCP connection to 192…port 55552)
 9월 09 16:58:04 kali beef[18916]: [16:58:04][!] ["/usr/share/rubygems-integration/all/gems/msfrpc-client-1.1.2/lib/msfrpc-client/client.rb:26…
 9월 09 16:58:04 kali beef[18916]: [16:58:04][!] API Fire Error: Authentication failed in {:owner=>BeEF::Extension::Metasploit::API…soft_load()
 9월 09 16:58:04 kali systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
 9월 09 16:58:04 kali systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1...

**Comment by bcoles** [comment]
> how can solve this problem

Disable the Metasploit extension in `config.yaml` if you aren't using it.

**Comment by hjs595975** [comment]
> > how can solve this problem
> 
> Disable the Metasploit extension in `config.yaml` if you aren't using it.

How can i config.yml true for metasploit
