### ISSUE TITLE
Ho to solve this proplem to open beef

### ISSUE THREAD

**Issue by Mina93-min** [beefproject/beef#2032]
> Executing ??sudo beef-xss??
[sudo] password for kali: 
[i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1...

**Comment by bcoles** [comment]
Dupe of #2031

**Comment by Starzzzxc** [comment]
nothing happens after that for me
