### ISSUE TITLE
How to add intermediate SSL certificate

### ISSUE THREAD

**Issue by XianShuKhi** [beefproject/beef#2034]
How to add intermediate SSL certificate to configuration? W/o this cert I'm getting SSL-related error in any browser and in console I have this: 

140421796149056:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1528:SSL alert number 46

SSL certificate issued by ZeroSSL and has 3 files:
certificate -> added to beef_cert.pem
private.key -> added to beef_key.pem
ca_bundle - where it should be added?

**Comment by andysnotamintt** [comment]
I SECOND this question................I cant seem to figure out how to setup a paid SSL to work? I dont think In understand enough about how SSLs even functions...

**Comment by wheatley** [comment]
@XianShuKhi & @andysnotamintt thanks for submitted, I understand it has been sometime since you've posted this issue but we were wondering if you still required some help?

**Comment by wheatley** [comment]
Closing due to not activity.
