### ISSUE TITLE
the way that beef bypass pop up blockers

### ISSUE THREAD

**Issue by jason-matison** [beefproject/beef#2037]
in commands > social engineering > fake notification bar beef does bypass browser's pop up blocker
where could i find the code that beef  uses for bypassing the browsers pop up blocker?

**Comment by bcoles** [comment]
> 
> 
> in commands > social engineering > fake notification bar beef does bypass browser's pop up blocker
> where could i find the code that beef uses for bypassing the browsers pop up blocker?

The fake notification bar modules do not bypass popup blockers. They simply display a notification at the top of the window.

Modern browsers prevent popups. However, BeEF does have a simple technique to bypass this.

Modern browsers still allow popups in response to mouse click events. Take a look at the `persistence/popunder_window` module.

![Create Pop Under](https://user-images.githubusercontent.com/434827/103745187-25b41a80-5053-11eb-8658-526c5e236efd.png)

When the `clickjack` option is selected, this module adds a click event handler which will spawn a window whenever the mouse is clicked within the window.

https://github.com/beefproject/beef/blob/49478370d8dac015aadc6a564817d881720fec59/modules/persistence/popunder_window/command.js#L33-L46

**Comment by sislight224** [comment]
I want to discuss more detail this project.
