### ISSUE TITLE
Rename veganLol function

### ISSUE THREAD

**Issue by joshuaaguilar20** [beefproject/beef#2040]
https://github.com/beefproject/beef/blob/49478370d8dac015aadc6a564817d881720fec59/core/main/client/browser/cookie.js#L75

Just curious what this function was for ? also may want to consider a rename as it appears it does not fit the code pattern as well.

**Comment by bcoles** [comment]
> Just curious what this function was for ? also may want to consider a rename as it appears it does not fit the code pattern as well.

Once upon a time there was some software (a browser extension?) called Vegan which attempted to detect BeEF hooks. It did so by detecting the format of the cookie. `veganLol` was added to defeat the detection.

I agree, the function should be renamed.

**Comment by ImKool-Gitch** [comment]
oooooh i get it hahahhaha

**Comment by DeezyE** [comment]
Is this even relevant anymore?

**Comment by bcoles** [comment]
> 
> 
> Is this even relevant anymore?

Yes.

https://github.com/beefproject/beef/blob/694df4c17b73c963d20923cab73bb615d32255f9/core/main/client/browser/cookie.js#L740-L100

**Comment by DeezyE** [comment]
sorry I mean the extension was last updated in 2018 - seems incredibly niche?

**Comment by bcoles** [comment]
> 
> 
> sorry I mean the extension was last updated in 2018 - seems incredibly niche?

The exact implementation is petty and poorly named, but the underlying idea is sound. Cookie names should feature some randomness to thwart simple detection.

I believe this function is used by default, in which case we've always been using it and should consider it "safe". If it is not currently used then it can be removed.

If we keep it, the function should be renamed. The function should also be investigated further for areas of improvement - it was a quick hack.

**Comment by DeezyE** [comment]
ah right. Sounds fair, so something more generic like 'cookieRandomizer' to reflect it's function?

**Comment by bcoles** [comment]
> 
> 
> ah right. Sounds fair, so something more generic like 'cookieRandomizer' to reflect it's function?

If that's what the function does, and the existing function and implementation are reasonable, then yes.

**Comment by zinduolis** [comment]
The `veganLol` function generates a random alphanumeric string with a length between 17 and 25 characters. The string is composed of uppercase letters (A-Z) and lowercase letters (a-z), but it explicitly excludes certain special characters like semicolons (`;`) and equal signs (`=`), replacing them with the character `'x'` to ensure the generated string remains valid in contexts such as cookies or URL parameters. The function calculates the string length randomly within the specified range and uses the `grunt` helper function to generate each character based on a random number, ensuring the output string conforms to the desired alphanumeric format.

Then it's used to set cookie value: `this.setCookie( name, beef.browser.cookie.veganLol(), '', '/', '', '' );`

Finally, this is captured in jsdocs. 

Hence, the above new name suggestion by @DeezyE sounds reasonable. 

With a slight tweak and seeing that most of the words in the code follow American english, I'll rename it to 'cookieValueRandomizer'. Then I'll fix up the code and documentation.

**Comment by zinduolis** [comment]
Fix has been implemented.
