### ISSUE TITLE
vim config.ya*** stack smashing detected ***: <unknown> terminated

### ISSUE THREAD

**Issue by uemahra** [beefproject/beef#2043]
# Submit Issue

Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).

Please do your best to provide as much information as possible. It will help substantially if you can enable and provide debugging logs with your issue. Instructions for enabling debugging logs are below:

1. In the `config.yaml` file of your BeEF root folder set debug and client_debug (lines 11 & 13 respectively) to `true`
   * If using a standard installation of `beef-xss` the root folder will typicaly be `/usr/share/beef-xss`
2. Reproduce your error
3. Retrieve your client-side logs from your browser's developer console (Ctrl + Shift + I)
4. Retrieve your server-side logs from `~/.beef/beef.log`
5. **If using `beef-xss`:** Retrieve your service logs using `journalctl -u beef-xss`

Thank you, this will greatly aid us in identifying the root cause of your issue :)

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**
Feel free to open it back up if you continue to have issues. 

## Summary

**Q:** Please provide a brief summary of the issue that you experienced.
**A:**

## Environment

*Please identify the environment in which your issue occurred.*

all latest

I just cloned beef from github and finished install with the install script, I try to launch beef, it returns [!] ERROR: Default username and password in use!
[10:22:48]    |_  Change the beef.credentials.passwd in config.yaml
Then I try to use vim to change config.yaml's content, but when I try to use TAB to complete config.yaml's file name, console pop up a error:
root@iPhone:~/beef# vim con*** stack smashing detected ***: <unknown> terminated
*** stack smashing detected ***: <unknown> terminated

root@iPhone:~/beef#
root@iPhone:~/beef# vim con*** stack smashing detected ***: <unknown> terminated
*** stack smashing detected ***: <unknown> terminated

root@iPhone:~/beef# ps -ef|grep beef
root        6931     979  0 10:23 pts/0    00:00:00 grep beef
root@iPhone:~/beef# vim config.ya*** stack smashing detected ***: <unknown> terminated
*** stack smashing detected ***: <unknown> terminated
Before install beef, vim works all fine, have you faced same problem?

**Comment by bcoles** [comment]
> Then I try to use vim to change config.yaml's content, but when I try to use TAB to complete config.yaml's file name, console pop up a error:

Unusual. Can you open other files with vim? This doesn't seem like an issue with BeEF.

The `install` script isn't meant for use on an iPhone. I'm not sure why vim would have broken. The installer installs a few operating system packages and Ruby gems.

**Comment by uemahra** [comment]
it's not an iPhone, it's a kali linux, I changed it's hostname. After reboot, vim don't report that error again, strange, cause I only did beef install and nothing else, maybe rack-protection did this? I don't know, I just found out my bettercap works wrong too...TBC

**Comment by bcoles** [comment]
> 
> 
> it's not an iPhone, it's a kali linux, I changed it's hostname. After reboot, vim don't report that error again, strange, cause I only did beef install and nothing else, maybe rack-protection did this? I don't know, I just found out my bettercap works wrong too...TBC

Bettercap (ruby) or Bettercap NG (Go) ? Perhaps its a Ruby issue, perhaps caused by one of the Ruby gems.

**Comment by uemahra** [comment]
I used Bettercap Go, I reinstalled bettercap library, and I found some of them has been removed, after the apt install, it works all fine now

**Comment by bcoles** [comment]
> 
> 
> I used Bettercap Go, I reinstalled bettercap library, and I found some of them has been removed, after the apt install, it works all fine now

Strange. Either way, not an issue with BeEF. Closing.
