### ISSUE TITLE
Zombies not deleting.

### ISSUE THREAD

**Issue by Do0ks** [beefproject/beef#2044]
when right clicking on the hooked IPs, both online and offline then clicking delete zombie, nothing happens.

**Comment by bcoles** [comment]
Are you using the latest version of BeEF?

Works fine here on the latest version from `master` ...

Also, if the zombie is still online, and polls back to the BeEF server, the zombie will be recreated in the UI.

**Comment by bcoles** [comment]
It appears there is a bug when trying to delete offline browsers. The UI fails to retrieve the zombie id.

![image](https://user-images.githubusercontent.com/434827/104212295-28ff3a00-5489-11eb-8719-f90d17443ac1.png)

**Comment by KaTodorov** [comment]
The bug appears when you use the left side bar to delete a zombie. When you log in into the ui panel, go to "Zombies" tab , and delete it from there.

**Comment by Do0ks** [comment]
> Are you using the latest version of BeEF?
> 
> Works fine here on the latest version from `master` ...
> 
> Also, if the zombie is still online, and polls back to the BeEF server, the zombie will be recreated in the UI.

Yes, latest version. The only way I can get it to delete is manually going into the database files and deleting that way. I also believe none of the right click options work either. After testing, then referencing the database it doesn't appear to make any changes.

**Comment by Do0ks** [comment]
> The bug appears when you use the left side bar to delete a zombie. When you log in into the ui panel, go to "Zombies" tab , and delete it from there.

Unfortunately,  it doesn't delete from that section either. The only way I can get it to delete is through the database.

**Comment by bcoles** [comment]
@wheatley this bug should be easy to fix if you're interested.

**Comment by wheatley** [comment]
@Do0ks & @KalinTodorov this issues as now be resolved in the latest release.

https://github.com/beefproject/beef/releases/tag/v0.5.2.0

Please update your beef repo and let us know if this is still an issue.
