### ISSUE TITLE
Unable to change the website to which Google Phishing attack in Social Engineering section leads to

### ISSUE THREAD

**Issue by P-arag** [beefproject/beef#2055]
While doing google phishing in BeEF, after clicking the Sign In button, it leads me to https://accounts.google.com/ServiceLoginAuth which no longer exists
How can I change the url????

I am running Parrot OS and firefox

PS: I don't know which file to edit, I am kinda new to this :neutral_face:

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/blob/845b2db2555082e6a645160a2a7ed807df063b03/modules/social_engineering/gmail_phishing/command.js#L37

**Comment by P-arag** [comment]
Thanks, it worked!!!!
