### ISSUE TITLE
login issue with ngrok

### ISSUE THREAD

**Issue by truesamurai** [beefproject/beef#2062]
# Submit Issue

Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).

Please do your best to provide as much information as possible. It will help substantially if you can enable and provide debugging logs with your issue. Instructions for enabling debugging logs are below:

1. In the `config.yaml` file of your BeEF root folder set debug and client_debug (lines 11 & 13 respectively) to `true`
   * If using a standard installation of `beef-xss` the root folder will typicaly be `/usr/share/beef-xss`
2. Reproduce your error
3. Retrieve your client-side logs from your browser's developer console (Ctrl + Shift + I)
4. Retrieve your server-side logs from `~/.beef/beef.log`
5. **If using `beef-xss`:** Retrieve your service logs using `journalctl -u beef-xss`

Thank you, this will greatly aid us in identifying the root cause of your issue :)

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**
Feel free to open it back up if you continue to have issues. 

## Summary

**Q:** Please provide a brief summary of the issue that you experienced.
**A:**

When I login in my local network 127.0.0.1/ui/panel then I can login with my details as specified in config.yaml. No issues on local network.

When I use ngrok and login in xxxxxx.ngrok.io:80/ui/panel  then I get an error about wrong credentials. But they are correct for sure.

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:** 
2. 0.5.0.0-alpha-pre

2. **Ruby Version:**
2.7.2p137

3. **Browser Details (e.g. Chrome v81.0):**
4. Firefox

4. **Operating System (e.g. OSX Catalina):**
Kali Linux

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:**
changed login credentials 
+
public: "xxxxxxxx.ngrok.io"    # public hostname/IP address
public_port: "80"                     # public port (experimental) 

**Q:** Have you enabled or disabled any BeEF extensions?
**A:**
no

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
<br />

login without issue

**Actual Behaviour:**
<br />

wrong login credentials error

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1. activate ngrok
2. make necessary changes in config.yaml
3. go to xxxx.ngrok.ui.panel and try to login

## Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be retrieved by following the instructions towards the top of the issue template.

**Comment by sh1va73** [comment]
Edit: when I try with Beef-over-wan then my login is succesfull. But when I try only with beef+ngrok then I can not login.

**Comment by bcoles** [comment]
It looks like you're using ngrok. This may help:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

Be aware that there's an issue #1785 when using HTTPS.

**Comment by wheatley** [comment]
Please see new release with fix 

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by Akashsingha** [comment]
I am also getting this error but i don't understand how to fix it .

Your answers are not helpful😭

**Comment by Akashsingha** [comment]
beef:

    # ...

    http:

        # ...

        public: 
            host: "<ngrok-id>.ngrok.io" # ngrok domain name for forwarding URL
            port: "443"                 # ngrok port for forwarding URL (443 for HTTPS)
            https: true                 # ngrok supports HTTPS by default

This is an example or i should copy this in config.yaml

**Comment by bcoles** [comment]
> I am also getting this error but i don't understand how to fix it .

There is a bug where you cannot login to the admin panel remotely when using ngrok. #2527

You will need to login using one of the network interfaces.

**Comment by Cozmo007** [comment]
what do you mean one of the network interfaces? I didn't understand

**Comment by bcoles** [comment]
> what do you mean one of the network interfaces? I didn't understand

Use any of your system's IP addresses.

**Comment by hackerjimjam** [comment]
> 

this is still useless because it still wont connect over ngrok, the whole point of the ngrok is so youcan put the script in another server and execute the framework cababiloties, not just connect to your localhost machine to hack yourself. it worked once for me everything worked fine i had the script on another sever with the ngrokurl/hook.js then it coinected to my machine and i was able to execute scripts ot my elsewhere hosted website. now i cant and seems no one has an answer either

**Comment by bcoles** [comment]
> this is still useless because it still wont connect over ngrok

Your issue is unrelated.

> the whole point of the ngrok is so youcan put the script in another server and execute the framework cababiloties, not just connect to your localhost machine to hack yourself.

Use the local interface to login, not hook.

> it worked once for me everything worked fine i had the script on another sever with the ngrokurl/hook.js then it coinected to my machine and i was able to execute scripts ot my elsewhere hosted website. now i cant and seems no one has an answer either

Are you using a free account? ngrok has anti-abuse functionality which requires a HTTP header to be set. Requests which do not include this header are rejected.
