### ISSUE TITLE
Why can't hosts on the LAN connect to the local loopback network interface reserved for local network connections (not LAN connections) ?

### ISSUE THREAD

**Issue by ImKool-Gitch** [beefproject/beef#2063]
so when i paste the hook url outside my vm it doesnt work it says refused to connect and
when i do it inside my vm it works
Any idea on how to fix this ?

**Comment by ImKool-Gitch** [comment]
![Uploading Captureasa.PNG…]()

**Comment by ImKool-Gitch** [comment]
![Captureasa](https://user-images.githubusercontent.com/71771827/109419432-b82ac780-79cd-11eb-9c7d-a643bbc1051c.PNG)

**Comment by ImKool-Gitch** [comment]
![Capture56756](https://user-images.githubusercontent.com/71771827/109419441-c0830280-79cd-11eb-8d4b-959b22175db2.PNG)

**Comment by ImKool-Gitch** [comment]
![dxgvfgdf](https://user-images.githubusercontent.com/71771827/109419448-c5e04d00-79cd-11eb-9374-2df03a004a65.PNG)

**Comment by ImKool-Gitch** [comment]
![vbnmcvk;lh](https://user-images.githubusercontent.com/71771827/109419450-caa50100-79cd-11eb-8e1c-52b5c5ee913e.PNG)

**Comment by bcoles** [comment]
`127.0.0.1` is the local loopback network interface.

Try using an IP address for one of your local area network interfaces.

**Comment by ImKool-Gitch** [comment]
ok

**Comment by ImKool-Gitch** [comment]
> `127.0.0.1` is the local loopback network interface.
> 
> Try using an IP address for one of your local area network interfaces.

thank you so much it worked

**Comment by Dhairyapandya007** [comment]
> `127.0.0.1` is the local loopback network interface.
> 
> Try using an IP address for one of your local area network interfaces.

Hey what do you mean by local area network interface I mean which IP do I need to use on my host pc 

Please help

**Comment by Dhairyapandya007** [comment]
> > `127.0.0.1` is the local loopback network interface.
> > Try using an IP address for one of your local area network interfaces.
> 
> thank you so much it worked

Hey I'm facing same issue what should I do ?

**Comment by bcoles** [comment]
> 
> 
> > `127.0.0.1` is the local loopback network interface.
> > Try using an IP address for one of your local area network interfaces.
> 
> Hey what do you mean by local area network interface I mean which IP do I need to use on my host pc
> 
> Please help

Use your LAN IP address.

**Comment by Dhairyapandya007** [comment]
> > > `127.0.0.1` is the local loopback network interface.
> > > Try using an IP address for one of your local area network interfaces.
> > 
> > 
> > Hey what do you mean by local area network interface I mean which IP do I need to use on my host pc
> > Please help
> 
> Use your LAN IP address.

Hey its still not working will you please help me with screenshot I can't find what I am doing wrong

**Comment by bcoles** [comment]
> Hey its still not working will you please help me with screenshot I can't find what I am doing wrong

What are you trying to do?

How did you do it?

What was the expected result?

What happened instead?

**Comment by Dhairyapandya007** [comment]
> > Hey its still not working will you please help me with screenshot I can't find what I am doing wrong
> 
> What are you trying to do?
> 
> How did you do it?
> 
> What was the expected result?
> 
> What happened instead?

this is the exact same error that's coming 
![error](https://user-images.githubusercontent.com/81666449/113325398-fea97400-9335-11eb-8263-7142893d2727.png)

**Comment by Dhairyapandya007** [comment]
> > Hey its still not working will you please help me with screenshot I can't find what I am doing wrong
> 
> What are you trying to do?
> 
> How did you do it?
> 
> What was the expected result?
> 
> What happened instead?

i am trying to use beef on my pc its running in virtual environment but if i try to use the hook link on any other device it shows site can't be reached 

and as you mentioned in the upper thread to use the IP of the LAN so I am using the IP which I get by typing "what's my IP address " on google 

this is the exact same error that's coming 
![error](https://user-images.githubusercontent.com/81666449/113326021-c9515600-9336-11eb-9dc9-96ecd49812e6.png)

**Comment by bcoles** [comment]
There are several things going on here.

> this is the exact same error that's coming

It will never work on another system when you're using `127.0.0.1`. This points to the local loopback network interface on the local system.

> and as you mentioned in the upper thread to use the IP of the LAN so I am using the IP which I get by typing "what's my IP address " on google

The IP address you get from Google is your WAN IP address. That won't work either (unless you've set up port forwarding).

> i am trying to use beef on my pc its running in virtual environment but if i try to use the hook link on any other device it shows site can't be reached

You need to use the IP address of the system running in the virtual environment. On *nix systems you can view the IP address for network interfaces with `ip addr` or `ifconfig`.

This will only work on systems which can route network traffic to the virtual environment.

**Comment by virus696969** [comment]
Hey i dont know why my hook url does not work at all i installed like thousands of things like ngrok and so on but the hokk url leads me to a external error every single timer...does someone know ho to fix it

**Comment by wheatley** [comment]
@bcoles original query as been resolved feel free to close this issue, was in the process of separating the other queries for reference.
