### ISSUE TITLE
Stealing Cookies with BeEF

### ISSUE THREAD

**Issue by moldychez3543** [beefproject/beef#2069]
Is it possible to steal cookies with BeEF? what i mean is when my victim gets hooked, how do i steal all their cookies? Thanks

**Comment by bcoles** [comment]
The cookies are automatically retrieved and stored in the browser details when the browser is hooked. You can see these cookies on the `Details` tab:

![image](https://user-images.githubusercontent.com/434827/110224916-363e1f80-7f34-11eb-9a5f-00594b28968b.png)

You can also retrieve cookies using the `Browser` -> `Hooked Domain` -> `Get Cookie` command module:

https://github.com/beefproject/beef/tree/master/modules/browser/hooked_domain/get_cookie

![image](https://user-images.githubusercontent.com/434827/110224932-5b329280-7f34-11eb-9116-5fa18107db50.png)

**Comment by moldychez3543** [comment]
ok. i see. But if i want to grab someones cookies on another site, like youtube.com or gmail.com or some site like that how would i do this?

**Comment by bcoles** [comment]
> 
> 
> ok. i see. But if i want to grab someones cookies on another site, like youtube.com or gmail.com or some site like that how would i do this?

You need to execute JavaScript code (specifically the BeEF hook JavaScript code) within the context of the other domain. This can be achieved by injecting the hook during a cross-site scripting (XSS) attack or injecting the hook during a man-in-the-middle attack.

**Comment by bcoles** [comment]
> Any how the question is that how hook browser persistence if Client close our Beef Link..?

See the [persistence modules](https://github.com/beefproject/beef/tree/master/modules/persistence).

**Comment by Nonu-Gamez** [comment]
> 

Could you please explain a bit more of how to inject the hook during an XSS attack or injecting the hook during MITM attack? I need some guidance.

**Comment by bcoles** [comment]
> > 
> 
> Could you please explain a bit more of how to inject the hook during an XSS attack or injecting the hook during MITM attack? within the context of the other domain? I need some guidance.

You would insert the BeEF hook into another domain the same way you would insert any other JavaScript resource.
