### ISSUE TITLE
Missing logo in pretty theft command?

### ISSUE THREAD

**Issue by glosnick** [beefproject/beef#2082]
Hi, I was trying to execute the pretty theft command on a hooked machine.   The fake login executes fine but it is missing the relevant icon in the login box.  I've checked and rechecked the path to the logo so I see no reason why it shouldn't work.  Is there any chance you can help?

Regards

Nick

**Comment by bcoles** [comment]
> I've checked and rechecked the path to the logo so I see no reason why it shouldn't work.

Most of the Pretty Theft templates don't usage images.

The `Generic` template lets you specify a URL for an image. There's nothing magic going on here. The URL for the image is just a URL.

**Comment by glosnick** [comment]
I've checked an rechecked too and it just doesn't work for me.

Regards

Nick

**Comment by bcoles** [comment]
> 
> 
> I've checked an rechecked too and it just doesn't work for me.
> 
> Regards
> 
> Nick

What do you mean?

Are you using the Generic template?

**Comment by glosnick** [comment]
Yeah I was using the generic template initially but the beef.png logo didn't appear.  Then I wanted to try a youtube logo so I created one on my local drive and used apache2 to allow access to it but that didn't work either.

Thanks for your help and regards.

Nick

**Comment by bcoles** [comment]
> 
> 
> Yeah I was using the generic template initially but the beef.png logo didn't appear. Then I wanted to try a youtube logo so I created one on my local drive and used apache2 to allow access to it but that didn't work either.
> 
> Thanks for your help and regards.
> 
> Nick

I'm going to need to see screenshots of your config or something. There's no magic here. It's literally a URL in an `<img>` tag.

Are you absolutely certain that you have specified the correct URL? Can the host running the hooked browser route traffic to the host hosting the image? Are they both using HTTPS?

Here's pretty theft using the Generic template with your GitHub avatar.

![image](https://user-images.githubusercontent.com/434827/114363895-33ca8780-9bbc-11eb-9b95-a6fcf4cd9e0c.png)

![image](https://user-images.githubusercontent.com/434827/114363903-35944b00-9bbc-11eb-8901-6d399c0a54be.png)

**Comment by glosnick** [comment]
Thanks for you help.  I almost absolutely certain that the URL is correct.  When I enter it on the target machine the logo opens but not when I execute petty theft.  No they are not both running https.  Is that a problem?  I was using bettercap to downgrade the target machine from https to http.

I'm not entirely sure what you mean by can the hooked browser route traffic to the host hosting the image.  Could you elaborate a little please?

And finally what config would you care to see?

Again thanks for your help and regards

Nick

**Comment by bcoles** [comment]
> No they are not both running https.  Is that a problem?

If the hooked browser is configured to prevent loading of mixed passive content, and the browser is hooked on a page which is using HTTPS, and the image you are trying to load is on HTTP, then the browser will not load the image.

If the web server hosting the image is using HTTPS and you're performing a man-in-the-middle attack to redirect traffic to your own HTTPS server, then the certificate presented by your HTTPS server *must* be valid and trusted by the browser, otherwise the connection will fail.

The quickest and easiest test is to use an image from a known HTTPS web server which you know is routable from the hooked browser host and serves a valid certificate.


> I was using bettercap to downgrade the target machine from https to http.

Eliminate complexity.

If it works when you're not using Bettercap then you have broken something by using Bettercap.

Take a step back and think about what you're doing. If Bettercap is intercepting and proxying all traffic, then the Bettercap host *must* be able to route traffic to the server where the image is hosted if you want the image to load.


> I'm not entirely sure what you mean by can the hooked browser route traffic to the host hosting the image.  Could you elaborate a little please?

If a web browser cannot establish a network route to another host then it cannot establish a HTTP connection to a server listening on that host. If the browser cannot establish a HTTP connection to a web server it cannot request an image from that web server. If the browser cannot request an image it will not be able to load the image. If the browser cannot load an image you will not see the image.


> And finally what config would you care to see?

Are there any errors in the browser console?

What debugging have you performed? Do you see the HTTP request in network traffic? Do you see the network request in the Network tab of the browser development console?

**Comment by glosnick** [comment]
Wow that was a pretty comprehensive response and I really do appreciate it even though it has taken several days for me to get my  head around it and it has melted my head somewhat thinking about it.  I think I begin to understand what the issue is, well sort of but I had a couple of questions regarding your previous response.  What do you mean when you say 'If the hooked browser is configured to prevent loading of mixed passive content'?  What is mixed passive content and how or why would a browser be configured to prevent it's loading?

I tried following your advice and figured out a way to hook the target browser without using bettercap, from my Kali virtual machine I started apache2 and added the command to hook the browser to the index.html file.  I managed to hook the browser in this fashion but noticed that when I navigated to the ip address of the Kali machine that the connection was not secure, even though I did in fact manage to hook the target browser using this method.  So I guess this would imply that there might be some security issue.  How would I add the necessary security certificates to my apache2 on my Kali machine?

Having managed to hook the target browser I attempted to run the fake youtube login in again but noticed that when the login executed there was a box which should have contained the youtube logo but still no logo.  Right clicking on this box I discovered that the link to the picture that fake login was trying to use led to an image that was no longer available, so this is what I presume the problem is.  The link was as follows:

http://www.youtube.com/yt/brand/media/image/yt-brand-standard-logo-630px.png

However, when attempted to change the default url in the beef options for pretty theft it still attempted to load the previously stated URL.  So I changed it to http://10.0.2.4/youtube.png.   I'm not quite sure what it is doing.  Is this a symptom of my security issues or maybe a bug in beef or am I just not doing it properly which is entirely possible?

Finally, I wasn't actually doing any debugging and I'm not entirely sure what you mean by it.  Please could you explain a little further and what software would I need to perform such debugging.

Who knew that trying something as simple as loading a logo could get so complicated, but I really do appreciate the time you have taken to help and respond to a novice such as myself.

One final, final question if I haven't exhausted your patience.  What does 'proxying traffic' mean?

Regards

Nick

**Comment by bcoles** [comment]
> What is mixed passive content and how or why would a browser be configured to prevent it's loading?

* https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content
* https://www.cloudflare.com/learning/ssl/what-is-mixed-content/

**Comment by bcoles** [comment]
> Finally, I wasn't actually doing any debugging and I'm not entirely sure what you mean by it. Please could you explain a little further and what software would I need to perform such debugging.

Practice the scientific method.

In this instance you should start with the browser development tools built into your browser. In particular the developer console.

> I tried following your advice and figured out a way to hook the target browser without using bettercap, from my Kali virtual machine I started apache2 and added the command to hook the browser to the index.html file.

Using the demo page would have been easier.

> However, when attempted to change the default url in the beef options for pretty theft it still attempted to load the previously stated URL. So I changed it to http://10.0.2.4/youtube.png. I'm not quite sure what it is doing. Is this a symptom of my security issues or maybe a bug in beef or am I just not doing it properly which is entirely possible?

Use the browser development tools to find out what your browser is doing.

> Who knew that trying something as simple as loading a logo could get so complicated

You brought this on yourself when you decided to layer complexity without testing that any of the existing layers worked.

**Comment by glosnick** [comment]
Hi, sorry about the late reply but my principle machine developed a hardware fault and had to be returned so it's taken a while to set up my backup machine to carry on where I left off.  I have now reinstalled all the required software and run the task again and the logo in the fake login fails to load.  I've eliminated bettercap from the equation as I now hook the browser using an alternative method.  When I attempt to use the pretty theft command the fake login attempts to load the following logo:

youtube.com/yt/brand/media/image/yt-brand-standard-logo-630px.png

Which doesn't appear to exist and I think this is the problem.  As far as I can tell beef isn't attempting to load the custom logo but using the above logo

The following shows a screen shot of my options:

![pretty-theft-options](https://user-images.githubusercontent.com/31044891/115215888-dd999f00-a0fb-11eb-9232-e814cdd3e69c.PNG)

As far as I can tell when I hook the browser the server where I'm running apache2 is using http,  the custom logo is setup to use http and therefore the use of https has been eliminated to.  So doesn't that imply that it is some error or bug in beef?

Especially as I have eliminated bettercap, https and in general simplified the whole process and I'm even using a different machine.

Thanks for you help.

Regards

Nick

**Comment by glosnick** [comment]
Thanks once again for your response.  I do believe you are correct in that I don't believe the youtube logo exists anymore.  When I cut and paste the URL for the logo into a browser google fails to find it.  So does this mean that it was in fact an issue with beef and not anything I was doing.  So is it possible to correct this and have beef load attempt to load a you tube logo that does exist?

When I used the generic fake login I was able to use my custom youtube logo and it worked fine

Again, thank you for your help.

Regards

Nick

**Comment by bcoles** [comment]
> So does this mean that it was in fact an issue with beef and not anything I was doing.

No. You were doing something wrong. You never mentioned the YouTube template until now, instead stating multiple times you were using the Generic template.

> So is it possible to correct this and have beef load attempt to load a you tube logo that does exist?

Yes.

> When I used the generic fake login I was able to use my custom youtube logo and it worked fine

:tada:

**Comment by glosnick** [comment]
And how would I get beef to load a logo of my choice using the fake youtube login?

Thanks and regards

Nick

**Comment by bcoles** [comment]
> And how would I get beef to load a logo of my choice using the fake youtube login?

You can modify the logo in the module `command.js` file.

Here's an example:

https://www.youtube.com/about/static/svgs/icons/brand-resources/YouTube-logo-full_color_light.svg

```diff
diff --git a/modules/social_engineering/pretty_theft/command.js b/modules/social_engineering/pretty_theft/command.js
index 62e6c26b..a5641ffc 100644
--- a/modules/social_engineering/pretty_theft/command.js
+++ b/modules/social_engineering/pretty_theft/command.js
@@ -225,7 +225,7 @@ beef.execute(function() {
                var box_prestyle  = 'style="color: #666;font-size: 11px;font-weight: bold;font-family: Arial,sans-serif;padding-left:30px;"';
                var inputboxstyle = 'style="width:140px;font-size: 11px;height: 20px;line-height:20px;padding-left:4px;border-style: solid;border-width: 1px;border-color:#CDCDCD;"';   
                var buttonstyle   = 'style="font-size: 13px;background:#069;color:#fff;font-weight:bold;border: 1px #29447e solid;padding: 3px 3px 3px 3px;clear:both;margin-right:5px;"';
-               var logo  = 'http://www.youtube.com/yt/brand/media/image/yt-brand-standard-logo-630px.png';
+               var logo  = 'https://www.youtube.com/about/static/svgs/icons/brand-resources/YouTube-logo-full_color_light.svg';
                var title = 'Session Timed Out <img src="' + logo + '" align=right height=20 width=70 alt="YouTube">';
                var messagewords = 'Your session has timed out due to inactivity.<br/><br/>Please re-enter your username and password to login.';
                var buttonLabel  = '<input type="button" name="ok" value="Sign In" id="ok" ' +buttonstyle+ ' onClick="document.getElementById(\'buttonpress\').value=\'true\'" onMouseOver="this.bgColor=\'#00CC00\'" onMouseOut="this.bgColor=\'#009900\'" bgColor=#009900>';
```

Although it doesn't look great on the grey background.

![Pretty Theft YouTube](https://user-images.githubusercontent.com/434827/115472403-24fb6900-a27d-11eb-9b7c-3aa1c1f3a4f6.png)

**Comment by glosnick** [comment]
I was just wondering why you closed this thread.  You didn't give me a chance to thank you.  I also wondered where I could find the command.js file.  I looked in Kali and couldn't figure out it's location.

Thanks and regards

Nick

**Comment by bcoles** [comment]
>  I also wondered where I could find the command.js file. I looked in Kali and couldn't figure out it's location.

It is in the modules directory wherever BeEF is installed.

* https://github.com/beefproject/beef/blob/master/modules/social_engineering/pretty_theft/command.js

**Comment by glosnick** [comment]
Yay!!!!!! Success!!!!  I found the necessary file in beef and after a bit of fiddling I managed to get it to load the logo I wanted it to load and not the default logo which didn't exist.  Thank you so much for you help and patience with this novice user.

Regards

Nick
