### ISSUE TITLE
Beef-xss not working

### ISSUE THREAD

**Issue by Simptomz** [beefproject/beef#2089]
# Submit Issue

Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).

Please do your best to provide as much information as possible. It will help substantially if you can enable and provide debugging logs with your issue. Instructions for enabling debugging logs are below:

1. In the `config.yaml` file of your BeEF root folder set debug and client_debug (lines 11 & 13 respectively) to `true`
   * If using a standard installation of `beef-xss` the root folder will typically be `/usr/share/beef-xss`
2. Reproduce your error
3. Retrieve your client-side logs from your browser's developer console (Ctrl + Shift + I)
4. Retrieve your server-side logs from `~/.beef/beef.log`
5. **If using `beef-xss`:** Retrieve your service logs using `journalctl -u beef-xss`

Thank you, this will greatly aid us in identifying the root cause of your issue :)

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**
Feel free to open it back up if you continue to have issues. 

## Summary

**Q:** Please provide a brief summary of the issue that you experienced.
**A:** Im braindead

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:**

2. **Ruby Version:**

3. **Browser Details (e.g. Chrome v81.0):**

4. **Operating System (e.g. OSX Catalina):**

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:** No

**Q:** Have you enabled or disabled any BeEF extensions?
**A:** No

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
<br />
**Actual Behaviour:**
<br />

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1.Ok so when i do `sudo apt-get install beef-xss` it shows 
`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
beef-xss is already the newest version (0.5.0.0+git20191218-0kali2).
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.`

Then when i do `sudo beef` it shows 
`[i]` Something is already using port: 3000/tcp
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ruby    1317 sqeakz   13u  IPv4  23531      0t0  TCP *:3000 (LISTEN)

UID        PID  PPID  C STIME TTY      STAT   TIME CMD
sqeakz    1317     7  0 14:34 ?        Sl     0:02 ruby ./beef

[i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1...`

THEN
When I open ui it works fine *note i open ui on 127.0.0.1:3000 since thats all it shows me.*

Then when I do `cd /var/www/html` it lists 
`index.html  index.html.save  index.html.save.1  index.html.save.2  index.nginx-debian.html`

Then I put in the hook js into index.html **<script src="http://127.0.0.1:3000/hook.js"></script>**

And I go to http://127.0.0.1:3000/hook.js to make sure code is there it says internal server error.

So Im guessing thats why when I put the hook in the html it doesnt work so how do I fix it?

## Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be retrieved by following the instructions towards the top of the issue template.

**Comment by c4t3z** [comment]
Maybe try sudo beef-xss-stop and then beef-xss again and see if it works

**Comment by Simptomz** [comment]
> Maybe try sudo beef-xss-stop and then sudo beef-xss again and see if it works

im doing cd beef then ./beef and the hook still doesnt work

**Comment by Simptomz** [comment]
it also shows ```[i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1... 
```

**Comment by c4t3z** [comment]
> > Maybe try sudo beef-xss-stop and then sudo beef-xss again and see if it works
> 
> im doing cd beef then ./beef and the hook still doesnt work

Don't cd into anything. Try firing sudo beef-xss-stop and then sudo beef-xss straight from your home directory.
I'm not an expert but just suggesting based on my intuition

**Comment by Starzzzxc** [comment]
after it does "5,4,3,2,1" nothing happens for me. When I click the link myself it doesn't even load up. What is happening?!

**Comment by bcoles** [comment]
BeEF runs on port 3000 by default. Open your web browser and navigate to `http://127.0.0.1:3000/ui/panel`.
