### ISSUE TITLE
pls help i dont know how to fix this error

### ISSUE THREAD

**Issue by dean-hacker** [beefproject/beef#2096]
https://www.youtube.com/watch?v=0s5OxXrbP3Y

**Comment by dean-hacker** [comment]
any one knows the error

**Comment by dean-hacker** [comment]
<script>alert ("food")</script>

**Comment by bcoles** [comment]
Possibly a duplicate of #2095.

You can view the logs for the `beef` user with:

```
journalctl -u beef-xss
```

**Comment by bcoles** [comment]
Closing as a duplicate of #2095. You don't need to open a new issue every time you post.

**Comment by dean-hacker** [comment]
still same error
