### ISSUE TITLE
help

### ISSUE THREAD

**Issue by canzafk** [beefproject/beef#2100]
i dont know which is the ip i have to send to the victim to click on 
and when i click on every ip it doesnt load for them what do i do??

**Comment by bcoles** [comment]
When you start BeEF you will see the hook URL printed to console.

Although if you're using a service such as `beef-xss` you may not see the URL in the console.

> i dont know which is the ip i have to send to the victim to click on

Your IP address. The hook URL is:

```
http://<your ip address>:3000/hook.js
```

You may wish to look at the demo pages as an example.

```
http://<your ip address>:3000/demos/basic.html
```

**Comment by canzafk** [comment]
i gave them the "http://<your ip address>:3000/demos/basic.html" 
but it doesnt load for them and i dont see a broswer online what do i do?
