### ISSUE TITLE
How to optimize hook.js

### ISSUE THREAD

**Issue by seeblog** [beefproject/beef#2102]
The hook.js file loaded in the Internet request is about 580KB, and it takes a long time in the case of poor network environment
There are a lot of comment codes in the hook.js file. How can I reverse the file size of hook.js through configuration? Thanks!

**Comment by wheatley** [comment]
Hey @seeblog,
This looks a good idea, do you have any experience in the area of minimising is or ruby?

**Comment by bcoles** [comment]
Disabling some extensions would cut down on the total amount of JavaScript code bundled in the hook.

Using the evasion extension to minify the hook will minify the hook code.

A staged hook, once implemented, would partially resolve this. See #1573 for discussion, in particular the use of jQuery.

**Comment by DeezyE** [comment]
@seeblog good idea. This will be solved by the staged hook as bcoles mentioned. Closing as this has a solution in the works.
