### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by tamirff** [beefproject/beef#2109]
So I'm using a vm I can go in on the hooking site on my vm but when I go on my host/main pc It says This site can't be reached
![Screenshot 2021-06-06 12 16 29](https://user-images.githubusercontent.com/85436741/120920818-0af8d700-c6c1-11eb-87b5-142ae51b42b4.png)

**Comment by bcoles** [comment]
You're using the IP address associated with the local loopback network interface. https://en.wikipedia.org/wiki/Localhost

Use an IP address associated with a local network interface.

**Comment by tamirff** [comment]
> You're using the IP address associated with the local loopback network interface. https://en.wikipedia.org/wiki/Localhost
> 
> Use an IP address associated with a local network interface.

How
