### ISSUE TITLE
Question, How do I setup beef over wan?

### ISSUE THREAD

**Issue by RobloxPros** [beefproject/beef#2114]
I just need to know how to set it up over wan, I have ngrok free and network access. How do I do it?

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by wheatley** [comment]
@RobloxPros just checking in and seeing if you're having any more issues setting this up using the link @bcoles provided you?
