### ISSUE TITLE
Question identify_lan_subnets

### ISSUE THREAD

**Issue by 1124219777** [beefproject/beef#2119]
Issue:

> (if we get 5+ results something probably went wrong. this happens sometimes.). Why?

```javascript
if (discovered_hosts.length >= 5) { 
    // if we get 5+ results something probably went wrong. this happens sometimes.
    if (timeout > min_timeout) {
      // if timeout is more than 500ms then decrease timeout by 500ms and try again
      doScan(timeout-500);
    } else {
      ...
    }
}
```
@bcoles Requesting your help.

**Comment by bcoles** [comment]
It is not impossible for a host to be able to route traffic to 5 different RFC1918 subnets, but unlikely.

This module uses a time-based technique. There could be many issues with network latency, caching, etc. This module could probably be improved.

The answer to your question is in the code comment:

https://github.com/beefproject/beef/blob/663d8e7489e6d0a7fae95a58c8391b9fdc7ca550/modules/network/identify_lan_subnets/command.js#L102
