### ISSUE TITLE
No connection pool for ActiveRecord::Base found

### ISSUE THREAD

**Issue by Darkkronos** [beefproject/beef#2128]
I know that beef doesn't support termux yet, but still can anyone help me out with these issues?
[Screenshot_20210712-232329_Termux.jpg](https://user-images.githubusercontent.com/87331682/125405674-c952fe80-e3d9-11eb-8b4c-b3eb0d601221.jpg)

**Comment by bcoles** [comment]
> can anyone help

Every now and then a wild @Auxilus flies past, dispenses Termux related wisdom, then vanishes into the ether.

I once saw it respond when called by name - but just as likely that it shall turn away from unwanted attention.

**Comment by Auxilus** [comment]
O dear @Darkkronos, I used beef in termux once on [Feb 17, 2019](https://github.com/beefproject/beef/issues/1680#issuecomment-464422903).
for current release, you don't even need to change anything in the `Gemfile`. just cloning the repo works perfectly (I just tried that after 2 years).

I can see in your screenshot that you are using `termuxblack`. So if you installed beef from its repository, you should contact its maintainer

**Comment by Darkkronos** [comment]
> O dear @Darkkronos, I used beef in termux once on [Feb 17, 2019](https://github.com/beefproject/beef/issues/1680#issuecomment-464422903).
> for current release, you don't even need to change anything in the `Gemfile`. just cloning the repo works perfectly (I just tried that after 2 years).
> 
> I can see in your screenshot that you are using `termuxblack`. So if you installed beef from its repository, you should contact its maintainer

Yeah, I opened a issue on his github but didn't get any response from anyone.

@Auxilus dude thanks alot it works normally just by cloning it. 
![Screenshot_20210713-163228_Chrome.jpg](https://user-images.githubusercontent.com/87331682/125437762-c2abeeb7-0c24-4cf6-afad-1fe4af04e3f9.jpg)
