### ISSUE TITLE
Hey i dont know why my hook url does not work at all i installed like thousands of things like ngrok and so on but the hokk url leads me to a external error every single timer...does someone know ho to fix it

### ISSUE THREAD

**Issue by wheatley** [beefproject/beef#2131]
Hey i dont know why my hook url does not work at all i installed like thousands of things like ngrok and so on but the hokk url leads me to a external error every single timer...does someone know ho to fix it

_Originally posted by @virus696969 in https://github.com/beefproject/beef/issues/2063#issuecomment-812133842_

**Comment by bcoles** [comment]
The issue description is useless.
