### ISSUE TITLE
Error handling HTTP request: SQLite3::ReadOnlyException: attempt to write a readonly database

### ISSUE THREAD

**Issue by ArunBohra33** [beefproject/beef#2136]
# Username and password from config.yaml file not working

I have my config file edited like this:
```
credentials:
    user: "123"
    passwd: "123"
```

When I start the ui on this network url ```( UI URL:   http://192.168.1.101:3000/ui/panel )``` and use the same credentials as above, I get error saying that I entered invalid username or password.

I am using latest version of beef.
![Screenshot_2021-07-21_21_02_12](https://user-images.githubusercontent.com/83329195/126516580-5fe870a8-3e5e-47a7-b91c-0185a17b2b67.png)
![Screenshot_2021-07-21_21_02_46](https://user-images.githubusercontent.com/83329195/126516702-7c395ced-243e-41df-bb10-7b8a90bdcf62.png)

**Comment by ArunBohra33** [comment]
Later I found this on the terminal --> [21:05:40][!] Error handling HTTP request: SQLite3::ReadOnlyException: attempt to write a readonly database

**Comment by ArunBohra33** [comment]
Later I found this on the terminal --> [21:05:40][!] Error handling HTTP request: SQLite3::ReadOnlyException: attempt to write a readonly database

**Comment by bcoles** [comment]
> 
> 
> Later I found this on the terminal --> [21:05:40][!] Error handling HTTP request: SQLite3::ReadOnlyException: attempt to write a readonly database

That won't end well. Ensure the `beef.db` database file is writable.

**Comment by ArunBohra33** [comment]
Thanks, that worked, but can I clear all data from that file and start over?

**Comment by bcoles** [comment]
> 
> 
> Thanks, that worked, but can I clear all data from that file and start over?

`./beef -x` to clear the database.

**Comment by wheatley** [comment]
@ArunBohra33 Just checking in the @bcoles comment helped?

**Comment by ArunBohra33** [comment]
Yes it did helped and solved the problem.

**Comment by wheatley** [comment]
@ArunBohra33 good to hear!

**Comment by wheatley** [comment]
closing as issue has been resolved
