### ISSUE TITLE
Internal Server Error while accessing the hook url

### ISSUE THREAD

**Issue by D3crypT0r** [beefproject/beef#2141]
# Submit Issue

Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).

Please do your best to provide as much information as possible. It will help substantially if you can enable and provide debugging logs with your issue. Instructions for enabling debugging logs are below:

1. In the `config.yaml` file of your BeEF root folder set debug and client_debug (lines 11 & 13 respectively) to `true`
   * If using a standard installation of `beef-xss` the root folder will typically be `/usr/share/beef-xss`
2. Reproduce your error
3. Retrieve your client-side logs from your browser's developer console (Ctrl + Shift + I)
4. Retrieve your server-side logs from `~/.beef/beef.log`
5. **If using `beef-xss`:** Retrieve your service logs using `journalctl -u beef-xss`

Thank you, this will greatly aid us in identifying the root cause of your issue :)

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**
Feel free to open it back up if you continue to have issues. 

## Summary

**Q:** Please provide a brief summary of the issue that you experienced.
**A:**

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:**

2. **Ruby Version:**

3. **Browser Details (e.g. Chrome v81.0):**

4. **Operating System (e.g. OSX Catalina):**

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:**

**Q:** Have you enabled or disabled any BeEF extensions?
**A:**

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
<br />
**Actual Behaviour:**
<br />

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1.

## Additional Information
![image](https://user-images.githubusercontent.com/66831571/128300155-450b8e05-bf71-4d51-a214-3bf87263b75b.png)
i am getting this error after accessing the hook url , even after setting  debug and client_debug to true,

**Comment by wheatley** [comment]
hey @D3crypT0r thanks for the query

As you're using kali could you please do the following:

  1. Move to the install location for beef-xss
  2. `git pull`

What are your current values for the configuration of

`# HTTP server
    http:
        debug:

**Comment by bcoles** [comment]
What errors do you get in terminal? Or, if you're running as a service, what errors are in `journalctl -u beef-xss` ?

**Comment by wheatley** [comment]
Labelling this Stale due to inactivity.

**Comment by wheatley** [comment]
Closing this issue due inactivity

**Comment by catchmeifyoucaan** [comment]
please open this im having this error

**Comment by bcoles** [comment]
> please open this im having this error

There is not enough information here to reproduce this error. "Internal Server Error" tells us nothing except than an error occurred.

Please create a new issue and be sure to complete the issue template.

**Comment by catchmeifyoucaan** [comment]
please check i just oppend this : hook url shows a bunch of codes in beef #2346

**Comment by wandas1212** [comment]
> # Submit Issue
> 
> Verify first that your issue/request has not been posted previously:
> 
>     * https://github.com/beefproject/beef/issues
> 
>     * https://github.com/beefproject/beef/wiki/FAQ
> 
> 
> Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).
> 
> Please do your best to provide as much information as possible. It will help substantially if you can enable and provide debugging logs with your issue. Instructions for enabling debugging logs are below:
> 
>     1. In the `config.yaml` file of your BeEF root folder set debug and client_debug (lines 11 & 13 respectively) to `true`
>        
>        * If using a standard installation of `beef-xss` the root folder will typically be `/usr/share/beef-xss`
> 
>     2. Reproduce your error
> 
>     3. Retrieve your client-side logs from your browser's developer console (Ctrl + Shift + I)
> 
>     4. Retrieve your server-side logs from `~/.beef/beef.log`
> 
>     5. **If using `beef-xss`:** Retrieve your service logs using `journalctl -u beef-xss`
> 
> 
> Thank you, this will greatly aid us in identifying the root cause of your issue :)
> 
> **If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.** Feel free to open it back up if you continue to have issues.
> ## Summary
> 
> **Q:** Please provide a brief summary of the issue that you experienced. **A:**
> ## Environment
> 
> _Please identify the environment in which your issue occurred._
> 
>     1. **BeEF Version:**
> 
>     2. **Ruby Version:**
> 
>     3. **Browser Details (e.g. Chrome v81.0):**
> 
>     4. **Operating System (e.g. OSX Catalina):**
> 
> 
> ## Configuration
> 
> **Q:** Have you made any changes to your BeEF configuration? **A:**
> 
> **Q:** Have you enabled or disabled any BeEF extensions? **A:**
> ## Expected vs. Actual Behaviour
> 
> **Expected Behaviour:** **Actual Behaviour:**
> ## Steps to Reproduce
> 
> _Please provide steps to reproduce this issue._
> 
> 
> ## Additional Information
> 
> ![image](https://user-images.githubusercontent.com/66831571/128300155-450b8e05-bf71-4d51-a214-3bf87263b75b.png) i am getting this error after accessing the hook url , even after setting debug and client_debug to true,



have you been able to find solution to that issue,
i am really facing such problem for over a week now and still not able to fix it and really really need help on that, can you help me fix it please

**Comment by bcoles** [comment]
> have you been able to find solution to that issue,
> i am really facing such problem for over a week now and still not able to fix it and really really need help on that, can you help me fix it please

Internal Server Error means an error occurred. Check the logs for more info.

**Comment by wandas1212** [comment]
> > have you been able to find solution to that issue,
> > i am really facing such problem for over a week now and still not able to fix it and really really need help on that, can you help me fix it please
> 
> Internal Server Error means an error occurred. Check the logs for more info.

REALLY GRATEFUL FOR YOUR QUICK REPLY..
REALLY APPRECIATE IT  

can you help me out on that,
i am really stranded and don't know how to resolve it, have tried all my best but still not able to fix it...
my tele_gram ID is @wandas1212
will be very grateful for your support....

**Comment by bcoles** [comment]
> can you help me out on that,

If you ran BeEF from command line, you should see any errors in the terminal. Logs are also logged to file: `~/.beef/beef.log`

If you are using `beef-xss` service, you can retrieve service logs with `journalctl -u beef-xss`

**Comment by bcoles** [comment]
Locking this issue.

The original issue `Internal Server Error` means an error occurred. This could mean anything.

Insufficient information was provided to diagnose the root cause.

Check the logs to determine the root cause.

If you have an issue, create a new issue and ensure the issue template is completed.
