### ISSUE TITLE
Add support for Ruby 3.x

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#2148]
Ruby 3.0 is already 8 months old. https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

**Comment by DeezyE** [comment]
The install script will need to be updated to handle ruby 3 (as well as versions between min and 3.x)

**Comment by bcoles** [comment]
I think this is done?

**Comment by jcrew99** [comment]
#2479 
Preferably not mokeypatching this so potentially need to re-write the module or introduce it in the source code

**Comment by DeezyE** [comment]
Unclear on what you mean. Are you saying that #2479 needs monkeypatching? That's not a blocker for Ruby 3

**Comment by jcrew99** [comment]
The issue with the module occurs due to the URI.escape() command being removed in in Ruby 3. I think the clickjacking module should be kept so some form of rewrite to ensure that the module works with ruby 3 would be good

**Comment by bcoles** [comment]
This is done.
