### ISSUE TITLE
Problem with installing beef

### ISSUE THREAD

**Issue by Steam-21-lol** [beefproject/beef#2152]
Always when i try to install beef this happens: 

[WARNING]  This script will install BeEF and its required dependencies (including operating system packages).
Are you sure you wish to continue (Y/n)? y
[INFO]  Detecting OS...
[INFO]  Operating System: Linux
[INFO]  Launching Linux install...
[INFO]  Detecting Linux OS distribution...
[INFO]  OS Distribution: Debian
[INFO]  Installing Debian prerequisite packages...
Hit:1 http://ftp.halifax.rwth-aachen.de/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
autoconf is already the newest version (2.69-14).
automake is already the newest version (1:1.16.3-2).
bison is already the newest version (2:3.7.6+dfsg-1).
build-essential is already the newest version (12.9).
curl is already the newest version (7.74.0-1.3+b1).
gcc-9-base is already the newest version (9.3.0-22).
git is already the newest version (1:2.32.0-1).
libc6-dev is already the newest version (2.31-13).
libcurl4-openssl-dev is already the newest version (7.74.0-1.3+b1).
libgcc-9-dev is already the newest version (9.3.0-22).
libncurses5-dev is already the newest version (6.2+20201114-2).
libreadline-dev is already the newest version (8.1-2).
libsqlite3-0 is already the newest version (3.34.1-3).
libsqlite3-dev is already the newest version (3.34.1-3).
libssl-dev is already the newest version (1.1.1k-1).
libtool is already the newest version (2.4.6-15).
libxml2-dev is already the newest version (2.9.10+dfsg-6.7).
libxslt1-dev is already the newest version (1.1.34-4).
libyaml-dev is already the newest version (0.2.2-1).
nodejs is already the newest version (12.22.5~dfsg-2~11u1).
openssl is already the newest version (1.1.1k-1).
sqlite3 is already the newest version (3.34.1-3).
zlib1g is already the newest version (1:1.2.11.dfsg-2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
[INFO]  No Ruby package manager detected - will install Ruby
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ruby-dev is already the newest version (1:2.7+2).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 2.7.4 is installed
[INFO]  Updating rubygems...
ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.

**Comment by bcoles** [comment]
`cd beef && bundle install`

**Comment by Steam-21-lol** [comment]
I just did it

**Comment by bcoles** [comment]
`./beef` to run BeEF.

**Comment by wheatley** [comment]
hey @Steam-21-lol was wondering if you were still having issues?

**Comment by wheatley** [comment]
Closed due to inactivity.
