### ISSUE TITLE
Error while trying to start ./beef - Could not find a JavaScript runtime

### ISSUE THREAD

**Issue by BassistGTG** [beefproject/beef#2215]
WHEN I TYPE ./beef  IT GIVES ME THE COMMAND LINES BELOW PLEASE HELP!

Traceback (most recent call last):
        15: from ./beef:44:in `<main>'
        14: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        13: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        12: from /home/kali/beef/core/loader.rb:16:in `<top (required)>'
        11: from /usr/lib/ruby/2.7.0/bundler.rb:174:in `require'
        10: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
         9: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
         8: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
         7: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
         6: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
         5: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:74:in `require'
         4: from /var/lib/gems/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:5:in `<top (required)>'
         3: from /var/lib/gems/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:5:in `require'
         2: from /var/lib/gems/2.7.0/gems/execjs-2.8.1/lib/execjs.rb:4:in `<top (required)>'
         1: from /var/lib/gems/2.7.0/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
/var/lib/gems/2.7.0/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)

**Comment by bcoles** [comment]
You need NodeJS 10 or newer.

**Comment by wheatley** [comment]
Hi @BassistGTG, I was wondering if @bcoles answer assisted in your question?

**Comment by BassistGTG** [comment]
thx bcoles problem solved
