### ISSUE TITLE
Gem 'nokogiri' listed in Gemfile but is never required

### ISSUE THREAD

**Issue by wheatley** [beefproject/beef#2219]
Investigate whether nokogiri is required in Gemfile.

**Comment by wheatley** [comment]
@bcoles is nokogiri used at all within BeEF?
I can see that capybara uses it within tests, but it's not explicitly required within the code base.

**Comment by jcrew99** [comment]
I'll have a look into this.

**Comment by DeezyE** [comment]
Looking at the gemfile, nokogiri is no longer included. closing for now
