### ISSUE TITLE
zsh: permission denied: ./beef

### ISSUE THREAD

**Issue by Sensoirobinson** [beefproject/beef#2243]
Hi, 
When I launch beef, it shows me this error. (zsh: permission denied: ./beef).
May I know how to fix this please. Thank  you very much.
I have tried many commands and searched many websites.
I would appreciate if someone could help me.
Thanks again!
<img width="682" alt="Screenshot 2021-12-12 at 10 20 09 AM" src="https://user-images.githubusercontent.com/95990308/145697920-2917d598-d4a8-4766-91af-da2d35672e1d.png">

**Comment by bcoles** [comment]
`chmod +x beef`

**Comment by wheatley** [comment]
hey @Sensoirobinson just wondering if @bcoles comments helped resolve you're issue

**Comment by jcrew99** [comment]
Closing due to being stale.
Re-open if the suggestion did not help.
