### ISSUE TITLE
Problem with launching beef

### ISSUE THREAD

**Issue by Sensoirobinson** [beefproject/beef#2244]
<img width="682" alt="Screenshot 2021-12-12 at 10 23 00 AM" src="https://user-images.githubusercontent.com/95990308/145697993-d110f0d5-646f-4486-9ead-59e9a0b86c9f.png">

I have already changed the password in the config.yaml file.
May I know which file to change, there are many files.
I changed the file which says config_new.yaml
Thank you for helping me

<img width="1032" alt="Screenshot 2021-12-12 at 10 26 08 AM" src="https://user-images.githubusercontent.com/95990308/145698041-c1cf3412-e58d-4492-8059-832612c8214e.png">
<img width="1032" alt="Screenshot 2021-12-12 at 10 26 19 AM" src="https://user-images.githubusercontent.com/95990308/145698049-a5abdbe4-153b-499b-9096-decfd0494f83.png">

**Comment by wheatley** [comment]
@Sensoirobinson just wondering if @bcoles comments helped?

**Comment by jcrew99** [comment]
Closing due to being stale.
Re-open if the suggestion did not help.
