### ISSUE TITLE
executor failed running [/bin/sh -c apk add --no-cache git curl libcurl curl-dev ruby-dev libffi-dev make g++ gcc musl-dev zlib-dev sqlite-dev &&   bundle install --system --clean --no-cache --gemfile=/beef/Gemfile $BUNDLER_ARGS &&   rm -rf /usr/local/bundle/cache]: exit code: 2

### ISSUE THREAD

**Issue by fnatic0606** [beefproject/beef#2247]
executor failed running [/bin/sh -c apk add --no-cache git curl libcurl curl-dev ruby-dev libffi-dev make g++ gcc musl-dev zlib-dev sqlite-dev &&   bundle install --system --clean --no-cache --gemfile=/beef/Gemfile $BUNDLER_ARGS &&   rm -rf /usr/local/bundle/cache]: exit code: 2

**Comment by DeezyE** [comment]
Hi, thanks for the report, can you elaborate on what you were attempting to do?

**Comment by jcrew99** [comment]
@fnatic0606  If possible, can you expand on what you were trying to achieve?

**Comment by DeezyE** [comment]
Closed; inactive.
Please reopen this when necessary
