### ISSUE TITLE
Update installer to correctly identify Arch linux as distro

### ISSUE THREAD

**Issue by DeezyE** [beefproject/beef#2249]
https://github.com/beefproject/beef/blob/113e6214f29be4d54edd74e3a7702c1daabcd31c/install#L93
does not correctly identify 'arch' and thus the install fails
line 93 outputs
```

arch
archlinux
``` 
where it should output
```
arch
````

**Comment by jcrew99** [comment]
@DeezyE It might be best to close this issue if the issue has been fixed.

**Comment by DeezyE** [comment]
Correct, and thanks!
