### ISSUE TITLE
sudo gem should not be in ./install 

### ISSUE THREAD

**Issue by Ryn0K** [beefproject/beef#2266]
while installing beef `manually` in ubuntu
i run install script, but due to `sudo gem` in `install` so i remove sudo and script got executed and install beef.
![image](https://user-images.githubusercontent.com/44202642/149288091-dae55520-4f46-45bb-bc2d-e496fcf86cb2.png)

so i am advising please remove sudo from ./install, because gem is always not in root directory.

**Comment by DeezyE** [comment]
Thanks for raising this issue. We're looking at it today.
If you're interested in helping with development of BeEF, join our discord https://discord.gg/Pp6DFz3f

p.s. cool avatar

**Comment by Ryn0K** [comment]
ok,let me know what i can do @DeezyE

**Comment by DeezyE** [comment]
Will do :)

**Comment by DiracSpace** [comment]
I'd like to add another thing, I've noticed that in the [installation instructions for Ubuntu](https://github.com/beefproject/beef/wiki/Installation#ubuntu-installation) you use RVM. The issue I found and is related to this one is that the following issue happes: [sudo: gem: command not found](https://discuss.rubyonrails.org/t/sudo-gem-command-not-found/62143/2). My solution was to simply change "sudo gem" to "rvm sudo gem" in the install script.

**Comment by bcoles** [comment]
> Is this discord still a thing?

The link has probably expired. Here's a new one.

https://discord.gg/cmBQR77F

**Comment by bcoles** [comment]
> I'd like to add another thing, I've noticed that in the [installation instructions for Ubuntu](https://github.com/beefproject/beef/wiki/Installation#ubuntu-installation) you use RVM. The issue I found and is related to this one is that the following issue happes: [sudo: gem: command not found](https://discuss.rubyonrails.org/t/sudo-gem-command-not-found/62143/2). My solution was to simply change "sudo gem" to "rvm sudo gem" in the install script.

RVM has been removed from the installation instructions.

**Comment by bcoles** [comment]
> so i am advising please remove sudo from ./install, because gem is always not in root directory.

`sudo gem install bundler` has been removed in #2780.

`sudo` is required to update system ruby gems. The install script shouldn't be updating the system Ruby gems.

This was added in a9bcaf3e224317d17ea03e6cc9eb89f1fb0920df to fix an issue where the installer would fail on OSX if the user's bunlder gem was out of date (#1606). We should not be updating the system gems and I don't think we need this anymore. If outdated `bundler` gem is an issue in the future we can always add a check to update this gem. Removed in #2780.

The install script now uses `sudo` only to install operating system packages (not Ruby gems) as required.
