### ISSUE TITLE
GeoIP no longer supported

### ISSUE THREAD

**Issue by hwac121** [beefproject/beef#2267]
Simple question: When will beef-xss be updated to the latest GeoIP2 format?

**Comment by bcoles** [comment]
PR #2268 updates the GeoIP functionality.

Once this is merged, the next release will include this update. The `beef-xss` package will include this update once the package maintainers update to the next release.

**Comment by bcoles** [comment]
Although this update still uses the GeoIP-Lite database format `.mmdb`. I have no idea if GeoIP2 uses the same format.

**Comment by DeezyE** [comment]
PR approved, as noted, the next beef-xss update should reflect this change
