### ISSUE TITLE
Can't update RubyGems

### ISSUE THREAD

**Issue by GYKgamer** [beefproject/beef#2296]
I have a raspberry pi 4b and whenever I try to install beef I get hit with a rubygem error 
![image](https://user-images.githubusercontent.com/41442793/154159213-a3f769c7-e979-4bbf-869c-2d0aca88a6bc.png)

**Comment by DeezyE** [comment]
On a pi? Interesting.
Does it work for you on a desktop install out of curiosity? Do you have a virtual machine you can test it in?

**Comment by GYKgamer** [comment]
Yes, I can create one rn.

**Comment by GYKgamer** [comment]
![image](https://user-images.githubusercontent.com/41442793/154518516-e3eb657a-dbb5-4716-9bd3-4a22f15b142b.png)
I get this error

**Comment by DeezyE** [comment]
Is this a live version or a full install of Mint?

**Comment by GYKgamer** [comment]
That was a live version, i'll install now
