### ISSUE TITLE
Password change issue

### ISSUE THREAD

**Issue by SukhdevThukral** [beefproject/beef#2297]
I am trying to change the beef password and username in the config.yaml file use root in kali but even after saving it isn't getting effected on the beef page it's still getting only logged in with the old credentials

**Comment by bcoles** [comment]
The config file will not be reloaded until you restart BeEF.

**Comment by SukhdevThukral** [comment]
> The config file will not be reloaded until you restart BeEF.

Thanks, dude it worked, btw what if I keep an easy password would anyone be able to access it by account?

**Comment by bcoles** [comment]
> > The config file will not be reloaded until you restart BeEF.
> 
> Thanks, dude it worked, btw what if I keep an easy password would anyone be able to access it by account?

I don't know what that means.

Make sure the `config.yaml` file is readable only by the user account which runs BeEF.

**Comment by ChickenNugget123456780** [comment]
how do you restart beEF?

**Comment by DeezyE** [comment]
close any beef browser windows then launch beef with `./beef` after you've changed the password

**Comment by DeezyE** [comment]
@ChickenNugget123456780 were you able to solve this?

**Comment by jcrew99** [comment]
Closing due to age, if you have a related question, feel free to comment and re-open.

**Comment by 1983Dan1983** [comment]
show to édit config.yaml file?
