### ISSUE TITLE
sound issue

### ISSUE THREAD

**Issue by matgeusz** [beefproject/beef#2302]
Okay, i had installed beef and its working in my local network.
beef is on laptop with ubuntu
pc is test device
on pc beef page works and dialog prompts show but SOUND isnt played.
on laptop page works and SOUND is played
how to fix this?

**Comment by DeezyE** [comment]
So PC is a separate device? 
Is it on same network?
Which browser(s) are you using?

**Comment by bcoles** [comment]
What did you do? What did you expect to happen? What happened instead?

Are your speakers on? Is the system volume  enabled? Is the browser permitted access to the audio device? Is the hooked domain permitted to play audio?

What browser are you hooking? What operating system?

**Comment by matgeusz** [comment]
I am trying to hook chrome yes speakes on and everything else

**Comment by bcoles** [comment]
> I am trying to hook chrome yes speakes on and everything else

What did you do? What did you expect to happen? What happened instead?

**Comment by DeezyE** [comment]
@matgeusz can you step through your issue more? Was the hook successful? Can you run other modules against the hooked browser?

**Comment by matgeusz** [comment]
Yes everythink is working expect sound

**Comment by DeezyE** [comment]
@matgeusz you'll need to elaborate more, if you can answer bcoles questions that will help in troubleshooting

**Comment by DeezyE** [comment]
Closing inactive, reopen if necessary
