### ISSUE TITLE
Ruby Error

### ISSUE THREAD

**Issue by ac0769** [beefproject/beef#2308]
I am aware that someone else made one similar to this, but mine is on kali linux. I am having the same code as him though. It is an error with ruby gems.
![Capture](https://user-images.githubusercontent.com/80079425/154981802-ec46edea-5d4e-41d9-ab5f-43ad7aa6eae1.PNG)

**Comment by DeezyE** [comment]
This is most likely a Kali issue. You mentioned someone else had the same issue - how did they resolve it?

**Comment by chuckcarne** [comment]
I had that same thing on Ubuntu ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.
root@Hack-book-PRO:/home/charles/beef# 


and its not working. and im kinda new to this Linux stuff and i can't figure it out

**Comment by MaliBoti1** [comment]
I have the same issue

**Comment by bcoles** [comment]
Presumably you're running the install script.

The install script installs a few operating system dependencies, installs Ruby, installs the bundler Ruby gem, then installs the necessary Ruby gems.

You can achieve similar with the following commands:

```
sudo apt-get install ruby ruby-dev
sudo apt-get install curl git build-essential openssl libreadline6-dev zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev autoconf libc6-dev libncurses5-dev automake libtool bison nodejs libcurl4-openssl-dev

cd /path/to/beef
bundle install
```

**Comment by chuckcarne** [comment]
ok i'll try it soon and give feedback.

**Comment by ac0769** [comment]
This is whats happening now. 
![other capture](https://user-images.githubusercontent.com/80079425/156674594-2b85da20-32ca-42d9-9cd9-60a1ce6668b4.PNG)

**Comment by bcoles** [comment]
> This is whats happening now. ![other capture](https://user-images.githubusercontent.com/80079425/156674594-2b85da20-32ca-42d9-9cd9-60a1ce6668b4.PNG)

`gem install bundler`

**Comment by theverygoodwebsite** [comment]
I think you should see the tutorial it is for ubuntu but it is almost the same issue in the video how to download beef in ubuntu but they also show there is a  problem in there gem file too so please see it 
https://www.developsec.com/2018/06/22/installing-beef-on-ubuntu-18-04/

**Comment by bcoles** [comment]
```
gem install bundler
cd /path/to/beef
bundle install
```

**Comment by chuckcarne** [comment]
I think that worked. Thank you for your help and time.

**Comment by DeezyE** [comment]
Closing resolved

**Comment by imtrying2280** [comment]
hey i know yall already closed this but after following the final step i get this


Bundler::GemNotFound: Could not find xmlrpc-0.3.2.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'      
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in
create_threads'

An error occurred while installing xmlrpc (0.3.2), and Bundler cannot continue.

In Gemfile:
  xmlrpc


Ideas?

**Comment by hackernet8** [comment]
you should try it on Ubuntu. it perfectly works, just get from any appstore or website.

**Comment by lapzanry** [comment]
> ind

I tried to run; gem install xmlrpc -v 0.3.2
and it work.
