### ISSUE TITLE
How can i get beef to work on another device somewhere else in the world?

### ISSUE THREAD

**Issue by EzScripts** [beefproject/beef#2315]
I am trying to make it so someone clicks a link and it gives me there info like beef does, but ive noticed its hosted off of my internet, how can i make it so its a link that i can send globally?

**Comment by bcoles** [comment]
You'll need to host BeEF on a publicly access server.

Alternatively, you can port forward your router to BeEF on your LAN.

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

Some people have also had success with ngrok.

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by EzScripts** [comment]
> You'll need to host BeEF on a publicly access server.
> 
> Alternatively, you can port forward your router to BeEF on your LAN.
> 
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
> 
> Some people have also had success with ngrok.
> 
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

i cant get  ngrok to function properly on kali linux 64 bit

**Comment by DeezyE** [comment]
@EzScripts any luck? I've drafted a blog post on getting beef/ngrok working together, let me know if you still need help

**Comment by catchmeifyoucaan** [comment]
i need help please how to get it to work with ngrok, the hook url also shows server error and i have ngrok setup @DeezyE

**Comment by bcoles** [comment]
> i need help please how to get it to work with ngrok, the hook url also shows server error and i have ngrok setup @DeezyE

Impossible to help without knowing what error you're getting.

**Comment by Pamphilemkp** [comment]
> @EzScripts any luck? I've drafted a blog post on getting beef/ngrok working together, let me know if you still need help

Please can I have that blog post?
