### ISSUE TITLE
Does "persistence" still work?

### ISSUE THREAD

**Issue by squodgeface** [beefproject/beef#2318]
This is more of a generic question rather than a specific issue.

To what extent today does persistence work? For example in (https://github.com/beefproject/beef/issues/1972) from July 2020, there seems some debate about whether persistence mechanisms are still effective. 

Here is the Persistence page: https://github.com/beefproject/beef/wiki/Persistence

Do they work and, if so, is there considered to be a consistently reliable method?

**Comment by DeezyE** [comment]
Closing. This discussion is now referenced on the BeEF Persistence wiki page https://github.com/beefproject/beef/wiki/Persistence
