### ISSUE TITLE
Beef hook url not working

### ISSUE THREAD

**Issue by RNTsubasa** [beefproject/beef#2321]
Hello im using BeEF in docker portainer. docker is running in a ubuntu lts vm latest version. i did all the steps docker pul .... and it works whit out problems. but when i  want to hook somebody like my mother it dosnt work. the ports a re open and i can access it whit a url but it still dosnt work. can somebody pls help me?

**Comment by theverygoodwebsite** [comment]
What do you mean? you have problem using beef or you can't join the beef

**Comment by RNTsubasa** [comment]
i can join it but when i open it nothing happens in beef.
![image](https://user-images.githubusercontent.com/45661713/157201774-811d9d64-307d-4c08-b3a3-5fbe75b4bee0.png)
normaly there would be a ip address of a pc there right? but nothing is there not even my own :c so im a little confuste i even have the port open and it has ssl.

Sorry for my late reaction i was on vacation whit my family.

**Comment by RNTsubasa** [comment]
and im using portainer docker and nginx proxy manager.

**Comment by RNTsubasa** [comment]
ok beef is running now out site of my network but now i get a error like this:
![image](https://user-images.githubusercontent.com/45661713/157239058-ad5e3792-c71f-4117-b81e-1369088f2aee.png)

 im sorry for my poor english

**Comment by bcoles** [comment]
Strange. Are there any other errors in terminal?

Have you installed `nodejs` ? `apt-get install nodejs`

**Comment by RNTsubasa** [comment]
yes i have it installed, this only happens when i open this (https://md-beef.duckdns.org/demos/butcher/index.html). its the web address to hook it has https and every thing via nginx i use duckdns.

**Comment by RNTsubasa** [comment]
Hoo and i have only the port 3000 open

**Comment by bcoles** [comment]
Are you accessing `/ui/panel` on your local network or via the reverse proxy?

Are there are any errors in the browser console when you try to admin panel?

Have you changed `base_path: "/ui"` in the config file?

**Comment by RNTsubasa** [comment]
I acces /ui/panel via local and via the proxi both work fine

There are no errors at all

I didnt change the base path. To what should i change that? Its my first time doing this

**Comment by bcoles** [comment]
I noticed this in your hook:

```javascript
beef.net = {

    host: "md-beef.duckdns.org",
    port: "3000",
    hook: "/hook.js",
    httpproto: "http",
    handler: '/dh',
    chop: 500,
    pad: 30, //this is the amount of padding for extra params such as pc, pid and sid
    sid_count: 0,
    cmd_queue: [],
```

As you're using BeEF with a public DNS name (`md-beef.duckdns.org`) and HTTPS, you'll need to update the public host and public port in the `config.yaml` file.

```yaml
        public:
             host: "md-beef.duckdns.org"
             port: "443"
             https: true
```

You may also need to set:

```yaml
        https:
            # Enabled this config setting if you're external facing uri is using https
            public_enabled: true
```

My version of BeEF does not appear to call `/hooked-browser-tree-update.json`. I also can't find this in the source.

> There are no errors at all

Strange.

> I didnt change the base path. To what should i change that? Its my first time doing this

The default value is probably ok.

**Comment by RNTsubasa** [comment]
Right now i see the zombie tab and i have 0 message after  opening the hook url external perhaps it is becaus of my phone i chek that later when im home

**Comment by RNTsubasa** [comment]
when i try to start beef now i get this error:
![image](https://user-images.githubusercontent.com/45661713/157282183-3d22db34-24bb-40d0-b987-833868587627.png)
i only forwarded the port 3000

**Comment by bcoles** [comment]
> when i try to start beef now i get this error:

It looks like your config file is malformed. Whitespace alignment in the config file is important.

**Comment by bcoles** [comment]
good:

![image](https://user-images.githubusercontent.com/434827/157283759-ef4183f6-5bb1-41bd-8171-d54c73403a43.png)


bad:

![image](https://user-images.githubusercontent.com/434827/157283849-1456d7c5-6e3b-4f83-ba65-dcd46a5a952e.png)

bad:

![image](https://user-images.githubusercontent.com/434827/157283918-72609d56-2003-4f6c-9902-97d2a33a9e30.png)

**Comment by RNTsubasa** [comment]
oo good that i made a snapsho before working on this XD thx for the info im going to change it now

**Comment by RNTsubasa** [comment]
still the same error but when i change that again then i can acces it but i cant hook other external.

**Comment by bcoles** [comment]
> this should be good right?

looks fine to me

> still the same error but when i change that again then i can acces it but i cant hook other external.

What does that mean? You're going to have to do some debugging. Do the hooked browsers have any errors in the browser console? Can you see network requests in the browser developer tool? Are they going to the correct host?

**Comment by RNTsubasa** [comment]
![image](https://user-images.githubusercontent.com/45661713/157286715-4cf502c8-4a01-408c-bc30-0139a97f19ee.png)
this error sorry forgot to put the image in here.

**Comment by RNTsubasa** [comment]
im lookinh and searching but i rly dont know what i need to do. i can reinstall this on like arch linux.

**Comment by bcoles** [comment]
> this error sorry forgot to put the image in here.

Your configuration file is malformed. Remove the space.

![image](https://user-images.githubusercontent.com/434827/157287309-9cfe147b-46cf-4c61-8758-05fd5d229a76.png)

**Comment by RNTsubasa** [comment]
omg im retarded that worked now i need to test.

**Comment by RNTsubasa** [comment]
ok weird the hook still dosnt work.

**Comment by RNTsubasa** [comment]
i dont get any error but when i click on the url to hook the browser nothing happens.

**Comment by bcoles** [comment]
> i dont get any error but when i click on the url to hook the browser nothing happens.

What does that mean? You're going to have to do some debugging. Does the hook page load? Does the hook load? Do the hooked browsers have any errors in the browser console? Can you see network requests in the browser developer tool? Are they going to the correct host?

**Comment by RNTsubasa** [comment]
the are going to the correct host and yes the hook page loads and no there are no error when i open the hook page. how do i open the browser developer tool?

**Comment by bcoles** [comment]
> how do i open the browser developer tool?

F12; or:

Firefox: CTRL + SHIFT + K
Chrome: CTRL + SHIFT + J

**Comment by RNTsubasa** [comment]
ok now it gets more weird. my own brower that i hooket lokaly disapiert and i got a random ip address in there that i dont know. its not my own i chekt that weird.

**Comment by RNTsubasa** [comment]
this is localy not external

**Comment by bcoles** [comment]
> ok now it gets more weird. my own brower that i hooket lokaly disapiert and i got a random ip address in there that i dont know. its not my own i chekt that weird.

Is it the IP address of your reverse proxy?

**Comment by bcoles** [comment]
Perhaps similar to this issue #2324.

Sounds like you got it working anyway?

**Comment by RNTsubasa** [comment]
![image](https://user-images.githubusercontent.com/45661713/157294593-004497c6-4edb-4625-8d7c-aa52f3848da2.png)
![image](https://user-images.githubusercontent.com/45661713/157294668-2f2ba66d-e167-4820-ba6a-e3e82cba4590.png)
this are the errors i get

**Comment by bcoles** [comment]
> when i try to start beef now i get this error:

your configuration file is malformed

**Comment by bcoles** [comment]
> this are the errors i get

It is trying to connect to port 3000. I believe you're running the reverse proxy on public port 443? `public.port` should be `443` and `public.https` should be `true`.

**Comment by RNTsubasa** [comment]
the reverse proxy is running on 3000 and i port fowarded to 3000 to i have nothing whit 443 going right now only my docker runs on 443.

**Comment by RNTsubasa** [comment]
i dont have a public.https in my file. becaus when i try to search it it says not found. i work whit nano not vi.

**Comment by RNTsubasa** [comment]
is it perhaps my nginx proxy manager?

**Comment by RNTsubasa** [comment]
yeah it was adblock XD so mutch work for a adblocker :D stil thx for the help i only need to figure it out so that it works whit adblock.

**Comment by bcoles** [comment]
> i dont have a public.https in my file. becaus when i try to search it it says not found. i work whit nano not vi.

`public.https` is YAML notation for this:

```yaml
public:
    https: ....
```

> the reverse proxy is running on 3000 and i port fowarded to 3000 to i have nothing whit 443 going right now only my docker runs on 443.
> yeah it was adblock XD so mutch work for a adblocker :D stil thx for the help i only need to figure it out so that it works whit adblock.

I have no idea how you got it working. You are definitely using port 443 not 3000. Port 3000 is not open. Port 443 is open.

**Comment by RNTsubasa** [comment]
ok its weird becuas i looked at my port forward and it says that i use 3000 for the ip address of beef. my port 443 is open for docker. so i think its weird anyway.

**Comment by RNTsubasa** [comment]
![image](https://user-images.githubusercontent.com/45661713/157299791-3acf57fc-3237-4005-859b-607e66a28848.png)

**Comment by RNTsubasa** [comment]
it works whit web url i try it now on a friend just for test purpose and then i know more :D

**Comment by RNTsubasa** [comment]
now it works whit ad block i dont understant this thing XD its so weird but im happy that it now even works whit adblock :D

**Comment by bcoles** [comment]
> ok its weird becuas i looked at my port forward and it says that i use 3000 for the ip address of beef. my port 443 is open for docker. so i think its weird anyway.

You're using `md-beef.duckdns.org` for `public.host` and `443` for `public.port`. I can see it in your BeEF hook.

```yaml
beef.net = {

    host: "md-beef.duckdns.org",
    port: "443",
    hook: "/hook.js",
    httpproto: "https",
    handler: '/dh',
    chop: 500,
    pad: 30, //this is the amount of padding for extra params such as pc, pid and sid
    sid_count: 0,
    cmd_queue: [],
```

That is correct.

> now it works whit ad block i dont understant this thing XD its so weird but im happy that it now even works whit adblock :D

Adblock shouldn't block BeEF, unless your domain is blacklisted for some reason. BeEF works fine with adblock on my test systems.

**Comment by RNTsubasa** [comment]
at least it works dont even know what i did to get it working i just restartet it like 100x

**Comment by RNTsubasa** [comment]
![image](https://user-images.githubusercontent.com/45661713/157300770-d2685cf5-4232-4ce6-b4ca-a9dfae9d5fa2.png)
i forgot to click on force ssl first i did that after around 10 minuts it worked. perhaps this is the reason.

**Comment by RNTsubasa** [comment]
and now it dosnt work anymore :D

**Comment by RNTsubasa** [comment]
btw a question do i need to have the demo tab open so that beef works or do you only click it once and i have acces to the web browser?

**Comment by bcoles** [comment]
> btw a question do i need to have the demo tab open so that beef works or do you only click it once and i have acces to the web browser?

A hooked page must remain open for the BeEF hook to run.
