### ISSUE TITLE
git clone issue

### ISSUE THREAD

**Issue by chris12x1** [beefproject/beef#2322]
hello, im trying to clone the github project to my kali. 

before i started i made sure i have updated using these commands
sudo apt-get update -y; sudo apt-get upgrade -y
sudo apt install ruby ruby-dev
sudo apt install git

and then after making sure it is installed/updated i tried to close the project using this command
git clone https://github.com/beefproject/beef
and the error i get is unable to access, could not resolve host:github.com

anyone can help me please and thank you!

**Comment by wheatley** [comment]
hey @chris12x1,

If you're looking to install the latest beef instance clone is definitely the best option.
Please note you may still get some errors after following the steps below, due to some dependency issues.
If you do get errors please copy and bash the terminal output and we'll help you resolve them.

Please follow the steps below 

Please do the following to fix your issues

1. Remove kali beef

`sudo apt remove beef-xss`

2. Clone the latest version

`cd ~`
`git clone https://github.com/beefproject/beef.git`

3. Install gems (you may have issues here please let us know)

`bundle install`

4. Update the config.yaml with a more secure password
5. Run 

`./beef`

Please post any further issues you have.

**Comment by chris12x1** [comment]
for bundle install
 
i get error "an error occurred while installing sqlite 3 (1.4.2) and bundler cannot continue. make sure that "gem install sqlite3 -v '1.4.2' --source https://rubygems.org/ succeds before bundling. 

i then tried 

sudo apt-get install sqlite3 libsqlite3-dev

problem cant find package

then tried 

sudo gem install sqlite3-ruby

error with that one as well. 

can you also teach me how to update the config.yaml thank you for your help!

**Comment by chris12x1** [comment]
──(kali㉿kali-raspberry-pi)-[~/beef]
└─$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Using rake 13.0.6
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.7.0
  /var/lib/gems/2.7.0/build_info
  /var/lib/gems/2.7.0/cache
  /var/lib/gems/2.7.0/doc
  /var/lib/gems/2.7.0/extensions
  /var/lib/gems/2.7.0/gems
  /var/lib/gems/2.7.0/plugins
  /var/lib/gems/2.7.0/specifications
Using concurrent-ruby 1.1.9
Using i18n 1.10.0
Using minitest 5.15.0
Using tzinfo 2.0.4
Using activesupport 7.0.2.2
Using activemodel 7.0.2.2
Using activerecord 7.0.2.2
Using public_suffix 4.0.6
Using addressable 2.8.0
Using ansi 1.5.0
Using ast 2.4.2
Using fiber-local 1.0.0
Using console 1.13.1
Using nio4r 2.5.8
Using timers 4.3.3
Using async 1.30.1
Using async-io 1.32.2
Using async-dns 1.3.0
Using buftok 0.2.0
Using bundler 2.1.4
Using daemons 1.4.1
Using unf_ext 0.0.7.7
Using unf 0.1.4
Using domain_name 0.5.20190701
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.3
Using equalizer 0.0.11
Using erubis 2.7.0
Using espeak-ruby 1.0.5
Using execjs 2.8.1
Using ffi 1.15.4
Using ffi-compiler 1.0.1
Using hashie 5.0.0
Using hashie-forbidden_attributes 0.1.1
Using http-cookie 1.0.4
Using http-form_data 2.3.0
Using http-parser 1.2.3
Using http 4.4.1
Using http-accept 1.7.0
Using json 2.6.1
Using maxmind-db 1.1.1
Using thread_safe 0.3.6
Using memoizable 0.4.2
Using mime-types-data 3.2021.1115
Using mime-types 3.4.1
Using mojo_magick 0.6.6
Using msgpack 1.4.2
Using msfrpc-client 1.1.2
Using multipart-post 2.1.1
Using ruby2_keywords 0.0.5
Using mustermann 1.1.1
Using naught 1.1.0
Using netrc 0.11.0
Using otr-activerecord 2.1.1
Using parallel 1.21.0
Using parseconfig 1.1.2
Using parser 3.1.0.0
Using rqrcode_core 0.2.0
Using qr4r 0.6.1
Using rack 2.2.3
Using rack-protection 2.2.0
Using rainbow 3.1.1
Using regexp_parser 2.2.1
Using rest-client 2.1.0
Using rexml 3.2.5
Using rubocop-ast 1.15.2
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.1.0
Using rubocop 1.25.1
Using rubyzip 2.3.2
Using rushover 0.3.0
Using simple_oauth 0.3.1
Using tilt 2.0.10
Using sinatra 2.2.0
Using slack-notifier 2.4.0
Fetching sqlite3 1.4.2
Installing sqlite3 1.4.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
                                                                                                                                                                                                                               
    current directory: /tmp/bundler20220228-22594-10b2rprsqlite3-1.4.2/gems/sqlite3-1.4.2/ext/sqlite3
/usr/bin/ruby2.7 -I /usr/lib/ruby/vendor_ruby -r ./siteconf20220228-22594-6h2sv2.rb extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Try 'brew install sqlite3',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
        --with-sqlcipher
        --without-sqlcipher
        --with-sqlite3-config
        --without-sqlite3-config
        --with-pkg-config
        --without-pkg-config
        --with-sqlcipher
        --without-sqlcipher
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /tmp/bundler20220228-22594-10b2rprsqlite3-1.4.2/extensions/aarch64-linux/2.7.0/sqlite3-1.4.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20220228-22594-10b2rprsqlite3-1.4.2/gems/sqlite3-1.4.2 for inspection.
Results logged to /tmp/bundler20220228-22594-10b2rprsqlite3-1.4.2/extensions/aarch64-linux/2.7.0/sqlite3-1.4.2/gem_make.out

An error occurred while installing sqlite3 (1.4.2), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/'` succeeds before bundling.                                                                                                                     

In Gemfile:
  sqlite3

**Comment by wheatley** [comment]
Thanks for replying 
I'll have look at this when I get back from work today

**Comment by wheatley** [comment]
@chris12x1  - I just setup a virtual machine with the latest kali and was able to install both the sqlite3 (already install) and  libsqlite3-dev 

what version of kali are you using?

`lsb_release -a`

**Comment by chris12x1** [comment]
> @chris12x1 - I just setup a virtual machine with the latest kali and was able to install both the sqlite3 (already install) and libsqlite3-dev
> 
> you could also try in run the install script
> 
> `cd ~/beef` `./install`
> 
> what version of kali are you using?
> 
> `lsb_release -a`

thank you so much it worked
