### ISSUE TITLE
ruby package problem on Kali linux

### ISSUE THREAD

**Issue by bangkokhermetik** [beefproject/beef#2327]
hi i have a problem to download the ruby package on kali linuk when i type 
sudo apt-add-repository -y ppa:brightbox/ruby-ng 
it won't work ,i do not know if it's a syntax problem or else if someone can enlight me it'll be nice ,thanks ;)

**Comment by bcoles** [comment]
Kali includes a `beef-xss` package by default. You can install it with `apt install beef-xss`.

**Comment by bcoles** [comment]
Kali also includes Ruby packages installed by default. You can install them with `apt install ruby ruby-dev`.

**Comment by bangkokhermetik** [comment]
Thank you very much for your quick answer,i'll try it right know ;)

**Comment by bangkokhermetik** [comment]
it works ,thank you again ;)
