### ISSUE TITLE
http://127.0.0.1:3000/demos/butcher/index.html link error

### ISSUE THREAD

**Issue by cybercortar** [beefproject/beef#2334]
if i use this link outside vm ware i wont work.

beef generated link

**Comment by bcoles** [comment]
127.0.0.1 is an IP address for the local loopback network Udapter. use a LAN IP address.

**Comment by clappz8830** [comment]
So what is the solution for this problem

**Comment by bcoles** [comment]
> So what is the solution for this problem

use any other ip

**Comment by Sudhanshu41** [comment]
IF I WANT TO SHOW MY WEBSITE TO ANYONE SO HOW TO SEND IT

**Comment by Manishabharti695** [comment]
i want my website to show in mobile

**Comment by stephenakq** [comment]
> i want my website to show in mobile

Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/25wT2P8pwx

**Comment by liamleandropelozo-blip** [comment]
http://127.0.0.1:3000/demos/butcher/index.html

**Comment by ismailnirob93-hash** [comment]
from moviepy.editor import *
import numpy as np

# Dirk pink background    
bg = ColorClip(size=(720,1280), color=(30,0,50)).set_duration(10)

# Sneha Glow Text
name = TextClip("✨ SNEHA ✨", fontsize=170, color="pink", font="Arial-Bold")
name = name.set_position("center").set_duration(10).fadein(2).fadeout(2)

# Love Message
msg = TextClip("Forever In My Heart ❤️", fontsize=70, color="white", font="Arial-Bold")
msg = msg.set_position(("center", 1000)).set_duration(10)

# Floating Heart Effect
hearts = []
for i in range(30):
    heart = TextClip("💗", fontsize=50)
    heart = heart.set_position((np.random.randint(0,720),
                                 np.random.randint(200,1200)))
    heart = heart.set_duration(0.3).set_start(i*0.3)
    hearts.append(heart)

video = CompositeVideoClip([bg, name, msg, *hearts])
video.write_videofile("sneha_pro_intro.mp4", fps

**Comment by ismailnirob93-hash** [comment]
from moviepy.editor import *
import numpy as np

# Dirk pink background    
bg = ColorClip(size=(720,1280), color=(30,0,50)).set_duration(10)

# Sneha Glow Text
name = TextClip("✨ SNEHA ✨", fontsize=170, color="pink", font="Arial-Bold")
name = name.set_position("center").set_duration(10).fadein(2).fadeout(2)

# Love Message
msg = TextClip("Forever In My Heart ❤️", fontsize=70, color="white", font="Arial-Bold")
msg = msg.set_position(("center", 1000)).set_duration(10)

# Floating Heart Effect
hearts = []
for i in range(30):
    heart = TextClip("💗", fontsize=50)
    heart = heart.set_position((np.random.randint(0,720),
                                 np.random.randint(200,1200)))
    heart = heart.set_duration(0.3).set_start(i*0.3)
    hearts.append(heart)

video = CompositeVideoClip([bg, name, msg, *hearts])
video.write_videofile("sneha_pro_intro.mp4", fps
