### ISSUE TITLE
The hook link doesnt open out of my vm

### ISSUE THREAD

**Issue by Fanciermot8** [beefproject/beef#2340]
iv looked around and on here but i cant find a way for the links to work outside of my vm

**Comment by DeezyE** [comment]
Closing. As mentioned this has been solved

**Comment by oussama075** [comment]
> This question has been asked and answered many many many times.
> 
> You'll need to configure your network, then apply the following config changes.
> 
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

where do I need to configure those config changes and how I configure my network.

**Comment by bcoles** [comment]
> where do I need to configure those config changes and how I configure my network.

ngrok is likely the easiest way.

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
