### ISSUE TITLE
I cant create a public facing url

### ISSUE THREAD

**Issue by Astravi** [beefproject/beef#2345]
When ever I try to add an ip or domain to the section labled host name /domain name
 # Host Name / Domain Name
        # If you want BeEF to be accessible via hostname or domain name (ie, DynDNS),
        # These settings will be used to create a public facing URL
        # This public facing URL will be used for all hook related calls
        # set the public setting below:
           public:
           	  host: "carterc-cs.live" # public hostname/IP address
                port: "80" # public port will default to 80 if no https 443 if https 
                      # and local if not set but there is a public host
              https: false # true/false

The reason im trying to use an actual domain is because im going to use this for wan
# Reverse Proxy / NAT
        # If you want BeEF to be accessible behind a reverse proxy or NAT,
        #   set both the publicly accessible hostname/IP address and port below:
        # NOTE: Allowing the reverse proxy will enable a vulnerability where the ui/panel can be spoofed
        #   by altering the X-FORWARDED-FOR ip address in the request header.
        allow_reverse_proxy: true
Reverse proxy is set to yes / true as well

**Comment by bcoles** [comment]
Is there more to the issue? What happens instead? Where did you get stuck troubleshooting?

Also the YAML you pasted above is malformed. Whitespace is important.

**Comment by DeezyE** [comment]
@Astravi did you have further information to aid troubleshooting?

**Comment by catchmeifyoucaan** [comment]
my hook link shows internal error, please help

**Comment by jcrew99** [comment]
hey @catchmeifyoucaan, it seems likely that this would be an unrelated issue.
Have a look at the wiki or any other created issues for a similar issue to the one you are experiencing.
If you don't find anything, feel free to create and issue and fill out the issue template as best as you can.

There is not enough information here to help. I've added the inactive and needs more information tags.
If you need more assistance with this issue, please fill the issue template as best as you can.
