### ISSUE TITLE
is there any way to install on windows?

### ISSUE THREAD

**Issue by Azzerzz** [beefproject/beef#2353]
title

**Comment by bcoles** [comment]
Yes. But BeEF has not been thoroughly tested on Windows, nor actively used on Windows. There are likely to be many bugs.

BeEF is written in Ruby. Install Ruby. Install RubyGems. Install the `bundler` gem. Run `bundle install`. For each gem that fails to install, install it libraries it needs.

**Comment by DeezyE** [comment]
Def recommend setting up a linux VM and installing there if possible @Azzerzz

**Comment by theverygoodwebsite** [comment]
no i don't think so @Azzerzz

**Comment by DeezyE** [comment]
Closing as resolved, please reopen if needed.
