### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by TheDoffee** [beefproject/beef#2355]
<internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/bin/msfvenom:23:in `<main>'

**Comment by bcoles** [comment]
Metasploit project is here: https://github.com/rapid7/metasploit-framework

And Metasploit does not support Termux.
