### ISSUE TITLE
Determine feasibility of lightweight browser (feature) detection for first step of Staged Hook

### ISSUE THREAD

**Issue by DeezyE** [beefproject/beef#2363]
As part of the BeEF staged hook project https://github.com/beefproject/beef/issues/1573

In line with some of the goals of the staged hook "The implementation should have two primary goals - reliability and speed. Evasion is a secondary goal, which is a byproduct of the first by virtue of randomization."

We need to work out how the initial browser detection should occur. This exploration should answer:
- Can it be done using only Javascript
- What is the smallest we can make the initial browser detection while also being reliable against a wide range of browsers
- Rather than detecting browsers, it should instead detect features, which features should it be using

**Comment by DeezyE** [comment]
https://code-boxx.com/dynamically-load-javascript/
As a test, this functions fine

**Comment by DeezyE** [comment]
/home/ubuntu/beef/core/main/handlers/modules/beefjs.rb
is where the hook building function `def build_beefjs!(req_host)` lives

**Comment by bcoles** [comment]
What was the end result here?

**Comment by CrazyKidJack** [comment]
> What was the end result here?

+1
