### ISSUE TITLE
Problems with installation and running in macOS Monterey 

### ISSUE THREAD

**Issue by Kingteena** [beefproject/beef#2365]
After installing, I closed the terminal and ran ./beef, only to see the following error

```
Traceback (most recent call last):
	5: from /Users/Kingteena/Downloads/beef-0.5.4.0/beef:44:in `<main>'
	4: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	3: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	2: from /Users/Kingteena/Downloads/beef-0.5.4.0/core/loader.rb:14:in `<top (required)>'
	1: from /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- msgpack (LoadError)
```

I reran the installation script and realised that after installing wget, this error pops up:

```
[INFO]  wget installed
[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 2.7.5 is installed
[INFO]  Updating rubygems...
Latest version already installed. Done.
[INFO]  Detecting bundler gem...
[INFO]  bundler gem is installed
Installing required Ruby gems...
Could not locate Gemfile
```

Tried several times, redownloaded the files and ran it without changing anything to no avail

`ruby -v` gives:
```ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin21]```

macOS version: 12.1

BeEF version:
Attempted to use code from master branch first and then v0.5.4.0 which was linked as the latest stable release.

**Comment by bcoles** [comment]
> Could not locate Gemfile

Are you running the install script from within the BeEF directory?

It looks like most of the install completed, leaving only the gems remaining. You can probably just:

```
cd /path/to/beef
bundle install
```

**Comment by bcoles** [comment]
Strange. Perhaps `bundle exec ./beef`.

**Comment by iWhacko** [comment]
Ah yes, I ran into this earlier. MacOS doesn't allow you to change the default ruby install.
I got it to work using the steps in this answer by Mick: https://stackoverflow.com/a/66379795

especially adding the line to ~/.bash_profile (not .bashrc, thats for linux, on mac it's .bash_profile), that makes it choose the right Ruby version when opening a new terminal. Then using rbenv to install a separate ruby version. which can be modified and gems added to it.

**Comment by Kingteena** [comment]
> Strange. Perhaps `bundle exec ./beef`.

This worked for me... Thanks a lot!

**Comment by PP221B030145** [comment]
I have a similar error at startup ./beef :

Traceback (most recent call last):
	9: from ./beef:91:in `<main>'
	8: from /Users/usr/tools/beef/core/logger.rb:15:in `logger'
	7: from /Users/usr/tools/beef/core/logger.rb:15:in `new'
	6: from /Users/usr/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/logger.rb:389:in `initialize'
	5: from /Users/usr/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/logger.rb:389:in `new'
	4: from /Users/usr/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/logger/log_device.rb:18:in `initialize'
	3: from /Users/usr/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/logger/log_device.rb:86:in `set_dev'
	2: from /Users/usr/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/logger/log_device.rb:95:in `open_logfile'
	1: from /Users/usr/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/logger/log_device.rb:95:in `open'
/Users/usr/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/logger/log_device.rb:95:in `initialize': Permission denied @ rb_sysopen - /Users/usr/.beef/beef.log (Errno::EACCES)
