### ISSUE TITLE
Unable to browse executed commands on offline browsers

### ISSUE THREAD

**Issue by iWhacko** [beefproject/beef#2368]
When browsing the online hooked browsers, I can easily see commands that were executed before, and their results.
However as soon as the browser goes online, I can no longer see the gathered information from the offline browser. This is especially annoying because I execute some ARE rules to gather basic information as soon as someone clicks the link.
Now I can get the results from executed commands from beef.db using a script, and this is fine for reporting. 
But when actively monitoring I would like to be able to just click the offline browser and see the gathered info, just like an online one.
I am a programmer, so I can just do this myself, but some pointers on where to edit this behaviour would be appreciated.

**Comment by bcoles** [comment]
> I am a programmer, so I can just do this myself, but some pointers on where to edit this behaviour would be appreciated.

![image](https://user-images.githubusercontent.com/434827/159345309-a61a4ba7-1bbe-43ea-b4d6-4fd821cec0c1.png)

**Comment by bcoles** [comment]
For whatever reason, A JavaScript error occurs when clicking offline browsers. The error occurs in `web_ui_all.js` which is a bundled JavaScript file. The bundled JavaScript consists of files from `extensions/admin_ui/media/javascript`.

**Comment by iWhacko** [comment]
thanks, I must have missed that. I will take a look at it and see if I can find something.

**Comment by iWhacko** [comment]
Is there a guide on how to set up a dev environment? Like, how can I test changes to the UI javascript? since it's using a minified version, and ignoring my changes to the separate files. Can I make it use the source files? So I can do debugging in the browser?

**Comment by bcoles** [comment]
> Is there a guide on how to set up a dev environment? Like, how can I test changes to the UI javascript?

The easiest way is to clone the repository from GitHub.

> since it's using a minified version, and ignoring my changes to the separate files.

Are you sure?

> Can I make it use the source files? So I can do debugging in the browser?

The minified version is simply a bunch of files concatenated together then minified. Any changes you make to the JavaScript files in `extensions/admin_ui/media/javascript` will be applied to the minified files which are stored in `extensions/admin_ui/media/javascript-min`.

Note that you'll likely have to refresh the admin UI after making changes so that you browser loads the new minified file.

**Comment by iWhacko** [comment]
Thanks for the quick answer. I must have done something wrong, I will check try again later today.

**Comment by iWhacko** [comment]
Ok, I found the problem. Not sure if it is intentional. But here goes. 
In PanelViewer.js is the following code when the hash changes:
`function locationHashChanged() {
  var id = location_hash('id');

  if (id === null) return;

  var zombie = Object.values(beefwui.hooked_browsers).find(hb => hb.session === id);

  id = id.replace(/[^a-z0-9]/gi, '');
  console.log("Loading hooked browser with ID: " + id);
  mainPanel.remove(mainPanel.getComponent('current-browser'));
  if(!mainPanel.getComponent('current-browser')) {
    mainPanel.add(new ZombieTab(zombie));
  }

  mainPanel.activate(mainPanel.getComponent('current-browser'));
  //removeHash();
}`

it tries to find the hash in beefwui.hooked_browsers.
But this global parameter only contains the online zombies. See code from the line in updateZombies in ZombiesMgr.js:
`	this.updateZombies = function(zombies){
		var offline_hooked_browsers = zombies["offline"];
		var online_hooked_browsers = zombies["online"];
    beefwui.hooked_browsers = zombies["online"];
`
So I think if we concatenate these two lists in the global variable, it should fix this issue. But I'm not sure if it will cause problems elsewhere

**Comment by iWhacko** [comment]
I think I have created a proper fix. I will submit a Pull Request once I did more testing.

**Comment by jcrew99** [comment]
This pull request has been merged and has been solved
