### ISSUE TITLE
"Rubygems issue"

### ISSUE THREAD

**Issue by S1impgod** [beefproject/beef#2376]
ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.

New to linux is there a easy fix for this?

**Comment by S1impgod** [comment]
I have tried 

sudo bundle install 
sudo apt-get install ruby ruby-dev
sudo apt-get install curl git build-essential openssl libreadline6-dev zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev autoconf libc6-dev libncurses5-dev automake libtool bison nodejs libcurl4-openssl-dev

**Comment by bcoles** [comment]
> I have tried
> 
> sudo bundle install sudo apt-get install ruby ruby-dev sudo apt-get install curl git build-essential openssl libreadline6-dev zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev autoconf libc6-dev libncurses5-dev automake libtool bison nodejs libcurl4-openssl-dev

Did that work?

Once you've installed operating system packages you will need to install some Ruby dependenecies.

```
cd /path/to/beef
gem install bundler
bundle install
```

**Comment by S1impgod** [comment]
> > I have tried
> > sudo bundle install sudo apt-get install ruby ruby-dev sudo apt-get install curl git build-essential openssl libreadline6-dev zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev autoconf libc6-dev libncurses5-dev automake libtool bison nodejs libcurl4-openssl-dev
> 
> Did that work?
> 
> Once you've installed operating system packages you will need to install some Ruby dependenecies.
> 
> ```
> cd /path/to/beef
> gem install bundler
> bundle install
> ```

![issue linux beef_LI](https://user-images.githubusercontent.com/102562445/160509377-f6c0aa1f-edb6-4fec-8c61-c31a53264216.jpg)

**Comment by S1impgod** [comment]
I have followed those steps and at the end im left with above picture

**Comment by bcoles** [comment]
BeEF is not yet ready for Ruby 3. Strange that those packages failed if you've installed the sqlite-dev packages. There might be some hints in the bundle logs.

**Comment by S1impgod** [comment]
So what that being said whats the best way to install a older version of ruby to see if its compatible I've removed ruby 3

**Comment by bcoles** [comment]
> So what that being said whats the best way to install a older version of ruby to see if its compatible I've removed ruby 3

The easiest way is to use whichever ruby version is in your operating system packages if it still has Ruby 2.x packages, but I wouldn't recommend downgrading. You can use rvm to manage multiple versions of Ruby, although I wouldn't recommend that either.

It shouldn't be too difficult to get BeEF working on Ruby 3. You'll need to investigate the bundle logs to figure out why those gems failed. bundler should print a path to the logs somewhere in the error output.

**Comment by S1impgod** [comment]
Interesting im searching but not finding a solution, can we speak via discord if you are available no biggie if not. Im just new to Kali linux.

**Comment by bcoles** [comment]
Discord: https://discord.gg/Pp6DFz3f

**Comment by S1impgod** [comment]
Invalid link

**Comment by bcoles** [comment]
https://discord.com/invite/25wT2P8pwx

**Comment by S1impgod** [comment]
Bump

**Comment by bcoles** [comment]
This issue was resolved.

Kali has recently updated to using Ruby 3. BeEF appears to work after removing the Gemfile lock and installing dependencies for Ruby 3.

```
cd /path/to/beef
rm Gemfile.lock
bundle3.0 install
```
