### ISSUE TITLE
BEEF GEMS ERROR NEED HELP !!!

### ISSUE THREAD

**Issue by cyb3rpo3t** [beefproject/beef#2377]
INFO]  Detecting OS...
[INFO]  Operating System: Linux
[INFO]  Launching Linux install...
[INFO]  Detecting Linux OS distribution...
[INFO]  OS Distribution: Debian
[INFO]  Installing Debian prerequisite packages...
Hit:1 http://kali.download/kali kali-rolling InRelease
Reading package lists... Done   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
autoconf is already the newest version (2.71-2).
automake is already the newest version (1:1.16.5-1.3).
bison is already the newest version (2:3.8.2+dfsg-1).
build-essential is already the newest version (12.9).
curl is already the newest version (7.81.0-1).
git is already the newest version (1:2.35.1-1).
libc6-dev is already the newest version (2.33-6).
libcurl4-openssl-dev is already the newest version (7.81.0-1).
libncurses5-dev is already the newest version (6.3-2).
libreadline-dev is already the newest version (8.1.2-1).
libsqlite3-0 is already the newest version (3.38.1-1).
libsqlite3-dev is already the newest version (3.38.1-1).
libssl-dev is already the newest version (1.1.1n-1).
libtool is already the newest version (2.4.6-15).
libxml2-dev is already the newest version (2.9.13+dfsg-1).
libxslt1-dev is already the newest version (1.1.34-4).
libyaml-dev is already the newest version (0.2.2-1).
nodejs is already the newest version (12.22.10~dfsg-2).
openssl is already the newest version (1.1.1n-1).
sqlite3 is already the newest version (3.38.1-1).
zlib1g is already the newest version (1:1.2.11.dfsg-2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2).
The following packages were automatically installed and are no longer required:
  ettercap-common ettercap-graphical libapache2-mod-php libluajit-5.1-2 libluajit-5.1-common libnet-snmp-perl libnumber-bytes-human-perl nginx oracle-instantclient-basic python3-qrcode ruby-addressable ruby-concurrent ruby-did-you-mean
  ruby-i18n ruby-ipaddress ruby-mini-portile2 ruby-minitest ruby-power-assert ruby-progressbar ruby-public-suffix ruby-test-unit ruby-tzinfo ruby-zip ruby2.5-doc
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 379 not upgraded.
[INFO]  No Ruby package manager detected - will install Ruby
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ruby-dev is already the newest version (1:3.0+1kali1).
The following packages were automatically installed and are no longer required:
  ettercap-common ettercap-graphical libapache2-mod-php libluajit-5.1-2 libluajit-5.1-common libnet-snmp-perl libnumber-bytes-human-perl nginx oracle-instantclient-basic python3-qrcode ruby-addressable ruby-concurrent ruby-did-you-mean
  ruby-i18n ruby-ipaddress ruby-mini-portile2 ruby-minitest ruby-power-assert ruby-progressbar ruby-public-suffix ruby-test-unit ruby-tzinfo ruby-zip ruby2.5-doc
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 379 not upgraded.
[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 3.0.3 is installed
[INFO]  Updating rubygems...
**ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.**

No matter what I did I couldn't fix this error. I tried all kinds of updates, reinstalling and couldn't. I would be glad if you help.

**Comment by bcoles** [comment]
The installation has mostly completed. Only the ruby gems remain.

You should be able to do this:

```
cd /path/to/beef
bundle install
```
