### ISSUE TITLE
beef

### ISSUE THREAD

**Issue by benio2** [beefproject/beef#2378]
Everytime I use beef it works besides the fact that commands dont work. I open the data on a command once it has been executed and nothing shows and nothing happens from my computer to the windows machine. Ive tried updating beef but that didnt work. Re-executing doesnt work either. What do I do?

**Comment by benio2** [comment]
Hello there ,
Yes everything is working and it shows me that command is Executed but on
the target browser nothing is changing or happening.

**Comment by bcoles** [comment]
Which commands? All commands?

Do you get any output in terminal? Do you get any output in the browser development console?

**Comment by benio2** [comment]
[image: image.png]
this is what am getting

**Comment by bcoles** [comment]
> this is what am getting

The screenshot didn't come through.

Which command are you having trouble with?

Where did you get stuck during troubleshooting? Are there any errors in the browser console? Does BeEF output any errors to terminal?

**Comment by benio2** [comment]
I’ll send the screenshot again and am there’s no specific command, whatever
command am running through the beef browser it shows it’s executed, but
when am looking at the hooked browser nothings changing , for example the
alert box

**Comment by benio2** [comment]
[image: beef.PNG]
It's working.

**Comment by bcoles** [comment]
> but when am looking at the hooked browser nothings changing

Take a look at the browser development tools. See if there's any errors in the console or if any network requests are failing.

**Comment by benio2** [comment]
My main thing of using beef is to access the webcam of another
virtual machine, it’s apart of team project for uni to demo a hacking trick
and raise awareness if that make sense , so can I do that through beef

**Comment by benio2** [comment]
No fault showing

**Comment by bcoles** [comment]
> No fault showing

I don't understand. What is the problem?

**Comment by bcoles** [comment]
> access the webcam of another virtual machine
> so can I do that through beef

There are two modules to do this, although they have not been tested in many years:

* https://github.com/beefproject/beef/tree/master/modules/browser/webcam_flash
* https://github.com/beefproject/beef/tree/master/modules/browser/webcam_html5

There is also a module to check whether the hooked domain is permitted to access the webcam using Flash:

* https://github.com/beefproject/beef/tree/master/modules/browser/webcam_permission_check

**Comment by benio2** [comment]
Thanks, but how can i use them
