### ISSUE TITLE
Trace back ruby gems error 

### ISSUE THREAD

**Issue by rxeqz1** [beefproject/beef#2381]
Getting the following error when running ./beef from beef directory.

raceback (most recent call last):
        5: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
        4: from <internal:gem_prelude>:1:in `require'
        3: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `<top (required)>'
        2: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `require'
        1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:67:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:93:in `singleton class': undefined method `default_specifications_dir' for class `#<Class:Gem>' (NameError)

**Comment by bcoles** [comment]
Strange. It is not immediately obvious what the cause is, but possibly related to installing multiple versions of Ruby or an old version of rubygems.

Which operating system? Is `/usr/local/lib/site_ruby` from an operating system package? Which operating system?

You could try:

```
gem update --system
gem install bundler
bundle install
```

**Comment by bcoles** [comment]
It looks like someone else has had a similar issue.

https://github.com/rubygems/rubygems/issues/3068#issuecomment-778653415

This was suggested as a solution:

```
sudo gem update --system 3.0.6
```

**Comment by rxeqz1** [comment]
[](url)
![Screenshot_2022-04-01_03-19-59](https://user-images.githubusercontent.com/102776554/161181809-f6863be8-39b2-40a5-b2f9-bb015c05d11a.png)

**Comment by bcoles** [comment]
I presume that updating rubygems didn't work for you?

What operating system are you using? Are you using ruby from operating system packages?

**Comment by rxeqz1** [comment]
Im running on debian 

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.1"
VERSION_ID="2022.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

**Comment by bcoles** [comment]
```
gem --version
ruby --version
```

**Comment by rxeqz1** [comment]
┌──(root㉿kali)-[/home/rxeqz]
└─# gem --version
ruby --version
Traceback (most recent call last):
        5: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
        4: from <internal:gem_prelude>:1:in `require'
        3: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `<top (required)>'
        2: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `require'
        1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:67:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:93:in `singleton class': undefined method `default_specifications_dir' for class `#<Class:Gem>' (NameError)
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
                                                                                                                                                                               
┌──(root㉿kali)-[/home/rxeqz]
└─#

**Comment by bcoles** [comment]
> ┌──(root㉿kali)-[/home/rxeqz] └─# gem --version ruby --version Traceback (most recent call last): 5: from internal:gem_prelude:1:in `<internal:gem_prelude>' 4: from <internal:gem_prelude>:1:in `require' 3: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `<top (required)>' 2: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `require' 1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:67:in `<top (required)>' /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:93:in `singleton class': undefined method `default_specifications_dir' for class `#Class:Gem' (NameError) ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
> 
> ┌──(root㉿kali)-[/home/rxeqz] └─#

Looks like something is horribly broken with your ruby installation. Re-installing ruby may help.

```
apt-get install ruby ruby-dev rubygems
```

I recently updated my Kali test box to Ruby 3. BeEF works.

If both Ruby 2 and Ruby 3 are installed, you may need to ensure that dependencies are installed with the correct version.

```
bundle3.0 install
bundle3.0 exec ./beef
```

**Comment by rxeqz1** [comment]
┌──(root㉿kali)-[/home/rxeqz/beef]
└─# ./beef   
[ 3:48:26][!] ERROR: Default username and password in use!
[ 3:48:26]    |_  Change the beef.credentials.passwd in config.yaml

**Comment by bcoles** [comment]
You need to change the password in `config.yaml`.

You can find `config.yaml` in the root of the BeEF directory. The password is set in the `passwd` key.

**Comment by rxeqz1** [comment]
[
![1](https://user-images.githubusercontent.com/102776554/161186891-d325bad9-43c5-47c2-9992-a5856111aae3.png)
[
![3](https://user-images.githubusercontent.com/102776554/161186904-cfa20c06-c2cf-436c-a29a-e122dc481191.png)
]([](url)](![2](https://user-images.githubusercontent.com/102776554/161186899-3f9d4657-e92a-465c-9fe5-2cb89fe65843.png)))

**Comment by rxeqz1** [comment]
[
![1](https://user-images.githubusercontent.com/102776554/161186947-3c44eada-3e0b-4bd8-a65f-9196e561cd58.png)
[
![3](https://user-images.githubusercontent.com/102776554/161186965-f43bb507-586f-434e-8a30-49c996c9d51f.png)
]([](url)](![2](https://user-images.githubusercontent.com/102776554/161186953-fca5ff4b-15e2-4b3c-b8e2-a85199d3e1af.png)))

**Comment by rxeqz1** [comment]
[
![3](https://user-images.githubusercontent.com/102776554/161187001-f8d5fad5-5455-49f0-acc1-7231ceca575c.png)
](url)

**Comment by rxeqz1** [comment]
[
![2](https://user-images.githubusercontent.com/102776554/161187018-ebb0ede2-99db-4319-9f0f-8078b3b91336.png)
](url)

**Comment by bcoles** [comment]
Yes you will need to update the `config.yaml` file with your changes.

**Comment by rxeqz1** [comment]
I can due to read only permissions

**Comment by bcoles** [comment]
> I can due to read only permissions

If the file is owned by root then you will to edit the file with root privileges.

As you put beef in your home directory, you could change ownership to your user instead.

```
sudo chown -R rxeqz:rxeqz /home/rxeqz/beef
```

**Comment by rxeqz1** [comment]
Working thank you :+1:

**Comment by TRUTHANIKET** [comment]
> > ┌──(root㉿kali)-[/home/rxeqz] └─# gem --version ruby --version Traceback (most recent call last): 5: from internal:gem_prelude:1:in `<internal:gem_prelude>' 4: from <internal:gem_prelude>:1:in `require' 3: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `<top (required)>' 2: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `require' 1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:67:in `<top (required)>' /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:93:in `singleton class': undefined method `default_specifications_dir' for class `#Class:Gem' (NameError) ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
> > 
> > ┌──(root㉿kali)-[/home/rxeqz] └─#
> 
> Looks like something is horribly broken with your ruby installation. Re-installing ruby may help.
> 
> ```
> apt-get install ruby ruby-dev rubygems
> ```
> 
> I recently updated my Kali test box to Ruby 3. BeEF works.
> 
> If both Ruby 2 and Ruby 3 are installed, you may need to ensure that dependencies are installed with the correct version.
> 
> ```
> bundle3.0 install
> bundle3.0 exec ./beef
> ```
> 

I am getting bundle3.0: command not found

**Comment by TRUTHANIKET** [comment]
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    rubocop (~> 1.42.0) was resolved to 1.42.0, which depends on
      Ruby (>= 2.6.0)
  Current Ruby version:
    Ruby (= 2.5.8)

This is the error i am facing 
![IMG_20230114_152104.jpg](https://user-images.githubusercontent.com/100013837/212466206-e1b99e75-d975-4a78-bd52-f0efa84e70d7.jpg)

**Comment by bcoles** [comment]
> Current Ruby version:
> Ruby (= 2.5.8)

Support for Ruby 2.5 ended almost 2 years ago on March 31, 2021.

https://endoflife.software/programming-languages/server-side-scripting/ruby

**Comment by TRUTHANIKET** [comment]
> > Current Ruby version:
> > Ruby (= 2.5.8)
> 
> Support for Ruby 2.5 ended almost 2 years ago on March 31, 2021.
> 
> https://endoflife.software/programming-languages/server-side-scripting/ruby
> 

I upgraded Ruby 3.0 but still it's on 2.5 idk why so is there a fix for it

**Comment by bcoles** [comment]
> > > Current Ruby version:
> > > Ruby (= 2.5.8)
> > 
> > 
> > Support for Ruby 2.5 ended almost 2 years ago on March 31, 2021.
> > https://endoflife.software/programming-languages/server-side-scripting/ruby
> 
> I upgraded Ruby 3.0 but still it's on 2.5 idk why so is there a fix for it

You may have multiple `ruby`, `gem` and `bundle` utilities.

You can use tab completion in your shell to see if other versions are available.

You could try something like this:

```
gem3 install bundler
bundle3 install
bunde3 exec ./beef
```

BeEF is written in Ruby. It requires a working Ruby environment.
