### ISSUE TITLE
How to turn on auto open web browser

### ISSUE THREAD

**Issue by createvi** [beefproject/beef#2383]
I Installed BeEF using apt. it works well but i need to ask one thing. How can i disable the automatic web browser opening when starting BeEF. I am using Kali Linux.

**Comment by bcoles** [comment]
You can disable the automatic browser opening by removing this line from the `beef-xss` script

```
# which beef-xss
/usr/bin/beef-xss

# tail -n 3 /usr/bin/beef-xss
## Open browser
xdg-open "${URL}" 2>/dev/null >/dev/null &

```

The `beef-xss` package is managed by the Kali team. This line may re-appear when they update the package.
