### ISSUE TITLE
ERROR: you have held broken packages, PARROT OS

### ISSUE THREAD

**Issue by Starscreemn01** [beefproject/beef#2389]
# Submit Issue
$sudo apt-get install beef-xss
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ruby-activerecord : Depends: ruby-activemodel (= 2:6.0.3.7+dfsg-2) but 2:6.1.4.6+dfsg- 1 ~ fto11+1 is to be installed
                     Depends: ruby-activesupport (= 2:6.0.3.7+dfsg-2) but 2:6.1.4.6+dfsg-1 ~ fto11+1 is to be installed
E: Unable to correct problems, you have held broken packages.

(edited the "~ " to have spaced around it because it kept striking out the line)
## Summary

**Q:** Please provide a brief summary of the issue that you experienced.
**A:** I am trying to install beef on parrot os and im being met with this broken packages error

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:**
not installed

2. **Ruby Version:**
ruby 2.7.4p191

3. **Browser Details (e.g. Chrome v81.0):**
Mozilla Firefox 91.8.0esr

4. **Operating System (e.g. OSX Catalina):**
Parrot OS 5.0 linux

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:** no

**Q:** Have you enabled or disabled any BeEF extensions?
**A:** neither, its not installed

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
<br /> install the software
**Actual Behaviour:**
<br /> throws broken package error

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1. sudo apt-get install beef-xss

## Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be retrieved by following the instructions towards the top of the issue template

**Comment by bcoles** [comment]
This is a ParrotOS package issue.

You can work around this issue by clone BeEF from GitHub.

**Comment by Starscreemn01** [comment]
> This is a ParrotOS package issue.
> 
> You can work around this issue by clone BeEF from GitHub.

Thank you so much for the reply!!! I will try that! 
So use git clone and try and download the package? 

And hopefully I can get this going. I'm sad parrot 5.0 didn't come with beef pre-installed. Thank you for all the help!!

**Comment by bcoles** [comment]
> So use git clone and try and download the package?

git clone and install manually.

```
git clone https://github.com/beefproject/beef
cd beef
bundle install
```

**Comment by Starscreemn01** [comment]
Trying this right now! I did do that to begin with and got an error, but I did not do bundle install, I will try that! I'll msg back what happens.

**Comment by Starscreemn01** [comment]
$bundle install
Using rake 13.0.6
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.7.0
  /var/lib/gems/2.7.0/build_info
  /var/lib/gems/2.7.0/cache
  /var/lib/gems/2.7.0/doc
  /var/lib/gems/2.7.0/extensions
  /var/lib/gems/2.7.0/gems
  /var/lib/gems/2.7.0/plugins
  /var/lib/gems/2.7.0/specifications
Using concurrent-ruby 1.1.9
Using i18n 1.10.0
Using minitest 5.15.0
Using tzinfo 2.0.4
Using activesupport 7.0.2.2
Using activemodel 7.0.2.2
Using activerecord 7.0.2.2
Using public_suffix 4.0.6
Using addressable 2.8.0
Using ansi 1.5.0
Using ast 2.4.2
Using fiber-local 1.0.0
Using console 1.13.1
Using nio4r 2.5.8
Using timers 4.3.3
Using async 1.30.1
Using async-io 1.32.2
Using async-dns 1.3.0
Using buftok 0.2.0
Using bundler 2.1.4
Using daemons 1.4.1
Using unf_ext 0.0.7.7
Using unf 0.1.4
Using domain_name 0.5.20190701
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.3
Using equalizer 0.0.11
Using erubis 2.7.0
Using espeak-ruby 1.0.5
Using execjs 2.8.1
Using ffi 1.15.4
Using ffi-compiler 1.0.1
Using hashie 5.0.0
Using hashie-forbidden_attributes 0.1.1
Using http-cookie 1.0.4
Using http-form_data 2.3.0
Using http-parser 1.2.3
Using http 4.4.1
Using http-accept 1.7.0
Using json 2.6.1
Using maxmind-db 1.1.1
Using thread_safe 0.3.6
Using memoizable 0.4.2
Using mime-types-data 3.2021.1115
Using mime-types 3.4.1
Using mojo_magick 0.6.6
Using msgpack 1.4.2
Using msfrpc-client 1.1.2
Using multipart-post 2.1.1
Using ruby2_keywords 0.0.5
Using mustermann 1.1.1
Using naught 1.1.0
Using netrc 0.11.0
Using otr-activerecord 2.1.1
Using parallel 1.21.0
Using parseconfig 1.1.2
Using parser 3.1.1.0
Using rqrcode_core 0.2.0
Using qr4r 0.6.1
Using rack 2.2.3
Using rack-protection 2.2.0
Using rainbow 3.1.1
Using regexp_parser 2.2.1
Using rest-client 2.1.0
Using rexml 3.2.5
Using rubocop-ast 1.16.0
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.1.0
Using rubocop 1.26.0
Using rubyzip 2.3.2
Using rushover 0.3.0
Using simple_oauth 0.3.1
Using tilt 2.0.10
Using sinatra 2.2.0
Using slack-notifier 2.4.0
Using sqlite3 1.4.2
Using sync 0.5.0
Using tins 1.29.1
Using term-ansicolor 1.7.1
Using thin 1.8.1
Using twitter 7.0.0
Using uglifier 4.2.0
Using webrick 1.7.0
Using xmlrpc 0.3.2
Bundle complete! 41 Gemfile dependencies, 86 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.




this is what it did, do i run sudo bundle install?

**Comment by bcoles** [comment]
> this is what it did, do i run sudo bundle install?

no

> i tried just installing it with ./install and it gave this error.

If `bundle install` worked you likely won't need to run the install script.

Simply run `./beef`.

**Comment by bcoles** [comment]
> It was weird how it was throwing that error but still installed?

The install script is meant for users who struggle with `bundle install`.

> do you know anything about the beef over Wan application?

For running BeEF behind a reverse proxy, or port forwarding, or tunnel, refer to:

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
