### ISSUE TITLE
Beef Issue

### ISSUE THREAD

**Issue by abhishek-pandit1** [beefproject/beef#2391]
I have successfully login to the UI page of beef then I open the demo page link and advance page link in the tab and it open successfully in the tab but when I go to UI panel and see hooked online browsers and offline browsers , then it does not shows anything here no ip address and any other thing. I have tried thousands of times with this but it does not fetching any IP address or anything . Please help me

**Comment by abhishek-pandit1** [comment]
if you know please help me .

**Comment by bcoles** [comment]
Where did you get stuck during troubleshooting?

**Comment by abhishek-pandit1** [comment]
I copy and paste the link easily in the new tab of beef butcher but after opened that page no browser detail get fetched.

**Comment by bcoles** [comment]
You can use the browser developer tools to debug browser issues. The `Network` tab will show network traffic. The `Console` tab will show error messages.

**Comment by abhishek-pandit1** [comment]
Okk I will try

**Comment by abhishek-pandit1** [comment]
Can you please tell me all the steps of running beef and fetching online and offline browsers

**Comment by bcoles** [comment]
> Can you please tell me all the steps of running beef and fetching online and offline browsers

That's pretty much the jist of it. Run BeEF and open the web interface. You will see the online and offline browsers.

**Comment by abhishek-pandit1** [comment]
sir now it's done . thank you so much for your effort .

**Comment by DeezyE** [comment]
Closing resolved
