### ISSUE TITLE
Error Invalid Public hostname 

### ISSUE THREAD

**Issue by finestfew** [beefproject/beef#2394]
Q: Please provide a brief summary of the issue that you experienced.

Opened terminal and hit "ngrok http 3000".

Then copy-pasted the shown forwarding link with "ngrok.io" ending into beef's config file at the public section as directed on the FAQ page here. Set the port to 443 and https to true.

launched beef from another terminal window, it says, Error: invalid public hostname https: "something"ngrok.io
What do I do?

Environment
Please identify the environment in which your issue occurred.

BeEF Version: 5.4.0

Ruby Version: 2.7

Browser Details (e.g. Chrome v81.0): Firefox

Operating System (e.g. OSX Catalina): Linux Mint 20.3 Xfce

Configuration
Q: Have you made any changes to your BeEF configuration?
A: Username/password. Set the http server host from 0.0.0.0 to localhost. Edited out the comments in public section and made modifications for ngrok tunneling as mentioned above

Q: Have you enabled or disabled any BeEF extensions?
A: No

Expected vs. Actual Behaviour
Expected Behaviour:

Beef should have started and performed normally

Actual Behaviour:

It says Error invalid public hostname. It also displays a warning that my system language En_In is not UTF-8 compatible but beef worked normally earlier when I used it on my local network without ngrok even with this warning there so I don't think it's the issue.

config file is here 
http://paste.sensio.no/SumpeteKaffebar

**Comment by bcoles** [comment]
`bbef.public.host` expects a host name not a URL.
