### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by Magmoetvisser** [beefproject/beef#2395]
I use a virtual box with the linux / beEF program on it. But can i sent te link to myself (without a VB) and is there a way to open it cuz i get a error. bellow picture.
What do i need to do to open the links in a google tab?

![Screenshot_96](https://user-images.githubusercontent.com/103457041/163606720-a93b9a5b-eef5-40ba-b308-c2b47783617a.png)

**Comment by bcoles** [comment]
`127.0.0.1` is the local loopback network interface. You will need to use a URL for one of the LAN interfaces.
