### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by theorchorde** [beefproject/beef#2402]
So, i have a problem and i cant find solution, for example, i'm sending beef link to my target and when my target enter to my link i run js script to pop up google extension app, until here everything is good, after somehow i need to press one button in this extension, i cant find solution how to do it, can some one help me? xss attack is not helping.
After i found another way to do it, is there any way to take google extension app link and put in BeEF redirect, if it will be possible i will solve my problem, i tried it many times but it gives me error because origin policy. Is there any other way to do it?

**Comment by bcoles** [comment]
Is this different from the other issue you posted then ignored? #2399

> after somehow i need to press one button in this extension, i cant find solution how to do it, can some one help me?

If you can load the page in an iframe your could try a clickjacking attack.

**Comment by theorchorde** [comment]
look my target is opening a page it doest matter which page is it, because with JS i'm opening google extension app, my main goal is to click in one button in this extension.

**Comment by bcoles** [comment]
The hooked page does not have access to pages on other origins. Accessing other origins requires breaking the browser extension security model. You will need to bypass the same origin policy.

Here are some references which may help with your research:

* https://threatpost.com/web-apps-browser-extensions-backdoors/141061/
* https://resources.infosecinstitute.com/topic/owned-by-chrome-extensions/
* https://www.techtarget.com/searchenterprisedesktop/tip/What-IT-needs-to-know-about-Chrome-extension-security-issues
* Malicious Extensions
  * https://cybernews.com/news/google-chrome-vulnerability-provides-a-backdoor-to-spy-on-millions/
  * https://www.darkreading.com/application-security/malicious-code-injected-via-google-chrome-extension-highlights-app-risks
* Vulnerable Extensions
  * https://www.securityweek.com/flaw-evernote-extension-allows-hackers-steal-data
  * https://thehackerblog.com/reading-your-emails-with-a-readwrite-chrome-extension-same-origin-policy-bypass-8-million-users-affected/

The https://crxcavator.io website is useful for analysing an extension. This will show which permissions and extension has, use of potentially dangerous functions which may allow XSS, and outdated bundled libraries which are potentially vulnerable to XSS.
