### ISSUE TITLE
BeEF 

### ISSUE THREAD

**Issue by shadow4148b** [beefproject/beef#2404]
Everything is on the newest version

$ sudo beef-xss
[i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1...

GeoIp :----
└─# geoipupdate
error loading configuration file /etc/GeoIP.conf: the `AccountID` option is required

**Comment by Kingris9090** [comment]
> Everything is on the newest version
> 
> $ sudo beef-xss [i] GeoIP database is missing [i] Run geoipupdate to download / update Maxmind GeoIP database [_] Please wait for the BeEF service to start. [_] [_] You might need to refresh your browser once it opens. [_] [_] Web UI: http://127.0.0.1:3000/ui/panel [_] Hook: <script src="http://:3000/hook.js"></script> [*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>
> 
> System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down
> 
> [*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1...
> 
> GeoIp :---- └─# geoipupdate error loading configuration file /etc/GeoIP.conf: the `AccountID` option is required

**Comment by bcoles** [comment]
What is the problem?

**Comment by bcoles** [comment]
Looks like an issue with the systemd configuration. As a workaround you can clone BeEF from GitHub,

**Comment by bcoles** [comment]
Are you using WSL? I so, you cannot use the `beef-xss` wrapper because it uses systemd. WSL does not use systemd.

You can try running BeEFF manually.

```
cd /usr/share/beef-xss/
./beef
```
