### ISSUE TITLE
Beef runs fine but UI page times out 

### ISSUE THREAD

**Issue by iamtheef** [beefproject/beef#2414]
# Submit Issue

Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/v0.5.4.0).

Please do your best to provide as much information as possible. It will help substantially if you can enable and provide debugging logs with your issue. Instructions for enabling debugging logs are below:

1. In the `config.yaml` file of your BeEF root folder set debug and client_debug (lines 11 & 13 respectively) to `true`
   * If using a standard installation of `beef-xss` the root folder will typically be `/usr/share/beef-xss`
2. Reproduce your error
3. Retrieve your client-side logs from your browser's developer console (Ctrl + Shift + I)
4. Retrieve your server-side logs from `~/.beef/beef.log`
5. **If using `beef-xss`:** Retrieve your service logs using `journalctl -u beef-xss`

Thank you, this will greatly aid us in identifying the root cause of your issue :)

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**
Feel free to open it back up if you continue to have issues. 

## Summary

**Q:**  
**A:** Beef Server runs ok as expected but admin UI page times out.

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:** 0.5.4.0

2. **Ruby Version:** 2.7.4

3. **Browser Details (e.g. Chrome v81.0):** Brave 1.38.111

4. **Operating System (e.g. OSX Catalina):**  Ubuntu 20.04.4 LTS

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:** No, except admin credits and some other ports I tried to run it.

**Q:** Have you enabled or disabled any BeEF extensions?
**A:** No.

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
<br /> Seeing the admin UI panel.
**Actual Behaviour:**
<br /> Times out every time.

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1. After installing `./beef`
2. Visiting the admin panel on https://[my server]:3000/ui/panel

Log : [beef.log](https://github.com/beefproject/beef/files/8646723/beef.log)

## Additional Information

Port 3000 is open, no overlapping processes exist, no other error is logged. No output when curl'd locally. Tried to run it on other ports with no luck.

**Comment by bcoles** [comment]
> Visiting the admin panel on https://[my server]:3000/ui/panel

Does this mean you enabled HTTPS in the config file? BeEF runs with clear text HTTP by default and the console output shows BeEF is not using HTTPS.

**Comment by bcoles** [comment]
Are you able to access any pages on the web server at all? The index page `/` ? The demos `/demos/basic.html` ?

Enabling HTTP debugging might offer some clues (`beef.http.debug`).

The bad news is that there's currently a bug in the debug code that triggers exceptions. The good news is that the exceptions are only triggered once the web server is accessed, which means you can at least confirm that the web server is *trying* to respond to respond to requests if BeEF starts spitting errors.

**Comment by iamtheef** [comment]
I can access the demos/basic.html but only locally with curl. I can't load anything from outside the server.

`I, [2022-05-08T12:08:19.660641 #168370]  INFO -- : Thin web server (v1.8.1 codename Infinite Smoothie)
D, [2022-05-08T12:08:19.660690 #168370] DEBUG -- : Debugging ON
I, [2022-05-08T12:08:19.660751 #168370]  INFO -- : Maximum connections set to 1024
I, [2022-05-08T12:08:19.660810 #168370]  INFO -- : Listening on 0.0.0.0:3000, CTRL+C to stop`

This is all the http.debug logs. No external requests are appeared here

and this is after enabling http.debug and trying to hit the server locally:
`E, [2022-05-08T12:10:33.648905 #168370] ERROR -- : Unexpected error while processing request: undefined method `each' for nil:NilClass
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/rack-2.2.3/lib/rack/utils.rb:429:in `initialize'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/rack-2.2.3/lib/rack/utils.rb:422:in `new'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/rack-2.2.3/lib/rack/utils.rb:422:in `[]'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/rack-2.2.3/lib/rack/common_logger.rb:39:in `call'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/sinatra-2.2.0/lib/sinatra/base.rb:255:in `call'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
	/home/iamtheef/.rvm/gems/ruby-2.7.4@beef/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
	/home/iamtheef/beef/core/main/server.rb:156:in `start'
	./beef:278:in `<main>'`

**Comment by bcoles** [comment]
> I can't load anything from outside the server.

Does this mean you're using the `beef.public.host` and `beef.public.port` settings ?

> and this is after enabling http.debug and trying to hit the server locally:

yeah that's the expected buggy debug output

**Comment by iamtheef** [comment]
>> Does this mean you're using the `beef.public.host` and `beef.public.port` settings ?
> Yes

**Comment by iamtheef** [comment]
> > Visiting the admin panel on https://[my server]:3000/ui/panel
> 
> Does this mean you enabled HTTPS in the config file? BeEF runs with clear text HTTP by default and the console output shows BeEF is not using HTTPS.

No I haven't enabled HTTPS btw. Should I? Would it make any difference?

**Comment by bcoles** [comment]
> > Does this mean you're using the `beef.public.host` and `beef.public.port` settings ?
> 
> Yes

Ok. There's your problem.

BeEF is incapable of performing modifications to network routes and firewall settings. You will need to configure port forwarding or tunneling. Refer to:

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by iamtheef** [comment]
Thanks @bcoles ! Working on it!
`https://<your-id>.ngrok.io/ui/panel` what is "<your-id>" referring to? The auth key I got from ngrok?

**Comment by bcoles** [comment]
> Thanks @bcoles ! Working on it! `https://<your-id>.ngrok.io/ui/panel` what is "your-id" referring to? The auth key I got from ngrok?

ngrok gives you a URL. It should look something like that.

**Comment by iamtheef** [comment]
Got it to work eventually! It just doesn't seem to be hooking now. It only loads as text the hook page. And I don't see any machines hooked on admin panel.

**Comment by bcoles** [comment]
>  It only loads as text the hook page.

What does this mean? Are you trying to load the `hook.js` file in a browser? That won't work. The BeEF hook is written in JavaScript and needs to be executed. Try one of the demo pages.

**Comment by iamtheef** [comment]
Yes! Worked! Thanks a lot @bcoles!
