### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by eoksum** [beefproject/beef#2418]
## Summary

**Q:** Please provide a brief summary of the issue that you experienced.
**A:** I was trying out BeEF and then suddenly BeEF stopped working. I enabled DevTools and checked the Network tab to see what is going on and I realized calls to hook.js is failing due to a Internal Server Error. I tried stopping and starting the Docker container and BeEF to see if that fixes the issue, it didn't work. However, when I tried to start BeEF after I restarted the Docker container I encountered this error during starting BeEF:

<pre>2022-05-10 15:51:53 - NameError - uninitialized constant BeEF::Core::Command::Read_inotes:
        /beef/core/main/handlers/modules/command.rb:52:in `add_command_instructions'
        /beef/core/main/handlers/hookedbrowsers.rb:97:in `block (2 levels) in <class:HookedBrowsers>'
        /usr/local/bundle/gems/activerecord-7.0.2.2/lib/active_record/relation/delegation.rb:88:in `each'
        /usr/local/bundle/gems/activerecord-7.0.2.2/lib/active_record/relation/delegation.rb:88:in `each'
        /beef/core/main/handlers/hookedbrowsers.rb:97:in `block in <class:HookedBrowsers>'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1042:in `route_eval'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1021:in `block in route!'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `each'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `route!'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1140:in `block in dispatch!'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'
        /usr/local/bundle/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
        /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
        /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
        /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
        /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'
        /usr/local/bundle/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
        /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /usr/local/bundle/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
        /usr/local/bundle/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
        /beef/core/main/server.rb:156:in `start'
        ./beef:278:in `<main>'</pre>

This NameError repeats every second, rendering BeEF Framework useless due to Internal Server Error.

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:** BeEF 0.5.4.0 Running on Docker container

2. **Ruby Version:** ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux-musl]

3. **Browser Details (e.g. Chrome v81.0):** Firefox v100.0

4. **Operating System (e.g. OSX Catalina):** Windows 11

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:** No, except enabling debug mode after the issue and setting username and password.

**Q:** Have you enabled or disabled any BeEF extensions?
**A:** Tried executing IBM inote reading commands. Except of that, no.

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
No Internal Server Error during hook.js communication after testing IBM inote related tools
**Actual Behaviour:**
Internal Server Error during hook.js communication.

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1. Install BeEF 0.5.4.0 on a Docker container which is running with WSL on Windows 11
2. Execute IBM inote related commands (I'm not sure which one caused this, but it happened after I was testing this out)

## Additional Information

Screenshot: https://prnt.sc/pro0_zziKdBq
Screenshot of DevTools: https://prnt.sc/gvQ_y9IaVMDn

**Comment by eoksum** [comment]
It fixed when I cleaned the cookies on target browser and unhooked it. I think there is a typo or something in inote module.

**Comment by bcoles** [comment]
The inotes modules were updated a few weeks ago.

**Comment by DeezyE** [comment]
@eoksum thanks for this very well filled out issue!

So is it functioning correctly now then?

**Comment by eoksum** [comment]
It does function correctly if I clean the cookies on the target browser but I would recommend you or someone, checking the source code of the related module to figure out what caused this issue to prevent it from happening again in the future to someone else. I don't have any acquintance with Ruby or BeEF Framework codeflow therefore I can't fix it :(
