### ISSUE TITLE
Bundling suck                 

### ISSUE THREAD

**Issue by Timodo22** [beefproject/beef#2422]
an error occurred while installing sqlite3 (1.4.2), and Bundler
cannot continue.                                                             
Make sure that `gem install sqlite3 -v '1.4.2' --source                      
'https://rubygems.org/'` succeeds before bundling.

**Comment by Timodo22** [comment]
sorry didnt work buddy

**Comment by Timodo22** [comment]
> 

whats ur discord?

**Comment by bcoles** [comment]
https://discord.gg/rKh2fhz5

**Comment by DeezyE** [comment]
`Make sure that gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/' succeeds before bundling.`

Did you run this?
If so what was the result?
