### ISSUE TITLE
Beef authentication 404 not found

### ISSUE THREAD

**Issue by luckysingh070** [beefproject/beef#2424]
# Submit Issue

Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/v0.5.4.0).

Please do your best to provide as much information as possible. It will help substantially if you can enable and provide debugging logs with your issue. Instructions for enabling debugging logs are below:

1. In the `config.yaml` file of your BeEF root folder set debug and client_debug (lines 11 & 13 respectively) to `true`
   * If using a standard installation of `beef-xss` the root folder will typically be `/usr/share/beef-xss`
2. Reproduce your error
3. Retrieve your client-side logs from your browser's developer console (Ctrl + Shift + I)
4. Retrieve your server-side logs from `~/.beef/beef.log`
5. **If using `beef-xss`:** Retrieve your service logs using `journalctl -u beef-xss`

Thank you, this will greatly aid us in identifying the root cause of your issue :)

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**
Feel free to open it back up if you continue to have issues. 

## Summary

**Q:** Please provide a brief summary of the issue that you experienced.
**A:**

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:**

2. **Ruby Version:**

3. **Browser Details (e.g. Chrome v81.0):**

4. **Operating System (e.g. OSX Catalina):**

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:**

**Q:** Have you enabled or disabled any BeEF extensions?
**A:**

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
<br />
**Actual Behaviour:**
<br />

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1.

## Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be retrieved by following the instructions towards the top of the issue template.

**Comment by luckysingh070** [comment]
Please help me

**Comment by luckysingh070** [comment]
My beef authentication is 404 not found

**Comment by bcoles** [comment]
Provide logs. Provide screenshots.

**Comment by luckysingh070** [comment]
![Uploading Screenshot_2022-05-19-13-50-22-72_8659c1e795b4b4239e38d87c88c077b3.jpg…]()

**Comment by bcoles** [comment]
When you start BeEF, you will get output like this:

```
[ 4:33:47][>] Event: BeEF server started
[ 4:33:47][*] 8 extensions enabled:
[ 4:33:47]    |   XSSRays
[ 4:33:47]    |   Social Engineering
[ 4:33:47]    |   Requester
[ 4:33:47]    |   Proxy
[ 4:33:47]    |   Network
[ 4:33:47]    |   Events
[ 4:33:47]    |   Demos
[ 4:33:47]    |_  Admin UI
[ 4:33:47][*] 316 modules enabled.
[ 4:33:47][*] 2 network interfaces were detected.
[ 4:33:47][*] running on network interface: 127.0.0.1
[ 4:33:47]    |   Hook URL: http://127.0.0.1:3000/hook.js
[ 4:33:47]    |_  UI URL:   http://127.0.0.1:3000/ui/panel
[ 4:33:47][*] running on network interface: 192.168.200.130
[ 4:33:47]    |   Hook URL: http://192.168.200.130:3000/hook.js
[ 4:33:47]    |_  UI URL:   http://192.168.200.130:3000/ui/panel
[ 4:33:47][*] RESTful API key: c587014472aa152bf8aa8fdfbb8fb879f8ca5ade
[ 4:33:47][*] HTTP Proxy: http://127.0.0.1:6789
[ 4:33:47][*] BeEF server started (press control+c to stop)
```

Browse to the `UI URL`. In this example: `http://192.168.200.130:3000/ui/panel`

**Comment by luckysingh070** [comment]
No there is no

**Comment by luckysingh070** [comment]
![Uploading Screenshot_2022-05-19-14-06-06-57_8659c1e795b4b4239e38d87c88c077b3.jpg…]()

**Comment by luckysingh070** [comment]
There is something like this

**Comment by bcoles** [comment]
> ![Uploading Screenshot_2022-05-19-13-50-22-72_8659c1e795b4b4239e38d87c88c077b3.jpg…]()
> ![Uploading Screenshot_2022-05-19-14-06-06-57_8659c1e795b4b4239e38d87c88c077b3.jpg…]()

You need to wait until the screenshot finishes uploading before posting.

**Comment by luckysingh070** [comment]
When I start beef . It automatically start ui panel then in my browser show ''Not Found

The requested URL was not found on this server.
Apache/2.4.53 (Debian) Server at 127.0.0.1 Port 3000"

**Comment by bcoles** [comment]
> The requested URL was not found on this server.

```
http://127.0.0.1:3000/ui/panel
```

**Comment by luckysingh070** [comment]
Same result

**Comment by bcoles** [comment]
Are you running BeEF from GitHub or `beef-xss` from an operating system package?

**Comment by luckysingh070** [comment]
It was already in my Linux
And start from there

**Comment by bcoles** [comment]
Post output:

```
service beef-xss status
curl -isk http://127.0.0.1:3000/ui/panel
lsof -i :3000
```

**Comment by luckysingh070** [comment]
service beef-xss status
beef-xss: unrecognized service

**Comment by luckysingh070** [comment]
curl -isk http://127.0.0.1:3000/ui/panel
HTTP/1.1 404 Not Found
Date: Thu, 19 May 2022 08:48:51 GMT
Server: Apache/2.4.53 (Debian)
Content-Length: 273
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.53 (Debian) Server at 127.0.0.1 Port 3000</address>
</body></html>

**Comment by luckysingh070** [comment]
There is no output for lsof -i :3000

**Comment by bcoles** [comment]
> Server: Apache/2.4.53 (Debian)

That does not look like BeEF. Perhaps something else is already running on port 3000.

Post output:

```
journalctl -u beef-xss
```

How are you running BeEF? `beef-xss` ?

**Comment by luckysingh070** [comment]
journalctl -u beef-xss                                                                                         
No journal files were found.
-- No entries --

**Comment by bcoles** [comment]
How are you running BeEF? `beef-xss` ?

**Comment by bcoles** [comment]
Are you using WSL?

**Comment by luckysingh070** [comment]
I am new on it

**Comment by bcoles** [comment]
You cannot use the `beef-xss` wrapper because it uses systemd. WSL does not use systemd.

You will need to run BeEF manually.

```
cd /usr/share/beef-xss/
./beef
```

**Comment by luckysingh070** [comment]
How can I delete beef 
And reinstall by GitHub

**Comment by bcoles** [comment]
> How can I delete beef And reinstall by GitHub

```
cd ~
git clone https://github.com/beefproject/beef/
cd beef
bundle install
./beef
```

**Comment by bcoles** [comment]
> How to delete this one

You don't need to removing the existing beef install to clone from GitHub.

**Comment by luckysingh070** [comment]
How to solve this.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by bcoles** [comment]
> How to solve this. System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down

https://github.com/beefproject/beef/issues/2424#issuecomment-1131436857

**Comment by luckysingh070** [comment]
How I can remove this msg

**Comment by bcoles** [comment]
> How I can remove this msg

https://github.com/beefproject/beef/issues/2424#issuecomment-1131436857
