### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down problem

### ISSUE THREAD

**Issue by luckysingh070** [beefproject/beef#2425]
How to solve 
 System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by bcoles** [comment]
You cannot use the `beef-xss` wrapper because it uses systemd. WSL does not use systemd.

You will need to run BeEF manually.

```
cd /usr/share/beef-xss/
./beef
```

**Comment by luckysingh070** [comment]
I am not using wsl

**Comment by bcoles** [comment]
What operating system are you using?

**Comment by luckysingh070** [comment]
Kali lunix

**Comment by bcoles** [comment]
> Kali lunix

Kali Linux on WSL?

**Comment by luckysingh070** [comment]
No

**Comment by bcoles** [comment]
Your system has not been booted with systemd as init system (PID 1). You cannot use the `beef-xss` wrapper because it uses systemd.

You will need to run BeEF manually.

```
cd /usr/share/beef-xss/
./beef
```

**Comment by luckysingh070** [comment]
Kali in virtual machine

**Comment by luckysingh070** [comment]
It is working on my other system

**Comment by bcoles** [comment]
> It is working on my other system

Your systemd configuration is broken. I don't know why.

Does BeEF work when you run it manually?

```
cd /usr/share/beef-xss/
./beef
```

**Comment by luckysingh070** [comment]
How i configure back

**Comment by bcoles** [comment]
> How i configure back

I don't know what that means.

**Comment by bcoles** [comment]
You have three options.

1. Run BeEF manually.

```
cd /usr/share/beef-xss/
./beef
```

2. Clone and run BeEF from GitHub.

```
cd ~
git clone https://github.com/beefproject/beef/
cd beef
bundle install
./beef
```

3. Fix your systemd

**Comment by luckysingh070** [comment]
I want to fix my systemd

**Comment by luckysingh070** [comment]
Please tell me how to fix it

**Comment by bcoles** [comment]
Does BeEF work when you run it manually?

```
cd /usr/share/beef-xss/
./beef
```

**Comment by luckysingh070** [comment]
I want to run beef_over_wan
