### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ridhamsharma12345** [beefproject/beef#2428]
This script will install BeEF and its required dependencies (including operating system packages).
Are you sure you wish to continue (Y/n)? y
[INFO]  Detecting OS...
[INFO]  Operating System: Linux
[INFO]  Launching Linux install...
[INFO]  Detecting Linux OS distribution...
[FATAL]  Unable to locate installer for your Linux distribution

**Comment by horllste** [comment]
Which Linux distribution are you using?

**Comment by ridhamsharma12345** [comment]
Termux

**Comment by ridhamsharma12345** [comment]
Termux

**Comment by bcoles** [comment]
Termux isn't supported.

BeEF used to work on Termux in the past. I have no idea if it still does. It should be as simple as cloning the repository and running `bundle install`.
