### ISSUE TITLE
Ruby platform x64-mingw-ucrt is not supported.

### ISSUE THREAD

**Issue by C4M2TJ** [beefproject/beef#2434]
Ruby platform x64-mingw-ucrt is not supported.
it keeps saying that every time i try and start beef using the command 
ruby beef

**Comment by bcoles** [comment]
Windows is not supported.

https://github.com/beefproject/beef/blob/cbe9f66990084a321ef790518a25ebeae8a054be/beef#L25-L33

**Comment by wheatley** [comment]
Closed has windows not support

**Comment by epenflow** [comment]
ive same issue any solution so far?
