### ISSUE TITLE
Browser Versions 100+

### ISSUE THREAD

**Issue by OlMi1** [beefproject/beef#2436]
Hey there,

using the latest versions of all tools, fully installed via the install script just a few mins ago. When trying it out on my own, only a few commands work (for instance cookies). I am using Chrome 102, leading to this log:
`New Hooked Browser [id:3, ip:1.2.3.4, browser:UNKNOWN-102.0.0.0.0, os:Windows-10]` and before that: `Invalid browser version returned from the hook browser's initial connection.`

I honestly have 0 knowledge of ruby, only some knowledge of JS but could not locate the issue (at least GitHubs search doesn't find it). Does anyone know if the 3 digit browser version may be an issue or is it unrelated? The results in the control panel are often only empty, but sometimes they work. I am using the Basic Demo.

Edit: Many commands seem to just not work, for instance `Return Ascii Chars`

Thanks!

**Comment by bcoles** [comment]
Unlikely to be related.

Please provide logs.

**Comment by bcoles** [comment]
Related: https://github.com/beefproject/beef/issues/1392#issuecomment-1118189890

**Comment by OlMi1** [comment]
Indeed, it may be related. However I am unable to locate the log file under `$home_dir/beef/beef.log`, so I just set the debug switch in `config.yaml` to true, this is the output (obtained with `./beef > log.txt`, IPs censored):

[paste.helpch.at](https://paste.helpch.at/umacijocas.md)

The issue I see printed is
```
^C2022-05-30 20:18:52 - NameError - uninitialized constant BeEF::Core::Command::Cryptoloot_miner:
        /root/beef/core/main/handlers/modules/command.rb:33:in `add_command_instructions'
        /root/beef/core/main/handlers/hookedbrowsers.rb:114:in `block (2 levels) in <class:HookedBrowsers>'
        /var/lib/gems/2.7.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb:88:in `each'
        /var/lib/gems/2.7.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb:88:in `each'
        /root/beef/core/main/handlers/hookedbrowsers.rb:114:in `block in <class:HookedBrowsers>'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1042:in `route_eval'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1021:in `block in route!'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `each'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `route!'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1140:in `block in dispatch!'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/null_logger.rb:11:in `call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/head.rb:12:in `call'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'
        /var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/urlmap.rb:74:in `block in call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/urlmap.rb:58:in `each'
        /var/lib/gems/2.7.0/gems/rack-2.2.3.1/lib/rack/urlmap.rb:58:in `call'
        /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
        /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
        /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'
        /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
        /var/lib/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /var/lib/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
        /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
        /root/beef/core/main/server.rb:158:in `start'
        ./beef:258:in `<main>'
```
although the cryptoloot miner is not used by me.

**Comment by bcoles** [comment]
> Indeed, it may be related. However I am unable to locate the log file under `$home_dir/beef/beef.log`, so I just set the debug switch in `config.yaml` to true, this is the output (obtained with `./beef > log.txt`, IPs censored):

BeEF does not log to `$home_dir/beef/beef.log`.

> Edit: After rehooking the browser with the advanced page, the ASCII debug started working, Also I noticed that the `Get All Cookies` function does create output in the browser console but it does not return any data to the web panel. The Webcam module does not seem to output a camera request.
> 
> So summing it up, I may have been wrong with some stuff which appeared to me as not working due to no output in my panel. Maybe an error message would be a good idea there. However some stuff is simply not displayed or, as said, generates no output.

You can enable client debugging in the config file which will print debug messages in the hooked browser console. This may help.
