### ISSUE TITLE
trouble connecting to a windows 10 browser

### ISSUE THREAD

**Issue by kyleparker134** [beefproject/beef#2442]
whenever i send the link to google chrome on windows 10, it comes up saying the connection either timed out or it cannot be reached. any help?

**Comment by bcoles** [comment]
Is the Windows 10 host on the same network?

**Comment by kyleparker134** [comment]
yes it is

**Comment by bcoles** [comment]
Where did you get stuck during troubleshooting?

**Comment by kyleparker134** [comment]
> Where did you get stuck during troubleshooting?

i have not really troubleshooted it yet as i have no idead what to do. i have tried this on parrot os and kali linux but both do not work. i can log into the ui just fine and hook the browser on the same machine, but when i try it on my windows pc it does not work. it says it took too  long to respond. hope this is enough info.

**Comment by bcoles** [comment]
> i have not really troubleshooted it yet as i have no idead what to do.
> but when i try it on my windows pc it does not work. it says it took too long to respond. hope this is enough info.

Now that you have defined the problem you can begin troubleshooting.

Ensure BeEF is running. Ensure the Windows PC can route network traffic to the host running BeEF. Ensure you're using the correct URL to access BeEF.

Is your Windows PC located on the same LAN as the host running BeEF? Can you connect to port 3000? Can the Windows host access other network services on the host running BeEF? 

The browser console is a great tool to view what your browser is doing. You can open the browser developer tools with F12.

You can see JavaScript errors in the Console tab. You can see network traffic in the Network tab.

**Comment by jcrew99** [comment]
Closing as stale

**Comment by bcoles** [comment]
>  i can log into the ui just fine and hook the browser on the same machine, but when i try it on my windows pc it does not work.

Sounds like a network routing issue.
