### ISSUE TITLE
ip_address_list: Permission denied - getifaddrs (Errno::EACCES)

### ISSUE THREAD

**Issue by uhuhuhuhuhuhuhuh** [beefproject/beef#2443]
/beef/core/main/console/banners.rb:55:in `ip_address_list': Permission denied - getifaddrs (Errno::EACCES)
        from /beef/core/main/console/banners.rb:55:in `print_network_interfaces_count'
        from ./beef:243:in `<main>'

This is the error I've been getting

**Comment by jcrew99** [comment]
With the information provided i would think that your user does not have permission on the system for "Socket.ip_address_list" to run. Based off the documentation for exceptions i would guess that you do not have write access to the socket.
https://docs.ruby-lang.org/en/2.1.0/Socket.html

Have a look at the user permissions and provide whatever access is missing.

**Comment by wheatley** [comment]
Also, @uhuhuhuhuhuhuhuh could you please provide some more so can help the best we can?

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:**

2. **Ruby Version:**

3. **Browser Details (e.g. Chrome v81.0):**

4. **Operating System (e.g. OSX Catalina):**

## Configuration

Have you made any changes to your BeEF configuration? Yes/No
Have you enabled or disabled any BeEF extensions? Yes/No

## Steps to Reproduce

1.

**Comment by uhuhuhuhuhuhuhuh** [comment]
Environment
BeEf version: 0.5.4.0
Ruby version 2.5.5
Browser details:nil
OS:Debian

Configuration
Have you made any changes to your BeEF configuration? No(only login creds)
Have you enabled or disabled any BeEF extensions? No

Steps to Reproduce
1. run ./beef

**Comment by uhuhuhuhuhuhuhuh** [comment]
Running it using UserLAnd

**Comment by wheatley** [comment]
Thanks for the information @uhuhuhuhuhuhuhuh, we'll try and replicate your environment to reproduce your errors.

If your using the os through userland,you may find that the user being used may not have the appropriate permissions.

**Comment by adnangul301** [comment]
i think you should open a root directory first or go with chmod +x command

**Comment by danny19891989** [comment]
userland. your docs socks. for more info check the follow:

**Comment by danny19891989** [comment]
#

**Comment by bcoles** [comment]
[UserLAnd](https://userland.tech) is an Android app and runs on non-rooted devices.

BeEF is failing as it does not have permission to list the network interfaces. It may be possible to work around this; however, you will almost certainly run into further issues.

BeEF has not been tested on UserLAnd. I have not used UserLAnd.

Is it possible to bind to a TCP port from UserLAnd? If not, you cannot run BeEF.
