### ISSUE TITLE
MacOS BeEF ./install error: 'openssl/ssl.h' file not found when installing eventmachine

### ISSUE THREAD

**Issue by cheyao** [beefproject/beef#2450]
Im just installing beef (not the cow one) on my computer and i got a error:

'openssl/ssl.h' file not found 
when i was installing eventmachine

its the cpp package stuff so i did first:
gem install eventmachine -v 1.2.0.1 -- --with-cppflags=-I/usr/local/opt/openssl/include
then 
./install

but that still dosnt work, how should i fix this?
should i change something in Gemfile? like:
gem 'eventmachine', :require => 'opt/openssl/include'?

**Comment by wheatley** [comment]
Hey, thanks for posting your query. Just to make sure we can kick off our support could you please provide some more information.

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:**
2. **Ruby Version:**
3. **Browser Details (e.g. Chrome v81.0):**
4. **Operating System (e.g. OSX Catalina):**

## Configuration

Have you made any changes to your BeEF configuration? Yes/No
Have you enabled or disabled any BeEF extensions? Yes/No

## Steps to Reproduce

1. 

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
A few suggestions in this thread:

* https://github.com/eventmachine/eventmachine/issues/932

Answers vary depending on the version of OSX in use. The newest and most reasonable looking answer is:

* https://github.com/eventmachine/eventmachine/issues/932#issuecomment-1123309180

```
bundle config build.eventmachine --with-openssl-dir=/opt/homebrew/opt/openssl@1.1
```

Although you may need to change 1.1 depending on your version of OpenSSL. If that doesn't work, or you mess up and need to change the bundle config, bundle writes the config to `.bundle/config`. You can edit this file.

Someone recently commented on Discord that they solved the issue with:

```
gem install eventmachine -- --with-openssl-dir=/usr/local/opt/openssl@1.1
```

BeEF requires the eventmachine gem. There's nothing that can be done on the BeEF side to fix  this. You will need to install eventmachine.
