### ISSUE TITLE
how i host beef on a free host service

### ISSUE THREAD

**Issue by ratarchivos** [beefproject/beef#2451]
# Submit Issue

i know how to host on ngrok but i want to host with a free hosting service how i can do that?

And I'm not saying that I need to host the <Script> i want to host the panel

pleasee help!

**Comment by QQ111QQ** [comment]
Read this article! it maybe helps u greetings, alpaca  [LINK ](https://github.com/beefproject/beef/issues/2451)

**Comment by bcoles** [comment]
The same way you host it locally.

You may want to set `public_host` in the config file if your host using a domain name.

**Comment by ratarchivos** [comment]
> The same way you host it locally.
> 
> You may want to set `public_host` in the config file if your host using a domain name.



> The same way you host it locally.
> 
> You may want to set `public_host` in the config file if your host using a domain name.

i just wanna host with a free service (NO with my pc)

**Comment by DeezyE** [comment]
AWS or other cloud hosting services have a free tier.

**Comment by ratarchivos** [comment]
> AWS or other cloud hosting services have a free tier.

but how?

**Comment by wilz7** [comment]
Ask uncle google not going to spoon feed you everthing

**Comment by CreeperGamerGitHub** [comment]
> > AWS or other cloud hosting services have a free tier.
> 
> but how?

go to aws and figure it out yourself.
