### ISSUE TITLE
Deprecate JSDoc as it is not maintained anymore and use webdoc instead

### ISSUE THREAD

**Issue by ShukantPal** [beefproject/beef#2458]
Hi, this isn't a typical "bug" report. I see you are using JSDoc for to document your [reference documentation](https://beefproject.github.io/beef/index.html). As you know, JSDoc is no longer being maintained and it's using outdated technology.

That's why I've developed [webdoc](https://github.com/webdoc-labs/webdoc), a drop-in replacement for JSDoc. [melonJS](http://melonjs.github.io/melonJS/docs/index.html) and [PixiJS](https://pixijs.download/release/docs/index.html) are already using webdoc!

I would be down to helping you moved over if you're interested! webdoc is and will remain free for community-maintained open source projects :)

**Comment by wheatley** [comment]
hey @ShukantPal we won't be using jsdocs moving forward, but thanks for reaching out.
