### ISSUE TITLE
Browser not hooking through both NGROK and localhost connections

### ISSUE THREAD

**Issue by YourDLCMaster** [beefproject/beef#2459]
I successfully got BeEF set up and can log in to the UI panel using NGROK on TCP, but no matter what I do, neither my host machine nor any virtual machine's browsers hook and appear in the UI when using either of the demo pages or the Hook Me! script. I've tried several browsers but to no avail. Is there something I'm doing wrong with BeEF or NGROK?

Info:
BeEF Version - 0.5.4.0
Ruby Version - 3.0.3p157
Common Browser - Opera GX Stable 86.0.4363.70
OSes - BeEF Host VM: Kali Linux amd64 (xfce4-whiskermenu-plugin 2.7.1) | Host OS: Windows 10 Home 21H2 (build 19044.1706)
_I hope this isn't too much detail._

**Update!!**
I got localhost on the Kali machine to hook, but NGROK still isn't hooking on other machines or OSes.

**Update 2 (1 Hour After)**
NGROK is still interfering with hooking, and TCP is the only way I'm able to access the BeEF control panel. HTTP does not go through, it just times out on the client's end.

**Comment by YourDLCMaster** [comment]
Please please please don't close it!!!

**Comment by bcoles** [comment]
> Please please please don't close it!!!

The issue was marked as stale due to lack of activity. There's not enough information here to reproduce the issue. Myself and several other people have successfully used BeEF with ngrok out of the box using the steps outlined in the FAQ:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

Although everyone tested on Linux rather than Windows.

There is currently a bug with being unable to login to the admin page via ngrok. However you should still be able to see the login page and hook browsers.

If you can't see the admin login page via ngrok then you have not configured BeEF and ngrok correctly.

**Comment by YourDLCMaster** [comment]
I am so, so, so, so, _SO_ sorry for the extremely, _extremely_ late reply, I was really busy the last couple of weeks.

- Yes, I can hit the default route; I was able to get to the decoy page I made, too.
- I will check the wiki article and provide an update.
- I will check the console.log from Opera and report an update to that as well.

Again, my greatest apologies for my extremely late reply.

**Comment by YourDLCMaster** [comment]
> > Please please please don't close it!!!
> 
> The issue was marked as stale due to lack of activity. There's not enough information here to reproduce the issue. Myself and several other people have successfully used BeEF with ngrok out of the box using the steps outlined in the FAQ:
> 
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
> 
> Although everyone tested on Linux rather than Windows.
> 
> There is currently a bug with being unable to login to the admin page via ngrok. However you should still be able to see the login page and hook browsers.
> 
> If you can't see the admin login page via ngrok then you have not configured BeEF and ngrok correctly.

Lmao sorry that came in through email and I replied jokingly, I'm working on the issue though and I'll provide updates as soon as I can.
Damn that's embarrassing lol, I thought it was an email bot, not a throughput bot.

**Comment by bcoles** [comment]
> Yes, I can hit the default route; I was able to get to the decoy page I made, too.

Ok. That's a good start.

> I will check the console.log from Opera and report an update to that as well.

Try the Console tab in the browser developer tools (F12). Also check the Network tab.
