### ISSUE TITLE
pretty_theft module never worked

### ISSUE THREAD

**Issue by SmailDH** [beefproject/beef#2461]
Dear team,
i tried to load the module "**pretty_theft**" here my code (replace MYIP) : 

```
{"name": "Windows login",
  "author": "xntrik",
  "browser": "FF",
  "browser_version": "ALL",
  "os": "ALL",
  "os_version": "ALL",
  "modules": [
    {"name": "pretty_theft",
    "condition": null,
    "options": {
      "choice": "Windows",
      "backing": "Grey",
      "imgsauce": "http://MYIP:3000/ui/media/images/beef.png"
      }
    }
  ],
  "execution_order": [0],
  "execution_delay": [0],
  "chain_mode": "sequential"
}
```
an example is also available on : **arerules/ie_win_missingflash-prettytheft.json**

I can see the module is loaed correctely when i start beef : 

![image](https://user-images.githubusercontent.com/90631526/173880875-4a3c7a73-1607-48d3-b8f2-e479e5306e27.png)

But surprisingly not working .... after spending hours troubleshooting i may missing something important or could be a problem with the beef not able to load this module  .... your thoughts/advises ?

**Comment by DeezyE** [comment]
Can you provide more details.

When you create an issue there should be an issue template to fill out - did that show up for you?
