### ISSUE TITLE
Not Loading In Google

### ISSUE THREAD

**Issue by IdkMyname1234** [beefproject/beef#2463]
![96-126-102-31 ip linodeusercontent com - Google Chrome 6_18_2022 1_36_10 PM](https://user-images.githubusercontent.com/107737923/174456370-370e5ac1-1ba5-47ea-a7b0-5f8074e3642e.png)

**Comment by wheatley** [comment]
Hi, could you please provide some more so can help the best we can?

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:**
2. **Ruby Version:**
3. **Browser Details (e.g. Chrome v81.0):**
4. **Operating System (e.g. OSX Catalina):**

## Configuration

Have you made any changes to your BeEF configuration? Yes/No
Have you enabled or disabled any BeEF extensions? Yes/No

## Steps to Reproduce

1. 

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
Ensure you're using the correct hook URL. The connection was reset meaning that the port was not reachable.

**Comment by bogobob** [comment]
I had this problem also except the site just took too long to respond, the only changes I made to any files was adding the GeoIP .mmbd file.

**Comment by bcoles** [comment]
There is insufficient enough information to provide any guidance.

**Comment by bogobob** [comment]
I can give you more information about it.

**Comment by bcoles** [comment]
> I can give you more information about it.

If you have an issue, create a [new issue](https://github.com/beefproject/beef/issues/new/choose). There is nothing actionable in this issue. Closing.
