### ISSUE TITLE
Ngrok

### ISSUE THREAD

**Issue by Lucidyyyy** [beefproject/beef#2464]
Hey, iam i useing Beef-xss_Ngrok basically beef tht comes with ngrok and iut says its not downloaded so i need to download it myself since it doesnt allow me to autodownload, where do i specifically have to download it if im using beef with ngrok, how do i install ngrok specifically to it?
![unknown](https://user-images.githubusercontent.com/106867189/174477170-a45ba40b-6f14-454d-a4dc-a080f4aa089c.png)

**Comment by bcoles** [comment]
I don't know what `Beef-xss_Ngrok` is. A quick search reveals no results.

It looks like the script you are running is trying to install ngrok then prompted you for your sudo password to complete installation. Did the install complete?

You can download ngrok here: https://ngrok.com/

You'll want to run it on the same host that you're running BeEF on.

**Comment by Lucidyyyy** [comment]
it doesnt download for some reason

**Comment by bcoles** [comment]
> it doesnt download for some reason

I don't know what that means and it isn't shown in the screenshot.

Running BeEF with ngrok is fairly straight forward.

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
