### ISSUE TITLE
beef not hooking over ngrok

### ISSUE THREAD

**Issue by sociallyakwardfrog** [beefproject/beef#2469]
after trying different methods to get it working for 6+ hours i finally decided to resort to opening an issue, after cloning beef from the github and downloading ngrok from snap and following the ngrok guide for beef i haven't gotten the hooking to work in any way shape or form, on my phone i can connect to the ~/demos/basic.html and from my computer i am able to connect to the ~/ui/panel but when i open the ~/demos/basic.htm on my phonel it doesn't get hooked even though the website seems to be working properly

**Comment by bcoles** [comment]
Are there any errors in the browser console? Have you set the beef public host and port in the config file?

**Comment by sociallyakwardfrog** [comment]
> Which guide?

this one https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by sociallyakwardfrog** [comment]
> Are there any errors in the browser console? Have you set the beef public host and port in the config file?

there seem to be no errors. and yes, the config looks like this 
![image](https://user-images.githubusercontent.com/82838374/175287406-26e1a22d-068b-46f6-8c8b-2678dc957eeb.png)

**Comment by bcoles** [comment]
> there seem to be no errors. and yes, the config looks like this

There's your problem. The public host and public port are commented out. Remove the preceding `#` and ensure the lines are vertically aligned correctly. Also, remove `https://` from the `host` field.

**Comment by sociallyakwardfrog** [comment]
> > there seem to be no errors. and yes, the config looks like this
> 
> There's your problem. The public host and public port are commented out. Remove the preceding `#` and ensure the lines are vertically aligned correctly. Also, remove `https://` from the `host` field.

now i have some new issues
![image](https://user-images.githubusercontent.com/82838374/175289012-72f020db-349d-410f-8e8a-2820c18bf039.png)
![image](https://user-images.githubusercontent.com/82838374/175289076-b5b0c25b-7ae1-4c29-91c7-62dee8aa5585.png)

**Comment by bcoles** [comment]
> now i have some new issues

The `public` parent key is still commented out.

**Comment by bcoles** [comment]
And the `https` key is still commented out.

**Comment by bcoles** [comment]
> still nothing

Vertical alignment is important.

**Comment by bcoles** [comment]
```yaml
beef:
    # ...
    http:
        # ...
        public: 
            host: "<your-id>.ngrok.io"      # public hostname/IP address
            port: "443"
            https: true
```
