### ISSUE TITLE
Executing Clickjacking cause NoMethodError (undefined method `escape')

### ISSUE THREAD

**Issue by ignacypolak1** [beefproject/beef#2479]
Beef was installed from repository with ./install, I also was asked to use "bundle install" to install gems. No other errors, other modules are working correctly. Mentioned error is printed in loop until killing process and persist until running beef again with -x flag. In case of running beef without -x error still exists.

## Versions
BeEF Version: 0.5.4.0
Ruby Version: 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux-gnu]
Browser Details: Firefox
Operating System: 5.18.0-kali2-amd64

## Changes
- Enabling Metasploit module (I think it's not related)

## Steps to Reproduce
1. Run beef with command ./beef.
2. Execute clickjacking module from beef UI panel with default parameters.

## Console Error:

2022-06-28 18:12:34 - NoMethodError - undefined method `escape' for URI:Module:
        (erubis):21:in `block in evaluate'
        /var/lib/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
        /var/lib/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
        /opt/beef/core/main/command.rb:197:in `output'
        /opt/beef/core/main/handlers/modules/command.rb:68:in `add_command_instructions'
        /opt/beef/core/main/handlers/hookedbrowsers.rb:108:in `block (2 levels) in <class:HookedBrowsers>'
        /var/lib/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb:88:in `each'
        /var/lib/gems/3.0.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb:88:in `each'
        /opt/beef/core/main/handlers/hookedbrowsers.rb:108:in `block in <class:HookedBrowsers>'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1042:in `route_eval'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1021:in `block in route!'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `each'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `route!'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1140:in `block in dispatch!'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'
        /var/lib/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/null_logger.rb:11:in `call'
        /var/lib/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/head.rb:12:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'
        /var/lib/gems/3.0.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'
        /var/lib/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/urlmap.rb:74:in `block in call'
        /var/lib/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/urlmap.rb:58:in `each'
        /var/lib/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/urlmap.rb:58:in `call'
        /var/lib/gems/3.0.0/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/3.0.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
        /var/lib/gems/3.0.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
        /var/lib/gems/3.0.0/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'
        /var/lib/gems/3.0.0/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
        /var/lib/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /var/lib/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /var/lib/gems/3.0.0/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
        /var/lib/gems/3.0.0/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
        /opt/beef/core/main/server.rb:156:in `start'
        ./beef:278:in `<main>'

**Comment by jcrew99** [comment]
I tried to replicate the error but was unable to get the same result. Only thing was I did not use ruby 3.0 so i believe it might be resulting due to that.

**Comment by jcrew99** [comment]
oh ahaha i didn't notice at first. I'm pretty sure this is caused by the URI.escape() command being removed in in Ruby 3

**Comment by jcrew99** [comment]
I have added it to the conversation regarding the ruby 3.0 upgrade but for now downgrading ruby to something like 2.7 would get it working.
