### ISSUE TITLE
How to use beef with Ngrok

### ISSUE THREAD

**Issue by danielsuperone** [beefproject/beef#2481]
Hello all, i've been trying to figure out how to use BeEF with Ngrok for the past few days but I haven't been able to get it to work... I was wondering, can someone please properly explain how to setup Ngrok to work with BeEF, I am aware that there is a documentation by the creators/contributors on how to do this, but i'm still getting some issues. In my case, when I edit the Ngrok config file I add 2 servers: https://uploadi.ng/UhskVJ3E then when I run './ngrok start --all` I get this: https://uploadi.ng/2VlICTNa two servers running on https when in other videos people get 4 servers in total (2 the same since 1 server is https and other is on http) I don't know why I keep getting my servers in https format... BTW: my BeEF file looks like this: https://uploadi.ng/dhHoYMNdthen i've tried using BeEF over WAN since I thought I kept doing something wrong and I still get the same issue (I know that BeEF over WAN is an unofficial software and that you are not affiliated with it) Well the issue with BeEF over WAN is that the login panel loads, but I can't sign into it and the link that I need to send to the "victim" simply doesn't even work. That aside your software BeEF is a very good software and I really enjoy playing around with all the features and i'd love to be able to use it on my other devices (not just on my KALI OS system. Any explanation on how to set it up would be greatly appreciated. Thank you in advance for any help.

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

You config file is missing the relevant `public` properties.

**Comment by danielsuperone** [comment]
I am still having problems... Can you please assist me a little more, i have edited the config like this: https://uploadi.ng/xO0uwnR9 and in the Ngrok terminal i have this this: https://uploadi.ng/TVazu4BX and in my browser i have tried going to all the links but they all lead to their default pages, https://uploadi.ng/DYoMDJbX

**Comment by bcoles** [comment]
> I am still having problems... Can you please assist me a little more, i have edited the config like this: https://uploadi.ng/xO0uwnR9 and in the Ngrok terminal i have this this: https://uploadi.ng/TVazu4BX and in my browser i have tried going to all the links but they all lead to their default pages, https://uploadi.ng/DYoMDJbX

You have set the ngrok host in the `host` field. That is incorrect. BeEF cannot bind to a host name. It must bind to a network interface. You need only to change the `public` properties.

Review the default config file:

https://github.com/beefproject/beef/blob/master/config.yaml

To perform troubleshooting I suggest ensuring you can access the admin page or demo page first. Accessing these requires no modifications to BeEF at all. It works out of the box with the default configuration file. If it doesn't work, you have not set up ngrok correctly.

Once you have ensured that the network configuration is working, then you can worry about editing the hook file.

**Comment by danielsuperone** [comment]
Sorry to bother again, but I haven't exactly understood on what I have to do, where can i find the `public` properties. Sorry for asking this simple question... and what do you mean by "review the default config file", where can i find that on my computer? (I don't know if i had already said this, but BeEF works withought Ngrok properly but only on my local machine)

**Comment by bcoles** [comment]
The config.yaml file is in the root of the BeEF directory.

**Comment by danielsuperone** [comment]
Is this the directory? https://uploadi.ng/76VR59A0
(also i'm raelly sorry for asking so many questions, and i really appreciate your patience)

**Comment by bcoles** [comment]
> Is this the directory? https://uploadi.ng/76VR59A0

You tell me. Is that the config file you have been editing?

**Comment by danielsuperone** [comment]
yes, , i just can't figure out how to copy the file (as a backup) i can only edit it via the terminal and not while viewing it through the file manager, it keeps saying permission denied...
Also i can access the ngrok panel only via the 127.0.0.1:3000 url and not the Ngrok... https://uploadi.ng/alUMsEfu the other Ngrok URLS take me to the default website of APACHE

**Comment by bcoles** [comment]
> should i comment here, or open a new issue? (i assume i can just comment here again?, or will you not see my comments here?)

comment here. or try discord.

https://discord.gg/r3HnzQzy

**Comment by danielsuperone** [comment]
Are you busy right now? I hope i'm not distracting you from anything important, if you can, perhaps i can show you my installation progress on Discord so you could guide me if it's not a problem?
