### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by KillerNO2020** [beefproject/beef#2482]
https://ppa.launchpadcontent.net/brightbox/ruby-ng/ubuntu jammy Release                                                 
  404  Not Found

**Comment by bcoles** [comment]
What operating system are you using? Using a ppa should be unnecessary.

**Comment by bcoles** [comment]
You should already have ruby available in packages.

```
sudo apt-get install ruby ruby-dev
```

Unfortunately BeEF does not full support Ruby 3 yet, but it mostly works.

**Comment by KillerNO2020** [comment]
@bcoles  i do this command and several commands like 
1.`sudo apt install ruby-full`
2.`rbenv install -l`

**Comment by KillerNO2020** [comment]
@bcoles  look
![Screenshot_3](https://user-images.githubusercontent.com/108419273/176481494-e6fb6aa9-4550-4c8f-b644-86b33e686c90.jpg)
this is a new issue

**Comment by bcoles** [comment]
> this is a new issue

Your package manager is doing something in the background. Wait for it to finish.

**Comment by KillerNO2020** [comment]
@bcoles  its not even opened

**Comment by bcoles** [comment]
> @bcoles its not even opened

It is running the background. Likely updating packages.

**Comment by KillerNO2020** [comment]
i have tried like 15 tutorial on youtube

**Comment by bcoles** [comment]
> @bcoles what should i do Wait .....? how much time ?

Until it is finished doing whatever it is doing.

> i have tried like 15 tutorial on youtube

They are all wrong.

```sh
cd $HOME
git clone https://github.com/beefproject/beef
cd beef
gem install bundler
bundle install
```

**Comment by KillerNO2020** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/108419273/176484435-ec084e21-7a60-4cb9-8ede-117c09101f0a.jpg)
 like this 
what should i do next ?

**Comment by KillerNO2020** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/108419273/176484826-d9794bfe-2ff9-490a-a16c-9c15386b2c34.jpg)
 
i have change the password 
but look

**Comment by bcoles** [comment]
Ah yeah, that's due to using Ruby 3.

**Comment by bcoles** [comment]
As a workaround, for now you can delete the extension.

```
rm -rf extensions/social_engineering
```

**Comment by bcoles** [comment]
> what should i do

https://github.com/beefproject/beef/issues/2482#issuecomment-1170192989

**Comment by KillerNO2020** [comment]
> > what should i do
> 
> [#2482 (comment)](https://github.com/beefproject/beef/issues/2482#issuecomment-1170192989)

does not make any thing
![Screenshot_6](https://user-images.githubusercontent.com/108419273/176488874-c0d5f1c7-d109-4fd6-9933-f836e7764a7c.jpg)

**Comment by KillerNO2020** [comment]
> 

how can i use it

**Comment by KillerNO2020** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/108419273/176490591-ec7bfef3-95e8-4c0d-960f-70cf07c2ec43.jpg)
  is it working right ????

**Comment by bcoles** [comment]
> is it working right ????

Yes.

It looks like you tried to open the proxy URL. The proxy is a proxy. You probably want to open the UI. You can find the UI URL where it says "UI URL".
