### ISSUE TITLE
Hooking not working

### ISSUE THREAD

**Issue by enderprime522** [beefproject/beef#2490]
BeEF Version: latest
Ruby Version: latest
 (e.g. Chrome v81.0): Latest Chrome, Firefox
 Kali Linux

1. Have you made any changes to your BeEF configuration? No
2. Have you enabled or disabled any BeEF extensions? No

I'm new to this ethical hacking-thing, but I'm open to learn more.
1. Hooking not working, not even on localhost. I installed a second browser, and it doesn't work either. I attached the screenshot of the terminal when I open the hooker link.

![Képernyőkép 2022-07-08 182346](https://user-images.githubusercontent.com/85453424/178032023-afc3f18e-2742-418e-9aef-b54f7eb5da27.png)
*

**Comment by SubGlitch1** [comment]
try the last release to find out if the error is within beef or your system

**Comment by enderprime522** [comment]
Where can I find the latest one? I thought I have it.

**Comment by enderprime522** [comment]
Never mind, I fixed the issue. It didn't work because I used the hooker in the Kali simulation.
