### ISSUE TITLE
Bundler install interrupted (Kali Linux)

### ISSUE THREAD

**Issue by tln159357** [beefproject/beef#2497]
![image](https://user-images.githubusercontent.com/109080404/178268116-1666a522-15f3-490e-a3e2-70470da693d7.png)

I've been having some trouble during bundler install. Can anyone help?

gem version 3.3.5
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux-gnu]

**Comment by bcoles** [comment]
The twitter Gem is only required for Twitter notifications. The easiest workaround is to simple remove this from `Gemfile` and `Gemfile.lock`.

You can also remove the `notifications` extension:

```
rm -rf extensions/notifications/
```

**Comment by tln159357** [comment]
I've to had to install those missing gems manually. Then it worked. 

`gem install unf`
`gem install twitter`
`gem install http`
`gem install http-cookie`
`gem install domain_name`
`gem install domain_name`

Thanks, btw.

**Comment by nastymontana** [comment]
> ![image](https://user-images.githubusercontent.com/109080404/178268116-1666a522-15f3-490e-a3e2-70470da693d7.png)
> 
> I've been having some trouble during bundler install. Can anyone help?
> 
> gem version 3.3.5 ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux-gnu]

me to i am also having this issue on my pc
