### ISSUE TITLE
Termux: cannot load such file -- net/smtp (LoadError)

### ISSUE THREAD

**Issue by aman6204** [beefproject/beef#2498]
I got error while installing beef in termux 
![Screenshot_2022-07-12-11-55-46-02_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/82750233/178423058-9dac5c37-2a6b-4761-8223-3c22672d3787.jpg)

**Comment by bcoles** [comment]
BeEF does not yet fully support Ruby 3.

See also:

* #2494
* https://github.com/beefproject/beef/issues/2336#issuecomment-1147368671
* https://github.com/beefproject/beef/issues/2379#issuecomment-1153404253

**Comment by aman6204** [comment]
> BeEF does not yet fully support Ruby 3.
> 
> See also:
> 
> * [I have problem installing in termux  #2494](https://github.com/beefproject/beef/issues/2494)
> * [Issues with running ./beef (Termux) #2336 (comment)](https://github.com/beefproject/beef/issues/2336#issuecomment-1147368671)
> * [cannot load such file -- net/smtp (LoadError) #2379 (comment)](https://github.com/beefproject/beef/issues/2379#issuecomment-1153404253)

Thanks  a lot
