### ISSUE TITLE
AdminUI] Error: Could not minify JavaScript file: web_ui_auth

### ISSUE THREAD

**Issue by junhello1** [beefproject/beef#2500]
Hello, I found the following error after installing beef-xss in kali2022
![image](https://user-images.githubusercontent.com/72799898/178670438-335b7fad-8d42-48a0-a7af-d0e547f0a86b.png)
This caused me to use 127.0.0.1:3000/hook.js which didn't work
![image](https://user-images.githubusercontent.com/72799898/178670862-de6980ec-ab8a-4973-8f1b-765eca04aed6.png)
How to solve this problem please

**Comment by bcoles** [comment]
Ensure `nodejs` is installed and `node` is in `$PATH`.

**Comment by bcoles** [comment]
It is also possible that the beef-xss package is out of date.

There was an issue which was patched in [Oct 14, 2021](https://github.com/beefproject/beef/pull/2186).

**Comment by junhello1** [comment]
Sorry for wasting your time, only to find out that the website is not parsed, thank you for your answer

**Comment by DeezyE** [comment]
👍
