### ISSUE TITLE
Beef offline towser

### ISSUE THREAD

**Issue by aman6204** [beefproject/beef#2506]
The browser comes offline just in 1 or 2 minutes.how to increase the duration

**Comment by bcoles** [comment]
The browser will remain hooked for as long as the hooked page remains open and the browser remains active.

The [persistence](https://github.com/beefproject/beef/tree/master/modules/persistence) modules can be used to attempt to keep a hook active longer.

**Comment by aman6204** [comment]
> The browser will remain hooked for as long as the hooked page remains open and the browser remains active.
> 
> The [persistence](https://github.com/beefproject/beef/tree/master/modules/persistence) modules can be used to attempt to keep a hook active longer.



> The browser will remain hooked for as long as the hooked page remains open and the browser remains active.
> 
> The [persistence](https://github.com/beefproject/beef/tree/master/modules/persistence) modules can be used to attempt to keep a hook active longer.

Please explain

**Comment by aman6204** [comment]
Please explain
