### ISSUE TITLE
WebRTC module - API Fire Error: Could not find table 'rtcsignals'

### ISSUE THREAD

**Issue by s1nglethr3ad** [beefproject/beef#2508]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. BeEF Version:  0.5.4.0
4. Ruby Version:  ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
5. Browser Details (e.g. Chrome v81.0):  FireFox 102.0 (64-bit)
6. Operating System (e.g. OSX Catalina):  20.04.1-Ubuntu

## Configuration

1. Have you made any changes to your BeEF configuration? Yes
2. Have you enabled or disabled any BeEF extensions? Yes

## Steps to Reproduce

1. I have Metasploit enabled through main config.yml and WebRTC module enabled under extensions/webrtc
2. Launch with ./beef from console.  Beef starts fine and initializes.  
3. After Beef launches, the following error is displayed:
`API Fire Error: Could not find table 'rtcsignals' in {:owner=>BeEF::Extension::WebRTC::RegisterPreHookCallback, :id=>12}.pre_hook_send()`
4. This error continues to be displayed until beef is stopped with Ctrl-C

## Attachments below
![Screenshot from 2022-07-19 10-37-49](https://user-images.githubusercontent.com/60003925/179779398-941e11e7-8126-4d01-a45f-44b38e685649.png)
![Screenshot from 2022-07-19 10-38-56](https://user-images.githubusercontent.com/60003925/179779423-e66a530e-342a-492c-9866-f5e701822839.png)
[beef_config.yaml.txt](https://github.com/beefproject/beef/files/9142134/beef_config.yaml.txt)
[webrtc_config.yaml.txt](https://github.com/beefproject/beef/files/9142137/webrtc_config.yaml.txt)
[web_logs.txt](https://github.com/beefproject/beef/files/9142146/web_logs.txt)
[beef.log.txt](https://github.com/beefproject/beef/files/9142151/beef.log.txt)
*

**Comment by s1nglethr3ad** [comment]
@bcoles 
If I would like to use WebRTC extension, would there be a possible fix?  Perhaps?

**Comment by bcoles** [comment]
@jcrew99

**Comment by s1nglethr3ad** [comment]
@bcoles , @jcrew99 

Interested to see if you all had a chance to play around with the error yet.  Thanks!

**Comment by bcoles** [comment]
This should be fixed in #2524.

Although it is highly unlikely that the WebRTC extension will work after these changes. It has barely been maintained since it was added in 2014 and last updated in 2015.

The extension was written by @xntrik. You could try pinging him but I doubt he's interested in maintaining it.
