### ISSUE TITLE
how do i access config.yaml on mac, im so confused, i did beef through a linode server btw

### ISSUE THREAD

**Issue by Notdialed** [beefproject/beef#2514]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. BeEF Version: 
4. Ruby Version:
5. Browser Details (e.g. Chrome v81.0): chrome
6. Operating System (e.g. OSX Catalina): mac monterey

## Configuration

1. Have you made any changes to your BeEF configuration?  no
2. Have you enabled or disabled any BeEF extensions?  no

## Steps to Reproduce

1. (eg. I ran install script, which ran fine)
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
3. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
The config.yaml file is in the root of the BeEF directory. Wherever you cloned BeEF, it's there.

**Comment by Notdialed** [comment]
> The config.yaml file is in the root of the BeEF directory. Wherever you cloned BeEF, it's there.

how do I find the root directory on mac?

**Comment by bcoles** [comment]
> how do I find the root directory on mac?

Where did you clone or unzip BeEF?

**Comment by Notdialed** [comment]
i just used this vid, https://www.youtube.com/watch?v=3ogyS4KOlXc&t=342s

**Comment by bcoles** [comment]
Wherever you put BeEF that's where the config file is.

**Comment by Notdialed** [comment]
> Wherever you put BeEF that's where the config file is.

I'm so confused sry what?

**Comment by bcoles** [comment]
```
cd /tmp
git clone https://github.com/beefproject/beef
cd beef
cat config.yaml
```

**Comment by Notdialed** [comment]
> 

what should i do wit this

**Comment by bcoles** [comment]
> what should i do wit this

This is the answer to your question.

The config file is in the BeEF directory. Wherever you put BeEF, that's where the config file is. The config file resides in the BeEF directory. Of all the directories on your file system, the config file exists only in the directory which contains BeEF. All directories on your file system which do not contain BeEF do not contain the config file. The directory which contains BeEF also contains the config file.
