### ISSUE TITLE
how do edit the change the config.yaml and where do i find it, i used this vid right here to install so someone pls explain, https://www.youtube.com/watch?v=3ogyS4KOlXc&t=342s

### ISSUE THREAD

**Issue by Notdialed** [beefproject/beef#2515]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. BeEF Version:
4. Ruby Version:
5. Browser Details (e.g. Chrome v81.0):
6. Operating System (e.g. OSX Catalina):

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No
2. Have you enabled or disabled any BeEF extensions? Yes/No

## Steps to Reproduce

1. (eg. I ran install script, which ran fine)
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
3. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
The video you linked to showd you where the config file is.

![image](https://user-images.githubusercontent.com/434827/180915703-c4417f82-9a70-4c64-8735-69627954ca15.png)

`config.yaml` is in YAML format. It is a text file. You can edit a text file using your favorite text editor software.

Closing as dupe of #2514.
