### ISSUE TITLE
how do i get roblox cookies, check below for exmaple, also what does advanced logging do?

### ISSUE THREAD

**Issue by Notdialed** [beefproject/beef#2516]
_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_95A395D629D1C30DBB1A833D55B59741BD786DC7EDDDB790FF83995B3A5772806EEE591DAF162B39359ADE0E77C9742BE67A8940FB52D784F43745AB056F7666D97BC0205C832590BD603E079A1685D6B861563EEB8C64DFA407F00AF449AB9794539113D7E6D42DB53F7BB366EF1D97630FC0523EAE1BE28C2CD9D037923E28E5FCD8E40C1EDE1E17D4C443DD4DC8392685C2D65555987815A8EA1476BDDFDBBF166F6885F664B46E683A0134B48D77FF5E407378ED025D281DD91EADC7995C04D506AD3FF50B4EC31CFC0C2EEE846AF1246723F1263652DE9BFFB3E90D802AAB879481B1AF268D19622332D1C4C899EE28E14EA1241F584156167624929B0DF9415A40AB367E8E0186D104D69ABD09477A66D6372B0CD6AE58C70F80A7AD58F5718A2F82042B6F9D9C7EB10B5BB81AE52F9E4F11C42000E80BC3FF1384F3D674DD0871F5ACD1AF8FB848783B1CABE968F3DB9805DA594371DD680FB683CAB1C4DA5F523952E20401E0B0F1D9AAA04FC64F2CB419AA6685311A7B294799615C3135DB9170F5A5816FFC44177EAE58B97C6A32F4

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No
2. Have you enabled or disabled any BeEF extensions? Yes/No

## Steps to Reproduce

1. (eg. I ran install script, which ran fine)
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
3. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
Why would you share a message that starts with "WARNING:-DO-NOT-SHARE-THIS" ?

**Comment by bcoles** [comment]
> how do i get roblox cookies

You will need to execute the hook within the Roblox origin.

> what does advanced logging do?

No idea. The phrase "advanced logging" appears nowhere within the BeEF source.

**Comment by Notdialed** [comment]
> > how do i get roblox cookies
> 
> You will need to execute the hook within the Roblox origin.
> 
> > what does advanced logging do?
> 
> No idea. The phrase "advanced logging" appears nowhere within the BeEF source.

wym execute inside roblox origin, when I test it on myself right I click get cookie when the hooked browser is on roblox btw , and it legit says "How to enable and capture detailed logging".

**Comment by Notdialed** [comment]
> Why would you share a message that starts with "WARNING:-DO-NOT-SHARE-THIS" ?

its a fake version of what it looks like, I switched around some numbers, plus it changed every 10 min

**Comment by bcoles** [comment]
> wym execute inside roblox origin

Access to cookies is restricted to the issuing origin. You will need to execute JavaScript within the Roblox origin to access the cookie. To do this you will need to bypass the [same origin policy](https://en.wikipedia.org/wiki/Same-origin_policy).

> when I test it on myself right I click get cookie when the hooked browser is on roblox btw

If you have hooked a page on the Roblox origin you can retrieve Roblox cookies. The "Get Cookie" module can be used to retrieve cookies for the hooked origin. Cookies marked `HttpOnly` cannot be retrieved using JavaScript without a bypass for the `HttpOnly` cookie protection flag.

> it legit says "How to enable and capture detailed logging"

I have no what "it" is in this context. The phrase "How to enable and capture detailed logging" does not appear anywhere in the BeEF source.

Whatever you are looking at is not part of BeEF. BeEF project is not affiliated with Linode. BeEF is not affiliated with the creator of the video tutorial.
