### ISSUE TITLE
stop closing my tickets, nothing was fixed, im trying to get roblox cookies but its not giving it to me, how do i change that, example of what it should look like below.

### ISSUE THREAD

**Issue by Notdialed** [beefproject/beef#2517]
_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_95A395D629D1C30DBB1A833D55B59741BD786DC7EDDDB790FF83995B3A5772806EEE591DAF162B39359ADE0E77C9742BE67A8940FB52D784F43745AB056F7666D97BC0205C832590BD603E079A1685D6B861563EEB8C64DFA407F00AF449AB9794539113D7E6D42DB53F7BB366EF1D97630FC0523EAE1BE28C2CD9D037923E28E5FCD8E40C1EDE1E17D4C443DD4DC8392685C2D65555987815A8EA1476BDDFDBBF166F6885F664B46E683A0134B48D77FF5E407378ED025D281DD91EADC7995C04D506AD3FF50B4EC31CFC0C2B367E8E0186D104D69ABD09477A66D6372B0CD6AE58C70F80A7AD58F5718A2F82042B6F9D9C7EB10B5BB81AE52F9E4F11C42000E80BC3FF1384F3D674DD0871F5ACD1AF8FB848783B1CABE968F3DB9805DA594371DD680FB683CAB1C4DA5F523952E20401E0B0F1D9AAA04FC64F2CB419AA6685311A7B294799615C3135DB9170F5A5816FFC44177EAE58B97C6A32F4

## Configuration

1. Have you made any changes to your BeEF configuration? /No
2. Have you enabled or disabled any BeEF extensions? /No

## Steps to Reproduce

1. (eg. I ran install script, which ran fine)
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
3. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
> stop closing my tickets, nothing was fixed

Nothing was fixed because there is nothing to fix. Your questions have been answered.
