### ISSUE TITLE
how i host beef on a free host service

### ISSUE THREAD

**Issue by ratarchivos** [beefproject/beef#2520]
i know how to host on ngrok but i want to host with a free hosting service how i can do that?

And I'm not saying that I need to host the <Script> i want to host the panel

pleasee help!

**Comment by bcoles** [comment]
BeEF is a server. You will need to run a server. You can't host it on something like Apache.

You can host it on a VPS or some cloud services.

**Comment by ratarchivos** [comment]
@bcoles i dont want apache i want a free host service

**Comment by bcoles** [comment]
Use a VPS

**Comment by ratarchivos** [comment]
@bcoles whats that?

**Comment by bcoles** [comment]
https://en.wikipedia.org/wiki/Virtual_private_server

**Comment by ratarchivos** [comment]
@bcoles there is any free?
