### ISSUE TITLE
Beef hooking link not working!

### ISSUE THREAD

**Issue by Im-Bob** [beefproject/beef#2529]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. BeEF Version: 0.5.4.0
4. Ruby Version: 3.0.4
5. Browser Details (e.g. Chrome v81.0): Firefox 91.11.0
6. Operating System (e.g. OSX Catalina): Kali Linux [name -r = 5.10.16.3-microsoft-standard-WSL2]

## Configuration

1. Have you made any changes to your BeEF configuration? I only enabled debug and metasploit
2. Have you enabled or disabled any BeEF extensions? I only enabled metasploit

## Steps to Reproduce

1. When I paste in the hook URL and load into the page. Beef is not logging it and nothing is happening 

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

I also use the github clone. And I tried to disable my VPN, firewall, and antivirus 

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
Do you get any errors in the browser console? Where did you get stuck during trouble shooting?

**Comment by Im-Bob** [comment]
Here's a video of what's going on:
https://user-images.githubusercontent.com/99659625/183471992-4f4834ab-2bf4-4c97-9f6b-641a8e3fd462.mp4

Here are the browser consoles from 1. The beef UI page, and 2. The hook link page

1. ![ui panel](https://user-images.githubusercontent.com/99659625/183472243-1fdab66f-f7cb-4e83-a14d-28f74fb947b6.png)

2. ![hook link page](https://user-images.githubusercontent.com/99659625/183472318-fb659401-94fb-4e4c-9182-7b907fb26fd4.png)

**Comment by bcoles** [comment]
"Internal Server Error" indicates that BeEF has encountered an error. Are there any errors in the terminal where you started BeEF?

>  I only enabled debug and metasploit

Try disabling the Metasploit extension.

`beef.debug` or `beef.http.debug` ? There is a known issue with `beef.http.debug`.

**Comment by Im-Bob** [comment]
Here is the error I see in the starting terminal when I click on the hook link myself: https://pastebin.com/WtuRLZc3

**Comment by Im-Bob** [comment]
I also disabled beef.debug, beef.http.debug and Metasploit extension

**Comment by Im-Bob** [comment]
I also see "Internal server error" on the demo page, but the advanced page looks normal

**Comment by Im-Bob** [comment]
Here is the starting terminal before I click the hooking link if anybody is curious: https://pastebin.com/60v3YUFC

**Comment by bcoles** [comment]
> [15:24:38][!] Warning: System language $LANG '' does not appear to be UTF-8 compatible.
> ArgumentError - invalid byte sequence in US-ASCII:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-

**Comment by Im-Bob** [comment]
Wow! I think it worked! 
![image](https://user-images.githubusercontent.com/99659625/183663912-5b8c0800-af80-4c03-92c2-14616114127e.png)

**Comment by Im-Bob** [comment]
Thank you so much!
