### ISSUE TITLE
GET /favicon.ico 404 Not Found

### ISSUE THREAD

**Issue by egasik** [beefproject/beef#2530]
GET /favicon.ico 404 Not Found when i go on link for hook(

**Comment by jcrew99** [comment]
Hey @egasik,

Can you please fill out the Beef issue template with the requested information?

**Comment by bcoles** [comment]
egasik is referring to the error message in the Firefox browser console stating that the `favicon.ico` file cannot be loaded.

You can see the same error by browsing to http://example.com/.

BeEF does not ship with `favicon.ico`.
