### ISSUE TITLE
my link hook dont work

### ISSUE THREAD

**Issue by egasik** [beefproject/beef#2533]
![image](https://user-images.githubusercontent.com/110778955/183603455-596e3230-685f-482c-833a-9c3bf3cb6038.png)

**Comment by bcoles** [comment]
It looks like you're using ngrok. Have you followed the instructions in the wiki?

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

Be sure to refresh the hooked page after restarting BeEF.

**Comment by egasik** [comment]
Hi, i made it correctly, but doesnt work(

**Comment by egasik** [comment]
could it be due to the use of a virtual machine

**Comment by bcoles** [comment]
> Hi, i made it correctly, but doesnt work(

Where did you get stuck during trouble shooting?
What errors do you get in the browser console, if any?
What errors do you get in the terminal where you started beef, if any?
Can you successfully hook a browsers locally without ngrok?

**Comment by egasik** [comment]
I dont have errors on browser or terminal, how i can hook a browser locally? I can try it

**Comment by bcoles** [comment]
> I dont have errors on browser or terminal, how i can hook a browser locally? I can try it

Remove the public host and port settings from the config file. Access the demo page via a LAN interface or the loopback interface.

**Comment by egasik** [comment]
ok, i try it now

**Comment by egasik** [comment]
can you view my file? I think I didn't set it up...

_______________________________________________________________


---
beef:
  version: 0.5.4.0-pre
  debug: false
  client_debug: false
  crypto_default_value_length: 80
  credentials:
    user: kali
    passwd: kali
  restrictions:
    permitted_hooking_subnet:
    - 0.0.0.0/0
    - "::/0"
    permitted_ui_subnet:
    - 0.0.0.0/0
    - "::/0"
    excluded_hooking_subnet: []
    api_attempt_delay: '0.05'
  http:
    debug: false
    host: 0.0.0.0
    port: '3000'
    xhr_poll_timeout: 1000
    allow_reverse_proxy: false
    hook_file: "/hook.js"
    hook_session_name: BEEFHOOK
    restful_api:
      allow_cors: false
      cors_allowed_domains: http://browserhacker.com
    websocket:
      enable: false
      port: 61985
      secure: true
      secure_port: 61986
      ws_poll_timeout: 5000
      ws_connect_timeout: 500
    web_server_imitation:
      enable: true
      type: apache
      hook_404: false
      hook_root: false
    https:
      enable: false
      public_enabled: false
      key: beef_key.pem
      cert: beef_cert.pem
  database:
    file: db/beef.db
  autorun:
    result_poll_interval: 300
    result_poll_timeout: 5000
    continue_after_timeout: true
  dns_hostname_lookup: false
  geoip:
    enable: true
    database: "/var/lib/GeoIP/GeoLite2-City.mmdb"
  integration:
    phishing_frenzy:
      enable: false
  extension:
    admin_ui:
      enable: true
      base_path: "/ui"
    demos:
      enable: true
    events:
      enable: true
    evasion:
      enable: false
    requester:
      enable: true
    proxy:
      enable: true
    network:
      enable: true
    metasploit:
      enable: false
    social_engineering:
      enable: true
    xssrays:
      enable: true

**Comment by egasik** [comment]
and i find some errors - E, [2022-08-08T14:18:50.413901 #2174] ERROR -- BeEF: [AdminUI] Error: Could not minify JavaScript file: web_ui_auth
E, [2022-08-08T14:18:50.480892 #2174] ERROR -- BeEF: [GeoIP] Could not find MaxMind GeoIP database: '/var/lib/GeoIP/GeoLite2-City.mmdb'
E, [2022-08-08T14:43:10.353067 #2174] ERROR -- BeEF: [Browser Details] Invalid browser plugins returned from the hook browser's initial connection.

**Comment by bcoles** [comment]
> can you view my file? I think I didn't set it up...

The public host and public port aren't configured if that's what you're asking.

**Comment by egasik** [comment]
this is bad?

**Comment by bcoles** [comment]
> this is bad?

BeEF is not working for you. You will need to perform troubleshooting. Revert all your changes back to the default. Makse sure BeEF works. Then change one thing at a time and test that each change works.

**Comment by egasik** [comment]
ok, thanks
i will do it

**Comment by egasik** [comment]
Now i have it problem - An error occurred while installing xmlrpc (0.3.2), and Bundler cannot
continue.                                                                          

In Gemfile:
  xmlrpc

**Comment by bcoles** [comment]
> Now i have it problem - An error occurred while installing xmlrpc (0.3.2), and Bundler cannot continue.
> 
> In Gemfile: xmlrpc

Does beef run?

```
./beef
```

**Comment by egasik** [comment]
no. Type it Could not find em-websocket-0.5.3, uglifier-4.2.0, otr-activerecord-2.1.1, http-cookie-1.0.5 in any of the sources                                                    
Run `bundle install` to install missing gems.

**Comment by bcoles** [comment]
Please paste the full output of `bundle install`

**Comment by egasik** [comment]
┌──(kali㉿kali)-[~/beef]
└─$ bundle install
Fetching gem metadata from https://rubygems.org/......
Using rake 13.0.6
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/3.0.0
  /var/lib/gems/3.0.0/build_info
  /var/lib/gems/3.0.0/cache
  /var/lib/gems/3.0.0/doc
  /var/lib/gems/3.0.0/extensions
  /var/lib/gems/3.0.0/gems
  /var/lib/gems/3.0.0/plugins
  /var/lib/gems/3.0.0/specifications
Using concurrent-ruby 1.1.10
Using public_suffix 4.0.7
Using fiber-local 1.0.0
Using ast 2.4.2
Using nio4r 2.5.8
Using timers 4.3.3
Installing buftok 0.2.0
Installing ansi 1.5.0
Using bundler 2.3.14
Using daemons 1.4.1
Using minitest 5.16.2
Using unf_ext 0.0.8.2
Using eventmachine 1.2.7
Installing http_parser.rb 0.6.0
Using digest 3.1.0
Installing equalizer 0.0.11
Installing erubis 2.7.0
Using espeak-ruby 1.0.5
Using ffi 1.15.5
Using http-accept 1.7.0
Using json 2.6.2
Using http-form_data 2.3.0
Installing maxmind-db 1.1.1
Installing execjs 2.8.1
Using hashie 5.0.0
Installing thread_safe 0.3.6
Using mime-types-data 3.2022.0105
Using mojo_magick 0.6.7
Using multipart-post 2.2.3
Using ruby2_keywords 0.0.5
Installing naught 1.1.0
Installing netrc 0.11.0
Using parallel 1.22.1
Using parseconfig 1.1.2
Using rqrcode_core 0.2.0
Using rack 2.2.4
Using rainbow 3.1.1
Using timeout 0.3.0
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.2.0
Using rubyzip 2.3.2
Installing simple_oauth 0.3.1
Using tilt 2.0.11
Using slack-notifier 2.4.0
Using sqlite3 1.4.4
Using sync 0.5.0
Using webrick 1.7.0
Using i18n 1.12.0
Using tzinfo 2.0.5
Using addressable 2.8.0
Using console 1.15.3
Installing unf 0.1.4
Using parser 3.1.2.0
Using ffi-compiler 1.0.1
Installing hashie-forbidden_attributes 0.1.1
Using mime-types 3.4.1
Using mustermann 2.0.2
Using qr4r 0.6.1
Using rack-protection 2.2.2
Using thin 1.8.1
Using rexml 3.2.5
Using activesupport 7.0.3.1
Using http-parser 1.2.3
Using net-protocol 0.1.3
Using rubocop-ast 1.19.1
Using sinatra 2.2.2
Using tins 1.31.1
Installing xmlrpc 0.3.2
Using regexp_parser 2.5.0
Using async 1.30.3
Using net-smtp 0.3.1
Using term-ansicolor 1.7.1
Using msgpack 1.5.4
Using activemodel 7.0.3.1
Using async-io 1.33.0
Using msfrpc-client 1.1.2
Using rubocop 1.33.0
Using async-dns 1.3.0
Using activerecord 7.0.3.1
Bundler::GemNotFound: Could not find ansi-1.5.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in    
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing ansi (1.5.0), and Bundler cannot
continue.                                                                          

In Gemfile:
  ansi


Bundler::GemNotFound: Could not find buftok-0.2.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing buftok (0.2.0), and Bundler cannot
continue.                                                                          

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    buftok


Bundler::GemNotFound: Could not find unf-0.1.4.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing unf (0.1.4), and Bundler cannot
continue.                                                                          

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    http was resolved to 4.4.1, which depends on
      http-cookie was resolved to 1.0.5, which depends on
        domain_name was resolved to 0.5.20190701, which depends on
          unf


Bundler::GemNotFound: Could not find http_parser.rb-0.6.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing http_parser.rb (0.6.0), and Bundler
cannot continue.                                                                   

In Gemfile:
  em-websocket was resolved to 0.5.3, which depends on
    http_parser.rb


Bundler::GemNotFound: Could not find equalizer-0.0.11.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing equalizer (0.0.11), and Bundler cannot
continue.                                                                          

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    equalizer


Bundler::GemNotFound: Could not find erubis-2.7.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing erubis (2.7.0), and Bundler cannot
continue.                                                                          

In Gemfile:
  erubis


Bundler::GemNotFound: Could not find execjs-2.8.1.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing execjs (2.8.1), and Bundler cannot
continue.                                                                          

In Gemfile:
  uglifier was resolved to 4.2.0, which depends on
    execjs


Bundler::GemNotFound: Could not find hashie-forbidden_attributes-0.1.1.gem for
installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing hashie-forbidden_attributes (0.1.1),
and Bundler cannot continue.                                                       

In Gemfile:
  otr-activerecord was resolved to 2.1.1, which depends on
    hashie-forbidden_attributes


Bundler::GemNotFound: Could not find maxmind-db-1.1.1.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing maxmind-db (1.1.1), and Bundler cannot
continue.                                                                          

In Gemfile:
  maxmind-db


Bundler::GemNotFound: Could not find thread_safe-0.3.6.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing thread_safe (0.3.6), and Bundler cannot
continue.                                                                          

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    memoizable was resolved to 0.4.2, which depends on
      thread_safe


Bundler::GemNotFound: Could not find naught-1.1.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing naught (1.1.0), and Bundler cannot
continue.                                                                          

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    naught


Bundler::GemNotFound: Could not find netrc-0.11.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing netrc (0.11.0), and Bundler cannot
continue.                                                                          

In Gemfile:
  rushover was resolved to 0.3.0, which depends on
    rest-client was resolved to 2.1.0, which depends on
      netrc


Bundler::GemNotFound: Could not find simple_oauth-0.3.1.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing simple_oauth (0.3.1), and Bundler
cannot continue.                                                                   

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    simple_oauth


Bundler::GemNotFound: Could not find xmlrpc-0.3.2.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing xmlrpc (0.3.2), and Bundler cannot
continue.                                                                          

In Gemfile:
  xmlrpc
                                                                                   
┌──(kali㉿kali)-[~/beef]
└─$

**Comment by bcoles** [comment]
Welp. You're going to need to install the dependencies to get BeEF working.

**Comment by egasik** [comment]
i make it, but i have this is problem

**Comment by bcoles** [comment]
You can try installing each of the missing gems manually. Removing `Gemfile.lock` may also help.

**Comment by egasik** [comment]
there i can find Gemfile.lock?

**Comment by egasik** [comment]
Hello, now i have this is error [ 4:26:53][*] BeEF server started (press control+c to stop)
[ 4:26:53][!] Another process is already listening on port 3000, or you're trying to bind BeEF to an invalid IP.
[ 4:26:53][!] Is BeEF already running? Exiting...

**Comment by bcoles** [comment]
> Hello, now i have this is error [ 4:26:53][*] BeEF server started (press control+c to stop) [ 4:26:53][!] Another process is already listening on port 3000, or you're trying to bind BeEF to an invalid IP. [ 4:26:53][!] Is BeEF already running? Exiting...

Something is already listening on port 3000. You can check what is running on port 3000 with `lsof -i :3000`.
