### ISSUE TITLE
How do I configure BeEF with ngrok?

### ISSUE THREAD

**Issue by Archilla1** [beefproject/beef#2537]
Hi! currently downloaded Beef 0.5.4.0-pre in kali. I am currently figuring things on my own but it seems that I can only see my local IP address. I checked other issues and I noticed that I do not have the option for  beef.http.public and beef.http.public_port in my config.yaml. for some reason I might have the same issue on many Linux applications. I do apologize for being such a newbie, but I feel stuck. Application works fine, just want to know if using it myself will show my local ip instead of the public or private.

## Configuration

1. Have you made any changes to your BeEF configuration? Yes, enabled metasploit, client debug, and password
2. Have you enabled or disabled any BeEF extensions? Yes

![beef pic](https://user-images.githubusercontent.com/110798175/183850589-9ed3c9af-815c-4ae5-ba4b-7d011eafe451.png)
![beef pic 1](https://user-images.githubusercontent.com/110798175/183850718-678d51ff-23ee-4dc0-b194-7a38d95c9bde.png)

**Comment by bcoles** [comment]
Sample config file is here.

https://github.com/beefproject/beef/blob/master/config.yaml

The section you're looking for is:

https://github.com/beefproject/beef/blob/72261c4fcd39601effa474274608347033e1d492/config.yaml#L53-L57

Remove the comments. Make sure the text is aligned properly. It should look like this.

```
beef:

    # ...

    http:

        # ...

        public: 
            host: "<ngrok-id>.ngrok.io" # ngrok domain name for forwarding URL
            port: "443"                 # ngrok port for forwarding URL (443 for HTTPS)
            https: true                 # ngrok supports HTTPS by de
```

**Comment by Archilla1** [comment]
![beef pic 3](https://user-images.githubusercontent.com/110798175/184063259-07438984-0179-438c-ab52-c65cba819f3f.png)


I think I put it right lol. Still shows my Local Ip address.

**Comment by bcoles** [comment]
> I think I put it right lol. Still shows my Local Ip address.

The `host` field requires a host rather than a URL. Also it looks like you've appended a path to the URL.

**Comment by Archilla1** [comment]
sorry again... 

The only thing I see that has something like "<ngrok-id>.ngrok.io" is when I open a tunnel on either port 80 or 443. I could just leave my public or private IP address if that is what it means.  I feel lost when understanding the  # ngrok domain name for forwarding URL. if you can please say it dummy prove I will take it

**Comment by bcoles** [comment]
> sorry again...
> 
> The only thing I see that has something like ".ngrok.io" is when I open a tunnel on either port 80 or 443. I could just leave my public or private IP address if that is what it means. I feel lost when understanding the # ngrok domain name for forwarding URL. if you can please say it dummy prove I will take it

When you start ngrok it prints some information including the ngrok URL.

A URL consists of various parts constructed like this:

```
<scheme>://<host>[:<port>]/path[?<query>][#<anchor>]
```

You want the host.

**Comment by Archilla1** [comment]
The host is always changing. Will I need then to update beef confi.yaml everytime I start ngrok?

Also, I did sudo beef-xss-stop -h to start over and now I have:

![beef pic 2](https://user-images.githubusercontent.com/110798175/184073785-06c7df43-eed6-4dc7-a34a-22db53dcbcb7.png)

going crazy here lol

**Comment by bcoles** [comment]
> The host is always changing. Will I need then to update beef confi.yaml everytime I start ngrok?

Yes.

> going crazy here lol

self inflicted

>Also, I did sudo beef-xss-stop -h to start over and now I have:

Check the logs. `journalctl -u beef-xss`.

**Comment by Archilla1** [comment]
Definitely inflicted, but learning for sure

![beef pic 4](https://user-images.githubusercontent.com/110798175/184074654-66f5fe8d-28c7-4b6b-bf33-460b92a365ab.png)

the other attempts have the same output

**Comment by bcoles** [comment]
The error message is cut off.

What happens when you start BeEF?

**Comment by Archilla1** [comment]
That is all I have: (same output)


![beef pic 5](https://user-images.githubusercontent.com/110798175/184075524-75138a6a-decf-4e2b-9f9b-4a337ee8b34a.png)

**Comment by Archilla1** [comment]
Aug 11 02:06:53 kali systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 02:06:53 kali systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Aug 11 02:06:53 kali systemd[1]: beef-xss.service: Consumed 1.214s CPU time.
Aug 11 02:27:17 kali systemd[1]: Started beef-xss.
Aug 11 02:27:18 kali beef[159546]: /usr/share/beef-xss/extensions/metasploit/rest/msf.rb:1:in `require_relative': cannot load such file -- /var/lib/beef-xss/core/main/router/router (LoadE>
Aug 11 02:27:18 kali beef[159546]:         from /usr/share/beef-xss/extensions/metasploit/rest/msf.rb:1:in `<top (required)>'
esupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
oad'
block in load'
each'
load'

-pre



/wiki

FAILURE



`require_relative': cannot load such file -- /var/lib/beef-xss/core/main/router/router (LoadError)
/msf.rb:1:in `<top (required)>'
rnel_require.rb:148:in `require'
rnel_require.rb:148:in `require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
nsion.rb:95:in `<top (required)>'
esupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
oad'
block in load'
each'
load'

-pre



/wiki

FAILURE



`require_relative': cannot load such file -- /var/lib/beef-xss/core/main/router/router (LoadError)
/msf.rb:1:in `<top (required)>'
rnel_require.rb:148:in `require'
rnel_require.rb:148:in `require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
nsion.rb:95:in `<top (required)>'
rnel_require.rb:148:in `require'
rnel_require.rb:148:in `require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
oad'
block in load'
each'
load'

-pre



/wiki

FAILURE



`require_relative': cannot load such file -- /var/lib/beef-xss/core/main/router/router (LoadError)
/msf.rb:1:in `<top (required)>'
rnel_require.rb:148:in `require'
rnel_require.rb:148:in `require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
nsion.rb:95:in `<top (required)>'
rnel_require.rb:148:in `require'
rnel_require.rb:148:in `require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
esupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
esupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
oad'
block in load'
each'
load'

-pre

**Comment by Archilla1** [comment]
Just disabled metasploit, and it works.

**Comment by Archilla1** [comment]
okay! This is the whole thing:



![beef pic 8](https://user-images.githubusercontent.com/110798175/184079508-402c628b-8125-4a0d-a5b1-cd325116f9fc.png)

**Comment by bcoles** [comment]
> okay! This is the whole thing:

Close.

It should look like this.

```
beef:

    # ...

    http:

        # ...

        public: 
            host: "<ngrok-id>.ngrok.io" # ngrok domain name for forwarding URL
            port: "443"                 # ngrok port for forwarding URL (443 for HTTPS)
            https: true                 # ngrok supports HTTPS by de
```

**Comment by Archilla1** [comment]
public: 
      host: "9f6d-65-99-68-34.jp.ngrok.io"
      port: "443"
      https: true

tried that and nothing. it does not even place my local ip online anymore

**Comment by Archilla1** [comment]
I can only see my local IP still. If there is a way we can do this through a shared screen  or remotely I would appreciate it

**Comment by bcoles** [comment]
> public: host: "9f6d-65-99-68-34.jp.ngrok.io" port: "443" https: true

Correct.

> tried that and nothing. it does not even place my local ip online anymore

I don't know what that means.

**Comment by bcoles** [comment]
> I can only see my local IP still.

I have no idea what that means.

Change 4 lines the config file as you've done. Load the demo page using the ngrok URL.

**Comment by Archilla1** [comment]
when you click on "To begin with you can point a browser towards the basic demo page [here](http://127.0.0.1:3000/demos/basic.html), or the advanced version [here](http://127.0.0.1:3000/demos/butcher/index.html)" on the main page it takes you to The Butcher, after that, the device that accessed that link appears online on the left side. As far as I know and have seen, it is not the local IP address. it is usually my eth0 IP address.

**Comment by bcoles** [comment]
> when you click on "To begin with you can point a browser towards the basic demo page [here](http://127.0.0.1:3000/demos/basic.html), or the advanced version [here](http://127.0.0.1:3000/demos/butcher/index.html)" on the main page it takes you to The Butcher, after that, the device that accessed that link appears online on the left side. As far as I know and have seen, it is not the local IP address. it is usually my eth0 IP address.

Those links are generated based on the interface IP address.

Load the demo page using the ngrok URL.

```
https://<your ngrok id>.ngrok.io/demos/basic.html
```

**Comment by Archilla1** [comment]
ERR_NGROK_8012

Traffic was successfully tunneled to the ngrok agent, but the agent failed to establish a connection to the upstream web service at [localhost:443](http://localhost:443/). The error encountered was:

dial tcp [::1]:443: connect: connection refused

got this by ngrok. but the link worked

**Comment by bcoles** [comment]
> got this by ngrok. but the link worked

Those are conflicting statements.

Start BeEF. Ensure BeEF is running. Start ngrok.

**Comment by Archilla1** [comment]
Okay Im in! I do not see the device appearing on beef. I just tried from my phone.

**Comment by bcoles** [comment]
> Okay Im in! I do not see the device appearing on beef. I just tried from my phone.

Where did you get stuck during debugging?

**Comment by Archilla1** [comment]
I have done everything step by step. I got ngrok to work and everything but i have no idea now
1. start ngrok on port 80
2.add host in config.yaml
3.run beef
4. open link from ngrok.
5. visit page
Once in that is it. No device populates

**Comment by bcoles** [comment]
> I have done everything step by step

> start ngrok on port 80

Port 80? See:

 *https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by Archilla1** [comment]
I did try ports 80,443, and 3000 and same thing

**Comment by bcoles** [comment]
> I did try ports 80,443, and 3000 and same thing

Neither of us have any idea what you are doing.

Getting BeEF working with ngrok is not difficult You literally need to change 4 lines in the config file.

I suggest starting again. Whatever you are doing is not right.

Maybe take a step back and think about what you're doing.

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

Start BeEF. Start ngrok. Browse to: `https://<your ngrok id>.ngrok.io/demos/basic.html`.

**Comment by Archilla1** [comment]
I was able to access http://<your WAN IP address>:3000/ui/panel

I click http://127.0.0.1:3000/demos/butcher/index.html and I can access it, but not even my local address appears online on beef

started ngrok http 3000

Was able to access /demos/basic.html  

Now it works!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 

Im sorry for the headache!! Tell everyone Thank you so much for your patience!!!!

**Comment by t00fi** [comment]
> ERR_NGROK_8012
> 
> Traffic was successfully tunneled to the ngrok agent, but the agent failed to establish a connection to the upstream web service at [localhost:443](http://localhost:443/). The error encountered was:
> 
> dial tcp [::1]:443: connect: connection refused
> 
> got this by ngrok. but the link worked

the reason is because there is no service running on that port,
