### ISSUE TITLE
beef hook link don't work on other devices on my network/outside my network

### ISSUE THREAD

**Issue by Im-Bob** [beefproject/beef#2538]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. BeEF Version: 0.5.4.0
4. Ruby Version: 3.0.4
5. Browser Details (e.g. Chrome v81.0): Firefox 91.11.0
6. Operating System (e.g. OSX Catalina): Kali Linux [name -r = 5.10.16.3-microsoft-standard-WSL2]

## Configuration

1. Have you made any changes to your BeEF configuration? No
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

1. The http:// myip :3000/hook.js only works for my network and not for anyone outside my network.
2. I also tried to use another computer on my network and it took too long to respond to the page
3. I tried to use the hook link, the demo page, and the advanced page. None of them respond to other devices

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
4. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
5. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by Im-Bob** [comment]
It also says that port 3000 is closed on the IP beef gives me

**Comment by N3WB13001** [comment]
> ## First Steps
> 1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
> 2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
> 3. BeEF Version: 0.5.4.0
> 4. Ruby Version: 3.0.4
> 5. Browser Details (e.g. Chrome v81.0): Firefox 91.11.0
> 6. Operating System (e.g. OSX Catalina): Kali Linux [name -r = 5.10.16.3-microsoft-standard-WSL2]
> 
> ## Configuration
> 1. Have you made any changes to your BeEF configuration? No
> 2. Have you enabled or disabled any BeEF extensions? No
> 
> ## Steps to Reproduce
> 1. The http:// myip :3000/hook.js only works for my network and not for anyone outside my network.
 did you forwarded the port 3000 from your router ? and if you have , have you added the public ip and port in the config file? if you have not , then first forward port forward 3000 and visit this faq page https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

**Comment by N3WB13001** [comment]
did you forwarded the port 3000 from your router ? and if you have , have you added the public ip and port in the config file? if you have not , then first forward port forward 3000 and visit this faq page https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

**Comment by Im-Bob** [comment]
I port forwarded through my router (I used my windows computers local ip):
![portforwarding](https://user-images.githubusercontent.com/99659625/184194767-dba3202f-e97b-4efb-bef1-e6cd78b9bc09.png)

I also changed the config.yaml file to my public windows ip address
![config yaml](https://user-images.githubusercontent.com/99659625/184195057-1ac5a172-6892-443b-a5b0-bbfb0bff0669.png)

I'm using WSL2 btw

Beef's also saying that I'm trying to bind beef to an invalid ip address or there might be another proccess running on port 3000 (There's none)

**Comment by N3WB13001** [comment]
well, then i don't exactly understand or know how to fix your issue. it might happen with windows firewall or some issue with port forwarding i guess.

**Comment by bcoles** [comment]
> The http:// myip :3000/hook.js only works for my network and not for anyone outside my network.
> I also tried to use another computer on my network and it took too long to respond to the page
> I tried to use the hook link, the demo page, and the advanced page. None of them respond to other devices
> I'm using WSL2 btw

You need to establish a network router. The WSL system uses different network interfaces to the Windows host. Many if not all will not be routable from outside the Windows host.

The route from the WSL system to the Internet looks like this:

BeEF -> WSL network interfaces -> Windows host -> LAN -> router -> WAN.

To access BeEF from the Internet you will need to establish a route:

WAN -> router -> Windows host -> WSL -> BeEF

**Comment by meshark12** [comment]
Hello, I am currently having the same problem. i have tried all the suggestions mentioned but am still unable to hook external devices.

**Comment by bcoles** [comment]
> Hello, I am currently having the same problem. i have tried all the suggestions mentioned but am still unable to hook external devices.

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

**Comment by bcoles** [comment]
> I also changed the config.yaml file to my public windows ip address ![config yaml](https://user-images.githubusercontent.com/99659625/184195057-1ac5a172-6892-443b-a5b0-bbfb0bff0669.png)
> 
> Beef's also saying that I'm trying to bind beef to an invalid ip address, or there might be another process running on port 3000 (There's none)

You've changed the `host` rather than than the `public.host`.

**Comment by Im-Bob** [comment]
I used the following command to open an IP to wsl: netsh interface portproxy add v4tov4 listenport=3000 listenaddress=0.0.0.0 connectport=3000 connectaddress=172.26.42.73

I also added the IP to the public.host:
![wslip](https://user-images.githubusercontent.com/99659625/186484691-f6790fb6-0249-48d9-a862-b4ec333e5ad5.png)

I now can open the hook on my wsl, but not on my smartphone for example. The page just won't load once again

**Comment by bcoles** [comment]
> I now can open the hook on my wsl, but not on my smartphone for example. The page just won't load once again

https://github.com/beefproject/beef/issues/2538#issuecomment-1212648407
