### ISSUE TITLE
Beef question - port forward

### ISSUE THREAD

**Issue by Kayr123** [beefproject/beef#2544]
So i know how to use beef within lan network but i changed my other phone to another network and it doesn't work .. i know i have to use portforward 

I watched in yt some videos about ngrok . But didn't work .

So how to use beef over wan .. can i use it with porntmap

**Comment by bcoles** [comment]
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
