### ISSUE TITLE
Fatal Error: cannot load configuration file '/home/fsociety/beef/./config.yaml' : (<unknown>): did not find expected key while parsing a block mapping at line 37 column 9

### ISSUE THREAD

**Issue by psybervac** [beefproject/beef#2549]
The Beef framework works well on the local network. But when i tried to set it up with ngrok and edited the config.yaml file it stops working and gives me this error. No idea what to fix here. Please help. 

![image](https://user-images.githubusercontent.com/110818739/185653262-058be39d-713e-45ad-bee2-b7a7e6d4cfbc.png)
![image](https://user-images.githubusercontent.com/110818739/185653362-7861b68a-6abb-4dd3-b1f0-e8d145affa70.png)

**Comment by bcoles** [comment]
The error message means your configuration file is malformed.

The config file is in YAML format. White space formatting is important. The alignment of the `public:` is off by one. Remove a single space before `public:`.

**Comment by psybervac** [comment]
Thank you. It worked.
