### ISSUE TITLE
Beef with ngrok/portmap - WAN 

### ISSUE THREAD

**Issue by psybervac** [beefproject/beef#2550]
Beef works fine on my localhost network. I have been trying to make beef work outside my local network for last 1 week. Have tried numerous attempts /tutorials/ installing - uninstalling both beef and Kali linux fresh over. Gone through several closed issues. But now i am tired and lost hope. I just want to know if anyone has got it to work so far.  Any of you has got it working with ngrok or portmap, please reply.

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by psybervac** [comment]
I have gone through these steps again and again with all the combinations in the config.yaml file. It never works.

**Comment by psybervac** [comment]
Let me start again and show you the errors
