### ISSUE TITLE
Troubleshooting the Beef -portmap - portforwarding - outside the local network issue

### ISSUE THREAD

**Issue by psybervac** [beefproject/beef#2551]
Case 1 : When config.yaml file is not edited - public key is commented 

![image](https://user-images.githubusercontent.com/110818739/185870915-3956ccd5-5fe3-44b9-992a-2a77cacd12b8.png)

-- beef starts fine with no errors
-- ui panel works
-- hook demo and hook by inserting the script in a index.html file of /var/www/html works fine.

![image](https://user-images.githubusercontent.com/110818739/185871418-94603381-a5cd-428f-a82e-986086f731db.png)

![image](https://user-images.githubusercontent.com/110818739/185871501-e676d664-6b1d-4eda-a699-6c54e8c1f483.png)

![image](https://user-images.githubusercontent.com/110818739/185871555-a3f73764-1874-4f75-bb40-2b0d600bc299.png)

Now, i have been trying with portmap to use it outside my network . 
-- created portmap account with port forwarding to port 3000
-- tried to use it with the QRLJacking tool and it worked fine and i was able to access the link over a different network. 
-- Now in beef config.yaml i make the following changes as per the ngrok instructions - 
public: 
            host: "psybaba-21698.portmap.host"
            port: "443"                
            https: true     

![image](https://user-images.githubusercontent.com/110818739/185872947-24702c58-fd49-480a-aa5b-9a569cc0330e.png)

-- beef start ok with no errors
-- able to access ui 
--  Hook url demo opens but no hooks shown / same with the localhost page in index.html 
![image](https://user-images.githubusercontent.com/110818739/185874147-dad7237e-9279-4cf9-b147-75185b604b5f.png)

-- the portmap url opens to an apache test page on other networks too (that means it is working right?)
![image](https://user-images.githubusercontent.com/110818739/185874434-10d1b46a-7ddc-4226-ab83-bbc9f2e6d432.png)

-- tried to change the script url in the index.html page as follows to the portmap hook.js

![image](https://user-images.githubusercontent.com/110818739/185874777-d057f2d4-f5e8-4b9e-9aac-05ea86244bb6.png)

-- The hook demo page and the index.html pages load up but no hooks shown in beef

Another try with another configuration : 
-- changed the port to "21698"  - the port in portmap
![image](https://user-images.githubusercontent.com/110818739/185875853-91ec43fa-2466-4460-924f-63f726a91a31.png)

result: 
-- beef runs fine
-- able to access ui
-- still the same - no hooks on any demo page or index.html 
-- the portmap link still opening on apache test page
-- changing the hook.js in index.html to the new public hook.js
![image](https://user-images.githubusercontent.com/110818739/185876546-56554e54-aa32-45ba-b0c2-29008affab51.png)

The same results overall . no errors in any of the troubleshooting so far. 

I a lost now. please help to continue from here. What am i doing wrong? The portmap link is working fine but no hooks are shown in beef ui panel or cli . 
And also the contents of my var/www/html is not accessible over the network.

**Comment by bcoles** [comment]
Are you able to load the demo page in a browser when using `https://` rather than `http://` ?

**Comment by psybervac** [comment]
> Are you able to load the demo page in a browser when using `https://` rather than `http://` ?

The demo pages are loading with every change i made. Nothing wrong with them . But in the beef UI panel/cli - it doesn`t show any hooked browsers

**Comment by psybervac** [comment]
But it all works fine again if i comment the public setting in the config.yaml file

**Comment by bcoles** [comment]
> > Are you able to load the demo page in a browser when using `https://` rather than `http://` ?
> 
> The demo pages are loading with every change i made. Nothing wrong with them . But in the beef UI panel/cli - it doesn`t show any hooked browsers

None of the screenshots show loading the demo page using `https://` rather than `http://`.

**Comment by bcoles** [comment]
Are you able to load the hook file over HTTPS?  `https://psybaba-21698.portmap.host/hook.js`

Is the SSL certificate you're using trusted in the browser?

Are there errors in the browser console ? is there network traffic in the `Network` tab ? Is it going to the right host? Does it load? Do you see the expected content in the response?

**Comment by psybervac** [comment]
Let me go through all of these questions one by one. Please wait.

**Comment by psybervac** [comment]
this is the config.yaml setting - 
![image](https://user-images.githubusercontent.com/110818739/185893647-97be2c8a-c523-4a0c-9775-f0f6a39f062c.png)

![image](https://user-images.githubusercontent.com/110818739/185893911-bb440f23-779c-4f67-ab5d-e1af885be812.png)

--now if i try to access the ui panel on https://psybaba-21698.portmap.host:443/ui/panel  -  it gives me a 404 error on portmap site
-- i am able to login through other ui links
-- when trying to access hook file over https : this is the error

![image](https://user-images.githubusercontent.com/110818739/185894293-c282b958-af99-4158-8a4b-6b2a822c99fd.png)

-- SSL certificate - which one ? I don`t get a SSL certificate in portmap`s free account.

**Comment by bcoles** [comment]
I don't think your portmap is configured properly as you can't load the hook file or demo pages using the portmap URL using HTTPS. `hook.js` should not be a 404.

> -- SSL certificate - which one ?

The SSL certificate presented when you attempt to load the hook or demo page over HTTPS.

> I dont get a SSL certificate in portmaps free account.

Does portmap support HTTPS for free accounts? If it does not, you will not be able to use HTTPS.

**Comment by psybervac** [comment]
Ok, in that case can i use http ? by putting https = false in config file or maybe use another service for port forwarding.

**Comment by bcoles** [comment]
> Ok, in that case can i use http ? by putting https = false in config file

Yes you can use http by changing the public `https` setting to `false`. You'll also need to change the public `port` - presumably to `80`.

> or maybe use another service for port forwarding.

ngrok is an alternative.

**Comment by psybervac** [comment]
yes but ngrok and also i tried loclxpose both have a warning sign before visiting the page. Is there a way to bypass that?

**Comment by psybervac** [comment]
Also if you can help or point out some resources on how to/where to add content so the link doesn`t go to apache test page.

**Comment by bcoles** [comment]
> yes but ngrok and also i tried loclxpose both have a warning sign before visiting the page. Is there a way to bypass that?

I have no idea what you're talking about.

> Also if you can help or point out some resources on how to/where to add content so the link doesn`t go to apache test page.

You mean the home page on the BeEF server? If `beef.http.web_server_imitation` is enabled, the content is controlled by `core/main/router/router.rb`.

**Comment by psybervac** [comment]
Let me explain - 

I am using localxpose which is similar to ngrok

i start the tool with forwarding the port at 3000
![image](https://user-images.githubusercontent.com/110818739/185908851-23fc34c3-6300-4917-8790-bcf6786b55ae.png)

And now i put the host url in the config file 

![image](https://user-images.githubusercontent.com/110818739/185909101-a66318d3-529f-492e-8a08-011581513432.png)

Now we run beef  
![image](https://user-images.githubusercontent.com/110818739/185909379-55387f29-9752-4c82-a1dc-26b8e25474ca.png)

And here i am able to login via https UI panel  

![image](https://user-images.githubusercontent.com/110818739/185909793-567beed1-e265-4bc4-b5e5-42c595c629ff.png)
Even we can get the hook url to work in https 

![image](https://user-images.githubusercontent.com/110818739/185910058-2cdc0533-3d74-47cd-bf85-454c0e79e515.png)

And i can get the hooked browsers in the UI 
![image](https://user-images.githubusercontent.com/110818739/185910229-6c6561d8-6a8b-47da-aa6e-aa23a6367999.png)
 Now my question - which link should i send to my victim . If i send the link localxpose gave me -  3v08syki6q.loclx.io   i get the test page for apache 2. 
Which i guess tells me the link is working over the internet. But now how/where do i put the hook.js script to link it to a page/website to be shares. I have tried to put files in the var/www/html folder but that doesn`t work.

**Comment by bcoles** [comment]
The hook file is served from `/hook.js` by default. So whatever your public URL is, add `/hook.js`.

**Comment by bcoles** [comment]
BeEF also prints the hook URL to terminal where it says "hook URL".

The hook it written in JavaScript. You can include it like you would any other script.

**Comment by psybervac** [comment]
Alright. So if i just send the hook url to someone should it hook their browser if they open it? When i try to open it on my end on a different network machine it shows the jquery codes. but it doesn`t hook the browser.

**Comment by bcoles** [comment]
> Alright. So if i just send the hook url to someone should it hook their browser if they open it?

No. You had the right idea before when you were using portmap.

![](https://user-images.githubusercontent.com/110818739/185874777-d057f2d4-f5e8-4b9e-9aac-05ea86244bb6.png)

**Comment by psybervac** [comment]
ok let me try it with localxpose

**Comment by bcoles** [comment]
Check the Network tab in the browser developer tools. This would have solved all your previous questions and will likely assist with any other questions you have.

If you cannot access hook.js or cannot access the demo pages then your network configuration is broken. There is no point in proceeding with modifying the public settings in the `config.yaml` file if your network configuration is broken.

I get a "TUNNEL NOT FOUND" error for: `https://lbeyklio4r.loclx.io/hook.js`

**Comment by psybervac** [comment]
ok now i am trying with ngrok . Same thing happens . https://eb00-2401-4900-3b1a-2bba-7d7c-9c86-6d02-6e0d.ngrok.io:443/hook.js 
If i open the website with the link on my local network it works but not on the WAN. 

Let me go through the network tab first as you suggested.

**Comment by bcoles** [comment]
Why not use a `<script>` tag in your html file hosted on Apache like you were doing before?

The key to troubleshooting is to eliminate complexity and apply the scientific method. Starting with a working configuration and change one thing at a time.

**Comment by psybervac** [comment]
Than you very much . It worked finally. As you said,i checked for all the network configurations. It was all okay. 
Next i went for the demos link, it was working on wan. 
 Edited the demos - basic.html  and all is well now. 

I thank you again as i said i was going crazy fro last 1 week in fixing this.

**Comment by roots123** [comment]
bonjour svp j'ai à peu près le même souci j'ai besoin d'aide merci de bien vouloir me répondre
