### ISSUE TITLE
can't install beef and run bundle install

### ISSUE THREAD

**Issue by DamienDeveloppeur** [beefproject/beef#2560]
Hello,

I tried to run the install (./install), but i got this issue :

ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.

![image](https://user-images.githubusercontent.com/91346259/188322005-2d683fa3-02dd-4e3c-b11c-3b75863b6c33.png)

So i tried to run bundle install (bundle3.0 install too), and i got this issue : 

![image](https://user-images.githubusercontent.com/91346259/188321982-3e3868e1-d680-4eb4-956f-50884114d76b.png)

I installed ruby and rubygems before all of this, someone can help me ? 

Best regards,

**Comment by 3dpro45** [comment]
I am having the same issues, and will report to you if I figure anything out. Best of luck. (see my issue post)

**Comment by bcoles** [comment]
Yeah you'll have to mess with the gems until you get it working.

**Comment by atomheartedboy** [comment]
cd /path/to/beef
rm Gemfile.lock
bundle3.0 install

then try again with ./install and ./beef

**Comment by atomheartedboy** [comment]
ok no issues what do you get when you run ./beef

**Comment by DamienDeveloppeur** [comment]
> 
![image](https://user-images.githubusercontent.com/91346259/188589167-94cdc9cd-654e-48c8-84d7-4bbccac435ff.png)

(bundle install does not work, as mentioned above)

**Comment by atomheartedboy** [comment]
good now,what i am going to tell you will take few minutes but you`ll have it running for sure. 
Just type  gem install rushover

**Comment by atomheartedboy** [comment]
and again do ./beef 
it will again come up with some error - could not find gem `gemname`
what you have to do is again type gem install NameOfTheMissingGem
and do ./beef again and do the gem install again for each gemfile.  Once you are done with all it will give you the option to change the beef password

**Comment by atomheartedboy** [comment]
Let me know if you got stuck somewhere

**Comment by DamienDeveloppeur** [comment]
> 

i sincerely thanks you ! Ur idea was excellent and it's work !
