### ISSUE TITLE
Unable to locate installer for EndeavourOS

### ISSUE THREAD

**Issue by LucasVChaves** [beefproject/beef#2561]
I'm trying to install beef v0.5.4.0 in my EndeavourOS (version Artemis_Neo_22_8) machine and it doesn't seems to be compatible.
Ruby, Sqlite and NodeJS are up to date.

Endeavour is arch based so I thought it would install without any distro related problems. 

![Captura de tela de 2022-09-05 11-26-35](https://user-images.githubusercontent.com/25365599/188471555-75850e84-ca76-4b3b-8d57-4e1a8810891f.png)

**Comment by bcoles** [comment]
I thought we did have support for EndeavourOS in the installer.

The install script is fairly simple. It installs a few operating system packages then runs `gem install bundler` and `bundle install`.

**Comment by LucasVChaves** [comment]
I ran the commands and was able to start the program. Thanks for the help 😄 !
