### ISSUE TITLE
Kali VM 404

### ISSUE THREAD

**Issue by Wamibit** [beefproject/beef#2562]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. BeEF Version:
4. Ruby Version:
5. Browser Details (e.g. Chrome v81.0):
6. Operating System (e.g. OSX Catalina):

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No
2. Have you enabled or disabled any BeEF extensions? Yes/No

## Steps to Reproduce

1. (eg. I ran install script, which ran fine)
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
3. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by Wamimit** [comment]
Using preinstalled beef-xss on Kali VM.  whether i launch it from /usr/share/beef-xss or from Kali menu, i have both 404 on http://127.0.0.1:3000/ui/panel (i am not using ngrok). 

nothing is running on port 3000 (i check with lsof -i :3000)

service beef-xss status

● beef-xss.service - beef-xss
     Loaded: loaded (/lib/systemd/system/beef-xss.service; disabled; preset: disabled)
     Active: active (running) since Mon 2022-09-05 19:10:54 CEST; 59s ago
   Main PID: 4126 (ruby)
      Tasks: 2 (limit: 4630)
     Memory: 67.7M
        CPU: 1.422s
     CGroup: /system.slice/beef-xss.service
             └─4126 ruby /usr/share/beef-xss/beef

Sep 05 19:10:56 kali beef[4126]: [19:10:55][!] Unable to load extension 'demos'
Sep 05 19:10:56 kali beef[4126]: [19:10:55][!] Unable to load extension 'events'
Sep 05 19:10:56 kali beef[4126]: [19:10:55][!] Unable to load extension 'requester'
Sep 05 19:10:56 kali beef[4126]: [19:10:55][!] Unable to load extension 'proxy'
Sep 05 19:10:56 kali beef[4126]: [19:10:55][!] Unable to load extension 'network'
Sep 05 19:10:56 kali beef[4126]: [19:10:55][!] Unable to load extension 'social_engineering'
Sep 05 19:10:56 kali beef[4126]: [19:10:55][!] Unable to load extension 'xssrays'
Sep 05 19:10:56 kali beef[4126]: -- migration_context()
Sep 05 19:10:56 kali beef[4126]:    -> 0.0047s
Sep 05 19:10:56 kali beef[4126]: [19:10:56][*] BeEF is loading. Wait a few seconds...

**Comment by Wamibit** [comment]
Anyone?

**Comment by rap-hack** [comment]
I got same 404 error on kali in VM, it loads in my machine but not on target machine. What should I do.......????

**Comment by bcoles** [comment]
> I got same 404 error on kali in VM, it loads in my machine but not on target machine. What should I do.......????

There is nowhere near enough information to offer any guidance here.

**Comment by bcoles** [comment]
> Sep 05 19:10:56 kali beef[4126]: [19:10:55][!] Unable to load extension 'demos'

That doesn't look right. I vaguely recall someone had issues with symlinks on Kali.

As a workaround you could try cloning from git.

**Comment by Wamibit** [comment]
I did also clone from git, same result 404. what further info. do you need and i'll provide? tx

**Comment by bcoles** [comment]
> I did also clone from git, same result 404. what further info. do you need and i'll provide? tx

Screenshot please.

**Comment by Wamibit** [comment]
![image](https://user-images.githubusercontent.com/87818430/189480204-1675efa2-7283-47c9-80c1-1e969996fdc6.png)

**Comment by bcoles** [comment]
Strange. Are there any hints in the terminal where you started BeEF? Can you access other URL routes like `/demos/basic.html` ?

**Comment by Wamibit** [comment]
nothing usual beside what i showed with service beef-xss status previously, i can share with journalctl -u beef-xss if you want but pretty much same findings. 

i will investigate symlink, there may be a broken link. Is it normal that  /usr/share/beef-xss/extensions/ is empty?
and contents are in actually in /var/lib/beef-xss/extensions/ ???

i was checking on the node too
┌──(root💀kali)-[~]
└─# node --version
v18.7.0

┌──(root💀kali)-[~]
└─# which node
/usr/bin/node

┌──(root💀kali)-[~]
└─# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

**Comment by bcoles** [comment]
Try cloning from git rahter than using the `beef-xss` service.

**Comment by Wamibit** [comment]
Cloning from the github over the Kali preinstalled beef doesn't work (issue with the .Deb package?) I have proceeded differently. i uninstall Kali beef with 

sudo apt remove beef-xss && sudo apt-get autoremove

remove the beef-xss  .deb if any with dpkg --purge beef-xss

reinstall with apt install beef-xss

when i relaunch from Kali menu, works perfectly now. Still i don't know what was the issue.

**Comment by bcoles** [comment]
> Cloning from the github over the Kali preinstalled beef doesn't work

Correct. I wouldn't recommend it. There's no need to uninstall. You can simply clone and run.

**Comment by jcrew99** [comment]
re-installing beef-xss from the apt repository's is not cloning beef from github and running it.
https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

Closing as it's working for you now.
