### ISSUE TITLE
SSL session is not started yet (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by SnowyYT07** [beefproject/beef#2567]
#<Thread:0x00005616d9d5f660 /home/snowy/beef/extensions/proxy/proxy.rb:53 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/3.0.0/openssl/buffering.rb:80:in `sysread': SSL session is not started yet (OpenSSL::SSL::SSLError)
	from /usr/lib/ruby/3.0.0/openssl/buffering.rb:80:in `fill_rbuff'
	from /usr/lib/ruby/3.0.0/openssl/buffering.rb:332:in `eof?'
	from /usr/lib/ruby/3.0.0/openssl/buffering.rb:285:in `readline'
	from /home/snowy/beef/extensions/proxy/proxy.rb:54:in `handle_request'
#<Thread:0x00005616d9d6ca40 /home/snowy/beef/extensions/proxy/proxy.rb:53 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/3.0.0/openssl/buffering.rb:80:in `sysread': SSL session is not started yet (OpenSSL::SSL::SSLError)
	from /usr/lib/ruby/3.0.0/openssl/buffering.rb:80:in `fill_rbuff'
	from /usr/lib/ruby/3.0.0/openssl/buffering.rb:332:in `eof?'
	from /usr/lib/ruby/3.0.0/openssl/buffering.rb:285:in `readline'
	from /home/snowy/beef/extensions/proxy/proxy.rb:54:in `handle_request'

**Comment by bcoles** [comment]
You opened the proxy in a browser. Open the UI panel URL instead.

**Comment by yourgotocoder** [comment]
> You opened the proxy in a browser. Open the UI panel URL instead.

What is a UI panel URL?
