### ISSUE TITLE
Beef-xss_Ngrok

### ISSUE THREAD

**Issue by Sally96s** [beefproject/beef#2568]
I use Beef-xss_Ngrok , it work well but when i press script "2"  it does not work and write [X] ngrok.yml not found . Can everyone one help me

**Comment by jcrew99** [comment]
Hey @Sally96s,
We need more information.
Please supply the information found in the issue_template.
https://github.com/beefproject/beef/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Sally96s** [comment]
> Hey @Sally96s, We need more information. Please supply the information found in the issue_template. https://github.com/beefproject/beef/blob/master/.github/ISSUE_TEMPLATE.md

Mozilla 5.0
Ruby 3.0.4
Beef 0.5.4.0
Kali linux 2022.1 amd64
But i use beef-over-wan too for wan network
I dont modify confi.yml
I try all solution for beef on wan network but i 
failed when i try login in panel beef  with ngrok.

**Comment by AashishDora** [comment]
Yes I am facing this same issue please someone help me with this...

**Comment by AashishDora** [comment]
> > Hey @Sally96s, We need more information. Please supply the information found in the issue_template. https://github.com/beefproject/beef/blob/master/.github/ISSUE_TEMPLATE.md
> 
> Mozilla 5.0 Ruby 3.0.4 Beef 0.5.4.0 Kali linux 2022.1 amd64 But i use beef-over-wan too for wan network I dont modify confi.yml I try all solution for beef on wan network but i failed when i try login in panel beef with ngrok.



> > Hey @Sally96s, We need more information. Please supply the information found in the issue_template. https://github.com/beefproject/beef/blob/master/.github/ISSUE_TEMPLATE.md
> 
> Mozilla 5.0 Ruby 3.0.4 Beef 0.5.4.0 Kali linux 2022.1 amd64 But i use beef-over-wan too for wan network I dont modify confi.yml I try all solution for beef on wan network but i failed when i try login in panel beef with ngrok.

Hello has this issue been solved if yes please let me know how to I am facing this same issue Ngrok not found when I going to script 2 please it would mean a lot! :)
