### ISSUE TITLE
command not found, mswin

### ISSUE THREAD

**Issue by kamal89990** [beefproject/beef#2569]
beef: line 12: =: command not found
beef: line 17: min_ruby_version: command not found
beef: line 28: syntax error near unexpected token `'mswin''
beef: line 28: `if RUBY_PLATFORM.downcase.include?('mswin') || RUBY_PLATFORM.downcase.include?('mingw')

**Comment by bcoles** [comment]
I have no idea what this is.

BeEF is written in Ruby. However you're executing BeEF is not using a Ruby interpreter.

**Comment by kamal89990** [comment]
ok

**Comment by TheGreenEye** [comment]
Is fixed?

**Comment by kamal89990** [comment]
yes,thanks
