### ISSUE TITLE
install

### ISSUE THREAD

**Issue by kamal89990** [beefproject/beef#2570]
Error :- your rubygems was installed trough apt, and upgrading it through rubygems

**Comment by jcrew99** [comment]
hey @kamal89990, We need more information.
Please supply the information found in the issue_template
https://github.com/beefproject/beef/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by kamal89990** [comment]
.O,                              
                                     lkOl                             
                                     od cOc                           
                                     'X,  cOo.                        
                                      cX,   ,dkc.                     
                                       ;Kd.    ,odo,.                 
                                        .dXl   .  .:xkl'              
                                          'OKc  .;c'  ,oOk:           
                                            ,kKo. .cOkc. .lOk:.       
                                              .dXx.  :KWKo. 'dXd.     
                                                .oXx.  cXWW0c..dXd.   
                                                  oW0   .OWWWNd.'KK.  
                                          ....,;lkNWx     KWWWWX:'XK. 
 ,o:,                          .,:odkO00XNK0Okxdlc,.     .KWWWWWWddWd 
  K::Ol                   .:d0NXK0OkxdoxO'             .lXWWWWWWWWKW0 
  od  d0.              .l0NKOxdooooooox0.        .,cdOXWWWWWWWWWWWWWx 
  :O   ;K;           ;kN0kooooooooooooK:  .':ok0NWWWWWWWWWWWWWWWWWWK. 
  'X    .Kl        ;KNOdooooooooooooooXkkXWWWWWWWWWWWWWWWWWWWWWWWNd.  
  .N. o. .Kl     'OW0doooooooooooooodkXWWWWWWWWWWWWWWWWWWWWWWWW0l.    
   0l oK' .kO:';kNNkoooooooooooook0XWWWWWWWWWWWWWWWWWWWWWWWKx:.       
   lX.,WN:  .:c:xWkoooooooooood0NWW0OWWWWWWWWWWWWWWWWWWWKo.           
    0O.0WWk'   .XKoooooooooooONWWNo  dWWWWWWWWWWWWWWWWWl              
     oKkNWWWX00NWXdooooooooxXWWNk'   dWWWWWWWWWWWWWWWWX               
      .cONWWWWWWWWOoooooooONWWK:...c0WWWWWWWWWWWWWWWWWW:              
         .;oONWWWWxooooodKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX.             
              'XW0oooookNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd             
              oW0ooooo0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO             
             ;NXdooodKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx             
          ;xkOOdooooxOO0KNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX.             
         .NOoddxkkkkxxdoookKWWWWWWWWWWWWWWWWWWWWWWWWWWX'              
          :KNWWWWWWWWWWX0xooONWWWWWWWWWWWWWWWWWWWWWWWk.               
         .xNXxKWWWWWWWOXWWXxoKWWWWWWWWWWWWWWWWWWWWNk'                 
         OWl cNWWWWWWWk oNWNxKWWWWWWWWWWWWWWWWWNOl.                   
        ,Wk  xWWWWWWWWd  xWWNWWWWWWWWWWWWXOdc,.                       
        .N0   lOXNX0x;  .KWWWWWWWWWWWNkc.                             
         :NO,         'lXWWWWWWWWWNk:.                                
          .dXN0OkxkO0NWWWWWWWWWWKl.                                   
             .';o0WWWWWWWWWWWNk;                                      
                  .cxOKXKKOd;.                                        
                                                                      

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
                   -- [ BeEF Installer ] --                      
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

[WARNING]  This script will install BeEF and its required dependencies (including operating system packages).
Are you sure you wish to continue (Y/n)? y
[INFO]  Detecting OS...
[INFO]  Operating System: Linux
[INFO]  Launching Linux install...
[INFO]  Detecting Linux OS distribution...
[INFO]  OS Distribution: Debian
[INFO]  Installing Debian prerequisite packages...
Hit:1 http://in.archive.ubuntu.com/ubuntu jammy InRelease                      
Hit:2 http://in.archive.ubuntu.com/ubuntu jammy-updates InRelease              
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:4 http://in.archive.ubuntu.com/ubuntu jammy-backports InRelease            
Hit:5 https://ngrok-agent.s3.amazonaws.com buster InRelease                    
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
autoconf is already the newest version (2.71-2).
automake is already the newest version (1:1.16.5-1.3).
bison is already the newest version (2:3.8.2+dfsg-1build1).
build-essential is already the newest version (12.9ubuntu3).
libncurses5-dev is already the newest version (6.3-2).
libreadline-dev is already the newest version (8.1.2-1).
libsqlite3-0 is already the newest version (3.37.2-2).
libsqlite3-dev is already the newest version (3.37.2-2).
libtool is already the newest version (2.4.6-15build2).
libyaml-dev is already the newest version (0.2.2-1build2).
sqlite3 is already the newest version (3.37.2-2).
nodejs is already the newest version (12.22.9~dfsg-1ubuntu3).
curl is already the newest version (7.81.0-1ubuntu1.4).
git is already the newest version (1:2.34.1-1ubuntu1.4).
libc6-dev is already the newest version (2.35-0ubuntu3.1).
libcurl4-openssl-dev is already the newest version (7.81.0-1ubuntu1.4).
libssl-dev is already the newest version (3.0.2-0ubuntu1.6).
libxml2-dev is already the newest version (2.9.13+dfsg-1ubuntu0.1).
libxslt1-dev is already the newest version (1.1.34-4ubuntu0.22.04.1).
openssl is already the newest version (3.0.2-0ubuntu1.6).
zlib1g is already the newest version (1:1.2.11.dfsg-2ubuntu9.1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu9.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[INFO]  No Ruby package manager detected - will install Ruby
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ruby-dev is already the newest version (1:3.0~exp1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 3.0.2 is installed
[INFO]  Updating rubygems...
ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.
root@kamal-Lenovo-G50-80:/home/kamal/beef#

**Comment by bcoles** [comment]
```
cd /path/to/beef
gem install bundler
bundle install
```

**Comment by kamal89990** [comment]
while running bundle  install i am getting 2 error
1)
Bundler::GemNotFound: Could not find xmlrpc-0.3.2.gem for installation

2)
An error occurred while installing xmlrpc (0.3.2), and Bundler cannot
continue.

In Gemfile:
  xmlrpc
root@kamal-Lenovo-G50-80:/home/kamal/beef# exit
exit

note :- i had run it with and without sudo 

full code :-
kamal@kamal-Lenovo-G50-80:~/beef$ sudo bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using i18n 1.12.0
Using minitest 5.16.2
Using tzinfo 2.0.5
Using activesupport 7.0.3.1
Using activemodel 7.0.3.1
Using activerecord 7.0.3.1
Using public_suffix 4.0.7
Using addressable 2.8.0
Using ansi 1.5.0
Using ast 2.4.2
Using fiber-local 1.0.0
Using console 1.15.3
Using nio4r 2.5.8
Using timers 4.3.3
Using async 1.30.3
Using async-io 1.33.0
Using async-dns 1.3.0
Using buftok 0.2.0
Using bundler 2.3.14
Using daemons 1.4.1
Using digest 3.1.0
Using unf_ext 0.0.8.2
Using unf 0.1.4
Using domain_name 0.5.20190701
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.3
Using equalizer 0.0.11
Using erubis 2.7.0
Using espeak-ruby 1.0.5
Using execjs 2.8.1
Using ffi 1.15.5
Using ffi-compiler 1.0.1
Using hashie 5.0.0
Using hashie-forbidden_attributes 0.1.1
Using http-cookie 1.0.5
Using http-form_data 2.3.0
Using http-parser 1.2.3
Using http 4.4.1
Using http-accept 1.7.0
Using json 2.6.2
Using maxmind-db 1.1.1
Using thread_safe 0.3.6
Using memoizable 0.4.2
Using mime-types-data 3.2022.0105
Using mime-types 3.4.1
Using mojo_magick 0.6.7
Using msgpack 1.5.4
Using msfrpc-client 1.1.2
Using multipart-post 2.2.3
Using ruby2_keywords 0.0.5
Using mustermann 2.0.2
Using naught 1.1.0
Using timeout 0.3.0
Using net-protocol 0.1.3
Using net-smtp 0.3.1
Using netrc 0.11.0
Using otr-activerecord 2.1.1
Using parallel 1.22.1
Using parseconfig 1.1.2
Using parser 3.1.2.1
Using rqrcode_core 0.2.0
Using qr4r 0.6.1
Using rack 2.2.4
Using rack-protection 2.2.2
Using rainbow 3.1.1
Using regexp_parser 2.5.0
Using rest-client 2.1.0
Using rexml 3.2.5
Using rubocop-ast 1.21.0
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.2.0
Using rubocop 1.36.0
Using rubyzip 2.3.2
Using rushover 0.3.0
Using simple_oauth 0.3.1
Using tilt 2.0.11
Using sinatra 2.2.2
Using slack-notifier 2.4.0
Using sqlite3 1.5.0 (x86_64-linux)
Using sync 0.5.0
Using tins 1.31.1
Using term-ansicolor 1.7.1
Using thin 1.8.1
Using twitter 7.0.0
Using uglifier 4.2.0
Using webrick 1.7.0
Installing xmlrpc 0.3.2
Bundler::GemNotFound: Could not find xmlrpc-0.3.2.gem for installation
 
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:171:in
`install_serially'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:97:in
`call'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:71:in
`call'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer.rb:259:in
`install_in_parallel'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer.rb:209:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer.rb:89:in `block
in run'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/process_lock.rb:12:in
`block in lock'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/process_lock.rb:9:in
`open'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/process_lock.rb:9:in
`lock'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer.rb:71:in `run'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer.rb:23:in
`install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/cli/install.rb:62:in `run'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/cli.rb:255:in `block in
install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/settings.rb:131:in
`temporary'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/cli.rb:254:in `install'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in
`run'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in
`invoke_command'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor.rb:392:in
`dispatch'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/cli.rb:31:in `dispatch'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in
`start'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/cli.rb:25:in `start'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/exe/bundle:48:in `block in <top
(required)>'
/var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/friendly_errors.rb:103:in
`with_friendly_errors'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/exe/bundle:36:in `<top (required)>'
  /usr/local/bin/bundle:25:in `load'
  /usr/local/bin/bundle:25:in `<main>'

An error occurred while installing xmlrpc (0.3.2), and Bundler cannot
continue.

In Gemfile:
  xmlrpc

**Comment by bcoles** [comment]
```
gem install xmlrpc
```

**Comment by kamal89990** [comment]
thanks you so much,it was a grate help, have a nice day

**Comment by jcrew99** [comment]
Nice, closing as completed

**Comment by FlSHSTICK** [comment]
I got the same error, and when trying the fix ### gem install xmlrpc ###  I got the error: You don't have write permissions for the /var/lib/gems/3.0.0 directory.
