### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by aditya324jhj** [beefproject/beef#2572]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. BeEF Version:Latest Updated
4. Ruby Version:3.0.4p208:
5. Browser Details (e.g. Chrome v81.0):Chrome version 104
6. Operating System (e.g. OSX Catalina):Kali linux on wsl2 in windows 11

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No
Yes
3. Have you enabled or disabled any BeEF extensions? Yes/No No

## Steps to Reproduce

1. (eg. I ran install script, which ran fine)
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
4. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
5. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by aditya324jhj** [comment]
Mainly the issue is that it works on mine computer but does not work on mobile or any other device.

**Comment by bcoles** [comment]
Correct. You will need to port forward from your border router or tunnel using something like ngrok:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by aditya324jhj** [comment]
Any tutorial on that please?

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by aditya324jhj** [comment]
I have already seen this.I had trouble understanding this.Can you please suggest a video tutorial.
Thank you.

**Comment by aditya324jhj** [comment]
Thank you. It worked.

**Comment by aditya324jhj** [comment]
Btw I have an easy way to run beef on windows.I could not find how to run beef on windows without vm.But there is a way to run it without vm all in windows.If you want I can tell you the way as it would help the community to expand but I could not write a documentation on it as I am a student. 
Thanks.
With regards
~Aditya

**Comment by bcoles** [comment]
> I have an easy way to run beef on windows.
> I could not find how to run beef on windows without vm

Windows is not a supported platform for BeEF. You could try WSL but this has not been tested thoroughly.

**Comment by aditya324jhj** [comment]
I am currently running my beef on wsl and it is working perfectly.If you want I can provide you some screenshots.

**Comment by aditya324jhj** [comment]
If you could please write this documention in GitHub as many people use windows and also want to use beef without vm.

**Comment by aditya324jhj** [comment]
@bcoles If you do this it would be a great help to the community

**Comment by bcoles** [comment]
> @bcoles If you do this it would be a great help to the community

BeEF should work on WSL although it has not been thoroughly tested. WSL is effectively a GNU Linux environment. The installation and usage should be the same as any other GNU Linux system.

**Comment by aditya324jhj** [comment]
I agree with you @bcoles but I am ready to provide you proof that it works perfectly.
Moreover I have more than 1+ years of experience in scam baiting and 4+ years of experience in python(all in windows).Even if there is a problem from the community I will help to resolve it.I am using beef because I think it is a better way to scam bait.

**Comment by aditya324jhj** [comment]
I agree with you @bcoles but I am ready to provide you proof that it works perfectly.
Moreover I have more than 1+ years of experience in scam baiting and 4+ years of experience in python(all in windows).Even if there is a problem from the community I will help to resolve it.I am using beef because I think it is a better way of scam baiting.I am telling you all this because most of their scam baiters I know personally are using windows and beef can be great way for scam baiting.

**Comment by aditya324jhj** [comment]
Even if it does not work properly some people could use it for testing purposes in windows

**Comment by bcoles** [comment]
> I agree with you @bcoles but I am ready to provide you proof that it works perfectly. Moreover I have more than 1+ years of experience in scam baiting and 4+ years of experience in python(all in windows).Even if there is a problem from the community I will help to resolve it.I am using beef because I think it is a better way to scam bait.

I'm not sure what you're suggesting.

> Even if it does not work properly some people could use it for testing purposes in windows

WSL on Windows is not Windows. It is Linux. It is a full Linux kernel and associated GNU userland utilities.

BeEF should work on WSL although it has not been thoroughly tested. WSL is effectively a GNU Linux environment. The installation and usage should be the same as any other GNU Linux system.

BeEF is open source and contributions are welcome. If there was something you want to change you can submit a pull request. If you want to discuss changes you can join the Discord server. An invite link is in the README.

Windows is not a supported platform for BeEF. There is no interest from existing developers in maintaining support for Windows.

**Comment by aditya324jhj** [comment]
Ok no prob
