### ISSUE TITLE
Can't access the UI panel or hook Amazon AWS free tier?

### ISSUE THREAD

**Issue by mallson1** [beefproject/beef#2576]
I am using Amazon's AWS free tier Ubuntu 22.04.1 LTS I'm sure it's a port issue but I am unsure what ports to open through the AWS networking tab any help would be highly appreciated. also what IP should I plug into the config.yaml should it be the address of my host machine or the AWS machine when I use iwconfig?

**Comment by bcoles** [comment]
> I am using Amazon's AWS free tier Ubuntu 22.04.1 LTS I'm sure it's a port issue but I am unsure what ports to open through the AWS networking tab any help would be highly appreciated.

The BeEF server used for XHR command and control runs on port 3000 - the same port as the admin UI.

https://github.com/beefproject/beef/blob/ed4c9169b369e1d630a44d16967a9a8b60dce750/config.yaml#L39

BeEF can also use websockets for command and control (but I don't think this works with `public` forwarding as per below).

https://github.com/beefproject/beef/blob/ed4c9169b369e1d630a44d16967a9a8b60dce750/config.yaml#L83

> also what IP should I plug into the config.yaml should it be the address of my host machine or the AWS machine when I use iwconfig?

Whichever IP is publicly accessible. You'll need to adjust the `beef.http.public*` properties. The same steps as outlined here:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
