### ISSUE TITLE
Hooked Browser Goes Offline

### ISSUE THREAD

**Issue by miocak** [beefproject/beef#2587]
1. BeEF Version: latest
2. Ruby Version: latest
3. Browser Details: latest of both brave and mozilla firefox
4. Operating System: kali linux latest

## Configuration

1. Have you made any changes to your BeEF configuration? Yes
2. Have you enabled or disabled any BeEF extensions? No

##

I edited the config file and did what needed to be done (changing url bc of the local ip of virtual machine) and it all worked out pretty well, I was able to take a screenshot or got html address etc. but all these applies if the victim browser is on the hooked url, otherwise, the hooked browser goes offline and not just when the tab closed but also when the tabs switched on hooked browser. is there anything i can do to fix this BIG ISSUE??

**Comment by bcoles** [comment]
Try the [persistence](https://github.com/beefproject/beef/tree/master/modules/persistence) modules.
