### ISSUE TITLE
BEEF USE 

### ISSUE THREAD

**Issue by JASIM0021** [beefproject/beef#2597]
HOW CAN I USE BEEF USING TERMUX WITH ANDROID :- I AM FASING ISSU WEN ITS INSTALING DEPENDENCES **SHOWING NO ROOT BINARY FOUND**

**Comment by jcrew99** [comment]
#2596 and this are similar.
Termux is not officially supported by BeEF.
I suggest that you have a look at #1680 and #2128 but the comments below should be helpful.

https://github.com/beefproject/beef/issues/1680#issuecomment-464422903
https://github.com/beefproject/beef/issues/2494#issuecomment-1179732737
