### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Denisbg2011game** [beefproject/beef#2601]
**^**

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/issues/2102#issuecomment-878787879

**Comment by Denisbg2011game** [comment]
> [#2102 (comment)](https://github.com/beefproject/beef/issues/2102#issuecomment-878787879)

I did have evasion enabled although I didn't configure it, I disabled it now and it loads fast as before hmmm

**Comment by Denisbg2011game** [comment]
> This issue as been marked as stale due to inactivity and will be closed in 7 days

no pls help why it not work with evasion enabled

**Comment by Denisbg2011game** [comment]
have removed beef from main page and also fixed the bug
