### ISSUE TITLE
Beef posix bindshell linux command timeouts for 30 seconds each time

### ISSUE THREAD

**Issue by Kali95739** [beefproject/beef#2604]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version:newest
5. Ruby Version:newest
6. Browser Details (e.g. Chrome v81.0):firefox and chrome testing
7. Operating System (e.g. OSX Catalina):debian based kali GNU rolling and testing with windows

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No
2. no
3. Have you enabled or disabled any BeEF extensions? Yes/No
4. no
5. 
Beef bind shell for posix does not run a command I try and it times out for 30 seconds where as windows says shell sent is there a reason for this?

**Comment by bcoles** [comment]
No real reason. One module prints when the commands are sent where as the other does not.

* https://github.com/beefproject/beef/blob/master/modules/ipec/inter_protocol_posix_bindshell/command.js
* https://github.com/beefproject/beef/blob/master/modules/ipec/inter_protocol_win_bindshell/command.js

**Comment by Kali95739** [comment]
I believe it maybe because I had it as a grey module at the time that being
it couldnt identify my browser of firefox with linux do you believe that to
be why?

**Comment by bcoles** [comment]
No. The POSIX module attempts to read and return the results of the executed commands.

**Comment by Kali95739** [comment]
To use this module properly does it require any other module to be ran before it can be executed or can we run this module right away

**Comment by Kali95739** [comment]
@bcoles

**Comment by bcoles** [comment]
> To use this module properly does it require any other module or extensions to be ran before it can be executed or can we run this module right away

You can run this module at your convenience. This module communicates with bind shells. You will need to specify the correct host and port for the bind shell you want to connect to.

**Comment by Kali95739** [comment]
Hello thank you for the fast response times I had tried to run a mshta command and it is on my local external network that being 10.0.0.1 etc it says shell ran but when I tested it had not actually ran the command as if It was coming from the command line for windows is that because its local?

**Comment by Kali95739** [comment]
Chrome browser

**Comment by Kali95739** [comment]
Or can this not run a mshta command? For windows

**Comment by Kali95739** [comment]
Or can this not run a mshta command? For windows

**Comment by Kali95739** [comment]
Or you mean we have to open a bind shell on them before we can use this officially?

**Comment by Kali95739** [comment]
Or the module does that itself

**Comment by Kali95739** [comment]
@bcoles

**Comment by Kali95739** [comment]
I had tried to open a bindshell on port 4444 through nodejs and tried with firefox on my linux posix module still wont send a shell command is it because I am doing it locally you believe?
