### ISSUE TITLE
Beef xss over wan not working ( While running the main.py its saying ngrok not found ) 

### ISSUE THREAD

**Issue by AashishDora** [beefproject/beef#2605]

**Comment by AashishDora** [comment]
Please help me this situaition it would help me a lot

**Comment by AashishDora** [comment]
pls ask for info if needed

**Comment by bcoles** [comment]
This is the BeEF issue tracker. BeEF over WAN is a separate unofficial tool.

`ngrok not found` implies that the tool could not find ngrok.

**Comment by bcoles** [comment]
The phrase "ngrok not found" does not exist anywhere in this script:

* https://github.com/stormshadow07/BeeF-Over-Wan/blob/master/BeeFOverWan.py

You will need to review which ever script you're using to see how it locates ngrok. If it presumes that `ngrok` is in your system path then you will need to add the path to ngrok to your system path.

Or you could configured BeEF with ngrok manually:

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by AashishDora** [comment]
Hi thank you for the reply..I think I know why i am facing this issue...Can you please tell where i can find ngrok.yaml file?
i have done some research it says that we need that

**Comment by AashishDora** [comment]
Sorry I closed that by mistake I think I know why i am facing this issue...Can you please tell where i can find ngrok.yaml file?
i have done some research it says that we need that file to to the BEEF XSS OVER WAN

**Comment by AashishDora** [comment]
Or i am not able to install Ngrok correctly it self I have seen many vids but none helped . I think that ngrok.yml file should be placed in a correcct location but I am not able to find that file please help me with this if you think its the problem with the installation please guide me through this..

**Comment by bcoles** [comment]
This is the BeEF issue tracker. BeEF over WAN is a separate unofficial tool.

ngrok is a different tool unrelated to BeEF. Refer to the ngrok documentation.
