### ISSUE TITLE
Issue with running event machine and BeeF

### ISSUE THREAD

**Issue by tortre** [beefproject/beef#2606]
When I installed all the dependencies and I ran ./beef I ran into the error
`Could not find gem 'eventmachine' in locally installed gems. Run `bundle install` to install missing gems.`
So when I tried installing it using bundle install I got this.
1 error generated.
make:  [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/handafeleke/.rvm/gems/ruby-3.0.3@beef/gems/eventmachine-1.2.7 for inspection.
Results logged to /Users/handafeleke/.rvm/gems/ruby-3.0.3@beef/extensions/arm64-darwin-21/3.0.0/eventmachine-1.2.7/gem_make.out

  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:102:in `run'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:43:in `each'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:43:in `make'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:171:in `build_extension'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:205:in `block in build_extensions'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:202:in `each'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:202:in `build_extensions'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:843:in `build_extensions'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/source/rubygems.rb:207:in `install'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/handafeleke/.rvm/rubies/ruby-3.0.3/lib/ruby/site_ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing eventmachine (1.2.7), and Bundler cannot continue.

In Gemfile:
  em-websocket was resolved to 0.5.3, which depends on
    eventmachine
And I looked everywhere and I tried installing event machine in many different ways but it just does not want to work with me

**Comment by jcrew99** [comment]
Try 
```
gem install eventmachine
bundle install
```
