### ISSUE TITLE
Can't Bind beef with my public IP

### ISSUE THREAD

**Issue by SlepPoweredBy2** [beefproject/beef#2619]
Can't bind beef with my Public IP

I did edit the host in the config.yaml and still nothing.

(The error says it can't listen because either there is another program listening on 3000 (no there isnt) or just ip is wrong)

There is no http.public.port or IP or whatever JSYK

**Comment by bcoles** [comment]
You can only bind to a network interface.

**Comment by SlepPoweredBy2** [comment]
How tf do i that?

**Comment by bcoles** [comment]
> How tf do i that?

The default `host` is `0.0.0.0`. This will bind to all network interfaces by default.

If your host is a NAT'd environment, refer to:

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

**Comment by SlepPoweredBy2** [comment]
How am I supposed to add my public IP to interfaces, then use beef with it.

I don't need to add public IP to interfaces using Apache2 or L3MON, or anything else..

**Comment by bcoles** [comment]
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

**Comment by SomeoneThatEx1sts** [comment]
There is no beef.http.public and no beef.http.port in config.yaml

**Comment by bcoles** [comment]
> There is no beef.http.public and no beef.http.port in config.yaml

Refer to the default config.yaml file for an example:

* https://github.com/beefproject/beef/blob/master/config.yaml

**Comment by SomeoneThatEx1sts** [comment]
Well there is no beef.http.public there...

And you need to do that for public ip

**Comment by bcoles** [comment]
> Well there is no beef.http.public there...

Yes there is. It is commented out:

https://github.com/beefproject/beef/blob/56945df5b89961fc0105e3b100b977d12f8b56a7/config.yaml#L48-L57

**Comment by SomeoneThatEx1sts** [comment]
Where
