### ISSUE TITLE
Fatal Error: cannot load configuration file '/home/kali/beef/./config.yaml' : (<unknown>): did not find expected key while parsing a block mapping at line 37 column 9

### ISSUE THREAD

**Issue by SlepPoweredBy2** [beefproject/beef#2625]
when i set this in config.yaml
![image](https://user-images.githubusercontent.com/113756956/200913190-3e132d4e-24ee-421b-b2cd-50bf1d375ae6.png)

Then this error comes up
![image](https://user-images.githubusercontent.com/113756956/200913270-7f0176cb-b90c-40b0-9afb-ee1f73eae7bd.png)

Tagging them out resolves that error, but it still means I can't use beef outside of LAN

**Comment by bcoles** [comment]
The config file is in YAML format. Whitespace is important. The keys must be vertically aligned.

**Comment by SlepPoweredBy2** [comment]
nvm it works love you :)

**Comment by SlepPoweredBy2** [comment]
![image](https://user-images.githubusercontent.com/113756956/201156087-3a53588f-f5e4-4288-9d4c-2c13ef3efe94.png)

**Comment by bcoles** [comment]
Something is already listening on port 3000 or you have specified an invalid network interface in the configuration file.

**Comment by SlepPoweredBy2** [comment]
wtf do u mean network interface bro i only have 192.168.68.101 and 127.0.0.1

**Comment by SlepPoweredBy2** [comment]
Problem: Got it to work, but it acts as a localhost and it wont let me hook my phone/ connect my phone to my UI

Yes, I have forwarded port 3000.

**Comment by bcoles** [comment]
There is not enough information to reproduce this issue.

**Comment by SlepPoweredBy2** [comment]
It says its on 79.181.103.184:3000 but when I log into that IP with the port (and /ui/authentication in the link) it doesn't work... 

How tof ix it

**Comment by bcoles** [comment]
> It says its on 79.181.103.184:3000 but when I log into that IP with the port (and /ui/authentication in the link) it doesn't work...

This is a known issue. #2527

Try logging in via a local IP address.

Alternatively, as a workaround, you could try setting `beef.http.allow_reverse_proxy: true`.

**Comment by SlepPoweredBy2** [comment]
Me using beef on public (with my public ip) with beef.http.allow.reverse.proxy thingy and same result.

And I did try using my normal IP (192.168.68.101) But then I can't hook people/ connect to beef remotely if i wanted...

**Comment by bcoles** [comment]
There is not enough information to reproduce this issue. Where did you get stuck during troubleshooting?

Ensure your network configuration is operating as intended.

**Comment by G4k3r** [comment]
its sad how we cant get the help we need.

**Comment by bcoles** [comment]
> its sad how we cant get the help we need.

What is your question?

**Comment by G4k3r** [comment]
ok glad to see  an update and you're active  I want to know why the #public section is not able to be uncommented

**Comment by bcoles** [comment]
> ok glad to see an update and you're active I want to know why the #public section is not able to be uncommented

The `public` section can be uncommented.
