### ISSUE TITLE
BeEF Error

### ISSUE THREAD

**Issue by KajshusCZ** [beefproject/beef#2633]
BeEF Version: 0.5.4.0
Ruby Version: 2.7.4p191
- when installing BeEF this error comes up - 
![obrazek](https://user-images.githubusercontent.com/118672662/202908605-d959f192-a9f8-4699-905e-df7537664195.png)
could you please help? Thanks.

**Comment by bcoles** [comment]
`gem install xmlrpc`

**Comment by KajshusCZ** [comment]
![obrazek](https://user-images.githubusercontent.com/118672662/203122335-dc522737-159f-4c9b-a149-6a3ec2e84bf0.png)
:( Dint work for me

**Comment by TheGreenEye** [comment]
sudo gem install xmlrpc

**Comment by TheGreenEye** [comment]
sudo gem install msgpack
