### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by TheGreenEye** [beefproject/beef#2637]
beef: line 12: =: command not found
beef: line 17: min_ruby_version: command not found
beef: line 28: syntax error near unexpected token `'mswin''
beef: line 28: `if RUBY_PLATFORM.downcase.include?('mswin') || RUBY_PLATFORM.downcase.include?('mingw')'
??
Pls help  me

**Comment by bcoles** [comment]
Windows is not supported.

**Comment by TheGreenEye** [comment]
I have Kali Linux

**Comment by TheGreenEye** [comment]
Is fixed
