### ISSUE TITLE
An error occurred while installing xmlrpc (0.3.2), and Bundler cannot continue.

### ISSUE THREAD

**Issue by prodigy233** [beefproject/beef#2638]
I am getting this error while trying to install beef. Ive looked at other issues and none of them have seemed to solve my problem. Any help would be much appreciated thanks!!!

**Comment by bcoles** [comment]
```
gem install xmlrpc
```

**Comment by prodigy233** [comment]
i just tried sudo gem install xmlrpc and sudo gem install msgpack. I am now getting this error.

An error occurred while installing domain_name (0.5.20190701), and
Bundler cannot continue.

**Comment by bcoles** [comment]
```
gem install domain_name
```

**Comment by rehman671** [comment]
I am getting this error while running command 
`gem install xmlrpc`

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/3.0.0 directory.

**Comment by bcoles** [comment]
> You don't have write permissions for the /var/lib/gems/3.0.0 directory.

```
sudo gem install xmlrpc
```

**Comment by valt8** [comment]
> > You don't have write permissions for the /var/lib/gems/3.0.0 directory.
> 
> ```
> sudo gem install xmlrpc
> ```
![Screenshot_2023-03-28_23_36_50](https://user-images.githubusercontent.com/59946614/228420388-aa5653e0-3180-4dfa-a890-30ca8ff9980f.png)

it still says the same thing.

**Comment by bcoles** [comment]
> it still says the same thing.

use `sudo`

**Comment by rehman671** [comment]
Use Sudo gem install domain_name

**Comment by reehaz077** [comment]
brooo i just solve this problem at one short 🤯🤯

**Comment by hackerishan03** [comment]
it doesnt' work man

**Comment by bcoles** [comment]
> it doesnt' work man

nothing anyone can do to help if you provide no information

**Comment by Lex-Case** [comment]
Hello everyone! 
Something similar happened to me and I'm going to explain how I solved it in case it helps someone. 
When the error appears, don't just look at the message at the end (`In Gemfile: xmlrcp`), look above where there is a line that begins: 
`Bundler::GemNotFound: Could not find <here>`
Install manually with the `gem install` command and the gem name (without version). 
Once installed run ./install again, repeat the process as many times as necessary, it should change the gem you need each time. Luck!
