### ISSUE TITLE
NGROK NOT REDIRECT

### ISSUE THREAD

**Issue by Cozmo007** [beefproject/beef#2646]
Hello.

I wanted to know why my beef-xss does not redirect to the panel page, I configured it for the external network with ngrok, but it is not logging in, the logins are correct.

![Captura de tela de 2022-12-05 14-41-10](https://user-images.githubusercontent.com/90281965/205705600-e192fd45-d08a-41f9-b2eb-f72c4e0b28c6.png)

**Comment by bcoles** [comment]
Dupe of #2527.

Login via `http://127.0.0.1:3000/ui/panel`
