### ISSUE TITLE
Beef xss over wan 

### ISSUE THREAD

**Issue by ChillVibesMushroom** [beefproject/beef#2660]
I was wondering how do I edit the hook file to work over wan kind of like port forwarding with a tunneling service but also the hook listens on 0.0.0.0

**Comment by bcoles** [comment]
* https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
