### ISSUE TITLE
Can not hook any browser except me

### ISSUE THREAD

**Issue by IMNOOBKING** [beefproject/beef#2665]
![image](https://user-images.githubusercontent.com/107189808/209108302-ff1e087d-023a-44ee-baee-64071a7a3d1e.png)
When i open hook link on my phone it doesn't hook and i trreid putting script in my website imnoobking.github.io but it still dos not hook browser. And how can i hook any browser that is not near me like anywhere else in the worland the only browser i can hook is my own browser.

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by ChillVibesMushroom** [comment]
That’s because you’re not using the right method  I’ve hooked plenty of browsers

**Comment by ChillVibesMushroom** [comment]
I do not know this man leave me be

**Comment by Warhammar** [comment]
Having the same issue but im using VM ware.. 
Maybe a direct installation would help. Cant figure it out..

**Comment by bcoles** [comment]
> Having the same issue but im using VM ware.. Maybe a direct installation would help. Cant figure it out..

There is not enough information to reproduce this issue.

Hooked browsers must be able to communicate with the BeEF server. This requires forwarding or tunneling network traffic from the public Internet to the BeEF server. Refer to:

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
