### ISSUE TITLE
is there any way to put/inject scripts into a targets website without a mitm attack?

### ISSUE THREAD

**Issue by ireallydontknowlmao** [beefproject/beef#2667]
alr so ive been looking around and cant find a way to inject or add scripts to a targets website and what  i mean is i want to add the beef hook to someones website when they visit it and i dont mean a website made by you i mean if they visit the website the hook gets injected and the main issue is most videos n stuff i found that could actually do this required a mitm attack that i need to be in their network for so rn what im asking for is a way to add the beef hook to any website the target visits

uh if this is too long or something just tell me and ill say what i need but in shorter terms.

**Comment by bcoles** [comment]
https://owasp.org/www-community/attacks/xss/
https://portswigger.net/web-security/cross-site-scripting
https://en.wikipedia.org/wiki/Cross-site_scripting

**Comment by ireallydontknowlmao** [comment]
> https://owasp.org/www-community/attacks/xss/ https://portswigger.net/web-security/cross-site-scripting https://en.wikipedia.org/wiki/Cross-site_scripting

so

**Comment by bcoles** [comment]
> > https://owasp.org/www-community/attacks/xss/ https://portswigger.net/web-security/cross-site-scripting https://en.wikipedia.org/wiki/Cross-site_scripting
> 
> so i read these(probally missed a few things idk) and they didnt really help with my issue, the issue im having rn is i dont have a way to put the script into the html of the website(i bet the articles explained but i missed it or smth)

It is explained. It is the fundamental premise of the attack described in those links.

> but what would really help me is if you gave me the name of an attack that can do this thats more specific then just "xss" like maybe a type of xss or something

Cross-Site Scripting (XSS)

> or linux software that could help me and if its xss i cant use a thing like chat boards bc if im trying to cookie log someone with beef most websites are protected by xss like that so again what i need is the name of a specific "xss" type etc

Cross-Site Scripting (XSS)
