### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by PoworMan** [beefproject/beef#2668]
wget http://127.0.0.1:3000/hook.js

Connecting to 127.0.0.1:3000... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2022-12-26 02:26:26 ERROR 500: Internal Server Error.

**Comment by PoworMan** [comment]
docker image :kalilinux/kali-rolling

**Comment by bcoles** [comment]
The logs should indicate why this is occurring. If running BeEF using the `beef-xss` package as the `beef-xss` user:

```
journalctl -u beef-xss
```
