### ISSUE TITLE
Hook was omitted because of a cross site redirect 

### ISSUE THREAD

**Issue by ChillVibesMushroom** [beefproject/beef#2672]
Everything is working perfectly fine I just need to get past the hook being omitted because of a cross site redirect

What’s the issue here

**Comment by ChillVibesMushroom** [comment]
![EE5C41D9-A848-418C-9B55-5F0FB62AF95A](https://user-images.githubusercontent.com/99580833/209900881-43ba8254-aa49-41f9-9ed0-43d89b2c94e9.jpeg)

**Comment by ChillVibesMushroom** [comment]
Any news I’m willing to pay cash

**Comment by bcoles** [comment]
I don't understand the question. Why does the hook not execute?
