### ISSUE TITLE
GEM ISUS

### ISSUE THREAD

**Issue by NotNukerOffical** [beefproject/beef#2676]
Installing timers 4.3.5
Fetching async 1.30.3
Installing async 1.30.3
Fetching async-io 1.34.1
Installing async-io 1.34.1
Fetching async-dns 1.3.0
Installing async-dns 1.3.0
Bundler::GemNotFound: Could not find unf-0.1.4.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/source/rubygems.rb:159:in `install'                                                                              
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing unf (0.1.4), and Bundler cannot continue.

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    http was resolved to 4.4.1, which depends on
      http-cookie was resolved to 1.0.5, which depends on
        domain_name was resolved to 0.5.20190701, which depends on
          unf

Bundler::GemNotFound: Could not find xmlrpc-0.3.2.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/source/rubygems.rb:159:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.19/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing xmlrpc (0.3.2), and Bundler cannot continue.

In Gemfile:
  xmlrpc

**Comment by bcoles** [comment]
```
gem install xmlrpc
```
