### ISSUE TITLE
Hook browser 

### ISSUE THREAD

**Issue by IMNOOBKING** [beefproject/beef#2678]
How do i hook a browser that is not in my router/someone who is 1km away from meg. Please provide a step by step guide.

**Comment by bcoles** [comment]
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
