### ISSUE TITLE
Install error(xmlrpc) os=ubuntu

### ISSUE THREAD

**Issue by kamal89990** [beefproject/beef#2682]
Bundler::GemNotFound: Could not find xmlrpc-0.3.2.gem for installation
 
/var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/source/rubygems.rb:159:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/installer/parallel_installer.rb:155:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/installer/parallel_installer.rb:146:in
`block in worker_pool'
/var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/worker.rb:62:in
`apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/worker.rb:54:in `loop'
/var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/worker.rb:54:in
`process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.4.0/lib/bundler/worker.rb:90:in `block (2
levels) in create_threads'

An error occurred while installing xmlrpc (0.3.2), and Bundler cannot
continue.

In Gemfile:
  xmlrpc

**Comment by bcoles** [comment]
```
gem install xmlrpc
```

**Comment by AvinFajarF** [comment]
> ```
> gem install xmlrpc
> ```

thanks bro
