### ISSUE TITLE
fatal Error: cannot load configuration file '/home/kali/Desktop/beef/./config.yaml' : (<unknown>): did not find expected key while parsing a block mapping at line 37 column 9 

### ISSUE THREAD

**Issue by biraj33** [beefproject/beef#2692]
I have trying swapping the port and host still it is not working how can i fix it please help
![Screenshot_2023-01-18_23_42_31](https://user-images.githubusercontent.com/53502629/213258611-ae434983-a350-4fef-a45c-ac8643048471.png)
![Screenshot_2023-01-18_23_42_55](https://user-images.githubusercontent.com/53502629/213258619-61aa04a0-970a-4c8b-8bab-b38f6d72ec47.png)

**Comment by moh0009** [comment]
i have the same issue 
![image](https://user-images.githubusercontent.com/83363934/213262344-39b37531-ceb9-4cb7-a2c2-d3d0a537e2a2.png)
![image](https://user-images.githubusercontent.com/83363934/213262437-8b236062-6def-4d21-bcd3-293e6d98b042.png)

**Comment by bcoles** [comment]
White space alignment is important. The `public` key is not correctly aligned.
