### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by iIDragonterrorIi** [beefproject/beef#2695]
How would i run this on repl.it?
https://replit.com/@Dragonterror/BeEF-1?v=1<-- I got this to work almost and when i turn on https it starts a bootup loop. But if I turn OFF https and turn ON reverse proxy it works. Any way to get it to work with https?

**Comment by jcrew99** [comment]
Can you provide the output of the terminal and any changes done to default configuration?

**Comment by bcoles** [comment]
Refer to #2717.
