### ISSUE TITLE
Cloud Console

### ISSUE THREAD

**Issue by xen-cyber** [beefproject/beef#2696]
I'm trying to install beef on google cloud console. I've followed docker installation steps and ran the container everything is fine until i try to open the panel. This image shown below is what the page returns.
![image](https://user-images.githubusercontent.com/77687289/213941120-bfbf3d53-be6f-46bc-b84d-86d2909af7e0.png)

I have followed the steps carefully and did not miss anything. I even tried the normal installation and it returns the same output when trying to access the panel. 

Here is beef running on port 3000 
![image](https://user-images.githubusercontent.com/77687289/213941213-fa5ce4fb-4003-484b-b466-b23f151beae5.png)

I've tried to switch ports i've also made sure port 3000 is not being used by another process.

**Comment by jcrew99** [comment]
Can you browse to to the ui endpoing?
``/ui/panel``

**Comment by IronHacker75** [comment]
I also have this probleme. doess anyone know how to solve it?

**Comment by bcoles** [comment]
> I also have this probleme. doess anyone know how to solve it?

https://github.com/beefproject/beef/issues/2696#issuecomment-1400211229
