### ISSUE TITLE
BEEF and Wordpress

### ISSUE THREAD

**Issue by gitKingBien** [beefproject/beef#2703]
Hi! I am using wordpress and beef and beef only works on http. Our requirements is to send a wordpress website in https and hook the browser. However I tried several times and beef can only hook browsers if I use http. 

How can I fix this? Thank you!

**Comment by bcoles** [comment]
Modern browsers do not load mixed active content by default. You will need to host BeEF using HTTPS or behind a reverse-proxy which uses HTTPS. Note that the HTTPS service must present a valid trusted certificate.

**Comment by bcoles** [comment]
In instances where BeEF is behind a reverse proxy you will need to inform BeEF what the publicly accessible URL is. Refer to:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
