### ISSUE TITLE
BeEF not hooking browsers

### ISSUE THREAD

**Issue by azazazaz15** [beefproject/beef#2710]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: idk. I used sudo install beef-xss
5. Ruby Version: 3.1.0
6. Browser Details (e.g. Chrome v81.0): firefox
7. Operating System (e.g. OSX Catalina): Windows (I'm running BeEF and Kali linux on a remote desktop)

## Configuration

1. Have you made any changes to your BeEF configuration? No
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

1. I setup BeEF
2. I ran it and visited the control panel of BeEF in my browser
3. I opened the Hook link on another computer which didnt work so I tried on my own computer which also didn't work
## Additional info
I installed BeEF and ran it but it gave me some errors so I ran it on root terminal using ./beef and it worked however, I cant hook browsers. I tried on my other browser on windows, also tried a VPN, nothing works. I also followed the steps I found on a website but that didnt work either.

**Comment by bcoles** [comment]
There is not enough information to answer your question.

Do you get any errors in terminal?

Do you get any errors in the browser console?

**Comment by azazazaz15** [comment]
didn't see any errors in the browser console however I did get some messages saying I have to install some extra stuff.

[20:10:52][!] [GeoIP] Could not find MaxMind GeoIP database: '/var/lib/GeoIP/GeoLite2-City.mmdb'
[20:10:52]    |_  Run geoipupdate to install
[20:10:52][*] HTTP Proxy: http://000.0.0:6789
[20:10:52][*] BeEF server started (press control+c to stop)
2023-02-07 20:11:57 - ArgumentError - invalid byte sequence in US-ASCII:
        /usr/lib/ruby/vendor_ruby/erubis/enhancer.rb:647:in `scan'
        /usr/lib/ruby/vendor_ruby/erubis/enhancer.rb:647:in `convert_input'
        /usr/lib/ruby/vendor_ruby/erubis/converter.rb:36:in `convert'
        /usr/lib/ruby/vendor_ruby/erubis/engine.rb:30:in `initialize'
        /usr/share/beef-xss/core/main/handlers/modules/legacybeefjs.rb:107:in `new'
        /usr/share/beef-xss/core/main/handlers/modules/legacybeefjs.rb:107:in `legacy_build_beefjs!'
        /usr/share/beef-xss/core/main/handlers/hookedbrowsers.rb:137:in `block in <class:HookedBrowsers>'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1696:in `call'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1696:in `block in compile!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1009:in `block (3 levels) in route!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1027:in `route_eval'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1009:in `block (2 levels) in route!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1058:in `block in process_route'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1056:in `catch'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1056:in `process_route'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1007:in `block in route!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1004:in `each'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1004:in `route!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1128:in `block in dispatch!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1099:in `catch'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1099:in `invoke'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1123:in `dispatch!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:939:in `block in call!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1099:in `catch'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1099:in `invoke'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:939:in `call!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:928:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/null_logger.rb:11:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/head.rb:12:in `call'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:219:in `call'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:2007:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/urlmap.rb:74:in `block in call'
        /var/lib/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/urlmap.rb:58:in `each'
        /var/lib/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/urlmap.rb:58:in `call'
        /usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0/gems/thin-1.8.0/lib/thin/connection.rb:86:in `block in pre_process'
        /usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `catch'
        /usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `pre_process'
        /usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0/gems/thin-1.8.0/lib/thin/connection.rb:53:in `process'
        /usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0/gems/thin-1.8.0/lib/thin/connection.rb:39:in `receive_data'
        /usr/lib/ruby/vendor_ruby/eventmachine.rb:196:in `run_machine'
        /usr/lib/ruby/vendor_ruby/eventmachine.rb:196:in `run'
        /usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0/gems/thin-1.8.0/lib/thin/backends/base.rb:75:in `start'
        /usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0/gems/thin-1.8.0/lib/thin/server.rb:162:in `start'
        /usr/share/beef-xss/core/main/server.rb:156:in `start'
        ./beef:278:in `<main>'

(I hid the IP address in the link at the top)

**Comment by jcrew99** [comment]
Have you made any configuration changes from the default config.yaml file?

**Comment by azazazaz15** [comment]
nope.

**Comment by azazazaz15** [comment]
so, is there any solution?

**Comment by stephenakq** [comment]
@azazazaz15 Did you make any progress?

**Comment by azazazaz15** [comment]
> @azazazaz15 Did you make any progress?

Nah, I tried all the tutorials I found online but nothing worked.

**Comment by bcoles** [comment]
Try this:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-
