### ISSUE TITLE
I am running beEF on windows in Ubuntu and i have multiple issues

### ISSUE THREAD

**Issue by Python9874** [beefproject/beef#2716]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version:
5. Ruby Version:
6. Browser Details (e.g. Chrome v81.0):
7. Operating System (e.g. OSX Catalina):

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No
2. Have you enabled or disabled any BeEF extensions? Yes/No

## Steps to Reproduce

1. (eg. I ran install script, which ran fine)
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
3. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by Python9874** [comment]
Error running '__rvm_package_extract /home/seb/.rvm/archives/ruby-2.3.3.tar.bz2 /home/seb/.rvm/tmp/rvm_src_19885',
please read /home/seb/.rvm/log/1676134449_ruby-2.3.3/extract.log
There has been an error while trying to extract the source. Halting the installation.
There has been an error fetching the ruby interpreter. Halting the installation.

**Comment by Python9874** [comment]
There has been an error while trying to extract the source. Halting the installation. There has been an error fetching the ruby interpreter. Halting the installation.

**Comment by Python9874** [comment]
rvm is not working either
and it is telling me to install ruby 3.0.3 but when i run it it cant find the package

**Comment by Python9874** [comment]
@ilatypov

**Comment by bcoles** [comment]
This seems like an issue with your Ruby environment.

Ruby 2.3 is ancient and hasn't been supported for many years.
