### ISSUE TITLE
Beef On Repl It

### ISSUE THREAD

**Issue by wendellmeset** [beefproject/beef#2717]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: Latest
5. Ruby Version: N/A
6. Browser Details (e.g. Chrome v81.0): NA
7. Operating System (e.g. OSX Catalina): Ubuntu Linux I think, but it is Replit so I am not 100% Sure!

## Configuration

1. Have you made any changes to your BeEF configuration? No
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

1. Run install commands on a fresh bash instance on replit
2. Run install script
3. Beef does not launch, error with sudo command.

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by Shane-At-School** [comment]
Replit cannot run Beef, and this (presumptively) is also against replits terms of service.  You can remove the sudo command from the install file, but afaik you cannot obtain most apt packages anyway. You also cannot obtain sudo on replit, as it is disallowed.

**Comment by wendellmeset** [comment]
Replit itself is a powerful docker container, could we use this to our advantage to run beef?

**Comment by bcoles** [comment]
> Replit itself is a powerful docker container, could we use this to our advantage to run beef?

You could try?

BeEF is a HTTP(S) server. So long as you have a working Ruby environment and a network connection you should be able to use BeEF. You'll also need nodejs and a handful of system packages such as sqlite.

**Comment by stephenakq** [comment]
@wendellmeset Did you get BeEF working on Replit?

**Comment by wendellmeset** [comment]
No not yet

**Comment by wendellmeset** [comment]
I found a replit that emulates a linux terminal with sudo however storage is full, so it may be possible wit ha premium repl subscripbtion!

**Comment by Auzgame** [comment]
I was able to get beef working on replit. However, I still workout at a few of the bugs right now.

**Comment by Shane-At-School** [comment]
> I was able to get beef working on replit. However, I still working out a few of the bugs right now.

Can you link the replit project?

**Comment by bcoles** [comment]
It is easy to get running.

![BeEF on repl](https://user-images.githubusercontent.com/434827/229164844-2927605b-abd7-4127-a8ef-dda70d3c7e94.png)

```yaml
        public:
            host: "<redacted>.<redacted>.repl.co"
            port: "443"
            https: true
        allow_reverse_proxy: true
```

Unfortunately you'll run into this issue #2768 for reasons which aren't immediately obvious.

**Comment by bcoles** [comment]
> I found a replit that emulates a linux terminal with sudo however storage is full, so it may be possible wit ha premium repl subscripbtion!

You don't need sudo. To install:

* import the project from GitHub (as a Ruby project)
* run `bundle install` from shell
* install Node JS (I think I ran `node` or `nodejs` from shell and it prompted me to install it)
* change the password and `public` settings in the `config.yaml` file.

To decrease network traffic and server load, it would be polite to increase the XHR poll duration:

https://github.com/beefproject/beef/blob/173d8009a70b4da3a00c4230c07cbb64f12afd2b/config.yaml#L46

You're done. Change the Run command to `./beef` or manually run `./beef` from the shell.

There is ample storage (1GB) to get a default install running. BeEF only needs about 30MB + database contents over time.

**Comment by bcoles** [comment]
Here's a temporary workaround for #2768:

```diff
diff --git a/core/main/network_stack/websocket/websocket.rb b/core/main/network_stack/websocket/websocket.rb
index 65fa3680..997faa8c 100644
--- a/core/main/network_stack/websocket/websocket.rb
+++ b/core/main/network_stack/websocket/websocket.rb
@@ -24,6 +24,8 @@ module BeEF
         MOUNTS = BeEF::Core::Server.instance.mounts
 
         def initialize
+          return unless @@config.get('beef.websocket.enable')
+
           secure = @@config.get('beef.http.websocket.secure')
 
           # @note Start a WSS server socket
```

**Comment by bcoles** [comment]
Using Replit for anything other than testing and developing would most likely be against the [terms of service](https://replit.com/site/terms). Closing.
