### ISSUE TITLE
Hello my running beef on a Ubuntu vps do I need to install Apache2 and what firewall rules would I need?

### ISSUE THREAD

**Issue by Zahidtz** [beefproject/beef#2721]

**Comment by bcoles** [comment]
> do I need to install Apache2

no

> what firewall rules would I need

BeEF uses port 3000 by default. This is configurable in the config file. It optionally also uses additional ports for websocket communications. These are configurable in the config file.

**Comment by Zahidtz** [comment]
would it work on port 80?

**Comment by bcoles** [comment]
> would it work on port 80?

Yes. BeEF is a HTTP server. It can run on whichever port your choose. You can set the port in the config file.

https://github.com/beefproject/beef/blob/b83e06d5e080988292fcc754891b7f7fc0201e2b/config.yaml#L39

Keep in mind that you will need elevated privileges to bind to port 80.

Also keep in mind that most modern websites using HTTPS and modern web browsers do not load mixed active content, such as JavaScript, from clear text HTTP websites. Ideally you should set up a frontend reverse proxy or configure BeEF on port 443 with HTTPS enabled and valid certificates.

https://github.com/beefproject/beef/blob/b83e06d5e080988292fcc754891b7f7fc0201e2b/config.yaml#L94-L95

**Comment by Zahidtz** [comment]
what should i change the host ip too?

**Comment by bcoles** [comment]
> what should i change the host ip too?

You can leave the host IP address as `0.0.0.0`. This will bind to all interfaces.

If you are using a reverse proxy you will need to set the public host details appropriately for the hook callback:

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

**Comment by Zahidtz** [comment]
Thanks!
