### ISSUE TITLE
IM running beef on a vps but i tried all the links they gave me but nothing shows up I have a pictuere of my firewall in the comments UBUNTU

### ISSUE THREAD

**Issue by Zahidtz** [beefproject/beef#2722]
![image](https://user-images.githubusercontent.com/121258605/219864773-a9c9a6f2-506b-4bf9-8fe0-676144555d70.png)

**Comment by Zahidtz** [comment]
![image](https://user-images.githubusercontent.com/121258605/219864851-de211308-0aef-42ce-8a34-7dc93f2d00af.png)

**Comment by bcoles** [comment]
> i tried all the links they gave me but nothing shows

What does that mean? Is the port open and accessible? Did you get a connection failure? A blank page?

**Comment by Zahidtz** [comment]
i will show u a picture

**Comment by Zahidtz** [comment]
It looks like this in every picture

![image](https://user-images.githubusercontent.com/121258605/219865172-b195b941-30b0-4f76-807d-573df14d576c.png)

**Comment by Zahidtz** [comment]
should i be like this?

**Comment by Zahidtz** [comment]
![image](https://user-images.githubusercontent.com/121258605/219865367-ced4a1b8-a990-4e69-95c4-51e0999957a4.png)

**Comment by bcoles** [comment]
> should i be like this?

I'm not familiar with your VPS platform.

BeEF is a HTTP(S) server. If it is configured to listen on port 443 you will need to allow access to port 443.

**Comment by Zahidtz** [comment]
> > should i be like this?
> 
> I'm not familiar with your VPS platform.
> 
> BeEF is a HTTP(S) server. If it is configured to listen on port 443 you will need to allow access to port 443.

it does have accses to port 443

**Comment by bcoles** [comment]
> > > should i be like this?
> > 
> > 
> > I'm not familiar with your VPS platform.
> > BeEF is a HTTP(S) server. If it is configured to listen on port 443 you will need to allow access to port 443.
> 
> it does have accses to port 443

```
# nmap -p 80,443 45.76.20.210
Starting Nmap 7.93 ( https://nmap.org ) at 2023-02-18 07:13 EST
Nmap scan report for 45.76.20.210.vultrusercontent.com (45.76.20.210)
Host is up (0.028s latency).

PORT    STATE    SERVICE
80/tcp  open     http
443/tcp filtered https

Nmap done: 1 IP address (1 host up) scanned in 1.54 seconds
```

**Comment by Zahidtz** [comment]
hmm i will try again

**Comment by Zahidtz** [comment]
i will delete all my rules and start from scratch

**Comment by Zahidtz** [comment]
wait 2 minutes then can you run the nmap scan again

**Comment by Zahidtz** [comment]
run the scan again

**Comment by bcoles** [comment]
> run the scan again

Port 443 is still filtered. You can check the ports yourself.

**Comment by Shane-At-School** [comment]
http://45.76.20.210:443/ui/panel Should work, no?
