### ISSUE TITLE
[15:01:54][!] [GeoIP] Could not find MaxMind GeoIP database: '/usr/share/GeoIP/GeoLite2-City.mmdb'

### ISSUE THREAD

**Issue by wandas1212** [beefproject/beef#2723]
always getting the below error when i run BeEF

[15:01:54][!] [GeoIP] Could not find MaxMind GeoIP database: '/usr/share/GeoIP/GeoLite2-City.mmdb'

![image](https://user-images.githubusercontent.com/76051210/219872921-288726f4-bbca-49ab-b93b-75608254691e.png)

**Comment by bcoles** [comment]
GeoIP database is optional. Refer to: https://github.com/beefproject/beef/wiki/Geolocation

**Comment by swifty29320** [comment]
i have the same problem as wandas, what should I write to fix this (tell me in a simple way pls)

**Comment by bcoles** [comment]
> i have the same problem as wandas, what should I write to fix this (tell me in a simple way pls)

GeoIP database is optional. Refer to: https://github.com/beefproject/beef/wiki/Geolocation

**Comment by wandas1212** [comment]
> i have the same problem as wandas, what should I write to fix this (tell me in a simple way pls)

have you been able to fix it??
if know, get in touch with me so we fix it,
wandasheets1212@gmail.com or @Genesismalware on telegram,
i also have lots of projects that we could work on
