### ISSUE TITLE
Documentation of Command Modules REST API

### ISSUE THREAD

**Issue by nzqo** [beefproject/beef#2730]
There are two IDs returned in the response to [list the command modules](https://github.com/beefproject/beef/wiki/BeEF-RESTful-API#list-command-modules), namely the top-level key and the `"id"` values of each command module. It is not clear to me why there are two, why they differ, and whether one of them is expected to be consistent across different BeEF configurations.
I couldn't find this information anywhere in the docs and it would be invaluable for scripting.

Could someone clarify?
Thanks in Advance!

**Comment by bcoles** [comment]
> It is not clear to me why there are two, why they differ

Agreed.

> and whether one of them is expected to be consistent across different BeEF configurations.

I would not rely on it being the same per startup, let alone per install.

> I couldn't find this information anywhere in the docs and it would be invaluable for scripting.

There are some rudimentary examples here which may help with scripting:

* https://github.com/beefproject/beef/tree/master/tools/rest_api_examples

Specifically this example:

* https://github.com/beefproject/beef/blob/master/tools/rest_api_examples/command-modules

And the associated library:

* https://github.com/beefproject/beef/blob/master/tools/rest_api_examples/lib/beef_rest_api.rb

The REST example lazily looks up all modules using `/modules` and caches the data. The associated ID for a given module can be retrieved using the `api.get_module_id` method:

https://github.com/beefproject/beef/blob/d4c5baee8bc2188cd57205c614060d9f74233817/tools/rest_api_examples/lib/beef_rest_api.rb#L166-L181

**Comment by nzqo** [comment]
Thanks for the quick response!

Regarding the scripting examples you mentioned: I am doing something like that as well currently, where I retrieve the ID from the name. If the IDs were persistent, that part would be a bit simpler though. 

I'll use that for now, but since a clarification of the REST API docs would probably still make sense I'll leave the issue open.

**Comment by nzqo** [comment]
Any updates on this? Anyone who can explain why there are two ids and what their scope is?

**Comment by bcoles** [comment]
> Any updates on this? Anyone who can explain why there are two ids and what their scope is?

Is there a reason you need the IDs? They will not be the same between installs and will likely changes after updates.

```
"{\"0\":{\"id\":1,\"class\":\"Ui_abuse_ie\",\"name\":\"User Interface Abuse (IE 9/10)\",\"category\":\"Social Engineering\"},\"1\":{\"id\":2,\"class\":\"Text_to_voice\",\"name\":\"Text to Voice\",\"category\":\"Social Engineering\"},\"2\":{\"id\":3,\"class\":\"Tabnabbing\",\"name\":\"TabNabbing\",\"category\":\"Social Engineering\"},\"3\":{\"id\":4,\"class\":\"Spoof_addressbar_data\",\"name\":\"Spoof Address Bar (data URL)\",
```

The first ID iterates starting from 0. This is unique to the REST response.

The `id` property for each module represents the module ID.

```
sqlite> select * from command_modules;
1|ui_abuse_ie|modules/social_engineering/ui_abuse_ie/module.rb
2|text_to_voice|modules/social_engineering/text_to_voice/module.rb
3|tabnabbing|modules/social_engineering/tabnabbing/module.rb
4|spoof_addressbar_data|modules/social_engineering/spoof_addressbar_data/module.rb
...
```

**Comment by nzqo** [comment]
> Is there a reason you need the IDs? 
I solved my problem in a different way, so I don't need the IDs anymore. It's mainly curiosity at this point. 

I believe it would make sense to explain the purpose and validity/lifetime of the ids somewhere in the REST API docs. Is the module id not fixed in source files or why would it change between installs? I understand this module id can be used in other requests to e.g. refer to a specific command to launch. But I don't understand the purpose of the other id, the key of the response. It seems like returning a list would have sufficed?

**Comment by bcoles** [comment]
> Is the module id not fixed in source files or why would it change between installs?

The ID depends on the number of modules and the order in which they are loaded cannot safely be assumed to be deterministic.

> But I don't understand the purpose of the other id, the key of the response.

It likely serves no purpose.

> It seems like returning a list would have sufficed?

Probably. The REST API was haphazardly added to the code base.
