### ISSUE TITLE
Just type shell.cloud.google.com in your browser and type the installation process:

### ISSUE THREAD

**Issue by flippermaster** [beefproject/beef#2734]
Just type shell.cloud.google.com in your browser and type the installation process:

$ sudo apt-get ruby
$ sudo apt-get git 
$ git clone https://github.com/beefproject/beef
$ cd beef
$ rm Gemfile.lock
$ sudo nano Gemfile (create your username and password)HOW DO I DO THAT?
$ sudo nano config.yaml (again create your username and password)
$ ./beef
After that, click on URL, (make sure its not hook.js) then login to your brand new easy account and enjoy

(!!!WARNING!!! Educational Purposes, Dont do this on Anyone for Any reason, if you dont have permission)

ez

_Originally posted by @cyberbeast6 in https://github.com/beefproject/beef/issues/2328#issuecomment-1159195762_

**Comment by jcrew99** [comment]
What's the issue here? this is interesting but I'm unsure why you opened up a Issue.
