### ISSUE TITLE
the browser hooking is not working on other devives

### ISSUE THREAD

**Issue by adnangul301** [beefproject/beef#2735]
so when i tried to hook my phones browser actually it didn't worked for me and beside that when i hooked my linux browser it was hooked but worked for very limited time and i think it can be solved by providing another services for hooking like using of ngrok,local tunnels or teleconsole with this the process will become for smooth and the social engineering attacks will look more professional

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK
