### ISSUE TITLE
beef-xss.service disabled

### ISSUE THREAD

**Issue by Lrdcpj** [beefproject/beef#2742]
I'm using Kali Linux version 2022.4 , ruby 3.1.2p20. At first I had issues with ruby gems and fixed them by reinstalling ruby. Now beef is successfully installed but facing this error. Can someone plz help me

[i] GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

× beef-xss.service - beef-xss
     Loaded: loaded (/lib/systemd/system/beef-xss.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Tue 2023-03-07 12:33:39 +06; 5s ago
   Duration: 6ms
    Process: 5794 ExecStart=/usr/share/beef-xss/beef (code=exited, status=217/USER)
   Main PID: 5794 (code=exited, status=217/USER)
        CPU: 1ms

Mar 07 12:33:39 GWizard systemd[1]: Started beef-xss.
Mar 07 12:33:39 GWizard systemd[5794]: beef-xss.service: Failed to determine user credentials: No such process
Mar 07 12:33:39 GWizard systemd[5794]: beef-xss.service: Failed at step USER spawning /usr/share/beef-xss/beef: No such process
Mar 07 12:33:39 GWizard systemd[1]: beef-xss.service: Main process exited, code=exited, status=217/USER
Mar 07 12:33:39 GWizard systemd[1]: beef-xss.service: Failed with result 'exit-code'.

**Comment by bcoles** [comment]
Are there addittional logs?

```
journalctl -u beef-xss
```

**Comment by Lrdcpj** [comment]
> Are there addittional logs?
> 
> ```
> journalctl -u beef-xss
> ```

Mar 07 01:56:39 GWizard systemd[1]: Started beef-xss.
Mar 07 01:56:41 GWizard beef[9391]: <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require': cannot load such file -- t>
Mar 07 01:56:41 GWizard beef[9391]: Did you mean?  tins
Mar 07 01:56:41 GWizard beef[9391]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 01:56:41 GWizard beef[9391]:         from /usr/share/beef-xss/core/loader.rb:26:in `<top (required)>'
Mar 07 01:56:41 GWizard beef[9391]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 01:56:41 GWizard beef[9391]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 01:56:41 GWizard beef[9391]:         from /usr/share/beef-xss/beef:45:in `<main>'
Mar 07 01:56:41 GWizard systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Mar 07 01:56:41 GWizard systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Mar 07 01:57:49 GWizard systemd[1]: Started beef-xss.
Mar 07 01:57:50 GWizard beef[9692]: <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require': cannot load such file -- t>
Mar 07 01:57:50 GWizard beef[9692]: Did you mean?  tins
Mar 07 01:57:50 GWizard beef[9692]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 01:57:50 GWizard beef[9692]:         from /usr/share/beef-xss/core/loader.rb:26:in `<top (required)>'
Mar 07 01:57:50 GWizard beef[9692]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 01:57:50 GWizard beef[9692]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 01:57:50 GWizard beef[9692]:         from /usr/share/beef-xss/beef:45:in `<main>'
Mar 07 01:57:50 GWizard systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Mar 07 01:57:50 GWizard systemd[1]: beef-xss.service: Failed with result 'exit-code'.
-- Boot dfb53e5f295842cea8aeaa8ce1f39aa0 --
Mar 07 02:26:45 GWizard systemd[1]: Started beef-xss.
Mar 07 02:26:49 GWizard beef[2970]: <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require': cannot load such file -- t>
Mar 07 02:26:49 GWizard beef[2970]: Did you mean?  tins
Mar 07 02:26:49 GWizard beef[2970]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 02:26:49 GWizard beef[2970]:         from /usr/share/beef-xss/core/loader.rb:26:in `<top (required)>'
Mar 07 02:26:49 GWizard beef[2970]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 02:26:49 GWizard beef[2970]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 02:26:49 GWizard beef[2970]:         from /usr/share/beef-xss/beef:45:in `<main>'
Mar 07 02:26:49 GWizard systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Mar 07 02:26:49 GWizard systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Mar 07 02:26:49 GWizard systemd[1]: beef-xss.service: Consumed 1.100s CPU time.
Mar 07 02:34:06 GWizard systemd[1]: Started beef-xss.
Mar 07 02:34:06 GWizard beef[3770]: <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require': cannot load such file -- t>
Mar 07 02:34:06 GWizard beef[3770]: Did you mean?  tins
Mar 07 02:34:06 GWizard beef[3770]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 02:34:06 GWizard beef[3770]:         from /usr/share/beef-xss/core/loader.rb:26:in `<top (required)>'
Mar 07 02:34:06 GWizard beef[3770]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 02:34:06 GWizard beef[3770]:         from <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
Mar 07 02:34:06 GWizard beef[3770]:         from /usr/share/beef-xss/beef:45:in `<main>'
Mar 07 02:34:06 GWizard systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Mar 07 02:34:06 GWizard systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Mar 07 02:37:23 GWizard systemd[1]: Started beef-xss.
Mar 07 02:37:24 GWizard beef[4449]: <internal:/usr/local/lib/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require': cannot load such file -- t>
Mar 07 02:37:24 GWizard beef[4449]: Did you mean?  tins

**Comment by bcoles** [comment]
The easiest solution is to clone from GitHub instead

**Comment by Lrdcpj** [comment]
I did that. First I cloned the files from Github to a new directory in home. Then installed beef from cloned files.

$ git clone https://github.com/beefproject/beef
then opened the directory with cloned files

$ ./install

**Comment by bcoles** [comment]
`install` is mostly unnecessary. It installs a handful of operating system packages then runs `bundle install`.

`bundle install` is the most important part.

Then `./beef` to run.

**Comment by Lrdcpj** [comment]
It worked. I am still new to kali Linux and don't have much knowledge about it. So your help is so much important to me. Thank you

**Comment by ABLYS0** [comment]
I tried ./ install but it dont work it keeps telling me, Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by Layvth** [comment]
❤️

**Comment by glock19s** [comment]
Hi, I still have the problem 
There is any solution?

**Comment by anishalx** [comment]
i am getting this error when i cloned and installed .

The following packages have unmet dependencies:
 libncurses5-dev : Depends: libtinfo6 (= 6.4-4) but 6.5+20250216-1 is to be installed
                   Depends: libncurses-dev (= 6.4-4) but 6.5+20250216-1 is to be installed
E: Unable to correct problems, you have held broken packages.
E: The following information from --solver 3.0 may provide additional context:
   Unable to satisfy dependencies. Reached two conflicting decisions:
   1. libtinfo6:amd64=6.4-4 is not selected for install
   2. libtinfo6:amd64=6.4-4 is selected as a downgrade because:
      1. libncurses5-dev:amd64=6.4-4 is selected for install
      2. libncurses5-dev:amd64 Depends libtinfo6 (= 6.4-4)

**Comment by Glock17s** [comment]
> Hi, I still have the problem There is any solution?

Ps , I installed and there were a few dependencies missed and I installed them manually now it’s works

**Comment by anishalx** [comment]
> stalled and there was a few dependencies missed and I installed them manually now it’s w

can u tell me how can i install it manually

**Comment by glock19s** [comment]
See which one is not installed or done which error the usually is written in red color and do manually 
"gem install bundler "for example

**Comment by reiyua** [comment]
Can confirm, simply cloning the Beef repository, cding into the beef directory and running sudo ./install.sh fixed it for me.
