### ISSUE TITLE
Hook page doesn't open in android or windows chrome browsers

### ISSUE THREAD

**Issue by Lrdcpj** [beefproject/beef#2743]
beef is running without errors in my virtual kali linux machine and can hook the firefox browser in the same virtual machine. But the hook page doesn't open in the browser on the host windows machine. Also, I tried it on my android phone's chrome browser but doesn't open.

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

**Comment by Lrdcpj** [comment]
> https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

Thank you. This says that I will need a paid version of ngrok to work with beef. Is there a free alternative for ngrok?

**Comment by Lrdcpj** [comment]
In that case, If I install kali linux  on the host machine instead of a virtual one and connect to the internet via my normal home broadband connection the hooked browsers would be able to connect right?  ( not practical. just to understand )

**Comment by bcoles** [comment]
> In that case, If I install kali linux on the host machine instead of a virtual one and connect to the internet via my normal home broadband connection the hooked browsers would be able to connect right? ( not practical. just to understand )

Only if your host OS is directly accessible via the Internet, which is unlikely. Your home broadband is likely behind a router which performs NAT.

BeEF is a web server like any other. If remote hosts can't establish a network connection to the server then... they can't connect.

You could try ngrok for testing purposes. ngrok features anti-abuse functionality which can only be avoided with a paid account. The anti-abuse requires manual user interaction with the server before connections are permitted. I forget exactly how it works, but I've tested with it successfully previously.

**Comment by Lrdcpj** [comment]
I'll study more about it. thanks you
