### ISSUE TITLE
i can not go to the beef ui and the hook site with a diffrent computer than the computer were i installed beef on

### ISSUE THREAD

**Issue by roandean1** [beefproject/beef#2748]
i can not go to the beef ui and the hook site with a diffrent computer than the computer were i installed beef on

**Comment by arjinmaroufi** [comment]
bro do this ok 
sudo apt-get install beef-xss
and then do sudo beef-xss to run beef and if you want to stop beef put in this command sudo beef-xss-stop

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK
