### ISSUE TITLE
Unable to correct problems , you have held broken packages

### ISSUE THREAD

**Issue by Mohamadar11** [beefproject/beef#2756]
Issue in installing beef how i can solve in![image](https://user-images.githubusercontent.com/128209699/226088287-7cd06c50-851e-49ec-a590-65d55b33636d.jpeg)

**Comment by bcoles** [comment]
Fix your packages. Or proceed with installing Ruby dependencies with `bundle install.`

**Comment by Mohamadar11** [comment]
Can you explain more i am beginner 😅

**Comment by bcoles** [comment]
```
bundle install
```

**Comment by Mohamadar11** [comment]
I get this ![image](https://user-images.githubusercontent.com/128209699/226090304-0da38921-abc6-44c4-ac62-035b2bf4aa61.jpeg)

**Comment by bcoles** [comment]
```
gem install xmlrpc
bundle install
```

**Comment by Mohamadar11** [comment]
![image](https://user-images.githubusercontent.com/128209699/226090847-b5a8cbd6-8376-4861-803e-bbc7b7680be6.jpeg)

**Comment by Mohamadar11** [comment]
I installed the gem xmlrpc 
And after that iget this ![image](https://user-images.githubusercontent.com/128209699/226091312-588254ea-94d2-4545-a786-ae11c39fadd5.jpeg)

**Comment by bcoles** [comment]
```
gem install unf
bundle  install
```

**Comment by Mohamadar11** [comment]
When bundle install ends what i have to do? 
I tried to install beef i get the same error 😫

**Comment by Mohamadar11** [comment]
![image](https://user-images.githubusercontent.com/128209699/226091914-b922793a-86c4-431e-96ac-0e76ce37247a.jpeg)

After installing bundle

**Comment by Mohamadar11** [comment]
![image](https://user-images.githubusercontent.com/128209699/226092145-55ecbcc5-1a00-4f5a-b2e3-faf89185fc58.jpeg)

**Comment by bcoles** [comment]
You are done. Run BeEF. `./beef`
