### ISSUE TITLE
After installing beef not working

### ISSUE THREAD

**Issue by Mohamadar11** [beefproject/beef#2757]
![image](https://user-images.githubusercontent.com/128209699/226099505-54aafa27-4132-4e13-a30a-2cac25ccdb45.jpeg)

**Comment by bcoles** [comment]
Install NodeJS.

**Comment by Mohamadar11** [comment]
I installed nodejs now i get this error 
![image](https://user-images.githubusercontent.com/128209699/226102259-adc03040-e98b-4bba-adff-541a9015102b.jpeg)

**Comment by Mohamadar11** [comment]
It works now 🤩
Thank you 🙏 ![image](https://user-images.githubusercontent.com/128209699/226102921-9fa9b1c8-72c1-42a2-8eac-97a825770573.jpeg)
