### ISSUE TITLE
ruby version out of date

### ISSUE THREAD

**Issue by KillzTheSpy2** [beefproject/beef#2765]
ok so when i type `./beef install` it comes up with `Ruby version 2.6.10 is no longer supported. Please upgrade to Ruby version 2.7 or later.`. So then i do `./update-beef` to update it right? no. it does this: 
`Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find compatible versions

Because capybara >= 3.37.0 depends on Ruby >= 2.7.0
  and Gemfile depends on capybara ~> 3.38,
  Ruby >= 2.7.0 is required.
So, because current Ruby version is = 2.6.10,
  version solving has failed.

I DON'T KNOW WHY
IVE BEEN TRYING TO FIX IT FOR THE PAST 20 MINUTES

oh also im on OSX

**Comment by nokee091** [comment]
did you figure it out? im having the same problem but now it needs 3.0 and when i try to get 3.0 it says allready latest version!!

**Comment by bcoles** [comment]
Ensure you are running BeEF with the correct version of Ruby If you have multiple versions of Ruby installed. ie, `ruby3 ./beef`

**Comment by Medokowider** [comment]
Did anyone figure it out. same boat here

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
