### ISSUE TITLE
ruby version out of date

### ISSUE THREAD

**Issue by KillzTheSpy2** [beefproject/beef#2766]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version:
5. Ruby Version: 2.6.10
6. Browser Details (e.g. Chrome v81.0):
7. Operating System (e.g. OSX Catalina): OSX Ventura 13.2

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No
2. Have you enabled or disabled any BeEF extensions? Yes/No

## Steps to Reproduce

1. (eg. I ran install script, which ran fine)
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
3. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by KillzTheSpy2** [comment]
ok so when i type `./beef install` it comes up with `Ruby version 2.6.10 is no longer supported. Please upgrade to Ruby version 2.7 or later.`. So then i do `./update-beef` to update it right? no. it does this: 
`Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find compatible versions

Because capybara >= 3.37.0 depends on Ruby >= 2.7.0
  and Gemfile depends on capybara ~> 3.38,
  Ruby >= 2.7.0 is required.
So, because current Ruby version is = 2.6.10,
  version solving has failed.

I DON'T KNOW WHY
IVE BEEN TRYING TO FIX IT FOR THE PAST 20 MINUTES

oh also im on OSX

**Comment by bcoles** [comment]
> ok so when i type `./beef install`

`beef install` is not a valid command.

> it comes up with `Ruby version 2.6.10 is no longer supported. Please upgrade to Ruby version 2.7 or later.`.

Ruby version 2.6.10 is no longer supported. Upgrade Ruby to version 3.0.3 or newer.

> So then i do `./update-beef` to update it right? no. it does this: `Fetching gem metadata from https://rubygems.org/......... Resolving dependencies... Could not find compatible versions

`update-beef` updates BeEF. It does not update Ruby.

> I DON'T KNOW WHY IVE BEEN TRYING TO FIX IT FOR THE PAST 20 MINUTES

As per the error message you must update to a supported version of Ruby.

* https://www.ruby-lang.org/en/downloads/branches/
