### ISSUE TITLE
Internal Server Error with hook.js

### ISSUE THREAD

**Issue by skjose0705** [beefproject/beef#2784]
When I put the url with the hook.js the server does a code 500 saying : Internal Server Error

In the ngrok panel say the same

  Session Status                online                                                                        Account                       x@gmail.com (Plan: Free)                                            Version                       3.2.2                                                                         Region                        Europe (eu)                                                                   Latency                       94ms                                                                          Web Interface                 http://127.0.0.1:4040                                                         Forwarding                    https://x.eu.ngrok.io -> http://localhost:3000                Connections                   ttl     opn     rt1     rt5     p50     p90                                                                 25      0       0.00    0.00    2.56    60.01                                 HTTP Requests                                                                                               -------------                                                                                               GET /hook.js                   500 Internal Server Error

And the beef terminal panel say this:

2023-04-01 19:15:35 - ArgumentError - invalid byte sequence in US-ASCII:
        /usr/lib/ruby/vendor_ruby/erubis/enhancer.rb:647:in `scan'
        /usr/lib/ruby/vendor_ruby/erubis/enhancer.rb:647:in `convert_input'
        /usr/lib/ruby/vendor_ruby/erubis/converter.rb:36:in `convert'
        /usr/lib/ruby/vendor_ruby/erubis/engine.rb:30:in `initialize'
        /root/beef/core/main/handlers/modules/legacybeefjs.rb:107:in `new'
        /root/beef/core/main/handlers/modules/legacybeefjs.rb:107:in `legacy_build_beefjs!'
        /root/beef/core/main/handlers/hookedbrowsers.rb:138:in `block in <class:HookedBrowsers>'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1696:in `call'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1696:in `block in compile!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1009:in `block (3 levels) in route!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1027:in `route_eval'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1009:in `block (2 levels) in route!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1058:in `block in process_route'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1056:in `catch'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1056:in `process_route'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1007:in `block in route!'        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1004:in `each'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1004:in `route!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1128:in `block in dispatch!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1099:in `catch'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1099:in `invoke'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1123:in `dispatch!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:939:in `block in call!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1099:in `catch'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:1099:in `invoke'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:939:in `call!'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:928:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/null_logger.rb:11:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/head.rb:12:in `call'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:219:in `call'
        /usr/share/rubygems-integration/all/gems/sinatra-3.0.5/lib/sinatra/base.rb:2007:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/urlmap.rb:74:in `block in call'
        /var/lib/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/urlmap.rb:58:in `each'        /var/lib/gems/3.1.0/gems/rack-2.2.6.4/lib/rack/urlmap.rb:58:in `call'        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
        /var/lib/gems/3.1.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /var/lib/gems/3.1.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'        /root/beef/core/main/server.rb:156:in `start'
        ./beef:278:in `<main>'

Help please

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-

**Comment by skjose0705** [comment]
I do this and the problem is still there, Are there more solutions?

**Comment by bcoles** [comment]
> I do this and the problem is still there

You must run the command in terminal before running BeEF.


> Are there more solutions?

A lot more information is required.

## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version:
5. Ruby Version:
6. Browser Details (e.g. Chrome v81.0):
7. Operating System (e.g. OSX Catalina):

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No
2. Have you enabled or disabled any BeEF extensions? Yes/No

## Steps to Reproduce

1. (eg. I ran install script, which ran fine)
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
3. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by skjose0705** [comment]
Thanks, solved :)
