### ISSUE TITLE
Hooked Browser not Showing in Beef UI.

### ISSUE THREAD

**Issue by thecowmilk** [beefproject/beef#2789]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version:
5. Ruby Version:
6. Browser Details (e.g. Chrome v81.0):
7. Operating System (e.g. OSX Catalina):

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No
Yes just the default username/password
2. Have you enabled or disabled any BeEF extensions? Yes/No
No
## Steps to Reproduce

1. I ran install script, which ran fine
2. when launching console with './beef' I get no error. 
3. I hook a .html file4. 
4. The server is loaded fine with the hooked html5. 
5. Browser not showing in beef UI.
## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
6. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
7. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
There is not enough information to reproduce this issue.

Are there errors in the browser console? Are there any hints in the Network tab in the browser developer tools

Can the host running the hooked browser establish a TCP connection to the BeEF server?

Are you running BeEF behind a reverse proxy or using a tunneling service? If so, have you set the appropriate `public` settings in the config file?

Are you running BeEF with SSL enabled? If so, are you using a valid SSL certificate trusted by the hooked browser?

**Comment by thecowmilk** [comment]
I will answer the question as soon as I can.

**Comment by thecowmilk** [comment]
> There is not enough information to reproduce this issue.
> 
> Are there errors in the browser console? Are there any hints in the Network tab in the browser developer tools

Yes, there's a error which says "content security policy: the page's setting blocked the loading of a resource" and points to my hook.js file

> Can the host running the hooked browser establish a TCP connection to the BeEF server?
Yes, it also is in inside LAN.

> Are you running BeEF behind a reverse proxy or using a tunneling service? If so, have you set the appropriate `public` settings in the config file?
No.

> Are you running BeEF with SSL enabled? If so, are you using a valid SSL certificate trusted by the hooked browser?
No. SSL is disabled.

**Comment by bcoles** [comment]
> Yes, there's a error which says "content security policy: the page's setting blocked the loading of a resource" and points to my hook.js file

BeEF does not bypass CSP.

If your script is inserted into a page which utilises CSP you must find a way to bypass the CSP. Unfortunately BeEF contains no CSP bypasses and does not easily lend itself to dynamic execution using common known bypasses.

**Comment by thecowmilk** [comment]
I see. Okay thanks for clarifying I will what I can do. All the best!!
