### ISSUE TITLE
Hook URL

### ISSUE THREAD

**Issue by yusufIQ** [beefproject/beef#2818]
The Hook URL works on my device but not on any other device. I do not know why? I created my own website using the same code used in the butchers website and i dont think its because of my code. The reason for this is because i tried the demo link on a diffrent device and it still doesnt work and says: Error. Refused to connect.
Please help.

**Comment by bcoles** [comment]
The BeEF hook is written in JavaScript. You can include it like any other JavaScript resource.

Note that in order for browsers to connect to be hooked by BeEF they must be able to establish a TCP connection to the BeEF server.

If you are running BeEF on your home network it will not be accessible from the Internet.

Also note that modern web browsers refuse to load JavaScript resources on HTTPS pages from HTTP sources.

As such, you will need to either enable HTTPS or host BeEF behind a reverse proxy.

Note that if you enable HTTPS you must use a valid certificate signed by a trusted certificate authority. Self-signed certificates are not trusted. Web browsers will not connect.

**Comment by yusufIQ** [comment]
Thanks, that helped alot.
