### ISSUE TITLE
Beef is not hooking over WAN (ngrok), Either ngrok is blocking or it's a bug????

### ISSUE THREAD

**Issue by kali64amd** [beefproject/beef#2827]
First of all I have checked this on closed issue and I couldn't find any solution so I'm opening this issue.

 
Beef is not hooking over WAN (ngrok), I have configure all thing properly in ngrok and config.yaml. Its working on LAN however over WAN it won't hook any devices.

it's Strange I can see its connected on ngrok however beef is not hooking any thing, And I can not able login in web panel over WAN but I can see beef web page which means its connecting but somehow its not working.

So I think Either ngrok is blocking or it's a bug?

Here is beef initiating 

![beef](https://user-images.githubusercontent.com/28497075/233801052-b45b3ce8-6de1-453e-a647-fef424d1b075.png)

here we can see it's connecting on WAN

![ngbeefconnect](https://user-images.githubusercontent.com/28497075/233801145-c6049e5f-ef40-462c-95eb-561ffda94d21.png)

It's connected on ngrok

![ngrok](https://user-images.githubusercontent.com/28497075/233801199-7e50d297-c041-4ece-bb45-60c9f09001a5.png)

However can not able Login in web panel, we can see beef web panel

![ngrok1](https://user-images.githubusercontent.com/28497075/233801253-51e572a9-84a5-49cf-89f7-a5edc667ff99.png)

 And here on my Android device it's connected but can't see beef web page

![andriod](https://user-images.githubusercontent.com/28497075/233801312-256ea8a2-3804-4d87-a992-9548a1b1442a.jpg)

Appreciate your Insight.

Thanks

AND NOW ITS ALSO NOT WORKING LOCALY (LAN) .................... What is going on???

![Screenshot at 2023-04-23 01-04-46](https://user-images.githubusercontent.com/28497075/233802678-210ada8a-33b6-42a9-b307-04ee344ec99f.png)

**Comment by bcoles** [comment]
Try the demo page

**Comment by kali64amd** [comment]
> Try the demo page

I do believe it might work!! however I'm stuck in config.yaml file.
I have open separate issue on this topic.

Appreciate your help!

**Comment by bcoles** [comment]
None of the above is true. The above is likely to be more confusing than useful to anyone else. I suggest no one follows your advice.

**Comment by bcoles** [comment]
> Strange it won't work on ios devices.
> 
> Anyone shed light on this???????

There is not enough information to offer guidance.
