### ISSUE TITLE
Question !! why  #public: string has missing in Parrot OS???? (config.yaml)

### ISSUE THREAD

**Issue by kali64amd** [beefproject/beef#2828]
Could Anyone tell me why  #public: string has missing in Parrot OS???? 

![config1](https://user-images.githubusercontent.com/28497075/233850901-4dffdc3b-18a5-40a1-8612-240807fd9e53.png)
![config2](https://user-images.githubusercontent.com/28497075/233850904-ebe9a65f-ffcb-4fe3-b164-6a04d5a28b85.png)
![config3](https://user-images.githubusercontent.com/28497075/233850906-743f3d2f-e3fe-4c79-b61a-713162cf1bc0.png)
![config4](https://user-images.githubusercontent.com/28497075/233850909-6fd74e66-7c38-43f4-8a78-17a545ed56ad.png)

**Comment by bcoles** [comment]
> Could Anyone tell me why #public: string has missing in Parrot OS????

You would have to ask the package maintainers. They likely removed it from the default config file as it is not used by default.
