### ISSUE TITLE
 No devices being hooked!!!

### ISSUE THREAD

**Issue by kali64amd** [beefproject/beef#2831]
It's Strange No devices has being hooked! Everything working was fine till yesterday but something happen maybe because I have enable msf on beef.

And I'm clueless cuz there hasn't any error! everything is ok.

  
![err](https://user-images.githubusercontent.com/28497075/234265592-50a8737b-82f6-4351-950a-26511663d977.png)

As we can see response = offline !!

why????

**Comment by bcoles** [comment]
> Everything working was fine till yesterday but something happen maybe because I have enable msf on beef.

Maybe. That should be easy to test...

> As we can see response = offline !!

What about on the client browser?

**Comment by kali64amd** [comment]
I can see Index page on client browser however no connection in beef!!

which is strange !!

**Comment by bcoles** [comment]
What about the network traffic on the client browser?

**Comment by kali64amd** [comment]
I can see default web page on client browser which is http://192.168.1.68:3000/demos/butcher/index.html however can't hook in beef

so far what I see is error 

Source map error: Error: request failed with status 404
Resource URL: http://192.168.1.68:3000/ui/media/javascript/vis.js/vis.min.js
Source Map URL: vis.map

![sorcemaperror](https://user-images.githubusercontent.com/28497075/234532274-25c114bd-b2ca-4e6a-b0e8-df7001cb1d3c.png)

**Comment by bcoles** [comment]
In all three of your screenshots you're showing the browser developer tools for the BeEF admin UI panel. That won't help.

Check the browser developer tools for the hooked browser.

**Comment by ScienceArtist** [comment]
were you able to find solution?, I am also stuck in this issue

**Comment by bcoles** [comment]
> were you able to find solution?, I am also stuck in this issue

No issue has been described. "No devices being hooked" is about as descriptive as "doesn't work". There is nothing actionable. No guidance can be offered.

**Comment by kali64amd** [comment]
@ ScienceArtist Just reinstall beef and you will be fine.....

**Comment by bcoles** [comment]
> @ ScienceArtist Just reinstall beef and you will be fine.....

This is not true. There are many reasons why a browser may not be hooked.
