### ISSUE TITLE
Ruby version 2.7.4 is not supported

### ISSUE THREAD

**Issue by kali64amd** [beefproject/beef#2838]
INFO]  No Ruby package manager detected - will install Ruby
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ruby-dev is already the newest version (1:2.7+2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 2.7.4 is installed
[FATAL]  Ruby version 2.7.4 is not supported. Please install Ruby 3.0 (or newer) and restart the installer

When I'm trying to install beef....

**Comment by bcoles** [comment]
Ruby 2.x is EOL. Install Ruby 3.0 or newer.
