### ISSUE TITLE
 Seriously...... Please explain this?? #2839 

### ISSUE THREAD

**Issue by kali64amd** [beefproject/beef#2840]
![beef2](https://user-images.githubusercontent.com/28497075/235089265-e9dffa4f-238b-4b32-8584-36443d6799ca.png)
![ruby](https://user-images.githubusercontent.com/28497075/235089290-2afc9b44-18ea-4149-b337-6d2b8b2cbf44.png)

**Comment by bcoles** [comment]
You have multiple versions of Ruby installed.

You don't need the installer script. Just run `bundle install`. Make sure you're using Ruby 3.0 or newer.

**Comment by kali64amd** [comment]
ok then, please have look this .....

![bundel1](https://user-images.githubusercontent.com/28497075/235092027-d813d2c7-222c-4122-92ee-277806665aa6.png)
![bundel2](https://user-images.githubusercontent.com/28497075/235092039-d8a68bc3-1ea7-4f94-a92f-d13f711269d1.png)
  AND STILL ...
![bundel3](https://user-images.githubusercontent.com/28497075/235092260-0df25319-870c-46cd-b490-224f07c50542.png)

**Comment by bcoles** [comment]
What is the problem?

**Comment by bcoles** [comment]
To run BeEF:

```
./beef
```

Ensure you're using the correct version of Ruby.

**Comment by kali64amd** [comment]
Ok the Explain this to me.....

What is wrong on this??? ruby 3.0 has already installed then why beef is not installing??

![new1](https://user-images.githubusercontent.com/28497075/235095934-439727a5-e482-45cb-b3b0-5dfc114a332a.png)
![new2](https://user-images.githubusercontent.com/28497075/235095937-fba6453e-8cdd-4895-9cf9-1b8994621a4f.png)
![new3](https://user-images.githubusercontent.com/28497075/235095946-ba5ddcae-2acc-4130-b7ea-fda4d905b4ad.png)
![new4](https://user-images.githubusercontent.com/28497075/235095952-38eadb96-9586-4996-9a2b-f507b2ff7210.png)

**Comment by bcoles** [comment]
> ruby 3.0 has already installed then why beef is not installing??

You do not need to run the install script. Use `bundle install` instead.

> What is wrong on this??? 

You have multiple different versions of Ruby installed. On top of that, you're using `rvm` to manage Ruby environments.

Ensure `rvm` is configured to use the correct version of Ruby. Ensure `bundle` installed the Ruby gems for the correct version of Ruby.

You may need to execute BeEF via `bundle`:

```
bundle exec ./beef
```

**Comment by kali64amd** [comment]
> > ruby 3.0 has already installed then why beef is not installing??
> 
> You do not need to run the install script. Use `bundle install` instead.

Yes I did it.
> 
> > What is wrong on this???
> 
> You have multiple different versions of Ruby installed. On top of that, you're using `rvm` to manage Ruby environments.
> 
> Ensure `rvm` is configured to use the correct version of Ruby. Ensure `bundle` installed the Ruby gems for the correct version of Ruby.

![rubver](https://user-images.githubusercontent.com/28497075/235103793-ca17e07c-34eb-4da1-b8a8-bcedfcddb93f.png)



> 
> You may need to execute BeEF via `bundle`:
> 
> ```
> bundle exec ./beef
> ```



![123](https://user-images.githubusercontent.com/28497075/235104055-3e2bef43-35ec-4c9b-9a42-e645c22770ca.png)

And yes ....... here is bundle install

![45](https://user-images.githubusercontent.com/28497075/235104751-e74b1108-be69-46f0-b959-ca0a42e92a33.png)



![46](https://user-images.githubusercontent.com/28497075/235104752-3e5af62e-0496-4989-a436-d387a136a63c.png)


Now could you tell me what is wrong here???

**Comment by bcoles** [comment]
You have multiple versions of Ruby. You need to fix your Ruby environment.

You may have multiple versions of `bundle`.

```
gem3.x install bundler
bundle3.x install
bundle3.x exec ./beef
```

**Comment by kali64amd** [comment]
Finally !!!!!!...............................
its fix.

gem update --system

I have just update bundle in system, and everything is updated. 

Anyway appreciate your help @bcoles

**Comment by kali64amd** [comment]
@bcoles could you advise me why beef is breaking when I enable Metasploit extensions ??

I can see msf payload in beef however its breaking other thingd..

**Comment by bcoles** [comment]
> @bcoles could you advise me why beef is breaking when I enable Metasploit extensions ??
> 
> I can see msf payload in beef however its breaking other thingd..

There is not enough information to provide guidance. #2396 https://github.com/beefproject/beef/issues/2396#issuecomment-1204260953
