### ISSUE TITLE
Beef not working on domain

### ISSUE THREAD

**Issue by Bani4kaa** [beefproject/beef#2842]
I connected my vps public ip to domain name that works connected everything, then when I connect to the ip I see that beef injects in my browser, but when I try the domain it does not work I made ssl certificate trought Cloudflare on the domain

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#can-i-use-a-domain-name-instead-of-ip-address-for-the-beef-hook

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/blob/943a6fd2266f2652e64885c499e8f8fb5735ac10/config.yaml#L56-L59

**Comment by Bani4kaa** [comment]
> It looks like you've messed something up. The error says port `80` but you're using `https://`.
> 
> Ensure your network routing is correct.

idk man I just want when I go example.com to hook the user but it does not work idk why

**Comment by Bani4kaa** [comment]
Like I do not want to control the beef panel with it only to hook

**Comment by bcoles** [comment]
BeEF is a HTTP server. You don't need to modify anything in the config file to get network access working. Modifying the `public` properties is only required to get hooking working.

Can you access the UI panel? `/ui/panel`

**Comment by Bani4kaa** [comment]
From the domain no from the public ip yes
the domain is on https and the public ip is ran on http

**Comment by bcoles** [comment]
> From the domain no from the public ip yes the domain is on https and the public ip is ran on http

There's something wrong without however you're routing.

If you're using a reverse proxy you will need to review your configuration.

If you're simply using the domain name to point to the public IP address, then you will need to either connect using `http://` or set BeEF to use HTTPS on port 443. Note that you should also use a trusted SSL certificate.

**Comment by Bani4kaa** [comment]
Yea I have cloudflare

**Comment by bcoles** [comment]
I have no idea what that means. There's nowhere near enough information to offer any guidance here.

If you can tell me why it doesn't work I can tell you how to fix it. BeEF is a HTTP(S) server.

**Comment by Bani4kaa** [comment]
![image](https://user-images.githubusercontent.com/122724138/236272110-8b869434-df95-441d-8eaa-87742f6644bf.png)
Ok when I run beef I get this two things, I log in with the first one because only that one works, I want to use the other one that has port 443 (https) to hook. I have fixed everything I can show you the config file too

**Comment by Bani4kaa** [comment]
![image](https://user-images.githubusercontent.com/122724138/236272535-e75b563d-a741-4280-b01d-531f7287f34b.png)

**Comment by Bani4kaa** [comment]
If you want we can continue our conversation on telegram or discord

**Comment by bcoles** [comment]
That configuration looks fine. It should work for hooking so long as the public host presents a trusted SSL certificate.

> If you want we can continue our conversation on telegram or discord

https://discord.gg/SpDd354p
