### ISSUE TITLE
Problem launching beef it seems

### ISSUE THREAD

**Issue by Vandalstreets** [beefproject/beef#2844]
![Screenshot 2023-05-03 111510](https://user-images.githubusercontent.com/132488831/235993522-0b1619ef-5c3e-49e9-a274-53f937aab406.png)

![image](https://user-images.githubusercontent.com/132488831/235994922-8e49f7b8-3002-4ec8-b1b5-2d49452fd4e8.png)

It might just be simple, but I'm only a beginner so I have no clue what's going on or how to fix it. 
I have the systemd problem under control though.

**Comment by valimikayilov** [comment]
Did you install the required dependencies from the ‘install’ file?
