### ISSUE TITLE
Cookies session 

### ISSUE THREAD

**Issue by jsthonk** [beefproject/beef#2848]
Howdy!
How can i get all cookies?
It doesn't seem to work, what should i do first before being able to get all cookies
And again why does it unhook user browser if you close the tab?

**Comment by bcoles** [comment]
> How can i get all cookies?

`document.cookie`

> It doesn't seem to work

why not?

> what should i do first before being able to get all cookies

hook the browser

> And again why does it unhook user browser if you close the tab?

code is executed in a tab

**Comment by jsthonk** [comment]
browser.cookie doesn't get all cookies
It gets only the cookie of that exact tab opened

**Comment by bcoles** [comment]
> It gets only the cookie of that exact tab opened

Correct. It also won't get cookies with the HttpOnly flag set.

To get cookies for all origins you will need to execute code in a privileged context, such as a browser extension or UXSS.
