### ISSUE TITLE
Cloud shell

### ISSUE THREAD

**Issue by Hmmmmmmmmmmmhm** [beefproject/beef#2856]
Just type shell.cloud.google.com in your browser and type the installation process:

$ sudo apt-get ruby
$ sudo apt-get git
$ git clone https://github.com/beefproject/beef
$ cd beef
$ rm Gemfile.lock
$ sudo nano Gemfile (create your username and password)
$ sudo nano config.yaml (again create your username and password)
$ ./beef
After that, click on URL, (make sure its not hook.js) then login to your brand new easy account and enjoy

I found this but I was wondering how to make the password because its hard to understand it pls help

**Comment by bcoles** [comment]
> $ sudo nano Gemfile (create your username and password)

This does not make any sense.

> $ sudo nano config.yaml (again create your username and password)

Do not create a file. Use the existing config file.

https://github.com/beefproject/beef/blob/master/config.yaml

> I found this but I was wondering how to make the password because its hard to understand it pls help

https://github.com/beefproject/beef/blob/82e4d36464874fe697355891caff1286c78a8d95/config.yaml#L21
