### ISSUE TITLE
Help with adding NGROK to beef

### ISSUE THREAD

**Issue by DannyBrock123** [beefproject/beef#2863]
Kali Linux VM (Ubuntu)
Lastest BeEF version 

I'm having issue connecting to Ngrok and it seems like there is too much going on, I tried editing the config.yaml but it just looked diffrenete to what others got and it made me confused. I need real hand help please

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

**Comment by DannyBrock123** [comment]
This don't help

**Comment by DannyBrock123** [comment]
Like 0%

**Comment by bcoles** [comment]
I don't care :)

**Comment by DannyBrock123** [comment]
That's great, never asked you to care anyways, and if you read that carefully, you could have seen me asking for a real hand help, which means online chat and stuff. There is crap that comes up every now and then. This crap don't go smoothly. Nothing does.

**Comment by bcoles** [comment]
If you're lucky someone on Discord will help https://discord.gg/HQZ3Z7zB
