### ISSUE TITLE
Invalid Public Hostname, Beef error with Ngrok Help plz

### ISSUE THREAD

**Issue by AliBahlol** [beefproject/beef#2872]
Browser Details ( Mozilla Firefox, Chrome):
Operating System (Kali Linux(rolling):

## Configuration

1. Have you made any changes to your BeEF configuration? Yes
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

1. BeEF was working fine on my local host.
 I watched a video to do it over WAN.
and changed Public Hostname in config.yaml to ngrok.io link which i got by ngrok http 3000.
After i did this I get this error:
  **Warning: System language $LANG '' does not appear to be UTF-8 compatible.
   [!] ERROR: Invalid public hostname: https://6c74-103-137-24-42.ngrok-free.app**

**Comment by bcoles** [comment]
Put the ngrok hostname not the URL.

**Comment by AliBahlol** [comment]
> Put the ngrok hostname not the URL.

Can you tell me where is the hostname so i can copy it.

**Comment by bcoles** [comment]
> > Put the ngrok hostname not the URL.
> 
> Can you tell me where is the hostname so i can copy it.

In the ngrok URL.


```
6c74-103-137-24-42.ngrok-free.app
```

**Comment by AliBahlol** [comment]
Thanks It worked
