### ISSUE TITLE
Hooked Browser not showing in Online Browser panel (Ngrok BeEF)

### ISSUE THREAD

**Issue by AliBahlol** [beefproject/beef#2873]
Browser Details (Mozilla ):
 Operating System (Kali Linux):

1. Have you made any changes to your BeEF configuration? Yes
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

I opened the UI panel and opened the hook link in another browser, i also tried opening link in another laptop. The link opens fine but there is no information in Online Browsers Panel.

![Capture](https://github.com/beefproject/beef/assets/66098853/2734db55-73b1-4280-b616-dcdc3aabc370)
 The left side of image is my chrome browser where I have opened Hooked link.
 The Right side is UI panel.

This is what is showing in terminal:
[*] BeEF server started (press control+c to stop)
2023-06-27 10:19:05 - ArgumentError - invalid byte sequence in US-ASCII:
        /var/lib/gems/3.1.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `scan'
        /var/lib/gems/3.1.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `convert_input'
        /var/lib/gems/3.1.0/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
        /var/lib/gems/3.1.0/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
        /home/alibahlol/tools/beef/core/main/handlers/modules/legacybeefjs.rb:104:in `new'
        /home/alibahlol/tools/beef/core/main/handlers/modules/legacybeefjs.rb:104:in `legacy_build_beefjs!'
        /home/alibahlol/tools/beef/core/main/handlers/hookedbrowsers.rb:138:in `block in <class:HookedBrowsers>'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `call'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `block in compile!'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (3 levels) in route!'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1037:in `route_eval'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (2 levels) in route!'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1068:in `block in process_route'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `catch'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `process_route'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1017:in `block in route!'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `each'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `route!'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1138:in `block in dispatch!'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1133:in `dispatch!'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `block in call!'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `call!'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:938:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.7/lib/rack/null_logger.rb:11:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.7/lib/rack/head.rb:12:in `call'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:219:in `call'
        /var/lib/gems/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:2018:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.7/lib/rack/urlmap.rb:74:in `block in call'
        /var/lib/gems/3.1.0/gems/rack-2.2.7/lib/rack/urlmap.rb:58:in `each'
        /var/lib/gems/3.1.0/gems/rack-2.2.7/lib/rack/urlmap.rb:58:in `call'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
        /var/lib/gems/3.1.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /var/lib/gems/3.1.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
        /home/alibahlol/tools/beef/core/main/server.rb:156:in `start'
        ./beef:278:in `<main>'

**Comment by bcoles** [comment]
Where did you get stuck during troubleshooting?

**Comment by AliBahlol** [comment]
I found the answer on stackoverflow,
I ran these commands and it worked:
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
bundle
