### ISSUE TITLE
NEED HELP WITH BEEF INSTALLING

### ISSUE THREAD

**Issue by cotne1233** [beefproject/beef#2885]
┌──(cotnessa㉿kali)-[~/Applications/beef]
└─$ bundle install
Using rake 13.0.6
Using concurrent-ruby 1.2.2
Using i18n 1.12.0
Using minitest 5.18.0
Using tzinfo 2.0.6
Using activesupport 7.0.4.3
Using activemodel 7.0.4.3
Using activerecord 7.0.4.3
Using ansi 1.5.0
Using ast 2.4.2
Using fiber-local 1.0.0
Using console 1.16.2
Using nio4r 2.5.8
Using timers 4.3.5
Using async 1.31.0
Using async-io 1.34.3
Using async-dns 1.3.0
Using bundler 2.4.8
Using daemons 1.4.1
Using unf_ext 0.0.8.2
Using unf 0.1.4
Using domain_name 0.5.20190701
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using em-websocket 0.5.3
Using erubis 2.7.0
Using espeak-ruby 1.1.0
Using execjs 2.8.1
Using hashie 5.0.0
Using hashie-forbidden_attributes 0.1.1
Using http-accept 1.7.0
Using http-cookie 1.0.5
Using json 2.6.3
Using language_server-protocol 3.17.0.3
Using maxmind-db 1.1.1
Using mime-types-data 3.2023.0218.1
Using mime-types 3.4.1
Using mojo_magick 0.6.7
Using msgpack 1.6.1
Using msfrpc-client 1.1.2
Using ruby2_keywords 0.0.5
Using mustermann 3.0.0
Using timeout 0.3.2
Using net-protocol 0.2.1
Using net-smtp 0.3.3
Using netrc 0.11.0
Using otr-activerecord 2.1.2
Using parallel 1.23.0
Using parseconfig 1.1.2
Using racc 1.7.1
Using parser 3.2.2.3
Using rqrcode_core 0.2.0
Using qr4r 0.6.1
Using rack 2.2.7
Using rack-protection 3.0.6
Using rainbow 3.1.1
Using regexp_parser 2.8.1
Bundler::GemNotFound: Could not find rest-client-2.1.0.gem for installation
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/source/rubygems.rb:159:in `install'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer/parallel_installer.rb:141:in `install_serially'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer/parallel_installer.rb:91:in `call'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer/parallel_installer.rb:67:in `call'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer.rb:244:in `install_in_parallel'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer.rb:201:in `install'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer.rb:89:in `block in run'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/process_lock.rb:12:in `block in lock'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/process_lock.rb:9:in `open'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/process_lock.rb:9:in `lock'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer.rb:71:in `run'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/installer.rb:23:in `install'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/cli/install.rb:62:in `run'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/cli.rb:261:in `block in install'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/settings.rb:131:in `temporary'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/cli.rb:260:in `install'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/cli.rb:34:in `dispatch'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/cli.rb:28:in `start'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/exe/bundle:45:in `block in <top (required)>'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /var/lib/gems/3.1.0/gems/bundler-2.4.8/exe/bundle:33:in `<top (required)>'
  /usr/local/bin/bundle:25:in `load'
  /usr/local/bin/bundle:25:in `<main>'

An error occurred while installing rest-client (2.1.0), and Bundler cannot continue.

In Gemfile:
  rushover was resolved to 0.3.0, which depends on
    rest-client

**Comment by bcoles** [comment]
```
gem install rest-client
```

**Comment by cotne1233** [comment]
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/local/bin directory.

**Comment by Pshock13** [comment]
"When in doubt, sudo"
`sudo gem install rest-client`

**Comment by siissioe123** [comment]
you manually install the gem: `sudo gem install rest-client`
