### ISSUE TITLE
BeEF is shutting down after error with procedure for using the web server behind NAT

### ISSUE THREAD

**Issue by siissioe123** [beefproject/beef#2888]
## Informations

BeEF Version: Running ./beef -v in /beef directory gives: version unknown
Ruby Version: 3.1.2p20
Browser Details: Firefox 115.0.3 (Mac), Firefox 115.0.2esr (Kali Linux)
Operating System: OSX Catalina 10.15.7 and Kali GNU/Linux Rolling 2023.2

## Configuration

I've done changes to BeEF configuration in the 'config.yaml' file inside beef directory and done the process to use BeEF outside NAT (port forwarding and changing host ip in config.yaml file from 0.0.0.0 to router's public ip adress

I haven't enabled or disabled BeEF extensions

## Steps to Reproduce

1. Opened terminal and wrote 'cd beef'
2. Inside beef directory wrote 'sudo su'  and put password
3. Once in super-user mode wrote './beef', beef started loading and after the confirm that the server is running there was an error: Another process is already listening on port 3000, or you're trying to bing BeEF to an invalid Ip. 
Is BeEF already running? exiting...

Then it closes itself

**Comment by bcoles** [comment]
> changing host ip in config.yaml file from 0.0.0.0 to router's public ip adress

Leave the `host` as `0.0.0.0`. Change the `public` settings as per https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
