### ISSUE TITLE
install wont run on my lubuntu machine?

### ISSUE THREAD

**Issue by d3k4-k3rb3r0s** [beefproject/beef#2904]
[install fails due to repository:

WARNING]  This script will install BeEF and its required dependencies (including operating system packages).
Are you sure you wish to continue (Y/n)? y
[INFO]  Detecting OS...
[INFO]  Operating System: Linux
[INFO]  Launching Linux install...
[INFO]  Detecting Linux OS distribution...
[INFO]  OS Distribution: Debian
[INFO]  Installing Debian prerequisite packages...
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 https://packages.microsoft.com/repos/vscode stable InRelease [3,573 B]                                                         
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                                    
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease                                        
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease                                           
Err:2 https://packages.microsoft.com/repos/vscode stable InRelease                   
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Ign:6 https://ppa.launchpadcontent.net/brightbox/ruby-ng/ubuntu jammy InRelease
Err:7 https://ppa.launchpadcontent.net/brightbox/ruby-ng/ubuntu jammy Release
  404  Not Found [IP: 2620:2d:4000:1::3e 443]
Reading package lists... Done                                  
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.microsoft.com/repos/vscode stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://ppa.launchpadcontent.net/brightbox/ruby-ng/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

???

**Comment by bcoles** [comment]
Your packages are broken.

You might not need them. Try installing Ruby gems:

```
bundle install
```

**Comment by d3k4-k3rb3r0s** [comment]
> bundle install

returns "Could not locate Gemfile"

**Comment by bcoles** [comment]
> > bundle install
> 
> returns "Could not locate Gemfile"

run from beef directory
