### ISSUE TITLE
help please!! many module not working

### ISSUE THREAD

**Issue by darkangel1010** [beefproject/beef#2921]
![Screenshot from 2023-09-03 14-04-55](https://user-images.githubusercontent.com/141255157/265254448-1419b9a2-b86e-436a-8625-90aaefb1f6d0.png)

**Comment by darkangel1010** [comment]
even screenshot module not working

**Comment by darkangel1010** [comment]
chrome extension all module get red light , how  to fix it,

**Comment by bcoles** [comment]
To understand the color coded icons, refer to the Getting Started tab when you first login to BeEF.
