### ISSUE TITLE
How to Use In Termux

### ISSUE THREAD

**Issue by vortexvi** [beefproject/beef#2941]
When I try to install BeEF in termux it shows multiple errors on multiple steps. Idk why it's shows like that. Now is there really a clear way how you can install and use BeEF on an Android phone using Termux? I Know that BeEF isn't officially supported by Termux but there might be a way to make it work on Termux and please let me know how to do it. I've read a lot of past issues regarding BeEF installation on Termux but those issues was opened way far back and have no Updates.

SO Please help me on how to install BeEF on an Android using Termux.

**Comment by stephenakq** [comment]
Thank you for raising this issue. You are correct and BeEF isn’t supported on Android using Termux. 

Which past Android issues are you referring to? 

Please join the BeEF discord to discuss the specific errors further. Someone there might have more experience https://discord.gg/ugmKmHarKc

**Comment by vortexvi** [comment]
With the gem sqlite3

**Comment by stephenakq** [comment]
Discussing in discord
