### ISSUE TITLE
BeEF only hooking on localhost.

### ISSUE THREAD

**Issue by naaaahTheDev** [beefproject/beef#2942]
![image](https://github.com/beefproject/beef/assets/107448004/58421b6d-34cf-4873-b108-204d896db779)
I have an issue, so my BeEF is running properly on the two IPs, one is my virtual machines IP which is bridged to my main PCs IP. However, when I try injecting a script into a vulnerable site with the IP it doesn't hook. However, when I hook with localhost 127.0.0.1 then it hooks just fine. Any idea why?

**Comment by bcoles** [comment]
Is the hooked origin HTTPS? Can the hooked browser route network traffic to the BeEF host? Are there errors in browser console?

**Comment by naaaahTheDev** [comment]
The hooked origin is HTTPS, there are no errors in the console. And, i was testing on the same HTTPS website with localhost.

**Comment by bcoles** [comment]
> The hooked origin is HTTPS, there are no errors in the console. And, i was testing on the same HTTPS website with localhost.

Modern web browsers do not permit HTTPS origins to load active mixed content, such as JavaScript, from HTTP origins.

**Comment by naaaahTheDev** [comment]
Ohh. Okay, so i have to setup my host to be on https?

**Comment by bcoles** [comment]
> Ohh. Okay, so i have to setup my host to be on https?

Yes, if you want to hook HTTPS origins. Most people either use a tunneling service like ngrok or a reverse proxy with a trusted HTTPS cert.

**Comment by stephenakq** [comment]
Closing because the question has been answered.
