### ISSUE TITLE
No Browsers visible in Hoocked Browsers tab

### ISSUE THREAD

**Issue by arch-il** [beefproject/beef#2947]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: 0.5.4.0
5. Ruby Version: 3.1.2p20
6. Browser Details (e.g. Chrome v81.0): Firefox
7. Operating System (e.g. OSX Catalina): Kali Linux (inside Oracle VM Virtualbox)

## Configuration

1. Have you made any changes to your BeEF configuration? Yes
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

I followed standard tutorial. Ran my ngrok and wrote details inside config file correctly. It is running without any errors and website is visible (even on other devices. But when I see demo page as I should, there are no hooked browsers visible in any way.

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by stephenakq** [comment]
Are you able to see hooked browsers when you run them on localhost?

**Comment by stephenakq** [comment]
Are you seeing any errors in the web console? https://screenful.com/guide/how-to/how-to-open-the-browser-developer-console

**Comment by stephenakq** [comment]
Assumed fixed due to no response. Please reopen for additional support.
