### ISSUE TITLE
Connection Refused Error for 172-105-51-237.ip.linodeusercontent.com

### ISSUE THREAD

**Issue by adityabhat20** [beefproject/beef#2956]
I'm trying to access the website at "172-105-51-237.ip.linodeusercontent.com" and am encountering a "Connection Refused" error. I'm using Linode and getting this error in Windows while accessing. Can anyone help me how to solve this issue? 

![Screenshot 2023-10-21 181630](https://github.com/beefproject/beef/assets/81157647/cb5552a3-a75b-4fc3-abcd-c8678fcae147)

![Screenshot 2023-10-21 182632](https://github.com/beefproject/beef/assets/81157647/66f56695-1e6c-4017-a120-18ac83f43ae1)

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc

**Comment by adityabhat20** [comment]
Yeah okay
