### ISSUE TITLE
beef-xss.service: Main process exited, code=exited, status=1/FAILURE

### ISSUE THREAD

**Issue by haxerr9** [beefproject/beef#2958]
Hello, i dont know if this was posted but i cant find if it was. im getting this issue ;

Im getting this error both on beef-xss and beef (github version)

![Screenshot_2023-10-25_18-50-58](https://github.com/beefproject/beef/assets/148996577/e6c8c984-e1c1-42c1-bc6b-095eb062aeb7)

![Screenshot_2023-10-25_19-15-27](https://github.com/beefproject/beef/assets/148996577/50e9b149-fc73-4a67-9918-2352ea6db2c3)

**Comment by cangover06** [comment]
Did you find the solution to the error?

**Comment by haxerr9** [comment]
> Did you find the solution to the error?

nah, not yet. No one is here for 2 days

**Comment by cangover06** [comment]
Did you find a solution?

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
