### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by Exript** [beefproject/beef#2960]
Hello,

I'm encountering the following error when trying to run the "beef" program:

Error: /var/lib/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/migration.rb:1411:in `initialize': wrong number of arguments (given 3, expected 4..5) (ArgumentError)

The issue seems to be that the "beef" program is experiencing an incompatibility with the ActiveRecord version, even though I've confirmed that the versions match using the gem list command. I'm still getting this error.

How can I resolve this issue?

**Comment by cangover06** [comment]
Did you find a solution?

**Comment by Exript** [comment]
No, unfortunately I couldn't find it, but you can use beef-xss until the problem is solved.

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc

**Comment by stephenakq** [comment]
Here is a workaround https://github.com/beefproject/beef/issues/2954
