### ISSUE TITLE
How to host Beef on godaddy buyed domain?

### ISSUE THREAD

**Issue by 000Andrew000** [beefproject/beef#2962]
Sum reply

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#can-i-use-a-domain-name-instead-of-ip-address-for-the-beef-hook

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
