### ISSUE TITLE
argument error

### ISSUE THREAD

**Issue by hackwell2** [beefproject/beef#2964]
/var/lib/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/migration.rb:1411:in 'initialize' : wrong number of arguments (given3 , expected 4.. 5) (error)

im running beef this is the issue that its been showing

**Comment by stephenakq** [comment]
Should be fixed in https://github.com/beefproject/beef/commit/e0ff71a5829d08b51d5beec1683c260cce69c76b

**Comment by hackwell2** [comment]
What should i do brother
