### ISSUE TITLE
The "Tunneling Proxy" feature is not working; I tried for the entire night but couldn't resolve it :(

### ISSUE THREAD

**Issue by xiaobai40009** [beefproject/beef#2973]
I recently started using BeEF and installed BeEF v0.5.4.0 on Kali. Overall, it feels good, but I found that the "Tunneling Proxy" feature is not working. I tried for a whole night but couldn't solve it, which is very disappointing. I strictly followed the BeEF tutorial but still couldn't resolve this issue. Upon inspection, BeEF has already opened port 6789 locally, but it seems that it is not forwarding proxy requests to the "victim" browser. The "Forget Request" feature works fine. I hope this issue can be resolved as soon as possible.

**Comment by bcoles** [comment]
> I strictly followed the BeEF tutorial 

Which tutorial?

There is not enough information to reproduce or diagnose this issue.

Where did you get stuck during troubleshooting?

What errors do you get in terminal?

What errors do you get in the web browser console?

Do you see network requests generated in the Network tab in the browser developer tools.

How were you trying to send HTTP requests via the proxy?

**Comment by bcoles** [comment]
Looks like the proxy is currently broken.

```
[10:19:26][*] New Hooked Browser [id:1, ip:192.168.200.132, browser:UNKNOWN-119.0, os:Linux-], hooked domain [192.168.200.130:3000]
#<Thread:0x00007f20622b2bc0 /root/Desktop/beef/extensions/proxy/proxy.rb:53 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/3.1.0/openssl/buffering.rb:80:in `sysread': SSL session is not started yet (OpenSSL::SSL::SSLError)
        from /usr/lib/ruby/3.1.0/openssl/buffering.rb:80:in `fill_rbuff'
        from /usr/lib/ruby/3.1.0/openssl/buffering.rb:332:in `eof?'
        from /usr/lib/ruby/3.1.0/openssl/buffering.rb:285:in `readline'
        from /root/Desktop/beef/extensions/proxy/proxy.rb:54:in `handle_request'
```

**Comment by stephenakq** [comment]
@xiaobai40009 Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc

**Comment by stephenakq** [comment]
@xiaobai40009 please discuss on discord and we'll provide assistance there
