### ISSUE TITLE
Rake

### ISSUE THREAD

**Issue by AnonymousRonin** [beefproject/beef#2981]
An error occurred while installing rake (13.1.0), and Bundler cannot continue.

In Gemfile:
  rake

The only thing I could spot was in the Gemfile I changed it from 13.0 > 13.1.0 .  Other than that I have no idea.

**Comment by stephenakq** [comment]
Thank you for taking the time to create this GitHub issue! Your feedback helps us make BeEF awesome. We're on it and will get back to you. If you have more details to add, feel free to share.

You can also join our Discord server, and someone might be able to help there.
https://discord.gg/ugmKmHarKc

**Comment by stephenakq** [comment]
@AnonymousRonin this is in the queue

**Comment by espero-dev** [comment]
i got the same issue on latest kali linux

**Comment by xenostructure** [comment]
This issue has been stale for nearly 3 months. It's late February and this is still an issue. Is everything okay over at Beef Project?

**Comment by xenostructure** [comment]
> @xenostructure this ticket was also closed 3 months ago, are you also seeing this issue?

Yes, the same error. Sorry, I didn't notice it was closed.

**Comment by xenostructure** [comment]
@stephenakq Here's my output, if it's useful for you. 

`:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                     [#########] 100%
(2/2) checking package integrity                   [#########] 100%
(2/2) loading package files                        [#########] 100%
(2/2) checking for file conflicts                  [#########] 100%
(2/2) checking available disk space                [#########] 100%
:: Processing package changes...
(1/2) reinstalling ruby-rdoc                       [#########] 100%
(2/2) reinstalling ruby                            [#########] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 3.0.6 is installed
[INFO]  Detecting bundler gem...
[INFO]  bundler gem is installed
Installing required Ruby gems...
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler::PermissionError: There was an error while trying to write
to `/usr/lib/ruby/gems/3.0.0/cache`. It is likely that you need to
grant write permissions for that path.
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:105:in `rescue
in filesystem_access'
/usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:102:in
`filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:446:in `fetch_gem'
/usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:433:in
`fetch_gem_if_possible'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:162:in `install'
/usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in
`install'
/usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:132:in
`do_install'
/usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:86:in
`call'
/usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:66:in
`call'
/usr/lib/ruby/3.0.0/bundler/installer.rb:244:in
`install_in_parallel'
  /usr/lib/ruby/3.0.0/bundler/installer.rb:201:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer.rb:89:in `block in run'
/usr/lib/ruby/3.0.0/bundler/process_lock.rb:19:in `rescue in
lock'
  /usr/lib/ruby/3.0.0/bundler/process_lock.rb:15:in `lock'
  /usr/lib/ruby/3.0.0/bundler/installer.rb:71:in `run'
  /usr/lib/ruby/3.0.0/bundler/installer.rb:23:in `install'
  /usr/lib/ruby/3.0.0/bundler/cli/install.rb:63:in `run'
  /usr/lib/ruby/3.0.0/bundler/cli.rb:244:in `block in install'
  /usr/lib/ruby/3.0.0/bundler/settings.rb:158:in `temporary'
  /usr/lib/ruby/3.0.0/bundler/cli.rb:243:in `install'
/usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:28:in
`run'
/usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in
`invoke_command'
/usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:527:in
`dispatch'
  /usr/lib/ruby/3.0.0/bundler/cli.rb:34:in `dispatch'
/usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:584:in
`start'
  /usr/lib/ruby/3.0.0/bundler/cli.rb:28:in `start'
/usr/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:28:in
`block in <top (required)>'
/usr/lib/ruby/3.0.0/bundler/friendly_errors.rb:117:in
`with_friendly_errors'
/usr/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:20:in
`<top (required)>'
  /usr/bin/bundle:25:in `load'
  /usr/bin/bundle:25:in `<main>'

An error occurred while installing rake (13.1.0), and
Bundler cannot continue.

In Gemfile:
  rake`

**Comment by GigelJmekkeru** [comment]
just sudo ./install instead of just ./install

**Comment by alewanas** [comment]
if you face rake error make sure you are in directory of beef ! then type su for root permission enter your password of root and agin run ./install command you cant face problem

**Comment by napSec** [comment]
> just sudo ./install instead of just ./install

this worked for me and it just so happen i was searching for it at the right time. 

Thanks!

**Comment by Adl111** [comment]
> just sudo ./install instead of just ./install

This actually work for me

**Comment by toing543** [comment]
jan 2025, works for me too. thanks.

**Comment by diegoespindola** [comment]
Dec 2025, still working, thanks

**Comment by Xploit0-0** [comment]
i did sudo ./install and it worked
