### ISSUE TITLE
 172.17.0.1 took too long to respond (ERR_CONNECTION_TIMED_OUT)

### ISSUE THREAD

**Issue by yassin819** [beefproject/beef#2993]
guys pls help me i have an hours trying to solve this issue and i didn't!!!

my hook an ui links aren't accessable even i tried to change port from 3000 to 80 ,or to 443 ,nothing happen it still the same as the photo
PLS IF ANYONE CAN HELP ME PLS DO SO ,BEC IAM BEGINNER
<img width="960" alt="Screenshot 2023-12-24 020529" src="https://github.com/beefproject/beef/assets/68121400/3d35b9b4-b1f4-4fb8-9e75-cc81036da6ef">

**NOTE:: IAM USING GOOGLE SHELL**

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
