### ISSUE TITLE
i cant use gem bundler installation step - bundle install

### ISSUE THREAD

**Issue by shan978** [beefproject/beef#2998]
this error will came continous ----please guide 
Fetching gem metadata from https://rubygems.org/........
Bundler::GemNotFound: Could not find http-cookie-1.0.5.gem for installation
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/source/rubygems.rb:163:in `install'                                                                                                                                                   
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.1.0/gems/bundler-2.5.3/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing http-cookie (1.0.5), and Bundler cannot continue.

In Gemfile:
  rushover was resolved to 0.3.0, which depends on
    rest-client was resolved to 2.1.0, which depends on
      http-cookie

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
