### ISSUE TITLE
Beef-xss wuth public ip

### ISSUE THREAD

**Issue by racsou** [beefproject/beef#3005]
# I have problem with runing beef-xss with my public ip address

# here is my config.yaml:
![Screenshot from 2024-01-12 12-00-41](https://github.com/beefproject/beef/assets/120835349/ec75511a-a91b-4a85-8b4a-00b48355f60a)

![Screenshot from 2024-01-12 12-01-20](https://github.com/beefproject/beef/assets/120835349/518bb885-bd62-4bf5-b32b-d6d62f35b77f)

## here is my iptables forwading :

# sudo iptables -t nat --line-numbers -L

"

num target prot opt source destination

1 DNAT tcp -- anywhere anywhere tcp dpt:https to:192.168.1.14:443

2 DNAT tcp -- anywhere anywhere tcp dpt:4444 to:192.168.1.14:4444

3 DNAT tcp -- anywhere anywhere tcp dpt:postgresql to:192.168.1.14:5432

4 DNAT tcp -- anywhere anywhere tcp dpt:55552 to:192.168.1.14:55552

5 DNAT tcp -- anywhere anywhere tcp dpt:3001 to:192.168.1.14:3000

6 DNAT tcp -- anywhere anywhere tcp dpt:http to:192.168.1.14:8080

7 DNAT tcp -- anywhere anywhere tcp dpt:ftp to:192.168.1.14:2121

"

# Router forwading:

router forwading is the same

# terminal :
![Screenshot from 2024-01-12 11-40-57](https://github.com/beefproject/beef/assets/120835349/43fd127d-4f19-4b6a-97a5-1090cfefa0cf)

brwser : 
![Screenshot from 2024-01-12 11-52-11](https://github.com/beefproject/beef/assets/120835349/4396a80d-aa3e-4b4c-acb5-69f50d5f364e)

**Comment by stephenakq** [comment]
beef-xss is a kali package is not supported here. Doing a "service beef-xss restart" and then a "beef-xss framework" might help. You can try https://github.com/beefproject/beef/wiki/Installation
