### ISSUE TITLE
BeEF problems on Linode/Akamai Cloud

### ISSUE THREAD

**Issue by VanillaZillaa** [beefproject/beef#3042]
Hey, so one I'm quite new to ethical hacking and what not, and so I've been trying to set up beef on linode, but when i go through the setup process on linode, it never gives me the option to make a password for the admin account. I've looked at the guide for it online on linode's website and it says to provide a password as pretty much the first step. So I've been trying to get the credentials by typing `cat /root/beef.info` 
Please someone help I don't exactly know what I'm doing. Thank you!

Cheers,
Maximus

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc*
