### ISSUE TITLE
Cant type in password

### ISSUE THREAD

**Issue by gvando** [beefproject/beef#3062]
Soo im using kali linux and when i use beef start it asks for a password but i cant type in there. Any solution?![IMG-20240416-WA0007(2).jpg](https://github.com/beefproject/beef/assets/167110117/fb138a1a-2572-41d4-b17b-eb614263940c)

**Comment by gvando** [comment]
Soo theres that white space and i cant enter nothing

**Comment by mathenz** [comment]
Hello.

It is asking for your sudo password. That "white space" is the shape of your cursor, which is a block.
