### ISSUE TITLE
HTTPS Isue

### ISSUE THREAD

**Issue by furure-software** [beefproject/beef#3067]
I have the beef script included in a website, but the counsel outputs an error saying that the requested script is insecure. Any help?

**Comment by bcoles** [comment]
Modern web browsers refuse to load JavaScript resources on HTTPS pages from HTTP sources. As such, you will need to either enable HTTPS or host BeEF behind a HTTPS reverse proxy.

Note that if you enable HTTPS you must use a valid certificate signed by a trusted certificate authority. Self-signed certificates are not trusted. Web browsers will not connect.

**Comment by furure-software** [comment]
> Modern web browsers refuse to load JavaScript resources on HTTPS pages from HTTP sources. As such, you will need to either enable HTTPS or host BeEF behind a HTTPS reverse proxy.
> 
> Note that if you enable HTTPS you must use a valid certificate signed by a trusted certificate authority. Self-signed certificates are not trusted. Web browsers will not connect.

Hi, thanks! So if I just set httpsto true on config.yaml it will work as https?

**Comment by bcoles** [comment]
> Hi, thanks! So if I just set https to true on config.yaml it will work as https?

That will enable HTTPS using the default self-signed certificate. Browsers won't trust this certificate. You will need to use a trusted certificate. Alternatively, host BeEF behind a HTTPS front end reverse proxy and set the appropriate public host/port: https://github.com/beefproject/beef/wiki/FAQ#can-i-use-a-domain-name-instead-of-ip-address-for-the-beef-hook

**Comment by furure-software** [comment]
> > Hi, thanks! So if I just set https to true on config.yaml it will work as https?
> 
> That will enable HTTPS using the default self-signed certificate. Browsers won't trust this certificate. You will need to use a trusted certificate. Alternatively, host BeEF behind a HTTPS front end reverse proxy and set the appropriate public host/port: https://github.com/beefproject/beef/wiki/FAQ#can-i-use-a-domain-name-instead-of-ip-address-for-the-beef-hook

Ok, awsome! Do you know how I can get a trusted certificate?
