### ISSUE TITLE
Refused to connect

### ISSUE THREAD

**Issue by jns858** [beefproject/beef#3068]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: latest (i think)
5. Ruby Version: latest (i think)
6. Browser Details (e.g. Chrome v81.0): chrome
7. Operating System (e.g. OSX Catalina): windows

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No no
2. Have you enabled or disabled any BeEF extensions? Yes/No no

## Summary 
i am running kali linux (the live version) on my machine off a usb. When i access the hook url from kali it works just fine, but when i access it through my laptop (windows 11, chrome) i get an error saying it refused to connect
![Screenshot 2024-04-23 220852](https://github.com/beefproject/beef/assets/149912988/427efd3c-e812-414f-893b-87fde8584035)

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
Use an IP address for one of the local area network adapters, not the loopback adapter (`127.0.0.1`).

BeEF prints the available IP addresses to terminal upon startup.

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc*
