### ISSUE TITLE
cant start ui site

### ISSUE THREAD

**Issue by Zlaze** [beefproject/beef#3076]
so when i start the beef-xss (in root terminal) i get this error: "GeoIP database is missing
[i] Run geoipupdate to download / update Maxmind GeoIP database
[*] Please wait for the BeEF service to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI: http://127.0.0.1:3000/ui/panel
[*]    Hook: <script src="http://<IP>:3000/hook.js"></script>
[*] Example: <script src="http://127.0.0.1:3000/hook.js"></script>

× beef-xss.service - beef-xss
     Loaded: loaded (/usr/lib/systemd/system/beef-xss.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Fri 2024-05-03 06:46:58 EDT; 3s ago
   Duration: 1.875s
    Process: 40327 ExecStart=/usr/share/beef-xss/beef (code=exited, status=1/FAILURE)
   Main PID: 40327 (code=exited, status=1/FAILURE)
        CPU: 1.869s

May 03 06:46:58 kali beef[40327]:    -> 0.0076s
May 03 06:46:58 kali beef[40327]: [ 6:46:58][*] BeEF is loading. Wait a few seconds...
May 03 06:46:58 kali beef[40327]: [ 6:46:58][!] [AdminUI] Error: Could not minify 'BeEF::Extension::AdminUI::API::Handler' JavaScript file: Invalid option: harmony
May 03 06:46:58 kali beef[40327]: [ 6:46:58]    |_  [AdminUI] Ensure nodejs is installed and `node' is in `$PATH` !
May 03 06:46:58 kali beef[40327]: [ 6:46:58][!] [AdminUI] Error: Could not minify 'BeEF::Extension::AdminUI::API::Handler' JavaScript file: Invalid option: harmony
May 03 06:46:58 kali beef[40327]: [ 6:46:58]    |_  [AdminUI] Ensure nodejs is installed and `node' is in `$PATH` !
May 03 06:46:58 kali beef[40327]: [ 6:46:58][!] Database connection failed: SQLite3::ReadOnlyException: attempt to write a readonly database
May 03 06:46:58 kali systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
May 03 06:46:58 kali systemd[1]: beef-xss.service: Failed with result 'exit-code'.
May 03 06:46:58 kali systemd[1]: beef-xss.service: Consumed 1.869s CPU time.

[*] Opening Web UI (http://127.0.0.1:3000/ui/panel) in: 5... 4... 3... 2... 1... 
"

i have apache2 running and i have been tring to fix the error for 3 hours I need help!

**Comment by bcoles** [comment]
> so when i start the beef-xss (in root terminal) i get this error: "GeoIP database is missing

That is a warning message and can be ignored.

> May 03 06:46:58 kali beef[40327]: [ 6:46:58][!] Database connection failed: SQLite3::ReadOnlyException: attempt to write a readonly database

Your `beef.db` database is not writable.

> May 03 06:46:58 kali beef[40327]: [ 6:46:58][!] [AdminUI] Error: Could not minify 'BeEF::Extension::AdminUI::API::Handler' JavaScript file: Invalid option: harmony

It is failing on this line:

https://github.com/beefproject/beef/blob/6d1c3c3a31c1600651e417526ed019c3127c1432/extensions/admin_ui/api/handler.rb#L36

Perhaps the library has changed and no longer supports `harmony`.

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc*

**Comment by Zlaze** [comment]
> > so when i start the beef-xss (in root terminal) i get this error: "GeoIP database is missing
> 
> That is a warning message and can be ignored.
> 
> > May 03 06:46:58 kali beef[40327]: [ 6:46:58][!] Database connection failed: SQLite3::ReadOnlyException: attempt to write a readonly database
> 
> Your `beef.db` database is not writable.
> 
> > May 03 06:46:58 kali beef[40327]: [ 6:46:58][!] [AdminUI] Error: Could not minify 'BeEF::Extension::AdminUI::API::Handler' JavaScript file: Invalid option: harmony
> 
> It is failing on this line:
> 
> https://github.com/beefproject/beef/blob/6d1c3c3a31c1600651e417526ed019c3127c1432/extensions/admin_ui/api/handler.rb#L36
> 
> Perhaps the library has changed and no longer supports `harmony`.

What do you mean with doesn't support harmony?
