### ISSUE TITLE
UI doesn't load after authentification

### ISSUE THREAD

**Issue by FunnyLoaf** [beefproject/beef#3086]
## First Steps
I am trying to log into my ui panel, but after logging in with no errors on client, It just loads the auth page again.

## Configuration

1. Have you made any changes to your BeEF configuration? Only password and username
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

IDK

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by FunnyLoaf** [comment]
I am getting this repetively(not after auth, but at different times):
#<Thread:0x00007f9c23f4e860 /workspaces/beef/extensions/proxy/proxy.rb:53 run> terminated with exception (report_on_exception is true):
/usr/local/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:80:in `sysread': SSL session is not started yet (OpenSSL::SSL::SSLError)
        from /usr/local/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:80:in `fill_rbuff'
        from /usr/local/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:332:in `eof?'
        from /usr/local/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/openssl/buffering.rb:285:in `readline'
        from /workspaces/beef/extensions/proxy/proxy.rb:54:in `handle_request'

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc*

**Comment by FunnyLoaf** [comment]
Will do. This is my first time checking this, sorry.

**Comment by FunnyLoaf** [comment]
Enabling reverse proxy fixed it, #2527
