### ISSUE TITLE
can't install BeEF

### ISSUE THREAD

**Issue by Eroxaoryrt8** [beefproject/beef#3095]
4. BeEF Version:  0.5.4.0
5. Ruby Version: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-gnu]
6. Browser Details (e.g. Chrome v81.0): google chrome, firefox, edge...
7. Operating System (e.g. OSX Catalina): linux: ubuntu 20.04

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No: Yes, changed the username and password
2. Have you enabled or disabled any BeEF extensions? Yes/No: No

## Steps to Reproduce

when I tried to install beef (./install) after I changed username and password I got this error: 
_```
_[WARNING]  This script will install BeEF and its required dependencies (including operating system packages).
Are you sure you wish to continue (Y/n)? Y
[INFO]  Detecting OS...
[INFO]  Operating System: Linux
[INFO]  Launching Linux install...
[INFO]  Detecting Linux OS distribution...
[INFO]  OS Distribution: Debian
[INFO]  Installing Debian prerequisite packages...
Hit:1 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://be.archive.ubuntu.com/ubuntu noble InRelease                                        
Hit:3 http://be.archive.ubuntu.com/ubuntu noble-updates InRelease                                
Hit:4 http://be.archive.ubuntu.com/ubuntu noble-backports InRelease                              
Ign:5 https://ppa.launchpadcontent.net/brightbox/ruby-ng/ubuntu noble InRelease
Hit:6 http://be.archive.ubuntu.com/ubuntu noble-proposed InRelease  
**Err:7 https://ppa.launchpadcontent.net/brightbox/ruby-ng/ubuntu noble Release
  404  Not Found [IP: 185.125.190.80 443]**
Hit:8 http://security.ubuntu.com/ubuntu noble-security InRelease
Reading package lists... Done
**E: The repository 'https://ppa.launchpadcontent.net/brightbox/ruby-ng/ubuntu noble Release' does not have a Release file.**
**N: Updating from such a repository can't be done securely, and is therefore disabled by default.**
**N: See apt-secure(8) manpage for repository creation and user configuration details._**
```_

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
