### ISSUE TITLE
people other than the host machine cant open hook beef itself is working and I have made changes to config, I ran install script, which ran fine so did launching beef but no one but I can accsess 

### ISSUE THREAD

**Issue by trampoline2259** [beefproject/beef#3108]
people other than the host machine cant open hook beef itself is working and I have made changes to config, I ran install script, which ran fine so did launching beef but no one but I can access

**Comment by trampoline2259** [comment]
pls help

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
