### ISSUE TITLE
it cant connect from a virtual machine to my laptop :(

### ISSUE THREAD

**Issue by gameboy87865** [beefproject/beef#3109]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: Latest
5. Ruby Version: 3.1.2p20
6. Browser Details Latest chrome
7. Operating System windows 11 home

## Configuration

1. Have you made any changes to your BeEF configuration? No 
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

just copy the text from the virtual machine and paste it onto your real computer and it does not work

![Screenshot 2024-07-13 192908](https://github.com/user-attachments/assets/29070118-2884-45fd-9cd0-07165ce64d4d)
![Screenshot 2024-07-13 193155](https://github.com/user-attachments/assets/9863f7ea-9ad4-40ad-9925-592de6673ca1)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
