### ISSUE TITLE
cannot load such file -- mize (LoadError) Did you mean?  mime

### ISSUE THREAD

**Issue by elmelali** [beefproject/beef#3120]
┌──(kali㉿kali)-[~/beef]
└─$ ./beef
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- mize (LoadError)
Did you mean?  mime
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /var/lib/gems/3.1.0/gems/term-ansicolor-1.11.1/lib/term/ansicolor.rb:3:in `<top (required)>'
        from /var/lib/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/runtime.rb:60:in `require'
        from /var/lib/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /var/lib/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/runtime.rb:55:in `each'
        from /var/lib/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/runtime.rb:55:in `block in require'
        from /var/lib/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/runtime.rb:44:in `each'
        from /var/lib/gems/3.1.0/gems/bundler-2.5.17/lib/bundler/runtime.rb:44:in `require'
        from /var/lib/gems/3.1.0/gems/bundler-2.5.17/lib/bundler.rb:212:in `require'
        from /home/kali/beef/core/loader.rb:16:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from ./beef:45:in `<main>'

**Comment by dalca-cloud** [comment]
Its happen the same with me. Someone knows how to fix it?

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc

**Comment by eescanilla** [comment]
hello!!!

for this error you edit  nano /var/lib/gems/3.0.0/gems/term-ansicolor-1.11.1/lib/term/ansicolor.rb

and delete requiere 'mize'

and ./beef

mize is deprecated librery

https://github.com/flori/term-ansicolor/pull/42/commits/571a0fb333fe451dead9907a6d397969e705cafa
GitHub
fix: Remove stale import for mize by BasitAli · Pull Request #42 ...
Fixes #41
GitHub
[fix: Remove stale import for `mize` by BasitAli · Pull Request #42 ...](https://github.com/flori/term-ansicolor/pull/42/commits/571a0fb333fe451dead9907a6d397969e705cafa)
Fixes #41
fix: Remove stale import for `mize` by BasitAli · Pull Request #42 ...

**Comment by dalca-cloud** [comment]
> hello!!!
> 
> for this error you edit nano /var/lib/gems/3.0.0/gems/term-ansicolor-1.11.1/lib/term/ansicolor.rb
> 
> and delete requiere 'mize'
> 
> and ./beef
> 
> mize is deprecated librery
> 
> [flori/term-ansicolor@571a0fb](https://github.com/flori/term-ansicolor/commit/571a0fb333fe451dead9907a6d397969e705cafa) GitHub fix: Remove stale import for mize by BasitAli · Pull Request #42 ... Fixes #41 GitHub [fix: Remove stale import for `mize` by BasitAli · Pull Request #42 ...](https://github.com/flori/term-ansicolor/pull/42/commits/571a0fb333fe451dead9907a6d397969e705cafa) Fixes #41 fix: Remove stale import for `mize` by BasitAli · Pull Request #42 ...

Thank you sir. But when I save it, the document turn back with 'Mize', seems like i needed a administrador permission :c

**Comment by dalca-cloud** [comment]
> hello!!!
> 
> for this error you edit nano /var/lib/gems/3.0.0/gems/term-ansicolor-1.11.1/lib/term/ansicolor.rb
> 
> and delete requiere 'mize'
> 
> and ./beef
> 
> mize is deprecated librery
> 
> [flori/term-ansicolor@571a0fb](https://github.com/flori/term-ansicolor/commit/571a0fb333fe451dead9907a6d397969e705cafa) GitHub fix: Remove stale import for mize by BasitAli · Pull Request #42 ... Fixes #41 GitHub [fix: Remove stale import for `mize` by BasitAli · Pull Request #42 ...](https://github.com/flori/term-ansicolor/pull/42/commits/571a0fb333fe451dead9907a6d397969e705cafa) Fixes #41 fix: Remove stale import for `mize` by BasitAli · Pull Request #42 ...

Thankyouuuuu sir. Its resolved for me <3

**Comment by dogukanma** [comment]
> hello!!!
> 
> for this error you edit nano /var/lib/gems/3.0.0/gems/term-ansicolor-1.11.1/lib/term/ansicolor.rb
> 
> and delete requiere 'mize'
> 
> and ./beef
> 
> mize is deprecated librery
> 
> [flori/term-ansicolor@571a0fb](https://github.com/flori/term-ansicolor/commit/571a0fb333fe451dead9907a6d397969e705cafa) GitHub fix: Remove stale import for mize by BasitAli · Pull Request #42 ... Fixes #41 GitHub [fix: Remove stale import for `mize` by BasitAli · Pull Request #42 ...](https://github.com/flori/term-ansicolor/pull/42/commits/571a0fb333fe451dead9907a6d397969e705cafa) Fixes #41 fix: Remove stale import for `mize` by BasitAli · Pull Request #42 ...

Thank you so much, I spent a lot of time but couldn't fix it until I see your comment.
