### ISSUE TITLE
beef panel loading slow

### ISSUE THREAD

**Issue by whatSchoolNahIbreakchromebooks** [beefproject/beef#3131]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: newest
5. Ruby Version: default
6. Browser Details Chrome v81.0
7. Operating System debian

## Configuration

1. Have you made any changes to your BeEF configuration? yes changing config.yaml default password and the HTTP server port to use HTTP (port 80)
2. Have you enabled or disabled any BeEF extensions? no

## Steps to Reproduce

1 started using sudo ./beef (needed sudo to use port 80)
2 went to http://xxxxxxxx/ui/panel (were it was hosted)
3 loading slow

## loading slow when hosted on Amazon was EC2 instance
so I loaded and install beef and it was slow
and its only the panel (/ui/panel)

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by FunnyCorgi** [comment]
beef is configured for 3000 by default try that and see if it works for you.
also try enabling reverse proxy if this doesn't fix it(with both port 80 and 3000)

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
