### ISSUE TITLE
ArgumentError - invalid byte sequence in US-ASCII:

### ISSUE THREAD

**Issue by MedusaPBT** [beefproject/beef#3138]
[18:47:25][*] BeEF server started (press control+c to stop)
2024-09-02 18:47:35 - ArgumentError - invalid byte sequence in US-ASCII:
        /var/lib/gems/3.1.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `scan'
        /var/lib/gems/3.1.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `convert_input'
        /var/lib/gems/3.1.0/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
        /var/lib/gems/3.1.0/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
        /root/beef/core/main/handlers/modules/legacybeefjs.rb:104:in `new'
        /root/beef/core/main/handlers/modules/legacybeefjs.rb:104:in `legacy_build_beefjs!'
        /root/beef/core/main/handlers/hookedbrowsers.rb:138:in `block in <class:HookedBrowsers>'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1775:in `call'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1775:in `block in compile!'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1065:in `block (3 levels) in route!'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1083:in `route_eval'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1065:in `block (2 levels) in route!'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1114:in `block in process_route'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1112:in `catch'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1112:in `process_route'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1063:in `block in route!'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1060:in `each'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1060:in `route!'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1184:in `block in dispatch!'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1155:in `catch'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1155:in `invoke'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1179:in `dispatch!'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:995:in `block in call!'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1155:in `catch'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1155:in `invoke'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:995:in `call!'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:984:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.9/lib/rack/null_logger.rb:11:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.9/lib/rack/head.rb:12:in `call'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:219:in `call'
        /var/lib/gems/3.1.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:2086:in `call'
        /var/lib/gems/3.1.0/gems/rack-2.2.9/lib/rack/urlmap.rb:74:in `block in call'
        /var/lib/gems/3.1.0/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `each'
        /var/lib/gems/3.1.0/gems/rack-2.2.9/lib/rack/urlmap.rb:58:in `call'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
        /var/lib/gems/3.1.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /var/lib/gems/3.1.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
        /var/lib/gems/3.1.0/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
        /root/beef/core/main/server.rb:156:in `start'
        ./beef:281:in `<main>'
how to fix it

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
