### ISSUE TITLE
Redirects from domain to local ip

### ISSUE THREAD

**Issue by oie1** [beefproject/beef#3143]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: 0.5.4.0
5. Ruby Version: 3.1.0
6. Browser Details (e.g. Chrome v81.0): Microsoft Edge Version 128.0.2739.79 (Official build) (64-bit)
7. Operating System (e.g. OSX Catalina): Arch Linux with KDE

## Configuration

1. Have you made any changes to your BeEF configuration? Yes
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

1. enable reverse proxy and configure public section in config.yaml
2. reverse proxy with nginx to beef
3. open the reverse proxied url, ex beef.domain.tld, it will redirect to ex 10.0.0.120:3000 ip

**Comment by QXIoa** [comment]
Possibly try apache or caddy fr reverse proxying to beef, that may be the issue.

**Comment by oie1** [comment]
issue was something else, not beef, and no it wasnt that I was using nginx @QXIoa

**Comment by QXIoa** [comment]
Ah I see
