### ISSUE TITLE
Network Hosts/Services is broken

### ISSUE THREAD

**Issue by Phasip** [beefproject/beef#3174]
## Summary
The network hosts and network services lists in the admin UI are broken and will not show newly added items.

## Steps to Reproduce
1. Run beef on same host as hooked browser
2. Do a cors scan for port 3000
3. Beef service is detected on port 3000 using cors scan
4. Beef service does not appear in the network services tab

**Comment by zinduolis** [comment]
Hi @Phasip , could you please help me reproduce the issue? What OS and browser and browser version are you using? 

My understanding is that you have executed Cross-Origin Scanner(CORS) from Network folder. Could you please advise how you filled the fields (it can be screenshot)?

Thanks

**Comment by Phasip** [comment]
Attached are two screenshots, first on how to perform the scan and second on the exception thrown.
Note that a pull request to fix this is here: https://github.com/beefproject/beef/pull/3175

![cors_scan_test_setup](https://github.com/user-attachments/assets/35434b60-cd46-49a6-8bea-5421a5dcf7f1)
![cors_scan_error](https://github.com/user-attachments/assets/d572d232-98a0-40e3-8a99-f83b6cadf862)

**Comment by zinduolis** [comment]
Hi @Phasip, unfortunately, the above screenshots do not show all the steps you're doing and what issue you're getting. Also, I don't know what OS and Browser and Browser version you're using. I need this information to reproduce the issue. Thanks for your collaboration.

**Comment by bcoles** [comment]
> Hi @Phasip, unfortunately, the above screenshots do not show all the steps you're doing and what issue you're getting. Also, I don't know what OS and Browser and Browser version you're using. I need this information to reproduce the issue. Thanks for your collaboration.

1. Hook a Firefox browser on localhost
2. Login to the web UI
3. Select the Current Browser tab
4. Select the Network tab
5. Select the Hosts Tab
6. Right-click the `127.0.0.1` host created by default
7. Select CORS scan and enter `3000` as the port
