### ISSUE TITLE
BeEF not working with linode.

### ISSUE THREAD

**Issue by xavs099** [beefproject/beef#3179]
I'm running lindoes version of beef (pretty sure its up to date) and whenever I do the installation it does it but cat /root/beef.info says beef doesn't exist?

1. Have you made any changes to your BeEF configuration? No
2. Have you enabled or disabled any BeEF extensions? No

![image_2024-10-25_121830001](https://github.com/user-attachments/assets/3af253c7-2f52-47ad-9893-ff9923750bae)

**Comment by bcoles** [comment]
The documentation says to view `/root/beef.info` to find the URL for BeEF. You should be able to find the IP address yourself. (with `ip a` or `ifconfig`).

**Comment by xavs099** [comment]
> The ip for the server is 172.236.20.118, git gives out the image I attached when you try go to the website.
![image](https://github.com/user-attachments/assets/175abeec-b9b3-4989-abf9-b63f21e9b271)

**Comment by bcoles** [comment]
> > The ip for the server is 172.236.20.118, git gives out the image I attached when you try go to the website.

Refer to your screenshot in the original post. The URL is provided. You may need to replace the host name with the IP address.

**Comment by stephenakq** [comment]
Removed references to ip address

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
