### ISSUE TITLE
Hook.js problem

### ISSUE THREAD

**Issue by MDHojayfa** [beefproject/beef#3184]
I got some problem in hooking browsers.
1. When i try to hook a browser with http://xxx:3000/hook.js it seems me
![Screenshot_20241026_235309](https://github.com/user-attachments/assets/d4cdecb2-293b-4198-9ee8-10f9567e2076)

2. When i execute create popup under it seems me created successful but when i move to another page that browser goes offline.
3. I used auto run commands, it seems me blank results 
![Screenshot_20241027_001022](https://github.com/user-attachments/assets/36adbe81-1002-400a-b918-571a104029df)
4. When i use https://ngrok:443/ui/panel i can't login there. Its all same to http://xxx:3000/ui/panel but i can login in http://xxx:3000/ui/panel but can't in https://ngrok:443/ui/panel. When i enter username and pass and press login ngrok page don't say anything and seems me that same page

I'll be very thankful if someone helps me to solve those problem.

Thank you.

**Comment by bcoles** [comment]
1. Correct
2. Was a popunder window created?
3. Does the command normally return results when not run using autorun?
4. Set `allow_reverse_proxy: true` - https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

**Comment by MDHojayfa** [comment]
> 1. But it don't hook the browser, i am using /butcher/index.html for hooking
> 2. Nope in Android but i didn't tryied in pc
> 3. Yeah.
> 4. Done but same problem. 

Uploading video_20241028_003507_edit.mp4…

![Screenshot_20241028_004009](https://github.com/user-attachments/assets/6aa3bada-72ce-4584-8291-507ef0047d2b)

**Comment by bcoles** [comment]
> > 1. But it don't hook the browser, i am using /butcher/index.html for hooking
> > 2. Nope in Android but i didn't tryied in pc
> > 3. Yeah.
> > 4. Done but same problem.
> 
> video_20241028_003507_edit.mp4
> 
> ![Screenshot_20241028_004009](https://private-user-images.githubusercontent.com/93394186/380525493-be64a15a-5dd4-4157-a465-aa1c28eda813.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNjg2MTQsIm5iZiI6MTczMDA2ODMxNCwicGF0aCI6Ii85MzM5NDE4Ni8zODA1MjU0OTMtYmU2NGExNWEtNWRkNC00MTU3LWE0NjUtYWExYzI4ZWRhODEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDIyMzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZGYzNGVmMDBlMTZhMzQzNDgyYmZjNWFiM2Y3ZGFmZDllMzIyM2M5NDcwNWQ0MDYzZTBkNmQ3NWVlMzQ5MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pYTSpBvLRy_kQCTvCUW7XJikQ7t5O1Y8YluxLycbbmk)

1. Correct. Try the demo page instead.
4. `true` not `false`

**Comment by MDHojayfa** [comment]
> 1. Correct. Try the demo page instead.
> 2. `true` not `false`

1.Oh. I used it. Its same.
2. Tnx.
3. What about popup under+ browser goes offline?
4. What about autorun commands seeing blank.

Here is the video of popup under error


Uploading lv_0_20241029005804.mp4…

**Comment by bcoles** [comment]
> 3. What about popup under+ browser goes offline?

If all hooked tabs/windows are closed the hook will be lost.

> 4. What about autorun commands seeing blank.

The `popunder_window` module should return at least one message to BeEF with `beef.net.send`:

https://github.com/beefproject/beef/blob/4b926dff44ec9951bc28776e251144d98f85473e/modules/persistence/popunder_window/command.js#L12-L22

**Comment by MDHojayfa** [comment]
> If all hooked tabs/windows are closed the hook will be lost.
> But this tab is not closed.  Watch my video here I have clearly given here when I moved from that page to another page in the same tab.  But still my connection is lost
> > 4. What about autorun commands seeing blank.
> but it still seems blank.

**Comment by bcoles** [comment]
>> If all hooked tabs/windows are closed the hook will be lost.

> But this tab is not closed. Watch my video here I have clearly given here when I moved from that page to another page in the same tab. But still my connection is lost

Same thing.

**Comment by MDHojayfa** [comment]
> > > If all hooked tabs/windows are closed the hook will be lost.
> 
> > But this tab is not closed. Watch my video here I have clearly given here when I moved from that page to another page in the same tab. But still my connection is lost
> 
> Same thing.

Bro but isn't there is any way to make my connection established with this tab or browser like when the browser gets close, it'll saw offline and as the browser opens, it'll automatically establish the connection.

Bonus Problem:
*When I hook a new browser it should show browser logo next to browser ip like if I hook google chrome browser it should show next to ip but it doesn't.*

![IMG_20241101_085301](https://github.com/user-attachments/assets/eed19a9f-6f25-4ce1-ab9b-790e1170a7e5)

**Comment by bcoles** [comment]
> Bro but isn't there is any way to make my connection established with this tab or browser like when the browser gets close, it'll saw offline and as the browser opens, it'll automatically establish the connection.

Persistence modules.

> Bonus Problem:
> When I hook a new browser it should show browser logo next to browser ip like if I hook google chrome browser it should show next to ip but it doesn't.

The browser type/version was not detected. The version may be too new. Update BeEF.

**Comment by MDHojayfa** [comment]
> > Bro but isn't there is any way to make my connection established with this tab or browser like when the browser gets close, it'll saw offline and as the browser opens, it'll automatically establish the connection.
> 
> Persistence modules.
I used it. Plz watch my video that i've sent before.
> > Bonus Problem:
> > When I hook a new browser it should show browser logo next to browser ip like if I hook google chrome browser it should show next to ip but it doesn't.
> 
> The browser type/version was not detected. The version may be too new. Update BeEF.

How?

**Comment by bcoles** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc

**Comment by MDHojayfa** [comment]
No ones replying. I msged in general. Come there.
