### ISSUE TITLE
Refresh beef Discord channel

### ISSUE THREAD

**Issue by zinduolis** [beefproject/beef#3187]
- Give a more fresh look with emojies next to groups and channels;
- Add automation for greeting and rules.
- Implement rules for people to see history just from when they join server.

**Comment by zinduolis** [comment]
Emojies added.

**Comment by stephenakq** [comment]
@zinduolis  has this been completed?

**Comment by zinduolis** [comment]
Added rules, looking into bringing MEE6 bot.
