### ISSUE TITLE
unable to locate

### ISSUE THREAD

**Issue by windyworldair** [beefproject/beef#3199]
so i was downloading beef xss opened install file with msys2 
![image](https://github.com/user-attachments/assets/f82b0f02-7e02-4b79-b96a-6722b8ed9d09)
 and this happened how to fix?

**Comment by windyworldair** [comment]
i am using windows 10  18363.418

**Comment by windyworldair** [comment]
i have everything installed is unable to locate the installer i dont know why.
i installed ruby everything needed

**Comment by bcoles** [comment]
Windows is not supported.

**Comment by windyworldair** [comment]
IT DOESNT SAY THAT THOUGH IT SAYS USE CHOCO MANAGER IF ON WINDOWS  
IF IT WAS NOT SUPPORTED IT WOULD SAY THAT IS NOT SUPPORTED

**Comment by windyworldair** [comment]
> Windows is not supported.

it said to use choco manager and use ruby if on windows wouldnt it say windows genius

**Comment by windyworldair** [comment]
BCOLES IT  WOULD SAY NOT SUPPORTED IF IT WAS NOT SUPPORTED PLEASE TELL HOW TO FIX

**Comment by bcoles** [comment]
> BCOLES IT WOULD SAY NOT SUPPORTED IF IT WAS NOT SUPPORTED PLEASE TELL HOW TO FIX

BeEF does not support Windows. Linux is recommended.

Some users have had success with running BeEF on WSL within Windows.

If you want to try running BeEF natively on Windows you are on your own. You will need to install Ruby, the `bundler` gem, and the required Ruby gems with `bundle install`. You will also NodeJS.
