### ISSUE TITLE
Beef Panel Issue with logging in.

### ISSUE THREAD

**Issue by Lemon7181** [beefproject/beef#3200]
I have followed all the steps to make a beef server and i have copied my server link and pasted it into my browser it says 
Username: 
Password:
And on the youtube videos i have been following they all use the username "beef" so i tried that and tried the password i used but it says incorrect but it is not incorrect because it works when i login using command prompt.

**Comment by bcoles** [comment]
The username and password are in the `config.yaml` configuration file. Refer to https://github.com/beefproject/beef/wiki/Configuration#credentials

If you are using ngrok, refer to https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

**Comment by Lemon7181** [comment]
Im Just very confused.

**Comment by Lemon7181** [comment]
I have done all the steps correctly it is just this part which is not making any sense.

**Comment by bcoles** [comment]
You must restart BeEF after modifying the configuration file.

**Comment by Lemon7181** [comment]
Im sorry im very lost here Where do i modify the configuration file and when you say "restart" do you mean reboot?

**Comment by bcoles** [comment]
> Im sorry im very lost here Where do i modify the configuration file

The username and password are in the `config.yaml` configuration file. Refer to https://github.com/beefproject/beef/wiki/Configuration#credentials

If you are using ngrok, refer to https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

> when you say "restart" do you mean reboot?

BeEF will load the configuration file when it is started.

**Comment by Lemon7181** [comment]
im using the user: beef and the pass: beef and it still is not working and i do not know how to change it and i do not know how to do the config file stuff and i can not do stuff in cmd prompt because it says: "No such file or directory"

**Comment by bcoles** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
