### ISSUE TITLE
Login won't work

### ISSUE THREAD

**Issue by jonc1987** [beefproject/beef#3212]
When I type in the right credentials it will just reload and not log me in.

**Comment by bcoles** [comment]
The username and password are in the `config.yaml` configuration file. Refer to https://github.com/beefproject/beef/wiki/Configuration#credentials

If you are using ngrok, refer to https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
