### ISSUE TITLE
Forbidden 403 (https://rubygems.org/gems/sqlite3-2.2.0-x86_64-linux.gem

### ISSUE THREAD

**Issue by blip-beep** [beefproject/beef#3216]
I'm doing a completely new installation of beef, downloaded it a couple of days ago.

All gems are fine except this one.
I also notice the is no gem called "sqlite3-2.2.0-x86_64-linux.gem"

Should it be: sqlite3-2.2.0-x86-linux-gnu.gem

[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 3.1.2 is installed
[INFO]  Detecting bundler gem...
[INFO]  bundler gem is installed
Installing required Ruby gems...
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching sqlite3 2.2.0 (x86_64-linux)

Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/sqlite3-2.2.0-x86_64-linux.gem)

Retrying download gem from https://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/sqlite3-2.2.0-x86_64-linux.gem)

Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/sqlite3-2.2.0-x86_64-linux.gem)

Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to underlying error <bad response Forbidden 403 (https://rubygems.org/gems/sqlite3-2.2.0-x86_64-linux.gem)>
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/rubygems_integration.rb:410:in `rescue in download_gem'                                                                                         
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/rubygems_integration.rb:385:in `download_gem'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/source/rubygems.rb:479:in `download_gem'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/source/rubygems.rb:436:in `fetch_gem'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/source/rubygems.rb:420:in `fetch_gem_if_possible'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/source/rubygems.rb:162:in `install'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/installer/gem_installer.rb:55:in `install'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/installer/gem_installer.rb:17:in `install_from_spec'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/installer/parallel_installer.rb:133:in `do_install'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/installer/parallel_installer.rb:124:in `block in worker_pool'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.1.0/gems/bundler-2.5.23/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing sqlite3 (2.2.0), and Bundler cannot continue.

In Gemfile:
  sqlite3

**Comment by blip-beep** [comment]
Installing on:
Linux kali 6.11.2-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.11.2-1kali1 (2024-10-15) x86_64 GNU/Linux

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
