### ISSUE TITLE
Add IPv6 Support

### ISSUE THREAD

**Issue by passbe** [beefproject/beef#519]
Update the framework to work with IPv6
<br><br><em>Google Code Issue: http://code.google.com/p/beef/issues/detail?id=142</em>

**Comment by bcoles** [comment]
#1672

**Comment by bcoles** [comment]
#1265

**Comment by wheatley** [comment]
![image](https://user-images.githubusercontent.com/689558/140927208-3410d702-22f0-439e-84a5-e75156ec7ca4.png)

**Comment by wheatley** [comment]
@bcoles it looks like you're correct, it can just work.
next test would be use an assigned ipv6 address

**Comment by bcoles** [comment]
> @bcoles it looks like you're correct, it can just work.

I was suggesting that BeEF should "just work" as a goal, not that BeEF will work with IPv6.

There are many baked-in assumptions about IPv4 in the code base that will need to be reviewed.
