### ISSUE TITLE
Decouple: admin_ui extension from main config.yaml

### ISSUE THREAD

**Issue by passbe** [beefproject/beef#565]
The configuration for the admin_ui is currently coupled with the main config in the trunk. Move all the admin_ui extension configuration settings from the ./config.yaml to the config for the admin_ui.

The setting that will need to be moved from the ./config.yaml is
demo_path: &quot;/demos/basic.html&quot;<br><br><em>Google Code Issue: http://code.google.com/p/beef/issues/detail?id=448</em>

**Comment by bcoles** [comment]
Fixed, and then removed, as the `demo_path` isn't used.
