### ISSUE TITLE
Create obfuscation interface

### ISSUE THREAD

**Issue by wadealcorn** [beefproject/beef#589]
Move the current functionality into an obfuscation extension and ensure the framework is still fully functional. Of course, this will need to work with the unit tests. 

The session id needs to controlled by the extension code. This might be custom to each extension.

Please refer to the network stack diagram.

**Comment by lussybaver** [comment]
Hi
I am trued evasion in config.yaml to obfuscated hook.js because bay pass google bot.
but refund hook site reported via googlebot.
help me how to bypass googlebot from hook.js page.
thanks
