### ISSUE TITLE
Modify all HTTP handlers to use the new Router class

### ISSUE THREAD

**Issue by antisnatchor** [beefproject/beef#654]
The new Router class, that extend Sinatra::Base (core/main/router/router.rb)
will be the parent class for all the HTTP handlers (both core like /dh, /hook,js, and extensions)
in BeEF.

This will facilitate writing custom extensions that don't use the DH, or that requires advanced settings.

**Comment by bcoles** [comment]
Demos extension modified to use the Router class in #2795.

**Comment by bcoles** [comment]
The DynamicReconstruction handler could do with a review. Regardless, it probably makes sense to use the DH when returning data to BeEF. For example, the Event Logger probably should share the `/dh` stream, rather than returning events to a separate `/events` route. Maybe?
