### ISSUE TITLE
Command Tree never logs

### ISSUE THREAD

**Issue by rmnieto** [beefproject/beef#655]
I´ve installed BeEF 0.4.3.3-alpha (with DevKit-tdm-32-4.5.2-2011).
I login in the http://host:3000/ui/panel and when I click the "Commands" tab shows a "Please wait, command tree is loading ..." that never finish to load. There´s a way to see a log for the /ui/panel to know the error?

**Comment by richardweiu** [comment]
I can open it,but I get this issue when I change the metasploit config from false to true
