### ISSUE TITLE
FullScreen Attack 

### ISSUE THREAD

**Issue by n0x00** [beefproject/beef#702]
I have been trying to code this but im terrible with Actionscript, consider this 

the full screen executes the user is told to hit escape to escape fullscreen and as that message fades a Blue Screen of Death flickers and your logged out. you should log back in, BSoD! crap! is my work safe ?!

what just happened was the swf/(and beef?) have made an educated guess on your OS and loaded the images to satisfy a identical log in screen for your operating system. the username and password are POSTed back to the attacker/beef

I'm not sure if it could go as far as getting the username but that would be great too

if the attack is successful you will obtain the current users credentials to further your attack - and the AV doesn't need know about any of this as it's just asking you to submit your user and password 

As I said before I'm terrible at Actionscript, but I know that swf will do a nice fullscreen might be nice to deploy as an exe too(or .app depending on how good the fingerprinting can get) - and using educated guesses on default user icon's etc.

I'd love to see this, would you ?

John

**Comment by bcoles** [comment]
@xntrik ping
