### ISSUE TITLE
Feature request: Delete from offline browsers

### ISSUE THREAD

**Issue by Viss** [beefproject/beef#762]
After a lengthy campaign, I have some entries in the list that are no longer relevant and I would like the ability to do something like check a box and hit delete, or rightclick and delete from the offline browsers. Without the ability to do this the left pane will get untenable after several large campaigns.

**Comment by bcoles** [comment]
I've added a REST API example script to remove all offline browsers.

```
# cd tools/rest_api_examples
# ./remove-offline-browsers --user beef --pass secret
[*] Authenticating to: http://127.0.0.1:3000
[+] Retrieved RESTful API token: b6000c4054516a653a1cdf31881eeca5b6b4825b
[+] Retrieved BeEF version: 0.4.7.0-alpha
[+] Retrieved offline browser list [1 offline]
[*] Removing hooked browser [id: 5]
[+] Removed browser [session: rvBlzx5CdGmWWVVZw1lYbyXHMec2hvyq4VMONw4b5OhJX2hkP41Ses5p6ExiAk2u0cKHrVtdaB5foCRs]
```

Use  `./remove-offline-browsers --help` for help.

**Comment by okazepis** [comment]
@bcoles I open the beef.db and I delete manually the zombie. I delete it from table _hooked_browsers_ Do I need to delete something else?

I noticed that you cannot delete zombie from offline browsers ( I tried to delete it, refresh, logout/in. I reported here in order not to open new issue.
