### ISSUE TITLE
Add stack for ARE modules

### ISSUE THREAD

**Issue by qswain2** [beefproject/beef#795]
Add a new stack similar to the commands stack in the client that will be used for specifying commands sent to the ARE for execution.

I think we can create in beef.js a new Array object, similar to the 'commands' stack we already have and use,
which will be called something like 'are_chain'. This stack will work in the same way as the 'commands' structure.

We'll also add, again into beef.js, a new method called 'are_execute', which will be the same as the 'execute' wrapper
we currently use to wrap modules javascript logic:

execute: function(fn) {
            if ( typeof  beef.websocket == "undefined"){
                 this.commands.push(fn);
            }else{
                fn();
            }
        },

In this way, we can differentiate which data is arriving to the client, and needs to be executed by ARE or as simple command modules.

**Comment by jcrew99** [comment]
This is a duplicate issue
