### ISSUE TITLE
Explain how to install BeEF on Windows

### ISSUE THREAD

**Issue by ghost** [beefproject/beef#805]
Is there anybody using BeEF on Windows ?

If yes, it would be great to write documentation [here](https://github.com/beefproject/beef/wiki/Installation), otherwise we can remove this part of the documentation or write clearly that BeEF is not supported on Windows.

What do you think ?

**Comment by Filipposcmd** [comment]
Thanks gyus!!!

**Comment by MayorWolf0207** [comment]
> Anyway on Windows, a friend of mine wrote nice docs based on screenshots something like 1 year ago. http://code.google.com/p/beef/wiki/WindowsInstall
> 
> We should just move the content here on github.

Can you pls give me premision so I can download?

**Comment by bcoles** [comment]
> > Anyway on Windows, a friend of mine wrote nice docs based on screenshots something like 1 year ago. http://code.google.com/p/beef/wiki/WindowsInstall
> > We should just move the content here on github.
> 
> Can you pls give me premision so I can download?

Those instructions are 10 years old.

This should get you most of the way there: install Ruby, install Rubygems, install NodeJS, `gem install bundle`, `bundle install`.

No further guidance will be provided. Windows is not supported.

**Comment by stephenakq** [comment]
You won't get support on Windows @MayorWolf0207. However, someone on Discord might be able to help with the other install types https://discord.gg/ugmKmHarKc
