### ISSUE TITLE
Integrate with Travis-CI?

### ISSUE THREAD

**Issue by claudijd** [beefproject/beef#850]
Hey guys,

I use travis-ci for testing some of my Ruby projects to make sure all my unit tests pass all the time, including any new pull requests to my projects.  Yesterday, I thought this might be a good thing for the beef project (not sure if you use some other build/ci solution), so I forked it and started playing around to see if I could suggest a config that you guys might consider.

Long story short, I didn't realize some of heavy system integration you guys have (as well as all the msf ties) and I figured if I was going to suggest any major changes or make a pull for this I should ask before spending anymore time on it to see if it's something you'd be interested in.

Thanks,

@claudijd

**Comment by bcoles** [comment]
FWIW I'm using Travis-CI for the unit tests. The logs are here: https://travis-ci.org/bcoles-travis/beef
