### ISSUE TITLE
Solution: Hide beef behind an apache webserver

### ISSUE THREAD

**Issue by lalaglubsch** [beefproject/beef#856]
Hi developers.

I installed beef to be "hidden" behind a apache proxy (mod-rewrite config on request) for my demo-system. There were some difficulites:
a) the hook-script ignored beef_public
b) the client IP was hidden by the proxy ;-)

I resolved these issues by:
a) corrected the beefjs.rb
b) addad a new config option: use_x_forwarded_for: [true|false] and added new code to hookedbrowsers.rb

Below is the diff. I hope you find it useful.

Cu,

Chris

---snip---

<pre>
diff --git a/core/main/handlers/hookedbrowsers.rb b/core/main/handlers/hookedbrowsers.rb
index 1236dec..d352044 100644
--- a/core/main/handlers/hookedbrowsers.rb
+++ b/core/main/handlers/hookedbrowsers.rb
@@ -55,9 +55,16 @@ module Handlers
         hooked_browser.lastseen = Time.new.to_i
         
         # @note Check for a change in zombie IP and log an event
-        if hooked_browser.ip != request.ip
-          BeEF::Core::Logger.instance.register('Zombie',"IP address has changed from #{hooked_browser.ip} to #{request.ip}","#{hooked_browser.id}")
-          hooked_browser.ip = request.ip
+       if config.get('beef.http.use_x_forward_for') == true
+          if hooked_browser.ip != request.env["HTTP_X_FORWARDED_FOR"]
+            BeEF::Core::Logger.instance.register('Zombie',"IP address has changed from #{hooked_browser.ip} to #{request.env["HTTP_X_FORWARDED_FOR"]}","#{hook
+            hooked_browser.ip = request.env["HTTP_X_FORWARDED_FOR"]
+          end
+        else
+          if hooked_browser.ip != request.ip
+            BeEF::Core::Logger.instance.register('Zombie',"IP address has changed from #{hooked_browser.ip} to #{request.ip}","#{hooked_browser.id}")
+            hooked_browser.ip = request.ip
+          end
         end
       
         hooked_browser.count!
diff --git a/core/main/handlers/modules/beefjs.rb b/core/main/handlers/modules/beefjs.rb
index f120f78..1f43418 100644
--- a/core/main/handlers/modules/beefjs.rb
+++ b/core/main/handlers/modules/beefjs.rb
@@ -66,6 +66,12 @@ module BeEF
             hook_session_config = BeEF::Core::Server.instance.to_h
 
             # @note if http_host="0.0.0.0" in config ini, use the host requested by client
+            unless hook_session_config['beef_public'].nil?
+              if hook_session_config['beef_host'] != hook_session_config['beef_public']
+                hook_session_config['beef_host'] = hook_session_config['beef_public']
+                hook_session_config['beef_url'].sub!(/#{hook_session_config['beef_host']}/, hook_session_config['beef_public'])
+              end
+            end
             if hook_session_config['beef_host'].eql? "0.0.0.0"
               hook_session_config['beef_host'] = req_host
               hook_session_config['beef_url'].sub!(/0\.0\.0\.0/, req_host)
</pre>

---snap---

**Comment by badbob** [comment]
Thanks a lot for your commit. 
Here is an example configuration for Nginx:

```
       location = /hook.js {
                proxy_pass   http://localhost:3003;
                proxy_set_header  Host       $host;
                proxy_set_header  X-Forwarded-For  $remote_addr;
        }

        location = /dh {
                proxy_pass   http://localhost:3003;
                proxy_set_header  Host       $host;
                proxy_set_header  X-Forwarded-For  $remote_addr;
        }
```
