### ISSUE TITLE
Default password

### ISSUE THREAD

**Issue by simaster99** [beefproject/beef#913]
Hi has the default password for http://localhost:3000/ui/authentication changed from beef / beef? 

as i get invalid username and password.

many thanks

**Comment by Hunter3173** [comment]
Dans le fichier de configuration "config.yaml" de beef, modifier dans la partiie permitted_ui avec votre adresse réseau et non 127.0.0.1

**Comment by simonm3** [comment]
I also have this issue. It was working fine then suddenly would not work. Have checked the config file and it still says beef/beef

**Comment by alexlaxu** [comment]
try
username:beef
password:beef

**Comment by ankitsaini2609** [comment]
It's happen because another service is listening on that port(3000). To solve this try
1) netstat -lntup (it will show you services along with the ports which they are using, check which service is running on 3000 port and note it's pid).
2) kill pid (pid = process id that you have noted).
3) restart beef.
Done!!

**Comment by mwindaji** [comment]
stop if started; start beef with -c <path+config.yaml>

look at the config.yaml => probably beef + feeb as password.

**Comment by rechandra** [comment]
Go to your beef-xss directory and run ./beef from terminal you can get new password each session you create below message
[17:36:11][!] Warning: Default username and weak password in use!
[17:36:11]    |_  New password for this instance : Blablabla~

**Comment by Masterdroyd** [comment]
Sorry what is the password default

**Comment by rechandra** [comment]
beef

**Comment by hledger** [comment]
Running the beef with Sudo solved for the issue for me.

**Comment by mbviruy** [comment]
beef credentials
uname=beef
password=beef

**Comment by kaegeh** [comment]
May i seek guidance? I am experimenting with BeEF. I have changed my credentials and i still get error:incorrect username or password. I've actually looked at multiple of your suggestiongs @bcoles , i am completely stumped. Can i ask for some help?

**Comment by thecowmilk** [comment]
Hello, I have having a similiar problem, when I launch beef it says that I'm using "Default Credentials" and is asking me to change the password.

**Comment by Mineck96** [comment]
What are the default username and password for BeEF?? I've used beef as username and password but i've failed :(

**Comment by bcoles** [comment]
> 
> 
> What are the default username and password for BeEF?? I've used beef as username and password but i've failed :(

The username and password are specified in the BeEF configuration file `config.yaml`.

**Comment by Hunter3173** [comment]
> Dans le fichier de configuration "config.yaml" de beef, modifier dans la partiie permitted_ui configurez cette patie avec votre adresse réseau et non 127.0.0.1

Dans le fichier de configuration "config.yaml" de beef, modifier dans la partiie permitted_ui configurez cette partie avec votre adresse réseau et non 127.0.0.1
In the configuration file "config.yaml" of beef, change the part permitted_ui  configure this part with your network address and not 127.0.0.1

**Comment by Rethick11** [comment]
first: go to the beef-xss dircetory
second: type ls in terminal 
third: type leafpad config.yaml 
 then change your password to anythig 


  -------------Thank you-----------------

**Comment by camillegroult** [comment]
> Hi has the default password for http://localhost:3000/ui/authentication changed from beef / beef?
> 
> as i get invalid username and password.
> 
> many thanks

Try this bro (B in MAJ) please let me know !!!

# Credentials to authenticate in BeEF.
# Used by both the RESTful API and the Admin interface
    credentials:
        user:   "Beef"
        passwd: "Beef"

**Comment by Mr-White-007** [comment]
default pass could be. :
user : beef
pass : beef
 second loging 
user : beef 
pass : toor

**Comment by minhaz8399** [comment]
How to edit beef-xss default password

**Comment by bcoles** [comment]
> 
> 
> How to edit beef-xss default password

The password is set in the `config.yaml` configuration file.

Upon successful installation, be sure to read the [Configuration](https://github.com/beefproject/beef/wiki/Configuration) page on the wiki for important details on configuring and securing BeEF.

**Comment by Darkcast** [comment]
Hey guys I have a question 
is there a way to add multiple users?
i tried 

    credentials:
        user:   "user1" 
        passwd: "something unique and complex"
        
        user:   "user2" 
        passwd: "something unique and complex"
and it didnt work. is this even possible ?


thank you

**Comment by khelv** [comment]
I used this to solve mine... simply change the password to something else

< nano config.yaml >
username: "beef"
password:"beefs"

ctrl O and enter key to save
ctrl X to exit 

You can run your beef now with ./beef

**Comment by dibbasey40** [comment]
> Go to your beef-xss directory and run ./beef from terminal you can get new password each session you create below message [17:36:11][!] Warning: Default username and weak password in use! [17:36:11] |_ New password for this instance : Blablabla~

thanks,
 this one works for me

**Comment by chuckcarne** [comment]
what is the link to log into beef?
Plz don't beef me.

**Comment by bcoles** [comment]
> what is the link to log into beef?

BeEF prints the URLs to during startup. BeEF also listens on all interfaces by default, so you can simply use the loopback interface.

```
http://127.0.0.1:3000/ui/panel
```

**Comment by chuckcarne** [comment]
Oh thanks

**Comment by chuckcarne** [comment]
I'm having an issue logging into beef. It worked before but it doesn't anymore after a reinstall. I have changed the password and username but it's not working anymore. Does anyone have any ideas?

**Comment by yntkts555** [comment]
I have changed the username and password in the config.yml folder, but when I enter the beef website, it's still wrong, how is this

**Comment by bcoles** [comment]
> I have changed the username and password in the config.yml folder, but when I enter the beef website, it's still wrong, how is this

This issue is 9 years old.

This issue is closed.

If you have an please create a [new issue](https://github.com/beefproject/beef/issues/new/choose) and be sure to complete the issue template, including more information than "not working" .
