### ISSUE TITLE
Where is hook.js?

### ISSUE THREAD

**Issue by resetter** [beefproject/beef#978]
Hi.
Just noticed that Norton360 is picking up the hook.js, so I wanted to find it and obfuscate it, but I can't seem to find the file. Where is it stored in Kali?

**Comment by freeartde** [comment]
http://your__ip:3000/hook.js
type it in your brownser and the code will be appears in your screen
copy paste and recode..

**Comment by Makveli** [comment]
Got It.  /home//beef/extensions/customhook

**Comment by Makveli** [comment]
open config.yaml in that folder and put in custome hook.js location
