### ISSUE TITLE
Problem with web_ui_auth.js" on kali

### ISSUE THREAD

**Issue by morfeuski** [beefproject/beef#979]
Hi,
I have problem with beef on kali linux. There is no file web_ui_auth.js" in /usr/share/beef-xss/extensions/admin_ui/media/javascript-min so I cant login in app. I already tried on 6 computers and all with same issue. It starts this week,maybe some new version has been added to kali repository.
root@pc105:/usr/share/beef-xss/extensions/admin_ui/media/javascript-min# ls
readme
Maybe there is some script,which I should run to generate web_ui_auth.js.
Please,can you help me.
Thank you
Paul

**Comment by CalfCrusher** [comment]
Same problem still in 2022 lol

**Comment by bcoles** [comment]
> Same problem still in 2022 lol

Have you installed nodejs? Is it in `$PATH` ? Do you have any errors in termainl?

**Comment by bcoles** [comment]
> Same problem still in 2022 lol

Different bug. This has been fixed. The patch should be available once you `git pull`.

**Comment by CalfCrusher** [comment]
Yea, that's the usual ruby problem. Anyway using beef-xss package shipped with Kali all seems to work, i'm unable to reach the ui/panel from localhost but i can access it from 192.168 class...dunno why. Anyway i see that beef is still mantained, that's very good. Keep it rock, thanks
